### ISSUE TITLE
Pass params into where with kwargs.

### ISSUE THREAD

**Issue by alexpantyukhin** [coleifer/peewee#1015]
Hi. Sometimes it's very useful to pass a collection of parameters with `kwargs` into the `where` clause.
What if to add some kind of function like `q(class, **kwargs)` into playhouse which gets params and translate it on expressions which are already used in the peewee.
(Not sure if such function already exists). Or maybe create another method like `where_by` likes it's done in SQLAlchemy.

**Comment by coleifer** [comment]
Actually, this functionality does exist, but is currently marked as deprecated and no longer documented. You can view the docs [on the 2.0.2 build](http://docs.peewee-orm.com/en/2.0.2/peewee/querying.html#SelectQuery.filter), however.

If you use the alternative `filter()` API, you can use Django-style kwargs lookups:

```python
# Works pretty much like you expect:
active = User.filter(active=True)
some_users = active.filter(username__in=('charlie', 'huey', 'zaizee'))

# You can do "OR" using `DQ`:
editors = User.filter(DQ(is_admin=True) | DQ(is_staff=True))
```
