### ISSUE TITLE
pwiz columns invalid names

### ISSUE THREAD

**Issue by vinczente** [coleifer/peewee#1022]
in mysql fields can be named:
"source id"
"marketing/position"
in this case pwiz creates python model attributes of the same name.
Related issue:  https://github.com/coleifer/peewee/issues/184

**Comment by coleifer** [comment]
Hmmm....

**Comment by coleifer** [comment]
Can you explain this in a bit more detail? What exactly is the nature of this bug?

**Comment by vinczente** [comment]
This is a example of generated code from pwiz

class Flag(BaseModel):
    description = TextField(null=True)
    flag id = CharField(null=True)
    name = CharField(null=True)

python will syntax error:

    flag id = CharField(null=True)
          ^
SyntaxError: invalid syntax

**Comment by vinczente** [comment]
Solution could be to escape the fields name and use a db_column property

flag_id = CharField(db_column='flag id', null=True)
