### ISSUE TITLE
PostgresqlDatabase class does not have `_upsert` statement

### ISSUE THREAD

**Issue by cheetah90** [coleifer/peewee#1023]
Looking at the [PostgresqlDatabase class](https://github.com/coleifer/peewee/blob/b84ca0c8bc724b8cccd0b5bbd557abc04885c478/peewee.py#L3945), it does not specify the statement for `_upsert`, so when [`query._upsert` is called here](https://github.com/coleifer/peewee/blob/b84ca0c8bc724b8cccd0b5bbd557abc04885c478/peewee.py#L1982) , it just return `None`.

**Comment by cheetah90** [comment]
Follow-up, Postgresql has implemented `UPSERT` in version > 9.5. [See here](https://wiki.postgresql.org/wiki/UPSERT)

**Comment by coleifer** [comment]
@cheetah90 -- there are two issues currently open tracking this exact thing:

* #942 
* #853
