### ISSUE TITLE
Add support for PostgreSQL geometric types

### ISSUE THREAD

**Issue by ilmerovingio** [coleifer/peewee#1026]
I'm opening this issue (as suggested in the [docs](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#postgresql-extensions)) to keep track of PostgreSQL [geometric type](https://www.postgresql.org/docs/current/static/datatype-geometric.html) support

**Comment by yohanboniface** [comment]
See an example of custom field for that here https://github.com/BaseAdresseNationale/ban/blob/master/ban/db/fields.py#L33

**Comment by coleifer** [comment]
While I personally have no intentions of implementing fields for those data-types, I would merge a pull-request that added support in the `playhouse.postgres_ext` module. On a personal note, I stopped using Postgres about 2 years ago and I haven't looked back, so new features to the `postgres_ext` extension are going to need to have either 1) strong interest from the community, 2) patches submitted by an ambitious contributor, or 3) a feeling that the presence of a particular feature will be important to users in evaluating whether or not to use Peewee. This last one was the case for both `jsonb` and `tsvector` (full-text search). Geometry fields just don't have the same panache, I guess :) .

I'm going to close this for now, but if you have any additional thoughts on the matter please leave a comment. Thanks!
