### ISSUE TITLE
Issue with using percent sign

### ISSUE THREAD

**Issue by bitnic028** [coleifer/peewee#1033]
A code like this
```
>>> from application.db.models import db
>>> query = 'SELECT 12 % 5;'
>>> res = db.execute_sql(query)
```
is crashing
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IndexError: tuple index out of range
```
Certainly, in this case percent sign should replace by `mod()` function.

**Comment by coleifer** [comment]
What database are you using?

**Comment by bitnic028** [comment]
Posgtrsql.

**Comment by coleifer** [comment]
This is a quirk of `psycopg2`, which apparently treats "%" as placeholders. This StackOverflow question deals with the exact same issue:

http://stackoverflow.com/questions/14054920/psycopg2-indexerror-tuple-index-out-of-range-error-when-using-like-operat

To escape the percent sign, just use "%%":

```python
In [5]: db.execute_sql('SELECT 12 %% 5;').fetchall()
Out[5]: [(2,)]
```
