### ISSUE TITLE
peewee support multi process mode ? 

### ISSUE THREAD

**Issue by rfyiamcool** [coleifer/peewee#1036]
peewee support multi process mode ?    How to create a connection dynamically?

**Comment by coleifer** [comment]
Could you please be specific? What do you mean by "dynamically"? Honestly, please try to explain things so I can understand exactly what you're talking about, otherwise you are wasting both of our time.

**Comment by coleifer** [comment]
Database connections are not shared across multiple Python interpreter processes. Peewee, by default, uses thread-locals to manage connection state, so database connections are not even shared across threads (though you can disable this). Using the standard APIs, there will typically be one connection open per thread. If you want to explicitly create a second connection, you can use the 

Here are some relevant sections of documentation based on my best guess as to what you were asking:

* http://docs.peewee-orm.com/en/latest/peewee/database.html#multi-threaded-applications
* http://docs.peewee-orm.com/en/latest/peewee/database.html#advanced-connection-management
* http://charlesleifer.com/blog/managing-database-connections-with-peewee/ (a blog post I wrote on connection management with peewee)

To quote from the second link:

> In some situations, however, you may want to manage your connections more explicitly. Since peewee stores the active connection in a threadlocal, this typically would mean that there could only ever be one connection open per thread. For most applications this is desirable, but if you would like to manually manage multiple connections you can create an ExecutionContext.

> Execution contexts allow finer-grained control over managing multiple connections to the database. When an execution context is initialized (either as a context manager or as a decorated function), a separate connection will be used for the duration of the wrapped block. You can also choose whether to wrap the block in a transaction.

If none of this information helped answer your question, please comment with more information.
