### ISSUE TITLE
Use six library

### ISSUE THREAD

**Issue by thomdixon** [coleifer/peewee#1038]
You should use the wonderful [`six`](https://pythonhosted.org/six/) library, which would make a lot of [this](https://github.com/coleifer/peewee/blob/master/peewee.py#L118) unnecessary (especially the [`exec` for `reraise`](https://github.com/coleifer/peewee/blob/master/peewee.py#L143)).

**Comment by coleifer** [comment]
In my opinion, the `six` library is silly and I don't want to add a useless dependency.
