### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by lyssdod** [coleifer/peewee#1039]
http://docs.peewee-orm.com/en/latest/peewee/database.html?highlight=sqlite#pragma-statements

Here it says "To run one or more PRAGMA statements against new connections, you can specify them as a list of 2-tuples... " but the code coming afterwards utilizes a tuple instead of list:

```
pragmas=(
    ('journal_mode', 'WAL'),
    ('cache_size', 10000),
    ('mmap_size', 1024 * 1024 * 32),
)
```

I've just experienced this myself, getting this error:
```
  File "/usr/lib64/python2.7/site-packages/peewee.py", line 3627, in _set_pragmas
    for pragma, value in self._pragmas:
ValueError: too many values to unpack
``` 

unless I tried to substitute `pragmas = (...)` to `pragmas = [...]`

**Comment by coleifer** [comment]
You can specify them as a list or a tuple, so I will update the documentation to that effect.

I'm guessing you ran into the error because you were only specifying one `PRAGMA` and forgot the trailing comma Python requires to differentiate simple parentheses from a tuple declaration.

**Comment by lyssdod** [comment]
Exactly, I was specifying one `PRAGMA` and forgot the comma. Thanks!
