### ISSUE TITLE
Peewee install is broken on PyPy

### ISSUE THREAD

**Issue by scitesy** [coleifer/peewee#1041]
Ubuntu 16.04
PyPy pypy2-v5.3.1-linux64

Both pip install peewee and python setup.py install from a virtualenv fail with the following terminal output: https://gist.github.com/scitesy/550fa086870c7d90ae138b8f7e209e1c

I believe it has been broken since sometime around July 14th.

**Comment by coleifer** [comment]
Interesting. Do you have Cython installed alongside Peewee by chance? If not it's using the C source files bundled with Peewee, which appear not to be compatible.

**Comment by coleifer** [comment]
I've reverted a particular commit and pushed the changes to `master`... Do you mind trying them out?

Should be:
```
pip install -e git+https://github.com/coleifer/peewee.git#egg=peewee
```

**Comment by scitesy** [comment]
Thank you. I'll try it again later tonight.

**Comment by scitesy** [comment]
That worked! To answer the question from earlier, I am running PyPy with no Cython installed.
The terminal output:
Obtaining peewee from git+https://github.com/coleifer/peewee.git#egg=peewee
  Cloning https://github.com/coleifer/peewee.git to ./test_pypy_peewee/src/peewee
Installing collected packages: peewee
  Running setup.py develop for peewee
Successfully installed peewee

Thank you!

**Comment by coleifer** [comment]
I'll issue a new release to pypi later today.

**Comment by ParthGandhi** [comment]
@coleifer When do you think this will be released? Thanks!
