### ISSUE TITLE
GFKField with custom field names?

### ISSUE THREAD

**Issue by bcthomas** [coleifer/peewee#1042]
I have a legacy Rails database that I'm writing a peewee wrapper around.  The Rails db uses a polymorphic/GFK for a "note".  I'm trying to use peewee GFKs, but the SQL it's using to find a note is using the lowercase name of the table for the associated model, but the value in the db is the actual class name.

For example, "Feature" is in the db resource_type column, but peewee is using a select query with "features".

```SQL
SELECT `t1`.`id`, `t1`.`value`, `t1`.`resource_id`, `t1`.`resource_type`
 FROM `notes` AS t1 WHERE ((`t1`.`resource_type` = %s)
 AND (`t1`.`resource_id` = %s)) ['features', 59]
```

Is there a way to customize this?

Thanks

**Comment by coleifer** [comment]
Unfortunately, the GFK field was never intended to interact with Rails. Perhaps you can add extra column(s) to the table to support the Peewee version of the data, or write a custom field that uses the names you need.

**Comment by bcthomas** [comment]
I figured this was the case.  Modifying the table is a great idea and probably the least work.

Thanks @coleifer !
