### ISSUE TITLE
Entity is dirty after loading from DB (peewee==2.8.2)

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/peewee#1043]
```python
from peewee import Model, SqliteDatabase, CharField

db = SqliteDatabase('test.db')

class Foobar(Model):
    field = CharField()

    class Meta:
        database = db
        only_save_dirty = True

db.connect()
db.create_tables([Foobar])

obj1 = Foobar.create(field='foobar')

foo = Foobar.get(id=obj1.id)
print(foo._dirty)

foo.save()  # should do nothing but actually hits db because fields are marked dirty
```

Output:

    {'id', 'field'}

With 2.8.1 `_dirty` is an empty set instead.

**Comment by coleifer** [comment]
I checked out 2.8.1 and was seeing that the instance from the db was dirty...nonetheless it looks like a bug.

**Comment by tuukkamustonen** [comment]
Weird, I tried again (in a clean virtualenv) and with peewee==2.8.1 `_dirty` is indeed an empty `set()`. Sounds a bit weird if the result is different in your sandbox.

Well, thanks for the bugfix anyway.

**Comment by coleifer** [comment]
I did not update PyPI (that would entail pushing a new release, 2.8.2). If you point at master branch on github you should see the fix:

```
pip install -e git+https://github.com/coleifer/peewee#egg=peewee
```

**Comment by tuukkamustonen** [comment]
That doesn't play together with an in-house pypi (devpi) so I'll just wait for 2.8.3 as 2.8.1 works just fine for me.
