### ISSUE TITLE
column names are stripped their '_id' part

### ISSUE THREAD

**Issue by maxdml** [coleifer/peewee#1045]
It seems that when a column is named, say "table_id", the generated models is always "table".

Command used: python -m pwiz -e mysql -u root database >> models.py

edit: I observe the same behavior with names such as "app-id"

e.g.:

sql schema:
DROP TABLE IF EXISTS `Application`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Application` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_id` char(100) NOT NULL,
  `app_name` char(100) NOT NULL,
  `app_env` text,
  `app_submit` text NOT NULL,
  `app_dag` text,
  `app_master` char(100) NOT NULL,
  `app_driver` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `app_driver` (`app_driver`),
  CONSTRAINT `Application_ibfk_1` FOREIGN KEY (`app_driver`) REFERENCES `Container` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

class Application(BaseModel):
    app_dag = TextField(null=True)
    app_driver = ForeignKeyField(db_column='app_driver', null=True, rel_model=Container, to_field='id')
    app_env = TextField(null=True)
    **app = CharField(db_column='app_id')**
    app_master = CharField()
    app_name = CharField()
    app_submit = TextField()

**Comment by maxdml** [comment]
After having a look at the code, I found the responsible function, in reflection.py:
```
425     def make_column_name(self, column):
426         column = re.sub('_id$', '', column.lower().strip()) or column.lower()                                    
427         column = re.sub('[^\w]+', '_', column)
428         if column in RESERVED_WORDS:
429             column += '_'
430         return column
```

Any reason why '_id' would be removed? Would it be still safe to have it replace such a string by '-id' ?

**Comment by coleifer** [comment]
It is removed because generally "_id" is database schema cruft, i.e. an indication that the column is a foreign key or something similar.

**Comment by maxdml** [comment]
Well I actually use it to name foreign keys =) As far as I know, and at least for MySQL, the engine makes no assumption about how FK are named.

**Comment by weihaipy** [comment]
Is there any way to keep "_id" exist?

**Comment by coleifer** [comment]
You can name your fields whatever you want:

```python

class MyModel(Model):
    some_field = TextField(column_name='actual_column_name')
    another_field = IntegerField(column_name='another_field_id')
```

**Comment by Cheaterz** [comment]
Nevertheless, any way to keep '_id' part? I have 150+ tables in db, I don't want to put back all removed '_id's manually. Can it be fixed without changing sources?

**Comment by Cheaterz** [comment]
Well, yes, I see, thanks for the explanation.
But I encountered an interesting behaviour. I'm developing a script for a XenForo-based forum, so I used pwiz to generate a model based on mysql schema. On my local machine it worked as expected: the script stipped out all "_id" parts. But when pwiz was launched on a client's machine, all "_id"s were preserved. So I thought, there is some option that can manipulate script's behaviour

**Comment by coleifer** [comment]
Probably their pre-existing database schema was missing the foreign key constraints.

**Comment by Cheaterz** [comment]
Yes, maybe, by the way. XenForo uses an interesting schema without (in some versions, as far as I know) foreign keys.
Thank you.

**Comment by coleifer** [comment]
The MyISAM storage engine, default before 5.5.5, does not handle fk constraints.

**Comment by Cheaterz** [comment]
I don't think that this is the problem, but I'll check it. Thanks again
