### ISSUE TITLE
Peewee 2.8.2 regression

### ISSUE THREAD

**Issue by mrjoes** [coleifer/peewee#1051]
Long story short - something in 2.8.2 is causing problem for one of the Flask-Admin tests.

Here's the test: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/tests/peeweemodel/test_basic.py#L918

Here's the traceback:

```
ERROR: flask_admin.tests.peeweemodel.test_basic.test_form_args
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joes/Work/flask-admin/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/joes/Work/flask-admin/flask-admin/flask_admin/tests/peeweemodel/test_basic.py", line 938, in test_form_args
    eq_(len(create_form.test.validators), 2)
AttributeError: 'ModelForm' object has no attribute 'test'
-------------------- >> begin captured logging << --------------------
peewee: DEBUG: ('CREATE TABLE "basemodel" ("id" INTEGER NOT NULL PRIMARY KEY)', [])
--------------------- >> end captured logging << ---------------------
```

Basically, `test` is not registering as a column for whatever reason.

**Comment by mrjoes** [comment]
Please ignore - it was already fixed in the master. Thanks!

**Comment by coleifer** [comment]
Can you point me to the commit that fixed this issue? I want to be sure I understand what happened.

**Comment by mrjoes** [comment]
I don't know - I installed peewee from the master and it worked all of a sudden.

**Comment by coleifer** [comment]
Just makes me nervous since that traceback doesn't really ring any bells.

**Comment by mrjoes** [comment]
The traceback is internal to flask-admin tests. 

Here's the issue:
```sql
CREATE TABLE "basemodel" ("id" INTEGER NOT NULL PRIMARY KEY)
```

For whatever the reason - it ignored the `test` column in the model definition. wtf-peewee didn't generate the field and test crashed with:
```AttributeError: 'ModelForm' object has no attribute 'test'```
