### ISSUE TITLE
Materialized views?

### ISSUE THREAD

**Issue by Resisty** [coleifer/peewee#1052]
Hello,

I was just trying to figure out, definitively, if Peewee supports the notion of [materialized views](https://www.postgresql.org/docs/9.3/static/sql-creatematerializedview.html). If so, any tips would be great, but if not, it's just good to know.

Thanks!

**Comment by coleifer** [comment]
Peewee does not generate the DDL for the creation of views, but you can certainly create a model for your view and query it normally. So, the answer is yes and no. Does that answer your question?

**Comment by Resisty** [comment]
I think so. The advice I got from a friend (who doesn't speak Python but only sql) was that having a materialized view would be good so I could have an index instead of, say, running a count across every table in the query every time. As long as I know I have to do it that way, I'm good to go. Thanks!

**Comment by coleifer** [comment]
You could also denormalize, and add the count as a column directly on the table. Might save you some disk space if your materialized view is large, and you can ensure the counts stay up-to-date using simple triggers. Just a thought.
