### ISSUE TITLE
[improvement] Model Definition via JSON

### ISSUE THREAD

**Issue by rognoni** [coleifer/peewee#1053]
For my project I need the **Model Definition** via JSON, for example:

https://github.com/rognoni/adaptable/blob/master/Backend/resources/schemas/info.json
```javascript
{
  "entities": {

    "group": {
      "properties": {
        "id": {"type": "int", "isPK": true},
        "desc": {"type": "str"},
        "name": {"type": "str", "isNull": false}
      }
    },

    "group_user": {
      "properties": {
        "id": {"type": "int", "isPK": true},
        "group_id": {"type": "ref", "entity": "group", "isNull": false},
        "user_id": {"type": "ref", "entity": "user", "isNull": false}
      }
    },

    "user": {
      "properties": {
        "id": {"type": "int", "isPK": true},
        "key": {"type": "str", "isNull": false, "isUnique": true},
        "password": {"type": "str", "isNull": false},
        "username": {"type": "str", "isNull": false}
      }
    }
  }
}
```

For the moment, to avoid source-code generation, I am using a dynamic way with `type(name, bases, dict)`

https://github.com/rognoni/adaptable/blob/master/Backend/Python-Flask/storage/sqlalchemy_sqlite.py

**Comment by coleifer** [comment]
Ummmm, huh?  http://thedailywtf.com/articles/the-inner-json-effect

I'm not going to add anything like this to peewee. It can't be more than 50-60 lines of code to do what you're trying to do.

Besides the familiar declarative syntax, Peewee can introspect an existing database, modify the schema on-the-fly, and provides extensions like [playhouse.dataset](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#dataset) and apps like [my web-based sqlite manager](https://github.com/coleifer/sqlite-web/).
