### ISSUE TITLE
Postgres extension's full text search Match raises KeyError 'T@@'

### ISSUE THREAD

**Issue by ephiepark** [coleifer/peewee#1054]
Hi, I am using peewee with flask and postgresql db, and I would like to use peewee's postgres extension to do full text search (http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#TSVectorField). But when I use Match function from the link, it raises KeyError 'T@@'. 

I followed the stack trace, and the KeyError is raised in get_op() call in QueryCompiler class. When q, the parameter to get_op() call, equates to 'T@@', self._op_map does not have key 'T@@' and raises KeyError.

**Comment by coleifer** [comment]
My guess is that you are not using the `PostgresqlExtDatabase` class, which is a subclass of `PostgresqlDatabase` class.

How are you defining your database?

**Comment by ephiepark** [comment]
Thank you for the quick reply!

Yes, I think my application is using PostgresqlDatabase not PostgresqlExtDatabase. I am using FlaskDB class setup db connection, and during init_app() call in FlaskDB it reads from config DB url and it automatically instantiate PostgresqlDatabase by looking at the url. 

Looking at the playhouse.db_url module, it seems like there is no way to let FlaskDB to create PostgresqlExtDatabase instance. 

What should I do to make use of PostgresqlExtDatabase? 

p.s. I have tried the following to force PostgresqlExtDatabase to be used 
`DATABASE = 'postgres://....db_url....' `
 `parsed = urlparse(DATABASE)`
 `connect_kwargs = parseresult_to_dict(parsed)`
 `flask_db = FlaskDB(database=PostgresqlExtDatabase(**connect_kwargs))`
And I got the follow error
`peewee.ProgrammingError: hstore type not found in the database. please install it from your 'contrib/hstore.sql' file`

**Comment by coleifer** [comment]
> Looking at the playhouse.db_url module, it seems like there is no way to let FlaskDB to create PostgresqlExtDatabase instance.

The docs show you how to use `db_url` to use the `PostgresqlExtDatabase`:

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#db-url

By default the hstore extension is enabled, so you can do one of two things:

1. Disable it
2. Enable it in postgres

To disable, pass in `register_hstore=False` when either instantiating the database instance, or as a parameter of the db_url, e.g. `scheme://user:password@host:port/database_name?register_hstore=false`

To enable it in postgres, open up a postgres shell `psql my_database` and run the following SQL:

```sql
CREATE EXTENSION hstore;
```

Depending on your system, you may need to install additional packages.
