### ISSUE TITLE
Set PIPES_AS_CONCAT in MySQL sessions

### ISSUE THREAD

**Issue by jakedt** [coleifer/peewee#1056]
Default `||` behavior in MySQL is to treat it as logical or. The `.concat` operator in peewee always uses `||`, so for concat to work in MySQL the session must be set to use `PIPES_AS_CONCAT`.

**Comment by coleifer** [comment]
For MySQL, I suppose that you will just need to use `fn.CONCAT('string 1', 'string 2', etc)` instead of `Model.some_field.concat()`. Is that reasonable, or do you think that the `concat()` function needs to be a bit smarter?

**Comment by coleifer** [comment]
Due to the design of the `QueryCompiler`, making the parser switch from an expression to a function call, in the event we're dealing with a concat on MySQL, requires some very ugly hacks.

**Comment by jakedt** [comment]
I just set up a proxy to switch between the two when I initialize the database connection. It's a fine workaround (the same as what we do for the random function across drivers) but I wish it were a little more seamless.
