### ISSUE TITLE
Peewee 2.8.3 insert_many problem

### ISSUE THREAD

**Issue by MarkSeol** [coleifer/peewee#1058]
Hi Charles:
Sorry to trouble you, we are using peewee and mysql, and our model's primary key is auto increase, we found a problem when invoking the insert_many api.
The method doesn't return the first inserted record's id, it just return True, but in the early version(like 2.4.5), it does return the first id.
So, we checked the peewee.py code. The insert section starts from line 3436:

```
if not self._is_multi_row_insert:
    if self.database.insert_returning:
        pk_row = cursor.fetchone()
        meta = self.model_class._meta
        clean_data = [
            field.python_value(column)
            for field, column
            in zip(meta.get_primary_key_fields(), pk_row)]
        if self.model_class._meta.composite_key:
            return clean_data
        return clean_data[0]
    return self.database.last_insert_id(cursor, self.model_class)
elif self._return_id_list:
    return map(operator.itemgetter(0), cursor.fetchall())
else:
    return True
```

- If we use Model.insert_many(rows).execute() , it just return True.
- If we use Model.insert_many(rows).return_id_list().execute(), it return a empty array []. operator.itemgetter(0), cursor.fetchall() both return empty array.
- If we use Model.insert_many(rows).returning(Model).execute(), an exception is threw out says that database is not supported.

So we want to ask is the insert_many method's behavior is by design or a bug? And how can we get the inserted id if we still want to use the insert many for sake of good performance?

Thanks.

**Comment by MarkSeol** [comment]
By the way, cursor.lastrowid is exactly the first record's id, it's what we want.
By using cursor.fetchone() or cursor.fetchall(), nothing is returned.

**Comment by coleifer** [comment]
This is intentional. When you're inserting multiple rows with auto-incrementing primary keys, and only the first ID is returned, it seems like maybe it would be confusing.

Postgres supports `RETURNING`, which can be used to do an `INSERT` and get back the relevant IDs. MySQL and SQLite, however, do not.

**Comment by MarkSeol** [comment]
Thanks for replying. 
So I think we should change db to Postgres or we modify a little code to return the cursor.lastrowid.

**Comment by coleifer** [comment]
Could you describe why you need the id when inserting multiple records?
