### ISSUE TITLE
Variable non-persistent instances?

### ISSUE THREAD

**Issue by yoyoprs** [coleifer/peewee#1060]
```python
>>> p = db.Paths.select().where(db.Paths.id == 1).get()
>>> p.lastsync
datetime.datetime(2016, 9, 13, 18, 59, 32, 463395)
>>> v = db.Paths.select().where(db.Paths.id == 1).get()
>>> id(p), id(v)
(4545364304, 4545364496)
>>> v.lastsync
datetime.datetime(2016, 9, 13, 19, 0, 41, 913038)
>>> import datetime
>>> v.lastsync = datetime.datetime.now()
>>> v.save()
1
>>> v.lastsync
datetime.datetime(2016, 9, 13, 19, 1, 28, 755457)
>>> p.lastsync
datetime.datetime(2016, 9, 13, 18, 59, 32, 463395)
>>> v.is_enabled = 0
>>> v.save()
1
>>> v.is_enabled
0
>>> p.is_enabled
True
```

Is this a standard behavior?

**Comment by coleifer** [comment]
peewee is an activerecord ORM. Once you understand that, though, there are no surprises. An instance is a container for row values, but not a representation of the row itself in the sense that multiple instances with the same ID are somehow linked.

Does that help?  And yes it is standard behavior. Django is the same.

**Comment by coleifer** [comment]
Please add a comment or create a new issue if you feel I haven't answered your question, or you are still not sure how this works.

**Comment by yoyoprs** [comment]
Ok for me, thank you :)
