### ISSUE TITLE
Add postgresql network address types plz

### ISSUE THREAD

**Issue by Q-Master** [coleifer/peewee#1064]
ALTER TABLE info ADD COLUMN ip inet;
this column type causes the pwiz.py to generate UnknownField class.

https://www.postgresql.org/docs/9.1/static/datatype-net-types.html

**Comment by coleifer** [comment]
Peewee does not currently support that column type. To add it, see the custom field docs:

http://docs.peewee-orm.com/en/latest/peewee/models.html#custom-fields

To get pwiz to understand the field, you'll first need your field class, then you'll want to modify the `PostgresqlMetadata.column_map` mapping the OID to the new field type.
