### ISSUE TITLE
KeyError: '"title" is not a recognized field.'

### ISSUE THREAD

**Issue by 631068264** [coleifer/peewee#1066]
```
class Manga(BaseModel):
    manga_id = IntegerField(unique=True, help_text="漫画id")
    cover_url = CharField(help_text="封面链接")
    view_page = CharField(help_text="漫画链接")
    title = CharField(help_text="漫画标题")
    date = DateField(help_text="发布日期")
```

What I want to save is a list of dict  like 

`{'manga_id': 1233504, 'title': '[中文][天道まさえ] 二つ結び [雙重馬尾][177P]', 'cover_url': 'http://img.177pic66.com/uploads/2016/08a/00012.jpg', 'date': datetime.date(2016, 9, 15), 'view_page': 'http://www.177pic66.com/html/2016/09/1233504.html'}`

and I use `Manga.insert_many(items).execute()` so why I can't insert it.

**Comment by gamelife1314** [comment]
什么原因，解决了吗？
