### ISSUE TITLE
Add `upsert_many`

### ISSUE THREAD

**Issue by MaxNoe** [coleifer/peewee#1069]
There's `insert_many` but not `upsert_many`

**Comment by coleifer** [comment]
What do you get calling insert_many() with .upsert() as well?

**Comment by MaxNoe** [comment]
You mean `insert_many(stuff).upsert()`?

**Comment by coleifer** [comment]
Yeah, I was just away from my computer and wondered what that would output?

**Comment by MaxNoe** [comment]
Ah, yes. This works. Thanks a lot.
