### ISSUE TITLE
Default value no work in Model.insert().execute()

### ISSUE THREAD

**Issue by zffl** [coleifer/peewee#107]
I add default value for datetime field, but not work in this case, but It work by writing  m =Model(..); m.save(). Is this a problem or by design?

**Comment by phryk** [comment]
I think this fix might have been un-fixed.

```
m = DatModel()
m.foo = None
m.save()
```
This results in an Integrity error (NOT NULL constraint failed) if ```DatModel.foo``` has ```null=False```.

I already found out that in the current version in pip, nothing besides ```Model.__init__``` calls ```ModelOptions.get_default_dict``` (The fix introduced a call to it in ```InsertQuery.__init__```).

**Comment by coleifer** [comment]
I'm not sure I'm understanding correctly, because if you explicitly set foo to None, peewee will not override it. Given that, makes sense to me there would follow an exception if foo was not null.

**Comment by coleifer** [comment]
Oh, but I see your point in reference to this particular issue and the way it was resolved.

So, to clarify, the fix should still be in place. Check out InsertQuery._iter_rows(). Basically it's applying defaults there. But when you are working with a model and explicitly set a field to a value, that takes precedence over a default.

**Comment by phryk** [comment]
Thanks for the clarification. But now I'm wondering what the correct way of setting the value of a field (of a previously existing instance, so UPDATE) back to its default. Do I have to manually evaluate ```DatModel.datfield._meta.default``` or is there a way to make peewee do it?

**Comment by coleifer** [comment]
Just do: obj.field = ModelClass.field.default (add parentheses if it's a callable).
