### ISSUE TITLE
Bug with multiple foreign keys to same table and DeferredRelation

### ISSUE THREAD

**Issue by miketheanimal** [coleifer/peewee#1072]
Python3 with Mysql, peewee from pip3 install --upgrade peewee. Two mysql tables:

    mysql> desc c ;
    +-------+---------+------+-----+---------+----------------+
    | Field | Type    | Null | Key | Default | Extra          |
    +-------+---------+------+-----+---------+----------------+
    | id    | int(11) | NO   | PRI | NULL    | auto_increment |
    +-------+---------+------+-----+---------+----------------+
    1 row in set (0.00 sec)

    mysql> desc p ;
    +-------+---------+------+-----+---------+----------------+
    | Field | Type    | Null | Key | Default | Extra          |
    +-------+---------+------+-----+---------+----------------+
    | id    | int(11) | NO   | PRI | NULL    | auto_increment |
    | c1    | int(11) | YES  |     | NULL    |                |
    | c2    | int(11) | YES  |     | NULL    |                |
    +-------+---------+------+-----+---------+----------------+
    3 rows in set (0.01 sec)

and the following test code:

    from peewee import *
    db = MySQLDatabase('p', user='p', password='p', host='localhost')
    deferredC = DeferredRelation()

    class C(Model):
        id = PrimaryKeyField()
        class Meta:
            db_table = 'c'
            database = db
    class P(Model):
        id = PrimaryKeyField()
        c1 = ForeignKeyField(deferredC, db_column='c1', related_name='c1')
        c2 = ForeignKeyField(deferredC, db_column='c2', related_name='c2')
        class Meta:
            db_table = 'p'
            database = db

    deferredC.set_model(C)

    c1 = C.create()
    c2 = C.create()
    p1 = P.get(P.id == 3)
    p1.c1 = c1
    p1.save()
    p2 = P.get(P.id == 3)
    p2.c2 = c2
    p2.save()
    db.commit()

If I run this on database with table c empty, and one record in p with p.c1=null, p.c2=null, then I get two records in table c (as expected) but only p.c1 links, not p.c2:

    mysql> select * from c ;
    +----+
    | id |
    +----+
    | 15 |
    | 16 |
    +----+
    2 rows in set (0.00 sec)

    mysql> select * from p ;
    +----+------+------+
    | id | c1   | c2   |
    +----+------+------+
    |  3 |   15 | NULL |
    +----+------+------+
    1 row in set (0.00 sec)

If I remove the DeferredRelation() and use ForeignKeyField(C, ....) then it works as expected, and p.c1 and p.c2 are both correctly set.

Thanks
Mike

**Comment by coleifer** [comment]
Fixed! Thanks for the great ticket.

**Comment by miketheanimal** [comment]
Glad to be of service :)
