### ISSUE TITLE
SQL views

### ISSUE THREAD

**Issue by gjask** [coleifer/peewee#1085]
I think it would be useful to be able create sql views using peewee api, that would be created with other tables from model classes. As things are now it seems I am forced to create views manually using sql and then create related peewee model.

**Comment by coleifer** [comment]
I find views to be in a bit of a gray area...kind of like triggers. My personal feeling is that there's enough variety in the types of SQL I'd need to support that until now peewee has avoided representing views or providing helpers to create/drop them. I think that for the time being I will continue to leave this unimplemented to focus on implementing and improving other features that may be more useful generally.
