### ISSUE TITLE
SqliteQueueDatabase.execute_sql() doesn't work

### ISSUE THREAD

**Issue by stenci** [coleifer/peewee#1087]
I noticed that this works:

```python
import peewee
db = peewee.SqliteDatabase('test.db')
print('journal mode = ', next(db.execute_sql('pragma journal_mode'))[0])
```

but this doesn't (with or without the `db.start()`):

```python
from playhouse.sqliteq import SqliteQueueDatabase
db = SqliteQueueDatabase('test.db')
# db.start()
print('journal mode = ', next(db.execute_sql('pragma journal_mode'))[0])
```

I don't know if it is supposed to work, but I'm reporting it because I couldn't find any documentation about this limitation and I assume it is supposed to work.

**Comment by coleifer** [comment]
Odd...that should work. The call to start() is needed (or initialize with autostart=True) because that sets up the worker threads which actually execute the queries. Also, the SqliteQueueDatabase sets the journal mode to wal automatically, but the query should work regardless. Are you using gevent? And when you say it doesn't work does it block forever without returning, time out, or return nothing? I'm afk otherwise I'd just check.

**Comment by stenci** [comment]
It returns an `AsyncCursor`, but the `next()` of it returns `TypeError: 'NoneType' object is not subscriptable`.

I don't use `gevent`. The 3 lines of code on my example are all it takes to reproduce in a clean new environment with peewee.

**Comment by coleifer** [comment]
Aha, I see the issue. The call to `next()` is not forcing the cursor to wait for the worker thread to send back the results and fire off the event. Basically, it's using an API loophole.

Try this:

```python
db.start()  # You always need either this, or autostart=True.
print('journal mode = ', next(iter(db.execute_sql('pragma journal_mode')))[0])  # Note "iter"
```

For performance reasons I would like to avoid checking the `Event` state every iteration (every call to next).

**Comment by coleifer** [comment]
I thought I had a solid understanding of python's iterator protocol, but the `next` builtin function kind of threw me off. I guess that it does not call it's argument's `__iter__()` method and directly calls `__next__()` instead. Not sure how to proceed at this point, as calling wait() every time a row is retrieved is going to make this slow as hell for large result sets.
