### ISSUE TITLE
Question: how to pass a database in tests?

### ISSUE THREAD

**Issue by aellwein** [coleifer/peewee#1097]
The documentation mentions about best practice of passing the database from the global scope:
```
sqlite_db = SqliteDatabase('my_app.db')

class BaseModel(Model):
    """A base model that will use our Sqlite database."""
    class Meta:
        database = sqlite_db
```
I use exact this pattern in my own "persistence.py" module and i need to use not 'my_app.db' for the integration tests but another (temporary) one, so how i am supposed to pass database instance in an integration test?

**Comment by coleifer** [comment]
You may find the following helpful: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#test-utils

Basically, at run-time you can swap out the database by setting `Model1._meta.database = test_db` and doing the same for `Model2`, etc. That's what the above helper takes care of (as well as schema creation).
