### ISSUE TITLE
trouble with ".select()" using peewee database

### ISSUE THREAD

**Issue by leojacoby** [coleifer/peewee#1099]
I am making a peewee database. In my python code I try to retrieve rows from the model that may be empty:

`player_in_db = Player.select().where(Player.name == player.name_display_first_last)`

`Player` is the name of the model

`name` is a field instance in `Player` defined...
```
class Player(Model):
      name = CharField()
```

`player.name_display_first_last` is a string

I get an error that says `peewee.OperationalError: no such column: t1.name`

I've been trying to solve this problem for the bulk of today, but to no avail.  Any help would be much appreciated.  Let me know if you need any more information to help me.  Thanks.

**Comment by coleifer** [comment]
It looks like you're missing assigning your database to your model:

```python
db = SqliteDatabase('my_app.db')

class Player(Model):
    name = CharField()

    class Meta:
        database = db

db.create_tables([Player], True)
```
