### ISSUE TITLE
get of create_or_get does not account for unique indexes

### ISSUE THREAD

**Issue by seaneagan** [coleifer/peewee#1100]
It accounts for fields that are `unique=True` [here](https://github.com/coleifer/peewee/blob/8dbf04073a0b02490cc8d86ae701523cc7481a4a/peewee.py#L4871), but not (possibly composite) unique indexes set on the meta model.

**Comment by coleifer** [comment]
Correct, I can see about improving the code to include these types of constraints.

**Comment by coleifer** [comment]
To be honest, there is no piece of code I regret more than get_or_create. It's so easy to write your own version that's specific to your model. But a general purpose one is complicated. Ugh.

**Comment by coleifer** [comment]
I think I'm actually going to remove get_or_create because of all the headaches. So, closing this as won't fix.
