### ISSUE TITLE
Tuples in SQL

### ISSUE THREAD

**Issue by maaaks** [coleifer/peewee#1105]
In a query, I need to compare tuples of values (I'm not sure how are they correctly called in SQL, maybe «records»?..), like this:

``` sql
where (a.field1, a.field2) < (b.field1, b.field2)
```

Currently I achieved this by calling an empty-named function through `fn` which works but seems to be a hack or maybe even a bug, depending on how you look at it:

``` python
getattr(fn, "")(a.field1, a.field2) < getattr(fn, "")(b.field1, b.field2)
```

Is there a better way to do this thing in Peewee? I am sure that it can be written manually using different `Node`s but shouldn't there be something for this out of the box?

**Comment by coleifer** [comment]
Traditionally, peewee hasn't supported this explicitly. Though with SQLite's new row-values stuff getting released I think it should, so I'll look at a patch.

**Comment by maaaks** [comment]
I haven't tried yet, but I just suddenly thought that I maybe could get what I want using `CommaClause`, couldn't I?

**Comment by coleifer** [comment]
Yes that should certainly work.

**Comment by coleifer** [comment]
In fact most likely that's how I'll end up implementing this: interpret tuples as CommaClause.

**Comment by coleifer** [comment]
Actually, and of course I should have realized this, the Python interpreter won't let us override the comparators for tuples, so writing:

```
(User.id, User.username) == (1, 'user-1')
```

Will be evaluated by the Python interpreter (as `True`) and at no point are we aware that the comparison is operating on a 2-tuple.

So for now, if you wish to use tuples in Peewee, you should use the new `Tuple` class (available if you `from peewee import *`). The `Tuple` class is simply an alias for `EnclosedClause`, as you had suggested.

**Comment by iurly** [comment]
Hi @coleifer , I was looking for a way to express [SQLite Row Values](https://www.sqlite.org/rowvalue.html#search_against_multi_column_keys) and only found the solution above by chance.
I believe this should be documented, and I'm willing to write a few words about it.
Where do you think it would be more appropriate?
Perhaps in the [Expressions section of the Query Operators chapter](http://docs.peewee-orm.com/en/latest/peewee/query_operators.html?highlight=where#expressions)?

**Comment by coleifer** [comment]
Added some docs.

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#row-values
