### ISSUE TITLE
AttributeError with db.atomic() and SqliteQ

### ISSUE THREAD

**Issue by theotherp** [coleifer/peewee#1109]
It's me again...

With 6ffc93cd867a7f3b28783ad4f533b1f9a205f540 I get an AttributeError using db.atomic() because lock_type is not set:

 ```
 File "C:/Users/user/PycharmProjects/nzbhydra\nzbhydra\search.py", line 318, in search
    with db.atomic():
  File "C:\Users\user\PycharmProjects\nzbhydra\libs\peewee.py", line 4471, in __enter__
    self.context_manager = self.db.transaction(self.transaction_type)
  File "C:\Users\user\PycharmProjects\nzbhydra\libs\playhouse\sqlite_ext.py", line 957, in transaction
    assert lock_type.lower() in ('deferred', 'immediate', 'exclusive')
AttributeError: 'NoneType' object has no attribute 'lower'
```

I'm using `with db.atomic("deferred")` to fix that but wanted to let you know.

**Comment by coleifer** [comment]
Are you running on the current, very latest commit? Because `sqliteq`'s `atomic()` is kinda broken right now in a totally different way, as I'm in the process of implementing something like a pipeline in Redis.

**Comment by theotherp** [comment]
Yeah, that's why I mentioned the commit hash. Not sure if you want feedback on your current development code.
