### ISSUE TITLE
MySQL - TimestampField Issue

### ISSUE THREAD

**Issue by Byte-Lorenz** [coleifer/peewee#1110]
**Model:**
`class Issue(BaseModel):
time = TimestampField(resolution=1000)`

Doc: [http://docs.peewee-orm.com/en/latest/peewee/api.html#TimestampField](url)

**Issue:**
Inserting TimestampFied with value: `1475411420001` will be stored in the MySQL database as `1475411420001000`.
Although the resolution of the field is set to milliseconds (1.000) and not to microseconds (1.000.000)

When I'm reading out the data of the database and transforming it to the corresponding model with model_to_dict(...).  I'm encountering the following error: "ValueError: year is out of range". (on line 1283 of peewee.py)

**Comment by coleifer** [comment]
> Inserting TimestampFied with value: 1475411420001 will be stored in the MySQL database as 1475411420001000.
> Although the resolution of the field is set to milliseconds (1.000) and not to microseconds (1.000.000)

It looks to me like you've over-thought it and done the multiplication yourself. The purpose of the `TimestampField` is to make all that unnecessary. `TimestampField` allows you to work with `datetime` objects in Python but store them as integers in the database. If you want to explicitly pass in a timestamp as an integer or floating point, then Peewee will scale that accordingly before storing it.
