### ISSUE TITLE
How do I make a CharField(collate='nocase')?

### ISSUE THREAD

**Issue by stenci** [coleifer/peewee#1111]
Is it possible to create a field with [`COLLATE nocase`](https://www.sqlite.org/datatype3.html#collation_sequence_examples)?

```
CREATE TABLE tab (col TEXT COLLATE nocase);
```

I looked for something like this, but I couldn't find it:
```
class Tab(Model):
    col = CharField(collate='nocase')
```

The alternative is to make either a lowercase index or a collate nocase index, and make sure all the queries are either lowercase or collate nocase. It would be much easier to create the columns as collate nocase and get sorting and querying automatically case insensitive.

**Comment by coleifer** [comment]
You can add a constraint:

```python
column = CharField(constraints=[SQL('COLLATE NOCASE')])
```
