### ISSUE TITLE
unsafe in multi-thread context

### ISSUE THREAD

**Issue by zkchen310** [coleifer/peewee#1114]
```
class MyModel(Model):
    name = CharField()
    class Meta:
        db = my_db
```

using `MyModel` in multi-thread environment is unsafe, as db can not be shared in different threads.

**Comment by coleifer** [comment]
Can you explain in greater detail? Peewee stores the connection state in a thread-local, so each thread should by default have its own connection.

**Comment by coleifer** [comment]
Whatever, closing.

**Comment by coleifer** [comment]
Please comment if you have any information you can provide to clarify the issue.
