### ISSUE TITLE
Silence Signals Support

### ISSUE THREAD

**Issue by smittysmee** [coleifer/peewee#1116]
Would it be possible to add the ability to silence signals for the pre_save handler, post_save handler, etc. This would allow for pre_save and post_save actions on the objects to prevent a loop modification within a handler.

Essentially, I have a process that once it is posted, the handler will take the object and perform a call within a module that takes the object, verifies it again our API, and modifies the object where need be.  Because it performs a save again when updating the object, I would like not run the call again to the API and save it again... etc. 

Proposed solution would be able to pass a kwarg to the save method that is overwritten by the playhouse signal method, that would look for the kwarg. If available and the value equates to true, then to skip over the signal method from running.

**Comment by coleifer** [comment]
I'm not following this at all.

**Comment by coleifer** [comment]
The signals all have a disconnect method, so you could use that. Alternatively you could use a global variable or thread local to keep track of the state.
