### ISSUE TITLE
Nested brackets in the documentation?

### ISSUE THREAD

**Issue by NathanWailes** [coleifer/peewee#1117]
What do the nested brackets mean in the documentation?
`model_to_dict(model[, recurse=True[, backrefs=False[, only=None[, exclude=None[, extra_attrs=None[, fields_from_query=None]]]]]])`
([Link](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#model_to_dict))

I looked online and it seems that having brackets nested like that can be used to show that one optional argument requires the presence of another optional argument, but that doesn't seem to be the case here, as I've seen examples of calls to this function that specify (for example) the 'extra_attrs' parameter without some of the earlier ones.

**Comment by coleifer** [comment]
These are optional keyword arguments. The arguments in brackets are shown with their default values (if they have one).

**Comment by NathanWailes** [comment]
I understand that brackets indicate optional arguments; I'm asking why they're nested.

**Comment by coleifer** [comment]
Because that's how you do it. https://docs.python.org/3/library/collections.html#collections.deque
