### ISSUE TITLE
Set PostgreSQL schema in atomic

### ISSUE THREAD

**Issue by shanavar** [coleifer/peewee#1119]
Hey everybody,

so I got a problem regarding schema selection with peewee and PostgreSQL. I use peewee almost exclusively in transaction mode with `atomic`. While the schema is set to `none` in the meta of the class, I would want to set a specific schema in the `atomic` block. All queries in the atomic block should now act on the specified schema when the transaction of this `atomic` block happens. All the schemas in question do contain the same table structure. Is it possible to simply call `Model._meta.schema = myschema` at the beginning of the `atomic` block, e.g.:

```python
class BaseModel(Model):
    name = CharField()
    class Meta:
        schema = none
        db_table = users


with db.atomic() as txn:
    # set the schema for this block and the User Model
    User._meta.schema = myschema

    # this queries myschema.users and NOT public.users
    db.execute_sql('SELECT * FROM users WHERE name = %s', 'JohnDoe')

    # so does this
    User.create(name='JohnDoe')
```

So can I simply use `Model._meta.schema = myschema`? On the other hand, I also went through the documentation and a little bit through peewee source code and I think what I might need is some sort of `atomic` with properties of `Using` for schemas.

**Comment by coleifer** [comment]
Yes, you can simply set `MyModel._meta.schema`. I'm not sure what it means to run a transaction against one schema...or how that works. I guess I thought a table lived in one schema, so the idea of switching it's schema to do a transaction should imply you're working with an entirely different table??

**Comment by shanavar** [comment]
Yes. I am sorry, I did express myself the wrong way. What I wanted to say is, that I have one model that I use for multiple schemas so that all the tables do have the same structure but are of course different tables. And what I wanted is to set the schema within the atomic block, either for the whole transaction or per object/class. I wasn't sure if `User._meta.schema` wouldn't cause any problems if I use it in a peewee atomic block in a flask request or if it would simply set `tablename` to `schema.tablename` for queries inside this transaction only and have no effect otherwise.

**Comment by coleifer** [comment]
You're fine to modify the schema attribute, peewee will use whatever's set when the query is executed.
