### ISSUE TITLE
Document (optional) requirements

### ISSUE THREAD

**Issue by vkrizan** [coleifer/peewee#1120]
Please document (optional) requirements in one document (or file). This will help first-timers and help when packaging (RPM, deb).

Requirements for playhouse extensions (so far I've identified these):
```
Cython      # optional for speedups
simplejson  # optional for playhouse.kv and playhouse.sqlite_ext (json is supported since 2.6+ in standard lib)
apsw        # for playhouse.apsw_ext
bz2         # optional for playhouse.fields
zlib        # optional for playhouse.fields
Crypto      # optional for playhouse.fields
bcrypt      # optional for playhouse.fields
flask       # (obviously) for playhouse.flask_utils
psycopg2cffi  # optional for playhouse.postgres_ext
vtfunc      # optional for playhouse.sqlite_udf (old import at sqlite_ext ?)
gevent      # optional for playhouse.sqliteq
```

Database drivers (Already noted in [Vendor Specific Parameters](http://docs.peewee-orm.com/en/latest/peewee/database.html#vendor-specific-parameters) in docs), could be noted in a table of supported databases and required drivers.
```
Mysql: MySQLdb or pymysql
Postgres: psycopg2
Berkley: (optional) pysqlite2
```

Thank you. 

I can help to create such document(s), although I am not sure when or why `simplejson` is needed.

**Comment by coleifer** [comment]
Certainly, thanks for the nudge.
