### ISSUE TITLE
the field can't named 'model'?

### ISSUE THREAD

**Issue by msean** [coleifer/peewee#1123]
In Test Model,It set a field named 'model':

class Test(peewee.Model):
        model = peewee.CharField(max_length=64,  null=True)
        class Meta:
            database = DATABASE
            db_table = "test"
            schema = "opr"

It happened error :
`File "/home/mwh/py3workplace/workplace/ad_tornado/handlers/opr.py", line 78, in post
yield from self.db.create(Test,model='android')
TypeError: create() got multiple values for argument ‘model’
`
I used peewee to related some Tables which had establishd and contains field 'model',but It happend error like this...if I don't change the field in db,is there any other ideas?

**Comment by coleifer** [comment]
Please take the 10seconds and format your code...

**Comment by msean** [comment]
In My Test Model,It set a field named 'model':
```
import peewee
class Test(peewee.Model):
    model = peewee.CharField(max_length=64,  null=True)
    class Meta:
        database = DATABASE
        db_table = 'test'
        schema = 'opr'
```
when I create a record,It happens an error:

```
File "/home/mwh/py3workplace/workplace/ad_tornado/handlers/opr.py", line 78, in post yield from 

    self.db.create(Test,model='android') TypeError: create() got multiple values for argument ‘model’
```
Weather the filed can named 'model'?@coleifer 
I used peewee to related some Tables which had establishd and contains field 'model',
if I don't change the field in db,is there any other ideas?

**Comment by msean** [comment]
In My Test Model,It set a field named 'model':
```
import peewee
class Test(peewee.Model):
    model = peewee.CharField(max_length=64,  null=True)
    class Meta:
        database = DATABASE
        db_table = 'test'
        schema = 'opr'
```
when I create a record,It happens an error:

```
File "/home/mwh/py3workplace/workplace/ad_tornado/handlers/opr.py", line 78, in post yield from 

    self.db.create(Test,model='android') TypeError: create() got multiple values for argument ‘model’
```
Weather the filed can named 'model'?@coleifer 
I used peewee to related some Tables which had establishd and contains field 'model',
if I don't change the field in db,is there any other ideas?

**Comment by coleifer** [comment]
I think the issue is in your code. There is no "Database.create" method in Peewee. It appears to be a function in your own application. :disappointed:
