### ISSUE TITLE
How can I omit creation of a field but still have it in my model?

### ISSUE THREAD

**Issue by maaaks** [coleifer/peewee#1128]
I'm using PostgreSQL. In one of my models I try to declare field named `tableoid`. This is a special field in PostgreSQL which is created automatically. So this always works:

```sql
select foo.tableoid from foo;
```

But the field cannot be created manually:

```sql
create table foo (tableoid int);
-- ERROR:  column name "tableoid" conflicts with a system column name
```

Yet I need to make Peewee aware of this field because when using [table inheritance](https://www.postgresql.org/docs/current/static/ddl-inherit.html) it is very convenient to join system tables and get tablenames by `tableoid`.

Could you please make something like `Field(..., omit_creation=True)` for this situation?

**Comment by maaaks** [comment]
Maybe there is an easier way to do what I want, by somehow cheating in `MyModel.create()`, but I don't understand how.

**Comment by coleifer** [comment]
Just added "undeclared" option, which was useful to me for a similar thing in SQLite regarding the "rowid" field. Commit:  eebbed7a5e1c6b3318bcbe6525ea80d900ee1f12
