### ISSUE TITLE
Math operators in query

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#1131]
Hi!
I have a `peewee.DateTimeField`in my model. And I need calculate duration between date in this field and current date in days.
```python
from peewee import DatetTimeField, fn
from playhouse.shortcuts import cast
from config import db
from datetime import datetime

class Table(db.Model):
    ts = DateTimeField(default=datetime.now)


duration = fn.current_date - cast(Table.ts, 'date')
qs = Table.select(duration.alias('duration')).dicts()
```
But it not works. Where I have mistaken?
SQL query works fine:
```sql
select current_date - cast(ts as 'date') as duration from table
```

**Comment by BEaStia** [comment]
What errors do you receive? 
What SQL is composed?

**Comment by coleifer** [comment]
Well, `fn.current_date` should be written as: `fn.current_date()`, unless that's some magical name in which case you should just write `SQL('current_date')`.

Math operators work as you'd expect, so theoretically your query would work provided your database understands the expression "current_date - cast(table.ts as date)".

Try fixing the function call as I described. It looks like you need to use the "SQL('current_date')" construction as opposed to the function call.

**Comment by ak04nv** [comment]
@coleifer great man!!! That's I wanted!
