### ISSUE TITLE
Possibility to exclude certain columns from default selection

### ISSUE THREAD

**Issue by MaxNoe** [coleifer/peewee#1135]
The default for `peewees` `select()` is to request all columns.

Could it be possible to exclude columns from this selection?

E.g. something like:

```python

class MyModel(Model):
    x = FloatField()
    data = BlobField()

    class Meta:
        database = database
        exclude_from_default_select = [data]
```

I ran into some performance issues, because I somewhere always requested a large blob through a foreign key traversion.

Now I do something like

```python
b = ModelB.select(ModelB.some_field).where(ModelB.id == a.model_b_id).get()
some_field = b.some_field
```

Instead of just accessing
```
a.model_b.some_field
```
because `ModelB` has a large Binary blob.

It would really simplify my code if I could exclude the blob field from the foreign key traversion.

Thanks for the great package and for any help!

**Comment by coleifer** [comment]
Just write a custom method.
