### ISSUE TITLE
Remove `*` imports in doc

### ISSUE THREAD

**Issue by MaxNoe** [coleifer/peewee#1136]
The one thing that often tends to annoy me when reading the docs is the use of `from peewee import *` or `from playhouse.migrate import *`.

One never really knows where stuff comes from.

**Comment by coleifer** [comment]
Yeah, I hear that. I guess, as the author, I'm always aware of that stuff but I can see how it would be super confusing in the docs. I'll update them as I find the time.

**Comment by coleifer** [comment]
Well, I looked into this a bit. The `import *` are actually necessary in some places because extension modules typically will shadow peewee globals. Peewee has always been made with an eye towards `from peewee import *` so ...think I'm going to just leave this one alone.
