### ISSUE TITLE
Print SQL queries

### ISSUE THREAD

**Issue by ripperdoc** [coleifer/peewee#114]
I updated from 1.0 to 2.0 and got into a bit of a mess - which has mostly cleared up now. One thing though - how do I print sql queries? I used to be able to do SelectQuery.sql() but not it requires a compiler argument, but what should I put into that? I cannot find any mention in the docs...

Thanks!

**Comment by kevinisaac** [comment]
@coleifer Can you please give an example of how to use that helper function?

**Comment by coleifer** [comment]
That function actually went away. Now you can just call:

```python
q = MyModel.select().where(MyModel.id == 3)
print q.sql()
sql, params = q.sql()
```

**Comment by TimothyBramlett** [comment]
@coleifer What if the result of `q = MyModel.select().where(MyModel.id == 3)` fails and caused an error?  Is it possible to get the query that was sent to the DB and failed?

**Comment by coleifer** [comment]
You can log all queries.

```python
import logging
logger = logging.getLogger('peewee')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
```

Or you can add try/except or use an interactive debugger...it's just Python, remember!

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/database.html#logging-queries

**Comment by NicolasCaous** [comment]
@TimothyBramlett you can use the logging package:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

Peewee will print all queries that it sends to the DB.

**Comment by tijptjik** [comment]
As per peewee `3.13` you can print SQL queries by first getting the cursor, then calling the `mogrify()` method for your query.

```python
query = <YOUR PEEWEE QUERY>

cur = database.cursor()
print(cur.mogrify(*query.sql()))
```
Where `database` is the Peewee Database object representing the connection to your database.

**Comment by coleifer** [comment]
`mogrify` may be a psycopg2-only thing, and no supported by other drivers. For example, the standard lib sqlite3 does not provide this method.
