### ISSUE TITLE
Model.get_or_none

### ISSUE THREAD

**Issue by razodactyl** [coleifer/peewee#1140]
I think the only place I found this behaviour was in the Dataset utility.

Usually, to get a row you would use Model.get.
However, if the row doesn't exist, a DoesNotExist is thrown.

I propose a 'get_or_none' function to return None instead of throwing an error, in this way, you can simply query a record and have nothing if there's no records.

e.g

```
user = User.get(username == 'razodactyl') # returns User
user = User.get(username == 'not_created_yet') # returns None
```

**Comment by razodactyl** [comment]
I'm currently using this on a 'BaseModel' my models are subclassing from.
With the 'BaseModel' being a subclass of the FlaskDB model - (not its internal BaseModel :P)

```
class BaseModel(db.Model):
    @classmethod
    def get_or_none(cls, *query, **kwargs):
        try:
            return cls.get(*query)
        except cls.DoesNotExist:
            return None
```

**Comment by timster** [comment]
user = User.select().where(username == 'not-created').first()

That's what I usually do. `first()` will return a record or None.

**Comment by coleifer** [comment]
Thanks @timster
