### ISSUE TITLE
About connection pool

### ISSUE THREAD

**Issue by 521xueweihan** [coleifer/peewee#1143]
Hi coleifer, 

First peewee is awesome, It is very useful. Thank you.

There I consult for something about `connection pool`. when I use the peewee connection pool, I meet some problem: `Exceeded maximum connections.` and `Error 2006: “MySQL server has gone away”`, so I read document and peewee source code solve this two Error. 

The reason is: I don't close the connection when I use the pool. So I try to find a way to fix it out.

The document give two way to auto close connection:

```python
with db.execution_context():
    # A new connection will be opened or, if using a connection pool,
    # pulled from the pool of available connections. Additionally, a
    # transaction will be started.
        for user in get_all_user():
            user_id = user['id']
            rule = Rule(user_id)
            rule_dict = rule.slack_rule()
            .....do something.....
```

```python
@app.before_request
def _db_connect():
    database.connect()
#
# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not database.is_closed():
        database.close()
#
#
# 
from playhouse.flask_utils import FlaskDB
from dock_fastgear.model.base import db
#
app = Flask(__name__)
FlaskDB(app, db) 
```

At last , I have a question: Why connection alway close by myself(Implicit or Dominant), Because can't check `_in_use` connections timeout ? There is no automatic management of connections, The feature will be there?

**Comment by coleifer** [comment]
Connections must be closed by the application writer. It is a good practice to ensure that your connections are opened and closed in a sensible way.
