### ISSUE TITLE
Misunderstanding somethng or weird behaviour ?

### ISSUE THREAD

**Issue by stuaxo** [coleifer/peewee#1144]
I've got a connection to a sqlite db and a table like this one :
```
class Resource(Model):
    # [snipped other fields]
    filename = CharField(null=True)
```

If I do 

```
resources = models.Resource.select().where(models.Resource.filename == None)
for r in resources:
    r.update(filename=filename)
    import ipdb; ipdb.set_trace()
```

Then r.filename is None...
```
>>> r.filename == None
True
```

Is this expected?  How can I set this value ?

**Comment by stuaxo** [comment]
Worse - if I use

```
r.filename = filename
r.save()
```

Data in completely different fields seems to be getting saved and I am getting wrong values.

(I switched from save() because of this initial problem)... now I've tested going back, it has this other bug.

**Comment by stuaxo** [comment]
Hi,
   I'm going to close this.    - Project I'm on is on a silly deadline, so don't have time to simply reproduce it unfortunately.    Our app is has quite a few threads using asyncio, which may be the issue.  ..  It'll take about the same time to move our app to SqlAlchemy as it would to make a simple example, so were going on this path.

Cheers
S

**Comment by coleifer** [comment]
You need to call ".execute()" to actually execute the update query.

**Comment by coleifer** [comment]
Sorry I didn't see this sooner, but hopefully this information finds you in time to make your project work.

**Comment by stuaxo** [comment]
Cheers for the info :)
