### ISSUE TITLE
Schema migrations don't create indexes

### ISSUE THREAD

**Issue by alexlatchford** [coleifer/peewee#1148]
If you're doing a migration and add a column with `index=True` or `unique=True` it doesn't automatically create an index. Even trying to perform a `migrator.add_index()` in the same `migrate()` block fails.

I'm doing this with the Postgres backend.

**Comment by coleifer** [comment]
The code to add an index is tested, so I believe adding an index explicitly should work. You can check the `test_add_index` test-case in `test_migrate.py`.

**Comment by coulix** [comment]
I confirm this odd behavior.

```python
database = PooledPostgresqlExtDatabase(...)

migrator = PostgresqlMigrator(database)

class BaseModel(Model):

    class Meta:
        database = database


class MessengerMessage(BaseModel):
    mid = CharField(unique=True, primary_key=True)
    sender_id = BigIntegerField(index=True)
    recipient_id = BigIntegerField(index=True)

    # Either text message or attachment.
    text = TextField(null=True)
    created = DateTimeField(default=datetime.datetime.utcnow)

    class Meta:
        order_by = ('-created',)
        db_table = 'messenger_message'
```

A call to:

```
database.create_table(MessengerMessage, safe=True)
```

Will output the CREATE TABLE SQL without any indexes.

**Comment by coleifer** [comment]
Call Model.create_table().

**Comment by coleifer** [comment]
Or, oddly, database.create_tables([Model]). The database.create_table method will only create the table, though, whereas create_tables() creates both tables and indexes.

**Comment by alexlatchford** [comment]
I've tested this with v2.8.6 and definitely fixed for the schema migration utils

**Comment by coulix** [comment]
@coleifer Yes sorry I removed my comment without updating.

`create_tables` do create both table and index but `database.create_table` does not.
