### ISSUE TITLE
Prefetch prefetches all foreign keys.

### ISSUE THREAD

**Issue by tkukushkin** [coleifer/peewee#1167]
I need to prefetch by only specific foreign key, but it prefetches by all.
Maybe need to add possibility to specify field for prefetch instead of join_model?

Also prefetch don't preserves by query methods like `Query.where` and it is not lazy. Maybe good to do query method like `Query.prefetch(self, *refs)` where `refs` – tuples like `(User.tweets, Tweet.select())` or simply `User.tweets`. This method will be lazy.

Sorry for my English 😢.

**Comment by coleifer** [comment]
Unfortunately, prefetch cannot be lazy by definition. I'd suggest just writing the queries you need explicitly.
