### ISSUE TITLE
Validation for choices in the application layer

### ISSUE THREAD

**Issue by ParthGandhi** [coleifer/peewee#1169]
I get why you don't validate for `choices` in the db layer.

Any reason it can't be implemented at the application layer? For backwards compatibility validated choices can be a new attribute called `allowed`/`validated_choices`? 

The behavior i'm thinking of is to throw a `ValueError` on saving a field if its not one of the allowed values.

**Comment by coleifer** [comment]
It can be validated in the application layer -- *your* application!

**Comment by ParthGandhi** [comment]
Heh, we already do that! Was wondering if there was any interest upstream.

Thanks!
