### ISSUE TITLE
why there is no pskel?

### ISSUE THREAD

**Issue by axiaoxin** [coleifer/peewee#1172]
I read the doc: <http://docs.peewee-orm.com/en/latest/peewee/database.html#generating-skeleton-code>, I test using pskel to generate the skeleton code, but I found the pskel is not exists in my local

under the site-packages, peewee's install-files.txt is:

```
..\peewee.py
..\pwiz.py
..\playhouse\apsw_ext.py
..\playhouse\berkeleydb.py
..\playhouse\csv_loader.py
..\playhouse\csv_utils.py
..\playhouse\dataset.py
..\playhouse\db_url.py
..\playhouse\djpeewee.py
..\playhouse\fields.py
..\playhouse\flask_utils.py
..\playhouse\gfk.py
..\playhouse\hybrid.py
..\playhouse\kv.py
..\playhouse\migrate.py
..\playhouse\pool.py
..\playhouse\postgres_ext.py
..\playhouse\read_slave.py
..\playhouse\reflection.py
..\playhouse\shortcuts.py
..\playhouse\signals.py
..\playhouse\sqlcipher_ext.py
..\playhouse\sqliteq.py
..\playhouse\sqlite_ext.py
..\playhouse\sqlite_udf.py
..\playhouse\test_utils.py
..\playhouse\__init__.py
..\peewee.pyc
..\pwiz.pyc
..\playhouse\apsw_ext.pyc
..\playhouse\berkeleydb.pyc
..\playhouse\csv_loader.pyc
..\playhouse\csv_utils.pyc
..\playhouse\dataset.pyc
..\playhouse\db_url.pyc
..\playhouse\djpeewee.pyc
..\playhouse\fields.pyc
..\playhouse\flask_utils.pyc
..\playhouse\gfk.pyc
..\playhouse\hybrid.pyc
..\playhouse\kv.pyc
..\playhouse\migrate.pyc
..\playhouse\pool.pyc
..\playhouse\postgres_ext.pyc
..\playhouse\read_slave.pyc
..\playhouse\reflection.pyc
..\playhouse\shortcuts.pyc
..\playhouse\signals.pyc
..\playhouse\sqlcipher_ext.pyc
..\playhouse\sqliteq.pyc
..\playhouse\sqlite_ext.pyc
..\playhouse\sqlite_udf.pyc
..\playhouse\test_utils.pyc
..\playhouse\__init__.pyc
dependency_links.txt
PKG-INFO
SOURCES.txt
top_level.txt
..\..\..\Scripts\pwiz.py
```

**Comment by coleifer** [comment]
It's only included in the git repo.

**Comment by ankostis** [comment]
Actually `pskel` is declared usign the `script=[]` parameter of `setup.py` installation script, which it fails on many occasions to properly install things.

It would work out of the box in all python environments if it was converted into console entry-point:
http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point
Setuptools will generate an `.exe` on Windows, and guess correctly the path if python-interpreter on POSIX.

I can provide a pull-request, but it would require some minor changes:
- create new `main()` functions on `/pwiz.py` and `/playhouse/pskel`, 
- rename it as `pskel.py`.

Would that be ok?
