### ISSUE TITLE
Hug framework support

### ISSUE THREAD

**Issue by 0gk** [coleifer/peewee#1174]
Please, add section about Hug support. I try to use instructions for Falcon, but it don't work. May be Hug just have no hooks or smth like?

**Comment by coleifer** [comment]
I'd accept a PR with docs.

**Comment by 0gk** [comment]
Maybe something like this:

```
@hug.request_middleware()
def preProcessing(request, response):
    db.connect()

@hug.response_middleware()
def afterProcessing(request, response, resource):
    db.close()
```
