### ISSUE TITLE
Database default

### ISSUE THREAD

**Issue by theobouwman** [coleifer/peewee#1175]
Is it possible to add a default which is done by the database server.
Like `DEFAULT CURRENT_TIMESTAMP` for a MySQL datetime field?

I would like to make a PR if it's not available.

**Comment by coleifer** [comment]
Yes, you can specify arbitrary stuff in the `constraints` field parameter:

```python
timestamp = DateTimeField(constraints=[SQL('DEFAULT CURRENT_TIMESTAMP')])
```

http://docs.peewee-orm.com/en/latest/peewee/models.html?#default-field-values
