### ISSUE TITLE
Subquery problems with peewee Cython

### ISSUE THREAD

**Issue by danygielow** [coleifer/peewee#1178]
I have encountered an error with subqueries and the usage of `SQL('*')` when peewee is built with Cython extensions. Without Cython, the behavior is the same as before.

TestCase:

```python
    def test_subselect(self):
        with test_database(self.mysql_test_db, [A]):
            A.create(a=1, b=3)
            A.create(a=2, b=4)

            sub = A.select(A.a, A.b)
            query = (A.select(peewee.SQL('*')).from_(sub.alias('sub')))

            for r in query.dicts():
                self.assertIn(r['a'], [1,  2])
                self.assertIn(r['b'], [3, 4])
```

Regardless, if the test is a representative example, it worked until version 2.8.4.
This time I won't be able to supply a PR, because of my lack of C skills.

**Comment by coleifer** [comment]
Are you dead set on using `SQL('*')`? The "peewee" way would be to write:

```python
sub = sub.alias('sub')
query = A.select(sub.c.a, sub.c.b).from_(sub)
```

**Comment by danygielow** [comment]
OK, you might be right. But there is still a discrepency in functionality between the Cython speedups and non-speedup code.

I close this issue, because we will use the columns from now on.
