### ISSUE TITLE
how can use sub-table search?

### ISSUE THREAD

**Issue by noogel** [coleifer/peewee#1179]
I have many of the same tables, just different table names.
like:
book_001
book_002
...
...
book_100

How to write a Model class according to different conditions of the table data.

E.g:
Book.get_model('001').select().execute()  => select * from book_001
Book.get_model('002').select().execute() => select * from book_002

How to implement the get_model() method.

Thanks!

**Comment by coleifer** [comment]
This is not a feature of peewee.
