### ISSUE TITLE
Postgresql FOR SHARE support

### ISSUE THREAD

**Issue by kapucko** [coleifer/peewee#1180]
Hi,

I'm looking for support of FOR SHARE locking level in postgres (https://www.postgresql.org/docs/9.4/static/explicit-locking.html). I have found just this: http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectQuery.for_update which generates FOR UPDATE.
Is there any way I can implement this as an extension?

Please help me.
Thank you.

**Comment by coleifer** [comment]
Added in 7f6f578f6f06e865ea5f3823c163d39aa6ff2a96

```python
SomeModel.select().with_lock('SHARE')
```
