### ISSUE TITLE
Model to dict for array of models

### ISSUE THREAD

**Issue by theobouwman** [coleifer/peewee#1185]
`model_to_dict` can only convert a single model to a dictionary, right?
But what about an array of models, like this: `User.select().where(User.age > 19)` this will return all `users` above 19 years old. But what when I want to return this array as json? Then I need to loop through every object an make it a dictionary with `model_to_dict`.

I find this pritty inconvenient to do when making an API. I know I can solve this by making a helper method, but I thought this should be in the core package.

I can make a PR to add it to the playhouse module.

Plz correct me if i'm wrong...

**Comment by coleifer** [comment]
Make a for loop. Jesus.

**Comment by theobouwman** [comment]
Wauw
