### ISSUE TITLE
autocommit should be True by default

### ISSUE THREAD

**Issue by benjsto** [coleifer/peewee#1186]
As documented, and by my reading of the peewee source code, `autocommit` is intended to be True by default. However, that does not line up with what I'm seeing:

Initializing a peewee MySQLDatabase instance:
```
db = MySQLDatabase(settings.get('db_name'),
                   host=settings.get('db_host'),
                   port=settings.get('db_port'),
                   user=settings.get('db_user'),
                   passwd=settings.get('db_pw'),
                   charset='utf8mb4',)
```
Results in connections in the general log that look like:
```
170207 22:01:58  1591 Connect   root@172.17.0.4 on test_db
                 1591 Query     SET NAMES utf8mb4
                 1591 Query     set autocommit=0
                 1591 Query     SELECT `t1`.`id` FROM `table` AS t1 ORDER BY `t1`.`published_at` DESC LIMIT 1 OFFSET 0
                 1591 Query     commit
```
I've found a workaround by subclassing MySQLDatabase and overriding the _connect method and explicitly passing in `autocommit=True` there.

**Comment by coleifer** [comment]
`autocommit` refers to the behavior of Peewee, not what the underlying driver may or may not be doing.
