### ISSUE TITLE
database locked even with minimal concurrency

### ISSUE THREAD

**Issue by rayzorben** [coleifer/peewee#1188]
I am trying to insert multi threaded. I have 4 worker threads that pull data off a queue (producer/consumer model) and does an insert_many on that data.

```python
def run(self):
        while True:
            try:
                r = self.q.get_nowait()
            except Empty:
                r = None

            if r is None:
                #TODO: signalling
                time.sleep(0.05)
                continue

            self.process(r)

    def process(self, item):
        table, data = item
        with db.transaction():
            table.insert_many(data).execute()
```

Here is how I setup my connection:

```python
db = SqliteDatabase(database, autocommit=False, threadlocals=True, pragmas=(('journal_mode', 'WAL'), ('cache_size', 10000)))
```

No matter how I set it up, I occasionally get `peewee.OperationalError: database is locked`.

I am guessing that the insert_many is holding the lock too long, and a timeout is being hit. Am I doing this incorrectly or should I be somehow handling the database is locked error and retrying?

**Comment by coleifer** [comment]
I wrote a blog post on this subject, http://charlesleifer.com/blog/multi-threaded-sqlite-without-the-operationalerrors/

But, tl;dr is that you probably are running up against timeouts while waiting for the write lock...possibly?

You can try increasing the timeout, by passing `timeout=10` or more to the initialization method of `SqliteDatabase`. Or you can try out `SqliteQueueDatabase` which works as a drop-in replacement for `SqliteDatabase`. Note that you cannot use transactions if you're using `SqliteQueueDatabase`, however.

I'd suggest taking a look at the post. I'd also suggest that, if you're planning to use SQLite in a multi-threaded application, you read the docs on how locking works. The SQLite docs are really good.

**Comment by rayzorben** [comment]
@coleifer Thanks for that, will look at it. In order to diagnose I ran it single threaded, and I can see the problem really clearly. Most writes happen in .02-.04 seconds. However every once in a while I will get writes that take 1-7 seconds, even up to 49 seconds!

Obviously even a timeout of 10 won't work, so hopefully the post will help out, but is there any way to diagnose why these writes are taking so long comparatively?

**Comment by evsasse** [comment]
Posting here because it is the last issue related to the database locked error. I've been dealing with this issue the last few months on my application, and here it is how I solved it. It was actually quite simple.

Reading on the web about the problem most people seem to be solving it by using `timeout=10`. Specifically my app runs on very old/cheap computers and this was simply not cutting. I needed to pass an absurdly large value to `timeout` to make it work, `timeout=100000`. 

It did raise me the question, is timeout in seconds or milliseconds? I have a couple writes that take more than a second, and thought that setting it to `10` would solve the problem, but it was only solved after `1000`.

Keep reading if you are using Qt.

This problem was terribly inconsistent for me, because somehow the way Qt handles its threads would prevent it from happening in most of the time. And it was impossible to debug it, because I couldn't reproduce it whenever I wanted. The solution was also quite simple, create some python threads (not Qt threads), and run a bunch of concurrent writes.

Hope this helps some other adventurous developers dealing with incredibly bad computers. ;)

**Comment by Zylatis** [comment]
Sorry for necro but I think it's missed in a few places, unless that SqliteExtDatabase interface really does use seconds?
https://docs.peewee-orm.com/en/latest/peewee/database.html

**Comment by coleifer** [comment]
That comment is outdated - seconds are used everywhere for sqlite timeouts.

**Comment by z3ugma** [comment]
@coleifer how do you feel about reopening this? 

I am often receiving `peewee.OperationalError: database is locked` 

```
  File "/root/searchfda/app/jobs/2_pdf_download.py", line 31, in process_row
    Job.create(
  File "/root/searchfda/venv/lib/python3.12/site-packages/peewee.py", line 6741, in create
    inst.save(force_insert=True)
  File "/root/searchfda/app/models/job.py", line 37, in save
    return super().save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/searchfda/venv/lib/python3.12/site-packages/peewee.py", line 6951, in save
    pk = self.insert(**field_dict).execute()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/searchfda/venv/lib/python3.12/site-packages/peewee.py", line 2036, in inner
    return method(self, database, *args, **kwargs)
```

this is happening during `create` calls 

I have a job queue runner that uses multiprocessing and pool - if I spawn 4 worker processes, and one of the workers is trying `create` operations then I get locked errors. I expect that I have set `timeout` and `busy_timeout` appropriately. There is some confusion on whether it's milliseconds or seconds. 

```
    DATABASE = {
        "name": DB_PATH,
        "engine": "playhouse.sqlite_ext.SqliteExtDatabase",
        "timeout": 30000,  # 30 second timeout
        "pragmas": {
            "journal_mode": "wal",
            "cache_size": -1024 * 64,  # 64MB page-cache
            "foreign_keys": 1,  # Enforce foreign-key constraints
            "journal_size_limit": 1024 * 1024 * 1,  # 1MB
            "busy_timeout": 30000,  # 30 second timeout
            "synchronous": "normal",
        },
    }
``` 

I would expect that the one worker that is trying to `create` would sit, blocking, for up to 30 seconds, waiting to insert its row.

**Comment by coleifer** [comment]
You can get locked errors regardless of the busy timeout if a deadlock is detected. You will get these instantly. Sqlite does not support concurrent writers, this is just fundamental...

**Comment by z3ugma** [comment]
Referencing a comment of yours @coleifer  at https://github.com/coleifer/peewee/issues/2949#issuecomment-2459821265 

does `create`  use db.atomic is the next thing I'm investigating 
```
For sqlite the important thing is to execute your queries that write to the database in an explicit transaction using db.atomic() - this ensures that the write lock is only held for a very brief time and prevents SQLITE_BUSY / database is locked errors.```

**Comment by z3ugma** [comment]
@coleifer in that case I would like to detect the deadlock and implement retry, unless that's something already built into one of the playhouse functions. It would be a pain to have to write this into every write/update/create/save operation in the application code so I plan to write it in my `BaseModel` class

**Comment by coleifer** [comment]
>does create use db.atomic is the next thing I'm investigating

No, you need to implement your own transaction management -- Peewee doesn't assume anything here. Keep your write transactions short and you'll minimize the risk of hitting a deadlock.

**Comment by z3ugma** [comment]
@coleifer  
```cursor().execute('COMMIT')
```

do you expect the COMMIT statement to show up in debug logs? The `BEGIN` statement does, as well as the SQL statements of the transaction 
```

('2025-01-31 18:28:09,091 - peewee - DEBUG - ('BEGIN', None)'
('2025-01-31 18:28:09,092 - peewee - DEBUG - ('INSERT INTO "job" ("created_at", "status", "updated_at", "data") VALUES (?, ?, ?, json(?))', [1738348089, <JobStatus.PENDING: 'pending'>, 1738348089, '{"module_path": "app.jobs.2_pdf_download", "function_name": "download_pdf", "args": ["K101871"]}'])'
```

**Comment by coleifer** [comment]
No, we skip over some of the APIs and call commit on the connection directly.
