### ISSUE TITLE
SqliteQueueDatabase Writer.execute() error

### ISSUE THREAD

**Issue by krikunts** [coleifer/peewee#1189]
Hello! I read your blogpost about SqliteQueueDatabase and want to try it out, but I have an error using SqliteQueueDatabase 
UnboundLocalError: local variable 'exc' referenced before assignment
https://github.com/coleifer/peewee/blob/d99f4a2649ce02da2f67769e381e51264f3c3eac/playhouse/sqliteq.py#L176
If there is exception during sql execution, the exc var is not visible outside of except block

**Comment by coleifer** [comment]
What exception is underneath the `UnboundLocalError` I wonder? I would've thought that catching Exception would suffice but it looks like whatever error is being raised extends `BaseException` instead?

**Comment by coleifer** [comment]
I couldn't replicate. I added a test-case in which invalid SQL is executed via the AsyncCursor and it all works as I'd expect. I've pushed a new release (2.8.6) in case the bug existed in the last release, however.
