### ISSUE TITLE
Update() on row affects every row and should be disallowed

### ISSUE THREAD

**Issue by HaraldNordgren** [coleifer/peewee#1192]
I used this code to update rows, and it seems that the update() function used in this way updates more than the current row. Possible every row in the model.

Maybe it should be altogether disallowed to avoid mistakes?

```
rows = Model.select().where(
    Model.status == SOME_STATUS
)

for row in rows:
    <do things, then depending on results do>
    row.update(
        job_status=SOME_NEW_STATUS
    ).execute()
```

**Comment by HaraldNordgren** [comment]
And the correct syntax in this case seems to be

    for row in rows:
        <do things>
        row.job_status = NEW_STATUS
        row.save()

**Comment by coleifer** [comment]
`update` is a classmethod, and is document as such. An update without a where clause is going to cause problems, obviously, as you found.
