### ISSUE TITLE
Is there a possibility of model.save() returning 0

### ISSUE THREAD

**Issue by Siva7891** [coleifer/peewee#1198]
1) When we try to insert a new row (i.e., model class's object) using model.save() (or model.save(forceinsert=True), will it ever return 0.? If we had primary key conflict, then we receive an exception. So can we safely assume that model.save() will always insert that object and if any problem, it would raise an exception

1) When we try to update a row (i.e., model class's object) using model.save() will it ever return 0?  Can we safely assume that model.save() will always update that object and if any problem, it would raise an exception?

I started to use peewee very recently on a small sized project. Currently, I am writing a wrapper code for all the model.save and handling the situation if the response is not '1'?  It is a right practice?

**Comment by coleifer** [comment]
Ummm...that's an interesting question, I guess... I think that you shouldn't need to even check the return value. An exception will be raised if a constraint is violated, for instance. So calls to `save()` should really be assumed to work unless an exception is raised.

**Comment by Siva7891** [comment]
Thanks for replying much faster.
