### ISSUE TITLE
ForeignKey: Do not load object if only the pk is accessed

### ISSUE THREAD

**Issue by Necoro** [coleifer/peewee#1200]
Given two models `Tweet` and `User` with the well-known relations: When accessing `tweet.user` Peewee currently always fetches the complete user.

Even in cases like
```python
if tweet.user:
    # we have a user, do something
else:
    # no user, eh?
```
and
```python
if tweet.user == someUser:
    # do something
```

In my opinion, in both cases the loading is not needed because it is sufficient to check whether `tweet.user_id is not None` and `tweet.user_id == someUser.id`, respectively. (And btw, that you can access the ids directly that way is not documented, is it? I had to inspect peewee's code to find it).

I think, that implementing this behavior should be fairly straight-forward. If you are not opposed, I'd give it a try.

(Of course, this only works with enabled foreign keys, so might be a trap for incautious sqlite users.)

**Comment by coleifer** [comment]
I think that we shouldn't break the convention that accessing the foreign key will, if necessary, load the related object. It makes the code simpler, too.

Just compare the IDs if that's all you need:

```python
if tweet.user_id:
```

Or

```python
if tweet.user_id == someUser.id:
```
