### ISSUE TITLE
bug on rollback? (peewee==2.8.7)

### ISSUE THREAD

**Issue by paulocheque** [coleifer/peewee#1208]
- Python 3.6
- peewee==2.8.7

Hi there, In the example below, two records (indexes 0 and 1) will be saved successfully in the database, although I am calling rollback.

```
db.connect()
with db.transaction() as txn:
    for index, row in enumerate(rows):
        try:
            model = MyModel()
            if index == 2:
                raise Exception('This should cancel the entire transaction, right?')
            model.save()
        except Exception as e:
            print('Rollbacking') # yes, lets rollback
            txn.rollback()
            raise # With this, no commit will be made
    print('Commiting') # not being here
    txn.commit()
db.close()
```

Is that correct?

**Comment by coleifer** [comment]
If I'm understanding your "example" code, then the following is equivalent:

```pythondb = SqliteDatabase(':memory:')

class Register(Model):
    value = IntegerField()
    class Meta:
        database = db

db.create_tables([Register])

with db.transaction() as txn:
    Register.create(value=1)
    Register.create(value=2)
    txn.rollback()
    txn.commit()

print Register.select().count()
```

When I run that script, the output is `0` as I'd expect.

**Comment by paulocheque** [comment]
Did you test with PostgresqlExtDatabase? With Python 3.6? With peewee 2.8.7?

For me the output is `2`.

```
    from playhouse.postgres_ext import PostgresqlExtDatabase
    db = PostgresqlExtDatabase()
    db.connect()
    with db.transaction() as txn:
        # User(email='a@a.com').save()
        # User(email='b@a.com').save()
        User.create(email='a@a.com')
        User.create(email='b@a.com')
        txn.rollback()
        txn.commit()
    print(User.select().count())
    db.close()

```

Any ideas?

**Comment by coleifer** [comment]
I did not test with Python 3. Maybe you can test with Python 2 and see if that works for you?

I re-ran the script and I'm still seeing 0 as the output:

```python
from peewee import *
from playhouse.postgres_ext import PostgresqlExtDatabase


#db = SqliteDatabase(':memory:')
db = PostgresqlExtDatabase('peewee_test')

class Register(Model):
    value = IntegerField()
    class Meta:
        database = db

db.create_tables([Register])

with db.transaction() as txn:
    Register.create(value=1)
    Register.create(value=2)
    txn.rollback()
    txn.commit()

print(Register.select().count())
db.drop_tables([Register])
```

Are you sure you don't have users in the db you're counting? Maybe drop then re-create the table?

**Comment by paulocheque** [comment]
Yes. Actually I tested here with Python2.7 and Python3.6 and it is working. The problem is happening because I am running this code inside a `Invoke` task. No idea of the reason!

# dropdb empty-test-db ; createdb empty-test-db
# virtualenv env2 -p python2.7
# source env2/bin/activate
# pip install psycopg2==2.7 peewee==2.8.7 invoke==0.15.0
# python a.py

# dropdb empty-test-db ; createdb empty-test-db
# python3.6 -m venv env3
# source env3/bin/activate
# pip install psycopg2==2.7 peewee==2.8.7 invoke==0.15.0
# inv test

from invoke import task


@task
def test(ctx):
    from peewee import Model, CharField
    from playhouse.postgres_ext import PostgresqlExtDatabase

    db = PostgresqlExtDatabase('empty-test-db', register_hstore=False)
    db.connect()

    class User(Model):
        email = CharField(unique=True)

        class Meta:
            database = db

    db.create_tables([User])
    print(User.select().count())

    with db.transaction() as txn:
        # User(email='a@a.com').save()
        # User(email='b@a.com').save()
        User.create(email='a@a.com')
        User.create(email='b@a.com')
        # txn.rollback()
        txn.commit()

    print(User.select().count())

    db.close()

**Comment by paulocheque** [comment]
I tested here a clean example with Py2 and Py3 and it is working. Well, no idea what is happening in my current project.

**Comment by coleifer** [comment]
@paulocheque -- glad to hear it's working for you. One thing to also consider is the possibility you had nested `transaction()` blocks...Because the semantics of nested transactions may be confusing, I'd recommend using `atomic()` instead. By using `atomic()`, peewee will automatically use a transaction or savepoint where appropriate.

**Comment by paulocheque** [comment]
In case you want to see my issue with Python 2 or 3, you can run this commands:

### Python 2
# virtualenv env2 -p python2.7
# source env2/bin/activate
# pip install psycopg2==2.7 peewee==2.8.7 invoke==0.15.0
# clear ; dropdb empty-test-db ; createdb empty-test-db ; inv create ; inv test
# inv test

### Python 3
# python3.6 -m venv env3
# source env3/bin/activate
# pip install psycopg2==2.7 peewee==2.8.7 invoke==0.15.0
# clear ; dropdb empty-test-db ; createdb empty-test-db ; inv create ; inv test
# inv test

File tasks.py (follow this name)

```
from invoke import task

from peewee import Model, CharField
from playhouse.postgres_ext import PostgresqlExtDatabase


db = PostgresqlExtDatabase('empty-test-db', register_hstore=False)
db.connect()

class User(Model):
    email = CharField(unique=True)

    class Meta:
        database = db


@task
def create(ctx):
    db = PostgresqlExtDatabase('empty-test-db', register_hstore=False)
    db.connect()
    db.create_tables([User])
    db.close()


@task
def test(ctx):
    db = PostgresqlExtDatabase('empty-test-db', register_hstore=False)
    db.connect()
    print('before', User.select().count())

    with db.transaction() as txn:
        try:
            User(email='a@a.com').save()
            User(email='a@a.com').save()
            User.create(email='c@a.com')
            raise Exception('e')
            User.create(email='d@a.com')
        except Exception as e:
            txn.rollback()
            txn.commit()
            # print('after', User.select().count())
            raise e

```

**Comment by paulocheque** [comment]
I understand now my mistake. I was using two different `PostgresqlExtDatabase` intances. One for the User model declaration and another one for the queries. Now I am single `db` variable and it is working. Thanks for the help again.
