### ISSUE TITLE
Any plans for supporting generic foreign keys?

### ISSUE THREAD

**Issue by sigurdga** [coleifer/peewee#121]
After spending a day to see if peewee is suitable for my project(s), I cannot see any way to use generic foreign keys, or any way to do a query that will join on explicit column names and values.

Tags would be a natural case for this, when you want to refer to "content type" and "object id" to be able to use tags all over without creating a lot of tables.

Django describes it as content types: https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/

The way I tried to do it was to have a CharField and an IntegerField, where the CharField contains the table name and the IntegerField the id. But I cannot figure out how to do the queries, as I am not able to join two tables without a foreign key.

**Comment by wonderbeyond** [comment]
I've made a simple generic foreign key implementation: https://gist.github.com/wonderbeyond/0e1f402b7595e0b4f9f653260fed029c#file-index-md

**Comment by crazy2k** [comment]
Why was this removed? Is there some other "official" way to handle the use case that @wonderbeyond's code solves?

**Comment by coleifer** [comment]
>Why was this removed?

In my opinion, it's a gross hack and really does not belong in production-worthy code. It cannot be optimized in a generic way. It's only helpful for the simplest use-cases, but is very easy to have a footgun moment. A well-designed schema will obviate the need for this.

Implementation-wise, it requires a centralized registry of sorts to indicate the "content-type" that an arbitrary identifier references.

Also muddies the water in terms of introspection.

**Comment by crazy2k** [comment]
Thanks for the reply!
