### ISSUE TITLE
Peewee writing to peewee.db not my.db

### ISSUE THREAD

**Issue by valleyrock** [coleifer/peewee#1223]
When I insert items to db, it writes to peewee.db not my.db

**Comment by coleifer** [comment]
Check that your model is specifying the database as a meta option:

```python
my_db = SqliteDatabase('my.db')

class MyModel(Model):
    class Meta:
        database = my_db
```

**Comment by coleifer** [comment]
For what it's worth (I can't believe I'm even taking the time to type this), don't you imagine if something as fundamental as writing to the "wrong" database were happening, that this would be a massive bug? That the tests would probably be failing? Etc? Did it not occur to you that you had made an error?

**Comment by valleyrock** [comment]
sorry coleifer.. you correction worked and has been working. Just forgot to comeback and say so.

To think, I wanted to learn sqlalchemy.... not worth it. Peewee is good enough. Just having difficulty sorting my datetime values 2017-04-07T01:51:00.000Z all the way to time. It sorts the dates but the time is always an issue I tried everything.

**Comment by coleifer** [comment]
Are you using 24-hour encoding? They should sort correctly simply due to being in order alphabetically. Of course if time-zones are introduced that may not be the case.
