### ISSUE TITLE
PostgreSQL - range types

### ISSUE THREAD

**Issue by Phibedy** [coleifer/peewee#1227]
Hi,
would like to use [range types](https://www.postgresql.org/docs/9.3/static/rangetypes.html) (in my case datetime with time zone), but I am not sure how to implement it for all types.
Any help appreciated :)

**Comment by coleifer** [comment]
I'm going to pass on implementing these right now, though I may revisit this feature in the future. If you're looking for ideas on implementation, I'd suggest checking out the other custom field types in `playhouse.postgres_ext`.
