### ISSUE TITLE
Default Snake Case Table Names

### ISSUE THREAD

**Issue by joshuamcginnis** [coleifer/peewee#1228]
I have several tables that have camelcased names (`FooType`, `FooScoreAttributes`, etc) and on table creation, the table names are: `footype` and `fooscoreattributes`.

Is there a way to have all table names snake cased  like: `foo_type`  without having to specify the `db_table` in each model?

**Comment by coleifer** [comment]
Sorry for the inconvenience, but you'll need to specify the `db_table` attribute.

Alternatively, you can pass in a function using `db_table_func` that does the conversion the way you'd prefer. Something like:

```python
def make_table_name(model_cls):
    name = model_cls.__name__
    # change name to snake-case
    return new_name

class BaseModel(Model):
    class Meta:
        db_table_func = make_table_name

class FooType(BaseModel):
    ...

class FooScoreAttributes(BaseModel):
    ...
```

**Comment by joshuamcginnis** [comment]
@coleifer Thanks! `db_table_func` is just what I need.
