### ISSUE TITLE
Where clause cannot handle dict_values (dict view - python3)

### ISSUE THREAD

**Issue by dhiana** [coleifer/peewee#1230]
When trying to use a where clause comparing a field to a dict_value, I get this error.

peewee.ProgrammingError: syntax error at or near "'dict_values([‘’foo’’, “bar’’])’”
LINE 1: …baz = ‘quz’)) AND ("t1”.”qux” IN 'dict_valu...

https://docs.python.org/3.0/library/stdtypes.html#dict.values

My code was working on python 2, but when modifying iteritems to items to use python 3, now I need to force list() on the dict_values.

**Comment by coleifer** [comment]
Convert it to a list explicitly:

```python
.where(SomeModel.field << list(some_dict.values()))
```
