### ISSUE TITLE
Why "from peewee import *" doesn't import InsertQuery?

### ISSUE THREAD

**Issue by TwoAnts** [coleifer/peewee#1232]
```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from peewee import *
>>> InsertQuery()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'InsertQuery' is not defined
>>> from peewee import InsertQuery
>>> InsertQuery()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes at least 2 arguments (1 given)
>>> 
```
`from peewee import *` doesn't import InsertQuery, 
but `from peewee import InsertQuery` does.  
I have tested it on Python 2.7.6 and Python 2.7.12 , got the same result.  
A little curious.

**Comment by coleifer** [comment]
Typically you would not import an InsertQuery directly, but use the `insert()` model method.

**Comment by coleifer** [comment]
Please read the docs.

**Comment by TwoAnts** [comment]
I think I have found my answer from http://stackoverflow.com/questions/44834/can-someone-explain-all-in-python.
Maybe I'm a little stupid here, now I'm clear. I see  `__all__` is used in peewee.py and other variables will not  be imported by `from peewee import *`.
Thanks for your patience.

**Comment by coleifer** [comment]
I see - so you were less interested, then, in using `InsertQuery` and were more interested in the mechanics of the Python import statement...

**Comment by TwoAnts** [comment]
😁
