### ISSUE TITLE
Add a way to copy over where clause between queries

### ISSUE THREAD

**Issue by tasn** [coleifer/peewee#1234]
Hi,

I want to be able to do:
```
a = Model.select().where(COMPLEX_CONDITION_HERE)
Model.insert(a=1).inherit(a)

```
Not sure if this is the best API, but this is a start.

There are two main places where this is useful:
1. When you want to do two manipulations on the same consecutively. For example, run a select, do some calculations, and if condition X applies, delete all of the entries that match the query without having to repeat yourself.
2. This one is more important because not having it here can introduce bugs: when the select query is abstracted away, either by a helper function that conditionally returns a different set, and then you can't know what is the set you have, so you can't easily delete it, or even in the most by sense by the built it "related_set". So for example, a.related_set.delete() is a useful operation, and at the moment people would have to resort to reimplementing the implementation of related_set to delete all related objects.

I asked on IRC and there were no database-only solutions to this problem. I.e the best solutions proposed were fetching all of the entries and then acting on them using the "in" operator, or alternatively just deleting/updating the objects one by one. Both are slow and unacceptable.

I hope this makes sense for the project.

**Comment by coleifer** [comment]
Well, for one, INSERT queries don't take a WHERE clause.

But to your point, just put the expressions together and assign them to a variable...

```python
COND = (MyModel.foo == 'bar') & (MyModel.baz < 4)
q1 = MyModel.select().where(COND)
MyModel.delete().where(COND).execute()

# or
MyModel.delete().where(MyModel.id << q1)
```
