### ISSUE TITLE
any documentation that doesn't require flask.

### ISSUE THREAD

**Issue by faststare** [coleifer/peewee#1237]
it gets complicated that you mix peewee and flask. not all developer develop web app nor flask.
documentation should be simple like  ponyorm docs.
it seems that you didn't the import this mantra with your package that you develop.
peewee have potential but too much quirks in the docs therefore new developer who try peewee will stay because of messy documentation.

I'm just suggest to improve the quality of peewee documentation.
thanks

**Comment by coleifer** [comment]
What are you talking about? Hardly anything is Flask-specific!

**Comment by coleifer** [comment]
Maybe you're talking about the example application, which is a flask application?

At any rate, the documentation is intentionally designed to be framework- or implementation-agnostic. It doesn't matter if you're doing batch processing, ETL, web, whatever....the docs describe the APIs and mechanics of peewee and don't tie you to a particular usage scenario.

**Comment by faststare** [comment]
how I map specific user with name column with insert function?
example:
Message.insert(msg='example', user_id=1#<--need to replace an user name here)
example schema:
Users:
    username = CharField()
    password = CharField()
Msg:
    user_id = ForeignKey(Users, related_name='username'')
    msg = Charfield()
    timestamp = DateTimeField()
