### ISSUE TITLE
Question: Can I use FlaskDB.Model in non-Flask process?

### ISSUE THREAD

**Issue by devkhan** [coleifer/peewee#1240]
I have defined a model `X` by subclassing `FlaskDB.Model`, and then I want to access one of the instances in a celery worker process. Is it possible, and if so, how should I go about that?

I've already tried that, and receiving an `AttributeError: Cannot use uninitialized Proxy.`. But I guess that is because of not opening a database connection, which also sparks the question that how should I use the database in the worker as there is no Flask app context to provide?

Any help is highly appreciated.

**Comment by coleifer** [comment]
This is do-able. You'll need to initialize the Flask application, though. Something like this:

```
with app.app_context():
    # Try using the database here.
```

This definitely isn't a bug, so I'm closing as this type of question belongs on Stackoverflow.
