### ISSUE TITLE
Automatically creating all tables, in right order.

### ISSUE THREAD

**Issue by tomvlk** [coleifer/peewee#1252]
I don't know if this was suggested before, but it would be great to have a function to create all tables, that automatically orders them in dependencies (like foreign keys etc.) so you would be able to have a dynamic application with dynamic models easily running without having to struggle with foreign keys while creating tables.

**Comment by coleifer** [comment]
`db.create_tables()` does just that.

**Comment by tomvlk** [comment]
I'm very sorry, thanks :+1:
