### ISSUE TITLE
How should I structure my peewee postgres database for hosting on heroku

### ISSUE THREAD

**Issue by rahul3103** [coleifer/peewee#1253]
http://stackoverflow.com/questions/43505529/peewee-and-postgres-on-heroku-not-able-to-create-table

I tried a lot but I was not able to run a simple code with peewee and postgres on heroku. Without database my app is running on heroku but with peewee and database its not running. If you can help me a little bit it will be great. The app [link](https://github.com/rahul3103/test-heroku)

**Comment by coleifer** [comment]
Responded on SO. Issue had nothing to do w/your peewee setup.
