### ISSUE TITLE
Huge bug - needs high priority

### ISSUE THREAD

**Issue by Chemmic** [coleifer/peewee#1257]
Hello, 
Im using ur program since 2 years now, I figured out that there exists a huge bug wich fucks the whole programe over.
You really Need to work on it and fix it asap.
The program is really unusable without Fixing it so please get your lazy ass off and fix it.

- Chemmic

**Comment by coleifer** [comment]
LOL. I'm sorry your shit got fucked so hard. Peewee doesn't fuck very much but when it does it fucks **hard**.

Can you tell me about the bug?

**Comment by coleifer** [comment]
Please comment with some details and I'll re-open for discussion.
