### ISSUE TITLE
Add `RetryOperationalError` support for `playhouse.db_url.connect`.

### ISSUE THREAD

**Issue by futursolo** [coleifer/peewee#1259]
Currently, I am working on a project using peewee object model built against both MariaDB(for production) and SQLite(for testing). Using `playhouse.db_url.connect` seems like to be the best solution.

However, when using the MariaDB backend, after a certain amount of time, the service starts to constantly output `Error 2006: MySQL server has gone away` until I restart the service. After some researches, I found that the documentation says it can be mitigated by adding `RetryOperationalError` mixin to the database class, but it cannot be used with `playhouse.db_url.connect`.

Please add `RetryOperationalError` support for `playhouse.db_url.connect`.

**Comment by coleifer** [comment]
You can do this yourself. I assume you have a MySQLDatabase subclass that you intend to use.... You can, then:

```python

from playhouse.db_url import connect, register_database

register_database(MySQLDatabaseSubClass, 'mysqlretry')
db = connect('mysqlretry://....')
```
