### ISSUE TITLE
Aiopeewee

### ISSUE THREAD

**Issue by kszucs** [coleifer/peewee#1260]
I've created an asyncio wrapper for peewee, adapted ideas from torpeewee.
It isn't feature complete yet, but I'm working on it.

@coleifer Could You give me a general feedback?

I need to duplicate a lot of code (due to asyncio nature), but I'm wondering how could I reduce it. 
Could You give some advice?

**Comment by OOPMan** [comment]
@kszucs Have you seen https://github.com/05bit/peewee-async ?

**Comment by kszucs** [comment]
Sure. Peewee-async uses another approach, with a centralized manager object.

**Comment by OOPMan** [comment]
@kszucs Neat. Does aiopeewee only support Postgres right now?

**Comment by kszucs** [comment]
Only Mysql, but postgres support is easy to implement - need to port only a couple of methods.
