### ISSUE TITLE
Encryption with python3 throws TypeError

### ISSUE THREAD

**Issue by cym13** [coleifer/peewee#1262]
Hi,

the AESEncryptedField in playhouse/fields.py is broken in python3.

Line 320 we see:

            key = key + bytes(' ') * (32 - len(key))

but bytes(' ') isn't valid python3 and will throw a TypeError.

**Comment by coleifer** [comment]
This field has been removed in the latest release, 2.10.0. For details and explanation of why, see https://github.com/coleifer/peewee/releases/tag/2.10.0
