### ISSUE TITLE
Bad Magic Number

### ISSUE THREAD

**Issue by ahopkins** [coleifer/peewee#1266]
I created a new virtualenv to test out peewee. I was simply trying to follow the [Quick Start](http://docs.peewee-orm.com/en/latest/peewee/quickstart.html).

    mkvirtualenv peweetest -p python3
    python
    >>> import peewee
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: bad magic number in 'peewee': b'\x03\xf3\r\n'

I have python 3.5 running (I also tried with 2.7 and 3.6), and peewee is on v 2.10.0.

Anyone else see this? Ideas?

**Comment by ahopkins** [comment]
It seems maybe someone should look into the pypi package. I installed via git, and that seemed fine.

**Comment by coleifer** [comment]
Thanks for bringing this to my attention. Pushed a new minor release and verified it is working correctly for me using 2.7 and 3.6 + PyPI.
