### ISSUE TITLE
Peewee >= 2.4.3 is required. Found version ...

### ISSUE THREAD

**Issue by thebalthasar** [coleifer/peewee#1277]
The instruction which is reported while doing the version check is misleading. This is the runtime error and its message:
RuntimeError: Peewee >= 2.4.3 is required. Found version 2.10.1. Please update by running pip install --update peewee

Should be instead:
**pip install peewee --upgrade**

The error comes from comparing versions in line 58 of sqlite_web.py

>>>version_old='2.4.3'
>>>version_new='2.10.1'
>>>version_new>version_old 
**False**
A better comparison would be:
>>> from distutils.version import StrictVersion
>>>StrictVersion(version_new) > StrictVersion(version_old)
**True**

Thank you for your work!
:-)

**Comment by coleifer** [comment]
Yes, this is fixed in sqlite-web. See the issue there: https://github.com/coleifer/sqlite-web/issues/30

**Comment by coleifer** [comment]
sqlite-web 0.1.8 was released as well, fixing the issue if you try again.
