### ISSUE TITLE
[Feature request] pg8000 support

### ISSUE THREAD

**Issue by vaygr** [coleifer/peewee#1280]
It'd be nice to have one pure-Python PostgreSQL driver supported to minimize amount of dependencies installed on the system.

I think [pg8000](https://github.com/mfenniak/pg8000) is a great candidate.

**Comment by vaygr** [comment]
Is it something not considered as a high priority at the moment?

I've also seen people trying to implement this, e.g. [here](https://www.quora.com/Is-it-possible-to-swap-in-a-pg8000-backend-for-psycopg2-when-using-Peewee).

**Comment by coleifer** [comment]
You can implement it by doing something like the above code snippet.

```python
class PostgresqlDatabasePG8000(PostgresqlDatabase):
    ...
```

**Comment by vaygr** [comment]
Yeah, but is there any chance it could get official support in peewee in the future?

**Comment by deltaGPhys** [comment]
I see that this was closed as 'completed' - does that mean that I can use peewee with pg8000? I've not been able to find any docs on how to do that

**Comment by coleifer** [comment]
You’ll want to consult the docs here: http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver
