### ISSUE TITLE
CompositeKey primary key not inheritable

### ISSUE THREAD

**Issue by rhkubiak** [coleifer/peewee#1281]
I have a model A in which the primary key is defined via CompositeKey. Model B inherits from model A. A database table generated from B does not have a primary key. 
The things get better if the 'elif' in the code below (peewee version 2.10.1) is replaced with just an 'if':

        composite_key = False
        if model_pk is None:
            if parent_pk:
                model_pk, pk_name = parent_pk, parent_pk.name
            else:
                model_pk, pk_name = PrimaryKeyField(primary_key=True), 'id'
        elif isinstance(model_pk, CompositeKey):
            pk_name = '_composite_key'
            composite_key = True

What do you think?

**Comment by coleifer** [comment]
Thanks for reporting this. I've pushed your suggested fix along with a test-case.
