### ISSUE TITLE
Facilitate case insensitive searches

### ISSUE THREAD

**Issue by Naatan** [coleifer/peewee#1284]
The docs state:

> LIKE and ILIKE with SQLite
> Because SQLite’s LIKE operation is case-insensitive by default, peewee will use the SQLite GLOB operation for case-sensitive searches. The glob operation uses asterisks for wildcards as opposed to the usual percent-sign. If you are using SQLite and want case-sensitive partial string matching, remember to use asterisks for the wildcard.

Unfortunately it does not touch on the not at all unlikely scenario of wanting to do case insensitive LIKE queries. It would be nice if peewee touched in its docs, ideally facilitating it, otherwise just stating that you should use `SQL()`.

**Comment by coleifer** [comment]
For case-insensitive LIKE you would just use ILIKE.

**Comment by Naatan** [comment]
You should make that clearer in the docs, this currently isn't evident.

**Comment by coleifer** [comment]
ILIKE is called ILIKE because it's case-insensitive.

**Comment by Naatan** [comment]
I get that now, but that's not self-evident. And it's not something you can search the docs for because nowhere does it say the word "insensitive".
