### ISSUE TITLE
Checking record exist

### ISSUE THREAD

**Issue by kadnan** [coleifer/peewee#1294]
I know about exception thrown in this regard, just want to know whether there's some `count` or `exists()` method to check whether some record returned or not?

**Comment by coleifer** [comment]
ffs man documentation

* http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectQuery.exists
* http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectQuery.count

**Comment by dsmurrell** [comment]
I was searching for the same thing (I don't usually RTFM right away either). Just to let you know that your links don't take you to the right place on the page as I assume the # is supposed to do.

**Comment by coleifer** [comment]
* http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectBase.exists
* http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectBase.count

tl/dr

```python

query = User.select().where(User.username == 'reads-the-manual')
if query.exists():
    print('there are %s users who %s' (query.count(), 'read the manual'))
```

**Comment by kadnan** [comment]
Funny thing is that I had to google something similar and I found my own opened issue 😆

**Comment by coleifer** [comment]
Hell yeah. I've had that happen once or twice myself.
