### ISSUE TITLE
flask note-taking app FTSModel classes must use the default `docid` primary key.'

### ISSUE THREAD

**Issue by quah6o** [coleifer/peewee#1297]
Hello together,

I'm new to python and only have a few basic programming skills.
I found this tutorial which creates a [flask note-taking app](http://charlesleifer.com/blog/saturday-morning-hacks-adding-full-text-search-to-the-flask-note-taking-app/). It is seperated in three steps. The first two steps work without any problems.
The complete project can be downloaded in [this gist](https://gist.github.com/coleifer/d93d6c43e59698d149c0).

But when I run the third step now, the following happens:

    (.p2) qua@mbp:0:~/python/flask-note-v3$ python main.py
    Traceback (most recent call last):
      File "main.py", line 5, in <module>
        from models import FTSNote
      File "/Users/qua/python/flask-note-v3/models.py", line 125, in <module>
        class FTSNote(FTSModel):
      File "/Users/qua/.p2/lib/python2.7/site-packages/peewee.py", line 4855, in __new__
        cls.validate_model()
      File "/Users/qua/.p2/lib/python2.7/site-packages/playhouse/sqlite_ext.py", line 281, in validate_model
        'FTSModel classes must use the default `docid` primary key.')
    peewee.ImproperlyConfigured: FTSModel classes must use the default `docid` primary key.
    (.p2) qua@mbp:1:~/python/flask-note-v3$ python app.py
    (.p2) qua@mbp:0:~/python/flask-note-v3$

I try to get this project working and modify it to suit my needs. By that I hope learning a bit more of python.

Can you help me? (I already asked this on /r/learnprogramming/)

Regards,
Qua

**Comment by coleifer** [comment]
Ahh yeah, the code is probably a bit out-dated and does not reflect what I've since learned about some best practices for the full-text search extension. Let me see about updating things.

**Comment by coleifer** [comment]
Ahh shit, I see I already left a note on code compatibility at the top of the post. I'm going to leave this alone for now, as I don't have time to go back through the code to update it all. Apologies for leaving you hanging -- I'll try to post an update, and when I do I'll update this ticket.

**Comment by quah6o** [comment]
Ah I should read more carefully. I will use a older version for now. Thanks!
