### ISSUE TITLE
Idea: Table prefixing

### ISSUE THREAD

**Issue by tomvlk** [coleifer/peewee#1300]
Hello there,
First of all thanks for the simple and yet so powerful ORM!
I got one of our users that is asking if I can provide database table prefix configuration for my application. The application I'm talking about is PyPlanet, (issue from the user: https://github.com/PyPlanet/PyPlanet/issues/378).

I can most probably fix this myself with some kind of hacky method that will override the table name generation, but instead it would be cool to have this feature in Peewee itself where you can give the option to prefix all the tables with a prefix given in a configuration. (Also, I don't really want to hack this deep in Peewee).

I'm curious how you think about the idea.

**Comment by coleifer** [comment]
To customize the table name on a one-off basis, you set the `db_table` option on the model's inner `Meta` class.

To set the table name dynamically, you can actually specify a different `Meta` attribute `db_table_func`. This should be a callable that receives the newly-created `Model` class, and returns a string to use as the table name.

I think this should probably accomplish what you want.
