### ISSUE TITLE
can not use ArrayField when I imort PostgresqlExtDatabase?

### ISSUE THREAD

**Issue by wdrich** [coleifer/peewee#1301]
when I import PostgresqlExtDatabase like this:
 from playhouse.postgres_ext import PostgresqlExtDatabase

that say:"NameError: name 'ArrayField' is not defined"

thanks

**Comment by coleifer** [comment]
Um...are you referencing `ArrayField` somewhere in your module? `ArrayField` is defined in `playhouse.postgres_ext` so to use it you'll need to import it along with `PostgresqlExtDatabase`.

**Comment by wdrich** [comment]
after that, I import ArrayField with:
from playhouse.postgres_ext import ArrayField

that say:"peewee.ProgrammingError: hstore type not found in the database. please install it from your 'contrib/hstore.sql' file"

thanks

**Comment by wdrich** [comment]
other wise:
I did not use 'hstore'

**Comment by wdrich** [comment]
That is ok， NOW！！

i forgot add hstore extension
use ‘ create extension hstore’
