### ISSUE TITLE
Swap databases to models

### ISSUE THREAD

**Issue by jbremson** [coleifer/peewee#1309]
I would like to test my models against a test db, but I'm not seeing an easy way to swap the db handle in the models.

How do I do this?

**Comment by jbremson** [comment]
I figured this out after some digging in the code. See my PR for a small change to the docs.

**Comment by jbremson** [comment]
It would be nice if there was a way to change the db handle on an application wide basis.  The Using context manager loses scope when calling outside functions. 

I will take a stab at trying to implement this. Any advice on how to do it?

**Comment by coleifer** [comment]
> It would be nice if there was a way to change the db handle on an application wide basis.

You can always implement an abstraction layer that handles this kind of thing. Or use the `Proxy` object:

```python
db = Proxy()
db_1 = SqliteDatabase('one.db')
db_2 = SqliteDatabase('two.db')

class MyModel(Model):
    class Meta:
        database = db

class AnotherModel(Model):
    class Meta:
        database = db

db.initialize(db_1)  # Now MyModel and AnotherModel are using db_1

# do some stuff....

db.initialize(db_2)  # Now they're using db_2...
```
