### ISSUE TITLE
Peewee ignoring db_table on create_tables()

### ISSUE THREAD

**Issue by timlehr** [coleifer/peewee#1313]
Hi Charles,

first: thanks for your hard work on peewee. It's a lovely package that already saved us a lot of time. :+1: 

However, we have an issue similiar to #201 where our uppercase db names are converted to lowercase, even though we specify an explicit uppercase name in the `db_table` attribute of the `meta` class.

```
from luti.core.models.basemodel import BaseModel

from peewee import *

class Collection(BaseModel):
	filter = CharField()
	id = PrimaryKeyField(db_column='idCollection')
	longname = CharField(null=True)
	path = CharField()

	class Meta:
		db_table = 'Collection'
```

Whatever we put in `db_table` will be used when we create the tables with `create_tables()`, but it will ignore any uppercase characters and lowercase them. We are using Python 2.7, Peewee 2.10.0 and MariaDB 10.1.24 / MySQL 5.7.18 servers for our test databases. Any clues?

**Comment by coleifer** [comment]
It appears to be working as I'd expect. In the example below the database is reporting a table named "Foo" and the SELECT query is querying the "Foo" table (successfully).

```python
In [1]: from peewee import *

In [2]: db = SqliteDatabase('/tmp/foo.db')

In [3]: class Foo(Model):
   ...:     value = TextField()
   ...:     class Meta:
   ...:         db_table = 'Foo'
   ...:         database = db
   ...:         

In [4]: db.create_tables([Foo])

In [5]: db.get_tables()
Out[5]: [u'Foo']

In [6]: Foo.create(value='x')
Out[6]: <__main__.Foo at 0x7fdd08157ed0>

In [7]: Foo.select()
Out[7]: <class '__main__.Foo'> SELECT "t1"."id", "t1"."value" FROM "Foo" AS t1 []

In [8]: Foo.get()
Out[8]: <__main__.Foo at 0x7fdd0815eb10>

```

**Comment by timlehr** [comment]
Hi Charles, 
I found the issue after trying the deployment on a Linux machine. 
MySQL on Windows makes DB table names lowercase by default (for some reason).
You have to manually change that option in the ini-file.

Sorry for the trouble!

Cheers,
Tim
