### ISSUE TITLE
peewee.OperationalError: (1060, "Duplicate column name )

### ISSUE THREAD

**Issue by dracarysX** [coleifer/peewee#1316]
Consider the following models:

```python
class Author(Model):
    id = PrimaryKeyField()
    name = CharField(max_length=50)

    class Meta:
        db_table = 'Author'

class Book(Model):
    id = PrimaryKeyField()
    name = CharField(max_length=255)
    author = ForeignKeyField(Author)

    class Meta:
        db_table = 'Book'
```

Follow the models, I execute this query:

```python
Book.select(Book.id, Author.id).join(Author).limit(10).count()
```

some error throw `peewee.OperationalError: (1060, "Duplicate column name 'id')`. then i check the query sql like this:

```sql
SELECT COUNT(*1) FROM (SELECT `t1`.`id`, `t2`.`id` FROM `Book` AS t1 INNER JOIN `Author` AS t2 ON (`t1`.`author_id` = `t2`.`id`) LIMIT 10) AS wrapped_select
```

So, i konw this error is SQL as alias table SQL syntax error. But i think this case, we can empty the select conditions then excute count.

**Comment by coleifer** [comment]
Try aliasing one of the columns, Book.id.alias('book_id') or Author.id.alias('author_id').
