### ISSUE TITLE
UpdateQuery FROM clause support

### ISSUE THREAD

**Issue by rammie** [coleifer/peewee#1321]
Turns out postgresql's Update statements support a FROM clause that is useful for doing bulk updates. I don't think this is standard SQL.

I looked through the documentation and couldn't find any examples of it. I perused the generate_update function in peewee and didn't see and SQL('FROM')'s in there so I assume that this is not supported.

I found this on the group, which is a related question. https://groups.google.com/forum/#!topic/peewee-orm/ov4M434fZ7U

It would be nice if peewee supported this. I was wondering if you had any suggestions on how to achieve this.

Standard disclaimer: I love peewee! It's my favorite ORM ever.

**Comment by rammie** [comment]
Doesn't seem worth the trouble. The subquery would likely be cached if it appears twice. Sorry for the noise.

**Comment by maaaks** [comment]
Well, I think it should be added to Peewee. Currently I don't see any ways in Peewee to do what `UPDATE FROM` does — to update one table using a joined table not only in `WHERE` (which could really be done with subqueries), but also as data source for expression in `SET`.

@coleifer, is there any chance that you will add this?

**Comment by coleifer** [comment]
It gets a bit weird...SQLite does not support fully-qualified column names in the SET portion of the query. I *believe* it's possible to accomplish anything you need without the `FROM` clause that would normally be possible using sub-selects or common-table-expressions. Closing.
