### ISSUE TITLE
Error when I run:- run_example in the twitter app

### ISSUE THREAD

**Issue by Summerian-Winter** [coleifer/peewee#1323]
Hi,
I'm new to peewee and when I run the run_example in the example twitter app I get an error somewhere in the line 131 but can't seem to find what exactly.

**Comment by coleifer** [comment]
Without you sharing the full traceback I have no way of helping you. Are you new to python?

**Comment by Summerian-Winter** [comment]
Here's what I get. I should have shared the traceback yes, but I ran the code as it was without changing anything so I thought something might have gone wrong after one of the commits. Btw, is there a better way of sharing the traceback. Cheers!

![1](https://user-images.githubusercontent.com/30374624/28891709-5e7eee6a-77c3-11e7-9f02-e702a412dd6e.JPG)
![2](https://user-images.githubusercontent.com/30374624/28891710-5e7f201a-77c3-11e7-8719-f7766e8283f4.JPG)

**Comment by coleifer** [comment]
In the docs, there is a section on explicitly creating the tables: http://peewee.readthedocs.io/en/latest/peewee/example.html#creating-tables

The docs read:

> In order to start using the models, its necessary to create the tables. This is a one-time operation and can be done quickly using the interactive interpreter. We can create a small helper function to accomplish this:

```python
def create_tables():
    database.connect()
    database.create_tables([User, Relationship, Message])
```

> Open a python shell in the directory alongside the example app and execute the following:

```pycon
>>> from app import *
>>> create_tables()
```

So you'll `cd` into the twitter example and open a python interpreter and run the above 2 lines of code.

**Comment by Summerian-Winter** [comment]
Hi Charles,

I appreciate the help but wouldn't it be better if the actual code in the
example had the create_tables() called in the __name__ == '__main__'
section, so every time someone tripped at this problem, they wouldn't
bother you for it.
