### ISSUE TITLE
execute_sql, unexpected result

### ISSUE THREAD

**Issue by pepelisu** [coleifer/peewee#1325]
Hi, 
While I was trying to perform a cleaning operation in a database, specifically removing the duplicates in a SQLite database.
Using a piece of code similar to this:
```python
db.execute_sql("DELETE FROM tableName WHERE rowid NOT IN (SELECT MIN(rowid) FROM tableName GROUP BY 'column1','column2','column3')")
```
The result is a complete delete of all entries in the database but the first one. It seems that execute_sql is not performing the grouping. 
If I run exactly the same query in the database with sqlite via terminal the result is the expected one. All the duplicated records are removed. 
I am doing something wrong or is there a bug?

**Comment by coleifer** [comment]
There must be a problem with the query as written. Peewee doesn't do anything to SQL queries passed directly to execute_sql() -- they are passed to the driver, which then executes them. I'd suggest working on the query in the database shell until you get the desired results.

**Comment by pepelisu** [comment]
That is what I tried to explain. Running the query in the database shell I get the desired results. But running exactly the same query inside execute_sql does not work as expected. 
Which driver are you using?
