### ISSUE TITLE
Potential mistake in docs regarding operator parameter in CompoundSelect

### ISSUE THREAD

**Issue by aniketpanjwani** [coleifer/peewee#1326]
I'm using peewee 2.9.1 with Python 3.5.2 on Linux Mint 18 to access a PostgreSQL 9.6.2 database hosted on AWS RDS.

The [documentation for CompoundSelect](http://docs.peewee-orm.com/en/latest/peewee/api.html#CompoundSelect) states that one should use a Node instance for the operator parameter in a compound query. I tried each of SQL('UNION'), SQL('INTERSECTION'), and SQL('EXCEPT'), but kept getting errors from psycopg2 and peewee with the syntax of the formatted SQL.

An example of the formatted SQL is below:

```
>>> print(inds.sql()
```
`('(SELECT "t1"."id", "t1"."recid", "t1"."year", "t1"."papername", "t1"."timeofday", "t1"."newspaper_id" FROM "newspaperyears" AS t1 WHERE ("t1"."year" = %s)) <peewee.SQL object at 0x7f2d702d6518> (SELECT "t3"."id", "t3"."recid", "t3"."year", "t3"."papername", "t3"."timeofday", "t3"."newspaper_id" FROM "newspaperyears" AS t3 INNER JOIN "newspapers" AS t4 ON ("t3"."newspaper_id" = "t4"."id") WHERE ("t3"."year" = %s))', [1952, 1952])`

It seems like either peewee's or psycopg2's SQL generation was directly inserting a reference to the Node instance. Noticing this, I instead simply used 'EXCEPT' instead of SQL('EXCEPT') for the operator parameter, and I was able to get the CompoundSelect query that I wanted.

I checked the commit history, and it didn't seem like there has been anything addressing this type of issue between 2.9.1 and 2.10, but my apologies if I missed something.

**Comment by coleifer** [comment]
Wow, no the docs are definitely wrong. I'll update them, thanks.
