### ISSUE TITLE
insert many and ids

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#1327]
Hi!
Is it possible to insert many records and get them id list?
Or maybe id of the last inserted. Or get the next identity value?
In one transaction. In postgresql.
Would be awesome!

**Comment by coleifer** [comment]
Currently if you are using Postgresql you can write:

```python
query = User.insert_many([{...}, {...}, {...}]).return_id_list()
ids_inserted = query.execute()
```

It's admittedly a weird API and not very flexible. In 3.0a it is the default to return the id list when the database supports the returning clause.
