### ISSUE TITLE
3.0a

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1328]
Hello,

Exciting to see an upgrade path.  I thought I would try it out.  
I removed the 2.10 version of peewee and installed 3.0a
Note, my app runs fine with 2.10.1, and I understand I may need to change some stuff to get to 3.0a.
Just thought I would start the process.  Thanks for the great product!

pip uninstall peewee==2.10.1
pip install git+https://github.com/coleifer/peewee.git@3.0a

Ran into an error ... not sure what it is about, other than not there :-)

Looks like
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:31:30 web.1   |      from peewee import PrimaryKeyField
14:31:30 web.1   |  ImportError: cannot import name PrimaryKeyField

is the basic problem.  

14:31:28 web.1   |  [2017-08-14 14:31:28 -0400] [9756] [INFO] Starting gunicorn 19.7.1
14:31:28 web.1   |  [2017-08-14 14:31:28 -0400] [9756] [INFO] Listening at: http://0.0.0.0:5000 (9756)
14:31:28 web.1   |  [2017-08-14 14:31:28 -0400] [9756] [INFO] Using worker: gevent
14:31:28 web.1   |  [2017-08-14 14:31:28 -0400] [9759] [INFO] Booting worker with pid: 9759
14:31:28 web.1   |  [2017-08-14 14:31:28 -0400] [9761] [INFO] Booting worker with pid: 9761
14:31:29 web.1   |  [2017-08-14 14:31:29 -0400] [9763] [INFO] Booting worker with pid: 9763
14:31:29 web.1   |  [2017-08-14 14:31:29 -0400] [9764] [INFO] Booting worker with pid: 9764
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9761] [ERROR] Exception in worker process
14:31:30 web.1   |  Traceback (most recent call last):
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:31:30 web.1   |      worker.init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:31:30 web.1   |      super(GeventWorker, self).init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:31:30 web.1   |      self.load_wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:31:30 web.1   |      self.wsgi = self.app.wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:31:30 web.1   |      self.callable = self.load()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
14:31:30 web.1   |  /gunicorn/app/wsgiapp.py", line 65, in load
14:31:30 web.1   |      return self.load_wsgiapp()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:31:30 web.1   |      return util.import_app(self.app_uri)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:31:30 web.1   |      __import__(module)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/main.py", line 22, in <module>
14:31:30 web.1   |      import xyzzy_admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/xyzzy_admin.py", line 9, in <module>
14:31:30 web.1   |      from flask_peewee.admin import Admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2
14:31:30 web.1   |  .7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:31:30 web.1   |      from flask_peewee.filters import FilterForm
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:31:30 web.1   |      from flask_peewee.forms import BaseModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:31:30 web.1   |      from wtfpeewee.orm import ModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.
14:31:30 web.1   |  framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:31:30 web.1   |      from peewee import PrimaryKeyField
14:31:30 web.1   |  ImportError: cannot import name PrimaryKeyField
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9759] [ERROR] Exception in worker process
14:31:30 web.1   |  Traceback (most recent call last):
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:31:30 web.1   |      worker.init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:31:30 web.1   |      super(GeventWorker, self).init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:31:30 web.1   |      self.load_wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:31:30 web.1   |      self.wsgi = self.app.wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:31:30 web.1   |      self.callable = self.load()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
14:31:30 web.1   |  /gunicorn/app/wsgiapp.py", line 65, in load
14:31:30 web.1   |      return self.load_wsgiapp()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:31:30 web.1   |      return util.import_app(self.app_uri)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:31:30 web.1   |      __import__(module)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/main.py", line 22, in <module>
14:31:30 web.1   |      import xyzzy_admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/xyzzy_admin.py", line 9, in <module>
14:31:30 web.1   |      from flask_peewee.admin import Admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:31:30 web.1   |      from flask_peewee.filters import FilterForm
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:31:30 web.1   |      from flask_peewee.forms import BaseModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:31:30 web.1   |      from wtfpeewee.orm import ModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:31:30 web.1   |      from peewee import PrimaryKeyField
14:31:30 web.1   |  ImportError: cannot import name PrimaryKeyField
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9759] [INFO] Worker exiting (pid: 9759)
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9761] [INFO] Worker exiting (pid: 9761)
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9763] [ERROR] Exception in worker process
14:31:30 web.1   |  Traceback (most recent call last):
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:31:30 web.1   |      worker.init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:31:30 web.1   |      super(GeventWorker, self).init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:31:30 web.1   |      self.load_wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:31:30 web.1   |      self.wsgi = self.app.wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:31:30 web.1   |      self.callable = self.load()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
14:31:30 web.1   |  /gunicorn/app/wsgiapp.py", line 65, in load
14:31:30 web.1   |      return self.load_wsgiapp()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:31:30 web.1   |      return util.import_app(self.app_uri)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:31:30 web.1   |      __import__(module)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/main.py", line 22, in <module>
14:31:30 web.1   |      import xyzzy_admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/xyzzy_admin.py", line 9, in <module>
14:31:30 web.1   |      from flask_peewee.admin import Admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2
14:31:30 web.1   |  .7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:31:30 web.1   |      from flask_peewee.filters import FilterForm
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:31:30 web.1   |      from flask_peewee.forms import BaseModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:31:30 web.1   |      from wtfpeewee.orm import ModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.
14:31:30 web.1   |  framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:31:30 web.1   |      from peewee import PrimaryKeyField
14:31:30 web.1   |  ImportError: cannot import name PrimaryKeyField
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9763] [INFO] Worker exiting (pid: 9763)
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9764] [ERROR] Exception in worker process
14:31:30 web.1   |  Traceback (most recent call last):
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:31:30 web.1   |      worker.init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:31:30 web.1   |      super(GeventWorker, self).init_process()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:31:30 web.1   |      self.load_wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:31:30 web.1   |      self.wsgi = self.app.wsgi()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:31:30 web.1   |      self.callable = self.load()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
14:31:30 web.1   |      return self.load_wsgiapp()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:31:30 web.1   |      return util.import_app(self.app_uri)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:31:30 web.1   |      __import__(module)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/main.py", line 22, in <module>
14:31:30 web.1   |      import xyzzy_admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Users/anon/Desktop/ra/xyzzy-master/xyzzy_admin.py", line 9, in <module>
14:31:30 web.1   |      from flask_peewee.admin import Admin
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:31:30 web.1   |      from flask_peewee.filters import FilterForm
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:31:30 web.1   |      from flask_peewee.forms import BaseModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:31:30 web.1   |      from wtfpeewee.orm import ModelConverter
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:31:30 web.1   |      result = _import(*args, **kwargs)
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:31:30 web.1   |      from peewee import PrimaryKeyField
14:31:30 web.1   |  ImportError: cannot import name PrimaryKeyField
14:31:30 web.1   |  [2017-08-14 14:31:30 -0400] [9764] [INFO] Worker exiting (pid: 9764)
14:31:30 web.1   |  Traceback (most recent call last):
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/bin/gunicorn", line 11, in <module>
14:31:30 web.1   |      sys.exit(run())
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
14:31:30 web.1   |      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
14:31:30 web.1   |      super(Application, self).run()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
14:31:30 web.1   |      Arbiter(self).run()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
14:31:30 web.1   |      self.reap_workers()
14:31:30 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
14:31:30 web.1   |      raise HaltServer(reason, self.WORKER_BOOT_ERROR)
14:31:30 web.1   |  gunicorn.errors.HaltServer
14:31:30 web.1   |  : <HaltServer 'Worker failed to boot.' 3>
14:31:30 web.1   Exited with exit code 1

**Comment by coleifer** [comment]
Ahhh yeah, the new codebase is not compatible with wtfpeewee or flask-peewee at the moment.

**Comment by ra-esmith** [comment]
Hello,

Cool.  When it is I will try an upgrade again.

Thanks!!! Super that you are doing this

Later,
Evan

Charles Leifer wrote:

**Comment by Lvl4Sword** [comment]
This appears to still be an issue. Are there any noticeable blockers to this?

**Comment by coleifer** [comment]
I don't think so, I pushed wtf-peewee 3.0.0 which should work with Peewee 3.0.0+.
