### ISSUE TITLE
Why use exec?

### ISSUE THREAD

**Issue by thomwiggers** [coleifer/peewee#1331]
On this line you're using `exec` to define `reraise`. I don't understand why you just don't use `def` directly. Would you mind clearing this up for me?

https://github.com/coleifer/peewee/blob/7beab7c60ca32477fb812eb768adc4ac458e5a57/peewee.py#L144

**Comment by mozillazg** [comment]
because on python 3 `raise tp, value, tb` will raise `SyntaxError`, use `exec` to skip syntax check.

**Comment by thomwiggers** [comment]
Ah, TIL. Thanks
