### ISSUE TITLE
Is it possible to get a count of a grouped field?

### ISSUE THREAD

**Issue by iancullinane** [coleifer/peewee#1332]
I have the following MySQL query:

`select Title, Field, count(*) as 'count' from model group by Title;`

Which returns:

`{ Title: 'Something', Field: 'Something Else', count: '5' } `

Where count is the number of occurrences of Title. I have been banging my head figuring out how to get this through peewee with no luck. Is this possible? The closest I have come sees the `Title` return overwrite the `Title` field so instead of 'Something' I get the count.

**Comment by coleifer** [comment]
Well, you need to group by both title and field if you're selecting both (unless you use mysql, which allows shenanigans like this).

If you have a lot of people, this prints out the surnames and the count associated with each, e.g.:

```python
query = Person.select(Person.last_name, fn.COUNT(Person.id).alias('ct')).group_by(Person.last_name)
for person in query:
    print person.last_name, person.ct
```
