### ISSUE TITLE
How to integrate peewee and Flask-login

### ISSUE THREAD

**Issue by yauler** [coleifer/peewee#1333]
D!
i am trying to use peewee and flask-login but wen create and user loader i have this error 
`    @login_manager.user_loader()
TypeError: user_loader() missing 1 required positional argument: 'callback'`
i knew that peewee have get_id() method but how to use it?

**Comment by candyboober** [comment]
I think you have to read that https://flask-login.readthedocs.io/en/latest/#flask_login.LoginManager.user_loader
And implement methods in your User-model that were discussed flask-login.

**Comment by coleifer** [comment]
Sorry, please direct this question to a more appropriate forum.
