### ISSUE TITLE
primary_key=False is not inheritable

### ISSUE THREAD

**Issue by maaaks** [coleifer/peewee#1335]
[This table](http://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata) says that `primary_key` is an inheritable meta field. But it doesn't seem so, at least not when I set `primary_key=False` on a parent model and expect a child class to get the same.

If it's a bug, I think it should be fixed.
If it's supposed to be this way, I think it's worth mentioning in documentation.

**Comment by coleifer** [comment]
This is working correctly in 3.0a -- I'm not inclined to change it in the 2.x branch, despite the documentation being somewhat confusing.

023037adf3d87127969c71bc95e6e6e070590873
