### ISSUE TITLE
full text postgres search crashes with more than one word

### ISSUE THREAD

**Issue by wilsonrocks** [coleifer/peewee#1339]
This seems to be a postgres thing. I wrote some code to convert "multiple search terms! with punctuation." to "multiple & search & terms & with & punctuation" which doesn't crash it. Would this be useful in peewee, perhaps in the Match function?

**Comment by coleifer** [comment]
Peewee probably won't ever handle escaping search queries -- that should probably be done by the application as the needs may vary from app to app.
