### ISSUE TITLE
Results as dict/array of dict?

### ISSUE THREAD

**Issue by rcarmo** [coleifer/peewee#134]
It would be grand if one could do something like this:

```
    >>> m = Model()
    >>> print m.select()
    [{'id':1, 'name':'foo'},{'id':2, 'name':'bar'}]
```

i.e., returning each row as a dict. This would be especially handy for returning JSON result sets, and could probably be done using **iter** to return self._data for the model.

**Comment by araaliFarooq** [comment]
@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by matthewmav** [comment]
As I do In MySQL (as I didn't check others):

1. `select().execute()` in one step
2. iterate through cursorwrapper
3. getting values by literal column names through Model attributes instead of numeric indexing, as former is more straightforward for me

```
cursorwrapper = SomeModel.select().execute()

colnames = [name[0] for name in cursorwrapper.cursor.description]
results = []

for row in cursorwrapper:
    res = {}
    for cname in colnames:
        res[cname] = getattr(row, cname)
    results.append(res)
```

**Comment by coleifer** [comment]
This is 8 years old. For quite a long time, Peewee has supported this out-of-the-box with the following query methods:

* [dicts()](http://docs.peewee-orm.com/en/latest/peewee/api.html#BaseQuery.dicts)
* [tuples()](http://docs.peewee-orm.com/en/latest/peewee/api.html#BaseQuery.tuples)
* [namedtuples()](http://docs.peewee-orm.com/en/latest/peewee/api.html#BaseQuery.namedtuples)

**Comment by matthewmav** [comment]
@coleifer Thank you for your info and your work.

**Comment by matthewmav** [comment]
Though as @coleifer pointed out  that this is a 8 years old post, but as this github issue is among the top finds of search engines regarding this topic and I didn't find a good example code for usage of the pretty useful `dicts()` method (thank to @coleifer of course), I decided to post one for future readers:

```
cursor = SomeModel.select().dicts().execute()

for row in cursor:
    print(type(row))
```
**Out:**
```
<class 'dict'>
<class 'dict'>
.
.
.
<class 'dict'>
```

**Comment by Insighttful** [comment]
More concisely retaining the query:
```python
query = SomeModel.select()
print(list(query.dicts()))
```
One liner:
```python
print(list(SomeModel.select().dicts))
```
