### ISSUE TITLE
add truncate_table to doc

### ISSUE THREAD

**Issue by toshitanian** [coleifer/peewee#1345]
truncate_table is implemented on peewee, but not in doc. i hope it is written in doc.

https://github.com/coleifer/peewee/pull/862/files

**Comment by coleifer** [comment]
That's true -- I will look at adding similar functionality to the 3.0a branch and will document it there, as Peewee will be moving to the 3.0 branch soon.

**Comment by coleifer** [comment]
Well, actually, I think I'm going to omit it from the 3.x branch for now, so will leave as-is. But thank you for letting me know.

**Comment by mildmelon** [comment]
I would love to see this functionality in v3 as it was available in v2. It doesn't make sense to omit this simple and very useful function. I would prefer to truncate over drop tables when I don't need a table structure change.
