### ISSUE TITLE
Delete() based on a dictionary instead of an Expression.

### ISSUE THREAD

**Issue by atrevino** [coleifer/peewee#1348]
I have this dictionary
`table_fields = {'entity_id': 9998777}` 

I can pass it to my own implementation of **get_or_create** by doing something like:
```    
        def get_or_create(table_fields):
        try:
            return AdNetworkModel.get(**table_fields).id
        except AdNetworkModel.DoesNotExist:
            return AdNetworkModel.create(**table_fields).id
```
My model looks like:
```
class AdNetworkModel(BaseModel):
    entity_id = peewee.CharField()

    class Meta:
        db_table = 'AD_NETWORK'
```

Until now all good, the get_or_create method works fine, but if I want to make a `delete()` it doesn't work, seems that I have to use an Expression which I wouldn't like to because I want to create my own dynamic delete based on a dictionary. Is this possible? 

```
  def delete(table_fields):
        AdNetworkModel.delete(**table_fields).execute()
```

The error that this code throws is:

```
{TypeError}delete() got an unexpected keyword argument 'entity_id'
```

**Comment by coleifer** [comment]
You can use:

```python
AdNetworkModel.delete().filter(**table_fields).execute()
```

If you're working on serving advertisements, though, I probably shouldn't help you :)

**Comment by atrevino** [comment]
Thanks sir !
