### ISSUE TITLE
Unnecessary parentheses in the produced SQL

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/peewee#1349]
```python
Foo.select().where((Foo.id == 1) | (Foo.id == 2) | (Foo.id == 3) | (Foo.id == 4))
```

Produces SQL like:

```sql
... WHERE ((((\"t1\".\"id\" = 1) OR (\"t1\".\"id\" = 2)) OR (\"t1\".\"id\" = 3)) OR (\"t1\".\"id\" = 4)) ...
```

And so on. I don't know if the extra parentheses have impact on performance, but I would think so?

Using `2.10.0` with postgres.

**Comment by coleifer** [comment]
The parentheses are semantically correct, though to a human they look extraneous. It's completely acceptable.
