### ISSUE TITLE
How to force not to get primary key on insert action

### ISSUE THREAD

**Issue by soyking** [coleifer/peewee#1350]
I use peewee as PostgreSQL orm. As I saw on [InsertQuery.execute](https://github.com/coleifer/peewee/blob/81091b87c8c4b4d3dc65fc63b985629cd70dfd3a/peewee.py#L3584), when `is_insert_returning` is set, peewee will use `RETURNING` to get primary key. Otherwise it will call `last_insert_id` which is implemented by `SELECT CURRVAL` in PostgreSQL. 

In my case, I use partition function on Postgres. So I will `RETURN NULL` when inserting a row, which means `RETURNING` won't work. And `SELECT CURRVAL` will fail as well.

So I open this issue to make sure that whether there is a way to force not to get primary key after insert action. Thanks!

**Comment by coleifer** [comment]
So...you bring up a good point. In peewee 2.x it's not really possible using the existing APIs.

In the 3.x branch, you can now write:

```python
SomeModel.insert({SomeModel.field: 'value'}).returning(None)
```

**Comment by soyking** [comment]
@coleifer 

Thanks for your response. It helps a lot.

ps. Is there any way to run raw query in 3.0 ? I didn't find the API actually.

**Comment by coleifer** [comment]
There is no more `RawQuery` in 3.0a. You can use `Database.execute_sql()` instead, which returns a cursor object.
