### ISSUE TITLE
Cannot specify schema with PostgresqlMigrator

### ISSUE THREAD

**Issue by irlabs** [coleifer/peewee#1353]
I'm trying to use `playhouse.migrate` to modify the database according to the model changes, but it seems I cannot specify the PostgreSQL schema of the table that I need to alter.

My model looks like this:

```python
db = PostgresqlDatabase(...)

class MyTable(Model):
    title = CharField()
    class Meta:
        database = db 
        db_table = 'table_name'
        schema = 'my_schema'

```

But if I run migration code like the following:

```python
migrator = PostgresqlMigrator(db)
new_field = CharField(default="")
migrate(
    migrator.add_column(MyTable._meta.db_table, 'new_field', new_field),
)
```

, I get this error:

```
peewee.ProgrammingError: relation "table_name" does not exist
```

How can I tell the migrator that it should alter the table `table_name ` in the schema `my_schema `?

**Comment by coleifer** [comment]
You're right. You may need to, in the meantime, run something like `db.execute_sql('set search_path to my_schema')` until I can get a fix.

**Comment by coleifer** [comment]
Did you try the above suggestion, by chance?

**Comment by irlabs** [comment]
> Did you try the above suggestion, by chance?
No, I used the psql command line instead.

**Comment by albireox** [comment]
Probably related, but I'm getting the same error using reflection on a Postgresql DB with a schema. `generate_models()` works fine but making a query on any of the generated models fails. If I do `db.execute_sql('set search_path to targetdb'`) the queries do work.

**Comment by coleifer** [comment]
@albireox -- check out febcb495de5f21bc19c8834af78522fbfdb6c994

**Comment by albireox** [comment]
Yep, that seems to fix the problem.

**Comment by coleifer** [comment]
Rather than modify all the APIs to support a schema parameter, I added a method which you can use to set the search path for subsequent operations. e.g.

```python

title_field = TextField(default='')
migrate(
    migrator.set_search_path('my_schema'),
    migrator.add_column('some_table', 'title', title_field),
)
```
