### ISSUE TITLE
crash on startup with port from 2 to 3a

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1364]
Thought I would try the 3.0a version

I was running peewee==2.10.1
did a pip uninstall of peewee and then installed peewee 3.0a

And then just ran my code ...

Got some errors right off ... ideas?  Is there a list of changes we should make to port up?
For example
"importError: cannot import name PrimaryKeyField"

Thanks!

Some more details

[OKAY] Loaded ENV .env File as KEY=VALUE Format
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91297] [INFO] Starting gunicorn 19.7.1
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91297] [INFO] Listening at: http://0.0.0.0:5000 (91297)
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91297] [INFO] Using worker: gevent
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91300] [INFO] Booting worker with pid: 91300
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91301] [INFO] Booting worker with pid: 91301
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91302] [INFO] Booting worker with pid: 91302
14:56:37 web.1   |  [2017-10-16 14:56:37 -0400] [91303] [INFO] Booting worker with pid: 91303
14:56:38 web.1   |  [2017-10-16 14:56:38 -0400] [91301] [ERROR] Exception in worker process
14:56:38 web.1   |  Traceback (most recent call last):
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:56:38 web.1   |      worker.init_process()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:56:38 web.1   |      super(GeventWorker, self).init_process()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:56:38 web.1   |      self.load_wsgi()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:56:38 web.1   |      self.wsgi = self.app.wsgi()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:56:38 web.1   |      self.callable = self.load()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
14:56:38 web.1   |      return self.load_wsgiapp()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:56:38 web.1   |      return util.import_app(self.app_uri)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:56:38 web.1   |      __import__(module)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/main.py", line 29, in <module>
14:56:38 web.1   |      from views.user import *
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/views/user.py", line 18, in <module>
14:56:38 web.1   |      from sample1_auth import sample1_auth
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_auth.py", line 17, in <module>
14:56:38 web.1   |      from sample1_models import User, UserAdmin
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_models.py", line 44, in <module>
14:56:38 web.1   |      from flask_peewee.admin import ModelAdmin
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:56:38 web.1   |      from flask_peewee.filters import FilterForm
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:56:38 web.1   |      from flask_peewee.forms import BaseModelConverter
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:56:38 web.1   |      from wtfpeewee.orm import ModelConverter
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:56:38 web.1   |      from peewee import PrimaryKeyField
14:56:38 web.1   |  ImportError: cannot import name PrimaryKeyField
14:56:38 web.1   |  [2017-10-16 14:56:38 -0400] [91301] [INFO] Worker exiting (pid: 91301)
14:56:38 web.1   |  [2017-10-16 14:56:38 -0400] [91300] [ERROR] Exception in worker process
14:56:38 web.1   |  Traceback (most recent call last):
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:56:38 web.1   |      worker.init_process()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:56:38 web.1   |      super(GeventWorker, self).init_process()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:56:38 web.1   |      self.load_wsgi()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:56:38 web.1   |      self.wsgi = self.app.wsgi()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:56:38 web.1   |      self.callable = self.load()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-package
14:56:38 web.1   |  s/gunicorn/app/wsgiapp.py", line 65, in load
14:56:38 web.1   |      return self.load_wsgiapp()
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:56:38 web.1   |      return util.import_app(self.app_uri)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:56:38 web.1   |      __import__(module)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/main.py", line 29, in <module>
14:56:38 web.1   |      from views.user import *
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/views/user.py", line 18, in <module>
14:56:38 web.1   |      from sample1_auth import sample1_auth
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versio
14:56:38 web.1   |  ns/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_auth.py", line 17, in <module>
14:56:38 web.1   |      from sample1_models import User, UserAdmin
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_models.py", line 44, in <module>
14:56:38 web.1   |      from flask_peewee.admin import ModelAdmin
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:56:38 web.1   |      from flask_peewee.filters import FilterForm
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import
14:56:38 web.1   |  __
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:56:38 web.1   |      from flask_peewee.forms import BaseModelConverter
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:56:38 web.1   |      from wtfpeewee.orm import ModelConverter
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:38 web.1   |      result = _import(*args, **kwargs)
14:56:38 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:56:38 web.1   |      from peewee import PrimaryKeyField
14:56:38 web.1   |  ImportError: cannot import name PrimaryKeyField
14:56:38 web.1   |  [2017-10-16 14:56:38 -0400] [91300] [INFO] Worker exiting (pid: 91300)
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91303] [ERROR] Exception in worker process
14:56:39 web.1   |  Traceback (most recent call last):
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:56:39 web.1   |      worker.init_process()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:56:39 web.1   |      super(GeventWorker, self).init_process()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:56:39 web.1   |      self.load_wsgi()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:56:39 web.1   |      self.wsgi = self.app.wsgi()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:56:39 web.1   |      self.callable = self.load()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
14:56:39 web.1   |      return self.load_wsgiapp()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:56:39 web.1   |      return util.import_app(self.app_uri)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:56:39 web.1   |      __import__(module)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/main.py", line 29, in <module>
14:56:39 web.1   |      from views.user import *
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/views/user.py", line 18, in <module>
14:56:39 web.1   |      from sample1_auth import sample1_auth
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_auth.py", line 17, in <module>
14:56:39 web.1   |      from sample1_models import User, UserAdmin
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_models.py", line 44, in <module>
14:56:39 web.1   |      from flask_peewee.admin import ModelAdmin
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:56:39 web.1   |      from flask_peewee.filters import FilterForm
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:56:39 web.1   |      from flask_peewee.forms import BaseModelConverter
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:56:39 web.1   |      from wtfpeewee.orm import ModelConverter
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:56:39 web.1   |      from peewee import PrimaryKeyField
14:56:39 web.1   |  ImportError: cannot import name PrimaryKeyField
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91303] [INFO] Worker exiting (pid: 91303)
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91302] [ERROR] Exception in worker process
14:56:39 web.1   |  Traceback (most recent call last):
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
14:56:39 web.1   |      worker.init_process()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
14:56:39 web.1   |      super(GeventWorker, self).init_process()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
14:56:39 web.1   |      self.load_wsgi()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
14:56:39 web.1   |      self.wsgi = self.app.wsgi()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
14:56:39 web.1   |      self.callable = self.load()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
14:56:39 web.1   |      return self.load_wsgiapp()
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
14:56:39 web.1   |      return util.import_app(self.app_uri)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
14:56:39 web.1   |      __import__(module)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/main.py", line 29, in <module>
14:56:39 web.1   |      from views.user import *
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/views/user.py", line 18, in <module>
14:56:39 web.1   |      from sample1_auth import sample1_auth
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_auth.py", line 17, in <module>
14:56:39 web.1   |      from sample1_models import User, UserAdmin
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Users/anon/Desktop/xxx/sample1-master/sample1_models.py", line 44, in <module>
14:56:39 web.1   |      from flask_peewee.admin import ModelAdmin
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/admin.py", line 19, in <module>
14:56:39 web.1   |      from flask_peewee.filters import FilterForm
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/filters.py", line 5, in <module>
14:56:39 web.1   |      from flask_peewee.forms import BaseModelConverter
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_peewee/forms.py", line 6, in <module>
14:56:39 web.1   |      from wtfpeewee.orm import ModelConverter
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
14:56:39 web.1   |      result = _import(*args, **kwargs)
14:56:39 web.1   |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wtfpeewee/orm.py", line 30, in <module>
14:56:39 web.1   |      from peewee import PrimaryKeyField
14:56:39 web.1   |  ImportError: cannot import name PrimaryKeyField
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91302] [INFO] Worker exiting (pid: 91302)
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91297] [INFO] Shutting down: Master
14:56:39 web.1   |  [2017-10-16 14:56:39 -0400] [91297] [INFO] Reason: Worker failed to boot.
14:56:39 web.1   Exited with exit code 3

**Comment by coleifer** [comment]
You need the 3.0a branches of wtf-peewee and flask-peewee, if your project depends on those libraries. Since I haven't merged 3.0a into master yet, you'll need to use the branches. When 3.0a is merged into peewee master, I'll merge the other libraries as well.
