### ISSUE TITLE
How to specify an icu tokenizer locale identifier for subclass of sqlite_ext.FTSModel?

### ISSUE THREAD

**Issue by galeo** [coleifer/peewee#1371]
Sqlite's built in icu tokenizer supports locale identifier, for example:
```sql
CREATE VIRTUAL TABLE thai_text USING fts3(text, tokenize=icu th_TH)
```
If tried to set `Meta.extension_options = {'tokenize': 'icu th_TH'}`, it will raise error:
```
peewee.OperationalError: unknown tokenizer: icu th_TH
```
Does it support specify this option for subclass of `playhouse.sqlite_ext.FTSModel`?

**Comment by coleifer** [comment]
It seems that Peewee is quoting the tokenizer (both 2.x and 3.0a), it looks like:

```sql
CREATE VIRTUAL TABLE "note" USING FTS3 ("content", tokenize="icu en_AU")
```

Can you do an experiment for me? Using Peewee (or just the plain old `sqlite3` module):

```python
from playhouse.sqlite_ext import *
db = SqliteExtDatabase(':memory:')
db.execute_sql('CREATE VIRTUAL TABLE thai_text USING fts3 (content, tokenize=icu th_TH);')
```

Or

```python
import sqlite3
conn = sqlite3.connect(':memory:')
conn.execute('CREATE VIRTUAL TABLE thai_text USING fts3 (content, tokenize=icu th_TH);')
```

And let me know what happens?

**Comment by galeo** [comment]
They work well, both of the methods above, by not quoting the tokenizer.

**Comment by coleifer** [comment]
Cool I didn't compile sqlite with icu so I wanted to double check that would work. I'll get a patch up today.

**Comment by galeo** [comment]
Thanks!

**Comment by coleifer** [comment]
You mind trying out c88fc2ef08c4ed5e7214b7d30f0b20707db43995 and seeing if that resolves the issue?

**Comment by galeo** [comment]
It works! Thanks so much!
