### ISSUE TITLE
BoolField for Sqlite does't get mapped to a boolean value

### ISSUE THREAD

**Issue by nad2000** [coleifer/peewee#1372]
BoolField for Sqlite does't get mapped to a boolean value. Instead its DB representation (INTEGER) value gets returned.

**Comment by coleifer** [comment]
Two reasons for that. One, sqlite has no boolean type. Two, in python true is literally the same as 1 and false is 0.

**Comment by nad2000** [comment]
Thanks for the comment. I was aware of that. That's why I thing it would be handy to have uniform type coercion. Original issue I ran into was that marshalling select query results into JSON with Sqlite3 and PG produces different output. I was expecting that mapping (isn't that what ORM is supposed to do) would shield me form limitations of the underlying DBs. Cheers!

**Comment by coleifer** [comment]
The values *are* coerced, though. It's just the storage type:

```ipython
In [1]: from peewee import *

In [2]: db = SqliteDatabase(':memory:')

In [3]: class Test(Model):
   ...:     value = BooleanField()
   ...:     class Meta:
   ...:         database = db
   ...:         

In [4]: db.create_tables([Test])

In [5]: t = Test.create(value=True)

In [6]: f = Test.create(value=False)

In [7]: print Test.get(Test.id == t.id).value
True

In [8]: print Test.get(Test.id == f.id).value
False
```
