### ISSUE TITLE
soundex postgres

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1376]
Hello,

Rather than use contains in my where clause I would like to use postgres soundex.  Does peewee support soundex?  What would be an example of the syntax.

Thanks,
Evan

**Comment by coleifer** [comment]
I'm not sure exactly what you mean, but Peewee supports arbitrary function calls:

```
SomeModel.select().where(fn.soundex(SomeModel.column) == fn.soundex(search_string))
```
