### ISSUE TITLE
Setting MySQL storage engine

### ISSUE THREAD

**Issue by tomvlk** [coleifer/peewee#1378]
I wonder if it's already possible to set the MySQL storage engine for tables in a model or anywhere so it kinda works with ``create_tables`` method.
I ask this because of the limitation when the default storage engine is set to MyISAM and when you are creating tables in a utf8mb4_unicode_ci collation, it will complain about varchar indexes over the limit. I have to advice users to change their default storage engine right now, but it would be better to just create the tables with the storage engine given as a parameter.

**Comment by coleifer** [comment]
https://github.com/coleifer/peewee/issues/178#issuecomment-232955141
