### ISSUE TITLE
Provide an enumeration for valid on_delete values.

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#1381]
Currently, the `on_delete` keyword argument of `ForeignKeyField` takes arbitrary strings.
The valid values are not documented in the [API reference](http://docs.peewee-orm.com/en/latest/peewee/api.html?highlight=cascade#ForeignKeyField) - just one example is given.
Assuming that all [options supported by MySQL](https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html) work, I request adding the following `enum.Enum` to peewee to be used alternatively to provide the field with the respective option.
```
class ForeignKeyConstraint(Enum):
    """Valid constraints for ForeignKeyFields."""

    RESTRICT = 'RESTRICT'
    CASCADE = 'CASCADE'
    SET_NULL = 'SET NULL'
    NO_ACTION = 'NO ACTION'
    SET_DEFAULT = 'SET DEFAULT'

    def __str__(self):
        return self.value

```

**Comment by coleifer** [comment]
Enum is a python 3 thing, using it in 2.x requires a separate library if I'm not mistaken. Similarly, I prefer not to hard-code the list of supported actions since there may be some variance between options between databases (?).
