### ISSUE TITLE
KeyError when fields specified in select()

### ISSUE THREAD

**Issue by jspayne** [coleifer/peewee#1385]
Test_File_Options is a many-many foreign key table with references to TestFile and TestOptions.
```
q1 = Test_File_Options.select(TestFile.file_name).join(TestFile).switch(Test_File_Options).join(TestOption).where(TestOption.option == '-G').distinct().alias('q1a')
```
I can directly run the query generated by the above, and get what I'd expect.

q1.get() results in `KeyError: <class 'compile_opts_db_mysql.Test_File_Options'>`

If I remove the `TestFile.file_name` from the select(), there is no error

[I'm trying to select the field here because later I'm trying to join q1 to a q2 with a different option based on file_name, and need to specify the join field]

**Comment by coleifer** [comment]
The issue is you're selecting a column on a joined model, but not selecting anything from Test_File_Options.

You probably want to rewrite as:

```python
(TestFile
 .select(TestFile.filename)
 .join(Test_File_Options)
 .join(TestOption)
 .where(TestOption.option == '-G')
 .get())
```
