### ISSUE TITLE
Help wanted on querying 

### ISSUE THREAD

**Issue by dashingspidy** [coleifer/peewee#1388]
I have User and Photo table and when i join them while querying, it duplicates User based on how many photo is associated with.

```
class User(BaseModel): 
      id = PrimaryKeyField()
      looking_for = CharField()
```

```
class Photo(BaseModel): 
      id = PrimaryKeyField()
      url = CharField()
      user = ForeignKeyField(User, related_name='photos')
```
Query:
`User.select(User, Photo).join(Photo).where(User.looking_for == 'params')`

**Comment by coleifer** [comment]
This kind of question is not appropriate for the issue tracker. Please post to stackoverflow.

Because I'm a nice guy :) you're getting duplicate rows because you're joining on Photo...why are you joining on photo in the above query?
