### ISSUE TITLE
Question: is there a best practice changing schema configuration depending on the model used?

### ISSUE THREAD

**Issue by atrevino** [coleifer/peewee#1391]
So I would like to know if there's a good way / approach to change schema configuration depending on the model used. I thought that `class Meta` was able to do that, but I can't find anything related to that on the docs, or probably not looking for it properly.

Any advice?
Best Regards!

**Comment by coleifer** [comment]
Could you be more specific?

**Comment by atrevino** [comment]
I just wanted to switch the schema using class Meta. I went through the docs and achieve it with this:
http://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata
