### ISSUE TITLE
ERROR:raysync:pysqlite or sqlite3 must be installed.

### ISSUE THREAD

**Issue by 0953** [coleifer/peewee#1395]
The peewee i used , running ok on windows, but linux. it print `ERROR:pysqlite or sqlite3 must be installed.`

![20171204094931](https://user-images.githubusercontent.com/4026598/33532908-93616f10-d8d8-11e7-9339-a8a781e0f004.png)

os: CentOS-x86_64-minimal
python: Python 2.7.13
pip list:
altgraph (0.14)
backports-abc (0.5)
certifi (2017.7.27.1)
configparser (3.5.0)
dis3 (0.1.1)
future (0.16.0)
hashids (1.2.0)
macholib (1.8)
peewee (2.10.2)
pefile (2017.9.3)
pip (9.0.1)
protobuf (3.2.0)
PyInstaller (3.3)
pysqlite (2.8.3)
setuptools (20.3.1)
singledispatch (3.4.0.3)
six (1.11.0)
tornado (4.5.2)

**Comment by coleifer** [comment]
Try opening up a python shell and running:

```
from peewee import sqlite3
print sqlite3
```

You can also try:

```
from pysqlite2 import dbapi2
import sqlite3
```

What happens?

**Comment by 0953** [comment]
My python is compiled by myself, I forget to add sqlite3 module.
