### ISSUE TITLE
Model.get doesn't work when I pass a foreing key field attribute

### ISSUE THREAD

**Issue by yanghg-basefx** [coleifer/peewee#1396]
Please see this code:

```python
import peewee
db = peewee.MySQLDatabase(**CONNECT_KWARGS)

class M(peewee.Model):
    parent= peewee.ForeignKeyField('self')
    class Meta:
        database= db
        db_table = 'M'

M.get(parent=None)  # It works.
M.get(parent=10000)  # It doesn't work. peewee.OperationalError: (1066, "Not unique table/alias: 't1'")
```

I've tested it both 2.10.2 and 3.0.a.

**Comment by coleifer** [comment]
Good catch...the `filter()` API is not very smart when it comes to self-referential foreign-keys. I had thought it would handle this simple case, but apparently I'm missing a unit-test (which would've revealed the issue).

For now, try:

```python
M.get(M.parent == 10000)
```

**Comment by coleifer** [comment]
I've pushed a fix for this simple case in 3.0a. Unfortunately, lookups that traverse the self-referential FK will still have the join alias issue.

**Comment by yanghg-basefx** [comment]
It works fine! When the 3.0 branch is stable, I will merge it into our company. Thanks!

But sorry, I can't really understand what does `lookups that traverse the self-referential FK will still have the join alias issue` mean. Can you give me a example? I can't reproduce it.

**Comment by yanghg-basefx** [comment]
Or do you mean this?

```python
query = M.select().join(M)

M.execute()  # peewee.OperationalError: (1066, "Not unique table/alias: 't1'")
```

In fact, I always do the alias for it

```
MA = M.alias()
query = M.select().join(MA)

query.execute()
```

I think it is good enough, because if I want to specify other conditions, I can do that:

```python
M.select().join(MA).where(M.name == 'a', MA.name == 'b')
```

**Comment by coleifer** [comment]
If you are doing a self-join you should always alias it (2nd example using `.join(MA)`).

The problem was that when using `.get()` with keyword-arguments, it is using the `.filter()` API under-the-hood, and this API does not cope well with self-referential FKs.

The standard APIs work just fine, however.

**Comment by yanghg-basefx** [comment]
I got it, thanks!
