### ISSUE TITLE
No way to create a table by string?

### ISSUE THREAD

**Issue by josephmancuso** [coleifer/peewee#1398]
why is this not possible?

```
engine = database.engines['default']
migrator = MySQLMigrator(engine)

engine.create_tables(['users'], True) <--- not possible

migrate(
    migrator.add_column('users', 'column_name', 'CharField(default=255)'),
)

engine.close()
```

is there no way to simply create a table based off of a string? I want to separate the models and the migrations from each other so that I don't need to create a model before I create a table for it. I would like to create tables without a model

or even a way to do:

`migrator.create_table('users', True),`

**Comment by coleifer** [comment]
What would it create if there were no columns defined?

**Comment by josephmancuso** [comment]
it could just create a table with an id column by default

**Comment by josephmancuso** [comment]
`migrator.create_table('users', pk = 'user_id'),`

**Comment by coleifer** [comment]
Peewee already has APIs for creating tables -- going to pass on these suggestions.
