### ISSUE TITLE
Keep getting error: OperationalError: Database has not been initialized

### ISSUE THREAD

**Issue by XuyangBai** [coleifer/peewee#1399]
Hi, I have following code using SqliteQueueDatabase. But I keep getting error `OperationalError: Database has not been initialized` I tried several methods but nothing works. So would please help me with that? Thanks you : )

dataService.py
```
from model import db
class dataService(object):
    def __init__(self, db_path):
        db.init(db_path)
        db.start()
    def some_func(self):
        pass
```
model.py
```
from playhouse.sqliteq import SqliteQueueDatabase
db = SqliteQueueDatabase(None)
class BaseModel(Model):
    class Meta(object):
        database = db

class Item(BaseModel):
    city = CharField()
    district = CharField()
```

**Comment by coleifer** [comment]
Somehow I assume your dataService() object is not getting instantiated. There is a problem in your python code, not in Peewee.

**Comment by XuyangBai** [comment]
Hello, I checked my code again and found that the error `OperationalError: Database has not been initialized` just thrown when I was trying to `from model import db`.  
So how could I import `db` without this error? ( Since my variable `db` and class `dataService` defined in two seperate files)
