### ISSUE TITLE
Support of BINARY fields

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#1401]
I was just searching the internet for possibilities to handle BINARY fields (MySQL) in peewee and came across [this](https://github.com/coleifer/peewee/issues/801).
However, though the [respective pull request](https://github.com/coleifer/peewee/pull/802) was merged in 2015, I cannot find the respective code in peewee any longer and the official documentation also does not state any support of BINARY.
What happend to its support and can it be added again?

**Comment by coleifer** [comment]
I believe you should be fine to use `BlobField` for most things, but it is also very easy to subclass `BlobField` and provide an implementation for the data-type you wish to use.

http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field
