### ISSUE TITLE
Foreign key fields without related attribute

### ISSUE THREAD

**Issue by vadimkantorov** [coleifer/peewee#1405]
I'd like to create a model that has two different foreign keys to another model. Peewee forces to use different `related_name`'s in order to make two different related Python attributes in the other model. In fact, I don't need those attributes.

Is there a way to tell Peewee to skip creating these attributes? I tried setting `related_name = None`, but it didn't help.

The usecase is modeling Audit records. I don't really care about conveniently retrieving all records by a given user using the Python code. I'll be just dumping all audit records to a spreadsheet and exploring it manually.

**Comment by coleifer** [comment]
You can, in the model `Meta`, specify `validate_backrefs = False` to disable validation in 2.x.

If you're using 3.0a, validation is not enforced at the moment.

I had not considered supporting disabling backrefs altogether, but that might be a good idea to add in 3.0a.

**Comment by coleifer** [comment]
In 3.0a, by specifying `backref='!'`, you can disable the addition of the backref accessor to the related model.
