### ISSUE TITLE
[Question] ForeignKey to self

### ISSUE THREAD

**Issue by Nixellion** [coleifer/peewee#1406]
I'm trying to create a hierarchy of objects, and for that I need to have a foreign key to self class. Not to same instance, but to same class.

So basically what I need is this:

```
class Object(Model):
    parent = ForeignKeyField(Object, related_name='children, null=False)
```

But naturally it does not work, since Object does not yet exist at that moment.

How can I approach this problem? Could not find it in documentation, not sure how to call this issue even.

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/models.html#self-referential-foreign-keys

**Comment by Nixellion** [comment]
Thanks a lot, sorry I could not find it myself.

**Comment by coleifer** [comment]
No worries it's tricky if you aren't sure what to Google for.
