### ISSUE TITLE
Document insert_many().execute() behavior

### ISSUE THREAD

**Issue by vadimkantorov** [coleifer/peewee#1407]
I'd like to bulk insert new Users in a table (peewee 2.10.2).

I'm doing `User.insert_many([dict(display = 'u1'), dict(display = 'u2')]).execute()`. However, this returned boolean. How do I get primary id's for the newly inserted objects?

I saw in the docs that `insert(...).execute()` will return an id, so I expected the bulk version does the same.

Thanks!

**Comment by vadimkantorov** [comment]
It seems it's impossible to implement cleanly. So a note in the docs about the difference in behavior of `execute()` would be awesome.

**Comment by coleifer** [comment]
What database engine are you using?

**Comment by vadimkantorov** [comment]
SQLite

**Comment by coleifer** [comment]
Yeah sqlite doesn't support the returning clause so you're out of luck.
