### ISSUE TITLE
MYSQL: TimeField returns datetime.time object instead of datetime.timedelta object

### ISSUE THREAD

**Issue by mos87** [coleifer/peewee#1414]
I have the following construction:

```
class Config(Model):
    id = IntegerField(primary_key=True) # primary key = unique id
    date = DateField()
    time = TimeField()
    class Meta:
        database = db
        db_table = 'config'

def getRepetitiveIntervall():
    return Config.get(Config.id == 2).time
```

The time object is from type datetime.time instead of timedelta as it is in MYSQL
If i set the value in the DB to 100:00:00 (4 days, 4 hours) the peewee TimeField only returns only the 4 hours as a time object instead of a timedelta object with the 4 days...

**Comment by coleifer** [comment]
Yes, this is documented. You can very easily add your own `IntervalField` implementation.

http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field
