### ISSUE TITLE
peewee .OperationalError: unknown tokenizer: icu zh_CN ( the same as #1371)

### ISSUE THREAD

**Issue by Shazoo** [coleifer/peewee#1416]
Hi , 
I installed peewee via:
```bash
git clone ....; cd peewee
python setup.py build_ext
```

but it raise peewee.OperationalError: unknown tokenizer: icu zh_CN. 

I checked the issue 1371 https://github.com/coleifer/peewee/issues/1371

Tried the code mentioned , but it failed... 
```python
>>> import sqlite3
>>> conn = sqlite3.connect(':memory:')
>>> conn.execute('CREATE VIRTUAL TABLE thai_text USING fts4 (content, tokenize=icu th_TH);')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: unknown tokenizer: icu
```

so , anything wrong ? 

Thanks

**Comment by coleifer** [comment]
You don't have the "icu" tokenizer, as the error states.

**Comment by coleifer** [comment]
http://site.icu-project.org
