### ISSUE TITLE
cast not supported

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1422]
Hello,

Peewee rocks!  Thank you for a great ORM!

I am porting unto 3.0 and ran into an error that
cast was not supported.  
How might I do the following

from playhouse.shortcuts import cast
                expr = (cast(column, 'text').contains(str((request_values[key_search]))))

Thanks,
Evan

**Comment by coleifer** [comment]
Cast is now just a method call:

```python

expression = column.cast('text').contains(...)
```
