### ISSUE TITLE
Compute COUNT of a RawQuery

### ISSUE THREAD

**Issue by vadimkantorov** [coleifer/peewee#1424]
I have a complex raw query with joins, but I'm interested only in the number of rows in the result set.

For now my workaround is: `len(list(MyModel.raw('SELECT obj.id FROM MyModel obj ...')))` but it's not very elegant and allocates objects uselessly.

Attempts like `MyModel.raw('SELECT COUNT(*) FROM MyModel obj ....').scalar()` (always returns 1) or `MyModel.raw('SELECT obj.id FROM MyModel obj ....').count()`, or `len(MyModel.raw('SELECT obj.id FROM MyModel obj ...'))` have failed.

Thanks!

**Comment by coleifer** [comment]
What about:

```python
sql = "my crazy query"
count_sql = "select count 1 from %s as _" % sql
count, = db.execute_sql(count_sql).fetchone()
```

**Comment by coleifer** [comment]
Closing due to no response.
