### ISSUE TITLE
Default index for Fields

### ISSUE THREAD

**Issue by tomako** [coleifer/peewee#1428]
Most of the Fields have `index=False` by default. But there are few exceptions in postgres_ext package like ArrayField, BinaryJSONField, HStoreField, TSVectorField where this changed and they get `index=True` silently.
I'm saying silently because I haven't seen in the doc and noticed that only later. Maybe our case is not a regular case because we don't need index for a BinaryJSONField field. But it was generated and was huge.
Though it seems logical to add index to these fields but changing the default behavior (comparing to other Fields) can be confusing. Maybe a highlighted notice in the doc could help preventing such cases.

**Comment by coleifer** [comment]
Fixed, thanks for bringing this to my attention (and sorry for the confusion it caused).
