### ISSUE TITLE
multi query slow

### ISSUE THREAD

**Issue by m358807551** [coleifer/peewee#1429]
I have thousands of ids for a table,and I want to query model one by one by use `xxx.select().filter(id==id).first()` in a for loop(not used `>>` operator because if the given id not exist in the table, I want to get None), but this way need thousands of db query and the huge total time() is unacceptable.
I need the query result is in order and be None if the given id not found in the table, of course as fast as possible, anyone has some good ideas?

**Comment by coleifer** [comment]
This is the most ludicrous and unrealistic ticket I've seen in a long time. There's no reason you should write your code in this way, in my opinion.

If you want to get `None` for the missing values, then you could do something like this:

```python
query = ModelClass.select().order_by(ModelClass.id)

last_id = current_id = 0
missing_ids = []
for obj in query:
    current_id = obj.id
    if current_id != last_id + 1:
        missing_ids.extend(range(last_id, current_id))
    last_id = current_id
```

Does that make sense?

**Comment by coleifer** [comment]
Peewee can be made to use less RAM when iterating over large result-sets by chaining a call to `.iterator()` in your query:

```python
query = ModelClass.select().order_by(ModelClass.id).iterator()

last_id = current_id = 0
missing_ids = []
for obj in query:
    current_id = obj.id
    if current_id != last_id + 1:
        missing_ids.extend(range(last_id, current_id))
    last_id = current_id
```

The solution you've commented should work fine, too, of course.

Peewee doesn't include anything like what you're asking for, no.

**Comment by m358807551** [comment]
Thanks for your explanation
