### ISSUE TITLE
Trouble compiling and running peewee with speedups

### ISSUE THREAD

**Issue by cLupus** [coleifer/peewee#1430]
Hi,
After building peewee with python and the SQLite extension speed ups, I get the following error when running the tests.

FAIL: test_regexp (playhouse.tests.test_fields.TestFieldTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snis/Projects/APS/GUI/libraries/build/peewee-2.10.2/playhouse/tests/test_fields.py", line 377, in test_regexp
    assertValues('^ab', 'abcdefg', 'abcd')
  File "/Users/snis/Projects/APS/GUI/libraries/build/peewee-2.10.2/playhouse/tests/test_fields.py", line 375, in assertValues
    self.assertEqual(values, list(expected))
AssertionError: Lists differ: [] != ['abcdefg', 'abcd']

Second list contains 2 additional elements.
First extra element 0:
'abcdefg'

- []
+ ['abcdefg', 'abcd']

----------------------------------------------------------------------
Ran 383 tests in 5.393s

FAILED (failures=1)

Any tips?

**Comment by coleifer** [comment]
Not sure... you might try Peewee 3.0a?

**Comment by coleifer** [comment]
Tests passed fine for me, for what it's worth.

**Comment by cLupus** [comment]
I've now tried the same with 3.0a (0914cee).
The test above now succeeds, however now there are two new failures:


```
Unable to import sqlite C extension tests, skipping.
Unable to import postgres extension tests, skipping.
Unable to import SQLCipher extension tests, skipping.
Unable to import sqlite extension tests, skipping.
...........................................................................................................................................................................................................................................................................FF...........................................................................................................................
======================================================================
FAIL: test_assert_query_count_ctx_mgr (tests.test_utils.TestQueryCounter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/***/build/peewee-3.0a/tests/test_utils.py", line 89, in test_assert_query_count_ctx_mgr
    self.assertRaises(AssertionError, will_fail)
AssertionError: AssertionError not raised by will_fail

======================================================================
FAIL: test_assert_query_count_decorator (tests.test_utils.TestQueryCounter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/***/build/peewee-3.0a/tests/test_utils.py", line 77, in test_assert_query_count_decorator
    self.assertRaises(AssertionError, will_fail_under)
AssertionError: AssertionError not raised by will_fail_under

----------------------------------------------------------------------
Ran 392 tests in 6.292s

FAILED (failures=2)
```

In both cases the command
```
$PYTHON setup.py build_ext \
 && $PYTHON setup.py build \
 && $PYTHON setup.py install \
 && $PYTHON runtests.py
```

was run
