### ISSUE TITLE
Feature request: Get by primary key shorthand.

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#1432]
I often want to get instances of models by the respective primary key value.  
It would be nice to have a short-hand for:

    def by_pk(pk_value):
        return Model.get(Model._meta.primary_key == pk_value)

Hence, I suggest adding `__getitem__` to `BaseModel`:

    def __getitem__(self, pk_value):
        return self.get(self._meta.primary_key == pk_value)

So we can use:

    try:
        record_with_pk_12 = Model[12]
    except DoesNotExist:
        print('No record with primary key 12.')

**Comment by coleifer** [comment]
This is already implemented in 3.0a.
