### ISSUE TITLE
Peewee 3.0.2, what happened to `Selectquery.naive`?

### ISSUE THREAD

**Issue by csytan** [coleifer/peewee#1439]
Here are the docs from 2.7.0, but I see no mention of it in the 3.0.2 change log.

http://docs.peewee-orm.com/en/2.7.0/peewee/api.html#SelectQuery.naive

Thanks!

**Comment by coleifer** [comment]
Ah, thanks! I'll correct the oversight.

In 3.x you can use `.objects()` instead.
