### ISSUE TITLE
Peewee 3.0.2, what happened to `playhouse.test_utils.test_database`?

### ISSUE THREAD

**Issue by cLupus** [coleifer/peewee#1440]
Hi,
The method `test_database` seem to have disappeared, and I can't find any references to it in the new documentation (or in the changes made).

Is there a new way of doing the same, or has the functionality ben removed for good?

**Comment by coleifer** [comment]
The functionality has been removed. You can instead use:

* http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.bind
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.bind_ctx

These methods allow you to bind a model (and optionally its relations) to a database.

The bind() method will not create the tables in the same way test_database did, as it is more generally useful for binding a graph of models to a different database, which is presumed to exist already.

**Comment by cLupus** [comment]
Thnaks 😄
