### ISSUE TITLE
3.0.2 release breaks FlaskAdmin

### ISSUE THREAD

**Issue by brunson** [coleifer/peewee#1442]
When upgrading to peewee 3.0.2 from 2.10.2 the contrib.peewee module for flask_admin fails attempting to import PrimaryKeyField from peewee.

**Comment by coleifer** [comment]
I'm not the maintainer of Flask-Admin. You can see in the [changes](http://docs.peewee-orm.com/en/latest/peewee/changes.html#fields) that PrimaryKeyField has been renamed to AutoField.

To simplify updating, I suppose I can add a shim that logs a DeprecationWarning if you try to use PrimaryKeyField, however. This will give other maintainers some warning to upgrade their code. WDYT?

**Comment by coleifer** [comment]
Pushed 3.0.4, which adds a shim for `PrimaryKeyField`, which raises a DeprecationWarning if you attempt to use it. This should give folks time to update their codes.

**Comment by brunson** [comment]
Wow, that's awesome.  I created an issue for the flask_admin maintainer:  https://github.com/mrjoes/flask-admin/issues/42

Thanks for the amazing turn around!

**Comment by coleifer** [comment]
Of course, thanks for reporting the issue. 3.0 is a major release and I want to be sure to make the transition as smooth as possible for folks upgrading. Cheers.
