### ISSUE TITLE
update with inner join

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1446]
hello,

what is the syntax for a peewee query such as the following?  Is there a good way to figure this out on my own (like an sql to query syntax generator?).
```sql
update
    customer
 set
    customer.x = customerrep.x,
    customer.y = customerrep.y
from
    customer cust
inner join
    customerrep custrep
on 
    cust.acct = custrep.acct
```

**Comment by ra-esmith** [comment]
#my thought is to try


def test():
    with my_app.db.database.atomic():
        Customer.update(x=CustomerRep.select(CustomerRep.x)
                        .where(CustomerRep.acct == Customer.acct)
                        .order_by(CustomerRep.id.desc())
                        .limit(1)).execute()
        Customer.update(y=CustomerRep.select(CustomerRep.y)
                        .where(CustomerRep.acct == Customer.acct)
                        .order_by(CustomerRep.id.desc())
                        .limit(1)).execute()

**Comment by coleifer** [comment]
Did you happen to notice, when commenting or creating your issue that your code was not formatted? Please take the extra 10 seconds to do this when submitting issues.

**Comment by coleifer** [comment]
So, unfortunately, Peewee does not really support updates with joins. In fact, I don't know if any of the RDBMS's that Peewee supports allow that syntax.

* https://www.postgresql.org/docs/current/static/sql-update.html
* https://www.sqlite.org/lang_update.html

Check out this example for some ideas: http://docs.peewee-orm.com/en/latest/peewee/query_examples.html#update-a-row-based-on-the-contents-of-another-row
