### ISSUE TITLE
cascade with drop_table

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1453]
Porting up from 2 to 3 looking for cascade option

.db.database.drop_tables(ALL_MODELS, safe=True, cascade=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2579, in drop_tables
    model.drop_table(**kwargs)
TypeError: drop_table() got an unexpected keyword argument 'cascade'

**Comment by ra-esmith** [comment]
ahh looks like you just fixed it in 3.0.9
https://github.com/coleifer/peewee/commit/d49784c2d6e525d882aab702fe0d2cf8163e4c18

will see if i can grab that

**Comment by ra-esmith** [comment]
hmm, tried 3.0.9 and even took what is in git, still get unexpected keyword.  Though looks like it should work ...

**Comment by coleifer** [comment]
Let me look into it some more.

**Comment by coleifer** [comment]
Fixed.
