### ISSUE TITLE
from playhouse.shortcuts import case

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1455]
I am porting up from peewee 2 to 3 and use the case statement. 
I get an import error now ...

What is the work around for case?

Thanks,
Evan

**Comment by ra-esmith** [comment]
Ah I see
The Case() helper has moved from the playhouse.shortcuts module into the main peewee module.

Not sure what that import is, but great I will find it

**Comment by coleifer** [comment]
If you use `from peewee import *` then the Case helper is automatically imported. `Case` is the same as `case` was in 2.x, so it should be as simple as removing the old imports and switching from "case" to "Case".

**Comment by ra-esmith** [comment]
from peewee import case
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name case

**Comment by ra-esmith** [comment]
ok 
will try import *, though I tend to avoid * when I can
thanks!!

**Comment by coleifer** [comment]
It's "Case" (upper-case "c").

**Comment by coleifer** [comment]
Re: "from peewee import *", Peewee defines `__all__` at module-scope so the things that are imported are limited to a subset of everything in the peewee module namespace. It's a matter of preference, tho, so whatever works.
