### ISSUE TITLE
Allow updating existing model via dict_to_model

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/peewee#1456]
Hosting a HTTP API, `PATCH` requests update existing data. Adding `instance` or similar to `dict_to_model` would allow to update the loaded model:

```python
def dict_to_model(model_class, data, ignore_unknown=False):
    instance = model_class()
```

As in:

```python
def dict_to_model(..., instance=None, ...):
    instance = instance if instance else model_class()
    ...

obj = Foo.get(id=...)
dict_to_model(Foo, payload, instance=obj)
```

I guess `model_class` would not be needed in case `instance` is passed in?

**Comment by conqp** [comment]
I implemented something like that some time ago:
https://github.com/HOMEINFO/peeweeplus/blob/master/peeweeplus/json.py#L177

**Comment by coleifer** [comment]
Implemented it as a separate function. `dict_to_model` works the same as it did previously and to update an existing instance, you can use:

`update_model_from_dict(instance, data[, ignore_unknown=False])`.

Documentation has been added, see: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#shortcuts
