### ISSUE TITLE
Orphaned code in peewee-3.0

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#1458]
While debugging some problems with peewee-3.0 I discovered some strange code, e.g. https://github.com/coleifer/peewee/blob/406eb5865d72f1c74f48abd67bb8f4c9ccc1391a/peewee.py#L4095 
The `_get_pk_value()` method was part of peewee < 3.0, but is no longer defined on peewee-3.0's `Model`. Heck, it isn't even defined anywhere in `peewee.py`.
Is this orphaned code or am I missing something?

**Comment by coleifer** [comment]
Yipes, I was scared for a sec that I had a glaring gap in the tests. Looking closer I think the `ForeignKeyAccessor` should handle setting the value so that this code is, indeed, dead. But for now I've simply updated the method to ".get_id()", which is the correct name.
