### ISSUE TITLE
Equality check on postgreSQL ArrayField clarification

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [coleifer/peewee#1461]
Continuation of https://github.com/coleifer/peewee/issues/1311
> When doing a SELECT, peewee doesn't know if the list you are passing should be unpacked (as it would for an IN query, for example). To work around, when passing lists in this situation you should wrap it in Param:

Isn't it possible for peewee to detect a PostgreSQL ArrayField is involved, and thus the operands should not be unpacked? This would give a more consistent user experience. Alternatively, maybe it's good to document this workaround somewhere (or include it in the unit tests, as that is a place people will look for examples)

**Comment by coleifer** [comment]
> Isn't it possible for peewee to detect a PostgreSQL ArrayField is involved, and thus the operands should not be unpacked?

What behavior are you seeing in relation to ArrayField?

**Comment by Karel-van-de-Plassche** [comment]
I get:
``` python
In [2]: Network.select().where(Network.target_names == ['efeITG_GB']).sql()
Out[2]:
('SELECT "t1"."id", "t1"."filter_id", "t1"."train_script_id", "t1"."feature_prescale_bias", "t1"."feature_prescale_factor", "t1"."target_prescale_bias", "t1"."target_prescale_factor", "t1"."feature_names", "t1"."feature_min", "t1"."feature_max", "t1"."target_names", "t1"."target_min", "t1"."target_max", "t1"."timestamp" FROM "develop"."network" AS "t1" WHERE ("t1"."target_names" = (%s))',
 [['e', 'f', 'e', 'I', 'T', 'G', '_', 'G', 'B']])
```
Where I would expect the SQL as generated by the mentioned workaround:
``` python
In [4]: Network.select().where(Network.target_names == AsIs(['efeITG_GB'])).sql()
Out[4]:
('SELECT "t1"."id", "t1"."filter_id", "t1"."train_script_id", "t1"."feature_prescale_bias", "t1"."feature_prescale_factor", "t1"."target_prescale_bias", "t1"."target_prescale_factor", "t1"."feature_names", "t1"."feature_min", "t1"."feature_max", "t1"."target_names", "t1"."target_min", "t1"."target_max", "t1"."timestamp" FROM "develop"."network" AS "t1" WHERE ("t1"."target_names" = %s)',
 [['efeITG_GB']])
```
I'm not sure if this should be natively handled by peewee, but I think equality check with an ArrayField is a common thing to do.

**Comment by coleifer** [comment]
Postgresql array equality is fixed in 4a14174 (and inequality/gt/lt/ge/le).

**Comment by coleifer** [comment]
More commonly, though, folks use the containment operators when working with arrays. So this hasn't really come up before.

**Comment by Karel-van-de-Plassche** [comment]
Thanks! I did not notice this in the howto's/guides, but to be honest it has been a while since I read them thoroughly.
