### ISSUE TITLE
Database.get_cursor missed in 3.X version

### ISSUE THREAD

**Issue by vikt0rs** [coleifer/peewee#1464]
Class Database has a "get_cursor" method in peewee 2.X versions, see [0] for example. But for some reason, it missed in 3.X versions. Documentation and changelog say nothing about this change.

Please, suggest. Thanks!

[0] - https://github.com/coleifer/peewee/blob/2.10.2/peewee.py#L3773

**Comment by coleifer** [comment]
It's `Database.cursor()` now. Updated docs to reflect this.
