### ISSUE TITLE
Pylint: "No value for argument 'database' in method call" on count() call

### ISSUE THREAD

**Issue by mikekeda** [coleifer/peewee#1466]
In my code I have `User.select().count()`, after upgrading Peewee from 2.10.2 to 3.0.10 I'm getting pylint error:

> [E1120(no-value-for-parameter), users_page] No value for argument 'database' in method call

Can we add default value None for database in count method?
```
    @database_required
    def count(self, database=None, clear_limit=False):
```
https://github.com/coleifer/peewee/blob/master/peewee.py#L1695

P.S. As I see a lot of methods now have `database` argument with `@database_required` decorator, so there will be pylint errors too.

P.P.S `count()` can be called as `User.select().count(None)` without Pylint error, this issue can be closed.

**Comment by coleifer** [comment]
This is python, a dynamic language. The linter is, quite simply, wrong. Not fixing because there's no bug here. Just silly tools.
