### ISSUE TITLE
auto-incrementing primary keys in Sqlite

### ISSUE THREAD

**Issue by markschl** [coleifer/peewee#147]
I have a question regarding auto-incrementing primary keys. As far as I can see from tests, in MySQL, primary key columns are created with AUTO_INCREMENT by default, whereas in Sqlite databases the primary key of an insert may not be unique forever if some rows are deleted. As far as I understand, the equivalent of AUTO_INCREMENT (MySQL) is AUTOINCREMENT in Sqlite.
I haven't yet been able to figure out how to use this feature with Sqlite without modifying peewee itself (model._meta.auto_increment doesn't seem to have an effect).

Thank you

**Comment by lixxu** [comment]
Still not work.

1 `db = SqliteDatabase('mydb.db', fields={'primary_key': 'INTEGER AUTOINCREMENT'})` got below error:

`peewee.OperationalError: near "AUTOINCREMENT": syntax error`

SQL is:
`u'CREATE TABLE "customer" ("id" INTEGER AUTOINCREMENT NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "upper_name" VARCHAR(255) NOT NULL, "remark" VARCHAR(255) NOT NULL)'`

2 `db.register_fields({'primary_key': 'INTEGER AUTOINCREMENT'})` has no effect at all

**Comment by coleifer** [comment]
This is for a much older version of Peewee. Check out http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#PrimaryKeyAutoIncrementField

**Comment by lixxu** [comment]
So, I have to define id manually? And, `PrimaryKeyAutoIncrementField` is only for Sqlite, right?
```
Class User(Model):
    id = PrimaryKeyAutoIncrementField()
    name = CharField()
```

**Comment by coleifer** [comment]
Peewee includes an autoincrement pk by default for all databases. For sqlite, there are different types, rowid and a special autoincrement type. See:

http://www.sqlite.org/autoinc.html
