### ISSUE TITLE
pwiz doesn't properly generate models for postgresql array columns

### ISSUE THREAD

**Issue by james-lawrence** [coleifer/peewee#1470]
given a table with an text array column pwiz generates `UnknownField #ARRAY` instead of `ArrayField(TextField)`.

**Comment by coleifer** [comment]
This is a known limitation of the introspection tools. I'm not sure how to go from the OID returned by the cursor description to a suitable definition of an ArrayField object.

**Comment by james-lawrence** [comment]
then leave this issue open. =)

side note: each array type has its own OID, you just need to map them:
here is an example list of OIDs pulled from https://github.com/jackc/pgx/blob/master/pgtype/pgtype.go,
there is a query you can run to pull the list from the DB as well.
```
	BoolOID             = 16
	ByteaOID            = 17
	CharOID             = 18
	NameOID             = 19
	Int8OID             = 20
	Int2OID             = 21
	Int4OID             = 23
	TextOID             = 25
	OIDOID              = 26
	TIDOID              = 27
	XIDOID              = 28
	CIDOID              = 29
	JSONOID             = 114
	CIDROID             = 650
	CIDRArrayOID        = 651
	Float4OID           = 700
	Float8OID           = 701
	UnknownOID          = 705
	InetOID             = 869
	BoolArrayOID        = 1000
	Int2ArrayOID        = 1005
	Int4ArrayOID        = 1007
	TextArrayOID        = 1009
	ByteaArrayOID       = 1001
	BPCharArrayOID      = 1014
        VarcharArrayOID = 1015
```

**Comment by james-lawrence** [comment]
also if the problem is figuring out the OID of the table columns there is a query for that as well.

**Comment by coleifer** [comment]
:+1:

**Comment by coleifer** [comment]
Support for arrayfield added in: c6b17b59cb491470b975c83ab23fd6e28311a4d2
