### ISSUE TITLE
alias() not reflected in get()

### ISSUE THREAD

**Issue by rw102** [coleifer/peewee#1473]
`Table.select(Table.column.alias('alias')).where(Table.id == 1).dicts().get()`
Until 3.0.2 this correctly returns :
`{'alias' : value}`
From 3.0.3 onwards, it returns :
`{'column': value}`

The same also happens when returning objects.

**Comment by coleifer** [comment]
Wrote a failing test, will work up a fix.

**Comment by coleifer** [comment]
Pushed a new release 3.0.13.
