### ISSUE TITLE
[Feature Request] Support Signals in `insert`/`update`/`delete` in Postgres using `returning`

### ISSUE THREAD

**Issue by logannc** [coleifer/peewee#1484]
It would appear that Postgres can support signals using `returning`.

It should be able to easily support `post_*` signals using returning. The performance penalty should be worth the consistency in `update` vs. `save`.

Supporting `pre_*` signals would be a bit painful as you'd need to execute the save/insert using returning in an atomic block, reverting it before the block ends, fire the `pre_*` signal, replay the query, and then finally fire the `post_*` signal. The performance penalty here has the potential to be severe.

Thoughts? Would a PR be welcomed?

**Comment by coleifer** [comment]
I'm unsure that this can be done cleanly and correctly, so I'm not inclined to implement or merge an implementation.

**Comment by logannc** [comment]
Briefly, what are your concerns?

**Comment by coleifer** [comment]
Where would you install the signal hooks? What would they do? How would you make them work on SQLite and MySQL, which do not have `returning` clause support?

**Comment by logannc** [comment]
They can be installed the same way they are now. They could function the same way, by mapping the signal handler over the iterable or providing a hook for passing the collection. 

They wouldn't work on SQLite or MySQL, just like `returning` doesn't work on them.

**Comment by coleifer** [comment]
Going to close this as I'm not interested in the feature, but feel free to implement it in a third-party module.
