### ISSUE TITLE
DateTimeTZField returns datetimes in other timezone

### ISSUE THREAD

**Issue by dswah** [coleifer/peewee#1489]
Hi there.
Thank you for the very useful library. I've used it a ton. However, ive recently run into something annoying with DateTimeTZField.

when i select records with a DateTimeTZField, i always see this field in timezone A (local tz of db), even though the datetimes were originally in timezone B.

why is this? how can i avoid this?

**Comment by coleifer** [comment]
From: https://www.postgresql.org/docs/current/static/datatype-datetime.html

> For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as Greenwich Mean Time, GMT). An input value that has an explicit time zone specified is converted to UTC using the appropriate offset for that time zone. If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's TimeZone parameter, and is converted to UTC using the offset for the timezone zone.
>
> When a timestamp with time zone value is output, it is always converted from UTC to the current timezone zone, and displayed as local time in that zone. To see the time in another time zone, either change timezone or use the AT TIME ZONE construct (see Section 9.9.3).

**Comment by dswah** [comment]
Thank you for the link to the documentation.
Is there a way to tell peewee to output a DateTimeTZField in a desired tz, as suggested in [1]?
This would be very useful.

Dani

[1](https://www.postgresql.org/docs/current/static/runtime-config-client.html#GUC-TIMEZONE)

**Comment by coleifer** [comment]
If you bothered to read the linked documentation, you would have found:

> The TimeZone configuration parameter can be set in the file postgresql.conf, or in any of the other standard ways described in Chapter 19. There are also some special ways to set it:
>
> The SQL command `SET TIME ZONE` sets the time zone for the session. This is an alternative spelling of `SET TIMEZONE TO` with a more SQL-spec-compatible syntax.
>
> The `PGTZ` environment variable is used by libpq clients to send a `SET TIME ZONE` command to the server upon connection.

So, you can run: `db.execute_sql('SET TIME ZONE ...')`.
