### ISSUE TITLE
insert_many throws ValueError with list of collections.Mapping instances

### ISSUE THREAD

**Issue by Jovito** [coleifer/peewee#1495]
Hello. I've been using peewee in my latest project and I'm enjoying it quite a bit. Recently, I came across a problem when trying to pass instances of collections.Mapping to `insert_many()`, namely, it throws an ValueError exception. Here's an [example](https://gist.github.com/Jovito/2adbc33d7d60ddc6b6ebadccb750e8d6). From what I gathered, it seems that the offending line is: `is_dict = isinstance(row, dict)` in `insert_many()`. Changing it to `is_mapping = isinstance(row, (Mapping, MutableMapping))` solves the problem and still works if `row` is a regular dictionary.

**Comment by coleifer** [comment]
Fix pushed. It's not necessary to check both Mapping and MutableMapping, since MutableMappings are Mappings.
