### ISSUE TITLE
Generalize Autofield test between sqlite and postgresql

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [coleifer/peewee#1499]
In sqlite the `AutoField` used for `PrimaryKeys` is 'INTEGER', while in postgresql its 'SERIAL'. This breaks test `test_db_table` of `TestModelDDL` in `tests/schema.py`. Either this test, or the underlying AutoField has to be generalized.

**Comment by coleifer** [comment]
Yes, it was a bad commit, the test is fixed in master now.
