### ISSUE TITLE
Why does not peewee support mysql-connector-python?

### ISSUE THREAD

**Issue by polikeiji** [coleifer/peewee#1501]
I think peewee support currently only MySQLdb and pymsql as drivers for MySQL. I have not compared   MySQL drivers in details, but I want to use the mysql-connector-python because I think it is the driver Oracle is maintaining officially.

**Comment by coleifer** [comment]
I'm not familiar with mysql-connector-python, but Peewee should work with any DB-API 2.0-compatible driver. If the mysql-connector-python library is fully DB-API 2.0 compatible, you should be able to simply subclass `MySQLDatabase` and override the `_connect()` method so it uses the mysql connector.

You can refer to this document for more information: http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver

**Comment by alecvinent** [comment]
You can always use PyMySQL

**Comment by coleifer** [comment]
Peewee supports mysql-connector via `playhouse.mysql_ext.MySQLConnectorDatabase`.
