### ISSUE TITLE
Undefined symbol ReverseRelationDescriptor in peewee.py

### ISSUE THREAD

**Issue by rammie** [coleifer/peewee#1511]
The symbol `ReverseRelationDescriptor` does not seem to appear anywhere in peewee.py except here:

https://github.com/coleifer/peewee/blob/94aee08a1fee79622148cb1fcd3d2af81a834e04/peewee.py#L5724

Just thought I'd point it out as it seems to have been left behind in error (or I'm missing something).

**Comment by coleifer** [comment]
Thanks for reporting, I must've missed this during the rewrite. Fixed in master now.

**Comment by coleifer** [comment]
Looks like there are still issues with the `filter()` API...looking into it.
