### ISSUE TITLE
Default order in 3.x

### ISSUE THREAD

**Issue by phryk** [coleifer/peewee#1514]
The "Changes in 3.0" documentation page states that `_meta.order_by` has been removed,
but it doesn't state anything on how to set a default ordering in 3.x and I haven't found anything on this in the code either.

Is there now a better way of doing this or was this feature just dropped without a substitute?

If the latter is true, would you consider bringing it back? I always considered `_meta.order_by` to be a good DX boon. :<

**Comment by coleifer** [comment]
The feature was dropped due to it's perceived smelliness... If you want to achieve something similar in 3.x, you can always:

```python
class User(Model):
    username = TextField()

    @classmethod
    def ordered(cls, *args):
        return cls.select(*args).order_by(cls.username)

unordered = User.select().where(...)
ordered = User.ordered().where(...)
```

**Comment by ibushong** [comment]
I miss this feature too, though I do agree that it's a bit smelly. Nevertheless, it can be very handy, especially when you're trying to get a quick and dirty web app put together. One notable example is in flask-admin, where you want the dropdown menus for automatically scaffolded foreign key fields to be in a sane order.

Just wanted to share my quick re-implementation of this feature for anyone else that might be looking for it:

```python
class BaseModel(ModelBase):

    class Meta:
        order_by = []  # override this value in subclasses, e.g. `order_by = ['name']`

    # Simple re-implementation of default ordering that was removed in peewee 3.x
    # Ideally, ordering should always be explicitly set in query, but this can be
    # very handy, esp. for auto-scaffolding frameworks like flask-admin
    @classmethod
    def select(cls, *fields):
        order_by = []

        for field_name in cls._meta.order_by:
            if field_name.startswith('-'):
                order_by.append(getattr(cls, field_name[1:]).desc())
            else:
                order_by.append(getattr(cls, field_name))

        return super(BaseModel, cls).select(*fields).order_by(*order_by)
```

**Comment by coleifer** [comment]
I would think `flask-admin` doesn't provide a way to define or override the query of related objects, but *shrug*?
