### ISSUE TITLE
Add `column_exists` method to `Database` class

### ISSUE THREAD

**Issue by Enether** [coleifer/peewee#1515]
Currently, when running migrations, I'd like to check if a column exists. My current solution is the following:
```python3
column_name = 'name'
table_name = 'users'
if any(column_data.name == column_name for column_data in db.get_columns(table_name)):
  pass
```
This also produces the following query (PostgreSQL) which is overkill:
```sql
SELECT column_name, is_nullable, data_type
            FROM information_schema.columns
            WHERE table_name = 'users' AND table_schema = 'public'
            ORDER BY ordinal_position
```

What I'd like to have is:
```python3
column_name = 'name'
table_name = 'users'
if db.column_exists(table_name, column_name):
  pass
```

And it could produce something like the following query:
```sql
EXISTS (SELECT 1
             FROM information_schema.columns
             WHERE table_name = 'users' AND table_schema = 'public' AND column_name='name')
```

I could implement this myself, I'd just like somebody to approve it.

**Comment by coleifer** [comment]
I don't plan on adding that API, you can very easily use the `get_columns()`, as you've indicated, to achieve  equivalent results.
