### ISSUE TITLE
why does rawquery not support iterator

### ISSUE THREAD

**Issue by m358807551** [coleifer/peewee#1517]
I want to execute some codes like:
`Article.raw("select * from article").iterator()`.
However, I got:
`{AttributeError}'RawQuery' object has no attribute 'iterator'`

**Comment by coleifer** [comment]
Is there a very compelling reason for using `raw()` in your case? The above could simply be written as `Article.select()`.

Raw queries *do* support iterator, but you need to preface it by calling `execute()` first:

```python

query = Article.raw('select * from article')
for article in query.execute().iterator():
    # do something with article.
```

**Comment by coleifer** [comment]
In 3.x raw queries support `iterator()`.

**Comment by m358807551** [comment]
Thank you.
