### ISSUE TITLE
Cursor count attribute returns 0, when shouldn't

### ISSUE THREAD

**Issue by vikt0rs** [coleifer/peewee#1519]
For some reasons, when I try to check if request returns some data with the "count" attribute, the check fails because it always returns 0. Please, suggest.
PS - this also worked in 2.X

```
>>> docs.select().execute()
<peewee.ModelObjectCursorWrapper object at 0x1089b80f0>
>>> docs.select().execute().count
0
>>> len(docs.select().execute())
308
```

**Comment by coleifer** [comment]
The `count` attribute of the cursor wrapper is something different than the `count()` method of a `Select` query:

```python

create_3_users()
User.select().count() == 3  # True

qr = User.select().execute()
qr.count == 0  # True

[x for x in qr]
qr.count == 3  # True
```

The `CursorWrapper.count` attribute tracks how many rows have been read from the cursor. It's a private API and has a different meaning than `Select.count()`.

Make sense?

**Comment by Karel-van-de-Plassche** [comment]
Suggestion: Maybe it can be renamed to _count to signify the private status?

**Comment by coleifer** [comment]
It's not documented, so I'm not even sure what would lead someone to using it?

**Comment by vikt0rs** [comment]
it is the part of public API, so I was pretty sure, that I can use it. Please, inform what's wrong in this idea? :)

**Comment by coleifer** [comment]
> it is the part of public API

Can you please share where this is documented?

**Comment by Karel-van-de-Plassche** [comment]
@coleifer You are right, I was misinterpreting PEP8
@vikt0rs As per PEP8 https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces:
> All undocumented interfaces should be assumed to be internal.

**Comment by vikt0rs** [comment]
Agreed, this wasn't documented, sorry for my note
