### ISSUE TITLE
Aggregation result as list

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#1523]
Hi!
First of all my congratulations with new major release! I've been using peewee several years and I love it!

This code below returns aggregated field as string. Is there another way to get result as list?
```python
    qs = (Model
          .select(Model.group, fn.array_agg(Model.name).alias('name'))
          .group_by(Model.group)
          .order_by(Model.group))
```
Thanks a lot!

**Comment by Karel-van-de-Plassche** [comment]
I'm going to assume the `name` field has a string as Python equivalent. By default, the result of the query is coerced to the same type of the original field, a string in this case. You can prevent this by doing:

``` python
    qs = (Model
          .select(Model.group, fn.array_agg(Model.name, coerce=False).alias('name'))
          .group_by(Model.group)
          .order_by(Model.group))
```
This should return a list!

**Comment by ak04nv** [comment]
@Karel-van-de-Plassche Thanks a lot!
I've found solution for 2 version of peewee:
```python
f = fn.array_agg(Model.name)
f._coerce = False
qs = (Model
        .select(Model.group, f)
        .group_by(Model.group)
        .order_by(Model.group))
```

**Comment by Karel-van-de-Plassche** [comment]
@ak04nv Great! Be aware that `_coerce` is part of the private API, and might change without notice. If this solution works for you, feel free to close the issue.

**Comment by coleifer** [comment]
Did @Karel-van-de-Plassche's suggestion of passing `coerce=False` into the function work for you @ak04nv ?

**Comment by ak04nv** [comment]
@coleifer yes and thank you guys again!
