### ISSUE TITLE
Documentation for `Case` Shortcut

### ISSUE THREAD

**Issue by r0mille** [coleifer/peewee#1524]
https://github.com/coleifer/peewee/blob/master/playhouse/README.md
mentions a section for `Shortcuts/helpers` where CASE statements can be constructed. 

However there is nothing in Peewee docs that would help a user figure out how to construct `CASE` statements.
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#shortcuts

Anything would be appreciated! Thanks in advance!

**Comment by coleifer** [comment]
I forgot that file existed, and so it hasn't been updated yet for 3.x.

You can find the `Case` helper here, as it's now part of "peewee.py": http://docs.peewee-orm.com/en/latest/peewee/api.html#Case
