### ISSUE TITLE
Postgres Match returns only one result

### ISSUE THREAD

**Issue by metakermit** [coleifer/peewee#1527]
Hi, I'm using the `Match` functionality to access Postgres' [full-text search](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#pg-fts) (`from playhouse.postgres_ext import Match`), but I only get 1 result.

For comparison, using the same search query (just a single word) the `contains` query returns more results. How can I access all the results from a `Match`?

```
ipdb> len([m for m in Act.select().where(Act.content.contains(query))])
66
ipdb> len([m for m in Act.select().where(Match(Act.content, query))])
1
```

**Comment by coleifer** [comment]
Example ipython notebook showing it working:

https://gist.github.com/coleifer/cee34b9db777c76de95a0c717aadd030
