### ISSUE TITLE
Why ForeignKeyAccessor.__set__() doesn't update instance._dirty?

### ISSUE THREAD

**Issue by TwoAnts** [coleifer/peewee#1530]
I use `=` to set a `ForeignKeyField` and call `save()` method, but it doesn't take effect.

When I read the source code in peewee.py, I found that `ForeignKeyAccessor.__set__()` seems not to update the `instance._dirty` . This leads to a failure to update `ForeignKeyField` by calling `save()` method.

Please fix it, if it is a bug.

**Comment by coleifer** [comment]
Fixed, thanks for reporting.
