### ISSUE TITLE
Flat tuples

### ISSUE THREAD

**Issue by jonathan-s** [coleifer/peewee#1532]
It would be nice if there was an option to return tuples that were flat. Much like the django queryset `values_list(flat=True)`.

**Comment by coleifer** [comment]
You can easily write a little transform:

```python

import operator
flat_transform = lambda query: map(operator.itemgetter(0), query)

x = [(1,), (2,), (3,), (4,)]
list(flat_transform(x))  # [1, 2, 3, 4]
```
