### ISSUE TITLE
how to get sql when save

### ISSUE THREAD

**Issue by visonforcoding** [coleifer/peewee#1537]
can i get the sql when i use save function .  i don`t know why i can`t save.

**Comment by coleifer** [comment]
You can turn on query logging: http://docs.peewee-orm.com/en/latest/peewee/database.html#logging-queries

```python
# Print all queries to stderr.
import logging
logger = logging.getLogger('peewee')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
```

Just a guess, but if you're not able to save...are you explicitly specifying the primary key? In other words, is your primary key something other than an auto-incrementing integer? If so, check out:

http://docs.peewee-orm.com/en/latest/peewee/models.html#id3
