### ISSUE TITLE
update_or_create is missing ?

### ISSUE THREAD

**Issue by earlzo** [coleifer/peewee#1540]
I'm curious that why the model method `update_or_create` is not provided.
https://github.com/coleifer/peewee/commit/073364ad89a8de48f4a25bbf6106bf42050d34fa

**Comment by coleifer** [comment]
Because it's hard to correctly write a generic version of these methods that isn't vulnerable to race conditions. The proper way to implement this is very short, and as a result, I leave it up to users to implement their own method for create-or-get (similar workflow for insert-or-update):

```python
# create-or-get
try:
    with db.atomic():
        return SomeObj.create(...)
except IntegrityError:
    return SomeObj.get(...)
```
