### ISSUE TITLE
drop_table does not pass **options properly

### ISSUE THREAD

**Issue by ccosby** [coleifer/peewee#1544]
https://github.com/coleifer/peewee/blob/74f3b30e6c0a6f8461b8bd33a21fd5fe9ad5c8c3/peewee.py#L4542

It appears as if **options should be passed to _drop_table() instead of execute() here.

unittest doesn't catch this one because it tests the private method instead of the public one.

**Comment by coleifer** [comment]
Thanks, fixed.
