### ISSUE TITLE
Add documentation for ~ opertor

### ISSUE THREAD

**Issue by dyadav7** [coleifer/peewee#1547]
Documentation has example for contains - e.g. Facility.name.contains('tennis').
There should be example for reverse of this contain API / reverse of any than queries.
e.g. I want to search for a Facility for which the Facility.name does not contain "tennis".

See: https://stackoverflow.com/questions/25734566/operator-not-in-with-peewee 

Thanks
Deepak

**Comment by coleifer** [comment]
There is an example.

![s1521726276 43](https://user-images.githubusercontent.com/119974/37774099-4aba906e-2dad-11e8-9683-3e9c572bbe14.png)

**Comment by dyadav7** [comment]
Thanks
