### ISSUE TITLE
Why don't you support oracle database?

### ISSUE THREAD

**Issue by inpool** [coleifer/peewee#1551]
I often need to write tools about existing apps, which are based on Oracle, and I love peewee, and when I'm ready to use her, I find that she doesn't support Oracle. Why does peewee not support Oracle?

**Comment by oz123** [comment]
It's pretty obvious that open source developers won't bother with Oracle and it's licences. 
What's the justification for writing and orm in your free time for a database you don't use?

If you are interested, it's easy to add a backed for Oracle, and if you have a license you can actually even test the code.

Maybe you can convince your employer to pay for the effort as a path to migrate from Oracle to PostgreSQL.

**Comment by coleifer** [comment]
Oracle has a DB-API 2.0-compatible Python driver, I believe it's called `cx_Oracle`? If you want to add support for Oracle you should be able to subclass `Database` and implement the appropriate methods to get it working with Oracle.

As @oz123 alluded to, Oracle is a proprietary database. I have no interest in supporting or maintaining support for it.

**Comment by inpool** [comment]
Thank you! I'll try it.
