### ISSUE TITLE
playhouse.postgres_ext.BinaryJSONField returns string

### ISSUE THREAD

**Issue by edricgarran** [coleifer/peewee#1554]
When I store data in a postgres JSONB field using the provided field type, it should be accessed as a dict/list object when I retrieve it. Instead it's being returned as a string.

**Comment by coleifer** [comment]
The JSONB code is tested, so if something were that badly broken it would certainly show up as a lot of test failures.

Are you using `playhouse.postgres_ext.PostgresqlExtDatabase` instead of the generic `peewee.PostgresqlDatabase`?
