### ISSUE TITLE
insert_many fails on sqlite 3.6.20

### ISSUE THREAD

**Issue by binrush** [coleifer/peewee#1558]
Hi! Thank you for your great project.

On peewee version 3.2.2, I'm trying to use insert_many with sqite 3.6.20:

```python
import peewee as pw
import logging

logging.basicConfig(level=logging.DEBUG)

db = pw.SqliteDatabase(':memory:')

class TestTable(pw.Model):
    id = pw.PrimaryKeyField()
    data = pw.TextField()

    class Meta:
        database = db

db.create_tables([TestTable])

TestTable.insert_many([{'id': 1, 'data': 'one'}, {'id': 2, 'data': 'two'}]).execute()
```

But I get error, because sqlite 3.6.20 does not support multiple inserts syntax:

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
~/pe-ve/lib/python3.5/site-packages/peewee.py in execute_sql(self, sql, params, commit)
   2519             try:
-> 2520                 cursor.execute(sql, params or ())
   2521             except Exception:

OperationalError: near ",": syntax error
```

Dump of queries peewee executes:
```
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "testtable" ("id" INTEGER NOT NULL PRIMARY KEY, "data" TEXT NOT NULL)', [])
DEBUG:peewee:('INSERT INTO "testtable" ("id", "data") VALUES (?, ?), (?, ?)', [1, 'one', 2, 'two'])
```

In older peewee version (2.8.3), in such cases peewee dropped to multiple inserts instead (it had bug with on_conflict clause though). Was this compatibility dropped by some reason?

**Comment by coleifer** [comment]
Correct, SQLite began supporting multi-value INSERT statements in 3.7.11, which was released over 6 years ago: http://sqlite.org/releaselog/3_7_11.html

For simplicity, Peewee 3.0 no longer includes this workaround. You can, of course, write your code to process the INSERTs in a loop (which is all 2.x did).
