### ISSUE TITLE
"return_id_list"  should be mentioned in 3.0 backwards-incompatible changes.

### ISSUE THREAD

**Issue by aniketpanjwani** [coleifer/peewee#1570]
In 2.x, there was a "return_id_list" method for Postgresql by which you could get back the new ids created through "insert_many". It appears that this has been replaced with a more general "returning" method.

However, neither change is documented in the "Changes in 3.0" page. Happy to make a PR myself, but I just wanted to confirm first that you agreed with my assessment.

Cheers!

**Comment by coleifer** [comment]
Ahh, you're right, sorry I missed that. I can add it.
