### ISSUE TITLE
ArrayField equals queries

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/peewee#1574]
How do you query [ArrayField](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#ArrayField) for equal list comparison like:

```sql
... WHERE field = ARRAY['element', 'another'];
```

`.where(MyModel.field == ['element', 'another'])` produces:

```sql
WHERE (\"field\" = (ARRAY['e', 'l', 'e', 'm', 'e', 'n', 't']::TEXT[], ARRAY['a', 'n', 'o', 't', 'h', 'e', 'r']::TEXT[]))
```

(Still using the oldish peewee `2.10.2`, sorry!)

**Comment by coleifer** [comment]
You might try using `Param` or `Passthrough` around your list, e.g.

```python
.where(MyModel.field == Passthrough(['element', 'another']))
```

**Comment by coleifer** [comment]
In peewee 3.x, for what it's worth, it's not necessary to use a wrapper around the value, you can express the equality as you'd expect:

```python
query = SomeModel.get(SomeModel.array_field == ['foo', 'bar', 'baz'])
```

**Comment by tuukkamustonen** [comment]
> ```python
> .where(MyModel.field == Passthrough(['element', 'another']))
> ```

This indeed does the trick, interesting. I was using `Clause` as a workaround, but `Passthrough`/`Param` (both work) makes it a bit cleaner and safer.

Will definitively upgrade to 3 soon. Thanks.

**Comment by tuukkamustonen** [comment]
Actually, maybe I could ask in which (other) cases do we need `Param`/`Passthrough`? Docs don't mention them.

Or are these completely removed in 3.x?

**Comment by coleifer** [comment]
Removed in 3.x. For 2.x you'll want to use it in places where you're passing a non-scalar type (like a list or something) to a database driver that understands those types...i.e., psycopg2 understands lists and dicts.
