### ISSUE TITLE
Column name conflict

### ISSUE THREAD

**Issue by biskit** [coleifer/peewee#1577]
This one left me scratching my head till trial and error found it.

1. Create a table with a column name 'update' - OK
2. Create a record - OK
2. Query a record - OK
3. Update a record - Not OK. Messages are extremely confusing from 'TypeError: 'str' object is not callable' to 'TypeError: 'unicode' object is not callable' to what not.

If this is documented somewhere, please disregard this.

**Comment by coleifer** [comment]
Right, so you named a column the same as a classmethod.

The workaround here is to:

```python
class Foo(Model):
    update = TimestampField()  # uh-oh.

# do this instead:
class Foo(Model):
    update_ = TimestampField(column_name='update')  # added "_" to avoid name conflict.
```

I suppose I can add this to the docs as well.

**Comment by biskit** [comment]
A document update would be extremely helpful. Not sure how one can find it there, but atleast one may get lucky.

**Comment by coleifer** [comment]
For sure, there's starting to be a bit of sprawl in the docs. If you had suggestions for re-organizing I'd be open to any ideas.

Added a note in the bottom of the "Fields" sub-section (after creating custom field).
