### ISSUE TITLE
Move playhouse module as a submodule on peewee?

### ISSUE THREAD

**Issue by vadimkantorov** [coleifer/peewee#1578]
Finding in source code something like `import playhouse.shortcuts` is not very specific or self-explaining IMO.

A big leap would be moving at least some functions like `model_to_dict` / `dict_to_model` to stock peewee, but even making them `peewee.playhouse.model_to_dict` would be more discoverable.

Thanks for a great package!

**Comment by coleifer** [comment]
This is simply how peewee is organized. Peewee is a standalone python module and all extras/extensions are included in a separate namespace.

**Comment by vadimkantorov** [comment]
I see your point. My suggestion was to move naming in the direction of making `playhouse` module name more related to peewee. A middle ground may be `peweeplayhouse`?

**Comment by coleifer** [comment]
It's been this way since ... 2010? I'm not too interested in changing it.
