### ISSUE TITLE
Problem importing ManyToManyField from playhouse.fields in pipenv

### ISSUE THREAD

**Issue by KlingKong** [coleifer/peewee#1580]
Hey,

recently I am having the problem of being unable to import the ManyToManyField from playhouse.fields on an Ubuntu server where I am using pipenv to manage packages and run python. Namely the command

`from playhouse.fields import ManyToManyField`

will lead to the error:

`ImportError: cannot import name ManyToManyField`

When I am using the same import command on my computer, it works, so this problem might be related to the virtualenvironment of pipenv. However, maybe this is a problem of different versions and you could help me. 
Additionally, the import command `from playhouse.shortcuts import ManyToManyField` works. Could I use this instead of the playhouse.fields entry? Are they the same? Can you tell me, why it might not find the ManyToManyField in the playhouse.fields? I would be grateful for any reference.
Thank you.

**Comment by coleifer** [comment]
Sounds like `pipenv` has an old version of peewee on your computer.

In peewee 3.x `ManyToManyField` has moved into `peewee`, so:

```python
# 3.x
from peewee import ManyToManyField
```

I'm not familiar with `pipenv` but it sounds like it's using an older version of peewee on your computer and the newer 3.x on your server.

**Comment by KlingKong** [comment]
Thank you. This seemed to be the case for me.
