### ISSUE TITLE
Window function for MySQL

### ISSUE THREAD

**Issue by victators** [coleifer/peewee#1584]
Are the window function queries supported for MySQL databases? I tried running the following and I get a ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(PARTITION BY `t1`.`date`) AS `avg` FROM `PROJECT` AS `aap` WHERE (' at line 1")

Thank you!

```python
try: 
    db.connect()
    aap = PROJECT.alias('aap')
    query = (aap.select(aap.date, 
                        aap.animal,
                        aap.value, 
                        fn.AVG(aap.value).over(partition_by = [PROJECT.date]).alias('avg'))
                .where((aap.date == '2018-02-08') & (aap.animal == 'DOG')))
finally:
    db.close()
print([c.avg for c in query])
```

**Comment by coleifer** [comment]
> Are the window function queries supported for MySQL databases?

I'm not sure, although they are supported with integration tests for Postgresql.

**Comment by coleifer** [comment]
You might try this for now:

```python
w = Window(partition_by=[PROJECT.date])
query = (aap
         .select(aap.date, aap.animal, aap.value, fn.AVG(aap.value).over(w).alias('avg'))
         .where((aap.date == '2018-02-08') & (aap.animal == 'DOG'))
         .window(w))  # Try adding this.
```

**Comment by victators** [comment]
I tried that too from your example in the docs but I just realized my MariaDB is running on MySQL 5.6 and window functions don't seem to come out until MySQL 8.0 so it was doomed from the start. Thank you for your help though

**Comment by coleifer** [comment]
Yeah, recent MySQL and MariaDB have support but I haven't tested it personally.
