### ISSUE TITLE
Database.cursor parameter documentation and consistency.

### ISSUE THREAD

**Issue by diekhans** [coleifer/peewee#1589]
peewee-3.3.1

http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.cursor

Indicates that Database.currsor(commit=None )  has cursor as an optional an parameter.  However, It does not define what this parameter does.

playhouse.postgres_ext.PostgresqlExtDatabase.cursor(commit) has the commit parameter as required. which conflictes with the definition in the base class.

thanks for the increidble package.

**Comment by coleifer** [comment]
Thanks, I've updated the method signature for `PostgresqlExtDatabase` and mentioned in the docs that the parameter is internal-use-only. fbb4ded7000d5163344c67236fee7a1fae38991c
