### ISSUE TITLE
Feature: get_unique_row

### ISSUE THREAD

**Issue by yanghg-basefx** [coleifer/peewee#1591]
Consider: If one database can't have an unique index, but some queries must get a unique record, what should we do?

So I implement this method in SelectQuery (peewee 2.8.1):

```python
def get_unique_row(self):
    clone = self.paginate(1, 2)
    qrw = clone.execute()
    try:
        row = next(qrw)
    except StopIteration:
        raise self.model_class.DoesNotExist('...')
    else:
        try:
            next(qrw)
        except StopIteration:
            return row
        else:
            raise self.model_class.ExistsTooMany('...')
```

It's really useful for us, and avoided a lot of unexpected exceptions. So if you can add a method like it to peewee 3.X, that's best! We can easier to upgrade our own peewee branch.

Thanks!

**Comment by coleifer** [comment]
Given how easy it is to add this to your own base model class, I'm going to pass on adding similar functionality to peewee. As you noted, the proper way to guarantee uniqueness is to have a unique constraint.

```python
@classmethod
def get_unique_row(cls, *expr):
    query = cls.select().where(*expr).limit(2)
    results = list(query)
    if len(results) == 1:
        return results[0]
    elif len(results) == 0:
        raise cls.DoesNotExist
    else:
        raise NonUniqueException
```

**Comment by yanghg-basefx** [comment]
That's what I need! Thanks!
