### ISSUE TITLE
Missing things from Changes in 3.0 doc

### ISSUE THREAD

**Issue by tomako** [coleifer/peewee#1592]
I've just moved a project to the latest version and found few shortcomings that I think are missing from the list of changes. I've checked also the release notes but neither found there. Anyway they might be useful for others.

- Database class init parameter `fields` (for adding custom fields) has been renamed to `field_types`
- SQL class init parameter `params` now is expected to be iterable
- SelectQuery's `union_all` method is gone but there is an operator (`+`) instead of it. As I remember I used the method call because there was no operator. And in fact I see the `union_all` method in the CTE class. TBH it was simpler to use the operator than understand what CTE is ;)

Ps. Special thanks for the `BigAutoField`. I was about to add it.

**Comment by coleifer** [comment]
Thanks for reporting, should be fixed.

**Comment by coleifer** [comment]
I added the following methods to select queries:

* `union_all()`
* `union()`
* `intersect()`
* `except_()`
