### ISSUE TITLE
Request: forgetting to wrap comparisons in parentheses, or using the wrong operators should cause an error

### ISSUE THREAD

**Issue by robhawkins** [coleifer/peewee#1600]
Is it possible to throw an exception when someone writes a condition the wrong way in peewee?

I'm just getting to know this very useful tool.  I used it for the first time a week ago, and then again today, and had forgotten to use `&` instead of `and` and also forgot to wrap the conditions in parentheses.  This caused some unexpected results during testing and did not throw an error indicating the root cause of the issue.

Is it possible to identify such issues for the user?  This cost me an extra 45 mins of development time and I wonder if that could be avoided in the future in the off chance I forget again.  Thanks!  This is a great tool.

**Comment by coleifer** [comment]
Sorry, there's not really any way to identify these kinds of mistakes. The documentation makes it abundantly clear that you're to use `&` and `|`, typically if you do make the mistake of using `and` and `or` you won't repeat it.
