### ISSUE TITLE
Get untouched database field values

### ISSUE THREAD

**Issue by timlehr** [coleifer/peewee#1605]
Hi Charles,

in Peewee 2 I was using the `prepared()` function to store the initial field values selected from the DB in a dictionary, so I could compare it with `__data__` at any time to determine if changes have been made. I know that the dirty field is supposed to offer this functionality, but using the dirty flags, I can not determine if the user has undone his changes. Since `prepared()` is gone in version 3, I'm struggling to find a function for my subclasses to do the same thing again. Any suggestions on this matter?

Best,
Tim

**Comment by coleifer** [comment]
That is the purpose of `dirty_fields`. For your use-case I'd suggest putting an interface on-top of your model instance and routing accesses through that. In that way you can track changes.
