### ISSUE TITLE
[Feature Request] iregex support

### ISSUE THREAD

**Issue by wonderbeyond** [coleifer/peewee#1607]
See https://docs.djangoproject.com/zh-hans/2.0/ref/models/querysets/#iregex

**Comment by coleifer** [comment]
Peewee supports a regexp operator. Depending on the database you're using, you can utilize the db-specific features to handle case-sensitivity.

**Comment by coleifer** [comment]
Added support for MySQL and Postgresql. SQLite is going to be trickier and I may not implement it.

See: f631f222fe6b0c5cb68de99dede98d03454d3e3f
