### ISSUE TITLE
table_exists() function not working.

### ISSUE THREAD

**Issue by djh2020** [coleifer/peewee#1612]
I am unable to get this function to work.  I have tried (table='job'),('job'),(job),(['job']) 

![screen shot 2018-05-24 at 4 55 31 pm](https://user-images.githubusercontent.com/6467508/40524375-154da6fa-5f8f-11e8-96c5-0a1644a695fa.png)

**Comment by djh2020** [comment]
So in examining / digging through your test I see your documentation isn't accurate.  https://github.com/coleifer/peewee/blob/49c162d5939bb52627c1e6a1687e722b8bf83ec9/tests/database.py#L398


documented
<img width="702" alt="screen shot 2018-05-24 at 8 22 18 pm" src="https://user-images.githubusercontent.com/6467508/40524715-02f652c0-5f91-11e8-9f98-fa47bc38ebec.png">


actually...
<img width="341" alt="screen shot 2018-05-24 at 8 24 11 pm" src="https://user-images.githubusercontent.com/6467508/40524726-16597fe0-5f91-11e8-85a6-a36e768d2cc3.png">

**Comment by coleifer** [comment]
Thank you, I've fixed this so that the implementation matches the docs (i.e., you pass the table name).
