### ISSUE TITLE
SchemaMigrator.add_column ignores the index_type, always results a btree index.

### ISSUE THREAD

**Issue by wonderbeyond** [coleifer/peewee#1613]
with `db.create_tables`, I can get an `GIN` index for a field like below:

```python
BinaryJSONField(default=dict, index=True, null=True)
```

However, if I add a new column with `migrator.add_column`, I always get a btree index.

You may need inspecting code here: https://github.com/coleifer/peewee/blob/master/playhouse/migrate.py#L290

**Comment by coleifer** [comment]
Thanks, I've fixed this in 8a95426 and added a test and updated docs. I appreciate you taking the time to report this issue.
