### ISSUE TITLE
use value as LIKE left hand operand

### ISSUE THREAD

**Issue by gbour** [coleifer/peewee#1616]
Hello,

In sqlite, we can do a query like that (prefix being a field of mytable table):
`SELECT * FROM mytable WHERE 123456 LIKE prefix||'%'`

same in mysql:
`SELECT * FROM mytable WHERE 123456 LIKE concat(prefix,'%')`

It will match prefixes like '12' or '1234'. I use it for prefix matching.
Unfortunately with peewee, *%* left hand must be the table field.

Is there a proper way to do that ?
Thanks for your help.

**Comment by coleifer** [comment]
Sure, you can use `Value(123456)`:

```python

# If prefix is a string literal:
query = SomeTable.select().where(Value('123456').startswith('someprefix'))

# If prefix is a column on the table:
query = SomeTable.select().where(Value('123456').startswith(SomeTable.prefix))
```

**Comment by gbour** [comment]
Oh really good, I did not found it in the documentation
Thanks very much @coleifer, you made my day :+1:  

this is only in 3.4.0 version, exact ?

**Comment by coleifer** [comment]
The `Value` type was added in 3.x. Prior to 3.x you may be able to use `Param` instead.
