### ISSUE TITLE
BaseModelSelect.get does not accept a db

### ISSUE THREAD

**Issue by rammie** [coleifer/peewee#1620]
Could `db` be added as an optional parameter to this function that would be passed to `clone.execute()`? -
https://github.com/coleifer/peewee/blob/master/peewee.py#L5724

This would allow us to have much cleaner code when fetching a single row from a replica. As always, thanks so much for peewee!

**Comment by rammie** [comment]
Just for clarification, would you recommend against using code like `query.execute(replica_db)`?

It's just that we found that pattern very convenient when we migrated to using read replicas. We were able to leave the query generation unchanged and decide which database to hit later. The `bind_ctx` decorator is nice, but it requires us to know which models are used by the query at the time of choosing the database. Though this can be tackled by inspecting the query, that seems a bit undesirable. 

Amongst the methods supported by `ModelSelect`, the following all support a database parameter -  `count`, `scalar`, `iterator`, `execute`, `dicts`, `tuples`, `peek`, `first`, `exists`. The `get` method, which is inherited from `BaseModelSelect.get` instead of `Select` is the only one I could find that does not support a database parameter. I understand the argument for consistency across the board, but it would be nice for it to be consistent amongst the methods exposed by `ModelSelect`. Unless of course you recommend against using `execute(db)` directly at all.

Is there any change you would you reconsider this change? please :). If you're ok with it I can put together a PR.

Standard note of appreciation: Peewee is the best ORM I've ever used. Thank you so much for supporting it for so long!

**Comment by coleifer** [comment]
Interesting...let me give this a think when I get back to my home in the next couple days.

**Comment by coleifer** [comment]
Implemented for `ModelSelect.get()`, thanks for doing the work of looking into the existing APIs and showing where `database` is accepted. Appreciate it!

**Comment by rammie** [comment]
Thank you so much! Really appreciate this.
