### ISSUE TITLE
Override Model __repr__

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#1622]
In peewee 2 I used to be able to override the `__repr__` of a Model by creating a custom class, for example

```python
class MyBase(Model):
    def __repr__(self):
        return '<{0}: {1}>'.format(self.__class__, self.label)
```

This doesn't seem to work anymore in peewee 3 because the `__repr__` is set in `ModelBase.__new__`. Is there a way to override this? I understand that it's still possible to override `__str__`, but I'd like to be able to control the whole string output.

**Comment by coleifer** [comment]
Well, theoretically in your example you would just:

```python
def __str__(self):
     return self.label
```

But for "complete" control...yeah, not do-able at the moment.

**Comment by coleifer** [comment]
Fixed it and added a test-case showing the behavior you described.

**Comment by jansing** [comment]
Hi coleifer,

I think it is only half fixed. It now works to define `__repr__` on a model itselt, but not on an intermediate model:
```
#!/usr/bin/env python3

from peewee import *

class MyBase(Model):
    label = CharField()
    def __repr__(self):
        print("__repr__ called")
        return '[{0}: {1}]'.format(self.__class__, self)

class MyModel(MyBase):
    pass

class MyModel2(MyModel):
    def __repr__(self):
        print("__repr__ called")
        return '[{0}: {1}]'.format(self.__class__, self)

# Does not work
m = MyModel(label = "blah")
print(repr(m))
print(MyBase.__repr__, MyModel.__repr__, m.__repr__, "\n")

# Works
m = MyModel2(label = "blah")
print(repr(m))
print(MyModel2.__repr__, m.__repr__)
```
Output:
```
<MyModel: None>
<function MyBase.__repr__ at 0x7f1737a29510> <function ModelBase.__new__.<locals>.<lambda> at 0x7f1737994400> <bound method ModelBase.__new__.<locals>.<lambda> of <MyModel: None>>

__repr__ called
[<Model: MyModel2>: None]
<function MyModel2.__repr__ at 0x7f1737994620> __repr__ called
<bound method MyModel2.__repr__ of [<Model: MyModel2>: None]>
```
The `"__repr__ called"` in the second last line of the output is generated by `print(m.__repr__)` calling `__name__` on the bound function, which itself calls `repr` on the object that `m.__repr__` is bound to (that is `m`) btw.

Peewee is really a nice library :). Very well designed!

**Comment by warvariuc** [comment]
@coleifer  is it possible to fix the issue to be able to define `__repr__` on a parent model?
