### ISSUE TITLE
MySQLDatabase return "using password: NO" when password is provided

### ISSUE THREAD

**Issue by ketozhang** [coleifer/peewee#1626]
*Version: 3.5.0*

I'm trying to validate my connection via `MySQLDatabase` on a fresh MySQL server (added a user with permission to specified database) but it's not accepting a password:

```py
>>> db = MySQLDatabase('database', user='username', password='***')
>>> db.get_tables()
(1045, "Access denied for user 'username'@'localhost' (using password: NO)")
```

I checked `db.__dict__['connect_params']['password']` and it exist there.This differs from another MySQL server which uses peewee@3.2.2, succeeds to connect.

**Comment by naktu** [comment]
Can you connect to this database directly without peewee?

**Comment by ketozhang** [comment]
@natku

Yes, I can access the database as root and other users.

I've tried the MySQLDatabase with other users as well.

**Comment by coleifer** [comment]
Have you tried using `passwd` instead of `password` for the password field?

**Comment by ketozhang** [comment]
@coleifer

Yes I have

**Comment by coleifer** [comment]
What MySQL driver are you using? Are you able to connect to the database using the driver directly? (e.g. pymysql, mysql-connector, etc)

**Comment by coleifer** [comment]
Since I haven't heard anything I am closing.

**Comment by ketozhang** [comment]
@coleifer 

Sorry for the late response, couldn't test out your question until the next weekday. Seems like pymysql returns the same error. So the root error doesn't seem to be peewee. Any suggestions?

```py
>>> pymysql.connect(db='database', user='username', password='***')
(1045, "Access denied for user 'intern'@'localhost' (using password: NO)")
```

**Comment by coleifer** [comment]
Thanks for the edit homie...that's interesting. So sounds like a pymysql + mysql 8 / sha256 bug? You can use the de-facto mysql driver, "mysql-connector" with py3k if you wish. e.g.:

https://github.com/coleifer/peewee/blob/master/playhouse/mysql_ext.py

**Comment by bmwant** [comment]
I had exact the same issue with 
```
>>> pymysql.__version__
'0.8.0'
```
and simple upgrade `pip install pymysql --upgrade` to `0.9.3` version resolved it.

**Comment by iq1604** [comment]
> I had exact the same issue with
> 
> ```
> >>> pymysql.__version__
> '0.8.0'
> ```
> 
> and simple upgrade `pip install pymysql --upgrade` to `0.9.3` version resolved it.

this worked, its seems there is some issue with the version 0.8.0/0.8.1. upgrading the package is working for me. Thanks!

**Comment by deepthi2514** [comment]
im getting Failed to connect to MySQL: Access denied for user ''@'localhost' (using password: NO)Wrong Username or Password error when i run one project in xampp 7.3.11 please help me to solve this error

**Comment by coleifer** [comment]
Are you able to connect to the mysql database using the mysql shell?

**Comment by deepthi2514** [comment]
yes

**Comment by ardamelih** [comment]
Hi, 
for a school project i created a simple webpage and using flask  i am trying to connect it to mysql. I am getting exactly the same error mentioned above. I am not a programmer and dont really understand what's going on here. I couldn't really benefit from or understand what has been written above sofar, probably due to my lack of knowledge. Can somebody tell me what l need to do?
my code looks like this : 
`app.config['MYSQL_HOST'] = 'localhost'
app.config['MYSQL_USER'] = 'root'
app.config['MYSQL_PASSWORD'] = 'mypassword'
app.config['MYSQL_DB'] = 'mysql_db'
mysql = MySQL()
mysql.init_app(app)
`
