### ISSUE TITLE
better documentation of the init function

### ISSUE THREAD

**Issue by 42sol-eu** [coleifer/peewee#1627]
The initialization of the Database classes with ``None`` as a name is not very obvious.

In my opinion it would be helpful to add this call directly to the quick start example.

see my suggestion at https://github.com/42sol-eu/peewee/blob/master/docs/peewee/quickstart.rst

What would you suggest?

**Comment by coleifer** [comment]
It's documented here: http://docs.peewee-orm.com/en/latest/peewee/database.html#run-time-database-configuration

Is there something specific you feel is missing?

**Comment by 42sol-eu** [comment]
Yes you are right, we had trouble to find it and it is not in any of the tutorial examples. The usage of None on the first parameter is also not described in the parameter description of the classes. This where the reasons for my supossed change in one or more of the quickstart examples.

**Comment by coleifer** [comment]
>  it is not in any of the tutorial examples

Yes, this is intention as it's not considered the common use-case.

Right at the very top there is a note call-out explaining deferred initialization:

http://docs.peewee-orm.com/en/latest/peewee/api.html#Database

> The database can be instantiated with None as the database name if the database is not known until run-time. In this way you can create a database instance and then configure it elsewhere when the settings are known. This is called deferred initialization.
>
> To initialize a database that has been deferred, use the init() method.
