### ISSUE TITLE
How to handle "Reference Cycles"

### ISSUE THREAD

**Issue by JoshuaC3** [coleifer/peewee#1628]
I have an auto generated db_model using pwiz. However, there is a reference cycle such that

```
class DataFaultReview(BaseModel):
    data_fault = ForeignKeyField(column_name='data_fault_id', field='id', model=DataFault)
```

and 

```
class DataFault(BaseModel):
    current_review = ForeignKeyField(
        column_name='current_review_id', field='data_fault_review',
        model=DataFaultReview, null=True
)
```

reference one another.

How can/should I handle this?

Many thanks :)

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/models.html#circular-foreign-key-dependencies
