### ISSUE TITLE
Force one-to-one backref?

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#1629]
Is there a way to force a backref in a foreign key to be one to one? Right now all backrefs seem to create a list even if one takes measures to ensure the relationship is one-to-one (e.g., by making the backref column UNIQUE). In SQLA one can manage this by doing

```
relationship(ToModel, backref=backref(FromModel, uselist=False))
```

Is there a way to do this in peewee?

**Comment by coleifer** [comment]
No, this isn't supported as-such, but you are on the right track by adding a unique constraint. In this case why not just add a `property` or something to look-up the one-to-one related model?

**Comment by albireox** [comment]
Right, I hadn't thought of using a property but that works nicely. It would be nice if this becomes a feature at some point but for now this works for my needs. Thanks.

**Comment by coleifer** [comment]
For simplicity's sake I'll probably leave it for now, but thanks.
