### ISSUE TITLE
Benchmark with PostgreSQL gives worse insert results than with MySQL

### ISSUE THREAD

**Issue by sapph1re** [coleifer/peewee#1633]
I'm running bench.py. Using python 3.5, peewee 3.5.0, on Debian 9 with 64 GB of RAM.

With a MySQL database (driver mysqlclient):
```
insert 0.232
insert_related 0.315
batch_insert 0.227
bulk_insert 0.027
select 0.093
select_related 0.26
select_related_left 0.237
select_related_dicts 0.09
```

With a PostgreSQL database (driver psycopg2):
```
insert 0.35
insert_related 0.52
batch_insert 0.32
bulk_insert 0.024
select 0.082
select_related 0.218
select_related_left 0.205
select_related_dicts 0.064
```

Why are results with PostgreSQL are significantly worse on inserting operations than with MySQL? PostgreSQL is supposed to be faster, isn't it?

**Comment by coleifer** [comment]
This is such a complicated subject. It depends on many, many variables and config settings. The bench is an internal script I use to profile the code sometimes after making big changes. It's in no way an indication of how well a database is performing. Be smart. Ignore it. It is literally meaningless.
