### ISSUE TITLE
Improve pwiz documentation with some examples

### ISSUE THREAD

**Issue by willyhakim** [coleifer/peewee#1642]
Pwiz is a helluva an awesome tool. Improving the docs around it by giving some examples for postgres, mysql and sqlite would be super cool.

**Comment by coleifer** [comment]
Thank you for the suggestion, I'll look into it. Glad you find it helpful!

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#pwiz-a-model-generator

Now includes more examples. Thanks for the suggestion.

**Comment by willyhakim** [comment]
Hahaha. You're so fast. I was hoping to make that my first PR
