### ISSUE TITLE
reflection got wrong mysql blob field type

### ISSUE THREAD

**Issue by GrayMissing** [coleifer/peewee#1644]
using pwiz to reflect created mysql table, I found blob column got a TextField defintion, which can lead to codec error. I don't think it's a proper way to decode byte_array using utf-8.

I read the issue before #1034 , but django's TextField seems more like BlobField in peewee...

**Comment by coleifer** [comment]
I'm confused by your issue. What exactly is the problem you are reporting? And if you read #1034, what are you confused about?

**Comment by GrayMissing** [comment]
pwiz reflect mysql blob column to TextField, and TextField decode byte value using utf-8

**Comment by coleifer** [comment]
Yeah, as it states in #1034, Peewee cannot differentiate blob from text due to a limitation in the introspection provided by pymysql. So you need to go through and change the TextFields to BlobFields.
