### ISSUE TITLE
Support for Postgres 10 IDENTITY columns

### ISSUE THREAD

**Issue by seamons** [coleifer/peewee#1650]
#Postgresql 10 has a new IDENTITY columns that replace SERIAL column:

> This is the SQL standard-conforming variant of PostgreSQL's serial
columns.  It fixes a few usability issues that serial columns have:
> - CREATE TABLE / LIKE copies default but refers to same sequence
> - cannot add/drop serialness with ALTER TABLE
> - dropping default does not drop sequence
> - need to grant separate privileges to sequence
> - other slight weirdnesses because serial is some kind of special macro

SQLAlchemy has partially supported for it: [PostgreSQL — SQLAlchemy 1.2 Documentation](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#postgresql-10-identity-columns)

I have tweaked the Peewee field to use IDENTITY column as follows:
```py
class AutoField(peewee.IntegerField):
    """Auto Increment ID Field

    Suport PostgreSQL 10's IDENTITY column.
    """
    #sequence = None # Disable sequence for auto increment id
    #auto_increment = True
        
    def __init__(self, *args, **kwargs):
        kwargs['primary_key'] = True
        kwargs['unique'] = True
        kwargs['constraints'] = [peewee.SQL("GENERATED BY DEFAULT AS IDENTITY")]
        super().__init__(*args, **kwargs)
```

Do you have any plan to officially support this feature?

**Comment by coleifer** [comment]
I slightly changed this:

```python
class IdentityField(AutoField):
    field_type = 'INT GENERATED BY DEFAULT AS IDENTITY'
```

**Comment by coleifer** [comment]
Added support. By default Peewee will continue to use `AutoField` (which corresponds to `SERIAL`), but you now have the option of using `IdentityField` instead:

```python
class MyModel(Model):
    id = IdentityField()
    data = TextField()
```

**Comment by seamons** [comment]
Cool! Thanks for the rapid response
