### ISSUE TITLE
Incorrect syntax for index creation in Sqlite when using schema

### ISSUE THREAD

**Issue by astrilchuk** [coleifer/peewee#1654]
Creating an index on a table with a schema specified (other than the default) produces the following sql for a Sqlite database:

CREATE UNIQUE INDEX IF NOT EXISTS "programhash_program_id" ON "cache"."programhash" ("program_id")

The Sqlite definition for index creation (https://www.sqlite.org/lang_createindex.html) states it should appear as:

CREATE UNIQUE INDEX IF NOT EXISTS "cache"."programhash_program_id" ON "programhash" ("program_id")

Thanks

**Comment by coleifer** [comment]
Nice catch, thanks for reporting.
