### ISSUE TITLE
Error when attaching Sqlite db using APSW

### ISSUE THREAD

**Issue by astrilchuk** [coleifer/peewee#1655]
I'm using APSW database driver(?) with peewee 3.5.1 and Sqlite and I am attempting to attach an in-memory database with the attach command:

db = apsw_ext.APSWDatabase("storage.db", pragmas=dict(foreign_keys=1, journal_mode="wal", cache_size=-1000 * 64))
...
db.attach(":memory:", "cache")

I'm getting an error on line 2812 of peewee.py stating: "'apsw.Connection' object has no attribute 'execute'".

Looking at the apsw docs, it appears that their connection object does not have have an execute() shortcut method.

If there's any more information I can provide please let me know.

Thanks

**Comment by coleifer** [comment]
Thanks, fixed: 3475cbe0e092d9cea7f527b3a6a380b9bf714b86
