### ISSUE TITLE
something like id__in(Django) for peewee

### ISSUE THREAD

**Issue by salvador-immortal** [coleifer/peewee#1657]
hi , 
does peewee provide something like this on django ?? 
`Model.objects.filter(id__in=instance['model_ids'])`
the instance['model_ids'] is list of ids ([1,2,3,4,5,6])

i know i can use `on((Model.id==instance['id][0]) & |.......................)`

but my list length isnt fixed ,, can change
i want to get all of them once in single query,,

**Comment by coleifer** [comment]
`.where(MyModel.id.in_([1, 2, 3, 4]))`

http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#id1
