### ISSUE TITLE
Reject or warn on naive datetime objects for playhouse.postgres_ext.DateTimeTZField?

### ISSUE THREAD

**Issue by wonderbeyond** [coleifer/peewee#1662]
When assign a naive datetime object to a model filed of DateTimeTZField, it results an utc-timezoned value into db.

This behavior is crude, because without the knowledge of the current timezone we cannot convert a naive datetime object to the right aware one.

Can we let DateTimeTZField just reject on naive datetime objects?

**Comment by coleifer** [comment]
I'm going to leave it as-is, but you are welcome to subclass `DateTimeTZField` and add whatever validation you want in the appropriate places.
