### ISSUE TITLE
TimestampField, Microseconds (Precision=10**6) and Postgres

### ISSUE THREAD

**Issue by yakirmar** [coleifer/peewee#1672]
Hi,
I created a Postgres DB with "PostgresqlDatabase" object and the field was defined like this:
`timestamp = TimestampField(resolution=10**6, index=True)`

Everything works great when I did some tests with SQLite but when I moved to Postgres, it created an integer field in the DB and the numbers that I want to insert (like this 1531326087799518) is much bigger than integer/int4.

How can I change it to be BigInt (according this: https://www.postgresql.org/docs/9.2/static/datatype-numeric.html#DATATYPE-INT)?

Thanks in advance,
Yakir

**Comment by coleifer** [comment]
Whoops, oversight on my part. I need to change the underlying field type to `BigIntegerField`. Will have a patch up shortly.

**Comment by coleifer** [comment]
3b89d3af132d06f986642384ffbdadfcffbfa563
