### ISSUE TITLE
Query do not support "%s as something"

### ISSUE THREAD

**Issue by m358807551** [coleifer/peewee#1679]
worked:
`PersonModel.raw("select name from person where id=%s", (1,))`
not worked:
`PersonModel.raw("select name, %s as field1 from person where id=%s", ("aaa",1))`

**Comment by coleifer** [comment]
Is there a reason you are using ".raw()"? You could very easily write your second example as:

```python
Person.select(Person.name, Value('aaa').alias('field1')).where(Person.id == 1)
```

I'm not sure why `%s as field1` wouldn't work. What error are you receiving? What database are you using?

**Comment by coleifer** [comment]
Aha, I see the problem. The documentation also reveals the issue: http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.raw

`Model.raw()` accepts the query parameters as `*args`, not as a tuple of arguments. So you can fix the problem:

```python
PersonModel.raw("select name, %s as field1 from person where id=%s", "aaa", 1)
```

**Comment by m358807551** [comment]
Thank you!!
I lose my mind!!〣( ºΔº )〣
