### ISSUE TITLE
One sequence for all primary keys in all tables of database

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#1681]
Hi!
This is very specific requirement: create a one sequence for all primary keys in all tables of database with start from 10000. It's simple for cli but is it possible to do in schema creation process?

Thanks!

**Comment by coleifer** [comment]
Your best bet is to simply add the following before you create the tables:

```python

def setup_schema():
    with db:
        db.execute_sql('create sequence if not exists "sequence_name" start with 10000')
        db.create_tables([Foo, Bar, Baz, etc])
```

**Comment by ak04nv** [comment]
Is it possible to change this sequence for all AutoField fields for all models?
This does not work for me:
```python
    for m in MODELS:
        if hasattr(m, 'id'):
            m._meta.fields['id'].sequence = 'id_generator'
        m.create_table()
```

**Comment by coleifer** [comment]
You can always do something like this, too:

```python
class MyAutoField(AutoField):
    def __init__(self, *a, **k):
        super(MyAutoField, self).__init__(sequence='the_sequence', *a, **k)
```

And use `id = MyAutoField()` in your models.

**Comment by ak04nv** [comment]
As I understand this code raise exception for postgresql if you create a table. Too many default values for field or something like this. Should be `IntegerField` instead of `AutoField` and add `primary_key=True` for arguments.
If you suggest another way would be great!
