### ISSUE TITLE
How to sort by geo distance?

### ISSUE THREAD

**Issue by BadReese** [coleifer/peewee#1686]

**Comment by BadReese** [comment]
provide a geo point, and sorted by distance

**Comment by coleifer** [comment]
I'm assuming you're using something like PostGIS for Postgresql, or Spatialite for SQLite.

You just need to find the appropriate distance function and call it, e.g. [ST_distance](https://postgis.net/docs/ST_Distance.html):

```python
fn.ST_Distance(SomeModel.point_1, SomeModel.point_2)
```
