### ISSUE TITLE
`User.select().dicts()` not return dict-list

### ISSUE THREAD

**Issue by bingtel** [coleifer/peewee#1697]
When I want to get a list of dict by `q = User.select().dicts()` , q is not a list of dict;
I have to `[e for e in q]` to get a dict-list.

**Comment by coleifer** [comment]
Peewee lazily evaluates queries -- they are not evaluated until iterated (or you explicitly call .execute(), and in that case you get a special/smart iterator).

To get a list of dicts, either:

```python
q = User.select().dicts()
list_of_dicts1 = q[:]
list_of_dicts2 = list(q)
list_of_dicts3 = [d for d in q]
```
