### ISSUE TITLE
Clause equivalent in version 3

### ISSUE THREAD

**Issue by dougalsutherland** [coleifer/peewee#1704]
I was using [this hack](https://github.com/coleifer/peewee/issues/1181#issuecomment-274626273), which worked in peewee 2, but `peewee.Clause` seems to not be a thing anymore.

How can I pass a `SEPARATOR` argument to `GROUP_CONCAT` in peewee 3?

**Comment by coleifer** [comment]
```python
from peewee import NodeList

fn.GROUP_CONCAT(NodeList((
    MyModel.test_score.distinct(), 
    SQL('ORDER BY'), 
    MyModel.test_score.desc(), 
    SQL('SEPARATOR \' \''))
))
```

INTO:

```sql
GROUP_CONCAT(DISTINCT "t1"."test_score" ORDER BY "t1"."test_score" DESC SEPARATOR ' ')
```

**Comment by dougalsutherland** [comment]
Cool, thanks. :)
