### ISSUE TITLE
Add possibility to add constrains in schema migrations

### ISSUE THREAD

**Issue by rominf** [coleifer/peewee#1706]

**Comment by coleifer** [comment]
This is already possible, if I understand the request correctly.

When adding a new column, you can add arbitrary constraints:

```python
price = FloatField(default=0., constraints=[Check('price >= 0.0')])
migrator = SchemaMigrator.from_database(db)
# Add the "price" column, which includes a CHECK() constraint.
migrate(migrator.add_column('some_table', 'price', price))
```

**Comment by coleifer** [comment]
Added support for adding/dropping generic table constraints: https://github.com/coleifer/peewee/commit/128e41ce16473baaeb24cc74864a088884a7e0cb#diff-77fadcec703631c9bc463a8865569f1bR2999
