### ISSUE TITLE
sql LENGTH function convert to peewee expression

### ISSUE THREAD

**Issue by mouday** [coleifer/peewee#1709]
sql `select * from table  where  LENGTH(name) < 45`

can I convert to peewee expression? thank you!

**Comment by coleifer** [comment]
```.where(fn.LENGTH(SomeModel.name) < 45)```

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/querying.html#filtering-records

**Comment by mouday** [comment]
thank you

**Comment by ElysiumFan086** [comment]
> `.where(fn.LENGTH(SomeModel.name) < 45)`

I have tried this, but it still does not work. Checking query.sql() info, there where condition with LENGTH function is missing.

start_date = datetime.datetime.strptime(start_time, '%Y%m%d')
end_date = datetime.datetime.strptime(end_time, '%Y%m%d')

query = MyModel.select(MyModel.name, MyModel.original_recall) \
            .where((~MyModel.inter_city_id.contains('null')))
query.where((fn.LENGTH(MyModel.core_line_id) != 19))\
         .where((MyModel.city_id == city_id))\
         .where((MyModel.add_time > start_date))\
         .where((MyModel.add_time < end_date))
print(query.sql())

The result is:
('SELECT `t1`.`name`, `t1`.`original_recall` FROM `test_data_table` AS `t1` WHERE (((NOT (`t1`.`inter_city_id` LIKE %s) AND (`t1`.`city_id` = %s)) AND (`t1`.`add_time` > %s)) AND (`t1`.`add_time` < %s))', ['%null%', '1', datetime.datetime(2021, 11, 25, 0, 0), datetime.datetime(2021, 11, 26, 0, 0)])
