### ISSUE TITLE
How do I make table names plural?

### ISSUE THREAD

**Issue by moar55** [coleifer/peewee#1714]
I like the default table naming function except that I want table names to be plural. How do I achieve this easily?

**Comment by krisfremen** [comment]
You can easily override the default naming.

```
class Project(Model):
    class Meta:
        table_name = 'projects'
```

See [here](http://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata) for more.

**Comment by moar55** [comment]
I knew about this I was thinking of making the table name function automatically append the 's' at the end of the table name. But I guess this is good enough too...

**Comment by krisfremen** [comment]
You can of course do a custom class that will create the model to be used with a generated table name .

https://github.com/coleifer/peewee/blob/ccf8ac09e6cd571a3becea0b31af9418fcb05a94/playhouse/kv.py#L55

Look at the above class for an example how to accomplish that.

Bit of a tricky case determining plurals, simply adding "s" doesn't make every word automatically plural, but if you use simple words, I guess you'll be fine.

**Comment by coleifer** [comment]
There is an example of a custom table naming function here: http://docs.peewee-orm.com/en/latest/peewee/models.html#table-names

Code from docs:

```python
def make_table_name(model_class):
    model_name = model_class.__name__
    return model_name.lower() + '_tbl'

class BaseModel(Model):
    class Meta:
        table_function = make_table_name

class User(BaseModel):
    # table_name will be "user_tbl".

class UserProfile(BaseModel):
    # table_name will be "userprofile_tbl".
```
