### ISSUE TITLE
Is there tinyint type in models?

### ISSUE THREAD

**Issue by moar55** [coleifer/peewee#1715]

**Comment by krisfremen** [comment]
Refer to [this table](http://docs.peewee-orm.com/en/latest/peewee/models.html#field-types-table) for fields that are currently supported in peewee.

For any other database specific types, you can easily create a [custom field](http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field).

Example:
```
class TinyIntegerField(IntegerField):
    field_type = 'TINYINT'
```

**Comment by moar55** [comment]
ok thanks!

**Comment by moar55** [comment]
Btw do you think it really matters perforamnce wise if i switch to tinyint?
This is a field with a value from 1 to 5.

**Comment by krisfremen** [comment]
You won't get any performance gain from peewee itself.

But depending on your database implementation/set up in regards to indexing, storage and so forth, you might see some gain.

**Comment by moar55** [comment]
Thanks!
