### ISSUE TITLE
Different syntax for python2 and python3

### ISSUE THREAD

**Issue by jbriales** [coleifer/peewee#1729]
Hi, I'm just starting to use peewee and pwiz, and it took a while to figure out this error:
TypeError: __init__() got an unexpected keyword argument 'column_name'
Apparently the syntax is different in the python2 and python3 versions,
so I got different results calling:
`python2 -m pwiz -e sqlite "testDB.sqlite" > testmodels.py`
`python3 -m pwiz -e sqlite "testDB.sqlite" > testmodels.py`

I installed both versions via pip.

**Comment by coleifer** [comment]
Uhh, it sounds like in one case you are running an old version of Peewee.

You can verify by running

```
python2 -c "import peewee; print(peewee.__version__)"
python3 -c "import peewee; print(peewee.__version__)"
```
