### ISSUE TITLE
VARCHAR not correctly parsed in pwiz

### ISSUE THREAD

**Issue by jbriales** [coleifer/peewee#1730]
Hi,
I was using pwiz in python3 with sqlite and it seems VARCHAR fields are not correctly parsed:

If no max length is provided, the field is not recognized:
```
CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           VARCHAR NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        TEXT,
   SALARY         REAL
);
```
```
class Company(BaseModel):
    address = TextField(db_column='ADDRESS', null=True)
    age = IntegerField(db_column='AGE')
    id = PrimaryKeyField(db_column='ID')
    name = UnknownField(db_column='NAME')  # VARCHAR
    salary = FloatField(db_column='SALARY', null=True)

    class Meta:
        db_table = 'COMPANY'
```

If max length is provided, I don't get it in models.py:
```
CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           VARCHAR(50) NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        TEXT,
   SALARY         REAL
);
```
```
class Company(BaseModel):
    address = TextField(db_column='ADDRESS', null=True)
    age = IntegerField(db_column='AGE')
    id = PrimaryKeyField(db_column='ID')
    name = CharField(db_column='NAME')
    salary = FloatField(db_column='SALARY', null=True)

    class Meta:
        db_table = 'COMPANY'
```

**Comment by coleifer** [comment]
Thanks, I've fixed the issue where VARCHAR without a length constraint is now recognized correctly with Sqlite -- fdeb92c1639c1dc9301ae501b95e36d83a63ee74

Regarding the max_length parameter, this has no effect in Sqlite and so it is fine to ignore it:

```sql
sqlite> create table kv (key varchar(4) not null primary key, value varchar(8) not null);
sqlite> insert into kv (key, value) values ('abcdefghij', '12345678901234567890');
sqlite> select * from kv;
abcdefghij|12345678901234567890
```

**Comment by jbriales** [comment]
Thanks for the fix, it's working now :)
However I still found two failing cases in my database:
# CHAR[38]
# FLOAT
I will make a pull request next.

**Comment by coleifer** [comment]
Eh.. You know SQLite only supports the following data-types, right?

* TEXT
* BLOB
* INTEGER
* REAL
* NULL

**Comment by jbriales** [comment]
Uhm... just starting with SQL so... why would this database I'm working with have those other fields? Is it maybe not actually SQLite? (although reading/writing to it as a SQLite works)

**Comment by coleifer** [comment]
SQLite is permissive about what it accepts, but internally it only knows about the data-types I mentioned.
