### ISSUE TITLE
id field value is None

### ISSUE THREAD

**Issue by jbriales** [coleifer/peewee#1733]
I'm trying to get the id field of a SQLite table but I always get None:
# Model:
```
class Document(BaseModel):
    id = IntegerField(db_column='id', primary_key=True, null=False, index=True)

    class Meta:
        db_table = 'Documents'
```
# Query:
```
query = Document.select()
    with db.atomic():
        for doc in query:
            print(doc.id)
```
The id field exists in the table as
`id` INTEGER PRIMARY KEY AUTOINCREMENT

**Comment by coleifer** [comment]
Uh... I know for a fact that something as fundamental as retrieving a column value from a select query is working -- it's covered quite thoroughly in the tests.

Perhaps you can provide a test-case or complete script so I can replicate the issue?

**Comment by jbriales** [comment]
Ok, you are fully right. Your mention of tests gave me an idea.
I tried tests and a simpler toy example and it revealed I had done some (apparently) small change inside peewee which however provoked this malfunctioning...
Working fine now! Sorry for the false alarm :)
