### ISSUE TITLE
Psycopg2 warning

### ISSUE THREAD

**Issue by yabirgb** [coleifer/peewee#1734]
I get this warning when running peewee with postgresql:

`UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.`

If I uninstall `psycopg2` and install `psycopg2-binary` I get the error `peewee.ImproperlyConfigured: Postgres driver not installed!`

**Comment by coleifer** [comment]
That doesn't sound correct at all. `psycopg2-binary` should install a psycopg2 package normally. It's just a binary package rather than a source package.

**Comment by coleifer** [comment]
See:

```
$ pip freeze | grep psycopg2
65:psycopg2-binary==2.7.5
(notebook) media@rho:~/envs/notebook$ ipython
Python 3.7.0 (default, Jul 15 2018, 18:17:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from peewee import PostgresqlDatabase

In [2]: db = PostgresqlDatabase('peewee_test')

In [3]: db.connect()
Out[3]: True
```

**Comment by yabirgb** [comment]
Ok thanks! I will check then what other thing could be failing. Sorry for the inconvenience
