### ISSUE TITLE
`sqlall()`gone missing in 3.x

### ISSUE THREAD

**Issue by jberkel** [coleifer/peewee#1736]
I'm just migrating a bunch of code from 2.x to 3.x. Nice job! My code previously used  `Model.sqlall()` to create a file with the current SQL schema. This method is gone in 3.x, and I don't see a replacement for it. I could easily reproduce this with some extra lines of code but I still think it's a worthwhile method to have, if only for quick debugging of schemas.

**Comment by coleifer** [comment]
> I could easily reproduce this with some extra lines of code

Go for it.

Updated the changes documentation to reflect the removal of this. Apologies for the confusion.
