### ISSUE TITLE
Incorrect sql generated by custom field

### ISSUE THREAD

**Issue by fy0** [coleifer/peewee#1738]
My database is PostgreSQL.

Field:
```
class INETField(peewee.Field):
    db_field = 'inet'
```

Model:
```
    reputation = IntegerField(default=0)
    ip_registered = INETField(default=None, null=True)
```

Error:
```
    cursor.execute(sql, params or ())
peewee.ProgrammingError: syntax error at or near ","
LINE 1: ...L, "reputation" INTEGER NOT NULL, "ip_registered" , "reset_k...                    
```

type, default and "not null" lost.
An old version: 3.5.2
Upgraded to 3.7.0, it still happened.

Is it a bug or some thing wrong with my code?

**Comment by coleifer** [comment]
In 3.x you need to use `field_type` instead of `db_field`. The docs are pretty clear:

http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field

**Comment by fy0** [comment]
@coleifer Sorry, in fact I had read the document before, but copy & paste my old code in the same file when I programming...
