### ISSUE TITLE
3.x index renaming

### ISSUE THREAD

**Issue by jberkel** [coleifer/peewee#1739]
I'm not sure if this is working as intended, but after upgrading to 3.x I get a different schema because of index renames.

I use `table_name` to set the table name, but the index name seems to use the automatic table name as prefix, e.g.

```python
class Foo
    some_text = TextField(index=True)

    class Meta
        table_name = "foos"
````

results in `CREATE INDEX "foo_some_text" ON "foos" ("some_text")` and not `CREATE INDEX "foos_some_text" ON "foos" ("some_text")` as it did previously.

**Comment by coleifer** [comment]
I'm not seeing that, actually. I added a testcase which to me validates that the behavior in 3.x respects the table name as the prefix.

47170c381329057f26ee5fb121eef54dbb7944e3

**Comment by jberkel** [comment]
Thanks for investigating, found the issue. I wasn't using `legacy_table_names = False`.

**Comment by coleifer** [comment]
When using legacy table names, Peewee will prefix the index with the model name, irrespective of the actual table name.
