### ISSUE TITLE
support sqlalchemy-style MySQL URI parameters

### ISSUE THREAD

**Issue by jwilner** [coleifer/peewee#1742]
The MySQL driver expects a dictionary of SSL parameters -- `{"cert": cert, "key": pkey, "ca": ca}`. SQLAlchemy supports these as URI components prefixed with `ssl` -- e.g. `?ssl_cert={cert}&ssl_key={pkey}&ssl_ca={ca}`. Currently, `playhouse.db_uri` has no comparable behavior, because although it parses out many types from the query string, it doesn't support nested objects.

I propose that `playhouse.db_uri` add a special case for the MySQL URIs which will support the same query params.

Basic idea would be that at the end of `parseresult_to_dict`, an additional postprocessing step would occur which would look like:
```python
if parsed.scheme == "mysql":
    _nest_by_prefix(connect_kwargs, prefix="ssl_", new_key="ssl")
```

**Comment by coleifer** [comment]
I think I'm going to pass. MySQL-Connector uses different arguments: https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html

I think this is going a bit above and beyond what the db url module was intended to do.
