### ISSUE TITLE
DeprecationWarning Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by Trim21** [coleifer/peewee#1748]
peewee.py:2256: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  is_dict = isinstance(row, collections.Mapping)

python version 3.7.0
peewee version 3.7.1

**Comment by coleifer** [comment]
49ca301f319a6a70d7acd1425b66fa5cbdf75d8e
