### ISSUE TITLE
peewee.OperationalError: SSL error: bad decrypt

### ISSUE THREAD

**Issue by maxcountryman** [coleifer/peewee#1757]
Running into this issue when spawning processes with `concurrent.futures.ProcessPoolExecutor`.

**Comment by coleifer** [comment]
I'm guessing you're opening the database connection before the fork? Try opening the connection after forking.

**Comment by maxcountryman** [comment]
Actually no, I’m not. The connection is initialized in the function the executor handles.

**Comment by coleifer** [comment]
Can you share a minimal example?

**Comment by coleifer** [comment]
If you could please let me know:

* What database engine / python driver combination are you using?
* What is the output of "print(db.is_closed())" when your forked processes are starting up?
* Are you sure it's not possible that some connection state is copied to the child process when forking?
