### ISSUE TITLE
model_to_dict + ManyToManyField shows abthrough_set instead of bs

### ISSUE THREAD

**Issue by patarapolw** [coleifer/peewee#1761]
>>> model_to_dict(db['card'].select()[1], backrefs=True)
    {'id': 1520716970993,
     'note': {'id': 1520716965129,
      'data': {'中文': '我们现在没有钱。',
       'Pinyin': 'Wǒmen xiànzài méiyǒu qián.',
       'English': "We don't have money now.",
       'Notes': '',
       'Example Type': '',
       'Article Title': 'Negation of "you" with "mei"',
       'Grammar Construct': '没 + 有 (+ Obj.)',
       'Source URL': 'https://resources.allsetlearning.com/chinese/grammar/ASGPNV3Q'},
      'notetagthrough_set': [{'id': 7, 'tag': {'id': 2, 'name': 'Adverbs'}},
       {'id': 6, 'tag': {'id': 3, 'name': 'Parts_of_Speech'}},
       {'id': 8, 'tag': {'id': 4, 'name': 'A1'}}]},
     'deck': {'id': 1496896533573, 'name': 'Chinese Grammar Wiki'},
     'template': {'id': 2,
      'model': {'id': 1496733135171,
       'name': 'Chinese Grammar Wiki',
       'css': '.card {\nfont-family: arial;\nfont-size: 30px;\ntext-align: center;\ncolor: black;\nbackground-color: white;\n}\n\n.hanzi {\nfont-family: SimSun;\nfont-size: 28px;\n}\n\n.pinyin {\ncolor: gray;\n}\n\n.translation {\nfont-size: 26px;\n}\n\n.lessonInfoHanzi {\nfont-family: SimSun;\nfont-size: 12px;\n}\n\n.lessonInfo {\nfont-family: arial;\nfont-size: 10px;\n}\n\n.english {\nfont-family: arial;\nfont-size: 20px;\n}\n\n.notes {\nfont-family: arial;\nfont-size: 12px;\ncolor: gray;\n}\n\n.spacer {\nheight: 20px;\n}\n\n.spacerSmall {\nheight: 3px;\n}\n\n.spacerMedium {\nheight: 10px;\n}\n'},
      'name': 'Translation',
      'question': '<div class="hanzi">{{中文}}</div>',
      'answer': '{{FrontSide}}\n<div class="spacer"> </div>\n<div class="english">\n\t<div class="pinyin">{{Pinyin}}</div>\n\t<div class="spacerSmall"> </div>\n\t{{English}}\n\t<div class="spacerMedium"> </div>\n\t<div class="notes">{{Notes}}</div>\n</div>\n\n\n<div class="lessonInfo">\n<div class="spacer"> </div>\n<div>Pattern: <span class="lessonInfoHanzi">{{Grammar Construct}}</span></div>\nArticle: <a href={{Source URL}}>{{Article Title}}</a>\n</div>'},
     'srs_level': None,
     'next_review': None}

It should be `tags`, not `notetagthrough_set`.

**Comment by coleifer** [comment]
You should use `manytomany=True`:

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#model_to_dict
