### ISSUE TITLE
query result to python list

### ISSUE THREAD

**Issue by michalchrzastek** [coleifer/peewee#1765]
Hello,

I'm trying to return  a list with integers (ID column) like so:

`my list = [1,2,3,4,...]`

 but get this error, what am I missing?

`TypeError: <modelFinance.tag_list object at 0x759703d0> is not JSON serializable`

my query:

`def get_tagsID(self):
		tagQ = tag_list.select(tag_list.id)
		return list(tagQ)`

**Comment by coleifer** [comment]
It's returning a list of tag instances...you need to:

```python
def get_tagsID(self):
    tagQ = tag_list.select(tag_list.id)
    return [tl.id for tl in tagQ]
```

Also python typically prefers lower case w/underscores instead of that camelCase just fyi.

**Comment by coleifer** [comment]
By the way, try reading the error message...it seems completely obvious to me at least.

**Comment by michalchrzastek** [comment]
Thank you, it works perfectly. No sorry, don't understand the error...
