### ISSUE TITLE
choices are not working!

### ISSUE THREAD

**Issue by surajano** [coleifer/peewee#1770]
In the following code the choices for Task tables are not working, while creating the instance of Task with status="Success",  its not adding the choices value(ie "S") in the task DB table. Its adding the "Success" as it is in the task table.
```
from datetime import datetime
import peewee

db = peewee.SqliteDatabase('peewee_choices.db')


class Task(peewee.Model):
    """
    Some Task table Model
    """
    TASK_STATUS = (
        ("S", "Success"),
        ("F", "Failure"),
        ("U", "Unknown"),
    )

    status = peewee.CharField(choices=TASK_STATUS)
    timestamp = peewee.DateTimeField(default=datetime.utcnow())

    class Meta:
        database = db


if __name__ == "__main__":
    db.connect()
    db.create_tables([Task])
    task_events_1 = Task(status="Success")
    task_events_1.save()
    task_1 = Task.get(status="Success")
    print("Task 1 Status : ", task_1.status) # Task 1 Status :  Success

    task_events_2 = Task(status="S")
    task_events_2.save()
    task_2 = Task.get(status="S")
    print("Task 2 Status : ", task_2.status) # Task 2 Status :  S
    db.drop_table(Task)
    db.close()


```
When we run the above code it will print the following:
Task 1 Status :  Success
Task 2 Status :  S

**Comment by coleifer** [comment]
* http://docs.peewee-orm.com/en/latest/peewee/api.html?highlight=choices#Field
* http://docs.peewee-orm.com/en/latest/peewee/models.html?highlight=choices#some-fields-take-special-parameters

> Both default and choices could be implemented at the database level as DEFAULT and CHECK CONSTRAINT respectively, but any application change would require a schema change. Because of this, default is implemented purely in python and **choices are not validated but exist for metadata purposes only.**

**Comment by coleifer** [comment]
If you want to enforce a particular value that should be done using a CHECK constraint:

```python
status = CharField(constraints=[Check("status IN ('S', 'F', 'U')")])
```
