### ISSUE TITLE
Add update_or_create() helper method

### ISSUE THREAD

**Issue by willyhakim** [coleifer/peewee#1772]
get_or_create is amazing! Could we add some more super powers by implementing update_or_create()

**Comment by coleifer** [comment]
No. `get_or_create` is a hack and I don't advise anyone to use it under any circumstances. It's vulnerable to race-conditions and weird behavior. Just write the extra 2-3 lines of code and do it right. Wrap it up in a classmethod on the model it pertains to. You can thank me later.
