### ISSUE TITLE
text field type when using mysql/mariadb database

### ISSUE THREAD

**Issue by hegusung** [coleifer/peewee#1773]
Hi,

According to the documentation, TextField should use MySQL longtext column type but it uses the text column type. Is this the desired behavior and the documentation has not been changed? If so, how can I change my code to make sure it uses a longtext and not a text field type?

**Comment by coleifer** [comment]
Apologies -- the docs are incorrect. Peewee used "longtext" up until 3.x, at which point it changed to just plain old "text".

To have a longtext field:

```python
class LongTextField(TextField):
    field_type = 'LONGTEXT'
```

Then just use it as you would a regular `TextField`.
