### ISSUE TITLE
Change default charset in MySql's create table statements

### ISSUE THREAD

**Issue by ibraaaa** [coleifer/peewee#178]
For MySql, when I try to insert text encoded in utf8 into a table, the text is scrambled. The issue is that the default charset for tables is latin1, to fix this I need to ALTER a table after its creation to change the charset. Providing such option from inside peewee will be helpful.

**Comment by mahdikiani** [comment]
When the peewee create table it sets the charset as latin1_swedish_ci. so when data insert to table it scramble the data.
so it need a way to change column charset

**Comment by coleifer** [comment]
You can also:
```
db = MySQLDatabase(...)
db.execute_sql("SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;")
```

Beyond that I'm not familiar enough with MySQL to be able to advise you what parameters or settings to modify. Consult the docs or try stackoverflow if you are still stuck.
