### ISSUE TITLE
Documentation on advanced connection management

### ISSUE THREAD

**Issue by Exteris** [coleifer/peewee#1783]
Hi,

Thanks for this cool package. I've been trying to work with multiple processes, and find references here and there to http://docs.peewee-orm.com/en/latest/peewee/database.html#advanced-connection-management but can't seem to find this page anymore. Is this not supported anymore?

Thanks,
Daan

**Comment by coleifer** [comment]
That information is outdated and was likely removed when 3.0 was released... I don't see any references to that from within Peewee.

For multiprocess, just be sure not to connect until after the fork.
