### ISSUE TITLE
model_to_dict fails to process disabled backrefs 

### ISSUE THREAD

**Issue by adontz** [coleifer/peewee#1785]
If there is a model with disabled backref "ForeignKeyField(OtherModel, backref='+')" then model_to_dict fails to convert such model to dict, because model has no '+' attribute

    File ".../site-packages/playhouse/shortcuts.py", line 105, in model_to_dict
        descriptor = getattr(model_class, foreign_key.backref)
    AttributeError: type object 'MyModel' has no attribute '+'

https://github.com/coleifer/peewee/blob/cb6cc1d6bc224070b6deef81dc314fb44c7e8386/playhouse/shortcuts.py#L105
As far as I understand foreign_key.backref should be tested like this
https://github.com/coleifer/peewee/blob/cb6cc1d6bc224070b6deef81dc314fb44c7e8386/peewee.py#L4569

LINK: somehow related to https://github.com/coleifer/peewee/issues/1405

**Comment by coleifer** [comment]
Nice, thanks.

**Comment by adontz** [comment]
You response speed in incredible! Thank you!

Can you please clarify why you have "not in '!+'" in one place and "== '+'" in another place?
Are not backref='+' and backref='!' the same?

**Comment by coleifer** [comment]
Sorry for the lack of documentation on this... "!" is retained for backwards-compatibility but should not be used. At some point I will remove that and just use `== '+'`.
