### ISSUE TITLE
OperationalError when creating table with schema in SQLite

### ISSUE THREAD

**Issue by belidzs** [coleifer/peewee#1787]
I have the following model:

```python
db = Proxy()


class BaseModel(Model):
    class Meta:
        database = db
        schema = 'api'


class Koltseg(BaseModel):
    id = CharField(primary_key=True, max_length=8)
    kotesszam = CharField(max_length=10)
    fokonyv = CharField(max_length=50)
    kozbeszerzeses = BooleanField()
    afas = BooleanField()
    osszeg = DecimalField(max_digits=12, decimal_places=2)
```

Normally I use postgres, but during testing I instantiate an in-memory SQLite database and use that. However, when I call `create_tables` from the test fixture I receive an exception complaining there is no database with the name 'api'.

```python
@pytest.fixture
def app():
    db = SqliteDatabase(':memory:')
    db.bind(MODELS, bind_refs=False, bind_backrefs=False)
    db.connect()
    db.create_tables(MODELS)
    app = create_app(testing=True, test_db=db)
    app.config['TESTING'] = True

    yield app  

    db.drop_tables(MODELS)
    db.close()
```

And the output:

```
test setup failed
self = <peewee.SqliteDatabase object at 0x0000015CA7DDA9E8>
sql = 'CREATE TABLE IF NOT EXISTS "api"."koltseg" ("id" VARCHAR(8) NOT NULL PRIMARY KEY, "kotesszam" VARCHAR(10) NOT NULL, "...v" VARCHAR(50) NOT NULL, "kozbeszerzeses" INTEGER NOT NULL, "afas" INTEGER NOT NULL, "osszeg" DECIMAL(12, 2) NOT NULL)'
params = [], commit = True

    def execute_sql(self, sql, params=None, commit=SENTINEL):
        logger.debug((sql, params))
        if commit is SENTINEL:
            if self.in_transaction():
                commit = False
            elif self.commit_select:
                commit = True
            else:
                commit = not sql[:6].lower().startswith('select')
    
        with __exception_wrapper__:
            cursor = self.cursor(commit)
            try:
>               cursor.execute(sql, params or ())
E               sqlite3.OperationalError: unknown database "api"
```

I'm using peewee 3.7.1

**Comment by coleifer** [comment]
Schemas, in SQLite, refer to attached databases. Therefore, to use "schemas" in SQLite you will need to attach databases with the given names. This is an advanced usage and probably not what you want, so I recommend avoiding the use of schema with sqlite unless you know what you're doing.

**Comment by belidzs** [comment]
Thanks for the quick answer!

I'm really only using SQLite to simulate my production environment (postgres) as close as possible during testing. In my production database tables are scattered through several schema (however my flask app only uses one). 

If you say it's not possible to just replace the database driver and use it like that while testing I can live with that but I think it would be nice if the documentation would reflect this limitation.
