### ISSUE TITLE
[Request] Raise exception on missing parens for field type definitions

### ISSUE THREAD

**Issue by kpeters58** [coleifer/peewee#1788]
When one forgets to add parentheses to a field type definition. e.g.
 mtype  = IntegerField 
instead of 
 mtype  = IntegerField ()
and create_tables executes, tables from the models get built, but columns do not get created for fields w/o parentheses. Exceptions aren't raised either.

It would be nice, if peewee alerted the negligent programmer to his/her mistake(s).

**Comment by coleifer** [comment]
Going to pass.
