### ISSUE TITLE
How's graphene-peewee going?

### ISSUE THREAD

**Issue by yanghg-basefx** [coleifer/peewee#1790]
I see [this ticket](https://github.com/graphql-python/graphene/issues/289), and I want to use peewee with graphql, but I didn't find any other info. How's it going? Or I must switch to sqlalchemy to use graphene-sqlalchemy?

**Comment by coleifer** [comment]
I'm not pursuing it, nor am I in a position to recommend an alternative.

**Comment by Tarun-S** [comment]
I ported @insolite’s [graphene-peewee-async](https://github.com/insolite/graphene-peewee-async) to the regular Peewee. Check it out here:

[graphene-peewee](https://github.com/emperorplatform/graphene-peewee)

This is my first major OSS contribution, so please leave feedback if anything can be improved. Also, this is an early release with limited testing. It has not been used in production by me. There may well be bugs.
