### ISSUE TITLE
MySQL Error 1059(FK identifier name is too long) on migrator.add_column

### ISSUE THREAD

**Issue by Dushyant7** [coleifer/peewee#1797]
peewee==2.8.1

I am using MySQLMigrator to migrate my tables.

When I am creating new column using add_column which is ForeignKeyField.
It throws `peewee.InternalError (1059, Identifier name ... is too long)`.

The reason behind this is MySQL has limit of 64 characters for FK identifier and identifier name which is created by add_column is more than 64 characters (68 in my case using format "fk_%s_%s_refs_%s").
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

I am not sure if I can specify such identifier in ForeignKeyField or in add_column function.

Not sure about other, but specific to MySQL, FK identifier name is auto generated in case not specified. This can solve the issue.

There should be some tests for maximum length constraint on identifiers.

**Comment by coleifer** [comment]
Peewee contains code that correctly truncates long index names. I've added a new patch that truncates long foreign-key constraint names, which will be included in the next release.

You're using an ancient version, I suggest upgrading.

**Comment by NicolasCaous** [comment]
peewee==3.7.1

Is this still happening in the latest version?

> peewee.InternalError: (1059, "Identifier name 'fk_investment_installment_loan_installment_id_refs_loan_installment' is too long")

When using:

```
class LoanInstallment:
    pass

class InvestmentInstallment:
    loan_installment = DeferredForeignKey('LoanInstallment', backref='+')

InvestmentInstallment._schema.create_foreign_key(InvestmentInstallment.loan_installment)
```

Is there a workaround for this?
