### ISSUE TITLE
ManyToManyField and backref='+' fails

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#1805]
It seems that if you have a `ManyToManyField` that uses a through model in which the foreign keys are defined with `backref='+'` it fails when trying to access the many-to-many field because it still tries to access the backref. The error is

```python
~/.pyenv/versions/3.7.1/Python.framework/Versions/3.7/lib/python3.7/site-packages/peewee.py in __get__(self, instance, instance_type, force_query)
   4609     def __get__(self, instance, instance_type=None, force_query=False):
   4610         if instance is not None:
-> 4611             if not force_query and isinstance(getattr(instance, self.src_fk.backref), list):
   4612                 return [getattr(obj, self.dest_fk.name) for obj in getattr(instance, self.src_fk.backref)]
   4613             else:

AttributeError: 'Target' object has no attribute '+'
```

**Comment by coleifer** [comment]
From the [documentation](http://docs.peewee-orm.com/en/latest/peewee/relationships.html#manytomany):

> Peewee provides a field for representing many-to-many relationships, much like Django does. This feature was added due to many requests from users, but I strongly advocate against using it, since it conflates the idea of a field with a junction table and hidden joins. It’s just a nasty hack to provide convenient accessors.

Regarding the backref ... I'm not sure I completely understand, but it appears to me that disabling the backref on the ManyToManyField works correctly:

```python
class Student(Model):
    name = TextField()

class Course(Model):
    name = TextField()
    students = ManyToManyField(Student, backref='+')

CourseStudent = Course.students.get_through_model()

# ...
# It seems to work fine to use the `course.students` many-to-many accessor:
math = Course.create(name='math')
s = Student.create(name='s')
math.students.add(s)  # Works.
list(math.students)  # Works, returns [<Student: 1>]
```

And, as it would suggest, there is no backref on the `Student` model, e.g. there's no `student.courses` backref.

-------------------------

If you're talking about manually declaring a through-model with backrefs disabled on both sides...I have to ask: what are you even bothering with using `ManyToManyField` for?

I'm not saying there's not a bug in the code. I am, however, suggesting that you're making a foolish choice to try and use ManyToManyField for anything but the most trivial many-to-many implementations.
