### ISSUE TITLE
Different result with 'or' - '|'

### ISSUE THREAD

**Issue by BreX900** [coleifer/peewee#1810]
I'm not very good at English. I will show the error with two examples. The same examples should show the same result but it is not...

`#first example
f = (Product.asin_product=="NameOne")
f = f | (Product.asin_product=="NameTwo")
Product.select().where(f).execute()
#peewee - DEBUG - ('SELECT "t1"."asin_product" FROM "product" AS "t1" WHERE (("t1"."asin_product" = %s) OR ("t1"."asin_product" = %s))', ['NameOne', 'NameTwo'])

#Second example
s = (Product.asin_product == "NameOne")
s = s or (Product.asin_product == "NameTwo")
Product.select().where(s).execute()
#2018-12-12 10:46:28,754 - peewee - DEBUG - ('SELECT "t1"."asin_product" FROM "product" AS "t1" WHERE ("t1"."asin_product" = %s)', ['NameOne'])`

They should return the same query as a result, but it is not

**Comment by coleifer** [comment]
Read the docs:

http://docs.peewee-orm.com/en/latest/peewee/query_operators.html
