### ISSUE TITLE
primary_key=True not working

### ISSUE THREAD

**Issue by dyadav7** [coleifer/peewee#1822]
What is the issue with below Model ?

     class Tags(BaseModel):
        tag = CharField(primary_key=True)
        cmd = CharField()

I am unable to save to database. Run attached script to see the issue.
I am unable to find the issues by checking docs.

[peewe_issue.py.txt](https://github.com/coleifer/peewee/files/2719957/peewe_issue.py.txt)

I get the below output

    $ peewe_issue.py
    Show all entries: 0
    ret=0
    Traceback (most recent call last):
      File "/home/deepaky/bin/peewe_issue.py", line 37, in <module>
       main()
      File "/home/deepaky/bin/peewe_issue.py", line 32, in main
        assert(ret)
    AssertionError
    $
`

**Comment by coleifer** [comment]
It is clearly explained here:

http://docs.peewee-orm.com/en/latest/peewee/models.html#id4

You need to specify `force_insert=True` when saving with a non-integer primary key. Please read the docs.
