### ISSUE TITLE
Does Peewee supports mysql Date() function?

### ISSUE THREAD

**Issue by littledemon** [coleifer/peewee#1830]
I have below command :

```
SELECT Date(mydate),sum(price),username 
from shop_table 
where Date(mydate)>'2011-01-07' 
GROUP BY Date(mydate),username
```

Because the dates include the time, I convert them into 'only date' using Date() function, so regardless of hours I can understand the total amount of sales in one day.

But is there an ability in peewee using 'fn' to do this?

**Comment by coleifer** [comment]
```python
query = (ShopTable
    .select(
      fn.DATE(ShopTable.mydate).alias('date_value'), 
      fn.SUM(ShopTable.price).alias('price_sum'),
      ShopTable.username)
    .where(fn.DATE(ShopTable.mydate) > '2011-01-07')
    .group_by(fn.DATE(ShopTable.mydate), ShopTable.username))
```

**Comment by coleifer** [comment]
In the future please post questions like "how do I..." to StackOverflow. This is the issue tracker.
