### ISSUE TITLE
Feature Request: Restore `Query` __repr__/__str__ functionality

### ISSUE THREAD

**Issue by ibushong** [coleifer/peewee#1833]
In peewee v2 it was convenient when debugging to print out the raw sql of a query with just `print query`, but  in v3 this just gives the generic `<peewee.ModelSelect object at 0x10abce150>`. For now I've just added it to my base peewee model, leveraging `sql()`, but I think this might be a nice feature to add back in v3?

**Comment by coleifer** [comment]
That has been replaced by calling the `.sql()` method on a query.
