### ISSUE TITLE
Mariadb 10.3.3+ change on values() function  

### ISSUE THREAD

**Issue by altunyurt** [coleifer/peewee#1834]
This is more like a heads up! issue. 

https://mariadb.com/kb/en/library/values-value/ states that 
```
INSERT INTO t (a,b,c) VALUES (1,2,3),(4,5,6)
    ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);
```
should be written as 
```
INSERT INTO t (a,b,c) VALUES (1,2,3),(4,5,6)
    ON DUPLICATE KEY UPDATE c=VALUE(a)+VALUE(b); <== this has changed 
```
starting from 10.3.3. 

Apparently peewee will fail at "on duplicate ... update ... values" queries on mariadb 10.3.3+ 
Judging from https://github.com/coleifer/peewee/blob/55f515be7012fcf8e33fe7f0b2726b7a36b729c0/tests/sql.py#L1287

**Comment by coleifer** [comment]
Thanks for the heads-up. This looks like a pain.

* MySQL uses VALUES: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
* MariaDB's changes do not appear to be backwards-compatible: https://mariadb.com/kb/en/library/values-value/
