### ISSUE TITLE
Model.get() method fails silently

### ISSUE THREAD

**Issue by arel** [coleifer/peewee#1835]
I came across a behavior with [`Model.get`](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.get) I found confusing and could be improved or at least better documented.

Calling `Model.get()` is a shorthand for "selecting with a limit of 1", which is clear. When you provide it filters, such as `.get(id=1442)`, things work as expected too. What was unexpected to me was that if you forget to specify the filter parameter by name such as `.get(1442)` the query does *not* fail. Rather, it returns an arbitrary result as if `.get(True)` or simply `.get()` were given. In my case, this led to a subtle bug because the two results were coincidentally very similar. For instance:

```
In [15]: Image.get(id=1442)                                                                                                                        
Out[15]: <Image: 1442>

In [16]: Image.get(1442)                                                                                                                           
Out[16]: <Image: 1433>
```

Is this the intended / desired behavior for some reason I'm missing? Or, would it be possible to raise an exception whenever the query expression is not an instance of type [Expression](http://docs.peewee-orm.com/en/latest/peewee/api.html#Expression)?

P.S. thanks for your work on this library!

**Comment by coleifer** [comment]
This gets translated into:

```sql
select * from image where 1442
```

So the db interprets that, most likely, as simply `true` and returns the first row of this arbitrarily-large result set.

I'm aware of this issue, but not positive about the best way to fix it. Python is highly dynamic, and so is peewee. Adding validation to all SQL clauses (not just WHERE, which is in this example), seems prohibitively complicated.

Perhaps, though, the `.get()` method can be fixed up.

**Comment by coleifer** [comment]
I've chosen to resolve this by supporting .get() with a single integer parameter, treating it as `.get(primary-key == value)`. So in the common case where one just passes an int, it will work as expected.

**Comment by arel** [comment]
OK, thanks!
