### ISSUE TITLE
PooledPostgresqlExtDatabase is imported as None

### ISSUE THREAD

**Issue by LearnedVector** [coleifer/peewee#1837]
```python
from playhouse.pool import PooledPostgresqlExtDatabase
print(PooledPostgresqlDatabase)  # returns None
```

digging into the code it looks like there is an import error causing this. any idea why?

https://github.com/coleifer/peewee/blob/master/playhouse/pool.py#L282

**Comment by coleifer** [comment]
You need to install psycopg2.
