### ISSUE TITLE
Get timestamp from database as int

### ISSUE THREAD

**Issue by HonzsSedlomn** [coleifer/peewee#1845]
I have a column of type Timestamp (or DateTime). If I save it to database, it's saved as integer, but when I want to get it from the database, it's returned as datetime. Is there any way to get it as it is in the database (integer) ?

**Comment by coleifer** [comment]
So you should:

* Use `DateTimeField` if you want to work with `datetime` in python and store the data using the `datetime` data-type in your sql db.
* Use `TimestampField` if you want to work with `datetime` in python and store the data using an integer in your sql db.
* Use `IntegerField` if you want to work with timestamps as integers in python and store the data as an integer in your db.
