### ISSUE TITLE
Support for different blob types in mysql

### ISSUE THREAD

**Issue by MaxNoe** [coleifer/peewee#1847]
I would need to store some binary data larger then 65kb in a mysql database.

peewee only seems to support one `BlobField`, which maps to mysqls `blob` which is max 65kb.

How can I make sure, the table is created with a `MEDBLOB` or `LONGBLOB` datatype while also maintaining sqlite compatiblity for local testing?

**Comment by coleifer** [comment]
Just subclass and specify the data-storage class:

```python
class LongBlogField(BlobField):
    field_type = 'LONGBLOB'
```

**Comment by MaxNoe** [comment]
This is not compatible with using a proxy that can either be a sqlite or mysql, as sqlite has no longblob type, or am I mistaken?

**Comment by coleifer** [comment]
https://www.sqlite.org/datatype3.html

From 3.1.3:

> If the declared type for a column contains the string "BLOB" or if no type is specified then the column has affinity BLOB.
