### ISSUE TITLE
Add support for column name option in ForeignKeyField

### ISSUE THREAD

**Issue by ExiaSR** [coleifer/peewee#1850]
```py
class User(Model):
	user_id = IntegerField(primary_key=true)

class Tweet(Model):
	tweet_id = IntegerField(primary_key=true)
	reply_to = ForeignKeyField('self') # Reference to itself
```
Current behaviour of the above snippet will automatically change column name of `reply_to` to `reply_to_id`. AFAIK `ForeignKeyField` class does not expose `column_name` parameter like `Field` class does.

It will be great if we can parametrize `column_name` for all `Field` class.

Here is what I have in mind.

```py
class Tweet(Model):
	tweet_id = IntegerField(primary_key=true)
	reply_to = ForeignKeyField('self', column_name='reply_to')
```

**Comment by coleifer** [comment]
ForeignKeyField *does* support `column_name`. What are you talking about?
