### ISSUE TITLE
Field class doesn't have an `index_type` attribute

### ISSUE THREAD

**Issue by ananis25** [coleifer/peewee#1851]
The ModelIndex class looks for the index_type argument in the definition of a Field when creating an index for it, but it is not defined as an attribute for the Field class.

```
class ModelIndex(Index):
    def __init__(self, model, fields, unique=False, safe=True, where=None,
                 using=None, name=None):
        self._model = model
        if name is None:
            name = self._generate_name_from_fields(model, fields)
        if using is None:
            for field in fields:
                if isinstance(field, Field) and hasattr(field, 'index_type'):
                    using = field.index_type
```

Might it be an oversight? If available, creating indices of type other than the default (B-tree) for fields would be really simple. 

```
class Table(Model):
    columnA = DateTimeField(index_type = 'BRIN')
```

Also, thank you for the great library :)

**Comment by coleifer** [comment]
This is only used internally by some special fields in the `playhouse.postgres_ext` module. However you *can* specify a custom index type via the `using=` parameter of `ModelIndex`:

```python
class Table(Model):
    timestamp = DateTimeField()

Table.add_index(Table.index('timestamp', using='BRIN'))
```

**Comment by coleifer** [comment]
I *do* think this is a legit suggestion that it should be applicable to all field types... I'm going to look at expanding the scope of the `index_type` bit to maybe apply across all fields.

**Comment by coleifer** [comment]
Fixed -- now it is possible to write:

```python
column_a = DateTimeField(index=True, index_type='BRIN')
```

**Comment by ananis25** [comment]
Thank you! The commit diff shows it was clearly more involved that it looks. 

The `add_index` method was also doable but for my use-case, I needed to redefine the Model class every time I used it. Another hack that worked was:

```
class Table(Model):
    columnA = DateTimeField(index = True)
    columnA.index_type = 'BRIN'

    class Meta:...

```
