### ISSUE TITLE
v3 multiple databases support

### ISSUE THREAD

**Issue by tyfncn** [coleifer/peewee#1853]
First thank you for such a great software. I've been using it for almost 3 years now. My issue is missing "Using()" context manager. It was very useful while backing up to a new sqlite database of same models.  It seems it is deprecated in v3. Is there any replacement for this?
Old docs was here: http://docs.peewee-orm.com/en/2.10.2/peewee/database.html#using-multiple-databases

My use case is somewhat like this:
```python
new_db = SqliteDatabase("backup_2019.db")
data_list = []
for rec in Record.select():
	data_list.append({"name": rec.name, "desc": rec.desc})

with Using(new_db, [Record]):
	for rec in data_list:
		Record.create(**data)
```
Would like to update to latest version but this particular use case holds me back. Any help would be greatly appreciated

**Comment by coleifer** [comment]
Yes, you can use `database.bind_ctx()`, or `Model.bind_ctx()`:

* http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.bind_ctx
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.bind_ctx
