### ISSUE TITLE
Bulk Upsert

### ISSUE THREAD

**Issue by takehaya** [coleifer/peewee#1855]
hi. I want to use update and preserve with bulk upsert.

I would like to run the following code. How should I do?
```
Book.insert_many(books).on_conflict(preserve=[Book.disposal], update=books).execute()
```

**Comment by coleifer** [comment]
Questions like this belong on StackOverflow.

The documentation in peewee:

* http://docs.peewee-orm.com/en/latest/peewee/querying.html#upsert
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Insert.on_conflict

Consult the manual for the SQL database you are using to get a better idea of how to write such a query.

**Comment by takehaya** [comment]
sorry.I looked at StackOverflow and read the document, but there was no example.

List can not be taken with" on_conflict (update = books) "
How to pass "list" to "on_conflict(update=*)"?

**Comment by coleifer** [comment]
I'm suggesting that you don't understand how insert with "on conflict" clause works. And that you should familiarize yourself with the way it is used.
