### ISSUE TITLE
Passing single model to bind_ctx causes uninitialized Proxy error

### ISSUE THREAD

**Issue by MushuEE** [coleifer/peewee#1856]
I was trying to make a fixture to do some unit testing for my Peewee methods when I hit this issue:
```
@pytest.fixture()
def test_db():
    """Test to check db."""
    _db = SqliteDatabase(":memory:")
    dbs = (Testbed)
    with _db.bind_ctx(dbs):
        _db.create_tables(dbs)
        yield _db
        _db.drop_tables(dbs)
```
Will trigger
```
    @pytest.fixture()
    def test_db():
        """Test to check db."""
        _db = SqliteDatabase(":memory:")
        dbs = (Testbed)
>       with _db.bind_ctx(dbs):

    def __getattr__(self, attr):
        if self.obj is None:
>           raise AttributeError('Cannot use uninitialized Proxy.')
E           AttributeError: Cannot use uninitialized Proxy.
```
That sent me down a bit of a rabbit hole. 
The issue ended up being that I needed `[Testbed]`, in other fixtures I had `(Model1, Model2, Model3)` which is happy because it is iterable. If there is a way to pass a single model or add a catch, I think it might be helpful. Thanks

**Comment by coleifer** [comment]
`(Testbed)` is not a tuple.

`(Testbed,)` is a tuple.

This is your problem.

**Comment by MushuEE** [comment]
Yes, I mentioned that, I opened because the Error message received was misleading. Hopefully others might find this helpful if they hit the same issue, thanks.
