### ISSUE TITLE
Isssue with varchar fiels in postgres

### ISSUE THREAD

**Issue by dorel14** [coleifer/peewee#1859]
Hello
I change my database from sqlite to postgres and varchar column are converted in array fields so all the new text i insert are embraced with brackets 
How can i deactivate this ?

THX

**Comment by coleifer** [comment]
That doesn't make any sense to me. Peewee doesn't automatically convert anything to ArrayField. People use their model classes with both SQLite and Postgres (ie Sqlite for tests, Postgres for production), and I've never heard of such an issue.

If you can provide instructions on how to reproduce this, I'll take a look. But you have not given me any information that I can use...other than you seem to be confused.

**Comment by dorel14** [comment]
ok faullt of my code  excuse me 
i discover peewee and it's not very simple
