### ISSUE TITLE
PostgreSQL support for on_conflict with partial indexes

### ISSUE THREAD

**Issue by iamyohann** [coleifer/peewee#1860]
I'm attempting to upsert multiple records into a PostgreSQL table containing a partial index.

The insert statement looks something like this in plain SQL

```
INSERT INTO abc (a, b, c, value1, value2) VALUES (1, 1, null, '0.2'::numeric, '0.02'::numeric)
ON CONFLICT (b, c) where a is null
DO UPDATE
SET value1 = '0.555'::numeric, value2 = '0.555'::numeric;
```
The table `abc` has a partial unique index on `(b, c) where a is null`.

However `OnConflict` does not appear to support PostgreSQL `index_predicate` as specified in the above query (`ON CONFLICT (b,c) where a is null`).

There is a `where` in `OnConflict` but that seems to be for the `conflict_action` section, not for the `conflict_target` section as specified here https://www.postgresql.org/docs/10/sql-insert.html

This results in a error being raised
```
peewee.ProgrammingError: there is no unique or exclusion constraint matching the ON CONFLICT specification
``` 

Is it possible to add support for `index_predicate` with `OnConflict` or am I missing something here?

----------------------------------------
Peewee version = `3.8.2`
PostgreSQL version = `PostgreSQL 10.5 on x86_64-apple-darwin18.0.0, compiled by Apple LLVM version 10.0.0 (clang-1000.10.43.1), 64-bit`
Python version = `3.6.x`

**Comment by coleifer** [comment]
Yes you're right, I didn't think about partial indexes when designing the API. To fix this, I've added a new parameter, `conflict_where`, which should take the expression(s) that comprise the WHERE clause of the partial index.

**Comment by iamyohann** [comment]
That was quick! Cheers

**Comment by pranavsreedhar92** [comment]
Is there a way to ignore duplicates that contains partial index with multiple conditions. 
Postgres Version: psql (10.17 (Ubuntu 10.17-1.pgdg20.04+1))

**Partial Index** 
` "participant_event_id_user_id_unique" UNIQUE, btree (event_id, user_id) WHERE deleted = false AND event_id IS NOT NULL AND role <> 'test-admin'::text`.

**Query**
`insert into participant (role, user_id, created_by, event_id) VALUES ('proctor', 21937, 'com.talview.27585f36-4b68-4bbf-b41f-20a6c4a37d83', 2463) on conflict(user_id, event_id) where ("role" != 'test-admin') DO Nothing;`

**Error**
ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification

**Comment by coleifer** [comment]
For it to match the partial index it must contain the same where clause conditions, as I understand it.
