### ISSUE TITLE
Update multiple rows by id

### ISSUE THREAD

**Issue by gurland** [coleifer/peewee#1865]
I have list of dicts `[{"pk": 1, "value": 12}, ...]`, how could I update all rows by their `id`? 

Only way I found is:
```
m = MyModel.get(id=pk)
m.value = value
m.save()
```

But that is very slow

**Comment by coleifer** [comment]
If you're using Postgres or a recent-ish sqlite, you can try to use the `ValuesList` with a common table expression in an UPDATE query. Postgres also supports UPDATE FROM which could also work. You can see an example here, as I've added a testcase: c1b6e5f8c5a2b6799f24b2df8788f43a0ba8811d
