### ISSUE TITLE
CentOS 6 support

### ISSUE THREAD

**Issue by goooroooX** [coleifer/peewee#1867]
Hi,

It seems peewee module is lack of CentOS 6 support. I have tried it in docker container and normal CentOS 6.8/6.9 installation, and in all cases I have the same exception (Python 2.6/2.7, x86/x64):

`  File "/app/base.py", line 233, in feed
    LogSourceModel.insert_many(batch).execute()
  File "/app/libs/peewee.py", line 1625, in inner
    return method(self, database, *args, **kwargs)
  File "/app/libs/peewee.py", line 1696, in execute
    return self._execute(database)
  File "/app/libs/peewee.py", line 2358, in _execute
    return super(Insert, self)._execute(database)
  File "/app/libs/peewee.py", line 2121, in _execute
    cursor = database.execute(self)
  File "/app/libs/peewee.py", line 2727, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/libs/peewee.py", line 2721, in execute_sql
    self.commit()
  File "/app/libs/peewee.py", line 2512, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/app/libs/peewee.py", line 2714, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: near ",": syntax error`

CentOS 7 is OK.
I've executed in-build tests, results are attached - they also contains the same exceptions.
[peewee_test_results.txt](https://github.com/coleifer/peewee/files/2894498/peewee_test_results.txt)

Can you please comment on this? Is there any easy way to make in work on CentOS 6?
Thank you!

**Comment by coleifer** [comment]
Those test failures are likely due to your using an absolutely ancient version of sqlite. This ancient version of sqlite does not seem to support bulk insert. That is the problem. Upgrade sqlite to a newer version.
