### ISSUE TITLE
Unexpected LIKE operations

### ISSUE THREAD

**Issue by dmwyatt** [coleifer/peewee#187]
The following LIKE query gets me nothing:

```
In [22]: movies =models.Movie.select().where(models.Movie.name % '%I%')         

In [23]: for m in movies:
   ....:     print m
   ....:     
```

Using ILIKE works:

```
In [26]: movies =models.Movie.select().where(models.Movie.name ** '%i%')        

In [27]: for m in movies:                                               
    print m
   ....:     
<Movie: 'Iron Man'>
<Movie: 'Wreck-It Ralph'>
```

Using the command line sqlite3 tool:

```
sqlite> SELECT * FROM movie WHERE name LIKE '%I%';                              
1|Iron Man
2|Wreck-It Ralph
sqlite> 
```

This is more likely my idiocy than a bug in peewee, but I can't see where I'm going wrong.  

I just pip installed peewee a couple hours ago, so I'm using whatever version is most recent.

**Comment by benhoyt** [comment]
This behavior got me too (before I looked at the output, noticed it was using GLOB with SQLite, then saw the note in the docs). It seems quite surprising, and would mean if you change your code to use `field % 'whatever*'` to work with SQLite, then if you switch to PostgreSQL it'll break.

I think it'd be more cross-database compatible and less surprising if the `%` operator on SQLite changed the `%`'s in your match string to `*` as well as using `GLOB`, so you didn't have to worry about which database you were on. Thoughts?
