### ISSUE TITLE
  _in_use size exceed Maximum connections despite calling db.close_idle(),  db.manual_close() or  db.close_stale(60)

### ISSUE THREAD

**Issue by ernest-andela** [coleifer/peewee#1870]
Calling the manual_close() method always return False because of this line in the code https://github.com/coleifer/peewee/blob/master/playhouse/pool.py#L194 . Where can l find the method is_closed() on this line https://github.com/coleifer/peewee/blob/master/playhouse/pool.py#L194? 

**Below is my initials for the creation of the connection**
```db = PooledPostgresqlDatabase(max_connections=30, timeout=300, stale_timeout=1, **db_args)```

**However l am having the following issues**
1. db.is_closed() is always True
2. self.self._in_use quickly gets to 30 causing Maximum Connection error

**Calling any of the following does not help:**
1. db.close_idle()
2. db.manual_close()
3. db.close_stale(60)

I am connecting to the database: **before_request** and closing the database **teardown_request**

**Comment by coleifer** [comment]
`is_closed` is implemented on `peewee.Database` in `peewee.py`. What it does is check whether there is a connection already open (for the current thread, if you're using multiple threads).

The logic of `manual_close` could be described in this way:

1. does the current thread have a connection open? If not, there's nothing to do - return `False`
2. get a reference to the currently-open connection
3. remove the connection from the list of connections currently-in-use by the pool
4. call the `Database.close()` method, which resets the connection state and internally calls `._close()`, which is overridden by the pool subclass.
5. (inside `_close()`) this is overridden by the pool subclass to recycle the conn, which will not happen as the conn is no longer marked as being in-use
6. call `_close()` again, this time with a flag indicating that yes -- we really want to close the connection -- at which point it will be closed.

The symptoms you are describing do not make a lot of sense to me... Are you using a multi-threaded application? If so, then `is_closed()` is with respect to the current thread, and maybe you're calling it from a different thread.

Something is definitely weird in your app or your setup. For instance, I use the peewee pooled database on a handful of flask apps and it is quite well-behaved -- doesn't leak conns, etc. Your stale timeout of 1 second seems odd, but shouldn't be causing the issue.

You can always turn on logging:

```python
import logging
logger = logging.getLogger('peewee.pool')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
```

Also note the pool is unit-tested.

If you can post some more information indicating this is a bug, or a minimal script that reproduces the issue, I will gladly reopen the issue.
