### ISSUE TITLE
auto field for postgres but not primary key

### ISSUE THREAD

**Issue by ra-esmith** [coleifer/peewee#1882]
Good Morning,

How would I, using the current version of peewee.
Define a field on my table which is an integer, serially increases in value, and is not a primary key field.  Auto Field gets the serial, but always looks to be primary.  I have some old code which already has a primary key, but it the primary key is not serial and I wish to chunk some operations based this new serial field.

Thanks,
Evan

**Comment by ra-esmith** [comment]
I am going to try

from playhouse.signals import Model, pre_save

class MyModel(Model):
    data = IntegerField()

@pre_save(sender=MyModel)
def on_save_handler(model_class, instance, created):
    # find max value of temp_id in model
    # increment it by one and assign it to model instance object
    next_value = MyModel.select(fn.Max(MyModel.temp_id))[0].temp_id +1
    instance.temp_id = next_value

which seems likely to work ... though rather involved perhaps ...

**Comment by coleifer** [comment]
You use sequences for that.

```python
my_field = IntegerField(sequence='my_field_seq')
```
