### ISSUE TITLE
Binding to EXCLUDED in upsert WHERE expression

### ISSUE THREAD

**Issue by brandond** [coleifer/peewee#1884]
For languages with upsert support, the row that would have been inserted if not for the conflict can be addressed in SQL as 'excluded':

```Column names in the expressions of a DO UPDATE refer to the original unchanged value of the column, before the attempted INSERT. To use the value that would have been inserted had the constraint not failed, add the special "excluded." table qualifier to the column name. ```

How do I bind to this in the on_conflict statement? I would expect to be able to do something like this, but I can't figure out where to import EXCLUDED from.
```python
             .on_conflict(conflict_target=[Host.ip_address],
                          preserve=[Host.instance_id, Host.account_id, Host.tags],
                          where=(EXCLUDED.state != 'terminated'))
```

**Comment by brandond** [comment]
Seems like I can do this, but I'm not sure if this is correct or not:

```python
EXCLUDED = Entity('EXCLUDED') 
```

**Comment by coleifer** [comment]
I mistakenly thought that `EXCLUDED` only applied to the SET part...didn't realize it could also be used in the `WHERE` portion. Thanks, I will put together a fix.

**Comment by coleifer** [comment]
Fixed. Docs along with examples are now online: http://docs.peewee-orm.com/en/latest/peewee/api.html#EXCLUDED

It is exported if you use `from peewee import *`, or you can use `from peewee import EXCLUDED`.
