### ISSUE TITLE
Can you elaborate more on why AutoField doesn't add 'AUTOINCREMENT' to the column definition in SQLite?

### ISSUE THREAD

**Issue by dougthor42** [coleifer/peewee#1897]
Let me preface by saying that I was originally going to ask if this was intended behavior, but I did *at least some* research 😆.

I'm well aware of how SQLite handles `INTEGER PRIMARY KEY` (alias for the int64 `ROWID`) and how adding `AUTOINCREMENT` modifies that. https://www.sqlite.org/autoinc.html which you and others have linked many times before.

In [#805](https://github.com/coleifer/peewee/issues/805#issuecomment-168504439) you say:

> SQLite and autoincrement is more involved than you might think. There's a reason peewee doesn't specify AUTOINCREMENT with SQLite ... Peewee instead will use the unique rowid which uses the algorithm MAX(rowid) + 1 to generate new rowids, rather than ensuring they are unique across deletions, etc.

In [#147](https://github.com/coleifer/peewee/issues/147#issuecomment-12056456):

> Because SQLite incurs additional overhead to guarantee monotonically incrementing PKs, I will keep the default behavior which simply guarantees they are unique.

Questions:
+ Is this still true in peewee version 3.8 and above?
+ If so, can you expand on the reasoning for that?
+ Is there a way to force `AUTOINCREMENT` to be added, cpu/memory/disk overhead be damned?
    + In #147 you tell someone to use the `fields` arg of `SqliteDatabase`, but that doesn't work (`TypeError: 'fields' is an invalid keyword argument for this function`)
    + I haven't found anything in the docs ([sqlite extensions](http://docs.peewee-orm.com/en/latest/peewee/sqlite_ext.html#sqlite-ext), [primary keys](http://docs.peewee-orm.com/en/latest/peewee/models.html#primary-keys-composite-keys-and-other-tricks)) that mentions it. Perhaps I'm just blind?

**Comment by coleifer** [comment]
You can use this, from the sqlite extension: http://docs.peewee-orm.com/en/latest/peewee/sqlite_ext.html#AutoIncrementField

The info in #147 is for a very old version.
