### ISSUE TITLE
Add truncate_table back into v3

### ISSUE THREAD

**Issue by mildmelon** [coleifer/peewee#1907]
I would love to see this functionality in v3 as it was available in v2. It doesn't make sense to omit this simple and very useful function. I would prefer to truncate over drop tables when I don't need a table structure change.

I saw your previous comments on a [related issue](https://github.com/coleifer/peewee/issues/1345) but I feel that this still holds value and should be added back into v3.

Is there any specific reason that this shouldn't be added? I can volunteer to port the functionality from v2 -> v3 with documentation and unit tests. Let me know if this is something you're interested in, thanks!

**Comment by coleifer** [comment]
Fixed.

**Comment by mildmelon** [comment]
Thank you so much!
