### ISSUE TITLE
peewee update thrown exception 'UnknownField' object has no attribute 'get_sort_key'

### ISSUE THREAD

**Issue by angerpeanut** [coleifer/peewee#1916]
code:

```
query = Order.update(is_review=1, review_time=review_time).where(Order.order_sn == order_sn)
query.execute()
```
exception:
```
cursor = database.execute(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\peewee.py", line 2952, in execute
    sql, params = ctx.sql(query).query()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\peewee.py", line 2363, in __sql__
    for k, v in sorted(self._update.items(), key=ctx.column_sort_key):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\peewee.py", line 555, in column_sort_key
    return item[0].get_sort_key(self)
AttributeError: 'UnknownField' object has no attribute 'get_sort_key'
```

environment：
peewee version:3.9.5
python:3.7

**Comment by coleifer** [comment]
You are clearly using models generated using the `pwiz` tool. If pwiz cannot determine the right field type to use for a column, it uses a placeholder "UnknownField". You will need to edit your model definitions and replace the UnknownField with an appropriate field type (e.g. TextField, IntegerField, whatever) if you wish to be able to use it in queries.

**Comment by angerpeanut** [comment]
> You are clearly using models generated using the `pwiz` tool. If pwiz cannot determine the right field type to use for a column, it uses a placeholder "UnknownField". You will need to edit your model definitions and replace the UnknownField with an appropriate field type (e.g. TextField, IntegerField, whatever) if you wish to be able to use it in queries.

Thanks.
Due to pwiz generate mysql bit field to UnKnownField.
