### ISSUE TITLE
Documentation: playhouse.reflection module does not contain generate_models

### ISSUE THREAD

**Issue by erezmarmor** [coleifer/peewee#1917]
**peewee version=3.6.4**
both these pages (there might be more, hadn't checked):
- http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#reflection
- http://docs.peewee-orm.com/en/latest/peewee/interactive.html#interactive

the documentation provides this import as an example:
`from playhouse.reflection import generate_models`

however this function is in fact a method of Introspector class (i.e. not available from the module scope).

the proper statement might look like:
```
from playhouse.reflection import Introspector
db = PostgresqlDatabase('my_app')
models = Introspector.from_database(db).generate_models()
```

**Comment by coleifer** [comment]
False.

```python
In [1]: from playhouse.reflection import generate_models

In [2]: from peewee import PostgresqlDatabase

In [3]: db = PostgresqlDatabase('my_app')

In [4]: models = generate_models(db)  # models is now a dict of table name -> model class.
```

**Comment by coleifer** [comment]
![s1556631726 02](https://user-images.githubusercontent.com/119974/56965970-df8b8180-6b23-11e9-8640-a12b2d1266de.png)

**Comment by erezmarmor** [comment]
![image](https://user-images.githubusercontent.com/16885498/57012343-a7ad3880-6c0e-11e9-8356-7587bd0cd580.png)
@coleifer , are there known compatibility issues with python3?

**Comment by coleifer** [comment]
No, sorry I didn't see you had an older version. The generate_models helper was added here:

https://github.com/coleifer/peewee/commit/23dad105456bf4034d3ee21c6d29e56a7e2b9c7a
