### ISSUE TITLE
Get initial value of dirty fields.

### ISSUE THREAD

**Issue by lalit-lintel** [coleifer/peewee#1932]
Peewee has a feature that manages dirty fields. 
It managing the list of fields name, which is changed, but not the old/initial value of those fields.

It is great if peewee also manages the old/initial value of fields when it gets changed.

There anything is available which can help to get the inital value of fields?

**Comment by coleifer** [comment]
> It is great if peewee also manages the old/initial value of fields when it gets changed.
>
> There anything is available which can help to get the inital value of fields?

You need to manage this yourself, unfortunately.

Peewee has very simplistic tracking for when fields are assigned, but this was only designed to simplify the use-case of when you have a lot of columns but only need to save a subset of them.

If you need to find original values, you can always query the DB for the current state of the row data.

Another option would be to mess around with overriding `Model.__init__` to add extra logic for saving the initial data the model is instantiated with.

**Comment by coleifer** [comment]
```python
class MyModel(Model):
    field1 = TextField()
    ... etc ...

    def __init__(self, **kwargs):
        super(MyModel, self).__init__(**kwargs)
        self._initial_data = self.__data__.copy()
```

**Comment by lalit-lintel** [comment]
> ```python
> class MyModel(Model):
>     field1 = TextField()
>     ... etc ...
> 
>     def __init__(self, **kwargs):
>         super(MyModel, self).__init__(**kwargs)
>         self._initial_data = self.__data__.copy()
> ```

Thanks for this hint, I got the expected result with this.
