### ISSUE TITLE
Rawquery with table name doesn't work?!

### ISSUE THREAD

**Issue by aaveidt** [coleifer/peewee#1934]
Mysql 5.7
Peewee 3.9.5
-

I use this code
`db.execute_sql("select count(*) from %s", ('_admin_group',))`

and got this
`peewee.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''_admin_group'' at line 1")`

but this one works

`db.execute_sql("select * from _admin_group where id=%s", (1,))`

Is there any problem while working with table name?

**Comment by coleifer** [comment]
You can't put the table-name in as a parameterized query with your MySQL driver. Simple as that. For instance, with SQLite, this comes up in other places, too -- like if you're creating an INDEX on an expression, you can't use parameter placeholders for the expression values.
