### ISSUE TITLE
python 3.6.8  DateTimeField formats 无效

### ISSUE THREAD

**Issue by itmeryn** [coleifer/peewee#1936]
![image](https://user-images.githubusercontent.com/18156931/58228949-d8424700-7d62-11e9-9da3-52b2f3186a78.png)
![image](https://user-images.githubusercontent.com/18156931/58229447-594e0e00-7d64-11e9-8333-1846d7f37ea0.png)
![image](https://user-images.githubusercontent.com/18156931/58229453-5d7a2b80-7d64-11e9-83db-02ae52daee7c.png)

**Comment by coleifer** [comment]
Is there a question? Under certain conditions and depending on your database driver, the date/time may be returned from the database cursor as a string. Similarly if you're loading csv or json into your date/time-field, it may be a string.

**Comment by itmeryn** [comment]
按照截图的逻辑 就会直接返回value  字段中配置的format 并没有生效

**Comment by coleifer** [comment]
English. Still not a clue what this issue is about.

**Comment by itmeryn** [comment]
According to the logic of the screenshot, the format directly returned in the value field does not take effect.
