### ISSUE TITLE
Syntax for using json_each in subquery

### ISSUE THREAD

**Issue by brandond** [coleifer/peewee#1937]
I'm trying to do something like this:

```sql
DELETE FROM tweet WHERE tweet.user_id IN (SELECT value FROM json_each('[1,2,3]'))
```

I have tried something like this, but it ends up selecting the literal string 'value' instead of the value column:

```python
inactive_users = peewee.Select(from_list=[peewee.fn.json_each('[1,2,3]')], columns=['value'])
dq = (Tweet
      .delete()
      .where(Tweet.user.in_(inactive_users)))
dq.execute()
```

In reality the JSON list is actually sourced from another query that's using the `json_group_array` aggregation to output a lengthy list of IDs that I am doing some post-processing on. If I simply pass the Python list in directly, it binds a host parameter for each list entry, which ends up overrunning the sqlite SQLITE_MAX_VARIABLE_NUMBER limit if the list is large; I'm trying to work around this by serializing the list back to a JSON string and then using the table-valued `json_each` function in a subquery to split it back out.

**Comment by brandond** [comment]
Hmm, I think I found something that works. I'd appreciate knowing if there's a less hacky way to do this though:

``python
tve = peewee.fn.json_each('[1,2,3]').alias('tve')
inactive_users = peewee.Select(from_list=[tve], columns=[tve.c.value])
dq = (Tweet
      .delete()
      .where(Tweet.user.in_(inactive_users)))
dq.execute()

```

**Comment by brandond** [comment]
I guess the proper way to do this would be to have json_each registered as a TableFunction, but right now we only get to use it through the `children()` wrapper, unless I'm missing something.

**Comment by coleifer** [comment]
Whoa, whoa... Slow down!

```python

id_list = [1, 2, 3]
id_json = json.dumps(id_list)

subq = Select(from_list=fn.json_each(id_json), columns=[Entity('value')])
query = Tweet.delete().where(Tweet.id.in_(subq))
```

This works fine for me.

**Comment by coleifer** [comment]
I think the crux of the problem is that your "column" is being treated as a sql parameter rather than a column name. Hence I use `columns=[Entity('value')]` to indicate this is a name.

**Comment by brandond** [comment]
Thanks - that'll work! I couldn't figure out how to get it to recognize 'value' as a column name without binding it to something.

**Comment by brandond** [comment]
@coleifer - when I try this with you example I get the following error:
`TypeError: object of type 'Function' has no len()`

I think it should be:
```python
subq = Select(from_list=[fn.json_each(id_json)], columns=[Entity('value')])
```

**Comment by coleifer** [comment]
Oh right, yep.
