### ISSUE TITLE
Handle missing record for ForeignKeyField

### ISSUE THREAD

**Issue by aaveidt** [coleifer/peewee#1938]
`edited_by_user = ForeignKeyField(User, null=True)`

After the record has been deleted but still has reference from other table, i'll get `*DoesNotExist: instance matching query does not exist error if i access to record.edited_by_user`

How do i get rid of it like the record is null then return None like `get_or_none`?

This case can be annoying to None object model in template.

It's impossible to use `try/except` in template? Then i have to write another method to check if the field is getable or not

```
def get_edited_by_user()
    try/except ....
```

Then assign it to the template.
That's so annoying. It should be another argument to determine return None for empty/missing ForeignKeyField

**Comment by coleifer** [comment]
> After the record has been deleted but still has reference from other table, i'll get *DoesNotExist: instance matching query does not exist error if i access to record.edited_by_user

What do you mean, you have orphaned `User` instances? e.g., the `edited_by_user` column contains a user id for which no corresponding user row exists?

If this is the case, then google "referential integrity". Your database should be enforcing these kinds of constraints, updating orphaned foreign-keys to NULL is supported by many databases. Peewee implements this as well via the `delete_instance(recursive=True, delete_nullable=False)`.
