### ISSUE TITLE
Pandas DataFrame as peewee backend

### ISSUE THREAD

**Issue by isthisthat** [coleifer/peewee#1943]
Hi @coleifer, for some reason sqlite writes and reads are painfully slow (10x slower) on my system through the python interface. System commands to sqlite are fast as expected. I've been experimenting replacing the sqlite back-end with a pandas DataFrame. I had some success using peewee Model select `.sql()` and then `pandasql.sqldf(sql)` to query a DataFrame. However that still loads data to an sqlite db behind the scenes so was taking up twice the memory. Is a pandas DataFrame something you might consider supporting as a back-end natively? I guess the missing link is a translation from sql to pandas query syntax as outlined [here](https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sql.html). Thanks!

**Comment by coleifer** [comment]
> sqlite writes and reads are painfully slow (10x slower) on my system through the python interface

What driver are you using?

How are you executing these queries?

Compared to what? C? The sqlite3 shell?

> Is a pandas DataFrame something you might consider supporting as a back-end natively?

Sorry, definitely not.

**Comment by isthisthat** [comment]
> What driver are you using?

I've tried `SqliteDatabase`, `SqliteExtDatabase` and `APSWDatabase` with all the `PRAGMA` tips and tricks I could find.

> How are you executing these queries?

Using e.g. list(Model.select(...).where(...).dicts())

> Compared to what?

The sqlite3 shell
