### ISSUE TITLE
Add support (or docs) for how to create jsonb indexes for Postgres

### ISSUE THREAD

**Issue by jboothatgranular** [coleifer/peewee#1945]
I'm trying to create a gin index on a postgres jsonb column.

```
=> \d layer
                               Table "public.layer"
         Column          |          Type          | Collation | Nullable | Default 
-------------------------+------------------------+-----------+----------+---------
 data                    | jsonb                  |           | not null | 
...
```

I can do in psql via `CREATE INDEX idx_data_foo ON layer USING gin ((data->'foo'));`

I can't seem to get it to go with the migrations support in playhouse. I have passing the whole `(data->'foo')` as a string, but it complains that isn't a column name. I've tried passing the column/JsonLookup `Layer.data["foo"]` but that isn't a string.

Is there a simple way this is expected to work that I'm missing? Needs documented? Needs implemented? Pointers if its needs implemented? Should I be doing the query a different way? (I'm trying to accelerate a `WHERE data->'foo'::text ?| '{a,b,c}'::text[]` type query)

**Comment by coleifer** [comment]
Don't be a hero:

```python
db.execute_sql("create index idx_data_foo ON layer USING gin (data->'foo');")
```
