### ISSUE TITLE
Strange Operational Error

### ISSUE THREAD

**Issue by BOBONA** [coleifer/peewee#1951]
```
model_class = MyModel
model_class.create(
      **stuff
)
```

Try this code^
This doesn't work and I get an error that says that 'mymodel' is not a table.
Is this a glitch or is it intended? I can't figure out how to fix it by myself.

Is the solution to only use lowercase names? :)

**Comment by BOBONA** [comment]
Nevermind, I just realized that uppercase table names are generally an issue.

**Comment by coleifer** [comment]
You have complete control over the model class name and/or the table name (same w/fields and columns).

http://docs.peewee-orm.com/en/latest/peewee/models.html#table-names
