### ISSUE TITLE
Implement full-text search in mysql?

### ISSUE THREAD

**Issue by aaveidt** [coleifer/peewee#1955]
It wasn't mentioned on the doc. Only issue #532 
You link to user-defined function but i have no idea how to use it to implement full-text search.
There's no doc on `Expression`
I've tried with this, but how am i supposed to set MATCH around `lhs`?
```
def fulltext(lhs, rhs):
    return Expression(lhs, 'AGAINST', rhs, True)
```

I have to use raw query like this instead
`q = q.select().where(SQL("MATCH (title) AGAINST(%s)", ("test",)))`

have no idea why i have to use `("test",)`, if i input `"test"`:
`q = q.select().where(SQL("MATCH (title) AGAINST(%s)", "test"))`

i'll get `TypeError: not all arguments converted during string formatting`

**Comment by coleifer** [comment]
Here is the doc: http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#adding-user-defined-operators

Just write a wrapper.

```python
def Match(columns, expr, modifier=None):
    match = fn.MATCH(*columns)  # MATCH(col0, col1, ...)
    args = expr if modifier is None else NodeList((expr, SQL(modifier)))  
    return NodeList((match, fn.AGAINST(args)))

.where(Match((Post.title, Post.text), 'search query'))

.where(Match((Post.title, Post.text), 'foo AND bar', 'IN BOOLEAN MODE'))
```

**Comment by coleifer** [comment]
To make it even easier, I added an implementation in f76ce0b.
