### ISSUE TITLE
Can't access to joined model data

### ISSUE THREAD

**Issue by vladivanovx** [coleifer/peewee#1962]
I'm trying to implement Many to Many select (http://docs.peewee-orm.com/en/latest/peewee/relationships.html#implementing-many-to-many), but I can't access to Book model data:
```
query = User.select(
    User,
    Book,
    BookRelationship,
).join(
    BookRelationship,
    on=BookRelationship.from_user,
).join(
    Book,
).where(
    BookRelationship.to_user == self,
).order_by(
    BookRelationship.created_at.desc()
)

for item in query:
    # Can access only user data (item.username, item.fullname, item.age)
```
In this example, I'm trying to retrieve user data along with books he liked.

I didn't want to open this issue, because of this kind of trifle, but I couldn't find another way out.

**Comment by coleifer** [comment]
In a many-to-many things are complicated. Depending on how you join, you're going to get duplicated data on one side or the other. Remember that the output of any query is always going to be a flat table-like data-structure. There is no nesting. So no rolling up of multiple Books for a single User. You'll get one User and one Book per User `times` Book.

You can still access this, you'd probably do something like

```python
for user in query:
   related_book = user.book_relationship.book  # Something like this, depends on your field names.
```

Your best bet is to do something like this:

```python
user = User.get(User.username == 'charlie')
liked_books = Book.select().join(BookRelationship, on=BookRelationship.from_user).where(BookRelationship.to_user=user)
```
