### ISSUE TITLE
Postgres field extension - inet data type

### ISSUE THREAD

**Issue by danielguardicore** [coleifer/peewee#1965]
First off, Peewee is great :)

Postgres supports network data types.
https://www.postgresql.org/docs/9.1/datatype-net-types.html
What would be the best way to implement support for these fields instead of peewees IPAddr field?

A simple Field extension with the right type would suffice?

If so, I will prototype it and open a PR

**Comment by coleifer** [comment]
```python
class SomeField(Field):
    field_type = 'inet'
```

If you require conversion from python data-types to db-friendly data-types, you would implement `python_value()` and `db_value()` as needed.

http://docs.peewee-orm.com/en/latest/peewee/models.html#custom-fields
