### ISSUE TITLE
Can peewee create relations but without foreign key constraint?

### ISSUE THREAD

**Issue by ethanlinys** [coleifer/peewee#1966]
In sqlalchemy I can do like below. [https://stackoverflow.com/questions/37806625/sqlalchemy-create-relations-but-without-foreign-key-constraint-in-db](url)

```
In [2]: class A(Base):
   ...:     a_id = Column(Integer, primary_key=True)
   ...:     __tablename__ = 'a'
   ...:     

In [3]: class C(Base):
   ...:     c_id = Column(Integer, primary_key=True)
   ...:     a_id = Column(Integer)
   ...:     __tablename__ = 'c'
   ...:     a = relationship('A', foreign_keys=[a_id],
   ...:                      primaryjoin='A.a_id == C.a_id')
```
How can I do this by peewee?

**Comment by coleifer** [comment]
I don't really understand, nor am I familiar w/SQLAlchemy, so the code example makes no sense to me.

In short, if you want a foreign-key, use the foreign key field.

If not, use an `IntegerField` and add a property to your model class.

```python
class Tweet(Model):
    user_id = IntegerField()

    @property
    def user(self):
        return User.get(User.id == self.user_id)
```

But I have no idea why you would want to do this.

**Comment by est** [comment]
@coleifer  The popular use case is to auto-generate JOIN statements.

`Tweet.select(Tweet.user.id.alias("user_name"))`

Would be simpler than imperative JOIN.

**Comment by lambdaq** [comment]
Yes, you can.

`myfield = peewee.ForeignKeyField(OtherModel, lazy_load=True, _deferred=True)`

I can confirm `_deferred` does not generate shit like

```
 FOREIGN KEY (`myfield_id`) REFERENCES `othermodel` (`id`)
```
