### ISSUE TITLE
Matching peewee with vuex-orm

### ISSUE THREAD

**Issue by dsmurrell** [coleifer/peewee#1967]
I realise that it's not your problem to match peewee with random frontend tools... however, I'm wondering whether there is a simple solution that already exists but which I don't know about that can adequately match what peewee returns with what this specific frontend tool wants.

For models Studies and Surveys, where a survey belongs to a study, if I used the code:

`jsonify({'surveys': list(query.dicts())}`

to return a list of surveys, or 

`survey = query[0]`
`jsonify({'survey': model_to_dict(survey, recurse=False)})`

to return a single survey...

The key which represents the study in the dictionary is 'study', but in both instances (in the second because `recurse=False` is used) the value is the study's id. For example:

`{
      "description": "The is the Skin Pre-survey",
      "id": "r7mzY2A8uMZv4R67Ca9tFF",
      "study": "UQMKsya34CyKWMA7Y4ZWpX",
      "title": "Skin Pre Survey"
    }`

Is there any way to configure peewee to return a key of 'study_id' instead of 'study' here? As this would mean that the naming on the client side orm can be 'study_id' for the id, and 'study' for the related study. i.e. I can say survey.study_id and survey.study in the client side code which is far more readable.

Currently, to get around this we've mapped the id onto study and the object onto study_obj and this causes confusion.

I realise that we could get around this with bit of transforming at any point in the chain, but this would require extra lines of code for each foreign key in our schema and be an additional maintenance issue.

If this functionality doesn't exist already, we're happy to add it if you think it useful. Where about would be the best place to add this?

**Comment by coleifer** [comment]
`model_to_dict` is a convenience helper, but people definitely tend to treat it as the be-all/end-all of putting their model data in a dict.

You can try excluding the `study` field and specifying `extra_attrs=['study_id']` which will use the built-in foreign-key object ID accessor. That may work.

**Comment by dsmurrell** [comment]
Thanks, I'll give that a go!
