### ISSUE TITLE
Get the original SQL statement

### ISSUE THREAD

**Issue by ztj1993** [coleifer/peewee#1968]
I execute the code:

```
sql = AdModel.select(AdModel.id).where(AdModel.status == 9,).sql()
print(sql)
```

The output is:
```
('SELECT `t1`.`id` FROM `ht_silo`.`ht_ad` AS `t1` WHERE (`t1`.`status` = %s)', [9])
```

How to output:
```
SELECT `t1`.`id` FROM `ht_silo`.`ht_ad` AS `t1` WHERE (`t1`.`status` = '9')
```

Thank you!

**Comment by coleifer** [comment]
Peewee issues parameterized queries. All the db drivers peewee works with out-of-the-box support this, so the `.sql()` method returns the query and the params, which is exactly what is sent to the db.

If you want to try, you can use `peewee.query_to_string(q)` which will interpolate the parameters, but this is obviously vulnerable to sql injection and is only provided for debugging.
