### ISSUE TITLE
Init db instance later

### ISSUE THREAD

**Issue by danieldaeschle** [coleifer/peewee#1970]
Is there any chance to initalize the database instance later?

When i want to create a MysqlDatabase i must give the "database" parameter.
But at the point of creating the instance i don't know it.
But i have to create the instance to create the models.

A better way for me would be to define the models without depend on the db instance.
Is there a way to add the models later to the db instance?

**Comment by coleifer** [comment]
Read the docs.

http://docs.peewee-orm.com/en/latest/peewee/database.html#run-time-database-configuration
