### ISSUE TITLE
 what's the alternative usage of ReadSlaveModel

### ISSUE THREAD

**Issue by kaka19ace** [coleifer/peewee#1971]
hi, peewee playhouse 3.x version has no longer support read_slave, 
and what's the alternative usage?

**Comment by coleifer** [comment]
Instead of this, Peewee 3.x instead provides some really nice APIs for switching the database around at run-time.

* http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.bind_ctx
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.bind_ctx
