### ISSUE TITLE
Postgres transaction isolation level 

### ISSUE THREAD

**Issue by duvifn** [coleifer/peewee#1972]
Hi,
Probably I'm missing something but I couldn't find a way to specify transaction isolation level for Postgres (default to [`Read committed`](https://www.postgresql.org/docs/9.5/transaction-iso.html) which is not sufficient for my use case - in which `Repeatable read` is needed).

Any way to workaround it (without changing postgres config or manually open transaction)?

Thanks a lot!

**Comment by coleifer** [comment]
The underlying psycopg2 connection class is exposed as `db.connection()`, e.g.

```python
db = PostgresqlDatabase('my_app')
conn = db.connection()  # returns current conn, opening one if necessary
```

Then use the psycopg2 apis to set the isolation level:

```python
from psycopg2 import extensions
conn.set_isolation_level(extensions.ISOLATION_LEVEL_REPEATABLE_READ)
```

You can put all this in a hook provided by peewee and executed automatically when a new connection is created.

```python

class RCPostgresqlDatabase(PostgresqlDatabase):
    def _initialize_connection(self, conn):
        conn.set_isolation_level(...)
```

This hook is called whenever a new connection is opened, so its probably what you're looking for.

**Comment by coleifer** [comment]
Added support for passing this into the PostgresqlDatabase `__init__()` method in master, will be available in the next release.

**Comment by duvifn** [comment]
@coleifer Thanks for the quick response and the code addition!

Do you have any plan to add isolation level as a parameter to `db.atomic()` or `db.transaction()` in the future? Sometimes per-transaction config is needed rather than per-session....

**Comment by coleifer** [comment]
Not really, it seems from the psycopg2 docs that when you set the isolation level it is for the duration of the session, so there doesn't seem to be an API that is just for the lifetime of a transaction. Because of this, I'm inclined to leave it as an exercise to the reader to implement a context-manager or whatever you need.

**Comment by coleifer** [comment]
```python
@contextmanager
def isolation(level):
    conn = db.connection()
    orig = conn.isolation_level
    conn.set_isolation_level(level)
    try:
        with db.atomic() as txn:
            yield txn
    finally:
        conn.set_isolation_level(orig)
```

Something like this?

**Comment by duvifn** [comment]
OK. Thanks again.

In case someone else will encounter this thread - another possible option (which i didn't try) is to use raw [`SET TRANSACTION`](https://www.postgresql.org/docs/9.5/sql-set-transaction.html) statement which should be ran before any other query in the transaction.

**Comment by ponponon** [comment]
> OK. Thanks again. 好的。再次感谢。
> 
> In case someone else will encounter this thread - another possible option (which i didn't try) is to use raw [`SET TRANSACTION`](https://www.postgresql.org/docs/9.5/sql-set-transaction.html) statement which should be ran before any other query in the transaction.如果其他人遇到这个线程 - 另一个可能的选择（我没有尝试）是使用原始 `SET TRANSACTION` 语句，该语句应该在事务中的任何其他查询之前运行。

I also want a convenient way, for example when I try to set the isolation level parameter directly in atomic

```python
with db.atomic(isolation_level='SERIALIZABLE'):
    
    result = db.execute_sql("SELECT @@transaction_isolation;")
    current_isolation_level = result.fetchone()[0]
    print("Current transaction isolation level:", current_isolation_level)

```

Will report an error

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ponponon/Desktop/code/work/vobile-it/crawler_console/dev/peewee_test.py", line 9, in <module>
    with db.atomic(isolation_level='SERIALIZABLE'):
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4368, in __enter__
    return self._helper.__enter__()
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4403, in __enter__
    self._begin()
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4389, in _begin
    self.db.begin(*args, **kwargs)
TypeError: Database.begin() got an unexpected keyword argument 'isolation_level'
```
