### ISSUE TITLE
Unecessary index on table creation

### ISSUE THREAD

**Issue by lucianobarcaro** [coleifer/peewee#1974]
I'm new to peewee (2 weeks now) and I noted an unecessary index on table creation.

Simple case:
 
```
class Usuario(BaseModel):
    nome = CharField()

 
class UsuarioAcesso(BaseModel):
  usuario = ForeignKeyField(Usuario)
  dataAcesso = DateTimeField()
  fromIP = CharField()
  class Meta:
      primary_key = CompositeKey('usuario', 'dataAcesso')
```

On table UsuarioAcesso, peewee create 2 indexes:
Primary key as expected (usuario_id, dataAcesso)
and
usuario_acesso_usuario_id (usuario_id)

This second index is already covered with primary key (on MySQL/MariaDB, foreign keys works as expected with just primary key here).

Am I missing something?

Best regards :)

**Comment by coleifer** [comment]
You're welcome to override the default foreign-key index creation, by specifying `index=False` explicitly in the `ForeignKeyField` declaration/initialization.

You might double-check your information, however, to make sure that you actually *do* have an index on `user_id` in the referring table (`UserAccess`).
