### ISSUE TITLE
SchemaMigrator.add_column problem

### ISSUE THREAD

**Issue by richey-v** [coleifer/peewee#1977]
(using peewee 3.9.6 with sqlite3)

I am assuming the problem that I am reporting may be difficult to fix, so this Issue might be best resolved by adding a note to the relevant [documentation](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#SchemaMigrator.add_column).

I needed a new Field in a Model and I naively added the new Field _in between_ two other Fields.  I wanted to provide a migration for the new Field on this Model, so I used `add_column`.  The new Field was *inserted* in between the other two Fields, but the column for the data was added at the *end* of each row for the Model.

Ideally, `add_column` gets fixed to put the new data column in the correct position, but if that is too difficult or takes a long time to be fixed, _please_ add a note recommending that new Fields be added after the last old Field.

**Comment by coleifer** [comment]
What difference does it make what order the column is in the underlying storage? Absolutely none, truthfully.
