### ISSUE TITLE
Enumerating over query result

### ISSUE THREAD

**Issue by karambaq** [coleifer/peewee#1986]
I want to get next element after the predicate is true

I've tried to use 
```
    for i in enumerate(gs):
        if predicate(i[1]):
            print(i)
```
Output: 
```
(0, <Fighter: 202157127>)
(0, <Fighter: 202157569>)
(0, <Fighter: 202158125>)
(0, <Fighter: 202159063>)
(0, <Fighter: 202160131>)
(0, <Fighter: 202160498>)
(0, <Fighter: 202160800>)
```

I need to catch that `i + 1` element, how can I do that?

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/contributing.html

Post this on stackoverflow or ask in IRC. This forum is for issues.
