### ISSUE TITLE
pwiz creates all fields as FloatField regardless of precision

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#1988]
It seems when `pwiz` creates a schema, it assigns `FloatField` to all the floating point types, regardless of their precision. Could it be possible to have it create the appropriate type of field?

Alternatively, is there a way to access the Postgresql underlying type for a field without having to connect to the DB?

**Comment by coleifer** [comment]
Pushed a fix -- oid 701 appears to be double-precision, so it's up-to-date now. If your schema already exists, however, it doesn't matter because Python uses a double internally anyways. Lastly, if it's an issue, you are free to modify the fields yourself.

> Alternatively, is there a way to access the Postgresql underlying type for a field without having to connect to the DB?

I don't know what this means.

**Comment by albireox** [comment]
Thanks, that works. My use for this case is that I have a tool that uses the introspection utils to generate PDF with the DB tables and columns, and it was assigning FLOAT to all the columns regardless of precision.

> > Alternatively, is there a way to access the Postgresql underlying type for a field without having to connect to the DB?
> 
> I don't know what this means.

I meant if it's possible to get the PSQL type for a field (e.g., 'BIGINT', 'DOUBLE', 'REAL', 'VARCHAR', etc.)

**Comment by coleifer** [comment]
> I meant if it's possible to get the PSQL type for a field

Check the code in reflection, it has all the info you need. You can map the oid to the typname in the pg_type table.
