### ISSUE TITLE
Question - Is there a way not to create a base model table in the database?

### ISSUE THREAD

**Issue by dsmurrell** [coleifer/peewee#1997]
I did scan the docs briefly, but nothing obvious popped out at me. I want to have the following configuration but not have the base table be created in the database as it's never used by me. Is there a way to do this?

```
class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    username = CharField(unique=True)
```

**Comment by coleifer** [comment]
The base model *is not* created... you have to explicitly tell peewee which tables to create. It doesn't matter the inheritance chain -- each model class is just a single table.

**Comment by dsmurrell** [comment]
Thanks! 

I've been using peeweedbevolve for too long which creates all by default. Just found the answer here for my use case.

https://github.com/keredson/peewee-db-evolve/issues/24#issuecomment-360875831
