### ISSUE TITLE
Column casting doesn't work in 3.10.0

### ISSUE THREAD

**Issue by cubez** [coleifer/peewee#2000]
Up until 3.9.6 I could do this:

```python
TableName.select().where(TableName.some_int_field.cast("CHAR").contains("abc"))
```
The result would just be empty. But now in 3.10.0 I get this error:

```sh
ValueError: invalid literal for int() with base 10: '%abc%'
```
Looking through the changelog I can't really find anything that would cause this. So I don't know if this is a bug or a feature. :)

**Comment by coleifer** [comment]
I can see both sides, but I do think that I will make the logic for adapting values more permissive. What changed is that an expression now looks a little bit harder to see if the right-hand-side can be converted using the conversion implied by the left-hand field. For a cast(), however, this should be more permissive.

Should be working again: 92713817185aa7decf29234fe704ba2182c10196

**Comment by coleifer** [comment]
Actually, I changed my mind about how to fix this. Instead, I will look at the `_coerce` internal flag and use that to determine whether to apply the conversion.

42e2b429c226590bac20770a8a10a4b4a9b0c897

**Comment by cubez** [comment]
If it works, it works. 👍 Thank you for the fast fixing.
