### ISSUE TITLE
The Document's issue - "Model.first()"  exists, but the method had disappeared yet

### ISSUE THREAD

**Issue by hacker-lin** [coleifer/peewee#2001]
thanks for "peewee".
I saw a small  issue   when I read the  document .

Document version:  latest

and look follow pic.
![image](https://user-images.githubusercontent.com/30204682/64009446-7146e200-cb4a-11e9-8802-f173503c7117.png)

**Comment by oz123** [comment]
The Method is still there:

    def first(self, database, n=1):

https://github.com/coleifer/peewee/blob/b51b230a45e71464d90607ccfdd40ccff4d2d3f8/peewee.py#L2049

**Comment by hacker-lin** [comment]
I see,  I use it incorrect sry!

**Comment by coleifer** [comment]
Beat me to it @oz123 thanks for helping out a newcomer.
