### ISSUE TITLE
Peewee Decimal Field Max Digits

### ISSUE THREAD

**Issue by MatthewDLove** [coleifer/peewee#2015]
Hello, 

Thank you for this great ORM. I work at a crypto start-up and it's been very useful so far. 

We need to store values of monetary transactions, so we implemented a table using the decimal field (underlying table Postgres):

class Order(CustomModel):
    ....
    price = DecimalField(max_digits=15)
    execution_price = DecimalField(max_digits=15, null=True)
    ....

However, when our tests make an order with price 100,000 (crypto is crazy), we get this error:

"numeric field overflow
DETAIL:  A field with precision 10, scale 5 must round to an absolute value less than 10^5"

But max_digits 15 should set the precision to 15, correct? When I read the code I linked below, it doesn't seem like passing in this parameter is doing anything:

https://github.com/coleifer/peewee/blob/00f32293e99bc7ad90f4706bd6b46d88f200b431/peewee.py#L4491

According to this, postgres should be able to store far more than 6 digits before the decimal place:

http://www.postgresqltutorial.com/postgresql-numeric/

So is this an actual issue, or am I misreading something? I hope this is actually worth you reviewing and not a stupid mistake on my part - I see how active you are online answering questions, and I both appreciate and admire that.

**Comment by coleifer** [comment]
Max digits corresponds to precision
Decimal places corresponds to scale

I'm not clear in your example whether you're using the "," as a thousands-separator or a decimal separator.

If unspecified, scale defaults to 5. So your example would be equivalent to:

```
"price" NUMERIC(15, 5) NOT NULL
```

I have absolutely no issues with this in a simple test-case:

```python

class R(Model):
    val = DecimalField(max_digits=15)

R.create(val=Decimal('100000.000'))  # val='100000.000' also works fine.
r = R.get()
print(r.val)  # 100000.00000
```

SQL for the table:

```sql
CREATE TABLE IF NOT EXISTS "r" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "val" NUMERIC(15, 5) NOT NULL)
```

Something is wrong with your schema or the code you've shared, but it appears working fine for me.

> crypto startup

not even once
