### ISSUE TITLE
'autoconnect' unused in 'PostgresqlExtDatabase'

### ISSUE THREAD

**Issue by wibimaster** [coleifer/peewee#2019]
Hi !

I'm using Peewee for a Postgres database connection.

The latest documentation says "If you would like to use these awesome features, use the PostgresqlExtDatabase from the playhouse.postgres_ext module", so.. That's what I did :D

But I need the "autoconnect=False" feature, to handle the connection on my own and avoid timeout issues (Peewee never reconnects on its own).

I tried and see that this feature works with "PostgresqlDatabase", but not "PostgresqlExtDatabase" from playhouse..

Is it an oversight or a will?

Thanks !

**Comment by coleifer** [comment]
Nice find. I need to fix, thanks.
