### ISSUE TITLE
Sybase Database Connection in Peewee.

### ISSUE THREAD

**Issue by govind1993** [coleifer/peewee#2022]
Hi, Developers.

Do we have an option to connect to Sybase Database using Peewee ORM?

**Comment by oz123** [comment]
No, but it's easy to add your own database backed.

**Comment by coleifer** [comment]
You'll probably want to find a db-api 2.0 driver and then read the docs on adding a new database driver:

http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver
