### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by JoanEliot** [coleifer/peewee#2024]
(Windows 10, same experience with global/'main' Python and a venv) 
I'm a Python dunderhead so excuse any bad lingo or other evidence of lack.
 
Installation via pip/pypi gave no errors, but imports failed. Checking \site-packages I find peewee.py and pwiz.py out bare in the main folder, and an egg-info folder but no plain peewee folder. Installation via the peewee git/setup.py produced the expected peewee-3.11.0-py3.7 folder (well, .egg) and imports worked.

**Comment by coleifer** [comment]
Couldn't tell you. Peewee should be in the main folder, as it installs as a module, not a package.
