### ISSUE TITLE
How best to get inserted row count from Model.insert_many()?

### ISSUE THREAD

**Issue by grantcox** [coleifer/peewee#2026]
I would expect the `Model.insert_many().execute()` return value to the `rowcount` affected, however it appears to always be `0` (presumably it's attempting to get the primary row id inserted?).

I have found that the following approach works, hacking on how the `returning` implementation works.  But it doesn't look like the correct way:
```
multi_insert_query = MyModel.insert_many(rows).on_conflict(action='IGNORE')
multi_insert_query._return_cursor = True
cursor = multi_insert_query.execute()
total_inserted = cursor.rowcount
```

Any suggestions for how this is better implemented?  I am using MySQL 5.6, although I'm not sure that matters.

**Comment by coleifer** [comment]
I hear you -- thanks for mentioning the database you're using. This should work with sqlite as well, though I don't believe it will work for postgres -- but I need to test it out. Let me look into this as I think it's a worthwhile request.

**Comment by coleifer** [comment]
ab43376

**Comment by coleifer** [comment]
Just a heads-up that this change has been rolled-back in #2556. Going forwards, to obtain the inserted row count, you may use the `Insert.as_rowcount()` chainable query method. Examples:

```python
db = MySQLDatabase(...)

query = User.insert_many([...])
# Old behavior:
#rowcount = query.execute()

# Behavior going forwards:
lastid = query.execute()

# To get the rowcount instead of the last id:
rowcount = query.as_rowcount().execute()
```
