### ISSUE TITLE
OpenAPI Specification / SwaggerUI for REST API

### ISSUE THREAD

**Issue by brandond** [coleifer/peewee#2029]
I'd love to have an autogenerated OpenAPI spec with SwaggerUI support that was easy to use with `flask_peewee.rest`. Someone hacked this together as a standalone module but the project appears to be dead:
https://github.com/hapyak/flask-peewee-swagger

I recently hacked together a translation layer to expose PynamoDB models via [Flask-RESTPlus](https://flask-restplus.readthedocs.io), so I considered taking a shot at that for Peewee, but I'd much rather use your built-in REST layer if at all possible.

**Comment by brandond** [comment]
That's a no then?

**Comment by coleifer** [comment]
> flask_peewee

wrong repo

**Comment by brandond** [comment]
I also saw the message on the docs site you're not working on the REST stuff any more. Sorry.

**Comment by brandond** [comment]
Right, sorry. I just assumed it was a submodule like the playhouse stuff. I just saw the message that you're not working on it any more. Did you ever get around to breaking out the REST bits into a separate library?
