### ISSUE TITLE
JSONFields can't be updated using Model.bulk_update if they're top-level lists

### ISSUE THREAD

**Issue by KarolTrojanowskiDL** [coleifer/peewee#2034]
DISCLAIMER: I am terribly sorry I didn't read that I should post an issue first. There's already a PR I made for this: #2033 

I noticed that using `Model.bulk_update` won't work with `JSONField`s that are top-level lists because by default `Value` will unpack the list into multiple values. Top-level lists are valid JSON objects.

Example:

```python
class Item(Model):
    json = JSONField()

item = Item.create(json=['a','b'])
item.json = ['c','d']

Item.bulk_update([item], fields=[Item.json])
```
will raise `OperationalError` because of a malformed update query.

**Comment by coleifer** [comment]
Fixed by above commit. Thanks for the report!
