### ISSUE TITLE
read from slave, write to master

### ISSUE THREAD

**Issue by evstratbg** [coleifer/peewee#2037]
Hi! I'm using peewee 3.11.2

We have master-slave postgres instances, slave - for reading, master - for writing

https://github.com/coleifer/peewee/blob/fc842eaf54a5d047f9281cf1866f81ce93a98496/docs/peewee/changes.rst
I've found out, that there is no longer `read_slave` extension (link above)

Any possibilities to read from slave and write to master in peewee > 3.0?

**Comment by coleifer** [comment]
You'll have to implement it yourself, which can actually be pretty easy.

You probably want to have two database instances (or two pools):

```python

master = PooledPostgresqlDatabase('master')
db = PooledPostgresqlDatabase('slave')
```

Then you can use the `bind_ctx()` context manager to bind your model(s) to the master when you need to do some writes:

```python

# Grab connection to master db from pool, and return it after write.
with master.connection_context():
    # Instruct user model (and related models) to use master db for write.
    with master.bind_ctx([User]):
        User.create(username='huey')
```

You can abstract this away in your own context manager:

```python

@contextmanager
def use_master(models):
    with master.connection_context():
        with master.bind_ctx(models):
            yield
```

Docs: 

* http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.bind_ctx
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.connection_context

**Comment by rms-sth** [comment]
@coleifer It looks like transaction is not maintained while using `master.bind_ctx(models)`. Can you provide some example where I can use maintain transaction while being able to bind the model to specific database?

**Comment by coleifer** [comment]
Transactions are specific to a database connection, so there's literally no way to carry the transaction across to another connection...
