### ISSUE TITLE
[Request] field type migrations for playhouse.migrate PostgresqlMigrator

### ISSUE THREAD

**Issue by mountainash** [coleifer/peewee#2038]
Can a function be added to PostgresqlMigrator to allow for field types to be changed and logged in a migration? (eg smallint to biginit)

Thank you.

**Comment by mountainash** [comment]
Just found this as a possible workaround, but it's a fair bit of "work" :-)

https://teamtreehouse.com/community/changing-a-peewee-charfield-to-a-textfield

**Comment by coleifer** [comment]
This is a pretty decent request, let me think about what it would entail.

**Comment by mountainash** [comment]
Dang - that was fast. Nice work!

**Comment by coleifer** [comment]
Thx, I appreciate the suggestion.
