### ISSUE TITLE
Peewee returns trigger information, but psycopg2 does not

### ISSUE THREAD

**Issue by phuvp** [coleifer/peewee#2039]
Hi, I have created a few triggers and am now trying to print their information out. When I run the below, the psyco method errors out since `result=None`, whereas the peewee method returns a list of trigger info shown below. I've already checked that the cursor for psycopg2 is in the right database. I'd like to know what causes this discrepancy.

Output:
`
[('test_db', 'public', 'executortrigger', 'INSERT', 'test_db', 'public', 'executortable', 1, None, 'EXECUTE PROCEDURE test_executor()', 'ROW', 'AFTER', None, None, None, None, None)]
`

`def list_triggers_peewee():
    return [i for i in POSTGRES.execute_sql('select * from information_schema.triggers;')]
`
`
def list_triggers_2_psyco():
    result = psyco_cursor.execute('select * from information_schema.triggers;')
    return [i for i in result.fetchall()]
`

version is peewee 3.10.0

**Comment by coleifer** [comment]
This is not a peewee issue. This is a psycopg2 question. Please use the appropriate forum going forward.

Psycopg2 cursor methods do not return a result. So:

```
cursor = conn.cursor()
cursor.execute('select ...')
for row in cursor.fetchall():
    ...
```
