### ISSUE TITLE
sqlite3.Warning: You can only execute one statement at a time.

### ISSUE THREAD

**Issue by luminousmen** [coleifer/peewee#2040]
Hi, I'm trying to execute some SQL scripts on the sqlite database. The SQL scripts example:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
    id integer,
    name VARCHAR(100)
);
INSERT INTO t1(id, name) VALUES
    (1, 'test');

```
And the code:

```python
from peewee import SqliteDatabase

database = SqliteDatabase(":memory:")

for template in templates:
    query = template.format(**args)
    database.execute_sql(query)
```
It all crashes on `execute_sql` call because internally the code calls the `execute` method of sqlite and it expects just one particular query.

How to fix that? The same code works with postgres

**Comment by coleifer** [comment]
pysqlite does not like it. Just break it up into multiple statements or use the connection directly and call the `executescript()` method.

https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.executescript
