### ISSUE TITLE
Usage example with FastAPI framework

### ISSUE THREAD

**Issue by anil-grexit** [coleifer/peewee#2042]
Hi,

I'm trying to integrate peewee with FastAPI and would be using it with the Serverless lambda framework. Can you provide me an example of how I would structure and use the database in terms of Models? I need to make sure that in a single lambda invocation I'm opening the DB connection, it's closed when the response is sent.

FastAPI documentation only contains SQLAlchemy related things and I love peewee since it's small, efficient and expressive. Any pointers on code structure would be helpful. It would be great if you could share a sample app with MySQL which I can start off with.

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/contributing.html#questions
