### ISSUE TITLE
BinaryJSONField unescaped JSON text

### ISSUE THREAD

**Issue by DucChau** [coleifer/peewee#2045]
Hello,

I'm using `PostgresqlExtDatabase` for the `JSONBField` types.

I currently have a JSONB text field in a Postgres table. When I set the field type to `TextField` in the PeeWee model, saving data in the table looks like valid JSON. Example of JSON value I'm saving to the table below.

``` {"query": "select \n    count(*) as count \nfrom\n    foo\n", "value": [21950367]}```

However when I switch the field type out to `BinaryJSONField` all values in the field becomes escaped. This makes it a pain to use the JSON parsing functions in Postgres.

```"{\"query\": \"select \\n    count(*) as count \\nfrom\\n  foo\\n\", \"value\": [21950367]}"```

Is there a way to not escape values going into the `BinaryJSONField` field when saving via a model in peewee?

**Comment by coleifer** [comment]
I'm not clear on why you used a text-field in the first place or whether that is in any way related to the problem. Or, for that matter, what the underlying actual column type is on your table? The peewee `playhouse.postgres_ext.BinaryJSONField` will store and retrieve data as JSON. So you can store `dict`, `list`, and string/scalar values.

The docs should give you clear examples on usage:

* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#JSONField
* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#BinaryJSONField
