### ISSUE TITLE
Support for SuperSQLite

### ISSUE THREAD

**Issue by lllama** [coleifer/peewee#2067]
Is it possible to swap out the default sqlite driver with SuperSQLite? (https://github.com/plasticityai/supersqlite). The library provides an up to date version of sqlite and adds a number of extensions which would be useful for my app.

Can I swap the underlying lib, or would it require its own backend?

**Comment by coleifer** [comment]
You have *got* to be kidding me, this is absolute garbage. It is incredibly easy to build your own SQLite, which the default Python driver should pick up.

This should contain all the information you might need:

http://charlesleifer.com/blog/compiling-sqlite-for-use-with-python-applications/

**Comment by lllama** [comment]
Not seeing a single thing about Windows on there, plus specifying a single dependency with pre-built binaries would make cross-platform distribution a lot easier but thanks for the quick response, I guess?

**Comment by coleifer** [comment]
Sorry - I don't know the first thing about how to do this on Windows.

**Comment by lllama** [comment]
Okay, I'll investigate what I need to do for that and how to bundle it up with my app. Given that I'll struggle to then get a Windows build working with gitlab CI, would implementing my own backend be the best way forward should I want to use that other lib? Or is some sort of monkey patch possible to get the existing one working?

**Comment by coleifer** [comment]
You can look at the apsw playhouse extension for an example, since it looks like supersqlite is a wrapper on apsw.
