### ISSUE TITLE
Should there be an All expression?

### ISSUE THREAD

**Issue by toppk** [coleifer/peewee#2073]
Just getting started with peewee, and I was looking at this pattern , to dynamically control the "where " clause.   

```
where = Expression(1,"=",1) # All
if some_condition1():
    where &= (Users.group_id != 1)
if some_condition2():
    where &= (Users.name % "%en%")
query = Users.select().where(where)
```

It seems this pattern is the best way to accomplish a dynamic where condition.  If so, it would be nice to have an "All" expression instance inside peewee, so I wouldn't have to define it myself.  

Something like:
`All = Expression(1,"=",1)`

Of course, if there's an better way to control which expressions are used in a query, I'd like to know what it is, I've looked at the examples, and didn't see anything offhand.

**Comment by coleifer** [comment]
Just append to a list and use `reduce` to combine the list elements (expressions).

**Comment by coleifer** [comment]
https://stackoverflow.com/questions/22238194/python-peewee-dynamically-or-clauses?r=SearchResults

**Comment by toppk** [comment]
That still has the same issue with an empty clauses array.  you need to have one element for this to work.

**Comment by coleifer** [comment]
```python
clauses = [
    (User.username == 'something'),
    (User.something == 'another thing'),
    ...
]
query = User.select()
if clauses:
    query = query.where(reduce(operator.or_, clauses))
```
