### ISSUE TITLE
Get the SQL output of count?

### ISSUE THREAD

**Issue by ztj1993** [coleifer/peewee#2078]
Suppose I have a query

```
OrderModel.select().count()
```

I want to get SQL output, Because I only use the model, not the database.

**Comment by coleifer** [comment]
>I want to get SQL output

I don't know what this means? The above function will query the database and return the count of rows in the select query.

**Comment by coleifer** [comment]
You can use `.scalar()` to obtain the result of a scalar aggregate query.

http://docs.peewee-orm.com/en/latest/peewee/querying.html#retrieving-scalar-values

Please note that the issue tracker is not for "how do I..." questions. Post those on stackoverflow or ask in the #peewee IRC channel or mailing list. This is for tracking issues with the software.
