### ISSUE TITLE
something is wrong with proxy

### ISSUE THREAD

**Issue by viponedream** [coleifer/peewee#2080]
in one app, i want to use two database, but it only save to the last database.

1,  define model
database_proxy = Proxy() 

class Item_DB(Model):
   user = CharField(null=True, unique=False)
    class Meta:
        database = database_proxy  # Use proxy for our DB.

2, define my own class the use peewee.
class Database:
 def __init__(self, table_name: str, orm_mapping = None, db = None):
        self.table_name = table_name      
        self.table = None                
        self.db = db if db is not None else sqlite_database  
        database_proxy.initialize(self.db)
        self.orm_mapping = orm_mapping if orm_mapping is not None else Item_DB 
    
def get_table(self):
        table = type(self.table_name, (self.orm_mapping,), {})
        self.db.connect(reuse_if_open=True)        
        if not table.table_exists():
            try:
                table.create_table()
            except BaseException:
                print(f'建立表{table}不成功!')
        return table

   def update(self, item: Item):
        table = self.get_table()
        with self.db.atomic() as transaction:
            try:
                table.replace(item.__dict__).execute()
            except:
                transaction.rollback()

3, use it now
DB_NAME = "all_account.db"
DB_PATH = os.path.join(ROOT_PATH, DB_NAME)
_db = SqliteDatabase(str(DB_PATH))     
all_db = Database(table_name=app_name, orm_mapping=Item_DB, db=_db) 

DB_NAME = "account.db"
DB_PATH = os.path.join(ROOT_PATH, DB_NAME)
_db = SqliteDatabase(str(DB_PATH))     
main_db = Database(table_name=app_name, orm_mapping=Item_DB, db=_db)  

item=something
all_db.update(item)
i want to save the data to the first db(all_db), but in fact it save to the last one.

it seems it can not change the database.

**Comment by coleifer** [comment]
Please edit your issue to format your code and I will reopen.
