### ISSUE TITLE
ambiguous column error on update query

### ISSUE THREAD

**Issue by ydelibasi** [coleifer/peewee#2082]
I have two geometry columns with same name. I would like execute update query but I get "peewee.ProgrammingError: column reference "geom" is ambiguous"  error. 
How to use alias for this columns ?

``` 
UserFileRows.update(
    location_ids=Location.parent_ids
)
.from_(Location)
.where((fn.st_intersects(UserFileRows.geom, Location.geom)) &
       (UserFileRows.fileid == file_id) &
       (Location.location_level_id == 4)).execute()
```

**Comment by coleifer** [comment]
Can you share the generated SQL for your query? I tried to replicate a minimal example and the generated SQL contains qualified names that would seem to resolve any ambiguity.

**Comment by ydelibasi** [comment]
generated SQL:
`
('UPDATE "user_data"."user_file_rows" SET "location_ids" = "parent_ids" FROM "r_data"."location" AS "t1" WHERE ((st_intersects("geom", "geom") AND ("fileid_id" = %s)) AND ("location_level_id" = %s))', ['6f3697c3-****', 4])
`

I use peewee 3.6.4
Thanks

**Comment by coleifer** [comment]
Upgrade to a newer version - that should resolve the problem with the SQL generation.

**Comment by ydelibasi** [comment]
I upgraded version. It works.

Thanks
