### ISSUE TITLE
how write one code in peewee for mysql, sqlite

### ISSUE THREAD

**Issue by TechComet** [coleifer/peewee#2086]
Hi,

how write one code in peewee for mysql, sqlite

I use peewee and sqlite on local server but on server use mysql need write one code to use mysql and sqlite

Like
```
database_type = 'mysql'

if database_type == 'mysql':
    db = peewee.mysql_connect('localhost', 'root', 'password', 'test1234.db')
else:
    db = peewee.sqlite_connect('test123.db')
```

if write MEDIUMTEXT Field and sqlite in database_type use this like TEXT

**Comment by coleifer** [comment]
You can specify a custom field type, e.g.

```python
class MediumTextField(TextField):
    field_type = 'MEDIUMTEXT'
```

And just use that if the db is mysql.

Alternatively, you can configure MySQL to treat all textfields as MEDIUMTEXT if you wish:

```python
MySQLDatabase.field_types['TEXT'] = 'MEDIUMTEXT'
```

**Comment by TechComet** [comment]
I think something like this is what I was looking for

class UnknownField(object):
    def __init__(self, *_, **__): pass

thank you
