### ISSUE TITLE
Add backref after foreign key declaration

### ISSUE THREAD

**Issue by Rizhiy** [coleifer/peewee#2089]
Is it possible to add `backref` after foreign key is declared?

I'm trying to do something like:
```python
class User(Model):
	username = CharField(unique=True)


class BasePost(Model):
	date = DateField()
	user = ForeignKeyField(User)
	
	class Meta:
		primary_key = CompositeKey('date', 'ticker')


class ShortPost(BasePost):
	text = CharField()
User.add_ref(ShortPost, 'short_posts')

class LongPost(BasePost):
	text = TextField()
User.add_ref(LongPost, 'long_posts')


class PicturePost(BasePost):
	url = CharField()
User.add_ref(PicturePost, 'pictures')

... other types of posts
```
i.e. I want to have a limit of one type of post per user per day and repeating `CompositeKey('date', 'ticker')` along with the fields is ugly and tiresome.

I don't want to combine all posts into one table, since with many types of posts the table will get very sparse very fast.

**Comment by coleifer** [comment]
You're going to have a really bad time inheriting foreign-keys. It just doesn't work well.

Furthermore, composite primary-keys are not well-supported, e.g. Peewee doesn't support foreign-keys to models with composite PKs.

Also, having different tables for various "post" types is almost guaranteed to be a mistake. If you ever want to combine the results you're forced to do unions and then you will be fighting to get the data you need for each type.

Play to the strengths of your database and your tools and use a single table with multiple columns (post_type, text, e.g.). It won't waste space. You know what they say about premature optimization, right?

Do not use a composite PK (really). Just use an auto-incrementing integer or a UUID if you must. You can add a multi-column unique index on anything you need to constrain.
