### ISSUE TITLE
Can't convert string to float 

### ISSUE THREAD

**Issue by vkachhawa** [coleifer/peewee#2105]
I have a database which has the column "loc" which has latitude and longitude data stored in a string:like this " [36.166540711883776,-115.14080871936427]" it's a complete string now i am able to get values of latitude and longitude using query like this: "36.166540711883776".Now how do i convert them to a float value in the query so i can use them in the great circle distance formula My code looks like this:
radius = 10

    query_lat = (new_table.select(fn.substr(new_table.loc, fn.instr(new_table.loc, "[") + 1, fn.instr(new_table.loc, ",") - 2)))
    query_long = (new_table.select(fn.substr(new_table.loc, fn.instr(new_table.loc, ",") + 2,(fn.instr(new_table.loc, "]") - fn.instr(new_table.loc, ",") - 2))))

    output_query = (new_table.select(new_table.id, new_table.loc, new_table.userId, new_table.description, new_table.price, new_table.status).where(
            (fn.acos(
             fn.cos(fn.radians(36.166540711883776)) * fn.cos(
                 query_lat) * fn.cos(fn.radians(-115.14080871936427) - query_long)
             + fn.sin(fn.radians(36.166540711883776)) * fn.sin(query_lat)) * 3969) <= radius))

**Comment by coleifer** [comment]
This is not your personal "help" message board. Use stackoverflow if you need help. Also you contacted me directly via my website in addition to posting here. Please don't spam.

As I said in my email response to you, your data is fucked. You're storing lat/lon in a string field like `[1.234, 2.345]`. Just process your data and separate them out into two separate numeric columns, and your life will be easier *plus* your queries will execute dramatically faster.

**Comment by coleifer** [comment]
`fn.cast(the_string_expression, 'numeric')` should do it, by the way.
