### ISSUE TITLE
playhouse/introspector: doesn't work with capitalized table names (Postgres DB)

### ISSUE THREAD

**Issue by fmarcolino** [coleifer/peewee#2108]
Hello, I'm trying inspect a table, but he doesn't find her. A exception is raised: UndefinedTable. I think that there is a bug in the query. When we don't put the double quotes in the table name, the postgres database consider name table as lower case.

![image](https://user-images.githubusercontent.com/19367970/74610484-60773200-50d2-11ea-9112-6317b5252cce.png)

I did here fixing the identifier table, in the PostgresqlMetadata Class and he works now.

What is the best solution?

Vlw flw

**Comment by coleifer** [comment]
Thanks, I've merged your patch.
