### ISSUE TITLE
Update record through foreign key

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2113]
If I have two tables, say `User` and `Tweet` related via a foreign key, and I try to do

```python
tweet = Tweet.select().first()
tweet.user.name = 'John Smith'
tweet.save()
```

The new name for the user is not saved (although no error is raised and `tweet.save()` returns `1`). The same is true if I do `tweet.user.save()`.

Is is possible to update the related record in peewee? I know I can do the query on `User` and join with `Tweet`, but sometimes it'd be convenient to update it through the foreign key.

**Comment by coleifer** [comment]
Peewee is an active record ORM, so you would need to `save()` any instances you modify.
