### ISSUE TITLE
How to compare with boolean for PostgreSQL?

### ISSUE THREAD

**Issue by EugeneRymarev** [coleifer/peewee#2119]
Hello!
`Table.coumn == False` in peewee give me
`Table.column = 0` in sql. 
And i receive error "can't compare boolean and int".

**Comment by EugeneRymarev** [comment]
`Table.Column == SQL('false')` works fine, but that wrong way

**Comment by coleifer** [comment]
Huh? I've added a regression test that shows the full range of boolean comparisons. I could not replicate any problems on my machine: a9ebf6bdf2c7a74a802bd6860d1357b091b332a2
