### ISSUE TITLE
Field help_text attribute?

### ISSUE THREAD

**Issue by jvickroy** [coleifer/peewee#2120]
What is the intent of the help_text attribute?
Looking at the code, it seems to only be be listed in the class Field definition.
I would like to be able to access the help_text strings, in my scripts, but do not know how to do so.
Could someone point in the right direction?
Thanks for your time.
P.S.  peewee is great!

**Comment by coleifer** [comment]
It's available to provide a standard way of adding metadata. `flask-peewee` &co made use of it. To access the help text, just access `field.help_text`. To iterate a model's fields, `ModelClass._meta.sorted_fields` returns the fields in order of declaration.
