### ISSUE TITLE
Hybrid expression with JOIN

### ISSUE THREAD

**Issue by vltr** [coleifer/peewee#2121]
Howdy! I'm fairly new to `peewee`, but have some strong background on SQLAlchemy (and all the vices that come with it). I'm trying to create a custom hybrid expression that correlates to a third (or N) table. I'll try to demonstrate in an example (non-tested) code:

```python
class BaseModel(Model):
    class Meta:
        database = database


class Person(BaseModel):
    id = PrimaryKeyField(column_name="person_id")
    name = CharField(max_length=255, column_name="person_name")
    username = CharField(max_length=255, column_name="person_username", null=True)



class PersonTree(BaseModel):
    id = PrimaryKeyField(column_name="person_tree_id")
    name = CharField(max_length=255, column_name="person_tree_name")
    code = CharField(max_length=255, column_name="person_tree_code")

    person = ForeignKeyField(
        column_name="person_id",
        model=Person,
        field="id",
        backref="tree",
    )


class Article(BaseModel):
    id = PrimaryKeyField(column_name="article_id")
    name = CharField(max_length=255, column_name="article_name")

    branch = ForeignKeyField(
        column_name="person_tree_id",
        model=PersonTree,
        field="id",
        backref="articles",
    )

    @hybrid_property
    def username(self):
        """
        This gives me the possibility to grab the direct username of an article
        """
        return self.branch.person.username

    @username.expression
    def username(cls):
        """
        What if I wanted to do: Article.query().where(Article.username == "john_doe") ?
        """
        pass
```

With the `username` `hybrid_property` on `Article`, I can get the `username` of the `Person` related to an `Article` using the `PersonTree` as a correlation, so far so good, but ... What if I wanted to "create a shortcut" to query all `Articles` created by the `"john_doe"` `Person` username, without declaring the `JOIN`s every time I make the query and without `.filter(branch__person__username="john_doe")`? I know it's possible with SA (to a great extent), but I'm finding this hard to accomplish with `peewee`.

Just for example, here's the SQL I hope to be able to construct:

```sql
SELECT
    *
FROM
    article a
    JOIN person_tree pt ON a.person_tree_id = pt.person_tree_id
    JOIN person p ON pt.person_id = p.person_id
WHERE
    p.username = 'john_doe';
```

Thanks a lot in advance!

**Comment by coleifer** [comment]
Questions typically go on stackoverflow.
