### ISSUE TITLE
Clarify PostgresqlMigrator.set_search_path in docs

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2130]
It may be beneficial to make a bit more clear that `PostgresqlMigrator.set_search_path` needs to be added to `migrate` for it to take effect. That may be obvious in hindsight but because of the way it's presented in the docs API it took me a good while to realise that. An example in the main section of the Schema Migration docs would be useful.

**Comment by coleifer** [comment]
Can you give an example of what you mean? I would have thought that the setting of `schema` on models would have been adequate, and that the migration methods would take the schema into consideration, though I may be wrong.

**Comment by albireox** [comment]
I may be misunderstanding how it's supposed to work but I'd guess that if I do

```python
 selected_field = peewee.BooleanField(default=True, null=False)
 migrator = PostgresqlMigrator(database)
 migrate(migrator.add_column('temp_guide', 'selected', selected_field))
```

and the `temp_guide` table is in a schema called `sandbox` that won't work because at any point I'm passing the `TempGuide` model to the migrator. Instead, doing

```python
 selected_field = peewee.BooleanField(default=True, null=False)
 migrator = PostgresqlMigrator(database)
 migrate(
    migrator.set_search_path('sandbox'),
    migrator.add_column('temp_guide', 'selected', selected_field)
)
```

works fine. But it took me a bit to realise that `migrator.set_search_path('sandbox')` had to be inside the `migrate` function.

Not saying that there's anything wrong per se in the docs, but it could be made a bit clearer.

**Comment by coleifer** [comment]
Thanks, added a note.
