### ISSUE TITLE
Python 3.8.0 : reduce is not defined

### ISSUE THREAD

**Issue by caryfitzhugh** [coleifer/peewee#2137]
Running with python 3.8.0 I run into errors where 'reduce is not defined'.

In looking at it peewee.py assumes that if you can 
```python
from collections.abc import Callable
```
then you don't need to import reduce.

In my environment at least, that is not accurate.

At the top of peewee.py (around line 192 in my latest version) - could we drop in this snippet?
```python
try:
    reduce
except NameError:
    from functools import reduce
```

**Comment by maxlv7** [comment]
in python 3,reduce are moved to functools module.you can use this snippet.

**Comment by maxlv7** [comment]
> Running with python 3.8.0 I run into errors where 'reduce is not defined'.
> 
> In looking at it peewee.py assumes that if you can
> 
> ```python
> from collections.abc import Callable
> ```
> 
> then you don't need to import reduce.
> 
> In my environment at least, that is not accurate.
> 
> At the top of peewee.py (around line 192 in my latest version) - could we drop in this snippet?
> 
> ```python
> try:
>     reduce
> except NameError:
>     from functools import reduce
> ```
in python 3,reduce are moved to functools module.you can use this snippet

**Comment by coleifer** [comment]
You must be using an old version of Peewee. For quite a long time it's had `from functools import reduce`.

**Comment by coleifer** [comment]
https://github.com/coleifer/peewee/blob/master/peewee.py#L172

**Comment by caryfitzhugh** [comment]
apologies.. I checked I was running the latest code, but - in debugging something else in that file I think my auto-save in vim reformatted some imports, and "fixed" the indentation on that one line without me knowing... Apologies again.  Thanks - all seems to work now.
