### ISSUE TITLE
Comparison operations for subqueries

### ISSUE THREAD

**Issue by EugeneRymarev** [coleifer/peewee#2143]
Hi, @coleifer!
Again with same problem, but not for **EQ** or **NE** operations.
Other operations not work too. Like **LT** or **GT**.
In _HashableSource class need add more operations from **OP**.

https://github.com/coleifer/peewee/issues/2118#issuecomment-593150353_

**Comment by coleifer** [comment]
4919f5b6ea56969e56abaa5f4e276452e96bc9c9
