### ISSUE TITLE
no function fts_bm25

### ISSUE THREAD

**Issue by Dawoodkhorsandi** [coleifer/peewee#2146]
Hi

I tried to use sqlite3 full-text search with peewee when I run this code 
```Python
Poets.select().
            join(PoetsIndex, on=(Poets.id == PoetsIndex.rowid)).
            where(PoetsIndex.match(phrase))
            order_by(PoetsIndex.bm25())
```
it's throws error:

    cursor.execute(sql, params or ())
    peewee.OperationalError: no such function: fts_bm25

the match function works well, I tried raw SQL too, and it was good, so probably my version contains FTS3 and FTS4, why that error occurs?

Thank you for peewee

**Comment by coleifer** [comment]
Peewee ships with some user-defined functions which provide the bm25 ranking (when using fts3/4). You need to ensure that you're using `SqliteExtDatabase` as your database class and you should be good-to-go, as it will register the rank functions by default.

You can register them yourself, too, just check out the code in `playhouse.sqlite_ext` (and the optional C extension) if you're curious.
