### ISSUE TITLE
mysql default sql_mode setting

### ISSUE THREAD

**Issue by amchii** [coleifer/peewee#2147]
Hi,

peewee set the sql_mode to `'PIPES_AS_CONCAT'` when use `MySQLDatabase`, but this will remove the default setted values `'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'`, 

```python
import peewee

pwdb=peewee.MySQLDatabase('test',user='root',password='password')

r=pwdb.execute_sql('select @@session.sql_mode')

r.fetchall()
Out[4]: (('PIPES_AS_CONCAT',),)

from MySQLdb import _mysql

db=_mysql.connect(user='root',passwd='password',db='test')

db.query('select @@session.sql_mode')

res=db.use_result()

res.fetch_row()
Out[9]: ((b'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',),)
```
and this lead to when insert a `not null` field without value(also no default), no error throw, incorrect insert(for normal) see https://github.com/coleifer/peewee/issues/2031
```python
from peewee import *


db = MySQLDatabase(DB_NAME, user=DB_USER, password=DB_PASSWORD)

class M(Model):
    value = IntegerField(default=None, null=False)
    class Meta:
        database = db

db.create_tables([M])

m = M.create()
m_db = M[M.id]

print(m_db.value)

# output:
# /home/bukinpk/.local/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1364, "Field 'value' doesn't have a default value")
#   result = self._query(query)
# 0
```

i think the sql_mode setting should append `'PIPES_AS_CONCAT'` to the default setting instead of replace

**Comment by coleifer** [comment]
You're welcome to specify whatever sql mode you wish by passing it in the constructor.
