### ISSUE TITLE
[Question] Return FKs with an _id suffix.

### ISSUE THREAD

**Issue by dsmurrell** [coleifer/peewee#2148]
Right now, even though foreign keys are stored as field names in the database with an `_id` suffix, they are added to the dictionary outputted by `model_to_dict` without the `_id` suffix.

I was wondering, if I want all foreign keys to appear in the output dict of `model_to_dict` with a `_id` suffix, do I have to write custom code to achieve this, or is there a setting in peewee that can achieve this.

The reason I ask is because on the client side, the expectation is to receive the `_id` suffix for FKs and right now I'm adding them on the client side for all keys that match some list of FKs. This is a brittle solution and I'd like to improve it.

For example, if a `post` has a `user` FK, then I'd like `model_to_dict(post)` to output something like:

```
{
  id: "xyz",
  title: "This is a post",
  user_id: "abc"
}
```

**Comment by coleifer** [comment]
`model_to_dict` is simply a shortcut, provided for convenience. If you need something different, then just implement a simple serialization function.

**Comment by dsmurrell** [comment]
I understand that and have read that elsewhere... just checking that something didn't exist already that I was missing. Thanks!
