### ISSUE TITLE
[q] Run-time model schema

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#2150]
Hi there!
I'm trying to make a multitenancy application (flask+peewee). I think it possible to change the schema for all models in runtime but can't find the way.
Any example, pls (without context managers)

Thanks!

**Comment by coleifer** [comment]
You can use the `SubclassAwareMetadata` implementation, which tracks all models declared in your app. From that list of models, you should be able to easily iterate through them and change each model's `._meta.schema`.

**Comment by coleifer** [comment]
This is exactly covered in this test-case:

https://github.com/coleifer/peewee/blob/4919f5b6ea56969e56abaa5f4e276452e96bc9c9/tests/models.py#L3255-L3287
