### ISSUE TITLE
ManyToMany field no longer has .add, .remove, .clear methods

### ISSUE THREAD

**Issue by PylakeyTeam** [coleifer/peewee#2153]
I suppose that http://docs.peewee-orm.com/en/latest/peewee/relationships.html#manytomanyfield is outdated. 

Example in docs doesn't work with latest peewee version because of AttributeError

EDIT: This issue is related to ManyToManyField with through_model set.

**Comment by PylakeyTeam** [comment]
I am sorry for opening this issue. Already found a stupid mistake

**Comment by coleifer** [comment]
The example code runs fine for me on the latest version of Peewee.

https://gist.github.com/coleifer/8dd15da06ed5e390064ff99ae8ef9378

The methods you mentioned *are* present. They are exposed on the backref accessor, not the field itself - this is how it has worked for a very long time.

**Comment by PylakeyTeam** [comment]
@coleifer, thanks for your reply, there was my mistake)
