### ISSUE TITLE
Slow attribute access in 2.10.2

### ISSUE THREAD

**Issue by ParthGandhi** [coleifer/peewee#2156]
We're on version `2.10.2`, with no plans to upgrade in the short term.

From our profiling we've found that `__get__ peewee.py:915` takes a really long time in some of our hot code paths. Any idea why that `FieldDescriptor` is so slow? It seems to be doing just a `get` on a dict. I tried accessing the underlying `._data` directly and thats about 2x the speed.

Any idea why its that slow? I know "python is slow" answers some of it, but not _all_ of it.

Any suggestions to improve attribute access? Would upgrading to `3.x` help? I went through the changelog but found nothing specifically about this.

**Comment by coleifer** [comment]
Python is slow. Typically the time spent querying the DB will be the bulk of the time spent in any peewee code path... usually orders of magnitude. If attribute access is hurting you, use the tuples method on the query to have the cursor return tuples instead of model instances.
