### ISSUE TITLE
sqlite3 random rows by seed

### ISSUE THREAD

**Issue by nisanb** [coleifer/peewee#2157]
With using Python, my tool has a randomized seed for each run.
Upon placing the same seed, I would like to receive the same randomized results.

I tried externally-implementing it, but that causes performance degradation for two reasons:
1. I need to build a list out of ModelSelect objects
2. I need to return all rows for a given where() query, even if I know I only need 5 randomized out of them.

The overhead is a pain and the performance penalty is high.

Could peewee provide an interface as such?
Or, is there a better way of doing it, other than what I tried?

**Comment by coleifer** [comment]
Sqlite allows you to write arbitrary user-defined functions. There are examples:

http://docs.peewee-orm.com/en/latest/peewee/database.html#sqlite-user-functions
