### ISSUE TITLE
How Update the required array in the database column (Integer)

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2158]
```
await db.execute(MarriagePlayer.update({
            MarriagePlayer.statistics[0]: MarriagePlayer.statistics[0] + 1
        }).where(
            MarriagePlayer.chat_id == msg.receiver_id,
            MarriagePlayer.user_id << [msg.sender_id, p.loved]))
```

i try to update 0 array in column but i get error

> MarriagePlayer.statistics[0]: MarriagePlayer.statistics[0] + 1
> 
> TypeError: unhashable type: 'ObjectSlice'

how i can update it witzhou error?

**Comment by coleifer** [comment]
Released in 3.13.3 https://github.com/coleifer/peewee/releases/tag/3.13.3
