### ISSUE TITLE
[Question] How to add new value for ArrayField table

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2163]
Hi, how i can add new value for arrayfield column? I try thet

`await db.execute(MarriagePlayer.update({MarriagePlayer.woman_childrens: MarriagePlayer.woman_childrens.append(1)}))`

But its not working(, i don't see  in documentation thet funcion

**Comment by coleifer** [comment]
Read the postgresql array docs: https://www.postgresql.org/docs/9.1/arrays.html

You can use the concatenation operator, though it's pretty "fragile" and may complain about operators, in which case you'll need to use casts.
