### ISSUE TITLE
[Question] How to remove element from ArrayField

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2164]
Hi, I apologize for the large number of questions. How can I remove an item from an ArrayField?

How to add, I seem to have found the function `from peewee import fn`
`fn.array_append ()`

But I did not find how to remove

**Comment by coleifer** [comment]
https://www.postgresql.org/docs/9.3/functions-array.html#ARRAY-FUNCTIONS-TABLE

**Comment by coleifer** [comment]
The issue tracker is not for "how do I..." questions. Ask those on:

* StackOverflow
* IRC
* Mailing list

http://docs.peewee-orm.com/en/latest/peewee/contributing.html#questions
