### ISSUE TITLE
delete_instance is atomic? 

### ISSUE THREAD

**Issue by theruziev** [coleifer/peewee#2165]
is it ok to delete_instance it's not atomic by design or I misunderstood code and documentation?

**Comment by coleifer** [comment]
Transaction management is left up to the user. So if you want atomicity, then wrap your operations in the `atomic()` context manager.

http://docs.peewee-orm.com/en/latest/peewee/database.html#managing-transactions

**Comment by theruziev** [comment]
Thanks for the answer
