### ISSUE TITLE
Support for read slaves

### ISSUE THREAD

**Issue by anil-grexit** [coleifer/peewee#2166]
Hi @coleifer,

I'm using a master-slave(read-only) setup for our MySQL RDS. Currently, there's no straightforward way to specify the database connection on the basis of `SELECT` vs other query types. I stumbled upon your `read_slave` module from playhouse extension v2.10.0 release of peewee. 

Is it possible that I can use the same code to do it myself?

```python
from peewee import *


class ReadSlaveModel(Model):
    @classmethod
    def _get_read_database(cls):
        if not getattr(cls._meta, 'read_slaves', None):
            return cls._meta.database
        current_idx = getattr(cls, '_read_slave_idx', -1)
        cls._read_slave_idx = (current_idx + 1) % len(cls._meta.read_slaves)
        return cls._meta.read_slaves[cls._read_slave_idx]

    @classmethod
    def select(cls, *args, **kwargs):
        query = super(ReadSlaveModel, cls).select(*args, **kwargs)
        query.database = cls._get_read_database()
        return query

    @classmethod
    def raw(cls, *args, **kwargs):
        query = super(ReadSlaveModel, cls).raw(*args, **kwargs)
        if query._sql.lower().startswith('select'):
            query.database = cls._get_read_database()
        return query

```

taken from `https://github.com/coleifer/peewee/blob/2.10.2/playhouse/read_slave.py`

Also, I'd like to know if there are any future plans to bring back the support for read slaves.

**Comment by coleifer** [comment]
The way to do this with Peewee 3 is probably to use the various context-managers:

http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.bind_ctx

You can explicitly set `Query._database` as well on a one-off basis, but that's up to you.

**Comment by anil-grexit** [comment]
Yep, I went with `DB.bind(models)`. Thanks for the response.

**Comment by JishnuRamesh** [comment]
@aniljaiswal 
Stumbled upon this issue while looking for read slaves in peewee. 
may i do not completely comprehend how to use the context manager in here
How does `DB.bind(models)` work if you want to use the same model for both read and write operations, where my reads are executed on slaves and write on master ?

**Comment by aniljaiswal** [comment]
You basically two connections, one for read and other for write. For read connection, you can specify the models to bind to the database.

**Comment by JishnuRamesh** [comment]
Got it. Thanks

**Comment by pylipp** [comment]
I'm still having trouble to understand. I don't want one set of models to be used for reading, and another distinct set of models to be used for writing. I want to use the read-connection when reading from any model, and to use the write-connection when writing to any model.

So I think it comes down to something similar to the original read-slave concept but using db-context switching:

```python
read_db = MySQLDatabase(...)
write_db = MySQLDatabase(...)

class ReadSlaveModel(Model):
    @classmethod
    def select(cls, *args, **kwargs):
        with cls.bind_ctx(read_db):
            return super().select(*args, **kwargs)

class User(ReadSlaveModel):
    name = CharField()
    
    class Meta:
        database = write_db
```
