### ISSUE TITLE
DecimalField wizhout max_digits

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2167]
Why can not you specify max_digits, etc. In ordinary PhpPgadmin, this can be done and the column is simply called numeric without max_digits, etc.

**Comment by daeeros** [comment]
![image](https://user-images.githubusercontent.com/34482855/81095923-5c5af380-8f0e-11ea-8a0b-c5e2ea562671.png)

**Comment by coleifer** [comment]
Peewee requires that you be explicit w/the decimal field. If you dislike this functionality, then you can subclass it and override the `get_modifiers()` method.

```python

class NumericField(DecimalField):
    def get_modifiers(self):
           pass
```
