### ISSUE TITLE
Join fails on Python3.8

### ISSUE THREAD

**Issue by ayyazdaniaryan** [coleifer/peewee#2169]
Hello,

I've recently used `peewee` for a new project, shying away after many years of `SQLAlchemy`. Neat package, works well, is pythonic, and small learning curve. Kudos!

I wanted to see anyone else though has noticed issues on the latest version of Python, 3.8, and peewee. I cannot seem to be able to do a `join` at all. Here's the error:

```
TypeError: 'NoneType' object is not callable
```

Here is how I produced this error:

**Python**: 3.8.2
**OS**: Mac OS X 10.14.6 
**DB**: Postgres 9.6.17
**Driver**: Psycopg2 2.8.5

Simple model structures, and a dead-simple join:

```python
class AAA:
   a = CharField(unique=True, index=True)

class BBB:
   a = CharField(null=False)
   b = ForeignKeyField(AAA, null=False)

class CCC:
   a = ForeignKeyField(AAA, null=False)
   b = ForeignKeyField(BBB, null=False)

entry_a = AAA.create(a="python")
entry_b = BBB.create(a="py", b=entry_a)
entry_c = CCC.create(a=entry_a, b=entry_b)

...

CCC.select(). # This works fine
CCC.select().join(BBB). # Throws the error
CCC.select().join(AAA) # Throws the error
```

My workaround for this was to downgrade my venv to Python3.7, and it's happy days. But it appears that Py3.8 has breaking changes for this package. Let me know if I'm doing something wrong, or if it's a known issue.

**Comment by coleifer** [comment]
Your example code obviously won't run, as your classes do not extend `Model`. Neither can I tell why you are including a trailing "." after your CCC.select() and CCC.select().join(BBB).

I just ran the following code without any issues on Python 3.8.0:

```python

db = PostgresqlDatabase('peewee_test')

class BaseModel(Model):
    class Meta:
        database = db

class A(BaseModel):
    a = CharField(unique=True)

class B(BaseModel):
    a = CharField()
    b = ForeignKeyField(A)

class C(BaseModel):
    a = ForeignKeyField(A)
    b = ForeignKeyField(B)

db.create_tables([A, B, C])
a = A.create(a='1')
b = B.create(a='2', b=a)
C.create(a=a, b=b)

q1 = C.select().join(B)
list(q1)
q2 = C.select().join(A)
list(q1)
db.drop_tables([A, B, C])
```
