### ISSUE TITLE
BitField variable name not accepting any name other than "flags"

### ISSUE THREAD

**Issue by nisanb** [coleifer/peewee#2173]
Hi,
Given your example:
```
class Post(Model):
    content = TextField()
    flags = BitField()

    is_favorite = flags.flag(1)
    is_sticky = flags.flag(2)
    is_minimized = flags.flag(4)
    is_deleted = flags.flag(8)

```

When changing "flags" variable to any other variable, the fields are effectively not being saved in the database.

When querying to see the data, it always returns 0.

**Comment by coleifer** [comment]
I don't see any such regression: 06c283159fa9917fda8836e2b2973fd38da0a029
