### ISSUE TITLE
Reflection does not identify primary keys

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2174]
It seems that `generate_models` does not identify when a field is the primary key. Instead it creates a composite primary key with all the fields in the model.

**Comment by coleifer** [comment]
If you can create a reproducible test-case I would be happy to investigate. As it is, the reflection module is already tested and I can assure you that it is not as fundamentally broken as all that.

https://github.com/coleifer/peewee/blob/3b1181a7cf727cc749a5fbb76f96602a3bb3325b/tests/reflection.py#L77-L443

**Comment by albireox** [comment]
Figure it out. The problem is that I was using a user that doesn't own the tables being reflected. The query that retrieves the primary keys uses the view `table_constraints` which, according to Postgresql

> The view table_constraints contains all constraints belonging to tables that the current user owns or has some privilege other than SELECT on.

I'm not sure if there's an alternative way of querying for primary keys that would solve this problem, otherwise reflection will only fully work if the user has write access to the tables being reflected.
