### ISSUE TITLE
MariaDB 5 

### ISSUE THREAD

**Issue by CaffeineLab** [coleifer/peewee#2178]
So I'm using MariaDB 5.?.? and every time I run I get a warning that it's unable to determine the MySQL version....  in the function it appears to only want to identify versions starting with a 1.  Not sure if this is an issue or if it's supposed to be a warning that you are using an old version of MariaDB so it's a bit unclear.  The function is def _extract_server_version(self, version) and the line in question is:

    if 'maria' in version:
        match_obj = re.search(r'(1\d\.\d+\.\d+)', version)

For now, I've removed the 1 from the re and it no longer gives me the warning.

**Comment by coleifer** [comment]
10.0 was released in 2012... So are you using an 8+ year old version of MariaDB?

You can also suppress warnings if that's your preference: https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings

**Comment by CaffeineLab** [comment]
Yes.  And I'm not happy about it either :)  So at this point, my opinion (and I am probably the only one with it) is that I think your warning is inaccurate and it should thereby be fixed because the MariaDB version **is** known .... it's just seriously outdated and shouldn't be used.  Oh - and the reason for it being old is it is what was shipped on the Synology DiskStation and I'm just using it temporarily so don't judge me too harshly.
