### ISSUE TITLE
Question. Migrations maker

### ISSUE THREAD

**Issue by mrkovalchuk** [coleifer/peewee#2180]
Peewee it's enough popular python ORM library. Have the migrations system. But he hasn't instrument for auto make migrations. Like in django, or Alimbic for SQLAlchemy.

Is any work in this direction? https://pypi.org/project/peewee-migrations/ - like this (but more life full)

**Comment by coleifer** [comment]
Peewee has a very easy-to-use migrations helper that you can use to modify your schema. At the time of writing, an automatic "detect changes and generate migrations" tool is not part of Peewee and likely will not be added at any time. Such tools carry a very large maintenance burden and are buggy, and bugs can have disastrous effects on your db if you aren't careful. I prefer explicit migrations, and Peewee supports that.

You're welcome to use a 3rd party tool, but I can't vouch for any of them, not having used them myself.
