### ISSUE TITLE
Postgres TimeFields with timezones

### ISSUE THREAD

**Issue by BryceBeagle** [coleifer/peewee#2186]
`DateTimeField` has a timezone-based subclass in `postgres_ext.DateTimeTZField`. Is there a reason why there's no analog for `TimeField` (i.e. `TimeTZField`)?

**Comment by BryceBeagle** [comment]
Also related, the [docs](https://github.com/coleifer/peewee/blame/master/docs/peewee/playhouse.rst#L688) mention (and try linking to) `DateTimeTZ` (as opposed to `DateTimeTZField`) resulting in a broken link

**Comment by coleifer** [comment]
How can a time have a timezone, when the time's value is dependent on the date it's attached to? At any rate, you can subclass `TimeField` and provide your own field-type. Creating field types is super easy, especially when they are derived from existing field.

Thanks for the note about the docs, I've fixed it.

**Comment by BryceBeagle** [comment]
Postgres has a [datatype that's just a time](https://www.postgresql.org/docs/current/datatype-datetime.html) (no date) with a timezone. This makes sense because I can say "7PM EST" and convert it to UTC without ever needing to get a date involved.

I understand if you don't want to add it, and can go with the custom field, but to me it seems strange to have first class support for the `timestamp with time zone` datatype but not the `time with time zone` one.
