### ISSUE TITLE
any plan to support async/await

### ISSUE THREAD

**Issue by DieterLi** [coleifer/peewee#2189]
as the title. Thanks, team

**Comment by coleifer** [comment]
Discussed and dismissed many times, notably #263. There are so many things I dislike about the ~twisted~ asyncio approach, mostly the fact that you have to write "asyncio"-specific everything -- drivers, ORMs, application frameworks, etc., etc. and even then you still have a "[what color is my function](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/)" situation.

Use gevent. Seriously. You can thank me later.

**Comment by Fingel** [comment]
This is really too bad. With async web frameworks becoming more and more prevalent, it would have been nice to have an alternative to SqlAlchemy. But with SqlAlchemy 2.0 just around the corner, and this project's author continuing to dismiss and suggestion of adopting python3 async, it doesn't look like it's going to happen.

For anyone else searching as I was, [Tortoise ORM](https://github.com/tortoise/tortoise-orm) looks promising but is lacking many features at this point.

**Comment by coleifer** [comment]
A commenter suggested [tortoise orm](https://tortoise-orm.readthedocs.io/en/latest/) - I cannot vouch for it, but wanted to preserve the recommendation for anyone who arrives here via google.

**Comment by klen** [comment]
@coleifer it's very sad that you ignore the `async/await` syntax. A lot of people/products use it these days and it's not only about `asyncio`. I know about the tortoise ORM, but I prefer Peewee syntax.

Maybe we have a chance to split the Peewee ORM and make a code that working with DB connections independently. So there will be drivers independent Peewee part which one only is responsible for the conversation Models <-> SQL and another part that implement database connection management. That way people could be available to use Peewee with any sync/async drivers.

**Comment by klen** [comment]
As an alternative, there is another library: https://github.com/klen/peewee-aio

**Comment by willianantunes** [comment]
If you came here, the I suggest:

https://charlesleifer.com/blog/asyncio/

**Comment by coleifer** [comment]
I'm thinking about *possibly* something like Mike Bayer's (@zzzeek) sweet greenlet trick from sqlalchemy. I've been prototyping a baby bit and am still wrapping my head around what changes will be needed and where the fault lines will lie.

**Comment by coleifer** [comment]
We've got some new, experimental asyncio support in the master branch if you want to take a look. Docs here: http://docs.peewee-orm.com/en/latest/peewee/asyncio.html
