### ISSUE TITLE
Postgresql materialized views not showing

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2198]
It seems Postgresql materialized views are not seen as a table or a view in Peewee. I have a model of a materialized view that works fine otherwise but `Model.table_exists()` returns `False`. If I try to find it in `database.get_tables()` or `database.get_views()` it does not appears anywhere. Is there a way to check if a materialized view model actually exists?

**Comment by coleifer** [comment]
First result on google my dude.

https://stackoverflow.com/questions/58720894/check-a-materialized-view-exists

**Comment by albireox** [comment]
I know how to use the `pg_class` table, "my dude", I was asking if this can be do directly in Peewee using its API. I won't be opening any more issues trying to improve Peewee since there doesn't seem to be an interest for it.
