### ISSUE TITLE
model to dict extra_attrs

### ISSUE THREAD

**Issue by JPilarr** [coleifer/peewee#2202]
Hello,
i have model like.
```
class Printer(pw.Model, ch.Model):
    # DB fields
    id = pw.AutoField(primary_key=True)
    name = pw.CharField()

    # cache field stored in redis
    state = ch.CharField(default=State.OFFLINE.name)
```
i have problem serialize redis part of model by model_to_dict. If i use exclude it work's but  if i use only and after use something like result['state'] = self.state. it doesn't work with error `"TypeError: Object of type CharField is not JSON serializable"`
```

        self.cache_get()
        self.fix_state()

        result = model_to_dict(self, only=[Printer.id, Printer.name,
                                           Printer.location, Printer.state]
                               )
        # from json import load
        result['state'] = self.state

        if self.printer_type_id:
            result['printer_type_id'] = self.printer_type.id

        return result
```

can you help me whats wrong? I dont' want use huge exclude. Is it way how to do it by extra_attrs parameter for model_to_dict.

**Comment by coleifer** [comment]
I'm sorry but I don't understand the question, what these special field subclasses are, or really what the problem is.
