### ISSUE TITLE
How to scrape an img src url?

### ISSUE THREAD

**Issue by xdebbie** [coleifer/peewee#2203]
I'm using peewee to scrape a webpage, and everything is working fine except when I try to get the url of an "img src=" tag. Does anyone know what is the correct syntax to get the url?

My code goes like this:
``` 
    # record label
    label = resp.html.find('.labels-list__item')
    if label:
        data['label'] = label[0].text

    # genre
    genre = resp.html.find('.genre-list__link')
    if genre:
        data['genre'] = genre[0].text

    # artwork
    artwork = resp.html.find('.single-album-tombstone__art img')
    if artwork:
        data['artwork'] = artwork[0].text

```

The # record label and # genre tags work fine, but with the #artwork it returns an "EMPTY" tag on my database. This is the html:

![website](https://i.imgur.com/vzorTL6.png)

How can I insert the attribute 'src' so it will return the actual url of the image?

**Comment by coleifer** [comment]
This is a question about some scraping library you are using. peewee issue tracker is not for questions, much less questions about a completely unrelated and unidentified html library.
