### ISSUE TITLE
Field in query results has ") appended to its name

### ISSUE THREAD

**Issue by zacc** [coleifer/peewee#2212]
Executing this query in Python\:
`Comment.select(Comment.submission_id, Comment.id, fn.Max(Comment.score)).group_by(Comment.submission_id)`

The `.sql()` output of the query is:
`('SELECT "t1"."submission_id", "t1"."id", Max("t1"."score") FROM "comment" AS "t1" GROUP BY "t1"."submission_id"', [])`

Running `print(vars(record))` on the output of the query shows:
`{'__data__': {'submission_id': '7k57rl', 'id': 'drbr3hf'}, '_dirty': set(), '__rel__': {}, 'score")': 37}`

The score field now is labelled `score")`

Working around it with `getattr(record, 'score\")'` for the moment!

The output appears to be correct, though!

The SQL might not be optimum for the case but I thought the bug might be of interest anyway. 
Thank you for the excellent ORM.

**Comment by coleifer** [comment]
You're probably using an older version of Sqlite(?) or otherwise the database is generating a column-name for your MAX value like 'MAX("t1"."score")'. Just specify an alias:

```python
fn.MAX(Comment.score).alias('max_score')
```

Then it will be available as the "max_score" attribute.

**Comment by zacc** [comment]
Sorry yes I should have mentioned SQLite! For your reference I am using 3.22, it has a version tag `3.22.0 2018-01-22 18:45:57` . Regards.
