### ISSUE TITLE
Add UUIDKeyField for postgres

### ISSUE THREAD

**Issue by jet10000** [coleifer/peewee#2214]
I found a UUIDKeyField in cockroachdb, Please add a UUIDKeyField for PostgreSQL, the default value `gen_random_uuid()`.

```
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
```
https://medium.com/@shawnoy/generate-a-uuid-as-postgresql-default-value-fc0ae41a37d2

if extension not exists, reminder to install this extension.

**Comment by coleifer** [comment]
CockroachDB provides this function out-of-the-box. Postgres requires an extension, so it is not provided as a built-in. It is quite easy to add this if you want it, though -- just use the implementation from cockroachdb or create your own subclass.

**Comment by jet10000** [comment]
PostgreSQL 13 
https://www.postgresql.org/docs/13/functions-uuid.html
