### ISSUE TITLE
How to get ridoff double quotes

### ISSUE THREAD

**Issue by wilberh** [coleifer/peewee#2218]
I'm using a database driver that is DB API (PEP-249) v2.0 compliant.  
How can I tell peewee to not add double quotes on everything?
ex:
My base class is inheriting from the Model class.  Whenever I call ItemModel.select() and noticed peewee is adding double quotes.  How can I configure the class Model to not add double quotes.  

Is coming out like:
SELECT "t1"."item1", "t1"."item2", "t1"."item3" FROM "trex_inventory_recipe_material" AS t1

I need it like this: 
SELECT t1.item1, t1.item2, t1.item3 FROM trex_inventory_recipe_material AS t1

**Comment by coleifer** [comment]
Responded to this when you asked on a different issue: https://github.com/coleifer/peewee/issues/2064#issuecomment-654236281

The alternative is to maintain a list of all sql reserved words and only quote words when they happen to collide with a sql keyword, and that seems silly. Quoting identifiers is the best way to handle this. Similarly, I've seen people who use whitespace and all kinds of other unexpected things in their sql identifiers. Quoting ensures that they work in all cases.
