### ISSUE TITLE
Override select()

### ISSUE THREAD

**Issue by wilberh** [coleifer/peewee#2219]
How can I override the select() method from the Model class?  

I need to remove remove the double quotes from the sql strings created by peewee so my DBAPI v2.0 compliant driver database can take it.

**Comment by coleifer** [comment]
Please quit spamming the same question. This is the third time you've posted some variation of this question. Asked and answered.

**Comment by wilberh** [comment]
Apologies; just trying to figure out any other way of removing double quotes.  
I'm using Impyla which is fully DB API v2.0 compiant.  And the HiveServer2 (Hive) gives an error when it sees double quoted coloum-names.
