### ISSUE TITLE
Question: is comma equivalent to & in where clause?

### ISSUE THREAD

**Issue by dsmurrell** [coleifer/peewee#2222]
In this example in the docs: http://docs.peewee-orm.com/en/latest/peewee/querying.html#filtering-records

`.where(Tweet.user == user, Tweet.is_published == True)`

Is this the same as `.where((Tweet.user == user) & (Tweet.is_published == True))` ?

I can't seem to find this comma syntax documented anywhere else.

**Comment by coleifer** [comment]
Yes, multiple expressions passed to `where()` are `AND`-ed together. It's typically cleaner to use parentheses, though, since python operator precedence seems to trip up a lot of people. Forcing the habit of using parentheses helps ensure they don't make a mistake.

**Comment by dsmurrell** [comment]
Great, thanks for clarifying.

**Comment by Calvin-he** [comment]
I think it should have mentioned it in the document this
