### ISSUE TITLE
Removing trailing square-brackets

### ISSUE THREAD

**Issue by wilberh** [coleifer/peewee#2223]
Is there a way of removing the square-brackets from getting added into sql queries?  
I'm getting this sql statement - 

SELECT t1.rname, t1.mrole, t1.rmaterial FROM stg.instruments AS t1 []

**Comment by coleifer** [comment]
You may be confusing the representation of the SQL statement with what actually gets sent to the database.

Those brackets are the representation of an empty list. The list is used to pass parameters to the driver, which handles escaping and all that (note to Always use parameterized queries).
