### ISSUE TITLE
Is there a way to join across databases?

### ISSUE THREAD

**Issue by skjbulcher** [coleifer/peewee#2227]
I have a MySQL server with a number of databases, e.g. `customer`, `dba_company_a`, `dba_company_b`. I need to join across databases to execute queries that include customer information from either dba_company database. I haven't been able to figure out how to do that with peewee.

I've tried using different `Meta` classes indicating it belongs to a different database

```
db = MySQLDatabase('customer')
class Customer(Model):
    id = AutoField()
    ....
    class Meta:
        database = db
```

as well as binding

```
db = MySQLDatabase('customer')
class Customer(Model):
    id = AutoField()
Customer.bind(db)
```

but in either case when I try to perform a join, _(something like `Orders.select(Orders, Customers).join(Customers).select()`, where Orders is a table on dba_company_a/b)_, I get a message like:

```
peewee.ProgrammingError: (1146, "Table 'dba_company_a.customer' doesn't exist")
```

Is there anyway to do joins across databases? Am I missing something simple?

**Comment by coleifer** [comment]
You can use the `Meta.schema` to achieve an extra layer of namespacing.
