### ISSUE TITLE
Drop Constraint Syntax Error in MySQL 8.0.18

### ISSUE THREAD

**Issue by hanxifu** [coleifer/peewee#2228]
Hi,

I'm using `peewee.playhouse.migrate.drop_constraint` to do some migrations on MySQL 8.0.18.
If failed with error message: 
<pre>
`Error in query (1064): Syntax error near 'CONSTRAINT `constraint_name`' at line 1`
</pre>

I've checked the SQL.
This will fail: <pre>ALTER TABLE xxx DROP CONSTRAINTS `XXX`</pre>
This will succeed: <pre>ALTER TABLE xxx DROP FOREIGN KEY `XXX`</pre>

Is there anything peewee can improve? Or configurations in MySQL I ignored?

Thanks for your help!

**Comment by coleifer** [comment]
For MySQL you would use the `drop_foreign_key_constraint` migrator method.

**Comment by hanxifu** [comment]
I couldn't find it in peewee's documentation. Maybe could add it later. Thanks!

**Comment by sanjok-bless** [comment]
Oh, it's spent a lot of time to find `drop_foreign_key_constraint` method... It will be very usefull to add it to the docs.
