### ISSUE TITLE
How to handle 'Duplicate entry' warnings when using `on_conflict_ignore()`?

### ISSUE THREAD

**Issue by SilentGene** [coleifer/peewee#2229]
Hello, when using `insert.on_conflict_ignore().execute()` method to insert new entries, there are always warnings shown as below:
```bash
C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\pymysql\cursors.py:170: Warning: (1062, "Duplicate entry 'http://link.aps.org/doi/10.1103/RevModPhys.90.015006' for key 'IX_link'")
  result = self._query(query)
```
Could I know how to hide or filter out these warnings?

**Comment by coleifer** [comment]
The warning is not raised by peewee. The warning is not generated by pymysql. The warning is coming directly from the sql database.

For general information about warnings, check here:

https://docs.python.org/3/library/warnings.html#module-warnings

Next time please spend more time looking into it before just immediately opening an issue.

**Comment by SilentGene** [comment]
Thank you @coleifer . I have been struggling for this issue for some time, but didn't know this is coming from SQL database with my little experience in SQL.  I thought this originated from pymysql or peewee, so I've spent much time looking for solutions there.

With your suggestion, now I have successfully used the following code to suppress the warnings:
```python
import warnings

def save_entries(d):
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', '.*Duplicate entry.*IX_link.*')
 
        with mysql_db.atomic():
                PaperInfo.insert_many(d).on_conflict_ignore().execute()
```

Thanks again for your time.
