### ISSUE TITLE
passing custom/additonal metadata

### ISSUE THREAD

**Issue by wilberh** [coleifer/peewee#2230]
Is there any way to pass additional metada when creating a table (in class Meta or some other way)?  
Meaning, adding additional information after table creation section - see bold section below.

Example: 

CREATE TABLE testing (
name VARCHAR
)
**COMMENT 'This is an internal table' 
ROW FORMAT DELIMITED 
NULL DEFINED AS '' 
STORED AS AVRO**

**Comment by coleifer** [comment]
No this is not supported
