### ISSUE TITLE
Unable to pass database parameter to mysql-connector-python through peewee

### ISSUE THREAD

**Issue by dshefman1** [coleifer/peewee#2231]
The database parameter 'tls_versions' does not appear to be getting passed through to mysql-connector-python. The [documentation ](http://docs.peewee-orm.com/en/latest/peewee/database.html#initializing-a-database) says, "Subsequent keyword arguments are passed to the underlying database driver when establishing the connection, allowing you to pass vendor-specific parameters easily". This does not appear to be the behavior I am witnessing when I pass the "tls_versions" parameter through peewee to mysql-connector-python.

When I connect directly with mysql-connector-python using the code below, I am able to connect successfully:

```
import mysql.connector

config = {'database': 'dbname',
 'user': 'username_so',
 'password': 'psswrd',
 'host': 'maria####-##-###-##.###.####.com',
 'port': 3307,
 'tls_versions': ['TLSv1.1', 'TLSv1.2']}

cnx = mysql.connector.connect(**config)

print(cnx.is_connected())
cnx.close()
```
Output:
> True

However, when I pass in the same configuration to peewee.MySQLDatabase() then I get an error message:

```
db = MySQLDatabase(**config)

db.get_tables() # This function and any other that connects to the db returns the same error message specified below
```
Error Message:

> ImproperlyConfigured: MySQL driver not installed!

I am pretty sure that the problem is with specifying the tls versions in peewee because I was getting the same error message with mysql.connector before I added in the additional 'tls_versions' parameter. Also, I get the same error message with peewee if I do not include the 'tls_versions' parameter at all.

My Setup:
Linux
Python 3.7
peewee==3.13.3
mysql-connector-python==8.0.21

**Comment by coleifer** [comment]
You need to use `playhouse.mysql_ext.MySQLConnectorDatabase` to connect using the mysql-connector driver. That will resolve your issue.
