### ISSUE TITLE
Using bitwise (&|~)in a query

### ISSUE THREAD

**Issue by TaceyWong** [coleifer/peewee#2239]
IN http://docs.peewee-orm.com/en/latest/peewee/query_operators.html

.bin_and(value) -> Binary AND

.bin_or(value) ->  Binary OR

but,I can not find the replace of Binary NOT .How can I write a peewee-style c=a&(~b)?

**Comment by coleifer** [comment]
Since it's a unary operator, you can probably get it working with something like:

```python

def bin_not(value):
    return NodeList((SQL('~'), value))
```
