### ISSUE TITLE
SQLite database generates GLOB for %, however GLOB is not LIKE…

### ISSUE THREAD

**Issue by zx80** [coleifer/peewee#2240]
The documentation says that `%` stands for `LIKE` in query expressions, but the traces shows a `GLOB` instead with SQLite, hoewever the regexp syntax is not the same between the two operators, eg `LIKE 'h%'` is `GLOB 'h*'`.

Version affected: *3.13.3*

Code:

```Python
    res = Store.select().where(Store.key % PARAMS['filter']).order_by(Store.key)
```

Trace:

    INFO:root:db = <peewee.SqliteDatabase object at 0x7ffac44c0c10>
    DEBUG:peewee:('SELECT "t1"."key", "t1"."val" FROM "store" AS "t1" WHERE ("t1"."key" GLOB ?) ORDER BY "t1"."key"', ['%h'])

In the [source](https://github.com/coleifer/peewee/blob/master/peewee.py) on line 3347:

```Python
    operations = { 'LIKE': 'GLOB', 'ILIKE': 'LIKE' }
```

Indeed, SQLite `LIKE` is case insensitive, however `GLOB` is not `LIKE` at all. ISTM that it would be more helpful to generate a not implemented exception than switching to another operator which breaks the portability.

**Comment by coleifer** [comment]
This has been this way for many years and I've no plans to change it. I do understand that it may have been confusing.

**Comment by zx80** [comment]
Hmmm… Indeed it is pretty confusing.

**Comment by coleifer** [comment]
![s1597080267 5538623](https://user-images.githubusercontent.com/119974/89811582-7fe09c00-db04-11ea-9d0f-d01e1900180d.png)
