### ISSUE TITLE
doc website seems to be hacked

### ISSUE THREAD

**Issue by azs0309** [coleifer/peewee#2245]
The document website http://docs.peewee-orm.com/en/3.6.0/peewee/quickstart.html seems to be hacked and whenever I click a link pointing me to fryruejoust.cam

**Comment by coleifer** [comment]
It seems to be working fine for me. This is the output of `curl http://docs.peewee-orm.com/en/3.6.0/peewee/quickstart.html`:

https://gist.github.com/coleifer/d6450e6d5bdcb4460cd6bbf36b8dcb4c
