### ISSUE TITLE
Custom SQL

### ISSUE THREAD

**Issue by mauriciobaeza** [coleifer/peewee#2253]
Hello...

Who to change?

    SELECT "t1"."id", "t1"."text" FROM "fields" AS "t1" WHERE ("t1"."id" = 1) LIMIT 1

For:

    SELECT FIRST 1 "t1"."id", "t1"."text" FROM "fields" AS "t1" WHERE ("t1"."id" = 1)

Thanks

**Comment by coleifer** [comment]
That syntax is not currently supported out of the box. I'd suggest looking at the query builder internals.

If you have more questions feel free to ask on the mailing list or #peewee on freenode and I'll try to help.

**Comment by mauriciobaeza** [comment]
ok, thanks.
