### ISSUE TITLE
Is it possible to modify the columns for a TableFunction in SQLite at runtime?

### ISSUE THREAD

**Issue by pacuna** [coleifer/peewee#2258]
I'm trying to create a table function that generates columns depending on the input. For example if the input is `("a", 1, "b", 2)` it should generate columns **a** and **b** with values **1** and **2**.  My code is working but I have to hardcode the columns in the class variable `columns` and I can't modify it after. Is there a way to accomplish this?

Thanks.

**Comment by coleifer** [comment]
Not really, look at the docs for the sqlite virtual table interface if you're curious how it works:

https://sqlite.org/vtab.html

The virtual table, when registered, has to declare it's structure.
