### ISSUE TITLE
Limit on backrefs ?

### ISSUE THREAD

**Issue by hrishikeshrt** [coleifer/peewee#2264]
When using `model_to_dict on` a model with possibly a large number of `backrefs`, could there be an argument to `model_to_dict` which limits the number of entries in any back reference to the given value? (or any alternate way to achieve the same.

**Comment by coleifer** [comment]
Just define which models or foreign-keys to exclude and they won't be traversed. Alternatively, you can explicitly implement your serialization strategy.

**Comment by coleifer** [comment]
Oh wait, I think I understand now -- no, this is something you will probably want to implement in a custom serializer if you want to control how the back-references are also queried.

**Comment by hrishikeshrt** [comment]
Alright, thank you.
I am currently doing it as follows,

`occurrences` is my `backref`

```
    results = []
    for _result in _results:
        result = model_to_dict(_result)
        result['occurences'] = [
            model_to_dict(occurence, backrefs=True)
            for occurence in _result.occurences.limit(limit)
        ]
        results.append(result)
```

I suppose this is the proper / (only?) way then?

**Comment by coleifer** [comment]
That's perfectly fine way, and what I would probably do as well. The next step up would be a dedicated serialization library.
