### ISSUE TITLE
Support Meta inheritance

### ISSUE THREAD

**Issue by jonashaag** [coleifer/peewee#2266]
Would be nice if this worked:

```py
class DefaultMeta:
    database = db
    ...

class Foo(Model):
    ...

    class Meta(DefaultMeta):
        ...
```

Right now it silently ignores the `DefaultMeta` fields.

**Comment by coleifer** [comment]
The meta class is a weird kind of a hack inspired by similar deal in Django. The meta class is not what gets inherited, but instead the "inheritable" settings of the Meta class are inherited by the model.

Ex:

```python

class BaseModel(Model):
    class Meta:
        database = db

class Foo(BaseModel):
    class Meta:
        table_name = 'foo_tbl'
        # "database" setting is inherited from BaseModel.
```

This is described in the documentation for model options and table metadata:

http://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata

**Comment by jonashaag** [comment]
OK, that works for me, but it's different from Django. /
