### ISSUE TITLE
Request: Option to disable numbered table name aliases (t1, t2, t3... etc)

### ISSUE THREAD

**Issue by ibushong** [coleifer/peewee#2271]
Is it possible to add an option to disable the automatic mapping of table names to numbered aliases? When debugging/reading raw queries, it's much easier to read something like ``WHERE (`mytable`.`name` == 'foo')`` instead of ``WHERE (`t3`.`name` == 'foo')``

quick hack:
```python
class AliasManager(object):
    ...
    def add(self, source):
        if source not in self.mapping:
            self._counter += 1
            # ORIGINAL self[source] = 't%d' % self._counter
            self[source] = source.__name__
        return self.mapping[source]
```

The only side effect of this (in my application at least, which is by no means exhaustive) is that I have to add an explicit alias for any uses of `Table.alias()`, e.g. `Table.alias('mytable_alias'`) (which I think is probably a good practice anyway).

**Comment by coleifer** [comment]
I don't have any plans to add such, but you are welcome to write a monkey-patch for AliasManager.add and maintain it separately for your own debugging purposes.
