### ISSUE TITLE
Documentation - Example of `choices` parameter.

### ISSUE THREAD

**Issue by LayneSadler** [coleifer/peewee#2274]
Hey there. Thank you for the simple ORM! It's ideal for a pypi package I am building that has no django/flask gui.

Do have an example of `choices=[(),()]` that could be added to the docs? It is not clear to me.

```
choices (list) – An iterable of 2-tuples mapping column values to display labels.
http://docs.peewee-orm.com/en/latest/peewee/api.html#fields
```

I swear I saw an example of this somewhere, but looking back through the ReadTheDocs and the `/examples` folder on GitHub I cannot find it.

**Comment by coleifer** [comment]
That's not the correct way. An iterable of 2-tuples looks like this:

```python
[('key1', 'Label 1'), ('key2', 'Label 2')]
```
