### ISSUE TITLE
on_conflict support in bulk_create

### ISSUE THREAD

**Issue by AntonioL** [coleifer/peewee#2275]
Please provide mechanism to ignore conflicts when calling bulk_create.

My target database is PostgreSQL.

At th moment I am handrolling my own query.

**Comment by coleifer** [comment]
I'm going to pass on implementing this as part of `bulk_create()` since this can be easily handled by:

```python
Model.insert_many([....]).on_conflict_ignore()
```

The problem arises w/postgres where the insert cursor returns IDs only for the rows that are created, which can't be mapped back to the actual objects that were inserted.
