### ISSUE TITLE
delete().execute() on model object deletes all records from the table.

### ISSUE THREAD

**Issue by p1v2** [coleifer/peewee#2277]
Hey. Recently I ran into issue, when accidentally dropping all records from the table.

if we have:
```
from peewee import Model

class Entity(Model):
    # fields list
    pass

# entity is single record from DB
entity = Entity.select()[0]

# entity delete is query that deletes all records in table
# next code line returns:
# ('DELETE FROM "entity"', [])
entity.delete().sql()

# And this code will actually do delete
entity.delete().execute()
# woop, no more any entity in DB
```

Any chance to change it, that delete method will delete single record.
This feels much more obvious.
Also Django-ORM does delete single record, when you call delete on single model object.

**Comment by coleifer** [comment]
To delete a single model instance, you should use `.delete_instance()`.

The documentation covers this in detail: http://docs.peewee-orm.com/en/latest/peewee/querying.html#deleting-records

**Comment by yongbo** [comment]
I got the same issue.  This is a terrible design.

**Comment by coleifer** [comment]
Yeah it’s a tricky one. Our query-building apis use method chaining based on the sql verb so select/insert/update/delete… maybe the best thing to do is raise if you call delete() on an instance as opposed to a class? I’m open to suggestions.
