### ISSUE TITLE
JSON/dict integer keys getting converted to strings when read.

### ISSUE THREAD

**Issue by pydatasci-repos** [coleifer/peewee#2282]
Here, I have provided a dictionary with integer-based keys `{0:_,1:_,2:_}` to a `JSONField()` attribute named 'folds'.

When I create the object and return it, the folds attribute still serializes with integer keys as expected.

However, when I fetch the object using `get_by_id()`, the `folds.keys()` are now strings. 

Is this expected behavior? Maybe a json.loads or python dict problem rather than a peewee problem, but I just wanted to report it so it's known.

![image](https://user-images.githubusercontent.com/71051965/96254397-3ccafb00-0f83-11eb-81d4-006f75aa70b8.png)

**Comment by pydatasci-repos** [comment]
Makes me think of this:
![image](https://user-images.githubusercontent.com/71051965/96255136-6a647400-0f84-11eb-9590-7d7185976284.png)

**Comment by coleifer** [comment]
What database are you using? Postgres, Sqlite or MySQL?

**Comment by pydatasci-repos** [comment]
@coleifer Sqlite
```
from playhouse.sqlite_ext import SqliteExtDatabase, JSONField
```

**Comment by coleifer** [comment]
I think this comes down to sqlite interpreting object keys as strings. I'd suggest following it up on the sqlite forums if you have more questions on it. https://sqlite.org/forum/forummain

```
sqlite> select json_valid('{1: "k1"}');
0
sqlite> select json_valid('{"1": "k1"}');
1
```

**Comment by pydatasci-repos** [comment]
@coleifer Thanks for taking a look. Your `json_valid` test got me on the right track. There are several posts out there pointing to the JSON spec saying that keys must be strings. E.g. https://stackoverflow.com/a/8758771/5739514

Let's see what the sqlite folks say. Surprised it allows it to be stored.
https://sqlite.org/forum/forumpost/28863dcedf

Taking a look at MongoDB, they use a lot of this syntax:
```
{
    "_id": 1,
    "name": "etc..."
}
```

**Comment by pydatasci-repos** [comment]
Workaround for future humans
```
folds = {"folds": [{"id":1, "name":"a"}, {"id":2, "name":"b"}]}
```
Kinda stinks but at least the inner list can be accessed via index in python. `Foldset.folds["folds"][0]`
