### ISSUE TITLE
peewee AttributeError 'datetime.datetime' object has no attribute 'get_sort_key'

### ISSUE THREAD

**Issue by hungter007** [coleifer/peewee#2287]
peewee version: 3.13.3
python version: py3.8

error：
![image](https://user-images.githubusercontent.com/32872324/97285859-b9ac7d80-187d-11eb-93aa-1bafec0024ca.png)

model:
    add_dt = peewee.DateTimeField(null=False, default=datetime_now, column_name="c_add_dt")

**Comment by coleifer** [comment]
I don't have enough information to help debug this. Can you provide the query?

**Comment by hungter007** [comment]
('INSERT INTO `t_group` (`c_id`, `c_group_name`, `c_group_code`, `c_doc_ids`, `c_company_id`, `c_is_delete`, `c_add_by`, `c_add_dt`, `c_update_dt`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)', ['185ede639b654695869c87b28d31b28d', 'data', '02', '', 'cdf49474297c4454aa2d410ba5eacf60', False, 'user_id', datetime.datetime(2020, 10, 27, 19, 2, 35, 675031), datetime.datetime(2020, 10, 27, 19, 2, 35, 675045)])

**Comment by hungter007** [comment]
when running insert_many get error.

await db_manager.execute(
     Group.insert_many(group_list)
)

**Comment by coleifer** [comment]
This looks like possibly a issue with peewee async? If you can provide a reproducible test that fails I will look into this some more, but `insert_many()` and all this is covered by existing (passing) tests, so I don't think there is anything fundamentally broken here.
