### ISSUE TITLE
Peewee constantly reruns select count in PyCharm REPL

### ISSUE THREAD

**Issue by dominusmi** [coleifer/peewee#2290]
In the pycharm REPL, once a database model is imported, it will keep running a select count after each instruction execution.
Putting the logger on debug mode, this message appears for each model loaded:

```DEBUG::peewee.py:3087::('SELECT COUNT(1) FROM (SELECT 1 FROM `Model` AS `t1`) AS `_wrapped`', [])```

The problem is that my model are very large database, and so the REPL becomes unuseable since after each instruction it stays stuck for a few seconds.
Unfortunately the line number in the log line seems to be wrong (no idea why) but it points to a line with no logging: 
https://github.com/coleifer/peewee/blob/92494cd9ed01b12826b2fddb25cde221ea34f155/peewee.py#L3087
However, since the only line with `logger.debug` in `peewee.py` is line 3117 (inside `execute_sql`), I would imagine it's an implicit call leading there.

I'm not sure if this is a bug or if it's a required decision, but I wouldn't really understand the necessity in the latter case.
Running peewee version `3.13.3`
The same issue doesn't seem to happen in ipython opened from terminal.
Do you have any idea / help for what's going on?

**Comment by coleifer** [comment]
Pycharm is probably calling all kinds of stuff. Specifically it's probably evaluating the truthiness or len(). Definitely not a peewee bug. I'd take it up with the pycharm folks.

Using a regular python repl or ipython has no problems at all.

**Comment by dominusmi** [comment]
Alright thanks for the feedback!

**Comment by whisust** [comment]
Bumping this one again to see if you got feedback, turning on the debug logger shows the queries:

![Capture d’écran 2024-02-18 à 18 36 09](https://github.com/coleifer/peewee/assets/22323709/80d42ae4-acf5-4c9d-a073-f4c495232861)

There are two for each model inherinting from `peewee.BaseModel` at each REPL evaluation.
Is there a workaround / setting to avoid this behavior?

**Comment by coleifer** [comment]
You can try overriding `Model.__len__` and see if that helps at all?

e.g.

```python
class BaseModel(Model):
    class Meta:
        database = my_db

    def __len__(self):
        return 1
```
