### ISSUE TITLE
'Expression' object has no attribute 'seconds'

### ISSUE THREAD

**Issue by ahvahsky2008** [coleifer/peewee#2291]
I try get data with creation time more 60 mins.  But its show error 
```
 hour = datetime.datetime.now() - datetime.timedelta(minutes = 60)
 zayavkis =Zayavki.select().where(Zayavki.req_data-hour).seconds/60>60)
```

**Comment by coleifer** [comment]
You're overthinking this. It is quite simple:

```python

cutoff = datetime.datetime.now() - datetime.timedelta(minutes=60)
query = Zayavki.select().where(Zayavki.req_data >= cutoff)
```

As to why this doesn't work, you cannot access the ".seconds" attribute on a peewee expression, as the error clearly states. This is because it's not a `timedelta` object, but rather a representation of a SQL expression.
