### ISSUE TITLE
Select by tuple in values

### ISSUE THREAD

**Issue by ak04nv** [coleifer/peewee#2297]
Hi there!
I haven't found in the docs (maybe missed, sorry). Is it possible to make a query like this:

```sql
select * from table where (field1, field2) in (('a', 'b'), ('a', 'c'), ('b', 'c'));
```
Thanks a lot for the greatest library!
p.s. Waiting for `asyncio` support out of the box, don't suggest please this [project](https://github.com/05bit/peewee-async) :smile:

**Comment by coleifer** [comment]
See: http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#row-values
