### ISSUE TITLE
Support "on_conflict" in bulk_create

### ISSUE THREAD

**Issue by albatros69** [coleifer/peewee#2298]
Hello,

I was trying to take advantage of `bulk_create` (and its batch-support) to insert a lot of new objects. However, unlike `insert_many`, I didn't find a way to specify the `on_conflict` behavior to handle duplicate key errors.
Would this be a possible feature to add?

**Comment by coleifer** [comment]
This came up recently and it is not something I plan to support. See:

https://github.com/coleifer/peewee/issues/2275

**Comment by albatros69** [comment]
OK, thanks anyway for the answer and support and sorry to have overlooked the existing issue (only looked for the opened ones, I admit).

**Comment by coleifer** [comment]
No problem. Like I said in the last issue, the problem is we have no way to map the "successful" IDs to the corresponding instances because of how postgres returns the data.
