### ISSUE TITLE
Does peewee currently support json fields?

### ISSUE THREAD

**Issue by zhenzi0322** [coleifer/peewee#2307]
Does peewee currently support json fields?

**Comment by coleifer** [comment]
Read the manual

* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#pgjson
* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#mysql-ext
* http://docs.peewee-orm.com/en/latest/peewee/sqlite_ext.html#sqlite-json1
