### ISSUE TITLE
MySQL ([Errno 111] Connection refused) running inside Docker

### ISSUE THREAD

**Issue by sriveros95** [coleifer/peewee#2313]
Hello and thanks for the amazing work.

I'm trying to use Peewee inside Docker but I keep receiving `peewee.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")`

DB name, user, port host are all correct (I'm using 127.0.0.1 as host). 

I don't think the problem is MariaDB's bind-address as I'm able to connect to the DB from other docker containers running GoLang. 

Any idea? 

Running Python 3.7.9, peewee 3.14.0

**Comment by coleifer** [comment]
The error indicates that you cannot connect to the server, so I completely fail to see how this is a peewee issue. Probably some docker networking issue on your end.

Can you connect to the mysql server using the mysql cli on the same host as the code is running? That'd be the best place to start debugging. But yeah -- this does not sound at all like a peewee bug to me. You might also try asking of stackoverflow if you need help debugging your docker configs.

**Comment by sriveros95** [comment]
Yeah tried with just pymysql and still erroring, sorry for the trouble, thank you @coleifer !
