### ISSUE TITLE
Model dependencies list with auto-id field and relations

### ISSUE THREAD

**Issue by mrkovalchuk** [coleifer/peewee#2314]
Good day.

Model.dependencies method bring some exception for me. 

Python 3.7
Peewee 3.14.0

Example:

```python
from peewee import Model, CharField, ForeignKeyField


class A(Model):
    text = CharField()


class B(Model):
    a = ForeignKeyField(A, backref='bbbs')


list(A().dependencies())
```

Error:
```
Traceback (most recent call last):
  File "/some-path/some-project/models/tmp.py", line 12, in <module>
    list(A().dependencies())
  File "/some-path/Envs/some-project/lib/python3.7/site-packages/peewee.py", line 6528, in dependencies
    node = (fk == self.__data__[fk.rel_field.name])
KeyError: 'id'
```

What happens: `A()` object doesn't have a value for ID field. And `Model().__data__` don't return this field. Looks like a bug.

Right now, I don't know, what way we should choose for resolve this issue. I'd be happy to create PR with fix, after talk about solution. 

Thanks.

**Comment by coleifer** [comment]
An un-saved model, by definition, will not have any dependencies -- so this does not strike me as a bug.
