### ISSUE TITLE
When a where clause query has any param as None, the query errors at _escape_like_expr

### ISSUE THREAD

**Issue by bsodhi** [coleifer/peewee#2317]
When the params (such the `dept_name, org_id, fname, lname, role` in the following example) are `None`, then the queries like the following (see failing code below) are failing with the error shown next. This code used to work prior to upgrading to 3.14.0 version of peewee.

Though it looks a bit ugly, for now I'm thinking to perform the None checks prior to the failing query statement. However, I would like to seek your suggestions on how to fix it properly.

Thanks in advance!

**Failing code in application:**
```
dept_name, org_id, fname, lname, role = ... 
query = query.where(
            ((dept_name is None) | (Person.dept_name.contains(dept_name)))
            &
            ((org_id is None) | (Person.org_id.contains(org_id)))
            &
            ((role is None) | (User.role == role))
            &
            ((fname is None) | (User.first_name.contains(fname)))
            &
            ((lname is None) | (User.last_name.contains(lname)))
        ).order_by(-User.id)
```

**Error details:**
```
File "/Users/MyUser/.venv/APPS/lib/python3.8/site-packages/peewee.py", line 1190, in _escape_like_expr
    if s.find('_') >= 0 or s.find('%') >= 0 or s.find('\\') >= 0:
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by coleifer** [comment]
Peewee doesn't support "<x is None>" expressions, for starters. This may have worked in previous versions, but it boils down to concatenating "%" with NULL and then performing a LIKE query - which is just gross.

I suggest that you clean up your code and refactor those expressions. I think I'll mark this wontfix for now.
