### ISSUE TITLE
'SqliteDatabase' object has no attribute 'create_index' error when calling create_index() method in Table class

### ISSUE THREAD

**Issue by ldconejo** [coleifer/peewee#2319]
Operating System: MacOS
Python version: 3.9
Peewee version: 3.14.0

It seems the _create_index()_ method in SQLite was deprecated, in turn breaking the _create_index()_ method in the Table class. The method in _dataset.py_ works as a wrapper:

```
    def create_index(self, columns, unique=False):
        self.dataset._database.create_index(
            self.model_class,
            columns,
            unique=unique)
```

I'm trying the following code:

db = DataSet('sqlite:///my_database.db')
table = db['UsersTable']
table.create_index(['test'])

Which returns this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/dataset.py", line 210, in create_index
    self.dataset._database.create_index(
AttributeError: 'SqliteDatabase' object has no attribute 'create_index'
```

**Comment by coleifer** [comment]
Thank you for the report. I've pushed a fix for this.

**Comment by ldconejo** [comment]
Thank you so much!
