### ISSUE TITLE
Could you tell me how to operating the content of the update only a data?

### ISSUE THREAD

**Issue by BarryYBL** [coleifer/peewee#2321]
user.update(username='tudou').where(id='20')
There is no effect！
He put all the table data keys are updated

**Comment by coleifer** [comment]
You need to put `.execute()` when you are finished creating your update query.

```python
User.update(username='foo').where(id=20).execute()
```

**Comment by BarryYBL** [comment]
But he has updated my  all username key value！
How do I update only the content with ID =76？
![image](https://user-images.githubusercontent.com/46100874/103543108-f24d8080-4ed8-11eb-9f9d-016fda57edd2.png)

**Comment by coleifer** [comment]
You need to write `.where(User.id == 20)`

**Comment by BarryYBL** [comment]
Has been solved！ OK，thankyou！
