### ISSUE TITLE
Using ESCAPE with Sqlite

### ISSUE THREAD

**Issue by mtihlenfield** [coleifer/peewee#2322]
I'm essentially trying to do the same exact thing as #348, but the solution there recommends using `Clause`, which doesn't seem to exist any longer. There no longer seems to be a way to execute a query like:

`select * from symbol where name LIKE "%\_printf" ESCAPE "\"`

on an sqlite database without just resorting to `.execute_sql`. Is there a new way to do this, or is `.execute_sql` the way to go?

**Comment by mtihlenfield** [comment]
Solved this just using `SQL()` like so:
```
Symbol.select().where(SQL("name LIKE ? ESCAPE '\\'", (sym_name, )))
```

**Comment by coleifer** [comment]
Peewee now automatically escapes when you use `.contains()`, `.startswith()` or `.endswith()`. So your example would be:

```python

Symbol.select().where(Symbol.name.endswith('_printf'))
```
