### ISSUE TITLE
Query results to json?

### ISSUE THREAD

**Issue by jet10000** [coleifer/peewee#2323]
Is there a convenient way to directly convert the query result into json, or into an orjson object?

**Comment by coleifer** [comment]
* http://docs.peewee-orm.com/en/latest/peewee/querying.html#retrieving-row-tuples-dictionaries-namedtuples - specifically `.dicts()`
* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#shortcuts

Please post questions to stackoverflow. The issue tracker is for tracking issues.
