### ISSUE TITLE
Allow deferring of foreign keys when lazy_load is disabled

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#2328]
I just encountered a problem when disabling lazy loading on foreign keys.

```python
class Referenced(Model): pass

class Referencing(Model):
     ref = ForeignKeyField(Referenced, lazy_load=False)

referenced = Referenced()
referencing = Referencing()
referenging.ref = referenced
referenced.save()
referencing.save()
```
The above code will result in a `DoesNotExist` exception, because the current `NoQueryForeignKeyAccessor` does not attempt to check `instance.__rel__`
I think this should work, since it does not require a query.
I will make a pull request, that solves this issue and also gets rid of the `NoQueryForeignKeyAccessor`.
This has the beautiful side effect, that changing a `ForeginKeyField`'s `lazy_load` attribute during runtime actually has an effect on the behaviour. Currently, `lazy_load`  is only evaluated during `ForeignKeyField.__init__` and then unnecessarily stored on the instance, since subsequent changes to it will not have any effect.

**Comment by coleifer** [comment]
Thanks for this - I've merged an equivalent patch which includes a regression test as well: b34e601
