### ISSUE TITLE
How to specify some fields when using the function of replace()?

### ISSUE THREAD

**Issue by vba34520** [coleifer/peewee#2330]
How to specify some fields when using the function of [`replace()`](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.replace)?

1. http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.replace
2. http://docs.peewee-orm.com/en/latest/peewee/querying.html#upsert

I give a primary key to  [`replace()`](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.replace) and just want to modify one of the field.

```python
from peewee import *

db = SqliteDatabase('test')


class Product(Model):
    product_id = CharField()
    product_name = CharField()

    class Meta:
        database = db


db.connect()
db.create_tables([Product])
id = Product(product_id='0001', product_name='apple').save()
Product.replace(id=id, product_name='banana').execute()  # specify some fields
print(id)
```

it will cause peewee.IntegrityError: NOT NULL constraint failed.

Looking forward to your reply!

**Comment by coleifer** [comment]
Replace will delete the row and replace it with the data you provide.

I think what you want is "update()".
