### ISSUE TITLE
`generate_models` returns empty `dict`

### ISSUE THREAD

**Issue by vsheg** [coleifer/peewee#2333]
Hi,
I want to see tables in my predefined database (it was created with `SQLAlchemy` and modified with GUI Beekeeper Studio)

1. When I use `peewee` I get noting:

```python
from peewee import PostgresqlDatabase
from playhouse.reflection import generate_models

db = PostgresqlDatabase('postgres', user=getenv('DB_USER'),
                                    password=getenv('DB_PASSWORD'),
                                    host='localhost',
                                    port=5432
                        )

print( generate_models(db) )
# {}
```

2. But when I use `SQLAlchemy` (or GUI Beekeeper Studio), I can see all my tables:
```python
from sqlalchemy import create_engine

engine = create_engine(getenv('DB_URI'))
print( engine.table_names() )
# ['sources', 'channels', 'persons', 'posts']
```
What's wrong?

<details>
  <summary>Versions</summary>
  

- Python 3.9.1
- pip 21.0 
- peewee 3.14.0
- psycopg2-binary 2.8.6
- macOS Big Sur 11.1

</details>

**Comment by coleifer** [comment]
I have no idea what might be going on in your setup. This code is covered with unit tests so it is not fundamentally broken:

https://github.com/coleifer/peewee/blob/master/tests/reflection.py#L81

I'd suggest debugging or providing more information.
