### ISSUE TITLE
ImproperlyConfigured: MySQL connector not installed!  

### ISSUE THREAD

**Issue by thisnugroho** [coleifer/peewee#2336]
hello, first I wanna thank you guys who made this, it's very helpfull for me who just start learning python, migrating from PHP 😁,
I got an error like in this picture below,

![image](https://user-images.githubusercontent.com/49790011/106567870-73964280-656d-11eb-8420-9603d1908171.png)

it's said I don't have mysql.connector installed,
then i try to import it, but there is no error

![image](https://user-images.githubusercontent.com/49790011/106568309-18188480-656e-11eb-9ba2-3c57a6ed6dd2.png)

so I confused about what is happening...

can someone explain to me, did i make mistake?

I'm trying point number 4 from this answer which is with `playhouse.mysql_ext.MySQLConnectorDatabase`  from this:
https://github.com/coleifer/peewee/issues/1569#issuecomment-484128525
and the code is looklike this:
```python
from peewee import * 
from playhouse.mysql_ext import MySQLConnectorDatabase 

dbc = {
    "db_name":"xxx",
    "host":"127.0.0.1",
    "user":"xxx",
    "password":"xxxx",
    "port":3306
}

db = MySQLConnectorDatabase(dbc['db_name'], user=dbc['user'], password=dbc['password'], host=dbc['host'])
```

I'm using:
python:3.8.5
flask:1.1.2
OS: ubuntu 20.04

**Comment by coleifer** [comment]
It looks like you're using a virtual environment. You may need to be sure mysql-connector is installed in your venv. Whatever is happening, the problem is that peewee cannot import mysql.connector.

You can verify this yourself in your script. Place this at the top:

```python
import mysql.connector
```

**Comment by thisnugroho** [comment]
> It looks like you're using a virtual environment. You may need to be sure mysql-connector is installed in your venv. Whatever is happening, the problem is that peewee cannot import mysql.connector.
> 
> You can verify this yourself in your script. Place this at the top:
> 
> ```python
> import mysql.connector
> ```

thank you so much for your response,
Solved it by doing:
- Install Python wsgi
I started by installing wsgi  `sudo apt-get install libapache2-mod-wsgi` but still got the error because i just know it that previous command is installing wsgi for python2, so it's running on python2 that's why my pymysql or other mysql modules that i tried doesn't work, so I run this to fix it `sudo apt-get install libapache2-mod-wsgi-py3` install wsgi for python3
- checking python-path in apache config
adding this line in my app.py.
```python
```
