### ISSUE TITLE
Syntax error near "VALUES" when using ValuesList and Tuple

### ISSUE THREAD

**Issue by cvanea** [coleifer/peewee#2344]
Hi, 

I'm trying to select rows from a table where the given row values are in a list of tuples. As I understand it, SQLite can only support this kind of IN operation if the right-hand side is a subquery expression. Therefore, in SQLite the following works:

```sql
CREATE TABLE T1(x,y,z);
INSERT INTO T1(x,y,z) VALUES(1,2,3),(2,3,4),(1,NULL,5);
SELECT * FROM T1 WHERE ((x,y) in (VALUES (1,2), (2,3)));
```

I've tried to implement this using peewee as follows:

```python
coords = [(1,2), (2,3)]
vl = ValuesList(coords, columns=('x', 'y'))
selection = T1.select().where(Tuple(T1.x, T1.y) << vl)
```

However, this leads to the error `{OperationalError}near "VALUES": syntax error`

Inspecting the query in the debugger it seems that peewee is trying to do something like:

```sql
SELECT * FROM T1 WHERE ((x,y) in VALUES (1,2), (2,3));
```

I believe the error comes from the lack of brackets around the VALUES clause as running the same in SQLite leads to the same error.

Apologies if there's a better way to form this kind of query or I've missed something, I'm fairly new to SQL and peewee.

Thanks!

**Comment by coleifer** [comment]
As a workaround you can add parentheses by:

```python

from peewee import EnclosedNodeList

vl = ValuesList(coords, columns=('x', 'y'))
rhs = EnclosedNodeList([vl])
...where(Tuple(T.x, T.y).in_(rhs))
```

**Comment by coleifer** [comment]
If you're using Sqlite, it is very picky about what it accepts. The following approaches all work with Postgres, but not Sqlite for some reason:

```python

vl = ValuesList(((1, 2), (2, 3)), columns=('x', 'y'))
q = T.select().from_(T, vl).where(
    (T.x == vl.c.x) &
    (T.y == vl.c.y))

q = T.select().from_(T).join(vl, on=(
    (T.x == vl.c.x) &
    (T.y == vl.c.y)))
```

**Comment by cvanea** [comment]
The EnclosedNodeList suggestion worked perfectly and sped up a big update query I had quite drastically.

Thanks for looking into this and for the great library!
