### ISSUE TITLE
Undocumented conflict with field name "_path"?

### ISSUE THREAD

**Issue by alvenhar** [coleifer/peewee#2347]
Hi, I recently encountered the problem that peewee's create_tables() call hung indefinitely and started eating up massive RAM for a minuscule database setup. I finally figured out that the "offensive" change was that I named a CharField on one of my models "_path". As soon as I changed that to "_path_str", everything was back to normal, so I guess "_path" conflicts with the underlying peewee implementation.
That's fine, it was just hard to find as the docs didn't mention any reserved words/identifiers and this one is not of the usual python "hidden magic". Might look into that?

**Comment by coleifer** [comment]
Thanks for the report. Not going to take any action on this at the moment, but feel free to open a patch to add a section to the docs.
