### ISSUE TITLE
Extension support check in setup.py needs path to sqlite3.h and sqlite3.lib files on Windows.

### ISSUE THREAD

**Issue by cdcadman** [coleifer/peewee#2350]
Initially, when I ran `python setup.py build_ext -i`, I got the following message.

<pre>test_pw_sqlite3.c(1): fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory
unable to compile sqlite3 C extensions - missing headers?
setup.py:100: UserWarning: Could not find libsqlite3, SQLite extensions will not be built.
  warnings.warn('Could not find libsqlite3, SQLite extensions will not '
running build_ext</pre>

After I modified setup.py so that it could find sqlite3.h and sqlite3.lib in the extension support check, the setup worked fine.

In '_have_sqlite_extension_support()', I inserted two lines after line 71 (`compiler = new_compiler()`):
`    compiler.add_include_dir(r'C:\Program Files (x86)\Python38-32\include')` (location of my sqlite3.h file)
`    compiler.add_library_dir(r'C:\Program Files (x86)\Python38-32\libs')` (location of my sqlite3.lib file)

**Comment by coleifer** [comment]
Glad you got it working.
