### ISSUE TITLE
Missing datatype numrange for postgresql

### ISSUE THREAD

**Issue by DanielAndreasen** [coleifer/peewee#2356]
I have a case, where I need the datatype [`numrange`](https://www.postgresql.org/docs/9.2/rangetypes.html), however I cannot find it in `playhouse.postgres_ext`.
Is it possible to implement this? I know it already exists in `psycopg2._range.NumericRange`.

Just for clarification, I have tried making a table like this:

```python
from psycopg2._range import NumericRange

db = PostgresqlDatabase(...)

class Cutoff(BaseModel):
    parameter = TextField()
    interval = NumericRange()

db.connect()
db.create_tables([Cutoff])
```

but the `interval` does not appear in the generated table, and no errors are thrown either.

**Comment by DanielAndreasen** [comment]
I have played around a bit with the source code to get this to work, and found a simple solution that seems to work. I add the following `class` to `playhouse.postgres_ext`

```python
from psycopg2._range import NumericRange

...

class NumericRange(Field, NumericRange):
    field_type = 'NUMRANGE'
```

The column is now created with all the nice functionality from the `Range` class, which [`NumericRange`](https://github.com/psycopg/psycopg2/blob/master/lib/_range.py#L457-L463) inherits from. Would you like me to open a PR with this simple solution?

**Comment by coleifer** [comment]
I think this is incorrectly implemented. I would think you would rather do something like this:

```python

class NumericRangeField(Field):
    field_type = 'NUMRANGE'

    def adapt(self, value):
        if value is not None: return NumericRange(value)
```

The idea is that the field retains all the regular field methods/apis while exposing a value to the user which represents the range and can be converted to the appropriate sql by the psycopg2 driver.

At any rate, I do not intend to be adding support at the present time.

**Comment by DanielAndreasen** [comment]
Alright, thanks for the answer. I guess I can just implement it directly into my models.
