### ISSUE TITLE
[Q] Do I have to add indexes to peewee if I have manually added them to the table?

### ISSUE THREAD

**Issue by NightMachinary** [coleifer/peewee#2360]
I have manually added some indexes using Datagrip to my peewee database. Do I have to add these indexes to the peewee model (i.e., add some peewee Python code), or do things just work?

**Comment by coleifer** [comment]
The only reason you would need to add them to the Peewee model is if you want Peewee to create them whenever you run `database.create_tables([...])` or `MyModel.create_table()`.
