### ISSUE TITLE
can i get how long one sql execute time

### ISSUE THREAD

**Issue by mouday** [coleifer/peewee#2370]
I want to  known sql execute time, but logging not show.

just like :
```
10.12 ms SELECT * FROM `person` WHERE `name` = 'Tom' LIMIT 1
```

**Comment by coleifer** [comment]
This is documented:

http://docs.peewee-orm.com/en/latest/peewee/database.html#logging-queries

If you want to know the sql only for a particular query you can use the `.sql()` method of the query object.

http://docs.peewee-orm.com/en/latest/peewee/api.html#BaseQuery.sql

**Comment by mouday** [comment]
> Peewee can log all queries. This is documented:
> 
> http://docs.peewee-orm.com/en/latest/peewee/database.html#logging-queries
> 
> If you want to know the sql only for a particular query you can use the `.sql()` method of the query object.
> 
> http://docs.peewee-orm.com/en/latest/peewee/api.html#BaseQuery.sql

I known ， but i want to see execute time and execute sql

like
```
time: 347.00 ms
```

**Comment by coleifer** [comment]
You can try monkey-patching `Database.execute_sql()` or subclass your database implementation and override the `execute_sql()` method to add timing information.

**Comment by mouday** [comment]
> You can try monkey-patching `Database.execute_sql()` or subclass your database implementation and override the `execute_sql()` method to add timing information.

thank you, i impl code  as :
```python
# -*- coding: utf-8 -*-

import math
import time
from functools import wraps

from peewee import MySQLDatabase

import logging


logger = logging.getLogger('peewee')

def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.time() * 1000
        ret = func(*args, **kwargs)
        end_time = time.time() * 1000
        logger.debug("time: %.2f ms" % math.ceil(end_time - start_time))
        return ret

    return wrapper


class CustomMySQLDatabase(MySQLDatabase):
    @timer
    def execute_sql(self, sql, params=None, commit=SENTINEL):
        return super().execute_sql(sql, params, commit)


```

**Comment by coleifer** [comment]
Just a suggestion: you might try using something like this for the start/end timings:

https://docs.python.org/3.9/library/time.html#time.perf_counter

**Comment by mouday** [comment]
> Just a suggestion: you might try using something like this for the start/end timings:
> 
> https://docs.python.org/3.9/library/time.html#time.perf_counter

thank you!
