### ISSUE TITLE
[Q] Is it possible to mark a model object as "unsave-able"?

### ISSUE THREAD

**Issue by NightMachinary** [coleifer/peewee#2375]
I have some data analysis code that reads some objects from DB, and mutates them for easier analysis; I want to make sure that these mutated objects are never accidentally saved to the database. Is there a way to enforce this?

**Comment by coleifer** [comment]
No, this is not something that is supported in Peewee.

**Comment by NightMachinary** [comment]
@coleifer I just thought about simply setting `model.save = None`. I think this will be enough to prevent me from shooting myself in the foot later ...

**Comment by coleifer** [comment]
You would also want to lock-down the update, delete, delete_instance, etc, etc, presumably. If you're using sqlite it's possible to set the connection read-only and may be ways to do this with other databases as well. That's what I would look into. Or even adding a read-only user to your db and connecting with that user.
