### ISSUE TITLE
Cannot nest database as context manager in transactions

### ISSUE THREAD

**Issue by arjd** [coleifer/peewee#2379]
It seems to me that this should be possible:

```
with db.atomic():
    with db:
        inst = Model.create()
```

But this fails with `OperationalError: Attempting to close database while transaction is open.`.

This is pretty similar to https://github.com/coleifer/peewee/issues/1918

**Comment by coleifer** [comment]
What is the intent of such a construction? Using the database as context manager implies you wish to close the database when it exits. Peewee is correctly telling you it cannot close the database because you have explicitly requested a transaction.

Not a bug, in my opinion.
