### ISSUE TITLE
contrib a DillField ?

### ISSUE THREAD

**Issue by aiqc** [coleifer/peewee#2385]
I've been using the `PickleField` a lot, but ran into Pickle's limitations. These are overcome by `dill`, which was written by the `pathos` people.
https://dill.readthedocs.io/en/latest/#major-features

At first, I thought I would just save my dill-serialized objects as bytes in the `BlobField()`, but then then I realized, "bah, every time I want to read this I'll need to call a method that deserializes it; lame." This was fine for internal fields, but not for user-facing fields.

```python
import io
import dill as dill

def dill_serialize(objekt:object):
    blob = io.BytesIO()
    dill.dump(objekt, blob) #regular pickle is `dumps`
    blob = blob.getvalue()
    return blob


def dill_deserialize(blob:bytes):
    objekt = io.BytesIO(blob)
    objekt = dill.load(objekt) #regular pickle is `loads`
    return objekt

# in action on a notorious nested function
def funk():
    def funkier():
        return 'z'
    return funkier()

blob = dill_serialize(funk)
unblob = dill_deserialize(blob)

unblob()
# 'z'

```

Are you open to the idea of a DillField?

**Comment by aiqc** [comment]
`playhouse.fields`
https://github.com/coleifer/peewee/blob/a8938588c00ae7ef94f453b8873820419474b4ce/playhouse/fields.py

`tests.extra_fields`
https://github.com/coleifer/peewee/blob/a8938588c00ae7ef94f453b8873820419474b4ce/playhouse/fields.py

**Comment by coleifer** [comment]
You're welcome to package this up as your own extension module, but I try to stay within the stdlib where possible.
