### ISSUE TITLE
model_to_dict exclude

### ISSUE THREAD

**Issue by bronte2k7** [coleifer/peewee#2386]
Hi

```python
class Account(Model):
	email = CharField(max_length=255, unique=True, index=True)
	password = PasswordField(index=True)

account = Account.get_or_none(Accountl.id == 1)
account = model_to_dict(account, exclude=['password'])
```

Password is not excluded

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#model_to_dict

>exclude – A list (or set) of field instances which should be excluded from the result dictionary.

You need to pass the field instance.

**Comment by bronte2k7** [comment]
I do not understand something. Please show me an example. I have already tried it in different ways)))

**Comment by coleifer** [comment]
Going forward, please post questions to stackoverflow.

>example

```python
account = model_to_dict(account, exclude=[Account.password])
```

**Comment by mouday** [comment]
thank you!
