### ISSUE TITLE
Connections fail with: peewee.OperationalError: (1524, "Plugin 'unix_socket' is not loaded")

### ISSUE THREAD

**Issue by scjoiner** [coleifer/peewee#2387]
In Peewee 3.14.4 connections are failing with the error message "peewee.OperationalError: (1524, "Plugin 'unix_socket' is not loaded")" on the db.connect() command. 

OS is Ubuntu 18.04 running Python 3.6 in a virtual environment for a Flask application with uwsgi. 

This application was previously working and this is a new issue.

**Comment by coleifer** [comment]
Sounds like an issue in your db driver. That error is being propagated up from whatever driver you're using. Presumably you upgraded something else in addition to just peewee. You can diff the last working version with 3.14.4 and see if anything jumps out at you, but it seems unlikely to me.
