### ISSUE TITLE
Add support for MySQL connection recycling

### ISSUE THREAD

**Issue by arnuschky** [coleifer/peewee#239]
We're getting the following error on our flask project:

```
  SQLError: (OperationalError) (2006, ‘MySQL server has gone away’)
```

This problem was implicitly mentioned in https://github.com/coleifer/peewee/issues/222 for example.

SQLalchemy addresses the problem as follows: https://github.com/mitsuhiko/flask-sqlalchemy/commit/05c51933c4972b47c1420fdc29429da9b67b75d8
Associated issue: https://github.com/mitsuhiko/flask-sqlalchemy/issues/2

Would it be possible to implement this in PeeWee as well?

**Comment by serkandaglioglu** [comment]
I use peewee with flask.

Peewee database connection : 
```
db = PooledMySQLDatabase(database,**{
            "passwd": password, "user": user,
            "max_connections":None,"stale_timeout":None,
            "threadlocals" : True
        })

@app.before_request
def before_request():
    db.connect()

@app.teardown_request
def teardown_request(exception):
    db.close()
```

After mysql error that "MySQL server has gone away (error(32, 'Broken pipe'))", select queries works without problem, but insert,update,delete queries don't work.

On insert,update,delete queries works behind(in mysql) but peewee throw this errors.

```
(2006, "MySQL server has gone away (error(32, 'Broken pipe'))")
```

**Comment by coleifer** [comment]
That's odd, not sure what that might mean.

**Comment by serkandaglioglu** [comment]
@coleifer I have two different applications with peewee and flask. They have same problem. Select queries has no problem but insert,update,delete always throws error which above. I will do test with an basic peewee and flask app and I will write the result of the test.
