### ISSUE TITLE
How can I split the table in Peewee?

### ISSUE THREAD

**Issue by nic519** [coleifer/peewee#2398]
```
class User(Model):
    id = IntegerField()
    name = CharField()

    Class Meta:
        database = db # db connection
        db_table = 'user_00' # Here is the problem
```

We have a lot of users, and I have to split the table like user_00,user_01,user_0...user_09.

If I use the field db_table, I can't do that, and I also don't want to create more model.

BTW, I know the function called db_table_func, but there are no more usage in the doc.

How do you use the split table in your project?

Thx, I really need help!

**Comment by coleifer** [comment]
You're going to have a hard time, basically.

You might create a VIEW or something that unions together all these tables, and just select from that view for read-only queries.

For writing you will need to either

1. change the `table_name` at runtime (`db_table` is deprecated, it has been renamed to `table_name`)
2. create a model-per-table and pick the right one at runtime
