### ISSUE TITLE
DataSet "peewee.OperationalError: duplicate column name" raised when unique column name with different case is present in thawed CSV file

### ISSUE THREAD

**Issue by ldconejo** [coleifer/peewee#2399]
Issue originally reported by @bromleysj

Running peewee-3.14.1 on Python 3.9.

Consider the following example:

```
# demo.py
from playhouse.dataset import DataSet

database = "test.db"

database = DataSet(f"sqlite:///{database}")

users = database["Users"]
users.insert(user_id="test")
users.create_index(["user_id"], unique=True)
users.delete(user_id="test")

users.thaw(filename='test_accounts.csv', format="csv")
```

If we try to add data from a .csv file with a column named "USER_ID", all uppercase, a _peewee.OperationalError: duplicate column name_ exception will be raised. The issue only occurs if the affected column has been marked as unique when creating the table and can be worked around by making the affected column in the .csv file match the case of the corresponding column in the existing table.

This .csv file will fail:

```
USER_ID,EMAIL,NAME,LASTNAME
Larisa.Yesima75,Larisa,Yesima,Larisa.Yesima75@testmail.com
```

This .csv file will pass:

```
user_id,EMAIL,NAME,LASTNAME
Larisa.Yesima75,Larisa,Yesima,Larisa.Yesima75@testmail.com
```

**Comment by coleifer** [comment]
I don't necessarily agree that this needs to be fixed by Peewee -- presumably you can sanitize or normalize this data.
