### ISSUE TITLE
[Playhouse.migrator] Implement add_foreign_key_constraint or document solution for sqlite

### ISSUE THREAD

**Issue by thigg** [coleifer/peewee#2409]
`add_foreign_key_constraint` for the sqlite migrator throws a NotImplemented error.

A possible solution would be to rename the table, recreate the table, copy the data, drop the copy. (as described in https://www.techonthenet.com/sqlite/foreign_keys/foreign_delete.php)

This could either be implemented or at least a comment could be added which points to a possible solution.

**Comment by coleifer** [comment]
I've decided to pass on implementing this for Sqlite, but it is possible, as you suggest.

**Comment by thigg** [comment]
Maybe this could be mentioned in the documentation then?
