### ISSUE TITLE
WHERE-IN query missing VALUES keyword leading to sqlite error

### ISSUE THREAD

**Issue by bravegag** [coleifer/peewee#2411]
I have the following use case in peewee version 3.14.4:

```
query = A.select().where(Tuple(A.a1, A.a2).in_([('x1', 'y1'), ('x2', 'y2')]))
print(query)
```

This will generate for sqlite a query similar to:
```
SELECT ... 
FROM a 
WHERE (a1, a2) IN (('x1', 'y1'), ('x2', 'y2'))
```
which leads to the sqlite error: `Error while executing SQL query on database X: row value misused`

peewee SQL generator is missing the VALUES keyword like the correct sql code should be:
```
SELECT ... 
FROM a 
WHERE (a1, a2) IN (VALUES('x1', 'y1'), ('x2', 'y2'))
```

**Comment by coleifer** [comment]
Sqlite is finnicky about parentheses.

This should work:

```python

vl = ValuesList([('x1', 'y1'), ('x2', 'y2')])
# wrap in extra parentheses for sqlite
vl_p = EnclosedNodeList([vl])

q = A.select().where(Tuple(A.a1, A.a2).in_(vl_p))
```
