### ISSUE TITLE
peewee.OperationalError: near "RETURNING": syntax error

### ISSUE THREAD

**Issue by bravegag** [coleifer/peewee#2412]
I'm on peewee 3.14.4 and sqlite, and I'm getting the above error `peewee.OperationalError: near "RETURNING": syntax error` for a simple insert_many query adapted to my context from exactly the same as stated in the docs i.e.

```
query = (User
         .insert(email='foo@bar.com', created=fn.now())
         .returning(User))
```

I have also tried returning User.id or even leaving returning arguments empty but I get the same error.

The generated sql is something like:

```
INSERT INTO table (a, b, c, ...) VALUES (...), (...), (...) RETURNING table.id
```

**Comment by bravegag** [comment]
I found [this discussion](https://sqlite.org/forum/info/a4dde39b614ec0b2) and the issue is my version of sqlite3 3.29.0 which is lower than 3.35.x from where the RETURNING clause is supported :(.

Is there another way to accomplish the same use-case without RETURNING?

**Comment by coleifer** [comment]
>Is there another way to accomplish the same use-case without RETURNING?

If you leave off the `returning()` (which is unsupported in sqlite < 3.35) then Peewee will already return you the last insert rowid, which it seems like is all you want anyways.
