### ISSUE TITLE
Unable to specify custom column name

### ISSUE THREAD

**Issue by alexin** [coleifer/peewee#2413]
Hello,

I am unable to set a custom column for a primary key.

For example, the following model

```python
class Product(peewee.Model):
    reference = peewee.IntegerField(column_name='reference', primary_key=True),
```

results in the following SQL query

```sql
CREATE TABLE IF NOT EXISTS "product" ("id" INTEGER NOT NULL PRIMARY KEY)
```

Note that I request the name 'reference', but instead I get 'id'.

**Python**: 3.9.4
**Peewee**: 3.14.4

Am I missing something?

Thank you,
Alexandre Vieira

**Comment by coleifer** [comment]
You have a trailing comma after your peewee.IntegerField() which is probably the issue.

This code works fine:

```python
class Product(Model):
    reference = IntegerField(column_name='reference', primary_key=True)
    class Meta:
        database = db
```

Produces:

```sql
CREATE TABLE IF NOT EXISTS "product" ("reference" INTEGER NOT NULL PRIMARY KEY)
```

Please debug your code a bit more before opening issues.

**Comment by alexin** [comment]
Thank you for pointing that out. I am so used to Java-like languages that I easily missed that comma.
I understand it is dumb mistake and I could have avoided it. In my defense, I am dumbfounded I got no error nor warning, that could have saved me hours of figuring what was happening.
