### ISSUE TITLE
[question] Use query alias for group_by/order_by

### ISSUE THREAD

**Issue by atanasoff-yordan** [coleifer/peewee#2415]
As the documentation says [here](https://docs.peewee-orm.com/en/latest/peewee/querying.html#sorting-records) we should put the column on the order_by/group_by, for example, here the `.order_by(fn.COUNT(Tweet.id).desc())`
My question: since we defined an alias for the count, can we get a reference to that alias to use it in the  group_by/order_by? instead of writing again the whole thing?
thx

```python
query = (User
         .select(User.username, fn.COUNT(Tweet.id).alias('num_tweets'))
         .join(Tweet, JOIN.LEFT_OUTER)
         .group_by(User.username)
         .order_by(fn.COUNT(Tweet.id).desc()))
```

**Comment by coleifer** [comment]
Peewee will do the right thing and use the alias if you write it this way:

```python
ct = fn.COUNT(Tweet.id).alias('ct')
query = (User
         .select(User.username, ct)
         .join(Tweet, JOIN.LEFT_OUTER)
         .group_by(User.username)
         .order_by(ct))
```

Produces:

```sql
SELECT "t1"."username", COUNT("t2"."id") AS "ct" 
FROM "user" AS "t1" 
LEFT OUTER JOIN "tweet" AS "t2" ON ("t2"."user_id" = "t1"."id") 
GROUP BY "t1"."username" 
ORDER BY "ct"
```
