### ISSUE TITLE
Value not getting stored?

### ISSUE THREAD

**Issue by Donkere-vader** [coleifer/peewee#2417]
I'm not really sure if this is a bug or not. But it is very unexpected behavior.

So in my code I have two classes ``List`` and ``ListItem``.

```py
class Item(Model):
    # snip
    def set_value(self, value):
        pass  # snip

class ListItem(Item):
    pass  # snip

class List(Model):
    # snip

    def append(self, value):
        new_item = ListItem(parent=self)
        new_item.set_value(value)
        new_item.save()
        print("Value from object:", new_item.value)
        print("Value from queried object: ", ListItem.select().where(ListItem.id == new_item.id).get().value)
```

the ``ListItem.set_value(value)`` function does basically set the field ``value`` to the str of the value and the field ``value_type`` to what type it is. To later convert it back to a python object of the correct type.

if for example the parameter ``value`` of the function ``append`` would be ``2``. I would expect the following output:

```bash
Value from object: 2
Value from queried object:  2
```

However, as you might have guessed, that's not the output. The real output is:

```bash
Value from object: 2
Value from queried object:  <class 'peewee.CharField'>
```

Can this be a bug? Or am I doing something wrong?

Any help would be appreciated :)

Full code is up on [pastebin](https://pastebin.com/fcSydNai) the ``append`` function is on ln. 127

**Comment by coleifer** [comment]
You're doing some very strange stuff with so many operator overloads and things, so it's hard to tell what is going on. Specifically, overriding getitem / setitem on model classes should probably be avoided.

I'd suggest simplifying your code as much as possible to track this down, as I'm quite sure it's not a bug in Peewee but rather in your implementation.

**Comment by Donkere-vader** [comment]
Oh it was a very very stupid problem.

The code for my ``ListItem`` class looked like this:

```py
class ListItem(Item):
    parent = ForeignKeyField(List, backref="items")
    value = CharField
```
Notice the last line, I set value to the class CharField instead of an instance of CharField. I forgot the braces 🤦🏻 .
Thanks for your response anyways!  

Line should've been:
```py
    value = CharField()
```
