### ISSUE TITLE
Create tables from ModelSelect outside the public schema

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2423]
I think there is a bug or limitation in the `ModelSelect.create_table()` method. The way it works right now, you can only create tables in the public schema. This is because `Entity` expects multiple arguments, one for each part of the path, but `create_table` can send only one. If you pass the whole path as a string (e.g., `sandbox.test_table`) it gets quoted as `"sandbox.test_table"` which still points to the public schema.

I think the solution is either to allow to pass a tuple to `create_table()` (which will break compatibility) or to change the function signature so that it's more greedy getting the arguments so that you can pass `create_table('sandbox', 'test_table')` and all those arguments make it to the `Entity` instance.

**Comment by coleifer** [comment]
I've chosen to support this by allowing a tuple for the `table_name` parameter. So:

```python

query = SomeModel.select()...
query.create_table('my_new_table')

# OR
query.create_table(('schema', 'my_new_table'))
```
