### ISSUE TITLE
Not cool bro

### ISSUE THREAD

**Issue by universuen** [coleifer/peewee#2424]
Why the owner just closed my pull request and commit the changes himself? 
What's the meaning of community? 
What's the meaning of open source?
No wonder why Peewee can't be compared with SQLAlchemy🤗

**Comment by oz123** [comment]
Welcome to peewee ❤️ one of the best ORMs maintend as a BDFL project. The owner can do it's thing and it's still a great ORM.

**Comment by universuen** [comment]
> Welcome to peewee ❤️ one of the best ORMs maintend as a BDFL project. The owner can do it's thing and it's still a great ORM.

Indeed a great project, but not the owner. BTW, you should pay attention to your spelling

**Comment by coleifer** [comment]
This 1 word doc typo fix #2422 ?

I do this sometimes for very small / trivial patches. Your commit did not reflow the doc text to maintain the line length of the section.

**Comment by coleifer** [comment]
I'll just add if I had known you would care, I would have been fine merging it.

**Comment by universuen** [comment]
> This 1 word doc typo fix #2422 ?
> 
> I do this sometimes for very small / trivial patches if they need small stylistic tweaks. Your commit did not reflow the doc text to maintain the line length of the section.

Oh thanks for explaining this. 
Now I know that I failed to follow the rules. 
It is right to close the request. 
Sorry for the bothering, I will be cautious the next time.
