### ISSUE TITLE
Syntax error when selecting in VALUES

### ISSUE THREAD

**Issue by Hippopotas** [coleifer/peewee#2426]
Peewee version: 3.4.14
SQLite version: 3.35

When running code of the form (as recommended in issues [2344](https://github.com/coleifer/peewee/issues/2344), [2411](https://github.com/coleifer/peewee/issues/2411), [2414](https://github.com/coleifer/peewee/issues/2414)):
```python
foo = [(1, 2), (3, 4)]
bar = ValuesList(foo, columns=('col1', 'col2'))
baz = EnclosedNodeList([bar])
t1.select().where(Tuple(t1.col1, t1.col2).in_(baz))
```

I am getting a different kind of error: `OperationalError: near ",": syntax error`

The query it is attempting to execute is apparently (in (query, param) form)
```
('SELECT "t1"."col1", "t1"."col2" FROM "t1" WHERE (("t1"."col1", "t1"."col2") IN (VALUES (?, ?), (?, ?)))',
 [1, 2, 3, 4])
```

The same occurs on
```python
t1.raw("""SELECT col1 FROM t1 WHERE ((col1, col2) IN (VALUES (1, 2))""").execute()
```

After some tinkering, it appears that the problematic syntax is the comma between `col1, col2`
I am unsure why this is happening. I played around with the parentheses a bit, but could not figure out a fix.

This does not occur on non-row-values queries, e.g.
```
t1.select().where(t1.col1 << [1, 2, 3])

('SELECT "t1"."col1", "t1"."col2" FROM "t1" WHERE ("t1"."col1" IN (?, ?, ?))',
 [1, 2, 3])
```

**Comment by coleifer** [comment]
This works fine for me:

```python
db = SqliteDatabase(':memory:')

class KV(Model):
    key = TextField()
    value = IntegerField()
    class Meta:
        database = db

db.create_tables([KV])

KV.insert_many([('k1', 1), ('k2', 2), ('k3', 3), ('k4', 4), ('k5', 5)]).execute()

vl = ValuesList([('k1', 1), ('k3', 3), ('k5', 5)])
vl_e = EnclosedNodeList([vl])

query = (KV.select()
         .where(Tuple(KV.key, KV.value).in_(vl_e)))
for row in query:
    print(row.key, row.value)
```

Prints:

```
k1 1
k3 3
k5 5
```

**Comment by Hippopotas** [comment]
Hm. I ran your example code, but got the same error. Could I ask what the sql being generated is?
