### ISSUE TITLE
how should  i use ModelSelect.select()?

### ISSUE THREAD

**Issue by CooperWanng** [coleifer/peewee#2442]
I ran into a problem when I used select function of ModelSelect
>query = Auth.select(Auth.id)  # Model.select()
select t1.id FROM auth AS t1;
query = Auth.select(Auth.id).select()  # ModelSelect.select()
> select FROM auth AS t1;

how should i do?

**Comment by coleifer** [comment]
If you are explicitly re-selecting columns, you need to specify which columns you want.

**Comment by CooperWanng** [comment]
> If you are explicitly re-selecting columns, you need to specify which columns you want.

thanks,the usage of peewee differs between the two versions(3.6->3.14)
