### ISSUE TITLE
Accessing views via models not possible

### ISSUE THREAD

**Issue by SilvanVerhoeven** [coleifer/peewee#2452]
I try to access a view in my SQLite database following the instructions from https://stackoverflow.com/questions/38707331/does-peewee-support-interaction-with-mysql-views. I figured that the article's `db_table` needs to be replaced with `table_name` in the current version of peewee. I used the following SQL statement to create the view: `db.execute_sql('CREATE VIEW IF NOT EXISTS foo_view AS SELECT UPPER(name) AS name FROM foo')`.

Unfortunately, even after this update my `FooView` model only returns `None` for the name. Printing the vars via `print([vars(fv) for fv in FooView.select(FooView.name)])` shows why:  
`[{'__data__': {}, '_dirty': set(), '__rel__': {}, 't1': 'HUEY'}, {'__data__': {}, '_dirty': set(), '__rel__': {}, 't1': 'MICKEY'}, {'__data__': {}, '_dirty': set(), '__rel__': {}, 't1': 'ZAIZEE'}]`

Compare this to the output of `print([vars(fv) for fv in Foo.select(Foo.name)])`:  
`[{'__data__': {'name': 'huey'}, '_dirty': set(), '__rel__': {}}, {'__data__': {'name': 'mickey'}, '_dirty': set(), '__rel__': {}}, {'__data__': {'name': 'zaizee'}, '_dirty': set(), '__rel__': {}}}]`

Interestingly enough, setting `Foo.Meta.table_name` to `foo_view` yields the same result as simply using `FooView`.

I wonder if this is a bug in peewee or whether I am doing something wrong. Help much appreciated!

**Comment by coleifer** [comment]
What version of sqlite are you using?

**Comment by SilvanVerhoeven** [comment]
The requirements.txt requires peewee 3.9.6

**Comment by coleifer** [comment]
No, what version of sqlite.

**Comment by SilvanVerhoeven** [comment]
I'm sorry. SQLite 3.31.1

**Comment by coleifer** [comment]
This example code is working fine for me, I suppose you have some issue in your code:

```python
from peewee import *

db = SqliteDatabase(':memory:')

class Foo(Model):
    name = TextField()
    class Meta: database = db

db.create_tables([Foo])
for name in ('huey', 'mickey', 'zaizee'):
    Foo.create(name=name)

db.execute_sql('create view foo_view as select upper(name) as name from foo')
class FooView(Foo):
    class Meta:
        primary_key = False
        table_name = 'foo_view'

print([row.name for row in FooView.select()])
```

Prints: `['HUEY', 'MICKEY', 'ZAIZEE']`
