### ISSUE TITLE
BETWEEN does not work with datetime objects in SQlite

### ISSUE THREAD

**Issue by LVerneyPEReN** [coleifer/peewee#2459]
Hi,

I have an issue where `BETWEEN` operation which does not work with a `DateTimeField` in SQLite when checking against Python `datetime.datetime` objects.

It seems this is due to the default adapter being used for such formats in SQLite is `str` conversion, which is not the same as an `isoformat`. Therefore, lexicographic comparison is broken afterwards.

See

```python
>>> import datetime
>>> str(datetime.datetime.now())
'2021-08-25 16:44:43.952660'
>>> datetime.datetime.now().isoformat()
'2021-08-25T16:44:56.216273'
```

And the extra "T" between date and time part.

Thanks!

**Comment by coleifer** [comment]
Sqlite does not have a dedicated date/datetime type. It is up to you, the developer, to ensure that your datetimes are stored in a way that supports correct lexicographic ordering. Additionally, Peewee does not apply any conversion at all to datetime objects - it hands them as-is to the db driver. It is actually the sqlite driver that is handling the conversion for sqlite: (`import sqlite3; sqlite3.adapters`). This is consistent and supports lexicographic ordering, but if you've stored your datetimes in ISO format in Sqlite, then you may have some work to do to get them working properly with python's sqlite3 module.

You can:

* register a different adapter for `datetime.datetime` that converts them to string in iso format - this may be the easiest
* write a custom `DateTimeField` subclass that implements a `db_value()` method that returns the datetime in isoformat
* update your data to use the python format (probably undesirable, but mentioning it as a possibility)

All that said, at the end of the day this is not really a peewee issue -- this is a consequence of the behavior of the python sqlite driver and sqlite's own lack of a dedicated datetime type.
