### ISSUE TITLE
UNSIGNED BIGINT AUTO_INCREMENT support in create_tables?

### ISSUE THREAD

**Issue by sherrrrr** [coleifer/peewee#2465]
I am using mysql and use UNSIGNED BIGINT as primary key. According to as [issue542](https://github.com/coleifer/peewee/issues/542), I try to use BIGINT UNSIGNED like this
```python
class UnsignedBigAutoField(BigAutoField):
    field_type = 'BIGINT UNSIGNED'
```
and I try to use `ForeignKeyField` in models.
```
class User(Model):
    id = UnsignedBigAutoField(primary_key=True)

class Tweet(Model):
    id = UnsignedBigAutoField(primary_key=True)
    user = ForeignKeyField(User, backref='tweets')
```

I want to use peewee to create tables, later I realize that inherite `AutoField` with `auto_increment = True` does't affect sql, there is no AUTO_INCREMENT in create table sql. What's more, when try to create `Tweet`, user_id's type is BIGINT without UNSIGNED beacuse of ForeignKeyField's [field_type](https://github.com/coleifer/peewee/blob/master/peewee.py#L5213).

so I write this
```python
class UnsignedBigAutoField(IntegerField):
    auto_increment = True
    field_type = 'BIGINT UNSIGNED AUTO_INCREMENT'

    def __init__(self, *args, **kwargs):
        if kwargs.get('primary_key') is False:
            raise ValueError('%s must always be a primary key.' % type(self))
        kwargs['primary_key'] = True
        super(UnsignedBigAutoField, self).__init__(*args, **kwargs)
```

and this would cause `user_id` in Tweet have `AUTO_INCREMENT`.

So is there a solution to use UNSIGNED BIGINT as primary key and foreign key when I want to create table using peewee?

**Comment by coleifer** [comment]
You overrode the pk, now just subclass `ForeignKeyField` and override the field_type property:

```python
class UnsignedBigAutoField(BigAutoField):
    field_type = 'BIGINT UNSIGNED AUTO_INCREMENT'

class UnsignedForeignKeyField(ForeignKeyField):
    field_type = 'BIGINT UNSIGNED'

class User(Base):
    id = UnsignedBigAutoField()

class Tweet(Base):
    id = UnsignedBigAutoField()
    user = UnsignedForeignKeyField(User)
```
