### ISSUE TITLE
Model.bulk_create() ignores id of instances

### ISSUE THREAD

**Issue by balloonz** [coleifer/peewee#2472]
It seems that Model.create() method respects id while Model.bulk_create ignores id of instances.

my model class:
```
class Book(Model):
    title = CharField(default="")
    author = CharField(default="")
    created_date = DateTimeField(default=datetime.now)

    class Meta:
        database = SqliteDatabase(":memory:")
```
The following code prints [(1, 'A'), (2, 'B'), (4, 'D'), (5, 'C')].
```
with db.atomic():
    Book.create(id=1, title="A")
    Book.create(id=2, title="B")
    Book.create(id=5, title="C")
    Book.create(id=4, title="D")
print([(book.id, book.title) for book in Book.select()])
```
The following code prints:
[(1, 'A'), (2, 'B'), (5, 'C'), (4, 'D')]
[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]
```
book_items = [
    Book(id=1, title="A"),
    Book(id=2, title="B"),
    Book(id=5, title="C"),
    Book(id=4, title="D"),
]
with db.atomic():
    Book.bulk_create(book_items, batch_size=50)
print([(book.id, book.title) for book in book_items])
print([(book.id, book.title) for book in Book.select()])
```
Also, the unsaved instances are kept unchanged and therefore inconsistent with the instances returned by Model.select().

**Comment by coleifer** [comment]
Why are you manually specifying the ID for an auto-incrementing (opaque) primary key? The `bulk_create()` API is a shorthand for generating an `insert_many()`. Just use `insert_many()` if you really want to explicitly set these, I suppose.

**Comment by balloonz** [comment]
I was importing some data into the database which involve relational data.
I thought `bulk_create()` as an alternative to `insert_many()` may also work.
If it is intended behavior, I will stick to `insert_many()`. 
Thanks for the quick response.

**Comment by coleifer** [comment]
If you want, you can disable the primary keys `auto_increment` attribute during bulk loading, but (especially if you're just creating the models to insert the data only) insert many is probably a fine choice.
