### ISSUE TITLE
Support for psycopg3

### ISSUE THREAD

**Issue by elderlabs** [coleifer/peewee#2473]
Preemptive ticket here. The maintainer of psycopg2 has busied themself with its next iteration, [psycopg3](https://github.com/psycopg/psycopg). Are there plans to add support for the project; is there already native support by design? This ticket's more to see if the project's on your radar as it has officially released, and support for psycopg2 might be in decline fairly soon.

Thanks.

**Comment by MaartenUreel** [comment]
Hello

I looked at your extension but I wondering, can I use this in conjuction with PostgresqlExtDatabase?

Any plans on built-in support for psycopg3? Considering is also adding it in their next release and it is a stable release..

**Comment by coleifer** [comment]
Are there any specific features of `PostgresqlExtDatabase` you were intending to use - e.g. jsonb, arrays? I'll have to spend some time seeing what works and what doesn't, since we use some helpers from `psycopg2.extras` (e.g. `Json`).

**Comment by coleifer** [comment]
No, I agree with you, things are going to be moving towards psycopg3 in the coming years so I'll want to be ready for that. Thanks for the ping on this, I'll be aiming to getting parity for psycopg3 with the current PostgresqlExtDatabase. No definitive timeline but it's a priority for me.

**Comment by amirreza8002** [comment]
hello
so i'm wondering if there are any news on this?

**Comment by coleifer** [comment]
Merged into master.

**Comment by HammerMeetNail** [comment]
@coleifer Great to see this merged. When do you think a release will be cut?

**Comment by andrewchen5678** [comment]
it is not merged to master yet, I just checked master and it is still have the hard coded check for psycopg2 for postgres, which is not the right package for psycopg3. The right package for psycopg3 is **psycopg** without 2. Please reopen this ticket.

```
    def _connect(self):
        if psycopg2 is None:
            raise ImproperlyConfigured('Postgres driver not installed!')
```

**Comment by coleifer** [comment]
The standard `PostgresqlDatabase` will continue to use psycopg2 for the foreseeable future. To use psycopg3, use `playhouse.psycopg3_ext.Psycopg3Database`.

**Comment by harishvadali** [comment]
@coleifer  Thank you for adding the psycopg3 support. I see the field for BinaryJSONField but not JSONField with psycopg3. Is that on roadmap?

**Comment by coleifer** [comment]
Is there a compelling reason not to use jsonb?
