### ISSUE TITLE
Remote Postgres Use Case

### ISSUE THREAD

**Issue by aiqc** [coleifer/peewee#2490]
Hiya. 

It sounded like you were fishing for use cases with respect to Postgres in the docs.
> https://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=postgresql#PostgresqlExtDatabase 
> 
> In the future I would like to add support for more of postgresql’s features. If there is a particular feature you would like to see added, please open a Github issue.

I'm using and love PeeWee w SQLite for local development and vertical scale (single desktop/ server). It's a great way to provide a 1-line install for contributors and open source users. 

I was hoping to drop a SQLite file into AWS EFS and mount many jobs/users to it simultaneously, but concurrent writes over NFS are a no-go zone for SQLite. Right now I have to manually manage my own lock file. 

So my solution would be to serve PSQL via AWS RDS. I searched for "postgresql" in the peewee docs because I don't want to switch ORMs. However, I didn't see anything like database IP address or port - so I was wondering if this implementation would support a remote psql db?

**Comment by coleifer** [comment]
Yes, peewee supports all the same parameters as psycopg2, so:

```python

# for example:
db = PostgresqlDatabase('db_name', host='192.168.1.30', port=5432, user='postgres', password='xyz')
```

Psycopg2 connection doc: https://www.psycopg.org/docs/module.html#psycopg2.connect
