### ISSUE TITLE
Bug related to create_table function in your Model

### ISSUE THREAD

**Issue by kezzhang** [coleifer/peewee#2492]
It is actually about one of your examples in version 2.9.1 and before, redis_vtable, in line 208, RedisView.create_table(), this will report error. But when I change that line to something like cursor.execute("create virtual table redisview using RedisModule()"), the whole program worked. 

So I highly doubt that there is something wrong with your create_table function especially under the apsw_ext situation. Besides, when you truly want to do extensions for something, doing it halfway is worse than nothing.

**Comment by coleifer** [comment]
I could swear I ran all the examples and they worked so possibly something has changed. 2.x is unmaintained since Feb 2018 so hard to say.
