### ISSUE TITLE
pwiz uses wildcard imports of peewee

### ISSUE THREAD

**Issue by tdennisliu** [coleifer/peewee#2494]
Hiya,

I've found pwiz very helpful in setting up my scripts, but since it wildcard imports `peewee` into the script. See below from the README:

```
from peewee import *
import datetime


db = SqliteDatabase('my_database.db')

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    username = CharField(unique=True)

class Tweet(BaseModel):
    user = ForeignKeyField(User, backref='tweets')
    message = TextField()
    created_date = DateTimeField(default=datetime.datetime.now)
    is_published = BooleanField(default=True)
```

I find this very difficult to troubleshoot if something goes wrong, and it takes a long time to simply find and replace the classes.

What I would like to see:

```
import peewee as pw
import datetime


db = pw.SqliteDatabase('my_database.db')

class BaseModel(pw.Model):
    class Meta:
        database = db

class User(BaseModel):
    username = pw.CharField(unique=True)

class Tweet(BaseModel):
    user = pw.ForeignKeyField(User, backref='tweets')
    message = pw.TextField()
    created_date = pw.DateTimeField(default=datetime.datetime.now)
    is_published = pw.BooleanField(default=True)
```

The [python docs](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) do state that this practise should be avoided.

As far as I can tell it's not too difficult to change this behaviour for pwiz, and I can set up a PR. 
Thoughts?

**Comment by coleifer** [comment]
This is a convention that is used throughout peewee examples, as well as my own code. Peewee module defines `__all__`, which controls what objects are exported, and I am happy with that. In your own code you are welcome to use whatever style you like, though.
