### ISSUE TITLE
Support for "<@" in PostgreSQL arrays

### ISSUE THREAD

**Issue by joaodlf** [coleifer/peewee#2497]
Peewee currently supports `@>` (`.contains()`) and `&&` (`contains_any()`) - [docs](https://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=array#ArrayField.contains)

It would be nice for Peewee to also support `<@`, as expressed in the [PostgreSQL docs](https://www.postgresql.org/docs/current/functions-array.html):

> anyarray <@ anyarray → boolean
>
> Is the first array contained by the second?
>
> ARRAY[2,2,7] <@ ARRAY[1,7,4,2,6] → t

Note that this is a completely different behavior to `@>`:

> anyarray @> anyarray → boolean
> 
> Does the first array contain the second, that is, does each element appearing in the second array equal some element of the first array? (Duplicates are not treated specially, thus ARRAY[1] and ARRAY[1,1] are each considered to contain the other.)
> 
> ARRAY[1,4,3] @> ARRAY[3,1,3] → t

I would imagine this implemented as something like `.contained_by()`?

**Comment by coleifer** [comment]
Thanks for the suggestion - this is implemented as `contained_by`.

**Comment by joaodlf** [comment]
Thanks for the **incredible** feedback in such a short notice, do you plan on releasing a minor version with this feature any time in the near future?

**Comment by coleifer** [comment]
Besides this one change, there aren't really any other notable changes yet to justify a new release, in my opinion -- everything else is just docs or example updates. I'll probably wait until after the holidays.

If you want to use this now, but don't want to pin to `master` branch, I'd suggest just implementing your own subclass of ArrayField that implements `contained_by()` and using that in the meantime.
