### ISSUE TITLE
AttributeError: 'Expression' object has no attribute 'execute'

### ISSUE THREAD

**Issue by thisnugroho** [coleifer/peewee#2502]
It's appear after upgrading from version 3.14.4 to peewee latest version 3.14.8,
i decide to upgrade because i want to using `Model.get_or_none()` function, it's not available in previous version.
and the error appear i'm trying to running this:
```python
SomeModel().select().get_or_none(SomeModel.field== value)
```
my configuration looklike this:
```python
db = MySQLDatabase(
    env("DB_DATABASE"),
    user=env("DB_USERNAME"),
    password=env("DB_PASSWORD"),
    host=env("DB_HOST"),
    port=int(env("DB_PORT")),
)
```

is there something that i need to adjust ? or i'm just missing something.

screenshoot:
![image](https://user-images.githubusercontent.com/49790011/145660391-f7bf7cf7-b00a-4073-998d-9122faabe720.png)

details
OS:Ubuntu 20.04
MYSQL Version = 8.0.27

**Comment by coleifer** [comment]
The `get_or_none()`, when used on a select query, does not accept any parameters -- though the error message is unhelpful here.

In your code you are:

1. `SomeModel.select()` which creates a `ModelSelect` query
2. Call the `get_or_none()` method on the `ModelSelect` query

I think what you intended to do is this:

```python

SomeModel.select().where(SomeModel.field == value).get_or_none()
```

Alternatively, you can use the *shortcut* method on model, which *does* accept an expression:

```python

SomeModel.get_or_none(SomeModel.field == value)
```

* http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.get_or_none
