### ISSUE TITLE
distutils has been deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [coleifer/peewee#2506]
https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/coleifer/peewee/blob/5a55933ed28b261fbe100568125fffe0ba854b99/setup.py#L5-L8

**Comment by coleifer** [comment]
Steve Dower, a Microsoft employee, is railroading through this idiotic pep. From what I can see there are quite a few people who disagree with his decision:

https://discuss.python.org/t/pep-632-deprecate-distutils-module/5134/29

**Comment by oz123** [comment]
As much as I sympathize with the reaction, the code should be updated in the future. It seems that the pep isn't going away.

**Comment by coleifer** [comment]
Fallback to the vendored distutils inside setuptools for now: 7ab5e401d85c1eec7aafbbe2fdf3c0344f82422b

**Comment by coleifer** [comment]
Anyone who stumbles upon this and can find examples of prior art for projects that build C extensions and are going through a similar migration, I'd appreciate links. I glanced around at a few projects I'm familiar with, and all of them are still on `distutils`.
