### ISSUE TITLE
Add ModelSelect to __all__ for linting

### ISSUE THREAD

**Issue by 1kastner** [coleifer/peewee#2509]
First of all thank you very much for creating this project and sharing it under the MIT license!

Recently I have started to rely more on type-hinting in my projects to have better tool support and in some cases making my intentions more obvious for the readers of the code. While doing that, I got the warning that ModelSelect is not part of the official interface as it is not listed in `__all__`. However, I would like to pass a query which is not yet executed to another method or function and only there execute it. Thus my request to add `ModelSelect` to `__all__` and treat it as an official part of the API.

Of course there could be design choices or other ideas that contradict this. In that case I would love to learn more about the future intentions of how this project will continue.

**Comment by coleifer** [comment]
I'm going to pass - I don't really see a need to export this.
