### ISSUE TITLE
How to get all data from my Model?

### ISSUE THREAD

**Issue by peepopoggers** [coleifer/peewee#2515]
My class looks like this:

```py
class WaitPayment(BaseModel):
    txn_id = TextField(unique=True, primary_key=True)
    discord_id = TextField()
    ms_expires = DecimalField()
```

and I want to recieve all of its records as a dict. However, when I use `WaitPayment.select()` or `WaitPayment.select().dicts()`, it returns:

```sql
SELECT "t1"."txn_id", "t1"."discord_id", "t1"."ms_expires" FROM "waitpayment" AS "t1"
```
in the terminal, which is not what I want. I do not want the sql query, I want the result. Any help? Thanks.

**Comment by coleifer** [comment]
You need to read the documentation.

Take 10 or 15 minutes and go through the quick start.

http://docs.peewee-orm.com/en/latest/peewee/quickstart.html#retrieving-data

**Comment by peepopoggers** [comment]
So I have to iterate over the select to get any results?

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/querying.html#selecting-a-single-record

http://docs.peewee-orm.com/en/latest/peewee/querying.html#selecting-multiple-records

**Comment by peepopoggers** [comment]
To answer my own question, yes you must iterate. @coleifer are there any ways of not iterating to save time? like recieving an array of classes instead of just something to iterate upon. Thanks. And please give some explanation rather than just sending a link, thank you.

**Comment by coleifer** [comment]
https://docs.python.org/3/library/functions.html#func-list

**Comment by peepopoggers** [comment]
for anyone wondering, you can use something like WaitPayment.__dict__
to get variables and their values. and you can extend that with ['__data__'] to not get '_dirty' or '__rel__'.
