### ISSUE TITLE
generate_models from DatabaseProxy ValueError

### ISSUE THREAD

**Issue by LLjiahai** [coleifer/peewee#2516]
db = DatabaseProxy()
db.initialize(RetryMySQLDatabase.get_db_instance(**kw_config))
models = generate_models(db)

ValueError: Introspection not supported for <peewee.DatabaseProxy object at 0x000002859D87FE40>

**Comment by coleifer** [comment]
In this case, just instantiate the introspector directly - or pass it the underlying db instance:

```python
# Option 1:
introspector = Introspector(MySQLMetadata(database))
introspector.generate_models()

# Option 2:
models = generate_models(db.obj)
```

**Comment by coleifer** [comment]
I gave this another look and made a better fix. Going forward introspection will work with a proxy just fine.
