### ISSUE TITLE
drop_tables does not delete "schema" tables in MySQL

### ISSUE THREAD

**Issue by ascaron37** [coleifer/peewee#2519]
I have a problem testing my application with MySQL. I have two separate databases on one MySQL server, say DB1 and DB2. I create a DB Object with `db1 = MySQLDatabase('DB1', ...)`. All my models from DB2 have a schema attribute in the inner Meta class:
```
class DBModel(Model):
    class Meta:
        database = db1

class Model2(DBModel):
    id = AutoField()

    class Meta:
        schema = 'DB2'
```
In the application this works well, but for testing purposes I want to create and drop all tables. All models from the first DB get created and deleted properly. My problem now is that creating the tables in the second DB works as expected, but drop_tables does not drop the tables from the second DB.
```
    db1.create_tables((Model2,))  # creates the table in the second DB
    db1.drop_tables((Model2,))  # does not drop tables from second DB
```

Is my usage of the schema attribute a lucky incident from the standpoint that it works in my application? Can I force drop_tables to delete also the tables from the other schemas?

**Comment by coleifer** [comment]
So the reason the drop doesn't work is because Peewee, when "safe=True" (the default), attempts to check if the table exists in the current db. To get this working, you can just specify `safe=False`:

```python
# This will skip the check that the table exists, and then issue the
# appropriate drop table.
db1.drop_tables([Model2], safe=False)
```

**Comment by ascaron37** [comment]
Perfect, thank you!
