### ISSUE TITLE
Temporary Database in SQLite

### ISSUE THREAD

**Issue by RAbraham** [coleifer/peewee#2522]
Hi,

How do I create a temporary SQLite database[1] using `peewee`?
In Python, I would normally create it like this with an empty string
```python
import sqlite3
db = sqlite3.connect("")
```

[1] - Section 'Temporary Databases' at https://www.sqlite.org/inmemorydb.html

**Comment by mhsundstrom** [comment]
Peewee has excellent documentation, here:

http://docs.peewee-orm.com/en/latest/index.html

I suggest searching that for the string ':memory:', for example.

**Comment by coleifer** [comment]
`SqliteDatabase(':memory:')`

**Comment by RAbraham** [comment]
Hi,
Thanks for your quick response.
I think what I want may not be satisfied by the ':memory' config value. I'd like a temporary table which is slightly different and a different option than an `in memory` database which I think will be created by `SqliteDatabase(':memory:')`

From the above sqlite documentation:

> The sole difference is that a ":memory:" database must remain in memory at all times whereas parts of a temporary database might be flushed to disk if the database becomes large or if SQLite comes under memory pressure.

Therefore, there are different options in sqlite
- For a pure in-memory database, it's ` sqlite3.connect(":memory:")` which is what `SqliteDatabase(':memory:')` is a wrapper for?
- For a temporary database, it's `sqlite3.connect("")`, unless `SqliteDatabase(':memory:')` creates a temporary table and not an in memory table? I did read the documentation a bit  before I posted. so if I have missed this part, I apologize.

**Comment by coleifer** [comment]
I was not aware of this usage. In that case I'd recommend just using Python's tempfile facilities to initialize it with a named temp file, or explicitly mark the database as not being deferred:

```python
db = SqliteDatabase('')
db.deferred = False
```

**Comment by RAbraham** [comment]
I'll try that. Thank you very much.
