### ISSUE TITLE
Default rule is not being applied in SQL

### ISSUE THREAD

**Issue by AnitaErnszt** [coleifer/peewee#2524]
When creating new table the default constraints are not applied in SQL.

Example:
```
class Test(BaseModel):
    not_nullable = CharField()
    unique = CharField(null=True, unique=True)
    default_true = BooleanField(default=True)
    default_0 = IntegerField(default=0)
```

If I run print_table_sql(Test) I get below, which is seems to be the SQL statement executed.
```
class Test(BaseModel):
    not_nullable = CharField()
    unique = CharField(null=True, unique=True)
    default_true = BooleanField(default=True)
    default_0 = IntegerField(default=0)
```
    
I need to make sure these default rules are also applied in SQL. 
Is there something I'm missing? If there's no straightforward way of doing this what's the best way to get the default values out of the models?

Edit:
Managed to get the defaults using below code. Is there a better way to achieve the same?
```
for model in models:
    for name, field in model._meta.__dict__["fields"].items():
        print(field.default)
```

**Comment by coleifer** [comment]
>I need to make sure these default rules are also applied in SQL.

That's done by adding an explicit constraint:

```python
default_0 = IntegerField(constraints=[SQL('default 0')])
```

Please consult the docs. I don't write them for fun.

http://docs.peewee-orm.com/en/latest/peewee/models.html#default-field-values
