### ISSUE TITLE
Add and_, or_ functions ?

### ISSUE THREAD

**Issue by mkmoisen** [coleifer/peewee#2533]
Would you consider adding a public `and_` and `or_` function to peewee?

SQLAlchemy has this which helps readability, compared to the bitwise operators.

```
User.select().join(
     Tweet, JOIN.OUTER_JOIN, on=(Tweet.user == User.id)
).where(
     User.id == 123,
     or_(
        Tweet.id.is_null(),
        Tweet.timestamp > datetime.now() - timedelta(hours=1)
    )
)
```

vs

```
User.select().join(
     Tweet, JOIN.OUTER_JOIN, on=(Tweet.user == User.id)
).where(
    User.id == 123,
    (
        (Tweet.id.is_null()) | (Tweet.timestamp > datetime.now() - timedelta(hours=1))
    )
)
```

The bitwise style can be especially hard to read when you have some complicated, multi nesting where clause with many ands and ors.

I noticed you already do this logic in in `where` and `orwhere` functions in `peewee.py`. Something like the following should suffice:

```
def or_(*expressions):
    return reduce(operator.or_, expressions)

def and_(*expressions):
    return reduce(operator.and_, expressions)
```

**Comment by coleifer** [comment]
Peewee doesn't need these - you can just `from operator import or_` and use that directly.
