### ISSUE TITLE
filter IN is not working

### ISSUE THREAD

**Issue by tjengbudi** [coleifer/peewee#2542]
hello,
i try to use filter IN in peewee. but the generated code is not right
for example i want to select * from item where itemid in (abc, def)
but the peewee is create without "()"

so the peewee will create select * from item where itemid in abd, def
it will raised the error in mysql.

could you help me about this?

**Comment by coleifer** [comment]
You also contacted me via my personal site. Then opened an issue on GH. Please in the future use stackoverflow for basic questions like this.

Works fine, by the way:

```python
from peewee import *

db = SqliteDatabase(':memory:')

class Reg(Model):
    key = TextField()
    class Meta:
        database = db

db.create_tables([Reg])

for i in range(10):
    Reg.create(key='k%s' % i)


query = Reg.select().where(Reg.key.in_(['k1', 'k3', 'k5']))
for row in query:
    print(row.key)
```

Output:

```
k1
k3
k5
```
