### ISSUE TITLE
Peewee Is there any performance benefit to using the Query Builder over the ORM's dict/nametuple functions?

### ISSUE THREAD

**Issue by mkmoisen** [coleifer/peewee#2544]
I know that when the ORM returns python model objects, there is some overhead that we can eliminate by calling `.dicts()` or `.namedtuples`(). 

Is there any performance benefit to using the [query builder API](https://docs.peewee-orm.com/en/latest/peewee/query_builder.html) to return dicts/namedtuples, in comparison to returning dicts/namedtuples from the ORM API?

(I was going to ask this on stackoverflow but figured performance questions like this were not appropriate there).

Thank you.

**Comment by coleifer** [comment]
You'll have to profile it yourself, as it probably depends quite a bit on what types of queries you are executing. If you are really concerned about performance, using your database's python driver directly is going to be the fastest, of course. But you're using Python, so it's probably a somewhat mis-placed effort, to try to micro-optimize at this layer.
