### ISSUE TITLE
PostgreSQL with pg8000?

### ISSUE THREAD

**Issue by andy47** [coleifer/peewee#2550]
I'm developing on an Apple Silicon Mac. At the moment there isn't a way to install a binary wheel for psycopg2. So I'm looking at alternative PostgreSQL driver modules and the one that seems to work is [pg8000](https://github.com/tlocke/pg8000).

Is there a way in PeeWee to substitute psycopg2 with pg8000 as the underlying PostgreSQL db-api module?

I looked through the documentation but the only references I can find are to psycopg2.

**Comment by coleifer** [comment]
I'm not familiar with pg8000, but you can consult the docs on adding a new database implementation:

http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver

**Comment by andy47** [comment]
Thanks, I'll take a look.

**Comment by coleifer** [comment]
Also I'm not too familiar with the new mac stuff but its probably fairly easy to compile psycopg2 and save yourself a lot of hassle. I've built it myself on linux many times.
