### ISSUE TITLE
Missing TableFunction

### ISSUE THREAD

**Issue by AA-Stargazer** [coleifer/peewee#2551]
I'm trying to use the table function from "from playhouse.sqlite_ext import TableFunction"
but it gives this error: 
`Traceback (most recent call last):
  File ".../main5.py", line 46, in <module>
    from playhouse.sqlite_ext import TableFunction
ImportError: cannot import name 'TableFunction' from 'playhouse.sqlite_ext' (C:\Users\Enesu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playhouse\sqlite_ext.py)`

I tried to look at the sqlite_ext.py file and also couldn't find TableFunction. But I could find the class TableFunction in the _sqlite_ext.pyx file. I don't know how to solve this, so I thought it would be good to submit it here. If I've done something wrong, sorry for that, it's my first time.

Oh, and 1 more thing, in the sqlite_ext.py file, there is a try-except statement for importing. Maybe 1 of the files is the problem and it causes all other modules to not get imported
try:
    from playhouse._sqlite_ext import (
        backup,
        backup_to_file,
        Blob,
        ConnectionHelper,
        register_bloomfilter,
        register_hash_functions,
        register_rank_functions,
        sqlite_get_db_status,
        sqlite_get_status,
        TableFunction,
        ZeroBlob,
    )
    CYTHON_SQLITE_EXTENSIONS = True
except ImportError:
    CYTHON_SQLITE_EXTENSIONS = False

**Comment by AA-Stargazer** [comment]
I imported traceback to sqlite3_ext.py, and added "traceback.print_exc()"  to except statement, this is what gave:
  File "C:\Users\Enesu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playhouse\sqlite_ext.py", line 22, in <module>
    from playhouse._sqlite_ext import (
ModuleNotFoundError: No module named 'playhouse._sqlite_ext'

**Comment by coleifer** [comment]
You need to compile the c extension to use those.

**Comment by AA-Stargazer** [comment]
the .pyx files?
is GCC works on them?

**Comment by coleifer** [comment]
read the docs... http://docs.peewee-orm.com/en/latest/peewee/installation.html

**Comment by AA-Stargazer** [comment]
Thank you very much for both solution and fast response.
