### ISSUE TITLE
Missing parametter `seen` in docstring

### ISSUE THREAD

**Issue by Seluj78** [coleifer/peewee#2554]
As `seen` here (lol)

https://github.com/coleifer/peewee/blob/a6198b96f475a2ee9687f36eda1cbb539907c56a/playhouse/shortcuts.py#L14-L32

Cheers!

**Comment by coleifer** [comment]
That's used internally to avoid cycles in graph when recursing. Ignore.

**Comment by Seluj78** [comment]
Could you maybe rename it `_seen` and note it in the docstring just in case ? :) So you don't have other questions ;)
