### ISSUE TITLE
Function Filter is not Working

### ISSUE THREAD

**Issue by weaverjess** [coleifer/peewee#2561]
Referencing: https://stackoverflow.com/questions/60067772/from-rows-to-columns-using-peewee-orm

Event:Booking is a 1:many relationship.

I have a situation where I want to pull all Events that are still bookable just to generate a list.

```python
n_bookings = peewee.fn.COUNT(BookingModel.id)
query = EventModel.select(EventModel, n_bookings.filter(BookingModel.status != 'cancelled').alias('count')).join(
    BookingModel,
    peewee.JOIN.FULL_OUTER,
    on=(BookingModel.event_id == EventModel.id)
).group_by(
    EventModel
).having(
    having
).where(
    select_where
).order_by(
    EventModel.start_time.asc(),
    EventModel.id.asc()
).limit(canary_limit)
```

While appending on a filter doesn't break anything, it also seems to do nothing, as it is still counting bookings with a status of "cancelled".

**Comment by coleifer** [comment]
It's not `fn.filter()` -- you want `fn.COUNT(EventModel.id).filter(EventModel.status == 'cancelled')`

This is not a peewee issue, but rather an issue in incorrectly translating SQL to peewee APIs.

**Comment by weaverjess** [comment]
That's exactly what I have... except it's BookingModel, not EventModel. It doesn't work. Apologies for the title being slightly off. Updated.

**Comment by weaverjess** [comment]
To clarify:

```python
peewee.fn.COUNT(BookingModel.id).filter(BookingModel.status != 'cancelled')
```
does not work.
