### ISSUE TITLE
select_extend(): allow Model parameters

### ISSUE THREAD

**Issue by morrissimo** [coleifer/peewee#2563]
My use case: incremental construction a query, usually via a subclass that leverages a superclass helper method. I'd like to keep the select() definition as built by the super class, but allow the subclass to extend the select targets (and JOINs, etc) _without_ having to resort to something like this:

```python

class Base:

    @classmethod
    def build_query(cls):
        return cls.select(cls).join_from(cls, SomeOtherClass)

class Subclass(Base):

    @classmethod
    def build_query(cls):
        qs = super().build_query()
        qs = qs.select_extend(
            *cls._meta.fields.values(),
            *YetAnotherClass._meta.fields.values(),
        ).join_from(cls, YetAnotherClass)
        return qs
```

With the proposed change to `select_extend()`, the above code would look like:
```python

class Base:

    @classmethod
    def build_query(cls):
        return cls.select(cls).join_from(cls, SomeOtherClass)

class Subclass(Base):

    @classmethod
    def build_query(cls):
        qs = super().build_query()
        return qs.select_extend(cls, YetAnotherClass).join_from(cls, YetAnotherClass)
```

Granted, I have no idea what the LOE looks like - but it _smells_ like a potential easy win for readability. Alternatively: there's a more correct way to do this and I've simply veered off the path ;)

**Comment by coleifer** [comment]
Thanks, this was an accidental omission, and is now resolved.
