### ISSUE TITLE
local variable 'model_attr' referenced before assignment

### ISSUE THREAD

**Issue by marcpearson** [coleifer/peewee#2578]
Hi

I updated my project to version 3.14.10 and receive this error. The error come from the convert_dict_to_node function. From my observation, i think the code is missing the assignation to model_attr in the for piece in key.split('__'):

`def convert_dict_to_node(self, qdict):
        accum = []
        joins = []
        fks = (ForeignKeyField, BackrefAccessor)
        for key, value in sorted(qdict.items()):
            curr = self.model
            if '__' in key and key.rsplit('__', 1)[1] in DJANGO_MAP:
                key, op = key.rsplit('__', 1)
                op = DJANGO_MAP[op]
            elif value is None:
                op = DJANGO_MAP['is']
            else:
                op = DJANGO_MAP['eq']

            if '__' not in key:
                # Handle simplest case. This avoids joining over-eagerly when a
                # direct FK lookup is all that is required.
                model_attr = getattr(curr, key)
            else:
                for piece in key.split('__'):
                    model_attr = getattr(curr, piece) <==============================   Maybe this line is needed
                    for dest, attr, _, _ in self._joins.get(curr, ()):
                        if attr == piece or (isinstance(dest, ModelAlias) and
                                             dest.alias == piece):
                            curr = dest
                            break
                    else:
                        model_attr = getattr(curr, piece)
                        if value is not None and isinstance(model_attr, fks):
                            curr = model_attr.rel_model
                            joins.append(model_attr)
            accum.append(op(model_attr, value))
        return accum, joins`

With this new line my code work as before with the version 2.10.2

Thanks in advance

**Comment by coleifer** [comment]
I can't replicate the exception -- I agree that it looks like there may be a bug there, but I'm not sure how to trigger it. The following all work just fine:

```python
class TestDjangoFilterRegression(ModelTestCase):
    requires = [User, Tweet]

    def test_django_filter_regression(self):
        a, b, c = [User.create(username=u) for u in 'abc']
        Tweet.create(user=a, content='a1')
        Tweet.create(user=a, content='a2')
        Tweet.create(user=b, content='b1')

        query = User.filter(username='a')
        self.assertEqual(sorted([u.username for u in query]), ['a'])

        query = User.filter(username__in=('a', 'c', 'x'))
        self.assertEqual(sorted([u.username for u in query]), ['a', 'c'])

        query = Tweet.filter(user__username='a')
        self.assertEqual(sorted([t.content for t in query]), ['a1', 'a2'])

        query = Tweet.filter(user__username__in=('a', 'c'))
        self.assertEqual(sorted([t.content for t in query]), ['a1', 'a2'])
```

**Comment by marcpearson** [comment]
I think you need to have 3 level relations like this

```
class Hour(Model):
    project = ForeignKeyField(Project, backref="hours")

class Project(Model):
    client = ForeignKeyField(Client, backref="projects")

class Client(Model):
```

When i want to filter all the hours (of all projects) for a specific client, i can filter the hours with a Django criteria 'project__client=1' in previous version without error. The criteria is coming from the URL for a backend call

I hope this will help you

 N.B I do my best to write in english, i'm a french speaker. Sorry if is not sound good !

**Comment by coleifer** [comment]
Presumably if you are able to replicate the exception locally with your own code, you can communicate to me what is different about it vs the tests, or how to modify the tests to replicate it...

**Comment by coleifer** [comment]
Finally figured it out, will post a fix shortly.
