### ISSUE TITLE
test_sqlite_isolation fails with Python 3.11

### ISSUE THREAD

**Issue by mgorny** [coleifer/peewee#2580]
When running tests with Python 3.11.0b3, I get the following failure:

```pytb
$ python runtests.py 
Unable to import APSW extension tests, skipping.
Unable to import CockroachDB tests, skipping.
Unable to import sqlite C extension tests, skipping.
Unable to import mysql-connector, skipping mysql_ext tests.
Unable to import postgres extension tests, skipping.
Unable to import SQLCipher extension tests, skipping.
Unable to import sqlite extension tests, skipping.
.s.....................s..................................s.....................sss...........................................s.......ss.....................................s........ssss............................................s...................................s.........................................................................s..................................................................................................................................................................ssss........................................ss.............................s..................s...........ss............s...s.........s....ss......s..............s..............................................................ss.......................E............ssssssss.....................................sss.......ssssssssssssss.....s..................s..ss..............................
======================================================================
ERROR: test_sqlite_isolation (tests.db_tests.TestSqliteIsolation.test_sqlite_isolation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/peewee/tests/db_tests.py", line 461, in test_sqlite_isolation
    self.assertEqual(curs.fetchone()[0], 0)
                     ~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 894 tests in 5.487s

FAILED (errors=1, skipped=65)
```

**Comment by coleifer** [comment]
I don't see anything in the python 3.11 changelog that looks promising, any ideas?

**Comment by mgorny** [comment]
I'm going to try bisecting it.

**Comment by mgorny** [comment]
And here it is:

https://github.com/python/cpython/commit/3df0fc89bc2714f5ef03e36a926bc795dcd5e05a

```
commit 3df0fc89bc2714f5ef03e36a926bc795dcd5e05a
Author: Erlend Egeberg Aasland <erlend.aasland@innova.no>
Date:   Wed Aug 25 12:28:47 2021 +0200

    bpo-44976: Lazy creation of sqlite3 result rows (GH-27884)

 Modules/_sqlite/cursor.c | 84 +++++++++++++++++-------------------------------
 Modules/_sqlite/cursor.h |  3 --
 2 files changed, 29 insertions(+), 58 deletions(-)
```

**Comment by coleifer** [comment]
Thanks @mgorny very nice! My sense is that this may be a bug in `sqlite3` (cc @erlend-aasland if you see this).

**Comment by erlend-aasland** [comment]
Can you report this on the CPython bug tracker? Please include a minimal reproducer and as much information about your environment as possible.

Thanks!

**Comment by coleifer** [comment]
Sure I'll report and send a test if it's indeed a cpython issue. My sense is that it is but I'll let you know early next week

**Comment by erlend-aasland** [comment]
Great, thanks.

FYI, beta 4 is over-due, but is currently on hold bco. release blockers. I've notified the RM about this (possible) issue; if we could pin-point a minimal reproducer pretty quick, we could add this to the beta 4 release blockers, so we'd get a fix in the upcoming release.

I've tried to create a repro, but it's a little bit hard, since I've never used peewee, and I don't know its internal workings :(

**Comment by coleifer** [comment]
No worries, I'll take a look tomorrow (Mon) morning and let you know asap. Thx!

**Comment by coleifer** [comment]
Since this seems to me quite definitively a CPython / sqlite3 issue, I will close here.

**Comment by erlend-aasland** [comment]
Thanks a lot for your investigations, @coleifer! I've marked python/cpython#94028 as a release blocker. Hopefully we'll find a solution within the next few days.

**Comment by erlend-aasland** [comment]
I have a fix for this in python/cpython#94042. If you have the possibility to test the fix before I merge it, I'd appreciate it, @mgorny.

**Comment by mgorny** [comment]
I can confirm that applying this patch to cpython causes peewee tests to pass.

**Comment by mgorny** [comment]
(I've applied it on top of 3.11.0b3)

**Comment by erlend-aasland** [comment]
Great, thank you!

**Comment by coleifer** [comment]
Thank you both @mgorny and @erlend-aasland for the help finding and fixing this.
