### ISSUE TITLE
Weird query operator behavior

### ISSUE THREAD

**Issue by wpnbos** [coleifer/peewee#2582]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/33165624/175815958-5a702699-c45e-457b-9399-68daeff3c4d8.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/33165624/175815980-dba5b463-a9c0-45d8-ae7c-f9e183621754.png">

It would seem the query operators here just don't work properly. 

I'm using a Postgres database, both fields are of type `real`.

**Comment by coleifer** [comment]
I have no idea what these screenshots are supposed to show. Post a self-contained, self-explanatory code snippet.

**Comment by coleifer** [comment]
Possibly this is to do with floating point precision. You need to use numeric / decimal field for prices.

**Comment by coleifer** [comment]
Confirmed this is floating point stuff.

```
In [1]: from peewee import *

In [2]: db = PostgresqlDatabase('peewee_test')

In [3]: class K(Model):
   ...:     price = FloatField()
   ...:     name = TextField()
   ...:     class Meta:
   ...:         database = db
   ...: 

In [4]: db.create_tables([K])

In [5]: K.create(price=123.45, name='12345')
Out[5]: <K: 1>

In [6]: K.create(price=123.44, name='12344')
Out[6]: <K: 2>

In [7]: K.create(price=123.46, name='12346')
Out[7]: <K: 3>

In [8]: K.select().where(K.price < 123.45).tuples()[:]
Out[8]: [(1, 123.45, '12345'), (2, 123.44, '12344')]

In [9]: K.select().where(K.price >= 123.45).tuples()[:]
Out[9]: [(3, 123.46, '12346')]
```

Next time submit code like ^^

**Comment by wpnbos** [comment]
> 

Thanks a lot! I changed my FloatFields to DecimalFields and I can confirm that this remedied my issue. 

My sincerest apologies for the lazy issue. I'll make sure to post self-contained, self-explanatory code snippets next time.
