### ISSUE TITLE
Snowflake Support

### ISSUE THREAD

**Issue by sfc-gh-pmonteiro** [coleifer/peewee#2588]
I really like this ORM but it lacks Snowflake support. I'm a python seasoned developer and willing to help Peewee support Snowflake. What is the best way to support this project? Is there any documentation on adding support to new DBs?

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver

Looks like there's a driver with dbapi support so hopefully it will be rather easy.
