### ISSUE TITLE
How to create enum in peewee ?

### ISSUE THREAD

**Issue by raoehtesham79** [coleifer/peewee#2600]
I am trying to create enum data type in peewee model but there is not such thing in peewee . Kindly, please help me to sort out this. Here is an example , what I want:
class travel_mode(enum.Enum):
    Air = 1
    Sea = 2
    NA = 3
but how to use it in peewee model

**Comment by coleifer** [comment]
#630 

https://gist.github.com/b1naryth1ef/607e92dc8c1748a06b5d

**Comment by raoehtesham79** [comment]
Thanks for your response . I have seen this method . This is also not working.
