### ISSUE TITLE
allow non-atomic get_or_create?

### ISSUE THREAD

**Issue by mayli** [coleifer/peewee#2605]
The current [get_or_create](https://github.com/coleifer/peewee/blob/eeff376be5af089e7d3849284a1c1d71b5df215f/peewee.py#L6626-L6627) requires the db supports `atomic()`, which is not necessary in most cases.
Is it possible add a parameter to allow non-atomic `get_or_create`?

**Comment by coleifer** [comment]
You are welcome to write your own implementation and place it on a `Base` model class you use.
