### ISSUE TITLE
Pylint complains that subclasses of `ColumnBase` leave `__iter__()` unimplemented

### ISSUE THREAD

**Issue by jborman-exos** [coleifer/peewee#2612]
Related to the fix released for #2606, running pylint over a local subclass of `ColumnBase` raises the following:

```
Method '__iter__' is abstract in class 'ColumnBase' but is not overridden (abstract-method)
```

Raising `NotimplementedError` implies that a concrete class is meant to implement this abstract method. According to the python [docs](https://docs.python.org/3/library/exceptions.html#NotImplementedError), if `__iter__` is never to be implemented on a subclass of `ColumnBase`, then it should be set to `None`

**Comment by coleifer** [comment]
No problem, fixed.
