### ISSUE TITLE
Add Example for Idiomatic Message Queue Pattern

### ISSUE THREAD

**Issue by zackees** [coleifer/peewee#2614]
Hi there. Great piece of software. I'm a novice at databases which has brought me to this solution.

I'm looking for examples on the internet for how to use Peewee to implement a Message Queue. The challenges here is that the message queue is highly sensitive to locking multiple entries in the queue so that they can be processed. As the items are processed their entries to have status updates so that in the case of a power failure, the system has enough information to pick up where it left off.

It looks like the `atomic` functionality will do what I need it to. But as a novice I lack the knowledge on whether my solution will be proper enough. Or whether there is some hidden, large grain implicit table lock that won't show a problem until the point of launch when the database starts getting hot.

I believe it would really help PeeWee's adoption if a simple, performant Message Queue implementation was added to the examples. This would allow dumb people like me to build off an idiomatic implementation and incrementally add features until it's satisfies the requirements.

Thanks again!

**Comment by coleifer** [comment]
I'm not going to do your homework for you, but there is a ton of discussion on this on the web. Some of it depends on what database you use, postgres probably being the most commonly discussed.

* https://github.com/que-rb/que - https://github.com/que-rb/que/blob/master/lib/que/poller.rb#L60-L113
* https://github.com/QueueClassic/queue_classic - https://github.com/QueueClassic/queue_classic/blob/master/lib/queue_classic/queue.rb#L92-L111

**Comment by coleifer** [comment]
If you're looking for something simpler, you can always refer to this, which is Peewee-specific:

https://github.com/coleifer/huey/blob/master/huey/contrib/sql_huey.py

**Comment by zackees** [comment]
> I'm not going to do your homework for you, but there is a ton of discussion on this on the web.

Dude, I've been a software developer for nearly 20 years in embedded land. It's possible one can be a novice to databases and also not a student, at the same time.
