### ISSUE TITLE
Pwiz exporting of postgres materialized view

### ISSUE THREAD

**Issue by surfer190** [coleifer/peewee#2618]
Pwiz exports an existing db into models that can be written to a file.

The [documentation mentions that the `-v` flag](https://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=generating%20models#pwiz-a-model-generator) can be used to export views.

I tried using `pwiz` with the `-v` flag and a materialized view I have was not exported.

In a [previous issue](https://github.com/coleifer/peewee/issues/1052) it was mentioned that peewee does not generate the DDL (data definition language) for the creation of views.

So the correct course of action is to manually define the model for the view?

**Comment by coleifer** [comment]
For now I'm going to hold off on implementing this, as our standard way of introspecting the columns associated with a table (or non-materialized view) does not seem to work with materialized views. With regular tables or views, we can run something like:

```sql
select column_name, is_nullable, data_type, column_default
from information_schema.columns
where table_name = 'the table or view name'
```

Unfortunately, it looks like the process for introspecting a materialized view is different, see: https://stackoverflow.com/questions/39179253/postgresql-get-materialized-view-column-metadata

For now you'll just want to create these manually.

**Comment by surfer190** [comment]
If the view you are manually defining does not have a primary key - read about [models without a primary key](https://docs.peewee-orm.com/en/latest/peewee/models.html#models-without-a-primary-key)
