### ISSUE TITLE
Unable to install peewee on py 3.10 on windows - ERROR: No .egg-info directory found in C:\Users\*User*\AppData\Local\Temp\pip-pip-egg-info-fhrb40k6

### ISSUE THREAD

**Issue by jurezic** [coleifer/peewee#2630]
Always getting the same error, except everytime I get another tag in the end of the trace.

Setup-
Python 3.10. 
setuptools-65.5.0
pip-22.3

poetry-
1.1.13.

What I have tried:
Update python/pip/setuptools
Install over poetry - same error

Does anyone have an idea how to proceed?

**Comment by coleifer** [comment]
Can you try doing:

```
git clone https://github.com/coleifer/peewee
cd peewee
python setup.py egg_info
```

**Comment by jurezic** [comment]
Sorry, forgot to mention, I have also downloaded peewee-3.15.3.tar.gz and tried
- py -3.10 -m pip install helpers/peewee-3.15.3.tar.gz
- poetry add helpers/peewee-3.15.3.tar.gz
- 
And again receive-
ERROR: No .egg-info directory found in C:\Users\*user*\AppData\Local\Temp\pip-pip-egg-info-8qd21w02

**Comment by coleifer** [comment]
Can you please try the commands in my comment, and paste the output here?

**Comment by jurezic** [comment]
This is the output of commands from your comment - 

```
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
unable to compile sqlite3 C extensions - missing headers?
C:\Users\**\Documents\Projects\**\**\helpers\peewee\setup.py:110: UserWarning: Could not find libsqlite3, SQLite extensions will not be built.
  warnings.warn('Could not find libsqlite3, SQLite extensions will not '
running egg_info
creating peewee.egg-info
writing peewee.egg-info\PKG-INFO
writing dependency_links to peewee.egg-info\dependency_links.txt
writing top-level names to peewee.egg-info\top_level.txt
writing manifest file 'peewee.egg-info\SOURCES.txt'
reading manifest file 'peewee.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests.py'
warning: no files found matching 'playhouse\*.c'
warning: no files found matching 'playhouse\pskel'
warning: no files found matching 'playhouse\tests\README'
adding license file 'LICENSE'
writing manifest file 'peewee.egg-info\SOURCES.txt'
```

**Comment by coleifer** [comment]
Looks like you don't have a C compiler installed, although I'm unsure why `pip` is complaining because the egg-info is successfully written. Anyways, I suggest either:

1. install a c compiler
2. in the `peewee` directory created earlier, just run `python setup.py install` and skip `pip` altogether.
