### ISSUE TITLE
datetime compare not working correctly with single digit

### ISSUE THREAD

**Issue by marcelkb** [coleifer/peewee#2636]
MariaDBConnectorDatabase:
DateTimeField:

PriceArchive.select().where(PriceArchive.time <= datetime.datetime(2022, 10, 10, 00, 00)).order_by(
                PriceArchive.time.desc()).limit(1).get()  works correctly

with datetime.datetime(2022, 10, 1, 00, 00) it gives first entry in Database, in my case something from August.

Concrete every day above 9 works, only single digits dates not

**Comment by marcelkb** [comment]
seems to be a problem of missing data ;)

**Comment by coleifer** [comment]
I hope it turns up! Sometimes when I lose something, I throw something similar away and watch where it goes.
