### ISSUE TITLE
Noob question about accesing meta data

### ISSUE THREAD

**Issue by ionesculiviucristian** [coleifer/peewee#2638]
Hi. I have the following class:

```py
class Migration(BaseModel):
    name = CharField(null=True, unique=True)

    class Meta:
        table_name = "migrations"
```
How can I access the table name without using it like this: 
```py
Migration._meta.table.__name__
```
Need something more "public" kinda way.

**Comment by James4Ever0** [comment]
you can modify the source code just like me

**Comment by James4Ever0** [comment]
the code is just a single file. you need to search and navigate.

**Comment by ionesculiviucristian** [comment]
> you can modify the source code just like me

Thanks for the response but I have no idea what you are referring to. What source code is that? Worst case I'm gonna add the same ```table_name``` on the parent class which is definitely not the way to do it.

**Comment by James4Ever0** [comment]
the other issue i have recently posted.

**Comment by coleifer** [comment]
The table name is accessible via:

```
ModelClass._meta.table_name
```

The full list of available meta options is here: http://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata
