### ISSUE TITLE
Bug: insert_many execute in PostgreSQL returns cursor instead of int row count

### ISSUE THREAD

**Issue by bravegag** [coleifer/peewee#2642]
Bug: insert_many execute in PostgreSQL returns cursor instead of int row count. In SQLite it returns the int number of rows inserted while in PostgreSQL it returns a cursor.

[In the documentation it states that `insert_many(...).execute()` returns the number of inserted rows.](https://docs.peewee-orm.com/en/latest/peewee/api.html?highlight=insert_many#Model.insert_many)

**Comment by coleifer** [comment]
And if you scrolled further, you'll see: ![screenshot](https://user-images.githubusercontent.com/119974/199052251-48224a6c-cb9c-492e-9102-91894e6deebb.png)

>The default return value is the number of rows modified. However, when using Postgres, Peewee will return a cursor by default that yields the primary-keys of the inserted rows. To disable this functionality with Postgres, use an empty call to returning().

The above will return you the actual psycopg2 cursor.

To get the rowcount instead: https://docs.peewee-orm.com/en/latest/peewee/api.html?highlight=insert_many#Insert.as_rowcount

**Comment by bravegag** [comment]
Ok, thanks! will this same API work with any vendor or is it PostgreSQL specific?
