### ISSUE TITLE
Bug: ``insert_many`` with tuple insert first character of string 

### ISSUE THREAD

**Issue by Sherlock-Homlmes** [coleifer/peewee#2645]
**Model:**
```
class Tags(PeeweeModel):
    id = IntegerField()
    name = TextField()

    class Meta:
        db_table = 'tags'
```

**Insert function:**
```
def create_sample_tags():
    list_tags=[
        ('val1-1'),
        ('val2-1'),
        ('val3-1')
    ]
    Tags.insert_many(list_tags, fields=[Tags.name]).execute()
``` 

**Result:**
![image](https://user-images.githubusercontent.com/19506491/201047088-764636b3-9569-43e7-835c-1ec80384b231.png)

It failed to insert the value with tuple.
When I insert_many with dictionary, it still works.

Peewee: 3.15.3
Database: Postgres 15

**Comment by rudyryk** [comment]
The thing is `('val1-1')` is not a tuple, it's just a string.

```
>>> v = ('val1-1')
>>> type(v)
<class 'str'>
```

For tuple It shoud be `('val1-1',)`.

**Comment by coleifer** [comment]
This is not a big but you have a mistake in your syntax. @rudyryk has the correct solution.

Also do you really think something THIS foundational would be broken? Next time triple check your own code before creating issues.
