### ISSUE TITLE
NameError: name 'Counter' is not defined in example

### ISSUE THREAD

**Issue by stefaneidelloth** [coleifer/peewee#2646]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [7], line 35
     28 users = (User
     29          .select(User, tweet_ct.alias('ct'))
     30          .join(Tweet, JOIN.LEFT_OUTER)
     31          .group_by(User)
     32          .order_by(tweet_ct.desc()))
     34 # Do an atomic update
---> 35 Counter.update(count=Counter.count + 1).where(Counter.url == request.url)

NameError: name 'Counter' is not defined

**Comment by coleifer** [comment]
Yeah the readme is just showing that to illustrate a point. It's hopefully obvious what the intent is.

**Comment by stefaneidelloth** [comment]
No, its not. I thought Counter is a missing Class.
