### ISSUE TITLE
affairs exist concurrency Error

### ISSUE THREAD

**Issue by DreamBizideal** [coleifer/peewee#2650]
![QQ截图20221121183253](https://user-images.githubusercontent.com/82210587/203028544-30f73d9f-3684-485f-90e5-eefee34f40a3.png)
`if __name__ == '__main__':
    t1 = threading.Thread(target=sell2)
    t2 = threading.Thread(target=sell2)

    t1.start()
    t2.start()

    t1.join()
    t2.join()`

sorry i don't speak english
我开启了两个线程 一个线程在被修改完成后 另一个线程查不到实时数据  只能查到修改之前的数据（操作都在with db.atomic() as txn:）
并且我没有rollback()

不使用 db.atomic()就正常查询到  但是我需要事务
添加了事务即使数据库修改过数据  在db.atomic()里进行查询也不会查到当前的数据 只会查到之前的

**Comment by coleifer** [comment]
You need to re-fetch it or use update... returning (if your database supports it).
