### ISSUE TITLE
Type support

### ISSUE THREAD

**Issue by gp-slick-coder** [coleifer/peewee#2659]
Type support in VSCode would be nice.

![image](https://user-images.githubusercontent.com/1906169/206869371-b9555cef-e9d1-4d66-a27f-5fc61968aae8.png)

**Comment by taufiq** [comment]
Hey, why was this closed? Is there already a solution for this?

**Comment by gp-slick-coder** [comment]
I already did some research ;-) unfortunately, the creator of this nice ORM doesn't like type hints. Coming from Typescript, python does miss a nice modern ORM solution :-(

**Comment by coleifer** [comment]
You can create your own hints, but this particular question has been asked and answered several times since type hints were introduced.

**Comment by Avasam** [comment]
The maintainer has made clear their stance over python typing annotations over the years across multiple issues. And is seemingly not a burden they intend to take. If you'd like peewee type annotations for your code, I'd suggest using https://pypi.org/project/types-peewee/ . To which you can contribute over at https://github.com/python/typeshed/tree/main/stubs/peewee

**Comment by coleifer** [comment]
I'm grateful to everyone who's helped maintain the stubs over the years - it is a thankless task, certainly from my side anyways, but I think the writing is on the wall about typing so I'm considering bringing them in-repo as a peewee.pyi stub. Main thing I wanna get is `ModelClass.field` and `model_inst.field` sorted.
