### ISSUE TITLE
bulk_create() doesn't work with server-side default values 

### ISSUE THREAD

**Issue by gondolio** [coleifer/peewee#2661]
It appears that bulk_create does not work with server-side default values specified in [constraint](https://docs.peewee-orm.com/en/latest/peewee/models.html?highlight=table%20generation#:~:text=can%20use%20the-,constraints,-parameter%20to%20specify). 

For example, with this model:
```
class MyModel(Modell):
    datetime = DateTimeField(constraints=[SQL("DEFAULT CURRENT_TIMESTAMP")])
    class Meta:
        database = my_postgresql_db
```

The following works:
`MyModel().save()`

whereas this fails:
```
MyModel.bulk_create([MyModel()])

# IntegrityError: null value in column "datetime" violates not-null constraint DETAIL:  Failing row contains (2, null).
```

Any suggestions on how to bulk create using server-side defaults?

**Comment by coleifer** [comment]
Yes, this is because `bulk_create()` is explicit about inserting all fields. If you want finer-grained control, for (e.g.) fields w/server-side defaults, you should just use `insert_many()` and be explicit.

**Comment by gondolio** [comment]
Got it - so first convert the objects to dicts (via `**object.__data__`) and then feed it into `insert_many()`. Thx!
