### ISSUE TITLE
Suggestion: SQLiteDatabase option to disable automatic DB creation

### ISSUE THREAD

**Issue by MrBillium** [coleifer/peewee#2662]
There does not appear to be a way to disable DB creation if not found.

e.g db = SqliteDatabase('mydb.db',  pragmas={'foreign_keys': 1}, **create_db=False**)

Why this could be helpful:

I just went down a rabbit hole moving  running code to an Apache server where I forgot to set **home=/var/www/myapp** in my apache .conf file.
The result was everything ran fine without errors but the DB in the same dir as the rest of the code was not found so an empty copy was created by Peewee in /home/<user> 
This led to troubleshooting why a fully functional db was not returning any data.

In most cases of deployment or migration the database should not NEED  be 'created' and preventing it from happening iwould immediately show up as an error as it should.

**Comment by coleifer** [comment]
Going to pass
