### ISSUE TITLE
Suggestion: .is_ and .is_not query lookups

### ISSUE THREAD

**Issue by frosthamster** [coleifer/peewee#2663]
It'd be great to have an option to write `is` and `is not` lookups via functions `Model.field.is_(value)` and not `Model.field >> value` which is unreadable, similar to `Model.field.in_(value)`. It's useful for writing queries against nullable boolean fields, like `Model.is_finished.is_not(True)`
I can submit a pr if you want that change too.

**Comment by coleifer** [comment]
We use `.is_null()`: http://docs.peewee-orm.com/en/latest/peewee/api.html#ColumnBase

**Comment by frosthamster** [comment]
But we can use it only for generating `is null` and `it not null`, not for `is not true`
