### ISSUE TITLE
Unable to import module 'app': No module named 'playhouse'

### ISSUE THREAD

**Issue by bitfede** [coleifer/peewee#2665]
Hello,

I am working on an [AWS Chalice](https://aws.github.io/chalice/quickstart.html#deploying) project, and I chose peewee as the ORM for the postgresql DB we have.

When I run things locally with `chalice local` I can run my api with no problem, I'm able to CRUD normally.

When I deploy my microservice using `chalice deploy` and I go test it out I encounter an error 500. When looking into the logs I see this message multiple times:

```
Traceback (most recent call last):
2023-01-03 22:39:57.665000 d87bac [ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'playhouse'
```

I cannot do `poetry add playhouse`, because I get the following error: `Could not find a matching version of package playhouse`. What can you suggest me to do to fix this?

Thank you so much

**Comment by coleifer** [comment]
Peewee, the package, includes `playhouse` so I'd assume you would just need to ensure that `peewee` is installed in your environment and then `playhouse` should work. I am not familiar with chalice, and questions such as this are better suited to StackOverflow.

**Comment by bitfede** [comment]
@coleifer Thank you for getting back to me very fast, I posted the question on StackOverflow.

@Insighttful really appreciate your response. Can you elaborate a bit more on why uploading the zip to S3 then load it into Lambda might make peewee's playhouse work compared to running `chalice deploy`? Thank you so much.

**Comment by teddybee** [comment]
I have the same issue in localhost. Somehow I cant install peewee by poetry or pip.
Both say its already installed, but I can`t see the lib in the .env dir. Also vscode missing it as well, when I import it.
Windows env if its matters.
