### ISSUE TITLE
[Feature Request] Event hooks for peewee

### ISSUE THREAD

**Issue by Zheaoli** [coleifer/peewee#2670]
For now, I'm looking for event hooks in peewee, but I think we don't support event hooks for peewee yet(I have already read the docs, please feel free to correct me if I'm wrong)

I think it's an excellent choice to support event hooks like Django ORM or sqlalchemy like below.

```python
from peewee import event

event.listen(client, "before_cursor_execute", callback_func)
```

The code above means that the callback function will be executed before the final SQL start to be executed.

It's a good feature for a lot of people. For example, we can inject the trace ID in SQL by using SQL comment using https://google.github.io/sqlcommenter/python/sqlalchemy/

FYI https://docs.sqlalchemy.org/en/14/core/events.html

**Comment by Ehco1996** [comment]
peewee already have signal support see more in https://docs.peewee-orm.com/en/latest/peewee/playhouse.html#signals

Does this feature meets your needs?

**Comment by coleifer** [comment]
@Zheaoli - I'm going to pass, as the generally-supported approach for Peewee users has been to override the `Database.execute_sql()` method in these types of cases (where you want before or after a query execution), for example. You can extend this to other core methods like `commit()`, etc.
