### ISSUE TITLE
excuse, how could i use a variable as table's field

### ISSUE THREAD

**Issue by EasyArch-lyy** [coleifer/peewee#2675]
eg: 
create table test
(
	id int auto_increment primary key,
	name  varchar(255) null,
);

field = 'name'
query_list = list(test.select().where(test.field=='cc').dicts())

AttributeError: type object 'test' has no attribute 'field'

want to know the api

**Comment by coleifer** [comment]
Post stuff like this on stackoverflow in the future. You use `getattr(test, field) == 'cc'`.
