### ISSUE TITLE
Can't query with unicode character

### ISSUE THREAD

**Issue by groggyegg** [coleifer/peewee#2683]
I have a column containing this type of data `{"zh": "\u65e5\u97e9\u5267"}` and when I query it with this code `Video.select().where(Video.director.contains('\u65e5\u97e9\u5267'))` , I'm not getting any result. It only works when I query non-unicode text e.g. `Video.select().where(Video.director.contains('"zh"'))`.

**Comment by coleifer** [comment]
This probably has to do with the collation you're using. Is this MySQL?

**Comment by groggyegg** [comment]
No, I’m using SQLite

**Comment by coleifer** [comment]
Wait so your data is *literally* the Unicode escapes? If so have you tried double escaping the forward quote?

**Comment by groggyegg** [comment]
> Wait so your data is _literally_ the Unicode escapes? If so have you tried double escaping the forward quote?

That seems to fix the problem. I'm suprised that I didn't realized that :astonished:
Thanks!
