### ISSUE TITLE
Undocumented parameter `sender` for `playhouse.signals.Signal.disconnect`.

### ISSUE THREAD

**Issue by real-yfprojects** [coleifer/peewee#2686]
https://github.com/coleifer/peewee/blob/f88fa44a29601ca2de9fe492fda11b1fb28fb412/playhouse/signals.py#L25

There is a `sender` parameter. However there is no such parameter here:

https://github.com/coleifer/peewee/blob/f88fa44a29601ca2de9fe492fda11b1fb28fb412/docs/peewee/playhouse.rst?plain=1#L2740

**Comment by real-yfprojects** [comment]
You just don't want to update/improve the documentation of your library or why are you closing it without a comment. Others will find that pretty unwelcoming.

**Comment by coleifer** [comment]
7246a7f2b8c5adbae33180af3c817601560dc33a
