### ISSUE TITLE
`CharField.max_length` has no effect on a Sqlite database

### ISSUE THREAD

**Issue by calvinweb** [coleifer/peewee#2694]

**Comment by coleifer** [comment]
That is correct, and is down to the way SQLite implements text affinity columns.

If you want to enforce a max length you can add a check constraint or implement a subclass of charfield that overrides the `db_value()` method to trim the string.

**Comment by calvinweb** [comment]
> That is correct, and is down to the way SQLite implements text affinity columns.
> 
> If you want to enforce a max length you can add a check constraint or implement a subclass of charfield that overrides the `db_value()` method to trim the string.

but i think this should be done by peewee itself because databases should have same behavour
