### ISSUE TITLE
FOR UPDATE not supported by CockroachDatabase

### ISSUE THREAD

**Issue by arel** [coleifer/peewee#2695]
I believe this is a bug. I am getting the following error when I try to use `for_update()` in Cockroach DB:

```
  File "/workspace/nuhom-api/.venv/lib/python3.10/site-packages/peewee.py", line 2509, in __sql__
    raise ValueError('FOR UPDATE specified but not supported '
graphql.error.graphql_error.GraphQLError: FOR UPDATE specified but not supported by database.
```

It looks like `CockroachDatabase` believes `FOR UPDATE` is not supported (which may have been the case in an earlier version): https://github.com/coleifer/peewee/blob/b5cee5e99bcc0b20010646cb52c60f8e37dd620a/playhouse/cockroachdb.py#L65

But, in the CockroachDB docs, it states that `FOR UPDATE` is now supported: https://www.cockroachlabs.com/docs/stable/select-for-update.html

And, even though CockroachDB does not support  [locking strengths](https://www.cockroachlabs.com/docs/v22.2/select-for-update#locking-strengths) (`FOR SHARE` or `FOR KEY SHARE`), the syntax is also supported to be compatible with Postgres.

**Comment by coleifer** [comment]
Thank you for letting me know, I'll get this fixed.

In the meantime you can set the flag manually when you do your database initialization.

```
db = ...
db.for_update = True
```

**Comment by arel** [comment]
Thanks!

**Comment by coleifer** [comment]
When I enabled the flag the crdb tests are locking up and failing, so something must be special about their implementation. If you're able to look into it that'd be great but if not I'll get around to it.

**Comment by coleifer** [comment]
I'm just marking the locked tests to skip for CockroachDB. I have no clue why it isn't working like Postgres or MySQL. This should be resolved now by:

0031ca565651bc3fd4a12ba347c4cb76c99a643f and 7357d9303a07826bab539a508f05b534f6fcbcc1
