### ISSUE TITLE
peewee-value-returns-to-its-default-after-few-seconds-bug

### ISSUE THREAD

**Issue by instasck** [coleifer/peewee#2697]
https://stackoverflow.com/questions/75804965/peewee-value-returns-to-its-default-after-few-seconds-bug

Can you explain this ?

**Comment by instasck** [comment]
OK ISSUES IS
That a pointer to the database is not refreshing automatically, it pointing to local data in memory so holding old data.

**Comment by coleifer** [comment]
Don't spam the issues -- please try to have a bit of patience.

**Comment by instasck** [comment]
Well it took me 2 hours before I found the issue.
it is not clear about refreshing data from the doc...
