### ISSUE TITLE
Create aware datetime objects for TimestampField

### ISSUE THREAD

**Issue by IBuckton** [coleifer/peewee#2700]
**Description**
With `TimestampField(utc=True)` it returns a naive datetime object. This is not recommended as they are treated by many datetime methods as local times.

**Expected behaviour**
Return an aware datetime object to avoid confusion, per the recommendation in [datetime docs](https://docs.python.org/3.11/library/datetime.html#datetime.datetime.utcfromtimestamp)

**Suggested change**
```python
    if self.utc:
-       value = datetime.datetime.utcfromtimestamp(value)
+       value = datetime.datetime.fromtimestamp(value, datetime.timezone.utc)
```

**Comment by coleifer** [comment]
You can't compare naive and tz-aware datetimes, so this is a non-starter unfortunately. The idea is that your naive datetime *is* already in UTC so the tzinfo is meaningless and provides flexibility -- that is *also* why `utc=False` by default. We can't be switching the return value between naive and tz-aware based on the value of the `utc` parameter.

My suggestion would be to subclass `TimestampField` and override the `python_value()` if you wish, e.g.

```python
class UTCTimestampField(TimestampField):
    def __init__(self, **kwargs):
        kwargs['utc'] = True
        super(UTCTimestampField, self).__init__(**kwargs)
    def python_value(self, value):
        value = super(UTCTimestampField, self).python_value(value)
        if value is not None:
            return value.replace(tzinfo=datetime.timezone.utc)
```

**Comment by coleifer** [comment]
628668437ef29f57d287e72d006d49908c3c5664 should provide compatibility with the deprecations in 3.12 and onwards.

**Comment by theunraveler** [comment]
I'm seeing this when upgrading to Python 3.12 for `DateTimeField`s. Does something similar need to be done there, or should I be using `TimestampField`s instead on SQLite?

```
peewee.py:3252: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
```

**Comment by coleifer** [comment]
@theunraveler - thanks, this should be addressed in https://github.com/coleifer/peewee/commit/53f81f2edc6750107c11f4bbc5d54faf9eca2177
