### ISSUE TITLE
How to avoid fetch-then-create pattern, when fk id already known?

### ISSUE THREAD

**Issue by anentropic** [coleifer/peewee#2706]
New to Peewee... I'm sure this is easy but could not find an example in the docs

In a case like this:

```python
def start_game(user_id, subject: str) -> GameSession:
    user = User.get(User.id == user_id)
    game = GameSession.create(user=user, subject=subject)
    return game
```

How do I avoid first fetching the `User`, and instead create `GameSession` directly using the `user_id` already known for the foreign key field

Is there something like Django's `user__id` relation-spanning syntax, or implicit `_id` suffixed fields for foreign keys?

**Comment by coleifer** [comment]
You can just do this:

```
game = GameSession.create(user=user_id, subject=subject)
```
