### ISSUE TITLE
 pwiz generates detailed field attributes

### ISSUE THREAD

**Issue by GuoGuo54** [coleifer/peewee#2707]
The peewee model generated by pwiz based on the database table is too simple， like：

class NameModel(Model):
    name = CharField(null=True)
    status = IntegerField(default=11, index=True)

    class Meta:
        table_name = 'name_model'

But generally we need more detailed field attributes，like (max_length, verbose):
 
class NameModel(Model):
    name = CharField(max_length=128, null=True, verbose_name='name')
    status = IntegerField(default=11, index=True, verbose_name='status')

    class Meta:
        table_name = 'name_model'

**Comment by coleifer** [comment]
Going to pass. Column comments is mysql-specific, and the varchar max length is negligible in my view, since adding it to the introspected field doesn't change any behavior (and it usually isn't enforced anywhere).
