### ISSUE TITLE
How to "NOT" create index on a "unique" field

### ISSUE THREAD

**Issue by eddysnjack** [coleifer/peewee#2713]
i have o model looking like this.

```
class User(BaseModel):
    id = BigIntegerField(unique=True)
    first_name = TextField()
    last_name = CharField(null=True)
    username = CharField(unique=True, null=True, index=False)
    phone = CharField(null=True)
    deleted = BooleanField(null=True)
    is_bot = BooleanField(null=True)
    bio = CharField(null=True)
    photo = TextField(null=True)
    roles = BigIntegerField()
```

After tables are created when i check db file with sqlstudio i saw "username" index on user table. I dont want this, it is unique but should be null as well. I'm getting "UNIQUE constraint failed: user.username" error when I try to update or create a user without a username second time. I believe that index is the cause.

<img width="870" alt="Screen Shot 2023-04-24 at 13 03 17" src="https://user-images.githubusercontent.com/38407276/233966648-e8504dc1-a15d-4fc8-974e-ad0f4ae42bba.png">

**Comment by coleifer** [comment]
What database engine are you using?

**Comment by eddysnjack** [comment]
> What database engine are you using?

how can i check that?

**Comment by coleifer** [comment]
You presumably declared it yourself... SqliteDatabase, MySQLDatabase, PostgresqlDatabase...

**Comment by coleifer** [comment]
At any rate it seems to be working fine for me:

```python
db = SqliteDatabase(':memory:')

class User(db.Model):
    username = TextField(null=True, unique=True)

User.create_table()

User.create(username=None)
User.create(username=None)
User.create(username='u1')
try:
    User.create(username='u1')
except IntegrityError:
    pass
else:
    assert False, 'expected integrity error not raised'

for u in User:
    print(u.username)
```

Correctly prints out:

```
None
None
u1
```

**Comment by eddysnjack** [comment]
> You presumably declared it yourself... SqliteDatabase, MySQLDatabase, PostgresqlDatabase...

oh i see SqliteDatabase in this case. i misinterpreted "engine", sorry :)
