### ISSUE TITLE
Calling save fails when PK is provided but record does not exist yet.

### ISSUE THREAD

**Issue by keiranjprice101** [coleifer/peewee#2717]
In this example:

```python
class CustomerPeewee(BaseModel):
    email = CharField()

    class Meta:
        db_table = "customer"

customer = CustomerPeewee()
customer.id = 4
customer.email = "example@example.com"
customer.save()
```

No record is created and 0 is returned. If this is intended it feels counter intuitive as the docs seem to make no mention of this behaviour not being possible

**Comment by coleifer** [comment]
The docs do make mention of this, there is in fact a section on this: http://docs.peewee-orm.com/en/latest/peewee/models.html#manually-specifying-primary-keys

At the most basic, though, this is all you need to add if you are doing this one-off:

```
customer.id = 4
customer.email = "example@example.com"
customer.save(force_insert=True)
```
