### ISSUE TITLE
Fastapi db connection doc

### ISSUE THREAD

**Issue by AndyJiangIsTaken** [coleifer/peewee#2718]
Hi, 
Here's the peewee doc I'm referring to:
https://docs.peewee-orm.com/en/latest/peewee/database.html#fastapi

According to the FastAPI doc,
the startup & shutdown events are for when the application, not request here:
https://fastapi.tiangolo.com/advanced/events/#startup-event

Let me know I'm missing something, new here.

**Comment by coleifer** [comment]
The FastAPI docs have a thorough section, I probably need to just link it since your comment is correct and my docs may be misleading.

https://fastapi.tiangolo.com/advanced/sql-databases-peewee/#make-peewee-async-compatible-peeweeconnectionstate

**Comment by coleifer** [comment]
Updated doc here: http://docs.peewee-orm.com/en/latest/peewee/database.html#fastapi
