### ISSUE TITLE
PeeWee ForeignKeyField error. IntegrityError: (1215, 'Cannot add foreign key constraint')

### ISSUE THREAD

**Issue by Ezyhoo** [coleifer/peewee#2719]
I have code like below:

```
import datetime

import peewee as pw
import os

my_db = pw.MySQLDatabase(database=os.getenv("DB_NAME"), host=os.getenv("DB_HOST"), port=os.getenv("DB_PORT"),
                            user=os.getenv("DB_USER"), passwd=os.getenv("DB_PASSWORD")


class MySQLModel(pw.Model):
    """A base model class that will use MySQL"""

    class Meta:
        database = my_db


class UnsignedBigAutoField(pw.BigAutoField):
    field_type = 'BIGINT UNSIGNED UNIQUE AUTO_INCREMENT'


class UnsignedAutoField(pw.AutoField):
    field_type = 'INT UNSIGNED UNIQUE AUTO_INCREMENT'


class User(MySQLModel):
    id = UnsignedBigAutoField(primary_key=True)
    alias = pw.CharField(max_length=16, unique=True, null=False)
    date_created = pw.DateTimeField(default=datetime.datetime.now)


class Ticket(MySQLModel):
    id = UnsignedBigAutoField(primary_key=True)
    user = pw.ForeignKeyField(User, backref="tickets", field="id", on_delete="RESTRICT", on_update="CASCADE")
    date_created = pw.DateTimeField(default=datetime.datetime.now)

my_db.create_tables([User, Ticket])

```
The last line of the code when creating ForeignKey produces error:

> peewee.IntegrityError: (1215, 'Cannot add foreign key constraint')

I checked the datatype(Bitint), and unique/non-null flag are all setup correctly for User table.

Couldn't figure out what went wrong here. I created the ForeignKey in MySqlWorkBench manually in Ticket table without a problem.

Any help would be appreciated.

**Comment by coleifer** [comment]
The issue is that Peewee sees your subclass of `BigAutoField` and infers that it should use BIGINT instead of BIGINT UNSIGNED. The fix is to override the `field_type` on the foreign-key, e.g.:

```python

class UnsignedForeignKey(pw.ForeignKeyField):
    field_type = 'BIGINT UNSIGNED'

class Ticket(MySQLModel):
    id = UnsignedBigAutoField(primary_key=True)
    user = UnsignedForeignKeyField(User, backref="tickets", field="id", on_delete="RESTRICT", on_update="CASCADE")
    date_created = pw.DateTimeField(default=datetime.datetime.now)
```

**Comment by coleifer** [comment]
Just a thought here, but are you absolutely positive you need 2^64 vs 2^63? It is probably easier and saner approach to just use plain old `BigAutoField` rather than unsigned. Plain old bigint should still be able to store 9,223,372,036,854,775,808 unique values... if each row was a mere 8 bytes (the size of the unsigned value) this is thousands of petabytes.

**Comment by Ezyhoo** [comment]
Fair argument actually. I agree the plain old BigAutoField is Saner and cleaner in PeeWee. But the team working on the project uses unsigned as a norm. Thank you coleifer for your suggestion!
