### ISSUE TITLE
get() method returns integer

### ISSUE THREAD

**Issue by Ezyhoo** [coleifer/peewee#2721]
Peewee version: 3.16.2
Python version: 3.9
DB Engine: MySQL

I have the DB table schema like follow:

```
class UnsignedBigAutoField(pw.BigAutoField):
    field_type = 'BIGINT UNSIGNED AUTO_INCREMENT'

class User(MySQLModel):
    id = UnsignedBigAutoField(primary_key=True)
    alias = pw.CharField(max_length=16, unique=True, null=False)
    date_created = pw.DateTimeField(default=datetime.datetime.now)
```

A user has been added to the DB, with id=1, alias="abc", date_created with the correct time.

When trying to retrieve the user object like [the doc](http://docs.peewee-orm.com/en/latest/peewee/querying.html#selecting-a-single-record)
`print(User.get(User.alias == 'abc'))`

The program prints out 1. Same return value using get_by_id().

When changing the alias to a non-existing one ("123"). The exception contains the SQL query which looks correct for get():

> <Model: User> instance matching query does not exist:
> SQL: SELECT `t1`.`id`, `t1`.`alias`, `t1`.`date_created` FROM `user` AS `t1` WHERE (`t1`.`alias` = %s) LIMIT %s OFFSET %s
> Params: ['123', 1, 0]

Why is my get() not returning the object like the doc demos?

**Comment by coleifer** [comment]
It's a model. Peewee just shows the primary key when printed by default. Try changing your code to:

```python
u = User.get(User.alias == 'abc')
print(u)
print(type(u))
```
