### ISSUE TITLE
Unexpected results from Peewee query on PostgreSQL (Supabase) when using Less Than Operator

### ISSUE THREAD

**Issue by shiroyasha9** [coleifer/peewee#2725]
Hello,

I'm using Peewee as an ORM for PostgreSQL hosted on Supabase. I have a table, let's call it **ABC**, with a numeric column named **factor**. The table has the following rows in the factor column: 
`0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50`

I'm trying to run the following query:

```query = ABC.select(ABC.factor).where(ABC.factor < 40.5)```

I expect this query to return all rows where factor is less than 40.5, which should include the numbers from 0 to 40. However, the actual result I'm getting includes only the numbers from 0 to 35. The number 40, which is less than 40.5, is not included for some reason. I am suspecting that peewee implicitly converts 40.5 to 40, and hence the behaviour. If I change it to <=, the code works and I get 40 in the output as well.

I'm not sure why this is happening. I'd appreciate any help or insights into what might be going wrong.

Attached screenshots (please ignore the different names)
Code:
![image](https://github.com/coleifer/peewee/assets/48734821/65df8ffd-1290-4b67-b134-6bf361ecc6f6)
Output:
![image](https://github.com/coleifer/peewee/assets/48734821/07bf3570-210e-4e34-b3e0-abc392cb58ff)
Database Column:
![image](https://github.com/coleifer/peewee/assets/48734821/0d3850e5-b6cd-4f40-b627-a4f2c22a6e9c)

Thank you!

**Comment by coleifer** [comment]
How did you declare the `ABC.factor` field? Are you using an `IntegerField`, by chance? By default Peewee coerces the right-hand side of things like comparisons to use the same type (int in this case).

Example behaviors:

```
from peewee import *

db = PostgresqlDatabase('peewee_test')

class Int(db.Model):
    factor = IntegerField()
class Numeric(db.Model):
    factor = DecimalField(decimal_places=5, max_digits=12)

db.drop_tables([Int, Numeric])
db.create_tables([Int, Numeric])

for i in range(0, 50, 5):
    Int.create(factor=i)
    Numeric.create(factor=i)

# Here peewee is converting the float (20.5) to an int for the
# comparison, which results in `< 20`.
q = Int.select(Int.factor).where(Int.factor < 20.5)
print([r for r, in q.tuples()])
# Your issue: Prints [0, 5, 10, 15]

# Tell peewee not to apply conversion:
q = Int.select(Int.factor).where(Int.factor < Value(20.5, converter=False))
print([r for r, in q.tuples()])
# OK: Prints [0, 5, 10, 15, 20]

# Do not coerce 20.5 (rhs term) to int:
q = Int.select(Int.factor).where(Int.factor.cast('numeric') < 20.5)
print([r for r, in q.tuples()])
# OK: Prints [0, 5, 10, 15, 20]

q = Numeric.select(Numeric.factor).where(Numeric.factor < 20.5)
print([r for r, in q.tuples()])
# OK: Prints [Decimal('0.00000'), ... Decimal('15.00000'), Decimal('20.00000')]

db.drop_tables([Int, Numeric])
```

You have some options:

1. Use the proper field type to match your data, e.g. NUMERIC (`DecimalField`)
2. Tell peewee not to apply a conversion
3. Explicitly cast to avoid the conversion
4. Change your query to be written as `<= 20`, which may be closer to the original intent(?)

**Comment by shiroyasha9** [comment]
The first solution worked! I had the column set to Int and changed it to Decimal later and forgot to update the schema. Thanks a lot for helping me, and great work on the package!
