### ISSUE TITLE
Selecting all columns from `Table`

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#2726]
When I define a `Table` without explicitly passing it the columns and do something like

```python
my_table = peewee.Table('my_table', schema='public').bind(database)
for row in my_table.select().limit(10):
    print(row)
```

I just get empty dictionaries. In this situation, a better solution would be to return all the columns (`SELECT my_table.*`) the same way that `Model.select()` does. Would this be possible, or is there a workaround with the `peewee.SQL` function?

For a rationale, normally if I get to need a `Table` instead of a `Model` (usually when working with temporary tables as intermediate steps of a large query), I may need to carry the columns for several queries, and sometimes I may not know the column names. In raw SQL the `*` takes care of that.

**Comment by coleifer** [comment]
If you want to do that, then you can write:

```python
my_table.select(SQL('*'))
```

**Comment by albireox** [comment]
I think that will only work in some simple cases, when you're selected from only one table. The moment that you join that table with a different one the `SQL('*')` will return all the columns from all the joined tables, which is not the same behaviour as `Model`. It would be useful to be able to do

```python
R.select().join(T, on=(T.c.pk == R.c.pk))
```

or 

```python
R.select(R, T.c.pk).join(T, on=(T.c.pk == R.c.pk))
```

similar to what's possible in `Model`.

**Comment by coleifer** [comment]
Gotcha! Yes you're correct, I did not read the issue closely enough. To simplify this (because it was a bit convoluted) I added a helper property to the base class used by Table, so now you would write:

```
R.select(R.star).join(T, ...)

R.select(R.star, T.c.pk).join(T, ...)
```

**Comment by albireox** [comment]
Fantastic, thanks!
