### ISSUE TITLE
Bulk inserts with defaults only 

### ISSUE THREAD

**Issue by andycasey** [coleifer/peewee#2730]
Hello,

I have one table that only has a primary key, which is used as a unique reference for other tables.

I cannot seem to perform bulk inserts on this table using any of the documented strategies. The behaviour is the same with Postgresql and SQLite. Here is a minimum reproducible example:

```python
from peewee import (
    AutoField,
    Model,
    SqliteDatabase
)
database = SqliteDatabase(":memory:")

class Spectrum(Model):

    pk = AutoField()

    class Meta:
        database = database

database.create_tables([Spectrum])

# This works
Spectrum.create()

# This does not:
Spectrum.bulk_create([Spectrum(), Spectrum()]

# This does not:
Spectrum.insert_many([{}, {}]).execute()

# This does not:
Spectrum.insert([{}, {}]).execute()
```

In all cases the exception is the same:

```python
File /.../peewee.py:3216, in Database.execute_sql(self, sql, params, commit)
   3214 cursor = self.cursor(commit)
   3215 try:
-> 3216     cursor.execute(sql, params or ())
   3217 except Exception:
   3218     if self.autorollback and not self.in_transaction():

OperationalError: near ")": syntax error
```

Where:
```python
ipdb> sql
'INSERT INTO "spectrum" () VALUES (), ()'
ipdb> params
[]
```

Is there something I am doing wrong here? 

Should `peewee` be providing the "DEFAULT VALUES" literal if an empty dictionary is given to `.insert`, `.insert_many`, or `.bulk_create`?

Thanks 🚀

**Comment by coleifer** [comment]
I don't believe it is possible with SQL to do multiple inserts in a single query w/DEFAULT VALUES. It works just fine for a single instance, which is what Peewee currently supports, e.g.

```python
# Works fine, INSERT INTO spectrum DEFAULT VALUES;
Spectrum.create()
Spectrum.insert().execute()
```

There is no way to, for example, write `insert into specture default values, default values,...`.

**Comment by coleifer** [comment]
Your best bet is just to use a transaction and run the inserts in a loop if you need more than 1.

```
with db.atomic() as txn:
    for _ in range(...):
        rowid = Spectrum.insert().execute()
```

**Comment by andycasey** [comment]
Thanks. For any reader that comes across this, another option that I came up with was to add a useless column to `Spectrum` (e.g., a `BitField` for some `flags` column that I might want) and to supply that same value for each record in `insert_many(...)`:

```python
(
  Spectrum
  .insert_many(
      [
          { "flags": 0}, 
          { "flags": 0}
      ]
  ).execute()
)
```

**Comment by coleifer** [comment]
If you use Postgres, you would probably just use a `sequence`.
