### ISSUE TITLE
BUG？After mysql call insert_many, execute always returns 1?

### ISSUE THREAD

**Issue by ponponon** [coleifer/peewee#2732]
```python
from loguru import logger
from peewee import *
import settings
from playhouse.shortcuts import ReconnectMixin


host = settings.MYSQL_CONFIG.host
port = settings.MYSQL_CONFIG.port
username = settings.MYSQL_CONFIG.username
password = settings.MYSQL_CONFIG.password
database_name = settings.MYSQL_CONFIG.database_name


class ReconnectMySQLDatabase(ReconnectMixin, MySQLDatabase):
    pass


db = ReconnectMySQLDatabase(
    database=database_name,
    host=host,
    port=port,
    user=username,
    password=password,
    charset='utf8mb4'
)


class User(Model):
    name = CharField(unique=True)
    age = IntegerField()

    created_at = DateTimeField(
        null=False,
        constraints=[SQL('DEFAULT CURRENT_TIMESTAMP')],
        help_text='使用数据库时间'
    )
    updated_at = DateTimeField(
        null=False,
        constraints=[
            SQL('DEFAULT CURRENT_TIMESTAMP'),
            SQL('ON UPDATE CURRENT_TIMESTAMP'),
        ]
    )

    class Meta:
        database = db
        table_name = 'user'


model_set = [User]


db.drop_tables(model_set)
db.create_tables(model_set)


users = [
    {'name': 'John', 'age': 25},
    {'name': 'Jane', 'age': 30},
    {'name': 'John', 'age': 28},  # 重复的数据
]

query = User.insert_many(users).on_conflict_ignore()

logger.debug(str(query))

affected_rows = query.execute()

print("affected_rows: ", affected_rows)
```

Output results:

```shell
2023-05-30 18:33:54.214 | DEBUG    | __main__:<module>:25 - INSERT IGNORE INTO `user` (`name`, `age`) VALUES ('John', 25), ('Jane', 30), ('John', 28)
affected_rows:  1
```

`select * from user;` By sql query, the database, indeed, inserted two rows of data. But why does execute return a value of 1?

<img width="512" alt="图片" src="https://github.com/coleifer/peewee/assets/38725104/03359d31-da9f-4f79-9bd1-e534e5498465">

**Comment by ponponon** [comment]
This issue is currently only found on mysql, if you are using sqlite, execute returns 2 instead of 1

```python
from peewee import *

database = SqliteDatabase('my_database.db')


class User(Model):
    name = CharField(unique=True)
    age = IntegerField()

    class Meta:
        database = database


# 创建表
User.create_table()

# 批量插入数据并忽略重复项
users = [
    {'name': 'John', 'age': 25},
    {'name': 'Jane', 'age': 30},
    {'name': 'John', 'age': 28},  # 重复的数据
]

query = User.insert_many(users).on_conflict_ignore()
affected_rows = query.execute()
print("affected_rows: ", affected_rows)

# 删除表
User.drop_table()
```


Output results:


```shell
affected_rows:  2
```

**Comment by coleifer** [comment]
Try this and let me know if it addresses the issue:

```python
query = User.insert_many(users).on_conflict_ignore()
query = query.as_rowcount()

affected_rows = query.execute()
```

**Comment by coleifer** [comment]
Yeah, looks like it's working correctly:

```
class User(db.Model):
    username = CharField(unique=True)
    age = IntegerField()

db.drop_tables([User])
db.create_tables([User])

iq = User.insert_many([
    {'username': 'u1', 'age': 10},
    {'username': 'u2', 'age': 20},
    {'username': 'u1', 'age': 100},
    {'username': 'u2', 'age': 50},
    {'username': 'u3', 'age': 30},
]).on_conflict_ignore()

iq = iq.as_rowcount()
print(iq.execute())
```

Correctly prints:

```
3
```

**Comment by ponponon** [comment]
> Yeah, looks like it's working correctly:
> 
> ```
> class User(db.Model):
>     username = CharField(unique=True)
>     age = IntegerField()
> 
> db.drop_tables([User])
> db.create_tables([User])
> 
> iq = User.insert_many([
>     {'username': 'u1', 'age': 10},
>     {'username': 'u2', 'age': 20},
>     {'username': 'u1', 'age': 100},
>     {'username': 'u2', 'age': 50},
>     {'username': 'u3', 'age': 30},
> ]).on_conflict_ignore()
> 
> iq = iq.as_rowcount()
> print(iq.execute())
> ```
> 
> Correctly prints:
> 
> ```
> 3
> ```

Very good, learned more methods and details

**Comment by ponponon** [comment]
I believe this is the bug



```python
from loguru import logger
from peewee import *
import settings


host = settings.MYSQL_CONFIG.host
port = settings.MYSQL_CONFIG.port
username = settings.MYSQL_CONFIG.username
password = settings.MYSQL_CONFIG.password
database_name = settings.MYSQL_CONFIG.database_name

db = MySQLDatabase(
    database=database_name,
    host=host,
    port=port,
    user=username,
    password=password,
    charset='utf8mb4'
)


class User(Model):
    name = CharField(unique=True)
    age = IntegerField()

    created_at = DateTimeField(
        null=False,
        constraints=[SQL('DEFAULT CURRENT_TIMESTAMP')],
        help_text='使用数据库时间'
    )
    updated_at = DateTimeField(
        null=False,
        constraints=[
            SQL('DEFAULT CURRENT_TIMESTAMP'),
            SQL('ON UPDATE CURRENT_TIMESTAMP'),
        ]
    )

    class Meta:
        database = db
        table_name = 'user'


model_set = [User]
db.drop_tables(model_set)
db.create_tables(model_set)

users = [
    {'name': '1', 'age': 25},
    {'name': '2', 'age': 30},
    {'name': '3', 'age': 28},  # 重复的数据
]

query = User.insert_many(users).on_conflict_ignore()
affected_rows = query.execute()
print("affected_rows: ", affected_rows)


users = [
    {'name': '4', 'age': 25},
    {'name': '5', 'age': 30},
    {'name': '4', 'age': 28},  # 重复的数据
]

query = User.insert_many(users).on_conflict_ignore()
affected_rows = query.execute()
print("affected_rows: ", affected_rows)

```

The output is as follows:

```shell
affected_rows: 1
affected_rows: 4
```



This is not what is expected



If the return value of query.execute, which represents the last_insert_id, then the output should be

```shell
3
5
```

If the return value of query.execute is rows_affected, then the output should be

```shell
3
2
```

and the truth is that nothing

**Comment by ponponon** [comment]
I know why, for mysql bulk inserts, the insert_id returned is the id of the first row, not the last 

For example, in the following sql, the insert_id returned is the id of ('abc', 25), not the id of ('d2ui', 25)!

```sql
INSERT IGNORE INTO `user` (`name`, `age`) VALUES ('abc', 25), ('sau', 25), ('d2ui', 25).
```

<img width="920" alt="图片" src="https://github.com/coleifer/peewee/assets/38725104/81227b48-4bc6-40e3-a6b0-7c77aee8902e">

**Comment by ponponon** [comment]
> The value of `cursor.lastrowid` is the first ID inserted with MySQL. When doing a bulk insert and combining it with `IGNORE` you can see that Peewee is returning the correct values for `lastrowid`:
> 
> ```python
> class User(db.Model):
>     username = CharField(unique=True)
> 
> db.drop_tables([User])
> db.create_tables([User])
> 
> iq = User.insert_many([
>     {'username': 'u1'},
>     {'username': 'u2'},
>     {'username': 'u1'},
>     {'username': 'u2'},
>     {'username': 'u3'},
> ]).on_conflict_ignore()
> 
> print(iq.execute())
> 
> iq = User.insert_many([
>     {'username': 'u4'},
>     {'username': 'u5'},
> ]).on_conflict_ignore()
> print(iq.execute())
> 
> for row in User:
>     print(row.id, row.username)
> ```
> 
> Prints:
> 
> ```
> 1  <--- first id of first row inserted ("u1")
> 6 <--- first id of first row inserted ("u4")
> 1 u1
> 2 u2
> 3 u3
> 6 u4
> 7 u5
> ```
> 
> In short, peewee is working correctly.

Yes, that's right, thank you for your help
