### ISSUE TITLE
HowTo: Run Peewee Query without Model Definition 

### ISSUE THREAD

**Issue by RAbraham** [coleifer/peewee#2741]
Hi,
I would like to use the wonderful query design as shown here: https://docs.peewee-orm.com/en/latest/peewee/query_examples.html#query-examples

As an ORM, I understand, one has to define the Model beforehand e.g. `Members`. Is there an underlying abstraction(or how can I make one) where I can directly call the table giving string as an input?

Assuming a function `table`, is there something like

```python
# peewee code: query = Facility.select()
# desired interface 1
query = table("facilities").select()
```
Actually, what I'm going for is to be able to call Python functions. Are there peewee functions, which I can wrap around to get the following interface(if it does not exist)
```python
# peewee code: query = Facility.select().where(Facility.membercost > 0)
# desired interface 1
non_zero = lambda cost: cost > 0
query = table("facilities").select().where(non_zero, "membercost")
```
I plan to experiment with your wonderful support for Python UDFs hopefully to get somewhere close to what I want.

**Comment by coleifer** [comment]
The Peewee query-builder APIs provide lower-level abstractions for querying. [There is a dedicated section](http://docs.peewee-orm.com/en/latest/peewee/query_builder.html#declaring-tables).

```python
# Explicitly declare columns
Person = Table('person', ('id', 'first', 'last'))

Note = Table('note', ('id', 'person_id', 'content', 'timestamp'))

# Do not declare columns, they will be accessed using magic ".c" attribute
Reminder = Table('reminder')

# Example queries:
query = (Note
         .select(Note.content, Note.timestamp, Person.first, Person.last)
         .join(Person, on=(Note.person_id == Person.id))
         .where(Note.timestamp >= datetime.date(2018, 1, 1))
         .order_by(Note.timestamp)
         .namedtuples())

for row in query:
    print(row.timestamp, '-', row.content, '-', row.first, row.last)

# Using dynamic columns:
today = datetime.date.today()
tomorrow = today + datetime.timedelta(days=1)

query = (Reminder
         .select(Reminder.c.alarm, Note.content)
         .join(Note, on=(Reminder.c.note_id == Note.id))
         .where(Reminder.c.alarm.between(today, tomorrow))
         .order_by(Reminder.c.alarm))
for row in query:
    print(row['alarm'], row['content'])
```

For what it's worth, if you delegate all your filtering logic to UDFs then you may be forcing the database to do a full table scan *and* call into Python (which must acquire and release the GIL) for each row examined, which may be prohibitively slow.

**Comment by RAbraham** [comment]
Thanks for the detailed example!

Oh, I wasn't aware of the performance implications :(. I was actually inspired by an example of peewee where an udf was called in a `where` function. I just looked at the documentation again to find it but I can't find it anymore(I feel bad every time because you have excellent documentation)
- If I understood it correctly, do you design it differently to mitigate the performance hit?
- the performance hit may only be for filters, but I'm guessing that it's not an issue for scalar, aggregate and table functions?

**Comment by coleifer** [comment]
Yes you can absolutely use UDFs in the where clause -- the issue I merely wanted to point out was that, in the absence of any other conditions, this will almost certainly need a full-table scan.

Here's a silly example:

```python
import time
from peewee import *

db = SqliteDatabase(':memory:')

class Reg(db.Model):
    key = TextField()
    value = IntegerField(index=True)

db.create_tables([Reg])

@db.func()
def is_lessthan(i, j):
    return i < j

with db.atomic():
    for i in range(0, 100000, 100):
        Reg.insert_many([
            ('k%05d' % j, j)
            for j in range(i, i + 100)]).execute()                                       


s = time.perf_counter()
list(Reg.select().where(Reg.value < 1000))
print(round(time.perf_counter() - s, 3))

s = time.perf_counter()
list(Reg.select().where(fn.is_lessthan(Reg.value, 1000)))                                
print(round(time.perf_counter() - s, 3))
```

The output on my laptop is:

* 0.009s for the "value" < 1000
* 0.05s for the udf version

The query plans:

* SEARCH reg USING INDEX reg_value (value<?)
* SCAN reg

**Comment by RAbraham** [comment]
Thank you very much for providing that example!
