### ISSUE TITLE
The postgres database table I am trying to query has special characters in the column field names

### ISSUE THREAD

**Issue by lfaller-korrobio** [coleifer/peewee#2747]
Specifically: some column names contain a `$`.

I tried the following:

```python
>>> for c in table.select().limit(5):
...     print(c.name$)
  File "<stdin>", line 2
    print(c.name$)
                ^
SyntaxError: invalid syntax
```

I also tried `print(c."name$")` and `print(c.'name$')` but none of these worked.

Any suggestions for how to get around this?

Thank you!

**Comment by coleifer** [comment]
Where is your table being declared? Is this a model class, and if so, can you share the definition? Typically you would:

```python
class SomeTable(Model):
    # Use a valid python access for the column "name$".
    name = TextField(column_name='name$')

for c in SomeTable.select().limit(5):
    print(c.name)
```

**Comment by lfaller-korrobio** [comment]
Thanks for the quick feedback! The database was not declared using peewee. It was set up by someone else. I used `models = generate_models(pg_db, schema='a_schema')` to infer the tables and columns.

**Comment by lfaller-korrobio** [comment]
This one worked:

```
print(c.name_)
```

Thanks for the help!
