### ISSUE TITLE
Inclusion of field names in ManyToMany "through" table naming

### ISSUE THREAD

**Issue by LordBex** [coleifer/peewee#2749]
**Hello,**

I encountered an issue when using ManyToManyField in Peewee with two or more fields referencing the same table. It seems that the current implementation generates the same "through" table for both relationships. This results in a conflict as both fields are trying to use the same intermediate table.

For instance, consider the following example:

```python
Copy code
class Locations(BaseModel):
    name = CharField(max_length=255)


class Travel(BaseModel):
    purpose = CharField(max_length=110)
    start = ManyToManyField(Locations)
    end = ManyToManyField(Locations)

```

**In this case, Peewee generates the following tables:**

locations
travel
travel_locations_through
Both Travel.start and Travel.end are using the same "through" table travel_locations_through, which causes the conflict.

A possible solution to this problem would be to include the field names (start and end in the example) in the generated "through" table name. This way, we would have two distinct "through" tables, one for each relationship, such as travel_start_locations_through and travel_end_locations_through.

```python 
    # line 5634 in peewee.py
    def _create_through_model(self):
        lhs, rhs = self.get_models()
        tables = [model._meta.table_name for model in (lhs, rhs)]
        tables.insert(1, self.column_name)   # add column name for generation

        class Meta:
            database = self.model._meta.database
            schema = self.model._meta.schema
            table_name = '%s_%s_%s_through' % tuple(tables)   # add one more %s_
            indexes = (
                ((lhs._meta.name, rhs._meta.name),
                 True),)

        params = {'on_delete': self._on_delete, 'on_update': self._on_update}
        attrs = {
            lhs._meta.name: ForeignKeyField(lhs, **params),
            rhs._meta.name: ForeignKeyField(rhs, **params),
            'Meta': Meta}

        klass_name = '%s%sThrough' % (lhs.__name__, rhs.__name__)
        return type(klass_name, (Model,), attrs)
```

This change would avoid conflicts and provide a more intuitive naming convention that aligns with the relationships defined in the model.

Best Regards, LordBex

**Comment by coleifer** [comment]
This would be backwards-incompatible and cause trouble for a large number of users.

Peewee provides a mechanism for setting the through model explicitly, so in cases where you either a) want more control, or b) have multiple many-to-many between the same tables, you can fall back to declaring the through table explicitly:

```python
db = SqliteDatabase(':memory:')

class Permission(db.Model):
    name = TextField()

DeniedThroughDeferred = DeferredThroughModel()

class User(db.Model):
    name = TextField()
    allowed = ManyToManyField(Permission)
    denied = ManyToManyField(Permission, through_model=DeniedThroughDeferred)

class DeniedThrough(db.Model):
    permission = ForeignKeyField(Permission)
    user = ForeignKeyField(User)

DeniedThroughDeferred.set_model(DeniedThrough)

db.create_tables([
    Permission,
    User,
    User.allowed.through_model,
    User.denied.through_model])

p1, p2, p3 = [Permission.create(name=n) for n in ('p1', 'p2', 'p3')]
u1, u2, u3 = [User.create(name=n) for n in ('u1', 'u2', 'u3')]

u1.allowed.add([p1, p2, p3])
u2.allowed.add(p2)
u2.denied.add([p1, p3])
u3.allowed.add(p3)
u3.denied.add(p1)

for u in User.select():
    print(u.name)
    print('  Allowed:')
    for p in u.allowed:
        print('  *', p.name)
    print('  Denied:')
    for p in u.denied:
        print('  *', p.name)
    print('')

# Correctly prints:
"""
u1
  Allowed:
  * p1
  * p2
  * p3
  Denied:

u2
  Allowed:
  * p2
  Denied:
  * p1
  * p3

u3
  Allowed:
  * p3
  Denied:
  * p1
"""
```

Alternatively you can subclass and extend `ManyToManyField` to provide your own implementation of `_create_through_model` following any naming convention you like.
