### ISSUE TITLE
db_value inside hybrid property and expression

### ISSUE THREAD

**Issue by petemarvin** [coleifer/peewee#2750]
class Sample(BaseModel):

        col1= CharField()
        @hybrid_property
        def is_complete(self):
            return my_function(self.col1)

        @is_complete.expression
        def is_complete(cls):
            return my_function(cls.col1)

I have a conceptual code above. Querying Sample.select() returns okay wherein it returns the column _is_complete_ as True or False. But when I put where clause it gives me error Sample.select().where(Sample.is_complete==True)

When I try to do research I can pass the value to **my_function**(cls.col1.db_value()). But gives me an error _Field.db_value() missing 1 required positional argument: 'value'_

I believe cls.col1 returns as <CharField: Sample.col1>

**Comment by coleifer** [comment]
I don't believe you understand how hybrid properties work, please consult the docs: https://docs.peewee-orm.com/en/latest/peewee/playhouse.html#hybrid
