### ISSUE TITLE
Int to float conversion does not work for IntegerField

### ISSUE THREAD

**Issue by AntonKyrychekCrit** [coleifer/peewee#2753]
I have encountered a conversion problem. here is the case and sql below.
```python
class Transaction(Model):
    warranty = IntegerField(default=0)

Transaction.select(
    (Transaction.warranty * 1.0 / 100.0).alias('warranty_float'),
    (Transaction.warranty / 100.0).alias('warranty_int'),
)

```

seems like the first float converts to the int automatically. for some reason,  other ones Nodes are fine and NOT converting the float to int, as i use it all the time.

here is what i get in SQL:

```sql 
      (("t1"."warranty" * 1) / 100.0) AS "warranty_float",
      ("t1"."warranty" / 100) AS "warranty_int",
```

is this intended behavior?

**Comment by coleifer** [comment]
Peewee tries (generally) to apply the conversion rule of the column to any values or expressions selected using that column. If `warranty` is an integer column, peewee tries to apply `int` to values selected.

To avoid this you probably want an explicit cast:

```python
db = SqliteDatabase(':memory:')

class Tx(db.Model):
    warranty = IntegerField()


Tx.create_table()
Tx.create(warranty=50)
Tx.create(warranty=5)

# use "real" or "numeric" or whatever the appropriate type is for your db.
q = Tx.select(
    (Tx.warranty.cast('real') / 100.0).alias('w1'),
    (Tx.warranty.cast('real') / 100).alias('w2'))
for row in q:
    print(row.w1, row.w2)

# 0.5 0.5
# 0.05 0.05
```

**Comment by coleifer** [comment]
Other options here:

```python
# Tell peewee to leave the value as-is
q = Tx.select((Tx.warranty / Value(100.0, converter=False)).alias('w1'))
for row in q:
    print(row.w1)

# 0.5
# 0.05

# Tell peewee to not apply the field's converter:
q = Tx.select((Tx.warranty.coerce(False) / 100.).alias('w1'))
for row in q:
    print(row.w1)

# 0.5
# 0.05
```

**Comment by AntonKyrychekCrit** [comment]
it';s just there is no homogeneity between `peewee.fn.SUM(Tx.warranty) / 100.0` and `Tx.warranty / 100.0` one will coerce another will not ...

**Comment by coleifer** [comment]
I'd argue that the bigger issue is using an integer to store a value you intend to use as a numeric. I'd suggest changing it to a DecimalField. That way you get decimal division which is probably what you want.

The rules are pretty simple, and there are ways to control the behavior.

Lastly we never convert sum (see https://github.com/coleifer/peewee/blob/master/peewee.py#L1589 ). Some aggregate functions always return a number so those are returned as-is.

**Comment by AntonKyrychekCrit** [comment]
The numeric is larger then integer and i have a lot of these fields, this is a sizable improvement for row length.  I will check sum coz it seems to me that i coerced it...
Thank you!
