### ISSUE TITLE
Dynamic table name query in the API request

### ISSUE THREAD

**Issue by Baloneo** [coleifer/peewee#2758]
I have multiple tables, one is the `total` table, the other is the sub-table, `total_2022_01`,`total_2022_02` more... They have the same data structure. 

code:
```
@bp.route("/data", methods=["GET"])
def get_data():
    month = get_query_params("month")  # 2022_01
    if not month:
        tb_name = "total"
    else:
        tb_name = "total_" + month
    
    # I want to implement this (A model class reuse)
    ModelTotal.tbname(tb_name).select()
```

I checked the documentation, and `make_table_name` doesn't seem to pass in the table name dynamically
```
def make_table_name(model_class):
    model_name = model_class.__name__
    return model_name.lower() + '_tbl'

class BaseModel(Model):
    class Meta:
        table_function = make_table_name

class User(BaseModel):
    # table_name will be "user_tbl".

class UserProfile(BaseModel):
    # table_name will be "userprofile_tbl".
```

Setting the table name affects other api requests
```
CollectEnergy._meta.table_name = tb_name
```

My current solution is

```
database_proxy = Proxy()

def TableFactory(table_name, M):
    class DynamicTable(M):
        class Meta:
            database = database_proxy 
            db_table = table_name
    return DynamicTable

database_proxy.initialize(ms_db)

tb = TableFactory(tb_name, ModelTotal)
sql =  tb.select()
```

Is there a better way?

**Comment by coleifer** [comment]
>I checked the documentation, and make_table_name doesn't seem to pass in the table name dynamically

Correct, this is for setting the table name once, during class creation time.

>Setting the table name affects other api requests

Correct.

>My current solution is...

Yeah that looks correct to me.

**Comment by Baloneo** [comment]
Thank you !

**Comment by byte-voyager** [comment]
But when I execute `tb.insert_manay(data_source).execute()` . I get `AttributeError: type object 'DynamicTable' has no attribute 'insert_manay'`
