### ISSUE TITLE
SqliteMigrator: Using sqlite3.version_info instead of sqlite3.sqlite_version_info

### ISSUE THREAD

**Issue by henriquegemignani** [coleifer/peewee#2759]
From official documentation, [sqlte3.version_info](https://docs.python.org/3/library/sqlite3.html#sqlite3.version_info) is the module's version, not SQLite's version. The desired variable is [sqlite_version_info](https://docs.python.org/3/library/sqlite3.html#sqlite3.sqlite_version_info).

With Python 3.11.1 from official distribution, version_info is `(2, 6, 0)` while sqlite_version_info is `(3, 39, 4)`.

This causes `drop_column`/`rename_column` to always use the legacy path.

**Comment by coleifer** [comment]
Thank you for catching this, will work up a fix.

**Comment by coleifer** [comment]
I've added a patch. Note that Sqlite's ALTER...DROP COLUMN is fairly limited and will not do things like drop affected indexes, and instead will raise an error. So it is necessary, when using the new forms, to be sure to drop affected indexes/constraints/etc first.

**Comment by henriquegemignani** [comment]
Appreciated! I just want to rename a column so at least my case is easy :)
