### ISSUE TITLE
Adding Support for jsonb_array_elements in Peewee: Discussion and Contribution Proposal

### ISSUE THREAD

**Issue by saknius** [coleifer/peewee#2763]
I want to perform the following query on my PostgreSQL database through Peewee:
SELECT line_items FROM haulage_freight_rates
    WHERE NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(line_items) AS item
        WHERE item->'slabs' != '[]'
    )
I have tried to search for how to iterate over a JSONB element, which is an array of dictionaries, but I was unable to find any resources. I believe Peewee supports the WHERE NOT EXISTS clause through fn.EXISTS(). Is jsonb_array_elements also supported? If so, any resources or pointers would be appreciated. If this feature is not available, I would be happy to contribute to add this functionality. Please provide details on how I could do so.

**Comment by coleifer** [comment]
Yes, any function is available using the "magic" `fn` helper, e.g.:

```
fn.jsonb_array_elements(FreightRates.line_items)
```

**Comment by coleifer** [comment]
Here's a more complete example:

```python
src = fn.jsonb_array_elements(FreightRates.line_items).alias('items')
subq = Select([src], [SQL('1')])
subq = subq.where(
    fn.jsonb_array_length(JsonLookup(Entity('items'), ('slabs',)) > 0))

q = (FreightRates
     .select(FreightRates.line_items)
     .where(~fn.EXISTS(subq)))
```

**Comment by saknius** [comment]
Thanks this helped a lot.
