### ISSUE TITLE
Full path to alias?

### ISSUE THREAD

**Issue by andr-04** [coleifer/peewee#2764]
https://github.com/coleifer/peewee/blob/f107a90897a21c9e4ef1aa43bd61a54ceb5e943f/peewee.py#L7023

It looks incorrect when join tables, and they contain columns with the same names. When we're in `SCOPE_VALUES` (for example, in the part of updating values: `UPDATE INNER JOIN SET [...]`, `INSERT ON DUPLICATE KEY UPDATE [...]`, etc.) it's important to include the full path to the source table (or its alias) to avoid ambiguity.

I suggest applying `SCOPE_NORMAL` (or `SCOPE_SOURCE`?) at least when we explicitly marked the table as alias (and the column of `ModelAlias` interprets as `FieldAlias`).

Or should we apply a fix to `Column` class?
https://github.com/coleifer/peewee/blob/f107a90897a21c9e4ef1aa43bd61a54ceb5e943f/peewee.py#L1300

**Comment by coleifer** [comment]
Can you provide example queries that aren't working, along with the SQL they currently generate? We already have support for INSERT ... ON DUPLICATE KEY UPDATE:

https://github.com/coleifer/peewee/blob/f107a90897a21c9e4ef1aa43bd61a54ceb5e943f/tests/sql.py#L1997-L2034

**Comment by coleifer** [comment]
Your sample code doesn't run, but have you tried using `QualifiedNames`? I think this should address the issue:

```
from peewee import QualifiedNames

# ...
QualifiedNames(fn.coalesce(TariffOptionRedefinint, TariffOption.int))
# ...
```

That helper class is to be used in places like your example.
