### ISSUE TITLE
Cython 3 support

### ISSUE THREAD

**Issue by vkrizan** [coleifer/peewee#2766]
Hey Charles,

Would it be possible to add support for Cython 3? There are lots of [major changes](https://cython.readthedocs.io/en/latest/src/changes.html#major-themes-in-3-0-0) in the new Cython version, so I can image that this might be a heavy lift.

The background is that Fedora 39 is going to be using Cython 3. There are couple of errors in `playhouse/_sqlite_ext.pyx`.
You can find all in in the latest [build.log](https://kojipkgs.fedoraproject.org/work/tasks/2329/104652329/build.log).

Thank you!

xref: https://bugzilla.redhat.com/show_bug.cgi?id=2226279

**Comment by coleifer** [comment]
The cython 3 changes are currently on master, I think I was being cautious about tagging a release but I've been using them for a month now and all tests are passing so it's probably safe. I'll tag a new release later on today.

**Comment by vkrizan** [comment]
That's great news. Thank you.

**Comment by coleifer** [comment]
3.16.3 is up now.
