### ISSUE TITLE
bulk_update update the field with wrong value

### ISSUE THREAD

**Issue by Ezyhoo** [coleifer/peewee#2770]
Definition:
````
class UnsignedBigAutoField(pw.BigAutoField):
    field_type = 'BIGINT UNSIGNED AUTO_INCREMENT'

class Issue(MySQLModel):
    id = UnsignedBigAutoField(primary_key=True)
    fix_confirmed = pw.BooleanField(default=False)
    date_created = pw.DateTimeField(default=datetime.datetime.now)
    date_updated = pw.DateTimeField(default=datetime.datetime.now)
````

Updating code:
````
# issues_2_update are retrieved from select() query and modify "fix_confirmed" and "date_updated" for each element
logger.info(f"After update: {list(issues_2_update.dicts())}")
Issue.bulk_update(issues_2_update, fields=[Issue.fix_confirmed, Issue.date_updated], batch_size=50)
````

I have turned on the logging using http://docs.peewee-orm.com/en/latest/peewee/database.html#logging-queries

Here is the logging message for the updating code:

> After update: [{'id': 49, 'fix_confirmed': False, 'date_created': datetime.datetime(2023, 6, 8, 17, 12, 45), 'date_updated': datetime.datetime(2023, 8, 18, 16, 43, 17)}, {'id': 52, 'fix_confirmed': False, 'closed_override': False, 'date_created': datetime.datetime(2023, 6, 8, 17, 12, 45), 'date_updated': datetime.datetime(2023, 8, 18, 16, 43, 17)}]

> ('UPDATE `issue` SET `fix_confirmed` = CASE `issue`.`id` WHEN %s THEN %s WHEN %s THEN %s END, `date_updated` = CASE `issue`.`id` WHEN %s THEN %s WHEN %s THEN %s END WHERE (`issue`.`id` IN (%s, %s))', [49, True, 52, True, 49, datetime.datetime(2023, 8, 18, 16, 44, 3, 804510), 52, datetime.datetime(2023, 8, 18, 16, 44, 3, 804644), 49, 52])

As you can see from the log, I would like to update the fix_confirmed to false, and the fix_confirmed turned to True during bulk_update. Can anyone explain this?

**Comment by coleifer** [comment]
Seems to be working fine, I'm guessing some bug in your code somewhere.

Also if you're updating them all to the same value you might consider just issuing a regular update query, e.g. `Issue.update(fix_confirmed=False).where(Issue.id.in_(...))`

Example code:

```python
from datetime import date as d
from peewee import *

db = SqliteDatabase(':memory:')

class Issue(db.Model):
    fix_confirmed = BooleanField()
    date_updated = DateTimeField()

db.create_tables([Issue])

i1 = Issue.create(fix_confirmed=True, date_updated=d(2023, 1, 1))
i2 = Issue.create(fix_confirmed=True, date_updated=d(2023, 1, 2))
i3 = Issue.create(fix_confirmed=False, date_updated=d(2023, 1, 3))

q = Issue.select()
for i in q:
    i.fix_confirmed = False
    i.date_updated = d(2023, 1, 4)

Issue.bulk_update(q, fields=[Issue.fix_confirmed, Issue.date_updated])

for i in Issue:
    print(i.fix_confirmed, i.date_updated)
```

Outputs (correctly):

```
False 2023-01-04 00:00:00
False 2023-01-04 00:00:00
False 2023-01-04 00:00:00
```

**Comment by Ezyhoo** [comment]
Thx for the example! This is actually how I do select and update.

In my code:
`logger.info(f"After update: {list(issues_2_update.dicts())}")`
This lines logs the correct updated value for `fix_confirmed`, which in this case are False.

But the next line `Issue.bulk_update(issues_2_update, fields=[Issue.fix_confirmed, Issue.date_updated], batch_size=50)`
The `fix_confirmed` turned into True in the Update query.

There is no code between this two line, so the value change is very weird. Still not able to figure out the root cause. Do you have more idea in any chance?

**Comment by coleifer** [comment]
Try looping over them and saving them individually.

**Comment by Ezyhoo** [comment]
Yes. Saving them individually does work.

**Comment by coleifer** [comment]
I don't know what to tell you except that the way you're mutating them or passing the arguments to your various calls is not correct. The example code I shared should demonstrate that the code itself in peewee is fine.
