### ISSUE TITLE
500 internal error on every .py page of Roxy-WI

### ISSUE THREAD

**Issue by Neelamcdac** [coleifer/peewee#2772]
ModuleNotFoundError: No module named 'peewee': /var/www/haproxy-wi/app/overview.py

**Comment by coleifer** [comment]
Peewee must not be installed, obviously.

**Comment by Neelamcdac** [comment]
[root@haproxy ~]#  pip3 install peewee
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: peewee in /usr/local/lib/python3.6/site-packages
