### ISSUE TITLE
The query operator .between in https://docs.peewee-orm.com/en/latest/peewee/query_operators.html does not state if it includes boundaries or not

### ISSUE THREAD

**Issue by ghpqans** [coleifer/peewee#2774]
From the docs it should be clear, if `.between(1,10)` means values from `0...9` or from `0...10`.
The manual does not tell this.
> .between(low, high) | Search for values between low and high.

**Comment by coleifer** [comment]
It is technically up to the database to determine how it implements `BETWEEN` but in practice it means "inclusive of both endpoints". I will update the docs at any rate, thanks for the suggestion.

**Comment by ghpqans** [comment]
Thank you very much!
