### ISSUE TITLE
Prefetch with union subquery

### ISSUE THREAD

**Issue by nomme** [coleifer/peewee#2777]
Hello, I have roughly the below scenario.

```python
class User(Model):
    username = TextField()
class Tweet(Model):
    user = ForeignKeyField(User, backref="tweets")
    content = TextField(index=True)
class Link(Model):
    tweet = ForeignKeyField(Tweet, backref="links")
    url = TextField(index=True)

users = User.select().prefetch(
    Tweet.select().join(Link).orwhere(Tweet.content == "c1", Link.url == "u1"),
    Link
)
```
But because the `orwhere` is not [sargable](https://en.wikipedia.org/wiki/sargable) performance is hurting a lot.

I would like to do something like this
```python
User.select().prefetch(
    Tweet.select().where(Tweet.content == "c1").union(Tweet.select().join(Link).where(Link.url == "u1")),
    Link
)
```
Which gives the below fixed prefetch query for `Link`
```sql
SELECT "t1"."id", "t1"."tweet_id", "t1"."url"
FROM "link" AS "t1"
WHERE ("t1"."tweet_id" IN (
  SELECT "t2"."id" FROM (      # <- This should be "SELECT "t5"."id" FROM ("
      SELECT "t2"."id", "t3"."user_id", "t3"."content"
      FROM "tweet" AS "t2"
      WHERE ("t2"."content" = 'c1')
    UNION
      SELECT "t3"."id", "t3"."user_id", "t3"."content"
      FROM "tweet" AS "t3"
      INNER JOIN "link" AS "t4" ON ("t4"."tweet_id" = "t3"."id")
      WHERE ("t4"."url" = 'u1')
  ) AS "t5"
))
```
With error `no such column: t2.id`

The best option I came up with is this
```python
users = User.select().prefetch(
    Tweet.select().where(Tweet.content == "c1"),
    Tweet.select().join(Link).where(Link.url == "u1"),
    Link
)
```
This doesn't prefetch `Link` for the first `Tweet` subquery which is fine for my scenario,  but it causes duplicate `Tweet`s in the result.

Any idea how to deal with this? 
Thanks

**Comment by nomme** [comment]
Looks so simple when you spell it out. The union-query as a subquery/CTE works great. Thank you!

> All prefetch does is restrict the inner queries to the rows present in the outer ones -- you can do this manually quite easily.

Yes, but if I understand you correctly you mean creating the queries outside of `prefetch`. The recursive model instantiation and building the hierarchy that `prefetch` does is very handy though.

**Comment by coleifer** [comment]
Yes, it is handy, but if you have a very particular usage that's not working well with `prefetch()` then it is certainly something you can write yourself fairly easily (especially since you know exactly where to put everything and how to map everything together).
