### ISSUE TITLE
Please revert the docs style to the previous version

### ISSUE THREAD

**Issue by vladmiller** [coleifer/peewee#2780]
The previous docs UI was more less black/white with good contrast and easier on the eyes. It was also easier to navigate. 

The newer version's menu contract is worse and somewhat makes my eyes hurt when focusing on it for too long. The left-side navigation is a bit harder to navigate.

**Comment by coleifer** [comment]
Thanks, I've switched us back to the RtD theme - this was unintentional and related to some changes in the way RtD builds projects.
