### ISSUE TITLE
Model.update() does not preserve field order

### ISSUE THREAD

**Issue by mbystryantsev** [coleifer/peewee#2781]
In cases when update expression contains other fields, field order can be important, but peewee performs sorting.

For example (MySQL):
| a | b | c |
|---|---|---|
| 1 | 2 | 3 |
```
MyModel.update(b = a, a = c)
```

Expected:
| a | b | c |
|---|---|---|
| 3 | 1 | 3 |

Actual:
| a | b | c |
|---|---|---|
| 3 | 3 | 3 |

**Comment by coleifer** [comment]
Yes, we sort things, to provide a predictable ordering and SQL generation. Prior to 3.8 dicts were in arbitrary order, as well. Such an update query, where the order of predicates is so important, is both very fragile and very much not a good fit for Peewee.

In other words, not planning on making any changes here.

**Comment by mbystryantsev** [comment]
But the alternatives are even fragile - use several quieries that differs only by updating field or use pure SQL inserts.

I think it at least makes sense to explicitly accept field-value pair list as an option.

**Comment by coleifer** [comment]
I hear you. For these (I can't imagine you have these littered all over the place) you can try writing the query by hand.
