### ISSUE TITLE
Sqlite user defined function can't be used in an index on expression

### ISSUE THREAD

**Issue by and-se** [coleifer/peewee#2782]
I've registered user-defined function like:
```
db = SqliteDatabase(...)

@db.func('LOWER_PY')
def lower(s):
    return s.lower()
```
and now try to build index on column `name` of the `user` table using expression `LOWER_PY(name)`:

```
db.execute_sql('create index if not exists LowerUserName on user(LOWER_PY(name))')
```
but sqlite fails with error 
> peewee.OperationalError: non-deterministic functions prohibited in index expressions

According to sqlite [docs](https://www.sqlite.org/expridx.html#restrictions):
>Note that [application-defined SQL functions](https://www.sqlite.org/appfunc.html) are by default considered non-deterministic and may not be used in a CREATE INDEX statement unless the [SQLITE_DETERMINISTIC](https://www.sqlite.org/c3ref/c_deterministic.html#sqlitedeterministic) flag is used when the function is registered.

I have not found a way to specify flag SQLITE_DETERMINISTIC using `SqliteDatabase` class.

**Comment by coleifer** [comment]
We can probably add support, pysqlite3 supports the flag, as does the stdlib sqlite3 as of python 3.8. Thanks I will look into getting this patched.

**Comment by coleifer** [comment]
This should now work:

```python
@db.func('LOWER_PY', deterministic=True)
def lower(s):
    return s.lower()
```

**Comment by and-se** [comment]
Now it works and so I can search using my function without having to call python implementation on every search (which is slow).

Thank you!

**Comment by coleifer** [comment]
3.17.0 is up on pypi and includes this fix.
