### ISSUE TITLE
minor docs issue on transactions

### ISSUE THREAD

**Issue by savraj** [coleifer/peewee#2783]
Hi, thanks for an awesome library. Minor issue in this section:
https://docs.peewee-orm.com/en/latest/peewee/database.html?highlight=managing%20transactions#managing-transactions

> If an exception occurs in a wrapped block, the current transaction/savepoint will be rolled back. Otherwise the statements will be committed at the end of the wrapped block.

Isn't it true that the transaction is only automatically rolled back if the exception is unhandled? Is it more correct to say:

> If an **unhandled** exception occurs in a wrapped block, the current transaction/savepoint will be **automatically** rolled back.

Sorry to trouble you, I hope I'm understanding this correctly, and thanks again.

**Comment by coleifer** [comment]
Yes only if the exception is unhandled -- we (peewee) only would know an exception occurred if it was unhandled by the user code.
