### ISSUE TITLE
strange save() behavior

### ISSUE THREAD

**Issue by dostisurta** [coleifer/peewee#2784]
I have the following code:

```
huey = User()
username='huey'
huey.save()

foo = bar(huey.id) #In order to calculate this value I must know huey's id which is autogenerated on insert.
huey.foo = foo 
huey.xyz = 123

sleep(1)

huey.save()
print(huey)
```
Huey is always printed correctly on the last line but if I remove the sleep line, sometimes foo and xyz are not saved on the database. Using step debugging always works, that's why I came up with the sleep.
What could be causing this? Is there a better way to achieve it without the double save()?

**Comment by coleifer** [comment]
Here's a minimal example that exhibits no odd behavior for me:

```python
from peewee import *

db = SqliteDatabase(':memory:')

class User(db.Model):
    username = TextField()
    foo = IntegerField(null=True)
    def __str__(self):
        return 'id=%s, username=%s, foo=%s' % (self.id, self.username, self.foo)

db.create_tables([User])

u = User()
u.username = 'huey'
u.save()

u.foo = 123
u.save()

print(u)
```

If you can provide a reproducible example or otherwise indicate what might be different between your code and the example above, I will try to help further.

**Comment by dostisurta** [comment]
Yes, actually bar() is launching a celery task and what I'm trying to do is to store the task's uuid.
But huey.xyz = 123 also fails to save, which is really strange.
Thanks for your reply.

**Comment by coleifer** [comment]
Well that explains it. Smellery sucks btw.

**Comment by dostisurta** [comment]
Yeah I started with dramatiq but I found it very limited. Now trying to replace it with celery which is somewhat better but also has it's things
Do you know a better tool?
