### ISSUE TITLE
How to use single connection in multi-thread program with MySQL?

### ISSUE THREAD

**Issue by aghasi** [coleifer/peewee#2785]
I wrote a program with too many threads (more than 50 threads).I'm using `MySQL` as database and `MySQLDatabase` for connecting to it. Threads were not working with database too many times, they are idle most of the time. I want to reduce connections count because it has some overhead on my database. How can i force `peewee` to use a single connection for all thread?

**Comment by coleifer** [comment]
Just specify `thread_safe=False` in the database init: http://docs.peewee-orm.com/en/latest/peewee/api.html#Database

```
db = MySQLDatabase(..., thread_safe=False)
```

All threads will share a single connection and a single transaction state. Be very careful! You should really be using a connection pool and returning idle connection to the pool...

**Comment by aghasi** [comment]
> Just specify `thread_safe=False` in the database init: http://docs.peewee-orm.com/en/latest/peewee/api.html#Database
> 
> ```
> db = MySQLDatabase(..., thread_safe=False)
> ```
> 
> All threads will share a single connection and a single transaction state. Be very careful! You should really be using a connection pool and returning idle connection to the pool...

Should I use a `threading.Lock` to prevent race?

Can you send a example about your solution (use a connection pool and returning idle connection to the pool)?

**Comment by coleifer** [comment]
The pool docs: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#pool

When you use the pool you just call connect and close like normal.

If you use the pool you should not set thread safe to false, and simply open and close connections only when you are actually doing work with the db.
