### ISSUE TITLE
corporate code checker found 'possible SQL injection vulnerability'

### ISSUE THREAD

**Issue by Mike31415** [coleifer/peewee#2786]
I am working for a CRO (contract research organization) developing some in-house tools but a code checker we are running comes up with this issue.
It centers around functions that take in a generic string used as an SQL argument in some functions e.g.

    def execute_sql(self, sql, params=None, commit=None):

Have you any advice on how to resolve this issue?
Thanks

**Comment by coleifer** [comment]
![](https://i.imgur.com/vLJv7Zu.gif)
