### ISSUE TITLE
[docs] enabling ManyToManyField.add() on backrefs with "correct" approach

### ISSUE THREAD

**Issue by khimaros** [coleifer/peewee#2787]
i am implementing a manytomany relationship using the recommended "correct" approach from https://docs.peewee-orm.com/en/latest/peewee/relationships.html#implementing-many-to-many

however, the backrefs created with this approach don't provide `add()` and `remove()` methods, which results in a less ergonomic API for the resulting models.

is it possible to enable these methods on the referenced tables?

context: i'm using the manually through table approach partly because i need to define some additional methods and metadata on the through table. maybe there is a better way to do that?

**Comment by coleifer** [comment]
Correct, there is no `add()` and `remove()` - those are provided by the "many to many field" helper. You can write your own helpers quite easily, or you can try using `ManyToManyField` with a custom through model, but that may get tricky when dealing with extra metadata on the through table. Short answer is there is no magic secret that will solve these issues - just write a couple helpers where you need them.

**Comment by khimaros** [comment]
where would be the right place to define the add() methods?

given the example from the docs:

```python
class Student(Model):
    name = CharField()

class Course(Model):
    name = CharField()

class StudentCourse(Model):
    student = ForeignKeyField(Student)
    course = ForeignKeyField(Course)
```

where would the add method be defined to allow `student.courses.add()`?

**Comment by khimaros** [comment]
i'm working through some of the implementation of this.

it seems like `backref_accessor_class` (`BackrefAccessor`) on `ForeignKeyField` is the part that is most relevant for this use case.  it is used in `ForeignKeyField.bind()`

would a patch to add `add()` and `remove()` to `BackrefAccessor` make sense or are there other complexities there that i'm missing?

**Comment by khimaros** [comment]
alright, i think this is what i arrived at:

```python
StudentCourseDeferred = DeferredThroughModel()

class Student(Model):
    name = CharField()
    courses = ManyToManyField(Course, backref='students', through_model=StudentCourseDeferred)

class Course(Model):
    name = CharField()

class StudentCourse(Model):
    student = ForeignKeyField(Student)
    course = ForeignKeyField(Course)

StudentCourseDeferred.set_model(StudentCourse)
```

**Comment by coleifer** [comment]
I would do things much more simply. Typically even when you have a many-to-many you're mostly managing it from one side, so I'd do something like:

```python
class Student(Model):
    ...
    def add_courses(self, ...):
        ...
    def remove_courses(self, ...):
        ...
```
