### ISSUE TITLE
plan for supporting excel or csv

### ISSUE THREAD

**Issue by funny-cat-happy** [coleifer/peewee#2788]
Hello developer,
  In my work, I alaways need to handle excel and csv and I want to find an orm tool to handle this.But I find nothing.So I want to ask if it can support excel or csv?In https://github.com/coleifer/peewee/issues/1551 ,you say oracle may have problem of license.And excel should not have the problem.If you have the plan,I will pull requests to it.

**Comment by coleifer** [comment]
You can use the `dataset` extension, which comes with lots of functionality for making working with CSV very easy. http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#dataset

To load a CSV http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#importing-data

Example code:

```python
from playhouse.dataset import DataSet

db = DataSet('sqlite:///:memory:')
table = db['stock_prices']  # Will create table if doesn't exist.
table.thaw(filename='stocks.csv', format='csv')  # Load CSV into table, creating columns.
rows = table.all()[:3]  # Get first 3 rows
print(rows)
```
