### ISSUE TITLE
Circular Foreign Keys

### ISSUE THREAD

**Issue by Saya47** [coleifer/peewee#2789]
Hello! How can we have circular FK fields?
Borrowing your code from: https://github.com/coleifer/peewee/issues/1711

I want Todo to have a FK field to `TodoItem`!
```
class Todo(Model):
    task_name = TextField()
    todo_items = ForeignKeyField(TodoItem, backref='todo_items')

class TodoItem(Model):
    todo = ForeignKeyField(Todo, backref='items')
    item_name = TextField()
```
But Python errors here since TodoItem is not defined yet. I believe Django handles this kind of referencing by allowing a String to be passed instead of the model class such as: `todo_items = ForeignKeyField('TodoItem', backref='todo_items')` But I tried it and it didn't work, so I was wondering how Peewee enables this, just out of curiosity, I know this would be bad design usually.
Thanks a lot for all your work!

**Comment by coleifer** [comment]
Your schema is completely wrong, Todo should not have a foreign key to todoitem.

Your question is answered in a whole dedicated section in the docs http://docs.peewee-orm.com/en/latest/peewee/models.html#circular-foreign-key-dependencies

Read the docs before posting here again
