### ISSUE TITLE
Under DELETE journal mode the write transaction happened before the read "database is locked"

### ISSUE THREAD

**Issue by instasck** [coleifer/peewee#2792]
I didn't see it is coming, I opened a Q on stackoverflow:
https://stackoverflow.com/questions/77211990/peewee-operationalerror-database-is-locked-on-a-single-thread-using-a-locker/77212573#77212573

Default journal mode is DELETE mean we can't read and write together, since the write lock can happen before the read does.

````
class InstaPyLimits(object):
    @staticmethod
    def update_daily_activity(time):
        with ActivityTracker_locker:
            # ActivityTracker.update(activity_time_curr= ActivityTracker.activity_time_curr + int(time)).where(ActivityTracker.date == _datetime.date.today()).execute()
            ActivityTracker.update(
                {ActivityTracker.activity_time_curr: ActivityTracker.activity_time_curr + int(time)}).where(
                ActivityTracker.date == _datetime.date.today()).execute()

models.py:
db = SqliteDatabase(Settings.stats_conf_database_location)
ActivityTracker_locker = threading.Lock()


class ActivityTracker(Model):
    date = DateField(unique=True)
    activity_time_curr = IntegerField(default=0)  # active seconds today
    activity_time_max = IntegerField()   # max active seconds today

    class Meta:
        database = db
````

 as I get it there are 2 threads opened by peewee, one for write and one for read, normally the read will lock the database first, later the write will, but for some race condition when journal is DELETED not WAL the write lock before the read does creating a database is locked. 

I think some document need to be added on this, so we shall not read and write OR better use WAL mode instead on those cases.

**Comment by coleifer** [comment]
> as I get it there are 2 threads opened by peewee, one for write and one for read

No this is completely wrong.

 Is a separate process or anything else accessing the database? If you can create a reproducible example I’ll take another look.

**Comment by sionking** [comment]
(it is me) no, nothing is accessing the database. my app is completely single threaded. moreover I added an isolation on windows so only python can access my app files.
Once changed to WAL mode this issue that happen 1 / 10000 times, is gone.

can you explain that?

**Comment by coleifer** [comment]
You've given me no usable information to try and help debug this, so I can't explain.

**Comment by sionking** [comment]
I gave you the exact code. so this code should run fine? the database is locked happen on ActivityTracker.update line.
I will try to update peewee

**Comment by coleifer** [comment]
No, there’s no info how it is actually used. I meant a standalone script that runs and demonstrates the issue, not some snippet of code.

**Comment by coleifer** [comment]
For example, the following runs (albeit slowly) without any issues using the DELETE journal mode. You've stated you only have a single thread, but yet you're using a `threading.Lock()` for some reason(?). In other words, I think you're omitting important details, whether you realize it or not.

```python
from peewee import *

db = SqliteDatabase('/tmp/test.db')

class Reg(db.Model):
    key = TextField(primary_key=True)
    count = IntegerField()

db.create_tables([Reg])
print(db.pragma('journal_mode'))
keys = ('k1', 'k2', 'k3')
for k in keys:
    Reg.create(key=k, count=0)

for i in range(100000):
    for k in keys:
        Reg.update(count=Reg.count + 1).where(Reg.key == k).execute()

# Should print 100,000 for each.
for r in Reg:
    print(r.key, r.count)
```

Prints:

```
delete
k1 100000
k2 100000
k3 100000
```

**Comment by instasck** [comment]
I am not running any thread, I am using a locker since I wanted to isolate the update if for some reason any thread will use it.
Might it be a specific PC issue ? maybe the virtual memory is ended (can it be related ?)
Regarding the example, it is as simple as the one you added. nothing fancy.
Update of windows did not make a change.
**I updated peewee from 3.15.4 to 3.17.0 I think the issue is gone now.** will update on that.

**Comment by coleifer** [comment]
That’s not at all how threads work but ok

**Comment by instasck** [comment]
I know how threads works, can you explain what you want to say ?

**Comment by instasck** [comment]
SEEMS LIKE IT GOT SOLVED BY LOCKING ALL CALLS WITH A MUTEX:
![image](https://github.com/coleifer/peewee/assets/43851500/696ac69e-549f-4596-8819-3e73a5841c03)

Apparently a read and a write operation could not live at the same time.

**Comment by coleifer** [comment]
>my app is completely single threaded

>I have threads

OK bro.
