### ISSUE TITLE
Support TiDB

### ISSUE THREAD

**Issue by wd0517** [coleifer/peewee#2794]
[TiDB](https://docs.pingcap.com/tidb/stable) is a distributed SQL database that is highly compatible with MySQL. However, there are still some differences between them. When using peewee, users may encounter the following issue:

- Unable to obtain the correct TiDB version, which may potentially cause issues because Peewee uses `server_version` to determine the appropriate function for `conflict_update` https://github.com/coleifer/peewee/blob/master/peewee.py#L4292
- Can't use TiDB [`AUTO_RANDOM`](https://docs.pingcap.com/tidb/stable/auto-random) column

If you plan to add TiDB to the playhouse but don't want to do it yourself, I would be happy to contribute.

**Comment by coleifer** [comment]
I don't have any plans to add support for TiDB, nor to maintain support for it when issues come up. My suggestion would be to package this as a 3rd-party extension, e.g. `peewee-tidb`, which provides the appropriate `Database` class along with any other helpers which would be relevant.
