### ISSUE TITLE
when I download code and run  /examples\blog   .  I  get this error  : ImportError: cannot import name 'Markup' from 'flask'

### ISSUE THREAD

**Issue by Naylor55** [coleifer/peewee#2795]
# errorDetail

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\cml\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\cli.py", line 219, in locate_app
    __import__(module_name)
  File "E:\code\Python\peewee\examples\blog\app.py", line 7, in <module>
    from flask import (Flask, flash, Markup, redirect, render_template, request,
ImportError: cannot import name 'Markup' from 'flask' (C:\Users\cml\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\__init__.py)

# env

* os：windows11    64bit
* python：3.9.7
* flask：3.0

# other
I  dot  not  know  the  'Markup' package  who belongs to

**Comment by coleifer** [comment]
Oh thanks I forgot to update that dependency they changed it recently. @palletsproject is stupid as fuck.

**Comment by coleifer** [comment]
Oh thanks I forgot to update that dependency they changed it recently. @pallets is stupid, constantly changing dumb shit.
