### ISSUE TITLE
playouse.pool | Don't work correctly

### ISSUE THREAD

**Issue by g-ruby** [coleifer/peewee#2798]
Hello, I noticed that the pools in the playhouse.pool extension PooledMySQLDatabase does not work properly when I set the max_connections parameter to 10 and executed more than 10 queries, in the DBMS I noticed that 10 sessions were created, but only one is running (because it has the shortest time from the last query, in all other sessions the time goes on forever), I called the close() function, but the queries did not close, even setting timeouts did not work.

Maybe I'm doing something wrong, but here's the code

```
database = PooledMySQLDatabase(
	database=config['db'],
	max_connections=5,
	stale_timeout=5,
	timeout=8,
	**{
	"user": config['user'],
	"host": config['host'],
	"password": config['password'],
	"thread_safe": False,
	"autoconnect": True})
```

```
@blueprint.route('/auth/scopes', methods=['GET'])
@manage_connections_db
async def scopes():
	api_key = request.headers.get('X-API-Key')

        // other code

	response.headers['Scopes'] = ', '.join([t.name for t in received_key])
	return response
````

````
def manage_connections_db(func):
	@wraps(func)
	async def wrap(*args, **kwargs):
		database.connect()
		result = await func(*args, **kwargs)
		database.close()
		return result
	return wrap
```

**Comment by coleifer** [comment]
Databases use a thread-local to represent the connection-state for a given thread. For asyncio you probably want async-context-locals, but these are not included out-of-the-box. That might explain what you're observing. In short, though, if you're trying to use this with asyncio you're going to need to sort out the context-local stuff.

Some helpful information may be found here: https://fastapi.tiangolo.com/how-to/sql-databases-peewee/
