### ISSUE TITLE
Utilizing `JSONField` without `psycopg2`

### ISSUE THREAD

**Issue by darren-recentive** [coleifer/peewee#2807]
I am trying to migrate from `psycopg2` -> `psycopg3`. Motivation: https://github.com/DataDog/dd-trace-py/issues/6578
My Flask app has contains preexisting `flask_peewee.db.Database.Model`s that utilize `playhouse.postgres_ext.JSONField`

I've read through [docs](https://docs.peewee-orm.com/en/latest/peewee/playhouse.html#json-support), Github Issues, but have been unable to find an equivalent Field.

Any help would be much appreciated, thanks!

**Comment by coleifer** [comment]
You can try using the `feature/psycopg3-fixes` branch: https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes

Alternatively, you can create your own extension module that effectively vendors some of the code in `playhouse/psycopg3_ext` to add your own json field. I think the following should be sufficient:

```python
from playhouse.postgres_ext import _JsonLookupBase

try:
    import psycopg
    from psycopg.types.json import Jsonb
except ImportError:
    psycopg = Jsonb = None


JSONB_CONTAINS = '@>'
JSONB_CONTAINED_BY = '<@'
JSONB_CONTAINS_KEY = '?'
JSONB_CONTAINS_ANY_KEY = '?|'
JSONB_CONTAINS_ALL_KEYS = '?&'
JSONB_EXISTS = '?'
JSONB_REMOVE = '-'


class _Psycopg3JsonLookupBase(_JsonLookupBase):
    def concat(self, rhs):
        if not isinstance(rhs, Node):
            rhs = Jsonb(rhs)  # Note: uses psycopg3's Jsonb.
        return Expression(self.as_json(True), OP.CONCAT, rhs)

    def contains(self, other):
        clone = self.as_json(True)
        if isinstance(other, (list, dict)):
            return Expression(clone, JSONB_CONTAINS, Jsonb(other))  # Same.
        return Expression(clone, JSONB_EXISTS, other)


class JsonLookup(_Psycopg3JsonLookupBase):
    def __getitem__(self, value):
        return JsonLookup(self.node, self.parts + [value], self._as_json)

    def __sql__(self, ctx):
        ctx.sql(self.node)
        for part in self.parts[:-1]:
            ctx.literal('->').sql(part)
        if self.parts:
            (ctx
             .literal('->' if self._as_json else '->>')
             .sql(self.parts[-1]))

        return ctx


class JsonPath(_Psycopg3JsonLookupBase):
    def __sql__(self, ctx):
        return (ctx
                .sql(self.node)
                .literal('#>' if self._as_json else '#>>')
                .sql(Value('{%s}' % ','.join(map(str, self.parts)))))


def cast_jsonb(node):
    return NodeList((node, SQL('::jsonb')), glue='')


class BinaryJSONField(IndexedFieldMixin, Field):
    field_type = 'JSONB'
    _json_datatype = 'jsonb'
    __hash__ = Field.__hash__

    def __init__(self, dumps=None, *args, **kwargs):
        self.dumps = dumps or json.dumps
        super(BinaryJSONField, self).__init__(*args, **kwargs)

    def db_value(self, value):
        if value is None:
            return value
        if not isinstance(value, Jsonb):
            return Cast(self.dumps(value), self._json_datatype)
        return value

    def __getitem__(self, value):
        return JsonLookup(self, [value])

    def path(self, *keys):
        return JsonPath(self, keys)

    def concat(self, value):
        if not isinstance(value, Node):
            value = Jsonb(value)
        return super(BinaryJSONField, self).concat(value)

    def contains(self, other):
        if isinstance(other, (list, dict)):
            return Expression(self, JSONB_CONTAINS, Jsonb(other))
        elif isinstance(other, BinaryJSONField):
            return Expression(self, JSONB_CONTAINS, other)
        return Expression(cast_jsonb(self), JSONB_EXISTS, other)

    def contained_by(self, other):
        return Expression(cast_jsonb(self), JSONB_CONTAINED_BY, Jsonb(other))

    def contains_any(self, *items):
        return Expression(
            cast_jsonb(self),
            JSONB_CONTAINS_ANY_KEY,
            Value(list(items), unpack=False))

    def contains_all(self, *items):
        return Expression(
            cast_jsonb(self),
            JSONB_CONTAINS_ALL_KEYS,
            Value(list(items), unpack=False))

    def has_key(self, key):
        return Expression(cast_jsonb(self), JSONB_CONTAINS_KEY, key)

    def remove(self, *items):
        return Expression(
            cast_jsonb(self),
            JSONB_REMOVE,
            # Hack: psycopg3 parameterizes this as an array, e.g. '{k1,k2}',
            # but that doesn't seem to be working, so we explicitly cast.
            # Perhaps postgres is interpreting it as a string. Using the more
            # explicit ARRAY['k1','k2'] also works just fine -- but we'll make
            # the cast explicit to get it working.
            Cast(Value(list(items), unpack=False), 'text[]'))
```

**Comment by darren-recentive** [comment]
> You can try using the `feature/psycopg3-fixes` branch: https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes
> 
> Alternatively, you can create your own extension module that effectively vendors some of the code in `playhouse/psycopg3_ext` to add your own json field. I think the following should be sufficient:
> 
> ```python
> from playhouse.postgres_ext import _JsonLookupBase
> 
> try:
>     import psycopg
>     from psycopg.types.json import Jsonb
> except ImportError:
>     psycopg = Jsonb = None
> 
> 
> JSONB_CONTAINS = '@>'
> JSONB_CONTAINED_BY = '<@'
> JSONB_CONTAINS_KEY = '?'
> JSONB_CONTAINS_ANY_KEY = '?|'
> JSONB_CONTAINS_ALL_KEYS = '?&'
> JSONB_EXISTS = '?'
> JSONB_REMOVE = '-'
> 
> 
> class _Psycopg3JsonLookupBase(_JsonLookupBase):
>     def concat(self, rhs):
>         if not isinstance(rhs, Node):
>             rhs = Jsonb(rhs)  # Note: uses psycopg3's Jsonb.
>         return Expression(self.as_json(True), OP.CONCAT, rhs)
> 
>     def contains(self, other):
>         clone = self.as_json(True)
>         if isinstance(other, (list, dict)):
>             return Expression(clone, JSONB_CONTAINS, Jsonb(other))  # Same.
>         return Expression(clone, JSONB_EXISTS, other)
> 
> 
> class JsonLookup(_Psycopg3JsonLookupBase):
>     def __getitem__(self, value):
>         return JsonLookup(self.node, self.parts + [value], self._as_json)
> 
>     def __sql__(self, ctx):
>         ctx.sql(self.node)
>         for part in self.parts[:-1]:
>             ctx.literal('->').sql(part)
>         if self.parts:
>             (ctx
>              .literal('->' if self._as_json else '->>')
>              .sql(self.parts[-1]))
> 
>         return ctx
> 
> 
> class JsonPath(_Psycopg3JsonLookupBase):
>     def __sql__(self, ctx):
>         return (ctx
>                 .sql(self.node)
>                 .literal('#>' if self._as_json else '#>>')
>                 .sql(Value('{%s}' % ','.join(map(str, self.parts)))))
> 
> 
> def cast_jsonb(node):
>     return NodeList((node, SQL('::jsonb')), glue='')
> 
> 
> class BinaryJSONField(IndexedFieldMixin, Field):
>     field_type = 'JSONB'
>     _json_datatype = 'jsonb'
>     __hash__ = Field.__hash__
> 
>     def __init__(self, dumps=None, *args, **kwargs):
>         self.dumps = dumps or json.dumps
>         super(BinaryJSONField, self).__init__(*args, **kwargs)
> 
>     def db_value(self, value):
>         if value is None:
>             return value
>         if not isinstance(value, Jsonb):
>             return Cast(self.dumps(value), self._json_datatype)
>         return value
> 
>     def __getitem__(self, value):
>         return JsonLookup(self, [value])
> 
>     def path(self, *keys):
>         return JsonPath(self, keys)
> 
>     def concat(self, value):
>         if not isinstance(value, Node):
>             value = Jsonb(value)
>         return super(BinaryJSONField, self).concat(value)
> 
>     def contains(self, other):
>         if isinstance(other, (list, dict)):
>             return Expression(self, JSONB_CONTAINS, Jsonb(other))
>         elif isinstance(other, BinaryJSONField):
>             return Expression(self, JSONB_CONTAINS, other)
>         return Expression(cast_jsonb(self), JSONB_EXISTS, other)
> 
>     def contained_by(self, other):
>         return Expression(cast_jsonb(self), JSONB_CONTAINED_BY, Jsonb(other))
> 
>     def contains_any(self, *items):
>         return Expression(
>             cast_jsonb(self),
>             JSONB_CONTAINS_ANY_KEY,
>             Value(list(items), unpack=False))
> 
>     def contains_all(self, *items):
>         return Expression(
>             cast_jsonb(self),
>             JSONB_CONTAINS_ALL_KEYS,
>             Value(list(items), unpack=False))
> 
>     def has_key(self, key):
>         return Expression(cast_jsonb(self), JSONB_CONTAINS_KEY, key)
> 
>     def remove(self, *items):
>         return Expression(
>             cast_jsonb(self),
>             JSONB_REMOVE,
>             # Hack: psycopg3 parameterizes this as an array, e.g. '{k1,k2}',
>             # but that doesn't seem to be working, so we explicitly cast.
>             # Perhaps postgres is interpreting it as a string. Using the more
>             # explicit ARRAY['k1','k2'] also works just fine -- but we'll make
>             # the cast explicit to get it working.
>             Cast(Value(list(items), unpack=False), 'text[]'))
> ```

Thanks @coleifer, I was able to utilize `BinaryJSONField` in the aforementioned PR https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes

**Comment by darren-recentive** [comment]
> I haven't yet merged this because psycopg3 does some things that are pretty annoying, most specifically you can no longer parameterize `None` as a substitution for `NULL` - you have to use NULL literally. At some point I will merge the psycopg3 changes, just not quite ready yet.

Thanks @coleifer, I was able to utilize `BinaryJSONField` in the aforementioned PR https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes
