### ISSUE TITLE
Connection Already Closed

### ISSUE THREAD

**Issue by yash2001cp** [coleifer/peewee#2808]
```
db_params = {
    "database": DATABASE_NAME,
    "user": DATABASE_USER,
    "password": DATABASE_PASSWORD,
    "host": DATABASE_HOST,
    "port": DATABASE_PORT,
    "autorollback": True,
    "max_connections": 200,
}


class CustomDatabase(PooledPostgresqlExtDatabase):
    @timer
    def execute_sql(self, sql, params=None):
        # add is closed check due to connection already opened error when using using concurrent.futures
        if db.is_closed():
            db.connect(reuse_if_open = True)
        return super().execute_sql(sql, params)


db = (
    CustomDatabase(**db_params)
    if ENVIRONMENT_TYPE == Environment.cli or APP_ENV != AppEnv.production
    else PooledPostgresqlExtDatabase(**db_params)
)
```

here i get Interface error connection already closed  ( my application is multi threaded)

threadlocals = True was the recommended option but  this is not a valid argument for PooledPostgresqlExtDatabase

this happens when mostly when this type of code is used

```
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
      futures = [
            executor.submit(get_info, obj.id, str(obj.name)) # get info does some select queries and processes the data
            for obj in response
        ]

```

similiar to issue #334  @coleifer

**Comment by coleifer** [comment]
># add is closed check due to connection already opened error when using using concurrent.futures

This looks like some kind of weird hack...if you don't understand why you were seeing this first problem, then wouldn't it be safe to assume that the second issue (Connection Already Closed) was likely closely related?

The docs also indicate that the argument is `thread_safe`, which defaults to `True` already: http://docs.peewee-orm.com/en/latest/peewee/api.html#Database

The following code works fine for me locally, by the way:

```python
from concurrent.futures import ThreadPoolExecutor
from peewee import *
from playhouse.pool import *

db = PooledPostgresqlExtDatabase('peewee_test')

class Reg(db.Model):
    key = CharField(unique=True)
    value = IntegerField()

db.drop_tables([Reg])
db.create_tables([Reg])

def create(i, n):
    with db:
        for x in range(i, i + n):
            Reg.create(key='k%04d' % x, value=x)

with ThreadPoolExecutor(max_workers=4) as ex:
    futures = [ex.submit(create, i, 100)
               for i in range(0, 10000, 100)]

print(len(Reg))

db.drop_tables([Reg])
```

**Comment by yash2001cp** [comment]
timelines = [future.result() for future in futures]
when i do this i get connection already closed

**Comment by coleifer** [comment]
You might have mentioned that, as your fast-api changes completely break thread-safety for connections by making them async-context aware (and not thread-aware)...

**Comment by yash2001cp** [comment]
so the only solution here is to go back to sync ?

**Comment by coleifer** [comment]
You're on your own, asyncio traveler. Godspeed.

**Comment by yash2001cp** [comment]
> You're on your own, asyncio traveler. Godspeed.

i am chalked

**Comment by coleifer** [comment]
The problem is basically that Peewee is not asyncio friendly out-of-the-box. FastAPI suggests a monkeypatch which makes the thread-local connection management aware of async context. In the process, it loses its awareness of threads. So it's this unfortunate split where you kinda need to either go all-asyncio or no-asyncio. To use a hybrid approach, with a threadpool executor, I think the way you make it work would need to have each worker-thread/function force it's own connection. I can't think of a great way to do that with the asyncio patch, but it might work. At any rate sorry not to be able to offer more advice. I [hate asyncio](https://charlesleifer.com/blog/asyncio/) for many reasons, and this is symptomatic of one of them - the needless bifurcation of code.

**Comment by yash2001cp** [comment]
`import concurrent.futures
from functools import wraps
from database.db_session import db, db_state_default


class ThreadpoolWithDBConnection:
    def __init__(self, max_workers=None, db_class = db):
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=max_workers)
        self.db_class = db_class

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.executor.shutdown(wait=True)

    def submit(self, func, *args, **kwargs):
        @wraps(func)
        def wrapper(*args, **kwargs):
            self.db_class._state._state.set(db_state_default.copy())
            self.db_class._state.reset()
            with self.db_class.connection_context():
                return func(*args, **kwargs)

        return self.executor.submit(wrapper, *args, **kwargs)`
This is the monkey patch for making it aware of thread , upon testing we didn't encounter any problems , can u review and see if we are missing anything here , everything else is the same as mentioned in the fastapi monkey patch
