### ISSUE TITLE
Encountering TypeError with heappush

### ISSUE THREAD

**Issue by Negaihoshi** [coleifer/peewee#2813]
Hi, our team has encountered the following issue, similar to the one mentioned in this [issue](https://github.com/coleifer/peewee/issues/1939). We are using Python 3.9.18 and Peewee 3.17.0.

We have been using Peewee for the past eight months, and this problem has not occurred before. However, due to increased traffic recently, we are unsure if it is related to that. Could you please provide recommendations on how to address this?

As the issue seems to be sporadic and not consistently reproducible, if you need additional information to assist with debugging, please let me know.

```
TypeError: '<' not supported between instances of 'Connection' and 'Connection'

  File "project/models2/tier.py", line 92, in query_tid_tier_map
    tid_tier_map[tid] = int(rank)
  File "peewee.py", line 3173, in __exit__
    self.close()
  File "peewee.py", line 3217, in close
    self._close(self._state.conn)
  File "playhouse/pool.py", line 187, in _close
    heapq.heappush(self._connections, (pool_conn.timestamp, conn))
```

**Comment by coleifer** [comment]
This can occur if the timestamp is identical to a timestamp already in `self._connections` -- are you using multiprocessing anywhere or just multithreading? What kind of setup is this? One thing that might help is if you can add some debug logging inside the `pool._close` method (around line 187 where it's calling `heappush`) and put something like:

```python
try:
    heapq.heappush(self._connections, (pool_conn.timestamp, conn))
except Exception:
    print([id(c) for _, c in self._connections])
    print(id(conn))
    raise
```

**Comment by Negaihoshi** [comment]
We are using multithreading. We are built on k8s and nginx-unit, where a Pod service consists of one process and eight threads.

Thank you for your suggestion. We will try to add logging and see if we can gather more information when the issue occurs.

**Comment by coleifer** [comment]
I'm using something like this to try and test to see if I can replicate but still no luck:

```
import threading
import time

from peewee import *
from playhouse.pool import *

db = PooledPostgresqlDatabase('peewee_test', max_connections=50)

def run():
    for j in range(100):
        db.connect()
        db.execute_sql('select 1').fetchall()
        db.close()

threads = [threading.Thread(target=run) for _ in range(50)]
for t in threads:
    t.start()
for t in threads:
    t.join()
```

This sets up 50 threads, each thread opens and closes a connection 100 times. Not seeing any errors.

**Comment by Negaihoshi** [comment]
> Are you using Windows by chance?
No, we are using Ubuntu 20.04.

Thank you for testing. It's already late in my region, but I will try to reproduce it when I find some time.

**Comment by TokuiNico** [comment]
Hi, I am Negaihoshi's colleague. The attached images are the sentry logs when we encountered a problem. Both screenshots show exceptions on the same pod.

You can see that the IDs of the two connections are different, but they have the same timestamp. I agree with your inference that this is due to a race condition causing both connections to use the same timestamp.

<img width="894" alt="image" src="https://github.com/coleifer/peewee/assets/12724338/cf0e631a-d562-4757-9bc1-e688bc93be92">
<img width="898" alt="image" src="https://github.com/coleifer/peewee/assets/12724338/59851a41-4fe3-4196-b361-77b6e2510037">

**Comment by coleifer** [comment]
How're those changes working for you all?

**Comment by Negaihoshi** [comment]
Thank you for your inquiry.
We have already conducted tests, but the low frequency of occurrence makes it challenging to observe the issue.

Furthermore, we have not encountered the problem again later, making it difficult to determine if it has been resolved.

If we come across it again, we will provide additional information for reporting. Thank you for your assistance!
