### ISSUE TITLE
Update branch `feature/psycopg3-fixes`

### ISSUE THREAD

**Issue by darren-recentive** [coleifer/peewee#2816]
Is it possible to rebase [feature/psycopg3-fixes](https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes) with `master` so that it can include the latest 4 commits?
https://github.com/coleifer/peewee/compare/feature/psycopg3-fixes...master

https://github.com/coleifer/peewee/commit/628668437ef29f57d287e72d006d49908c3c5664
https://github.com/coleifer/peewee/commit/110faf3018cca311db66079f1ca63b821b027a49
https://github.com/coleifer/peewee/commit/ea3fb11a9c2a4b0cd958a453dd287e408477eda5
https://github.com/coleifer/peewee/commit/53f81f2edc6750107c11f4bbc5d54faf9eca2177

**Comment by coleifer** [comment]
Done.
