### ISSUE TITLE
[Question] Local model, how make

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2822]
It is not always necessary to create a user in the database, only when he updates some information, then it is worth entering him into the database. And the rest of the empty users should be stored locally, is it possible to implement it as the following code? Or realize that the model is local?
```python
class BaseModel(peewee.Model):
    class Meta:
        database = database
        
class User(BaseModel):
    user_id = peewee.BigIntegerField(primary_key=True, unique=True)
    sex = peewee.IntegerField(default=None, null=True)
    
    class Meta:
        indexes = (
            (('user_id',), True),
        )

# Create local model
local_user = User(user_id=1)
# Oh.. user changed his sex! We need to add him to database
local_user.sex = 1
local_user.update() # Inserts to database if model local
```

**Comment by coleifer** [comment]
This makes no sense to me. Model instances are regular objects so you can do what you want with them.
