### ISSUE TITLE
datetime invoke

### ISSUE THREAD

**Issue by yash2001cp** [coleifer/peewee#2824]
```
from peewee import *
from database.db_session import db
from datetime import datetime, timedelta
import time

class User(Model):
    id = BigAutoField()
    updated_at_1 = DateTimeField(default = datetime.utcnow)
    updated_at_2 = DateTimeField(default = datetime.utcnow())
    updated_at_3 = DateTimeField(default = datetime.utcnow() + timedelta(days = 1))
    
    class Meta:
        database = db
        
User.create_table()

u1 = User.create()

time.sleep(10)

u2 = User.create()

print(u1.updated_at_1 == u2.updated_at_1)  # this goes false
print(u1.updated_at_2 == u2.updated_at_2)  # this goes true
print(u1.updated_at_2 == u2.updated_at_2)  # this goes true


User.drop_table()
```

DateTimeField(default = datetime.utcnow() + timedelta(days = 1)). i can never set this cause it will always take the time when the server was up , i can correct this by not using the default functionality but just wanted to know if this is desirable ?

**Comment by coleifer** [comment]
All peewee sees, because this is Python, is default=(the result of calling datetime.utcnow() + timedelta). You need to use a callable, so Peewee will call it each time it needs to populate the value:

```python

tomorrow = lambda: datetime.utcnow() + timedelta(days=1)

class User(...):
    updated_at = DateTimeField(default=tomorrow)
```

Docs: http://docs.peewee-orm.com/en/latest/peewee/models.html#default-field-values

This is mentioned explicitly:

>In some instances it may make sense for the default value to be dynamic. A common scenario is using the current date and time. Peewee allows you to specify a function in these cases, whose return value will be used when the object is created. Note we only provide the function, we do not actually call it

**Please read the docs.**

**Comment by yash2001cp** [comment]
> All peewee sees, because this is Python, is default=(the result of calling datetime.utcnow() + timedelta). You need to use a callable, so Peewee will call it each time it needs to populate the value:
> 
> ```python
> tomorrow = lambda: datetime.utcnow() + timedelta(days=1)
> 
> class User(...):
>     updated_at = DateTimeField(default=tomorrow)
> ```
> 
> Docs: http://docs.peewee-orm.com/en/latest/peewee/models.html#default-field-values
> 
> This is mentioned explicitly:
> 
> > In some instances it may make sense for the default value to be dynamic. A common scenario is using the current date and time. Peewee allows you to specify a function in these cases, whose return value will be used when the object is created. Note we only provide the function, we do not actually call it
> 
> **Please read the docs.**

https://github.com/coleifer/peewee/issues/2808 can u pls look at the last comment of this closed issue
