### ISSUE TITLE
Update branch `feature/psycopg3-fixes`

### ISSUE THREAD

**Issue by darren-recentive** [coleifer/peewee#2825]
Rebase [feature/psycopg3-fixes](https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes) with `master` to include 3 latest commits
https://github.com/coleifer/peewee/compare/feature/psycopg3-fixes...master
https://github.com/coleifer/peewee/commit/e0db76f075f5cfe54f69818653e35773e72621c9
https://github.com/coleifer/peewee/commit/437c4c2a15b22413b70b7251a8f213eda8f27559
https://github.com/coleifer/peewee/commit/d7d13d6a5b6e563f3b2003338b2900c639c4ca27

Should I create a PR instead to assist?

**Comment by coleifer** [comment]
Nah I just updated it, but you're probably best managing your own repo and rebasing as needed if you want to track master so closely.

**Comment by darren-recentive** [comment]
Yeah, I agree, I'll start doing that to avoid bothering you.
What are the long term plans for https://github.com/coleifer/peewee/tree/feature/psycopg3-fixes?
Are there open questions/tasks that I could help with?

**Comment by coleifer** [comment]
I just need to refactor some of the stuff that’s duplicated in the tests and then I’ll clean it up and merge. Sorry it’s been low on my priorities. I’ve been annoyed by the way it handles certain things like not allowing None as a parameter and have just been a little unsure how I want to handle the implementation.

**Comment by coleifer** [comment]
Just a heads-up, saw a comment on IRC that I missed (apologies) - I do intend to merge this, just have not had time.

**Comment by coleifer** [comment]
This is merged now.

**Comment by darren-recentive** [comment]
> This is merged now.

Thank you! :)
