### ISSUE TITLE
The `Model` class should provide a `__str__()` for heuristic string representation of the model object

### ISSUE THREAD

**Issue by redstoneleo** [coleifer/peewee#2828]
The `Model` class should provide a `__str__()` for heuristic string representation of the model object, let's take this as an example,
https://docs.peewee-orm.com/en/latest/peewee/quickstart.html#getting-single-records
Currently `print(grandma)` just returns `<some number>`, which is confusing and not heuristic to guide attribute access of the record like `grandma.name`, and is also counter to the philosophy that 

> Peewee is a simple and small ORM. It has few (but **expressive**) concepts, making it **easy to learn and intuitive to use**.

One solution is to define the `__str__()` of `Model` to represent the record as something like `Person object at <hex address>`, or even better the [`namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) like representation of the object.

**Comment by coleifer** [comment]
By default it uses the primary key as the `__str__()` and the `__repr__` contains the model name. You are encouraged to override this to something more suitable for your particular model.

**Comment by redstoneleo** [comment]
I still think to change the default behavior as I said above can benefit peewee beginners.
