### ISSUE TITLE
migrator.drop_column is not working

### ISSUE THREAD

**Issue by Hojagulyyev** [coleifer/peewee#2829]
Attempting to drop a table's column in Sqlite DB fails with:

File "/home/.../venv/lib/python3.11/site-packages/peewee.py", line 3252, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "DROP": syntax error

**peewee==3.17.0**
**fastapi==0.109.0**

## Test code

```
# db.py
from peewee import *
from playhouse.migrate import *


db = SqliteDatabase('people.db')


class Person(Model):
    name = CharField()
    date_of_birth = DateField()
    age = SmallIntegerField()

    class Meta:
        database = db


class Pet(Model):
    owner = ForeignKeyField(Person, backref='pets')
    name = CharField()
    animal_type = CharField()

    class Meta:
        database = db


db.connect()
db.create_tables([Person, Pet])

migrator = SqliteMigrator(db)
migrate(
    migrator.drop_column(
        Person._meta.table_name,
        "date_of_birth"
    ),
)
db.close()
```

I use FastAPI and make migrations with below command (just run fastapi server)
```
uvicorn main:app --reload
```

migrator's rename_column, add_column, ... methods works
I don't yet know the correct approach (folder, file structure e.g like in djangoORM) to migrate with Peewee

**Comment by coleifer** [comment]
Seems working fine for me:

```python
db.connect()
db.create_tables([Person, Pet])

migrator = SqliteMigrator(db)
migrate(
    migrator.drop_column(
        Person._meta.table_name,
        "date_of_birth"
    ),
)
db.close()

# These lines are added:
db.connect()
for col in db.get_columns('person'):
    print(col.name)
```

Output:

```
id
name
age
```

**Comment by coleifer** [comment]
Out of curiosity, what version of sqlite do you use? You can find this:

```
import sqlite3
print(sqlite3.sqlite_version_info)
```

**Comment by coleifer** [comment]
I run a newer sqlite3 locally that has full support for ALTER ... DROP COLUMN but after forcing it to use the legacy form, it is still working fine for me:

```python
migrator = SqliteMigrator(db)
migrate(
    migrator.drop_column(
        Person._meta.table_name,
        "date_of_birth",
        legacy=True,
    ),
)
db.close()

for col in db.get_columns(Person._meta.table_name):
    print(col.name)
```

Still correctly prints:

```
id
name
age
```

**Comment by Hojagulyyev** [comment]
sqlite3.sqlite_version_info (3, 31, 1)

**Comment by Hojagulyyev** [comment]
But sqlite shows

```
sqlite3 people.db

SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> PRAGMA table_info(person);
0|id|INTEGER|1||1
1|name|VARCHAR(255)|1||0
2|date_of_birth|DATE|1||0
3|age|INTEGER|0||0
sqlite>
```

**Comment by Hojagulyyev** [comment]
> I run a newer sqlite3 locally that has full support for ALTER ... DROP COLUMN but after forcing it to use the legacy form, it is still working fine for me:
> 
> ```python
> migrator = SqliteMigrator(db)
> migrate(
>     migrator.drop_column(
>         Person._meta.table_name,
>         "date_of_birth",
>         legacy=True,
>     ),
> )
> db.close()
> 
> for col in db.get_columns(Person._meta.table_name):
>     print(col.name)
> ```
> 
> Still correctly prints:
> 
> ```
> id
> name
> age
> ```

does `legacy=True,` matter?

**Comment by coleifer** [comment]
Try using the full path to the database file, I'm guessing you've made some mistake. The migration stuff is working just fine. It is also covered by unit tests...

**Comment by Hojagulyyev** [comment]
I tried with db full path and get:
```
    raise OperationalError('Connection already opened.')
peewee.OperationalError: Connection already opened.
```

then I undo it and still get it: `Connection already opened.`

then I removed the `db.connect()` line and tried again, it fails with:
```
    cursor.execute(sql, params or ())
peewee.OperationalError: near "DROP": syntax error
```

**could this be due to the asynchrony of fastapi?** 
in my opinion no

**Comment by Hojagulyyev** [comment]
> Try using the full path to the database file, I'm guessing you've made some mistake. The migration stuff is working just fine. It is also covered by unit tests...

I did this using docs https://github.com/coleifer/peewee/blob/master/docs/peewee/playhouse.rst#id215.

**Comment by Hojagulyyev** [comment]
@coleifer I tried everything again from scratch, the result is the same

**Comment by Hojagulyyev** [comment]
It worked for me after `legacy=True` param
```
migrate(
    migrator.drop_column(
        Person._meta.table_name,
        "date_of_birth",
        legacy=True,
    ),
)
```
Why is this default value False?
What exactly does the "legacy" do?

**Comment by coleifer** [comment]
There was a bug in the version check for sqlite support of drop column. I had it as 3.25, but in fact DROP was not added until 3.35, that's why you were seeing the error. Thanks for reporting this, `legacy=True` should continue to work until you pull in this patch -- what `legacy=True` does is works around limitations in Sqlite's ALTER TABLE support by:

1. Creating a new table w/the desired schema
2. Copying all data into the new table
3. Dropping the original table
4. Renaming the new table to the original table's name.

**Comment by Hojagulyyev** [comment]
I'll pull this patch and going to use drop_column method without "legacy" param

Thanks for your efforts
