### ISSUE TITLE
[Question] Unique index of ArrayField

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2833]
```python
class Marriage(BaseModel):
    users = postgres_ext.ArrayField(pw.BigIntegerField)
    chat_id = pw.BigIntegerField()

    class Meta:
        indexes = (
            (('users', "chat_id"), True),
        )
```

Hi! I have this model. I want to make the users and chat_id field a unique value. But when users have the same value but in different sequence the index does not work. Can you tell me how to implement it?

Already created row on database:
`users=[1,2], chat_id=1`
Try to create the same users but different positions on array:
`users=[2,1], chat_id=1 # Need to triggers UniqueViolation`

**Comment by coleifer** [comment]
I'd suggest consulting the Postgres folks as I'm not sure how you'd do that. I think the "best" solution is to store them flat:

```python
class Marriage(BaseModel):
    chat_id = pw.BigIntegerField()
    user_id = pw.BigIntegerField()
    class Meta:
        indexes = (
            (('chat_id', 'user_id'), True),
        )

for uid in (1, 2):
    Marriage.create(user_id=uid, chat_id=1)
```

Then to get all users for a marriage:

```
q = Marriage.select(Marriage.user_id).where(Marriage.chat_id == 1)
uids = [uid for uid, in q]
```
