### ISSUE TITLE
Is it possible to export ModelSelect object as string or json and then load back to ModelSelect object?

### ISSUE THREAD

**Issue by makarworld** [coleifer/peewee#2836]
> Question on [stackoverflow](https://stackoverflow.com/questions/77949042/is-it-possible-save-peewee-sql-query-as-string-or-json-and-then-load-back-to-mod)

I want to save a `ModelSelect` object to the redis repository and I need to serialize the object, but I don't know how I can do it.
I want to use something like `playhouse.shortcuts.model_to_dict` but for the `ModelSelect` query instead of `Model`.

I know about the possibility to save the query with `.sql()` and execute it later, but I need to do some actions with the query after deserialization (like `.limit()` or `.offset()`), and in this case it is not possible. 

Example how my dream about:

```python
from peewee import * 

db = SqliteDatabase(':memory:')

class User(Model): 
    id:   int 
    name: str = TextField()
    
    class Meta:
        database = db

# create User table
User.create_table()

# add new User
User(name = "new_user").save()

query = User.select().where(User.id == 1)

# export to dict
dict_query = modelselect_to_dict(query)
# something like: {"table": "user", "model_name": "User", "fields": [...], "_where": ..., ...}

# import from dict
saved_query = dict_to_modelselect(dict_query)
print(list(saved_query))
# [<User: 1>]
```

**Comment by coleifer** [comment]
This is the wrong idea. Serializing model instances to dicts is perfectly fine, and they can be de-serialized back to model instances. You cannot reasonably expect to serialize a query object, though. The query just represents the SQL and, when executed, contains a reference to a cursor object.

If you want to serialize an object, you would:

```
# select User with id = 1 -- note call to .get()!!
item = User.select().where(User.id == 1).get()
data = model_to_dict(item)
```

**Comment by makarworld** [comment]
I need to save a `ModelSelect` object as a context for the keyboard, for example: I want to show all banned users, so I make a query `User.select().where(User.ban == True)` and provide to keyboard a width and height, in depth my function works with the query object to get all rows for the current page (with `.offset()` and `.limit()`). I can't save the result of the query because it might take a lot of memory, and the database might change after the keyboard is created. I am looking for a way to export the `ModelSelect` object and import it again when needed.

**Comment by makarworld** [comment]
I solved my problem. But it may cause error in complex query with joins, but for small tests it looks fine.

```python
from peewee import ModelSelect, Expression
from peewee import * 
from typing import *

# create database
db = SqliteDatabase(':memory:')

class User(Model): 
    id:   int 
    name: str = TextField()
    
    class Meta:
        database = db

# create User table
User.create_table()

# add new User
User(name = "new_user").save()

class ModelSelectJSONify:

    @staticmethod
    # function for export ModelSelect to dict
    def dump(item: ModelSelect) -> dict:
        result = {}
        for key, value in item.__dict__.items():
            if key in ('_database', '_from_list', '_returning'):
                continue

            if not isinstance(value, (str, int, float, bool, dict)) and value is not None:
                
                if isinstance(value, Expression):
                    value = dict(value_type = "Expression",
                                 value = ModelSelectJSONify.dump(value))
                elif isinstance(value, list):
                    value = list(map(ModelSelectJSONify._dump_name, value))
                else:
                    value = ModelSelectJSONify._dump_name(value)

            result[key] = value
        
        return result


    @staticmethod
    # function for import dict back to Any
    def _dump_name(value: Any) -> str:
        if hasattr(value, '__name__'):
            return f"MODEL {value.__name__}"
        else:
            return f"MODEL_PROPERTY {value.model.__name__}.{value.name}"

    @staticmethod
    # function for import dict back to Any
    def _load_name(model: Model, value: str) -> Any:
        if value.startswith(f"MODEL_PROPERTY {model.__name__}"):
            return getattr(model, value.replace(f"MODEL_PROPERTY {model.__name__}.", ""))
        
        elif value.startswith(f"MODEL {model.__name__}"):
            return model
        
        else:
            return value
        
    @staticmethod
    # function for import dict back to Any
    def _direct_load(obj: Any, data: dict, model: Model = None) -> Any:
        result = {}
        for key, value in data.items():
            if key in ('model'):
                continue

            if isinstance(value, dict) and value.get("value_type"):
                match value["value_type"]:
                    case "Expression":
                        value = ModelSelectJSONify._direct_load(Expression, value["value"], model = model)
            
            if isinstance(value, str) and model is not None:
                value = ModelSelectJSONify._load_name(model, value)
            elif isinstance(value, list) and model is not None:
                value = [ModelSelectJSONify._load_name(model, x) for x in value]

            result[key] = value

        return obj(**result)

    @staticmethod
    # function for import dict back to ModelSelect
    def load(model: Model, data: dict) -> ModelSelect:
        result = model.select()
        for key, value in data.items():
            if key in ('model'):
                continue

            if isinstance(value, dict) and value.get("value_type"):
                match value["value_type"]:
                    case "Expression":
                        value = ModelSelectJSONify._direct_load(Expression, value["value"], model = model)
            
            if isinstance(value, str) and model is not None:
                value = ModelSelectJSONify._load_name(model, value)

            elif isinstance(value, list) and model is not None:
                value = [ModelSelectJSONify._load_name(model, x) for x in value]

            setattr(result, key, value)
        return result

def modelselect_to_dict(item: ModelSelect) -> dict:
    return ModelSelectJSONify.dump(item)

def dict_to_modelselect(model: Model, data: dict) -> ModelSelect:
    return ModelSelectJSONify.load(model, data)

item = User.select().where((User.id == 1) & (User.name == "new_user")).limit(1).offset(0).group_by(User.id)
dicted = modelselect_to_dict(item)
print("Exported as dict:", dicted)

usered = dict_to_modelselect(User, dicted)

print("Initial SQL:", item.sql())
# ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" WHERE (("t1"."id" = ?) AND ("t1"."name" = ?)) GROUP BY "t1"."id" LIMIT ? OFFSET ?', [1, 'new_user', 1, 0])
print("Imported SQL:", usered.sql())
# ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" WHERE (("t1"."id" = ?) AND ("t1"."name" = ?)) GROUP BY "t1"."id" LIMIT ? OFFSET ?', [1, 'new_user', 1, 0])

print("Equal:", item.__dict__ == usered.__dict__)
# True

```

**Comment by darren-recentive** [comment]
> I have written a serializer for the `ModelSelect` object.
> 
> ```python
> from __future__ import annotations
> from peewee import * 
> from typing import *
> import peewee
> 
> # create database
> db = SqliteDatabase(':memory:')
> 
> class User(Model): 
>     id:   int 
>     name: str = TextField()
>     #
>     posts: List[Post]
> 
>     class Meta:
>         database = db
> 
> class Post(Model):
>     id: int
>     title: str = TextField()
>     author: User = ForeignKeyField(User, backref = 'posts')
>     #
>     author_id: int
> 
>     class Meta:
>         database = db
> 
> # create User table
> User.create_table()
> Post.create_table()
> 
> # add new User
> user = User(name = "new_user")
> user.save()
> 
> # add new Post and set user as author
> Post(title = "first_post", author = user).save()
> 
> class Serializer:
>     """
>     ## class for serializing and deserializing `peewee.ModelSelect` object
>     
>     :param main_model_class: Main class from which all models are inherited. (Optional)
> 
>     ### Usage:
> 
>     ```python
>     import peewee
> 
>     # create database
>     db = peewee.SqliteDatabase(':memory:')
> 
>     class User(peewee.Model): 
>         id:   int 
>         name: str = peewee.TextField()
> 
>         class Meta:
>             database = db
> 
>     # create User table
>     User.create_table()
> 
>     # add new User
>     User(name = "first user").save()
> 
>     # create query
>     query = User.select().where(User.id == 1).limit(1)
>     print(query.sql())
>     # ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" WHERE ("t1"."id" = ?) LIMIT ?', [1, 1])
>     print(list(query))
>     # [<User: 1>]
>     
>     # serialize query to dict
>     serialized = Serializer(main_model_class = peewee.Model).serialize(query)
>     print(serialized)
>     # {'model': 'MODEL User', '_join_ctx': ..., ...}
>     # Now you can save serialized dict
> 
>     deserialized = Serializer(main_model_class = peewee.Model).deserialize(data)
>     print(deserialized.sql())
>     # ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" WHERE ("t1"."id" = ?) LIMIT ?', [1, 1])
>     print(list(deserialized))
>     # [<User: 1>]
>     ```
> 
>     """
>     mark_serialized_key = "__serialized__"
>     reserved_objects: tuple[Union[peewee.Join, peewee.Expression]] = (
>         peewee.Join, peewee.Expression
>     )
>     reserved_objects_names: tuple[str] = tuple(
>         x.__name__ 
>         for x in reserved_objects
>     )
> 
>     def __init__(self, main_model_class: Optional[peewee.Model] = peewee.Model):
>         self.model_class = main_model_class
>         self.models = list(self.reserved_objects) + main_model_class.__subclasses__()
>         
>     def _get_model_by_name(self, name: str) -> Union[peewee.Model, Any, None]:
>         """
>         Restore string name of object to real object
> 
>         :param name: name of object
>         """
>         for model in self.models:
>             if name == model.__name__:
>                 return model
>         return None
>     
>     # # # # # # # # # # # # #
>     #                       #
>     #    Serialize part     #
>     #                       #
>     # # # # # # # # # # # # #
> 
>     def serialize(self, obj: Union[peewee.ModelSelect, Any, dict]) -> dict:
>         """
>         Serialize `peewee.ModelSelect` object to dict
> 
>         :param obj: `peewee.ModelSelect` object
>         """
>         result = {}
>         obj_dict = obj.__dict__ if isinstance(obj, dict) is False else obj
> 
>         for key, value in obj_dict.items():
>             if key == '_database' or value is None:
>                 continue
> 
>             key = self._serialize_object(value = key)
> 
>             if isinstance(value, (str, int, float, bool)) is False:
>                 value = self._serialize_object(value)
> 
>             result[key] = value
>         
>         if isinstance(obj, peewee.ModelSelect):
>             result[self.mark_serialized_key] = True
> 
>         return result
> 
>     def _serialize_array(self, value: Union[list, tuple]) -> Union[list, tuple]:
>         """
>         Serialize list or tuple 
> 
>         :param value: list or tuple
>         """
>         result = [
>             self._serialize_object(item)
>             for item in value
>         ]
> 
>         if isinstance(value, tuple):
>             return tuple(result)
>         
>         return result
>         
>     def _serialize_object(self, value: Union[peewee.Model, str, dict, list, tuple, Any]) -> Union[str, dict, Any]:
>         """
>         Serialize object
> 
>         :param value: object
>         """
>         if isinstance(value, dict):
>             return self.serialize(value)
>         
>         elif isinstance(value, (list, tuple)):
>             return self._serialize_array(value)
>         
>         elif isinstance(value, self.reserved_objects):
>             return dict(
>                 value_type = value.__class__.__name__,
>                 value      = self.serialize(value)
>             )
>         
>         elif hasattr(value, '__name__'):
>             return f"MODEL {value.__name__}"
>         
>         elif hasattr(value, 'model'):
>             return f"MODEL_PROPERTY {value.model.__name__}.{value.name}"
>         
>         else: 
>             return value
> 
>     # # # # # # # # # # # # # #
>     #                         #
>     #    Deserialize part     #
>     #                         #
>     # # # # # # # # # # # # # #
> 
>     def deserialize(self, data: dict) -> peewee.ModelSelect:
>         """
>         Deserialize dict to `peewee.ModelSelect` object
> 
>         :param data: dict
>         """
>         result = {}
> 
>         if data.get(self.mark_serialized_key):
>             main_model: peewee.Model = self._deserialize_object(data.get('model'))
> 
>         for key, value in data.items():
>             if key == self.mark_serialized_key: 
>                 continue
> 
>             key = self._deserialize_object(key)
>             value = self._deserialize_object(value)
> 
>             if isinstance(value, self.reserved_objects) and key == '_on':
>                 key = 'on'
> 
>             result[key] = value
> 
>         if data.get(self.mark_serialized_key):
>             selection = main_model.select()
> 
>             for k, v in result.items():
>                 setattr(selection, k, v)
>             
>             return selection
> 
>         return result
> 
>     def _deserialize_array(self, value: Union[list, tuple]) -> Union[list, tuple]:
>         """
>         Deserialize list or tuple
> 
>         :param value: list or tuple
>         """
>         result = [
>             self._deserialize_object(item)
>             for item in value
>         ]
> 
>         if isinstance(value, tuple):
>             return tuple(result)
>         
>         return result
> 
>     def _deserialize_object(self, value: Any) -> Any:
>         """
>         Deserialize object
> 
>         :param value: object
>         """
>         if isinstance(value, dict) and value.get("value_type") in self.reserved_objects_names:
>             obj = self._get_model_by_name(value["value_type"])
>             return obj(**self.deserialize(value["value"]))
>         
>         elif isinstance(value, dict):
>             return self.deserialize(value)
>         
>         elif isinstance(value, (list, tuple)):
>             return self._deserialize_array(value)
> 
>         elif isinstance(value, str) and value.startswith("MODEL_PROPERTY"):
>             model_name, property_name = value.replace("MODEL_PROPERTY ", "").split('.')
>             model = self._get_model_by_name(model_name)
>             return getattr(model, property_name)
>         
>         elif isinstance(value, str) and value.startswith("MODEL"):
>             model_name = value.replace("MODEL ", "")
>             return self._get_model_by_name(model_name)
>         
>         else:
>             return value
> 
> # shortcuts
> def modelselect_to_dict(item: ModelSelect) -> dict:
>     """Shortcut for export `peewee.ModelSelect` to dict"""
>     return Serializer().serialize(item)
> 
> def dict_to_modelselect(data: dict, main_model_class: Optional[peewee.Model] = peewee.Model) -> ModelSelect:
>     """Shortcut for import `peewee.ModelSelect` from dict"""
>     return Serializer(main_model_class).deserialize(data)
> 
> # create query
> item = User.select().join(Post, on = (User.id == Post.author_id)).where((User.id == 1) & (User.name == "new_user")).limit(1).offset(0).group_by(User.id)
> 
> # export ModelSelect query to dict
> dicted = modelselect_to_dict(item)
> print("Exported as dict:\n", dicted, "\n")
> 
> # import dict to ModelSelect
> usered = dict_to_modelselect(dicted)
> 
> # query sqls
> print("Initial SQL:\n", item.sql())
> # ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" INNER JOIN "post" AS "t2" ON ("t1"."id" = "t2"."author_id") WHERE (("t1"."id" = ?) AND ("t1"."name" = ?)) GROUP BY "t1"."id" LIMIT ? OFFSET ?', [1, 'new_user', 1, 0])
> print("Restored SQL:\n", usered.sql(), "\n")
> # ('SELECT "t1"."id", "t1"."name" FROM "user" AS "t1" INNER JOIN "post" AS "t2" ON ("t1"."id" = "t2"."author_id") WHERE (("t1"."id" = ?) AND ("t1"."name" = ?)) GROUP BY "t1"."id" LIMIT ? OFFSET ?', [1, 'new_user', 1, 0])
> 
> # query results
> print("Initial query result:\n", list(item))
> print("Restored query result:\n", list(usered))
> 
> # compare initial and restored query
> print("\nEqual:", item.sql() == usered.sql() and list(item) == list(usered), "\n")
> ```

Thanks for sharing! 😄
