### ISSUE TITLE
error: Name "MySQLDatabase" is not defined in ci/cd

### ISSUE THREAD

**Issue by marc-at-brightnight** [coleifer/peewee#2840]
Hi,

I'm using yfinance as a dependency for my project, for which peewee is a dependency. I'm not having any problems locally but in ci/cd, I'm getting the following:

```
venv/bin/pwiz.py:34: error: Name "MySQLDatabase" is not defined  [name-defined]
venv/bin/pwiz.py:35: error: Name "PostgresqlDatabase" is not defined  [name-defined]
venv/bin/pwiz.py:36: error: Name "SqliteDatabase" is not defined  [name-defined]
```

It looks like according to my `poetry.lock`, it is installing peewee version 3.17.1, which seems to be latest. here are my poetry dependencies, in case relevant:
```
[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.0"
scipy = "^1.12.0"
matplotlib = "^3.8.2"
pydantic = "^2.5.3"
yfinance = "^0.2.36"
```

I'm sure I'm missing something but have googled and not found anything useful. Tried adding `pymysql` and `psycopg2-binary` to my poetry dependencies but it didn't help. Any help is appreciated.

**Comment by coleifer** [comment]
I don't know where those errors are coming from or why you're invoking `pwiz` inside your ci/cd pipeline -- possibly you have your own or another file named `peewee.py`? Nonetheless this is some issue on your end and not with Peewee... I have no idea what the problem could be.
