### ISSUE TITLE
Documentation is wrong or not up to date for the creation of objects from model.

### ISSUE THREAD

**Issue by cldtech** [coleifer/peewee#2841]
Hi, i lost some time on an issue that could easily be corrected so i report it here though it is about the documentation.

Almost all examples for creating a new object/record such as [here](http://docs.peewee-orm.com/en/latest/peewee/quickstart.html#storing-data) in the quickstart or [here](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#ArrayField) uses the following form;

```
from datetime import date
uncle_bob = Person(name='Bob', birthday=date(1960, 1, 15))
uncle_bob.save() # bob is now stored in the database
```
This does not work, the object is never written to the database and there are no error produced.

While this form works as expected using the create function of Model:

```
from datetime import date
uncle_bob = Person.create(name='Bob', birthday=date(1960, 1, 15))
uncle_bob.save() # bob is now stored in the database
```

Using the pythonic way of instantiating an object without the create function does not work and does not generate any error.

Please update the docs. :)

**Comment by coleifer** [comment]
This does work:

```
from datetime import date
uncle_bob = Person(name='Bob', birthday=date(1960, 1, 15))
uncle_bob.save() # bob is now stored in the database
```

The docs are correct.

**Comment by coleifer** [comment]
https://github.com/coleifer/peewee/blob/4d177b7a3e971f22192409d50161198bf5afe40a/tests/models.py#L600

**Comment by cldtech** [comment]
No it is not, i tried it on two different computers with not even the same OS and verified the database with Dbeaver. Nothing is recorded without the create function.

**Comment by yash2001cp** [comment]
> No it is not, i tried it on two different computers with not even the same OS and verified the database with Dbeaver. Nothing is recorded without the create function. Don't you care about your program?

just enable the logger and see whats the real problem , if u have uuid as ur primary key u need add default constraint on db level for .save to work

```
from peewee import *
from database.db_session import db
import uuid

class Tester(Model):
    id = UUIDField(primary_key = True, default = uuid.uuid4)
    name = CharField()
    
    class Meta:
        database = db
        
Tester.create_table()

t = Tester(name = 'A')

t.save() # this doesnt work but as soon as u change to id = UUIDField(primary_key = True, constraints=[SQL("DEFAULT gen_random_uuid()")])

Tester.drop_table()
```
