### ISSUE TITLE
Documentation missing for ArrayField.

### ISSUE THREAD

**Issue by cldtech** [coleifer/peewee#2842]
Hi, in the [doc for the ArrayField](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#ArrayField) there are nothing saying from where to import ArrayField.  Without import i of course get `NameError: name 'ArrayField' is not defined. Did you mean: 'AnyField'?` Can anyone tell me from where i can import ArrayField while i wait for the doc to get updated? I know it is in the playhouse module but i can't find it.

**Comment by coleifer** [comment]
It’s right there in the link you pasted, in the Postgres extension docs. If you scroll up a bit from your link you’ll see.

**Comment by cldtech** [comment]
Way to answer without even giving the damn response. Just go to hell i won't use your code anywhere anymore.
