### ISSUE TITLE
Seeking Clarification on wrapped_count() Method in Peewee 3.17.1

### ISSUE THREAD

**Issue by abhisekharh1988** [coleifer/peewee#2848]
I am currently in the process of upgrading from Peewee 2.10.1 to the latest version, Peewee 3.17.1. During this process, I have noticed that the wrapped_count() method, which allows us to count the number of rows returned by a query without actually fetching the rows, has been removed.

Could you please provide some guidance on the alternative method or approach to achieve the same functionality in the latest Peewee version?

**Comment by coleifer** [comment]
You can just use `.count()`, e.g. `User.select().where(...).count()`
