### ISSUE TITLE
[Question] Performance gain or loss when paginating in full-text search PostgreSQL

### ISSUE THREAD

**Issue by DRMPN** [coleifer/peewee#2849]
Hello!

I would like to create a pagination for search results. I'm not sure where to make it, on the client or server side.
For now, I have chosen server side.

To perform a search, I create a query like this:
`Cell.select(...).join(...).where(Cell.search_data.match(term, "english", True))`

If I add `.paginate(page, 10)` to the query, will this increase or decrease search performance?

---
_Side note:_
To speed up the full-text search, I've created my model's field like this:
`search_data = TSVectorField(null=True)`

The column and index were correctly created in the database:
`search_data | tsvector |`
`cell_search_data" gin (search_data)`

Thanks <3

**Comment by coleifer** [comment]
You’ll need to profile, explain/analyze, and consult the docs for tsvector.
