### ISSUE TITLE
[Question] Seeking Guidance on Clause Class Removal in Peewee 3.17.1

### ISSUE THREAD

**Issue by abhisekharh1988** [coleifer/peewee#2850]
I am currently in the process of upgrading from Peewee 2.10.1 to the latest version, Peewee 3.17.1. During this process, I have encountered an issue where the 'Clause' class, which was available in Peewee 2.10.1, is no longer available.

As a result, the query we had written using Peewee 2.10.1 is now failing. Could you please provide some guidance on the alternative method or approach to achieve the same functionality in the latest Peewee version?

```
Thread.select(
    Thread.column_1,
    fn.Count(Thread.id).alias("duplicate_count"),
    fn.Group_concat(
        Clause(Thread.id, SQL("ORDER BY"), Thread.time_created, SQL("DESC"))
    ).alias("thread_list"),
    fn.IF(
        fn.substr(Thread.column_2, 1, 2) == "+1",
        fn.substr(Thread.column_2, 3, 10),
        Thread.column_2,
    ).alias("phone"),
)
.where(fn.Length(Thread.column_2) <= 10)
.group_by(Thread.column_1, SQL("phone"))
.having(fn.Count(Thread.column_1) > 1)
```

**Comment by coleifer** [comment]
`NodeList`. Please try to at least figure it out before opening issues bro.
