### ISSUE TITLE
is_null() broken when using psycopg3

### ISSUE THREAD

**Issue by vethan** [coleifer/peewee#2851]
Attempting a Model.select().where(Model.field.is_null(False)) will currently fail when using a Psycopg3Database.  Seems to be a typing error when generating the SQL

**Comment by coleifer** [comment]
Yeah it's extremely annoying but psycopg3/libpq decided that they will parameterize everything except `NULL`, so we have to special-case any time `None` is used as a value and replace with the string `NULL`. This is implemented in the `feature/psycopg3` branch but if you prefer to stay on the main branch you can use something like this:

```python
from peewee import Expression, SQL

def is_null(lhs, is_null=True):
    return Expression(lhs, 'IS' if is_null else 'IS NOT', SQL('NULL'))

# ...

query = Model.select().where(is_null(Model.field))

query = Model.select().where(is_null(Model.field, False))
```

**Comment by vethan** [comment]
Oh that's super annoying... Thanks for the quick reply, I'll use that workaround for now!  Any idea when that branch will get merged in?

**Comment by coleifer** [comment]
I need to find some time to clean it up but I intend to get it merged in.
