### ISSUE TITLE
How to mix PooledSqliteDatabase and SqlCipherExtDatabase

### ISSUE THREAD

**Issue by devops-dmdx** [coleifer/peewee#2854]
Hi,

First thank you for this great package that, i must said, does the job and does it well!

I am wondering how could my desktop app couple `PooledSqliteDatabase` with `SqlCipherExtDatabase`?
There is no such `PooledSqlCipherExtDatabase` already available in the `playhouse.pool` module.

Best,
Hugo

**Comment by coleifer** [comment]
You'll just want to make a subclass...

```python
from playhouse.pool import _PooledSqliteDatabase
from playhouse.sqlcipher_ext import *

class PooledSqlCipherDatabase(_PooledSqliteDatabase, SqlCipherDatabase):
    pass
```

**Comment by devops-dmdx** [comment]
Indeed, simple. Though, i generally avoid importing protected members as they "may change without prior notice". 

Would it make sense to include it in `peewee` officially?

**Comment by coleifer** [comment]
You can take a look at the code in the modules referenced and see if there’s another way to accomplish your goal.
