### ISSUE TITLE
Not optimal primary key lookup

### ISSUE THREAD

**Issue by Demianight** [coleifer/peewee#2855]
https://github.com/coleifer/peewee/blob/4d177b7a3e971f22192409d50161198bf5afe40a/peewee.py#L6799

Consider that I have other field set as primary key. It's not int instance. So this method does not work properly. Givin' the NotExist error. I am not sure but it seems loke len(query) == 1 is already enough for it to work.

Thanks!

**Comment by coleifer** [comment]
It's not enough for it to work. That line is to give a short-hand for:

```python
class Person(db.Model):
    name = TextField()

Person.get(1)  # Get person w/id=1
Person.get(Person.id == 1)  # Same as above, also len(query) == 1
Person.get(id=1)  # Similar to above, but does not use *query
```

**Comment by Demianight** [comment]
I understand, but why should int check exist? If get uses Model.primary_key == ... thing?

**Comment by Demianight** [comment]
I got you. I will try to think about smth, cause get_or_none does not work with "custom" primary keys, in `Model.get_or_none("some name")` way, that is kinda unfortunate.

Thanks for quick response! Peewee is awesome anyways)
