### ISSUE TITLE
Cant create PK via Meta class OUTSIDE of Model class defenition

### ISSUE THREAD

**Issue by MikhailDunaev** [coleifer/peewee#2867]
It seams strange that I can not config primary key outside the Model class.

class MyModel(BaseModel):
   some_fld ...
   class Meta:
      primary_key = False

my_meta = MyModel._meta
my_meta.primary_key = CompositeKey('id', 'some_fld')

I want to config tables by myself in such a way (partitionig).

**Comment by coleifer** [comment]
You'll need to figure it out yourself, but you can dynamically create the classes either inside a function or using `type()`.
