### ISSUE TITLE
Feature Request: Encrypted Field in playhouse.fields

### ISSUE THREAD

**Issue by DMcP89** [coleifer/peewee#2868]
I have recently implemented a custom encrypted field using peewee in my app and I believe it would make a nice addition to the playhouse fields extensions. 

I know a previous attempt at an encrypted field was removed due to security concerns (#1264 ) however, my implementation leverages the cryptography library which was the recommendation from that thread.

```
from cryptography.fernet import Fernet
from peewee import Field


class EncryptedField(Field):
    def __init__(self, key, *args, **kwargs):
        super(EncryptedField, self).__init__(*args, **kwargs)
        self.key = key

    def db_value(self, value):
        f = Fernet(self.key)
        return f.encrypt(value.encode()).decode()

    def python_value(self, value):
        f = Fernet(self.key)
        return f.decrypt(value.encode()).decode()
```
https://github.com/DMcP89/harambot/blob/release/v0.4.0-Beta/harambot/database/fields.py

As you can see it is a pretty straightforward implementation. A suitable key value can be generated by simply calling:
```
key = Fernet.generate_key()
```
 I would be happy to open up a PR to have this added if you like.

**Comment by oz123** [comment]
This adds an unnecessary dependency on cryptography.
You can use scrypt or Blake2 from the Python STL.
Both are very fast and efficient.
https://docs.python.org/3/library/hashlib.html
