### ISSUE TITLE
Fields are missing in model

### ISSUE THREAD

**Issue by BulatTim1** [coleifer/peewee#2870]
I made a model like in quickstart, but for some reason I can't get the fields from the model... I tried different versions of Python, different databases, and tried installing the version from Github. But I keep getting this error.

Model (models.py):
```python
class User(Model):
    firstName: CharField()
    lastName: CharField()
    email: CharField(unique=True) 
    password: CharField()
    id: AutoField()
    class Meta:
        database = db
```

Line where I getting error (auth.py):
```python 
user = User.get(User.email == model.email)
```

In databases only one field - id:
1. sqlite:
![image](https://github.com/coleifer/peewee/assets/32904838/2287d205-7b69-40ac-90a5-930025641d15)
2. postgresql:
![image](https://github.com/coleifer/peewee/assets/32904838/affdd13f-4395-4856-b9f3-547094d46b47)
3. in code:
![image](https://github.com/coleifer/peewee/assets/32904838/896349fb-846a-440e-9f7e-2d68b1bf54ed)

This is my first time using peewee, what’s wrong? Or do I need manually create all tables, because peewee can’t do that?
Win11 23H2, Python 3.11.1 and 3.9.9.

**Comment by coleifer** [comment]
You are using colon when you should use equals for the fields.

**Comment by BulatTim1** [comment]
Thank you! Sorry to bother you with such a stupid mistake... Have a nice day ☺️
