### ISSUE TITLE
Redundant Database Queries Occurring In Select Operations When No Data Is Present

### ISSUE THREAD

**Issue by abhisekharh1988** [coleifer/peewee#2871]
Observed redundant database queries occurring in select operations when no data is present. Please find below the code snippet: 
```
@classmethod
def get_for_resource(cls, resource_type: str, resource_id: str) -> List[SomeModel]:
    return list(
        cls.select().where(
            cls.resource_id == resource_id, cls.resource_type == resource_type
        )
    )
```
The list() function invokes the BaseQuery's __len__() function, followed by the __iter__() function, and then again __len__() function. Within __len__() and __iter__(), Peewee includes a check called _ensure_execution():
```
def _ensure_execution(self):
    if not self._cursor_wrapper:
        if not self._database:
            raise ValueError('Query has not been executed.')
        self.execute()
```
Despite self._cursor_wrapper existing with a result set size of 0, the query still executes. We're unsure if this behaviour is intentional or if we should modify the condition to:
```
def _ensure_execution(self):
    if self._cursor_wrapper is None:
        if not self._database:
            raise ValueError('Query has not been executed.')
        self.execute()
```

**Comment by abhisekharh1988** [comment]
Furthermore, I've observed that modifying the code as shown below prevents redundant queries. However, considering our legacy code base, it may not be feasible to implement this change in multiple places:
```
@classmethod
def get_for_resource(cls, resource_type: str, resource_id: str) -> List[SomeModel]:
    cls.select().where(
        cls.resource_id == resource_id, cls.resource_type == resource_type
    ).objects()
```

**Comment by coleifer** [comment]
Thanks, this was a surprise. Fixed now.

**Comment by abhisekharh1988** [comment]
Thanks for the fix. :)
