### ISSUE TITLE
Transaction feature for SqliteQueueDatabase

### ISSUE THREAD

**Issue by travnick** [coleifer/peewee#2878]
As the example shows, current `SqliteQueueDatabase` implementation does not implement [transactions](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#transactions).

While doing a review it looks like it may be achieved by Thread-Local storage - so for each transaction, a local queue is created, and at the end it's flushed to the writer as a whole.

**Comment by coleifer** [comment]
No plans on implementing this, thanks though.
