### ISSUE TITLE
[Question] Block the possibility to change the default value

### ISSUE THREAD

**Issue by daeeros** [coleifer/peewee#2879]
At some point I noticed that the standard json value of the cooldowns attribute is changing, I must have made a mistake somewhere, so the question is, is it possible to block the change of the standard value? And to track it, at what point it happens, would be glad to have an example thanks <3

```python
import peewee as pw
import playhouse.postgres_ext as pw_ex
import time

class BaseModel(pw.Model):
    class Meta:
        database = database

class Player(BaseModel):
    user_id = pw.BigIntegerField(primary_key=True, unique=True)
    cooldowns = pw_ex.BinaryJSONField(default={
        "bonus": 0,
        "safe": 0,
        "bio": 0,
        "dinamite": 0,
        "transfer": 0,
        "rpcgame": 0,
        "double_reward": 0,
    })
    created = pw.BigIntegerField(default=time.time)
```

**Comment by coleifer** [comment]
You should never, as a rule, assign a mutable value to a default. Instead, if you intend to use a mutable value, use a callable:

```python

cooldowns = BinaryJSONField(default=lambda: {'bonus': 0, ...})
```
