### ISSUE TITLE
How do I add a ForeignKeyField to a model that is not yet defined?

### ISSUE THREAD

**Issue by stenci** [coleifer/peewee#2880]
Hi All,

I am redesigning a database and I need to add a foreign field to a table.
I have used this line after the definition of all the models, and it works well:
```python
playhouse.migrate.migrate(migrator.add_column('cncprogramsheet', 'inventory_sheet_id', 
                            peewee.ForeignKeyField(InventorySheet, 
                                      InventorySheet.id,
                                      backref='cnc_program_sheets', 
                                      null=True)))
```

As the changes to the database are increasing, I would like to move the migration up in the code, before the definition of the models. The previous line fails because `InventorySheet` is not defined yet, so I tried with this:
```python
playhouse.migrate.migrate(migrator.add_column('cncprogramsheet', 'inventory_sheet_id', 
                            peewee.DeferredForeignKey('InventorySheet', 
                                      to_field='id', 
                                      backref='cnc_program_sheets', 
                                      null=True)))
```

I thought the two lines were equivalent, but I am getting this error message:
```
AttributeError: 'DeferredForeignKey' object has no attribute 'model'
```

Why am I getting this error?
Is my approach completely wrong?

**Comment by coleifer** [comment]
Yeah, you can't use a deferred foreign key in a migration.
