### ISSUE TITLE
pwiz generates invalid Python code when creating BareField instances

### ISSUE THREAD

**Issue by fortysix2ahead** [coleifer/peewee#2909]
When used on the Adobe Lightroom sqlite db, pwiz will generate lines of code like the following, which is not valid Python code (single vs. double quotation marks):

```
state = BareField(constraints=[SQL("DEFAULT "master"")], null=True)
...
state = BareField(constraints=[SQL("DEFAULT "needs_binary"")], null=True)
...
binary_type = BareField(column_name='binaryType', constraints=[SQL("DEFAULT "original"")], null=True)
```

**Comment by coleifer** [comment]
Thanks, should be fixed now.

**Comment by xnny** [comment]
But my default value might be something like this:
```
DEFAULT '{}'::jsonb
```

After an update, I can no longer generate the demapped model using pwiz.

Changing double quotes to single quotes directly makes me incompatible with the old table structure.

**Comment by coleifer** [comment]
Oh wait, you're right @xnny - it should be preferring single quotes and escaping double quotes. Let me re-fix this.

**Comment by coleifer** [comment]
That should be fixed now.

**Comment by xnny** [comment]
Thank you very much.
