### ISSUE TITLE
create_tables() does not create any fields

### ISSUE THREAD

**Issue by PhilippCh** [coleifer/peewee#2912]
Hi there!

New to python in general, so please excuse it if I'm doing something wrong, but I cannot figure out why `create_tables([Task])` does not create the fields that I provided for the `Task` class.

```python
import datetime

from peewee import Model, TextField, BooleanField, DateTimeField
from playhouse.shortcuts import model_to_dict
from playhouse.sqlite_ext import SqliteExtDatabase

db = SqliteExtDatabase('shoppr.db', pragmas={
    'journal_mode': 'wal',  # WAL-mode.
    'cache_size': -64 * 1000,  # 64MB cache.
    'synchronous': 0})


class Task(Model):
    title: TextField()
    description: TextField()
    createdAt = DateTimeField(default=datetime.datetime.now)
    changedAt = DateTimeField(default=datetime.datetime.now)
    isDone: BooleanField(default=False)

    class Meta:
        database = db


db.connect()
db.create_tables([Task])
```

All that is created from this in the SQLite db is the id column:
![image](https://github.com/coleifer/peewee/assets/966567/8518eea5-b7c9-4d98-9f4b-5c5a9be28a21)

When debugging into `create_tables()`, it appears that the model is missing some fields (title, description, isDone) while others (createdAt, changedAt) are present, but not created in the DB.
![image](https://github.com/coleifer/peewee/assets/966567/a57e4021-68e8-4fd8-9fc1-811ae071b371)

Is there anything I'm doing wrong? Your help would be greatly appreciated!

**Comment by Seluj78** [comment]
You are using `:` instead of `=` :) 

Try

```py
import datetime

from peewee import Model, TextField, BooleanField, DateTimeField
from playhouse.shortcuts import model_to_dict
from playhouse.sqlite_ext import SqliteExtDatabase

db = SqliteExtDatabase('shoppr.db', pragmas={
    'journal_mode': 'wal',  # WAL-mode.
    'cache_size': -64 * 1000,  # 64MB cache.
    'synchronous': 0})


class Task(Model):
    title = TextField()
    description = TextField()
    createdAt = DateTimeField(default=datetime.datetime.now)
    changedAt = DateTimeField(default=datetime.datetime.now)
    isDone = BooleanField(default=False)

    class Meta:
        database = db


db.connect()
db.create_tables([Task])
```

**Comment by PhilippCh** [comment]
Oh wow, thanks a lot... like I said, still getting used to python 😀
