### ISSUE TITLE
sql in record update

### ISSUE THREAD

**Issue by fruitoiz** [coleifer/peewee#2919]
Hello, please add the ability to use SQL when updating a record.
————————
Здравствуйте, добавьте пожалуйста возможность использовать SQL в обновлении записи.

Example:
`Stat.update(fn.SQL("loss+1")`

**Comment by coleifer** [comment]
Well you can already, though you need to specify which field is being updated:

```python
Stat.update(loss=SQL('loss + 1')).sql()
#  ('UPDATE "stat" SET "loss" = loss + 1', [])

# Even better:
Stat.update(losses=SQL('losses + ?', (1,))).sql()
# ('UPDATE "stat" SET "losses" = losses + ?', [1])
```

If you want full control then issue your query via `.execute_sql()`:

```python
db.execute_sql('update stat set loss=loss+?', (1,))
```

**Comment by coleifer** [comment]
Is there a reason specifying the field doesn't work? I'd like to better understand this requirement.

**Comment by coleifer** [comment]
Balance is presumably an integer field? It should be instead a DecimalField.

**Comment by coleifer** [comment]
Alternatively, you can tell Peewee not to apply the `IntegerField` conversion to the value:

```python
User.update(balance=User.balance * Value(1.01, False)).where(User.id == 1)
# UPDATE "user" SET "balance" = ("user"."balance" * 1.01) WHERE ("user"."id" = 1)
```
