### ISSUE TITLE
Add YugabyteDB to the README. It works since YugabyteDB is postgreSQL compatible.

### ISSUE THREAD

**Issue by shreyas-agnihotri** [coleifer/peewee#2928]
Thanks for your work on peewee!

Can you please also add YugabyteDB to the README. It works since YugabyteDB is postgreSQL compatible.

Cheers,
Shreyas

**Comment by coleifer** [comment]
There's no need to add it if it's compatible.

**Comment by shreyas-agnihotri** [comment]
@coleifer Would you consider adding it for better visibility? YugabyteDB is similar to CockroachDB which is also postgres compatible but listed separately.

**Comment by coleifer** [comment]
It seems you have a connection to yugabyte but did not mention it for some reason.

**Comment by shreyas-agnihotri** [comment]
@coleifer Yes, I work for YugabyteDB. My intention was to get YugabyteDB also listed so that it benefits our customers looking for a simple ORM.

**Comment by coleifer** [comment]
![1571061139012](https://github.com/user-attachments/assets/d2cbebdd-1efb-467c-bfd1-3556cce7dcb7)
