### ISSUE TITLE
Multiple columns from a single field

### ISSUE THREAD

**Issue by TomGlass** [coleifer/peewee#2934]
Hello,

Bit of a question/query more so than an issue.

So I've got a use case where a DateField and a DateTimeField is needed and I'm attempting to do a insert_many from a dict (JSON imported from a web source)

So DateField allows me to submit a DateTime object as per the docs. I'm wondering if I can create 2 columns/fields identifiable as one to prevent me having to handle all the data to duplicate the item in the dict.

Strange but was curious if this could be achieved or you feel it's a good idea.

**Comment by coleifer** [comment]
If the two fields are identical expect that one version is a date and one is a date-time, it seems odd to handle this at the schema level by storing them separately. I would personally store the date-time and just convert it to a date whenever I needed it in that format.

But to your question, no there's no magic one field -> two fields thing.
