### ISSUE TITLE
FastAPI deprecated their peewee docs

### ISSUE THREAD

**Issue by dlfelps** [coleifer/peewee#2940]
The [link ](https://fastapi.tiangolo.com/advanced/sql-databases-peewee/) you provide to the FastAPI site was deprecated. Please update [database.rst#fastapi](https://github.com/coleifer/peewee/blob/master/docs/peewee/database.rst#fastapi) and host the missing content if possible.

**Comment by coleifer** [comment]
Thanks for the heads-up, gone ahead and removed it.
