### ISSUE TITLE
db.connect: True, db.is_closed: False, but 'Error, database connection not opened' occurs

### ISSUE THREAD

**Issue by ytyt-lead** [coleifer/peewee#2942]
Peewee reports that the connection to the database is not opened, although the `connect` and `is_closed` methods indicate otherwise.

> All code below was executed in the PyCharm console, in synchronous single-threaded mode.

```python
>>> from playhouse.db_url import connect

>>> db_url = 'postgresql+pool://user:password@localhost/db'
>>> db = connect(db_url, autoconnect=False)

# Check that the connection is established.
>>> db.connect()
True
>>> db.is_closed()
False

# Try to execute the request.
>>> 
try:
    db.create_tables([Tariff])
except Exception as e:
    print(e)

# Error text
'Error, database connection not opened.'

# Check that the connection is established.
>>> db.is_closed()
False
```

I also tried using the context manager (`with db`), the result is the same.

**Comment by coleifer** [comment]
I think it must have something to do with PyCharm but can't be sure. All the code works perfectly fine for me and is also covered by unit tests.
