### ISSUE TITLE
Table's with a column called "model" breaks aliasing

### ISSUE THREAD

**Issue by dhorkel** [coleifer/peewee#2947]
Apologies for creating two issues in a row but I think this one is an actual bug.

It appears that having a column called "model" breaks querying from an alias

Minimal example:

```
# Table that can't be prefetched
class A(Model):
    id = AutoField()
    model = TextField(null=True)

# Table that is OK
class B(Model):
    id = AutoField()
    not_model= TextField(null=True)

db.bind([A, B])

db.create_tables([A, B])

a = A.alias('a')
b = B.alias('b')
```

Querying B is fine: (query logging turned on)
```
>>> list(b.select())
('SELECT "b"."id", "b"."not_model" FROM "b" AS "b"', [])
[]
```

But querying A is not:
```
>>> list(a.select())
('SELECT "a"."id", "t1"."id", "t1"."model" FROM "a" AS "a"', [])
ProgrammingError: missing FROM-clause entry for table "t1"
LINE 1: SELECT "a"."id", "t1"."id", "t1"."model" FROM "a" AS "a"
```

I can see why this would be an issue as `aliased_table.model` typically points to the underlying model but I'm not sure the best way to work around this for an existing table.

**Comment by coleifer** [comment]
When this kind of thing occurs you will want to use a new attribute name and then explicitly specify the underlying column, e.g.:

```
class A(Model):
    id = AutoField()
    model_ = TextField(null=True, column_name='model')  
```
