### ISSUE TITLE
Questions regarding proper usage of PooledSqliteDatabase in multi-threaded GUI app use check_same_thread=True

### ISSUE THREAD

**Issue by devops-dmdx** [coleifer/peewee#2949]
Hi,

I am facing an issue with peewee's PooledDatabase in a multi-threaded GUI application. Either I am not using the library correctly or maybe there an uncovered topic here.

### Awareness 

Reading the documentation, I found:

> The pool module contains a number of [Database](https://docs.peewee-orm.com/en/latest/peewee/api.html#Database) classes that provide connection pooling for PostgreSQL, MySQL and SQLite databases. The pool works by overriding the methods on the [Database](https://docs.peewee-orm.com/en/latest/peewee/api.html#Database) class that open and close connections to the backend. The pool can specify a timeout after which connections are recycled, as well as an upper bound on the number of open connections.
>
> In a multi-threaded application, up to max_connections will be opened. Each thread (or, if using gevent, greenlet) will have its own connection.
>
> In a single-threaded application, only one connection will be created. It will be continually recycled until either it exceeds the stale timeout or is closed explicitly (using .manual_close()).
>
>By default, all your application needs to do is ensure that connections are closed when you are finished with them, and they will be returned to the pool. For web applications, this typically means that at the beginning of a request, you will open a connection, and when you return a response, you will close the connection.

https://docs.peewee-orm.com/en/latest/peewee/database.html#connection-pooling

And about thread safety:

> Peewee keeps track of the connection state using thread-local storage, making the Peewee [Database](https://docs.peewee-orm.com/en/latest/peewee/api.html#Database) object safe to use with multiple threads. Each thread will have it’s own connection, and as a result any given thread will only have a single connection open at a given time.

https://docs.peewee-orm.com/en/latest/peewee/database.html#thread-safety

### Usage

```pyhton
from playhouse.pool import _PooledSqliteDatabase
from playhouse.sqlite_ext import SqliteExtDatabase
from playhouse.sqlcipher_ext import _SqlCipherDatabase


class Database(_PooledSqliteDatabase, _SqlCipherDatabase, SqliteExtDatabase):
    pass


db = Database(
    None,
    autoconnect=False,  # Application shall handle connections explicitly.
    pragmas=(  # https://sqlite.org/pragma.html.
        ('cache_size', -1024 * 32),  # 32MB page-cache.
        ('journal_mode', 'wal'),  # WAL-mode allows readers and writers to co-exist.
        ('foreign_keys', 1),  # Enforce FOREIGN KEY constraints.
        ('ignore_check_constraints', 0),  # Enforce CHECK constraints.
        ('synchronous', 1),  # WAL mode is safe from corruption with NORMAL (1).
    ),
)

def get() -> Database:
    return db

def initialize(filepath: str, passphrase: str):
    db.set_passphrase(passphrase)
    db.init(filepath)
    atexit.register(db.close_all)

    with db.connection_context():
        with db.atomic():
            db.create_tables(models)
```

Given these instructions, and the methods above, here is how we use peewee:

* All connections are managed explicitly with `db.connection_context` context managers encapsulating all queries (eventually with a transaction context manager inside of necessary FYI).
* In most cases the main thread will indeed reuse the same underlying dbapi2 connection thanks to the pool mechanism
* But in cases were the  `db.connection_context`  and subsequent queries occur in another thread (to not freeze the GUI), the following `ProgrammingError` occurs: 
```
Traceback (most recent call last):
  File "venv\lib\site-packages\peewee.py", line 3327, in execute_sql
    cursor = self.cursor()
  File "venv\lib\site-packages\peewee.py", line 3320, in cursor
    return self._state.conn.cursor()
sqlcipher3.dbapi2.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12532 and this is thread id 18348.
```

### Investigations 

After a couple hours nagivating into the code source, I do not understant how peewee handles the per-thread connection. I have seen the `ConnectionLocal` class that inherits `threading.local`. This looks OK. But then due to we the pooled class `_connect()` call, an existing `dbapi2.Connection` is returned from the pool and then the ProgrammingError occurs.

Here are some logs added to the source code to keep track of the dbapi2 connection and the database state objects:

```
2024-11-05T11:12:33+0100 904 DEBUG  12532 <redacted>] Loading database database.db
CONNECT <peewee._ConnectionLocal object at 0x0000021EA7973BE0> True None
2024-11-05T11:12:33+0100 905 DEBUG  12532 peewee.pool:151] No connection available in pool.
2024-11-05T11:12:34+0100 091 DEBUG  12532 peewee.pool:180] Created new connection 2330650520624.
CONNECT RETURN <peewee._ConnectionLocal object at 0x0000021EA7973BE0> False <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
...
CONNECT <peewee._ConnectionLocal object at 0x0000021EA7973BE0> True None
CONNECT RETURN <peewee._ConnectionLocal object at 0x0000021EA7973BE0> False <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
2024-11-05T11:12:40+0100 318 DEBUG  12532 peewee:3325] ('SELECT <redacted> FROM "table" AS "t1"') 
CONNECTION <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
CLOSE <peewee._ConnectionLocal object at 0x0000021EA7973BE0> False <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
2024-11-05T11:12:40+0100 320 DEBUG  12532 peewee.pool:208] Returning 2330650520624 to pool.
CLOSE RETURN <peewee._ConnectionLocal object at 0x0000021EA7973BE0> True None
2024-11-05T11:12:40+0100 322 INFO  18348 <redacted>] Running in thread ID 18348, fetching database...
CONNECT <peewee._ConnectionLocal object at 0x0000021EA7973BE0> True None
CONNECT RETURN <peewee._ConnectionLocal object at 0x0000021EA7973BE0> False <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
2024-11-05T11:12:40+0100 324 DEBUG  18348 peewee:3325] ('SELECT <redacted> FROM "table" AS "t1")
CONNECTION <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
CLOSE <peewee._ConnectionLocal object at 0x0000021EA7973BE0> False <sqlcipher3.dbapi2.Connection object at 0x0000021EA598AC30>
2024-11-05T11:12:40+0100 324 DEBUG  18348 peewee.pool:212] Closed 2330650520624.
CLOSE RETURN <peewee._ConnectionLocal object at 0x0000021EA7973BE0> True None

Traceback (most recent call last):
  File "venv\lib\site-packages\peewee.py", line 3327, in execute_sql
    cursor = self.cursor()
  File "venv\lib\site-packages\peewee.py", line 3320, in cursor
    return self._state.conn.cursor()
sqlcipher3.dbapi2.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12532 and this is thread id 18348.
```

With prints added to `peewee.py`: 

```python
    def connect(self, reuse_if_open=False):
        with self._lock:
            print('CONNECT', self._state, self._state.closed, self._state.conn)
            if self.deferred:
                raise InterfaceError('Error, database must be initialized '
                                     'before opening a connection.')
            if not self._state.closed:
                if reuse_if_open:
                    return False
                raise OperationalError('Connection already opened.')

            self._state.reset()
            with __exception_wrapper__:
                self._state.set_connection(self._connect())
                if self.server_version is None:
                    self._set_server_version(self._state.conn)
                self._initialize_connection(self._state.conn)
        print('CONNECT RETURN', self._state, self._state.closed, self._state.conn)
        return True

    def close(self):
        with self._lock:
            print('CLOSE', self._state, self._state.closed, self._state.conn)
            if self.deferred:
                raise InterfaceError('Error, database must be initialized '
                                     'before opening a connection.')
            if self.in_transaction():
                raise OperationalError('Attempting to close database while '
                                       'transaction is open.')
            is_open = not self._state.closed
            try:
                if is_open:
                    with __exception_wrapper__:
                        self._close(self._state.conn)
            finally:
                self._state.reset()
            print('CLOSE RETURN', self._state, self._state.closed, self._state.conn)
            return is_open
```

### Conclusion

AFAI observe, the `self._state` looks correct according to prints, but with the call to `self._connect()` here `self._state.set_connection(self._connect())`, the pool returns an active connection that was opened from another thread. 

Obviously, if I remove the `PooledDatabase` inheritance, then everything behaves as expected but my GUI feels less reactive due to the underlying `dbapi connect / close` calls in each connection context.

Again, if i use `check_same_thread=False` it all works, but I'd rather not to even if using the journal WAL mode.

I can eventually circumvent the scenario by not using the PooledDatabase and not closing database connections in each connection context, but I'd rather not. I like the explicit context manager around all interactions with the DB.

This will make the usage falls into the aforementioned 'about thread safety' in docs, with a single Database object, managing one connection per thread.

But according to the documentation, our usage shall also work, right? 

> In a multi-threaded application, up to max_connections will be opened. Each thread (or, if using gevent, greenlet) will have its own connection.

This is not the case _a priori_ since the underlying connection is shared between different threads as you can see in logs above.

Thanks a lot for your guidance and help about this, i reckon, esoteric usage.

Best,
Hugo

**Comment by devops-dmdx** [comment]
Our _ideal_ usage being:

* Manage every Database connection explicitly with context managers
* But benefit from a pool to reuse connections and avoid delays in connect/close because of the ciphered nature of the underlying SQLite DB. 
* But also have the pool be aware of the thread the connection was created in to avoid the ProgrammingError and avoid sharing objects between threads by default

Perhaps, this logic is wrong and not an intended usage of peewee... In that case, what do you suggest?

**Comment by coleifer** [comment]
There is a check inside the sqlite3 driver used with Python -- you need to disable that if you are really sure you want to share connections across threads. This is how you would modify your code:

```
db = Database(
    None,
    autoconnect=False,  # Application shall handle connections explicitly.
    check_same_thread=False,  # ADD THIS LINE.
    pragmas=(  # https://sqlite.org/pragma.html.
        ('cache_size', -1024 * 32),  # 32MB page-cache.
        ('journal_mode', 'wal'),  # WAL-mode allows readers and writers to co-exist.
        ('foreign_keys', 1),  # Enforce FOREIGN KEY constraints.
        ('ignore_check_constraints', 0),  # Enforce CHECK constraints.
        ('synchronous', 1),  # WAL mode is safe from corruption with NORMAL (1).
    ),
)
```

That should be all that is necessary.

**Comment by devops-dmdx** [comment]
Thanks for your swift reply. 

I am aware of `check_same_thread`, but I do not really want to share connections across threads. Instead, I'd rather like to have connections bound to the thread it was created in, managed by the connection pool; on the one side. And I'd like to benefit from the protection of using explicit peewee Database object connection used by bound models to avoid implicit connections that would spread all over the code base in the long term.

When reading the documentation:

> In a multi-threaded application, up to max_connections will be opened. Each thread (or, if using gevent, greenlet) will have its own connection.

This is the behavior I'd expect, no matter the `check_same_thread` value. So, IMO, the quoted sentence above is somewhat misleading if not erroneous: in the PooledDatabase scenario, each thread WILL NOT HAVE its own connection. A previously opened connection (eventually opened by another thread) can be reused (i.e. picked from the pool).

**Comment by coleifer** [comment]
>but I do not really want to share connections across threads

This is the whole point of the pool, really. It allows a set of connections to be checked-out by a thread, then returned to the pool, at which point any other thread can check it out.

I think you're expecting the pool to track some sort of "thread affinity" but it does no such thing. It simply means that when a thread checks out a connection, all database accesses in that thread will go through the self-same connection.

If you want a connection-per-thread (e.g. you don't want connections to share threads) then you shouldn't be using the pool at all. Just use the regular database class and connect at thread startup and close at thread exit - no need at all for a connection pool.

**Comment by devops-dmdx** [comment]
I feel like I'm a bit insistant on this topic, but I really want to understand my options there and benefit from your expertise.

Indeed you're right on that side. There is no need at all for a connection pool to have a "thread affinity". 

Though, one side-effect of using a PooledDatabase object coupled with `autoconnect=False` I appreciate, is that the underlying Database is _closed_ from the Models point of view. Meaning that without a scoped `connection_context()` the Models' queries will fail because the connection is not checked-out from the pool. Am i right?

That being said, if I want best of both worlds, I guess I'll have to define some sort of ThreadAffinityDatabase that stores one underlying `dbapi2` connection per thread and that could be checked-out explicitly just has the PooledDatabase does.

**Comment by coleifer** [comment]
Since you're using Sqlite there's no downside to just keeping the connections open all the time *or* writing your own middleware that prevents queries from being executed outside of a scoped block (which seems to be the only thing you gain by using the pool in your scenario).

For sqlite the important thing is to execute your queries that write to the database in an explicit transaction using `db.atomic()` - this ensures that the write lock is only held for a very brief time and prevents `SQLITE_BUSY` / database is locked errors.

If you do choose to, you can of course write a database subclass that maps the thread id -> a connection and have it behave like a pool. But this is sorta what Peewee already does by storing the underlying db-api connection in a thread-local. The only thing you're "gaining" is the ability to make the DB appear closed until explicitly opened.

**Comment by devops-dmdx** [comment]
Thank you very much for your insights 👍
