### ISSUE TITLE
Redundant Select Query when data is not present - Continuation of #2871

### ISSUE THREAD

**Issue by Nivinr21** [coleifer/peewee#2950]
Facing same behaviour issue of https://github.com/coleifer/peewee/issues/2871 in 3.17.3 and above as well. The fix done for **BaseQuery** class has to be implemented for **BaseModelSelect** class as well.

Issue Reference:

class BaseModelSelect(_ModelQueryHelper):
    ...
    **def __iter__(self):
        if not self._cursor_wrapper: 
            self.execute()
        return iter(self._cursor_wrapper)**
    ...

Fix Reference: 3.17.3 - https://github.com/coleifer/peewee/commit/ec87d30b7298ab7eca2f14160a583509d17e783f#diff-67411bae22210c70f06f76a88cefd7b450894a6dec5977de8ba2a960d95a14b4L2098-R2098

**Comment by coleifer** [comment]
@Nivinr21 - I'm not seeing this myself, can you help me understand with a testcase? Here is the test-case:

```python
class TestQueryCountList(ModelTestCase):                                                 
    requires = [User]                                                                    
                                                                                         
    def test_iteration_single_query(self):
        with self.assertQueryCount(1):                                                   
            sq = User.select()                                                           
            for i in range(3):                                                           
                self.assertEqual(list(sq), [])
                self.assertFalse(bool(sq))  
```

This is what I see when I turn on the query logging:

```
('CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER NOT NULL PRIMARY KEY, "username" VARCHAR(255) NOT NULL)', [])
('SELECT "t1"."id", "t1"."username" FROM "users" AS "t1"', [])
('DROP TABLE IF EXISTS "users"', [])
```

**Comment by coleifer** [comment]
Will reopen with a test-case that indicates the issue.

**Comment by Nivinr21** [comment]
@coleifer Can you try accessing the query result with tuples() and check once ? My understanding is that, while accessing the list(query.dicts()) or list(query.tuples()), the **BaseModelSelect** class **iter** method is invoked and the cursor check is not enough to skip the query execute method for no data scenarios.


Minor Tweaked test case:

`
class TestQueryCountList(ModelTestCase):                                                 
    requires = [User]                                                                    
                                                                                         
    def test_iteration_single_query(self):
        with self.assertQueryCount(1):                                                   
            sq = User.select()                                                           
            for i in range(3):                                                           
                self.assertEqual(list(sq.tuples()), [])
                self.assertFalse(bool(sq))  
`

<img width="943" alt="Screenshot 2024-11-09 at 9 06 20 PM" src="https://github.com/user-attachments/assets/077480e5-7a28-4631-9587-45c526e8894c">

**Comment by coleifer** [comment]
Thx will investigate!

**Comment by coleifer** [comment]
```python
def test_iteration_single_query(self):
    with self.assertQueryCount(1):                                                   
        sq = User.select()                                                           
        for i in range(3):                                                           
            self.assertEqual(list(sq.tuples()), [])
            self.assertFalse(bool(sq))  
```

This is the code you shared -- this is actually not a bug. When you call `.tuples()` it effectively clones the query. For example, the following is passing:

```python
        with self.assertQueryCount(1):
            sq = User.select().tuples()
            for i in range(3):
                self.assertEqual(list(sq), [])
                self.assertFalse(bool(sq))
```

**Comment by Nivinr21** [comment]
@coleifer I tried your suggestion by moving tuples() next to select() and it removed one extra redundant query but still the query is getting re-executed. Sharing the code trace on how its happening

`query = Table1.select(Table1.col1, Table1.col2, peewee.fn.count(Table2.id)).tuples().order_by(Table1.col1.asc()).group_by(Table1.id)
return list(query)

------ Query Execution 1 Trace ------

<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2119 in **__len__**>, 
<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2101 in **_ensure_execution**>, 
<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2018 in inner>, 
<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2089 in **execute**>


------ Query Execution 2 Trace ------

<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 7256 in **__iter__**>, 
<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2018 in inner>, 
<FrameSummary file /Users/test-user/.pyenv/versions/3.9.16/envs/test-venv/lib/python3.9/site-packages/peewee.py, line 2089 in **execute**>, 

------`

As mentioned before the **BaseModelSelect**'s **__iter__** method is not checking the cursor correctly which leads to re-execution.

**Comment by coleifer** [comment]
I simply do not see this and have asked you to provide me a test-case that demonstrates the issue. Here is a script that does what your code is doing -- note that the query is only executed once.

```python
from peewee import *

db = SqliteDatabase(':memory:')

class T(db.Model):
    a = TextField()

db.create_tables([T])
T.create(a='a1')
T.create(a='a2')

import logging
logger = logging.getLogger('peewee')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

query = T.select().tuples().order_by(T.id)
list(query)
list(query)
```

Output:

```
('SELECT "t1"."id", "t1"."a" FROM "t" AS "t1" ORDER BY "t1"."id"', [])
```

Only one query is executed.
