### ISSUE TITLE
Clarification on `_BaseFormattedField.formats`

### ISSUE THREAD

**Issue by frlryr** [coleifer/peewee#2953]
Here is a piece of code I have:

````python
class BaseModel(Model):
    gid: UUID = UUIDField(index=True, primary_key=True)

    # Record
    created: datetime = DateTimeField(
        default=datetime.now(timezone.utc), formats=datetime.isoformat
    )
````

There is no coercion or clarification that this field should be an iterable. So I ended up getting a...

```python
...
TypeError: 'method_descriptor' object is not iterable
...
````

...in line `5290 `, method `format_date_time`. After a bit of code diving I realized it required an iterable. I know plural is an awesome hint, but it wouldn't hurt to have a coercion + warning or a clarification in the documentation for that. It should be a cinch to implement that in Line `5306` or just add an extra explanation in the [Note:](https://docs.peewee-orm.com/en/latest/peewee/models.html#some-fields-take-special-parameters).

EDIT: I just realized it also doesn't accept functions when selecting, but it does when inserting. Not sure why.

**Comment by coleifer** [comment]
You're using this totally wrong bro. First of all, `formats` (plural, as you noted) accepts an iterable. Second of all, glancing at the code you would quickly see that `formats` is just a list of strings that are tried when parsing datetimes that have to be stored in text-form (e.g. sqlite).

This is, of course, documented as well: http://docs.peewee-orm.com/en/latest/peewee/api.html#DateTimeField
