### ISSUE TITLE
SchemaManager create_foreign_key fails on a FK field with the constraint_name provided explicitly.

### ISSUE THREAD

**Issue by recipe** [coleifer/peewee#2957]
It will produce the following SQL statement:
```sql
ALTER TABLE `table` ADD CONSTRAINT `fk_table_field_refs_parent` 
CONSTRAINT `fk_explicitly_provided_constraint_name` 
FOREIGN KEY (`field`) REFERENCES `parent` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```
It's because the `field.foreing_key_constraint()` is called [here](https://github.com/coleifer/peewee/blob/master/peewee.py#L6155-L6158). It returns the ```CONSTRAINT `fk_explicitly_provided_constraint_name` ``` literal, that is set [here](https://github.com/coleifer/peewee/blob/master/peewee.py#L5618-L5619).

**Comment by coleifer** [comment]
You are correct, thanks for reporting this long-standing bug!
