### ISSUE TITLE
Aliasing an arithmetic expression

### ISSUE THREAD

**Issue by martindemello** [coleifer/peewee#2958]
I'm trying to convert the following sql to peewee:

```
        select
           H.division_id,
           H.player_id,
           sum(wins) wins,
           count(*)-sum(wins) losses,
        from
           halfpairing H
        where
          H.division_id = ?
          and H.round_number <= ?
        group by
          H.division_id,
          H.player_id
        order by
          H.division_id,
          sum(H.wins) desc,
```

but I could not see how to convert the `count(*) - sum(wins) losses` to an object i could call `alias` on. A hypothetical example of what I am looking for is either `fn.difference(fn.count(H.player_id), fn.sum(H.wins))` (have function aliases for the operators) or `fn.expression(fn.count(H.player_id) - fn.sum(H.wins))` (have a generic "expression" function that wrapped an expression), but I couldn't see either one in the docs.

**Comment by coleifer** [comment]
```python

diff = fn.count(SQL('*')) - fn.sum(HalfPairing.wins)
query = ...select(..., diff.alias('losses'))

# Or:
query = ...select(
    ...
    (fn.COUNT(...) - fn.SUM(...)).alias('losses'),
)
```

We override subtract, so it "just works".

**Comment by martindemello** [comment]
perfect, and thanks for the quick response! i was very impressed to see zero open issues in the github tracker.

**Comment by coleifer** [comment]
I run a tight ship around here.
