### ISSUE TITLE
Auto-completion of attributes in __init__ and create()?

### ISSUE THREAD

**Issue by jat255** [coleifer/peewee#2960]
Is there any trick to allowing a tool like Intellisense to pick up on the allowed arguments when creating a new instance of a model?

I am pretty new to using peewee, and am working off of a set of models auto-generated by `pwiz`. For example, if I define a model:

```python
class User(Model):
    email = TextField(null=True)
    first_name = TextField()
    is_active = BooleanField(constraints=[SQL("DEFAULT true")])
    last_name = TextField()
    username = TextField(primary_key=True)

    class Meta:
        table_name = "users"
```

I don't get any autocompletion of the arguments `email`, `first_name`, etc. when writing `u = User(...)` or `u = User.create(...)` elsewhere in the code. The best I could come up with is by manually defining an `__init__()` such as:

```python
def __init__(self, email: str, first_name: str, is_active: bool, last_name: str, username: str, *args, **kwargs):
    super().__init__(
        email=email,
        first_name=first_name, 
        is_active=is_active,
        last_name=last_name,
        username=username,
        *args,
        **kwargs
    )
```

and similarly for `create()`, but I'm wondering if there's some way to not have to manually do this for every class/table.

Any thoughts?

**Comment by coleifer** [comment]
At present it's kinda up to whatever tool you're using to be able to autocomplete it, or to explicitly declare the `__init__`/etc methods with the signature you desire.
