### ISSUE TITLE
[Question] Adding validation to fields

### ISSUE THREAD

**Issue by rezemika** [coleifer/peewee#2962]
Hello! I hope you're doing well, thank you so much for developing Peewee!

This is a question, not a bug report.
I wondered it was planned / considered to add some validation mechanisms to Peewee, so it wouldn't be possible to add an invalid value to a field?

I think even a simple trick like that would be really convenient (the types could be implicit I guess):

```python
class User(BaseModel):
    username = peewee.CharField(unique=True, validators=[peewee.validators.Type(str), peewee.validators.MaxLength(20)])
    birth_date = peewee.DateField(validators=[peewee.validators.Type(datetime.date), peewee.validators.MaxValue(datetime.date.today())])

# So something like this could catch validation errors (to, i.e., display some explanations given by the validators):

try:
    user = User(username=1234, birth_date=datetime.date(2038, 1, 19))
except peewee.ValidationError as e:
    print(f"Validations errors: {e.reasons}")
```

I know there is [peewee-validates](https://github.com/timster/peewee-validates/) but it is unmaintained, and I think it would be really great and useful to have such mechanism natively in Peewee. Do you think it would be feasible / planned in the future? If so, I would be happy to create a bounty to support its development. :)

**Comment by coleifer** [comment]
Peewee isn't really in the business of validation -- typically that would be handled by whatever is accepting untrusted input and would have facilities for reporting errors and all that. There are lots of mature libraries in Python that will do this.
