### ISSUE TITLE
How to use order_by with alias field?

### ISSUE THREAD

**Issue by thibaultmeyer** [coleifer/peewee#319]
Hello,

we have 2 issues with the order_by function when we use it with aliased field.
1. How to use  ASC and DESC with aliased field ?
2. The SQL generated request :

``` python
lstTransaction = Transaction.select(Transaction.id, Transaction.vendor,
Transaction.amount, Transaction.client, fn.MIN(Transaction.date).alias("date")
.where(Transaction.vendor == 1).distinct().group_by(Transaction.client)
.order_by("date")
```

Output request:

``` sql
SELECT DISTINCT t1.`id`, t1.`vendor`, t1.`amount`, t1.`client`, 
MIN(t1.`date`) AS date FROM `transaction` AS t1 
GROUP BY t1.`matricule` ORDER BY 'date'
```

Rather than 

``` sql
SELECT DISTINCT t1.`id`, t1.`vendor`, t1.`amount`, t1.`client`, 
MIN(t1.`date`) AS date FROM `transaction` AS t1 
GROUP BY t1.`matricule` ORDER BY `date`
```

In MySQL  5.5.35, the request results is bad ordered with "date" but is well ordered with `date`.

**Comment by mikolasan** [comment]
For some reason I prefer the second option. But there is no need to repeat the same operation from the select block. That thing can be assigned to a local variable, and I think, that will make it readable almost like the resulting SQL query

```
date = fn.MIN(Transaction.date).alias("date")
Transaction.select(..., date, ...)
.where(...)
.order_by(date)
```

**Comment by Palsy49** [comment]
@coleifer 79907H9rSpZ1
