### ISSUE TITLE
How to do deferred engine selection?

### ISSUE THREAD

**Issue by arnuschky** [coleifer/peewee#365]
How can one do deferred engine selection?

For example, if I use a class similarly as `Database` of `flask-peewee`, I would like to select the engine/configure peewee after creation of the instance (ie, the commong `init_app()` approach). Unfortunately, all my models need to know their baseclass to reference the database. Is there any way around this? Can I change the database in the baseclass?

This is related to https://github.com/coleifer/flask-peewee/issues/69

**Comment by ralphmueller** [comment]
Link http://peewee.readthedocs.org/en/latest/peewee/cookbook.html#dynamically-defining-a-database doesn't exist anymore. Can you help?

**Comment by coleifer** [comment]
* http://docs.peewee-orm.com/en/latest/peewee/database.html#run-time-database-configuration
* http://docs.peewee-orm.com/en/latest/peewee/database.html#dynamically-defining-a-database

**Comment by ralphmueller** [comment]
Thank you,

works very well!
Regards / Liebe Grüße,

Ralph Mueller

Annastrasse 44, 64673 Zwingenberg
Mobile: +49 177 449 0460
Office: +49 6251 789545
email: ralph.mueller.de@gmail.com <mailto:ralph.mueller.de@gmail.com>
https://www.ralph-mueller.net <https://www.ralph-mueller.net/>
