### ISSUE TITLE
sql_error_handler not called

### ISSUE THREAD

**Issue by tfeldmann** [coleifer/peewee#410]
Hi! After connecting to a mysql database and waiting for a long time (>8h) subsequent database calls fail with a "2006 MySQL has gone away". To work around this problem I want to implement a "ReconnectingMySQLDatabase" that reconnects if this exception is detected. 
For testing purposes I created the BaseModel tables and called `BaseModel.create()` several times (works), then shut down the database and called create() again. I expected the sql_error_handler to be called but it wasn't. [See the logfile](http://pastebin.com/x4zBuRgh)

``` python
import datetime
from peewee import *


class ReconnectingMySQLDatabase(MySQLDatabase):

    def sql_error_handler(self, exception, sql, params, require_commit):
        # I just want to print the arguments...
        print(exception, sql, params, require_commit)


database = ReconnectingMySQLDatabase(
    host='host',
    user='user',
    passwd='pass',
    database='name',
    threadlocals=True,
)


class BaseModel(Model):
    created = DateTimeField(index=True, default=datetime.datetime.now)
    modified = DateTimeField(index=True)

    class Meta:
        database = database

    def save(self, *args, **kwargs):
        self.modified = datetime.datetime.now()
        return super().save(*args, **kwargs)
```

Is there a better way to do this?

**Comment by havannavar** [comment]
I have the below connection and using the Pooled database as shown below.
           DATABASE = {
                'name': 'testdb',
                 'engine': 'playhouse.pool.PooledPostgresqlExtDatabase',
                 'register_hstore': False,
                  'user': 'test',
                  'host':'localhost',
                  'password':'test',
                  'port':5432,
                  'max_connections': 100,
                  'stale_timeout': 6000,
           }
Still i m facing the same the error 
"OpenSSL error of the type “decryption failed or bad record mac”?

Is there other way to solve this issue?

**Comment by coleifer** [comment]
Upgrade your openssl. Also that is not even remotely related to peewee or
this ticket. Go away.
