### ISSUE TITLE
Database.drop_tables hide warning when a table doesn't exist

### ISSUE THREAD

**Issue by rvindas-gap** [coleifer/peewee#416]
Just ugraded to version 2.3.0 and I was trying the `drop_tables` function. If a table doesn't exist then I get a warning like the following (even specifying the `safe=True` parameter)

```
/mypathto/env/site-packages/peewee.py:2702: Warning: Unknown table 'variables' cursor.execute(sql, params or ())
/mypathto/env/site-packages/peewee.py:2702: Warning: Unknown table 'companies' cursor.execute(sql, params or ())
/mypathto/env/site-packages/peewee.py:2702: Warning: Unknown table 'users' cursor.execute(sql, params or ())
```

Is there a way to turn off the warnings when trying to drop a table that doesn't exist and when specifying the `safe=True` parameter?

**Comment by esel7353** [comment]
I have the same problem. Simply ignoring the warnings is not a solution, because the warnings interfere with my regular command line user interface and would make the user interface quite ugly.
