### ISSUE TITLE
“exc_value.args” at line 2591 may caused the error " AttributeError: 'str' object has no attribute 'args' " sometime

### ISSUE THREAD

**Issue by JoneXiong** [coleifer/peewee#418]
eg:
if  you haven't seted "check_same_thread=False" may lead to:
  exc_value = “SQLite objects created in a thread can only be used in that same thread.The object was created in thread id.....”
and then: 
    reraise(new_type, new_type(*exc_value.args), traceback)
AttributeError: 'str' object has no attribute 'args'

**Comment by jet9** [comment]
It seems like MySQLdb python module affects on `exc_value` behavior. Workaround: use PyMySQL module instead.
