### ISSUE TITLE
Iterating over big dataset

### ISSUE THREAD

**Issue by demongoo** [coleifer/peewee#431]
I try to iterate result set:

```
for field1, field2 in query.tuples().iterator():
    print .... 
```

But it failes with 'out of memory' (script just gets killed by kernel), so, I see no difference in my case - either with iterator or without.

I have there python 2.6 and peewee 2.3.2.

I'm not familiar much with lazy loading in python, except generators, but how this supposed to work: https://github.com/coleifer/peewee/blob/master/peewee.py#L2439  ? In `execute` `self._qr` gets constructed anyway - so how can this save memory to allow coping with big dataset? Is it me missing something, or maybe obsolete python version or ...?

**Comment by est** [comment]
> You'll have to look into the implementation of the python driver 

By looking up the pymysql driver, is it possible to use the `fetchall_unbuffered()` when iterating large results?


https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor.fetchall_unbuffered
