### ISSUE TITLE
Foreign keys that do not end with "_id"

### ISSUE THREAD

**Issue by karlb** [coleifer/peewee#44]
There seems to be no way to declare a foreign_key which does not end with "_id", since the expected column name is attribute_name + '_id'. Or did I miss way to declare such a key?

**Comment by dcrystalj** [comment]
would be nice to add ```db_column ``` in api docs

**Comment by coleifer** [comment]
It is: http://docs.peewee-orm.com/en/latest/peewee/api.html#fields

And: http://docs.peewee-orm.com/en/latest/peewee/models.html#field-initialization-arguments
