### ISSUE TITLE
How to use functions like POSTGRES EXTRACT(YEAR FROM table.field)

### ISSUE THREAD

**Issue by demongoo** [coleifer/peewee#455]
This thing still doesn't let me sleep tight.
Can I somehow write the select field like:

```
EXTRACT(EPOCH FROM field)
```

Now I'm using `(fn.EXTRACT(SQL("EPOCH FROM \"t5\".\"ts\"")) * 1000).alias('session_id')` and the worst part is "t5". Is there any other solution? Or maybe some ideas how to let such constructions to be written?

**Comment by from-nibly** [comment]
For future reference it looks like you want to use `NodeList` now instead of Clause

**Comment by coleifer** [comment]
This is built-in to the database object as of Peewee 3. You can use `db.extract_date('epoch', M.field)`.
