### ISSUE TITLE
Database connection not refreshed after wait_timeout

### ISSUE THREAD

**Issue by arunisaac** [coleifer/peewee#489]
I'm using peewee with a MySQL database with pymysql being the database driver. The wait_timeout of my mysql database is set to the default value of 8 hours.

When my application remains idle for 8 hours, the database connection times out, and any further requests throw MySQL errors 2013 (Lost connection to MySQL server during query) and 2006 (MySQL server has gone away). Similar behaviour also happens with PooledMySQLDatabase connections.

Is this behaviour normal? Should I do something to make peewee to reconnect timed out connections, or is pymysql supposed to take care of this?

**Comment by rfyiamcool** [comment]
good idea
