### ISSUE TITLE
Add jsonb field support for postgres

### ISSUE THREAD

**Issue by extesy** [coleifer/peewee#496]
PostgreSQL 9.4 now supports binary json field (jsonb), the documentation is here: http://www.postgresql.org/docs/9.4/static/datatype-json.html

**Comment by coleifer** [comment]
Yes! I'm very interested in adding this. I currently have 9.3.5 installed so I'll need to get 9.4 running in order to start working on this.

**Comment by coleifer** [comment]
0f48020cf2604966aa77dcd57044b738cc7f44de

**Comment by coleifer** [comment]
I've made a start at implementing this. I'll put together some docs shortly.

**Comment by extesy** [comment]
:thumbsup:

**Comment by wishabhilash** [comment]
Any update on this issue @coleifer ???

**Comment by coleifer** [comment]
Support was merged in.
