### ISSUE TITLE
Custom field not getting parsed using alias

### ISSUE THREAD

**Issue by BusyJay** [coleifer/peewee#498]
Hi, I have a custom field definition like:

    class CustomField(peewee.Field):
        def coerce(self, value):
            return "parsed"

    class A(peewee.Model):
        f = CustomField()

When I parse custom value to Models directly, it works fine.

    >>> A.select().where(A.f == 20)
    <class '__main__.A'> SELECT "t1"."id", "t1"."f" FROM "a" AS t1 WHERE ("t1"."f" = ?) ['parsed']

But, when I use alias, it won't parse the value for me.

    >>> a = A.alias()
    >>> A.select().join(a, on=(A.f == a.f)).where(a.f == 20)
    <class '__main__.A'> SELECT "t1"."id", "t1"."f" FROM "a" AS t1 INNER JOIN "a" AS t2 ON ("t1"."f" = "t2"."f") WHERE ("t2"."f" = ?) [20]

What I am expecting is:

    <class '__main__.A'> SELECT "t1"."id", "t1"."f" FROM "a" AS t1 INNER JOIN "a" AS t2 ON ("t1"."f" = "t2"."f") WHERE ("t2"."f" = ?) ['parsed']

**Comment by BusyJay** [comment]
When will be next release?

**Comment by coleifer** [comment]
I'll create one soon.
