### ISSUE TITLE
pylint doesn't see some peewee Model fields

### ISSUE THREAD

**Issue by richey-v** [coleifer/peewee#499]
I'm using peewee with Flask.

I have an existing MySQL database and used pwiz to generate a decent model of it.  Functionally, everything is working fine, but pylint still complains about a Model field being not detected.

Here is the SQL:
```SQL
CREATE TABLE name_instance (
    id                    INT   NOT NULL AUTO_INCREMENT,
    name_id               INT   NOT NULL,
    alias_id              INT   UNIQUE,
    PRIMARY KEY (id),
    FOREIGN KEY (name_id)   REFERENCES name_variation (id)  ON DELETE CASCADE,
    FOREIGN KEY (alias_id)  REFERENCES name_variation (id)  ON DELETE CASCADE
);
```

Here is the pwiz-generated class:
```python
class NameInstance(BaseModel):
    alias = ForeignKeyField(db_column='alias_id',
                            null=True,
                            rel_model=NameVariation,
                            related_name='aliases',
                            to_field='id',
                            unique=True)
    name = ForeignKeyField(db_column='name_id',
                           rel_model=NameVariation,
                           related_name='names',
                           to_field='id')

    class Meta:
        db_table = 'name_instance'
```

In Flask code, I can do this without pylint complaining:
```python
   NameInstance.get(NameInstance.name == name_inst_id)
```
but pylint complains about "id" not defined in the following line:
```python
   NameInstance.get(NameInstance.id == name_inst_id
```

**Comment by coleifer** [comment]
Can you please format your issue? You can edit it and apply markdown style.

**Comment by coleifer** [comment]
If a model has an auto-increment integer primary key named `id`, the convention is to omit defining it explicitly. This convention comes from Django and I like it. If you want to fix it, just add this field definition to your models:

```python
id = PrimaryKeyField()
```

Also I see in your schema the foreign keys are `NOT NULL` but in peewee they are marked `null=True` -- you might want to remove that.
