### ISSUE TITLE
error with DateTimeField

### ISSUE THREAD

**Issue by daufinsyd** [coleifer/peewee#500]
Hello,
I can't filter objects from with DateTimeField (with Sqlite), it always return

> File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 2825, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: user-defined function raised exception

I have something like this:
>class A(Model):
    dateA = DateTimeField()
def Function(self):
    for a in (A.select().where(A.dateA.year == 2015)):
>        print('smthg')

but if I use
>    for a in (A.select().where(A.dateA == datetime.datime.now()):

It works

and
>print(A.select().where(A.dateA.year == 2015).count())
raise the same error.

i use sqlite and connect the db with:

>db = SqliteDatabase('db.sqlite')
def connectDb():
    db.connect()
    db.create_tables([A], true)

type:
>a = A.get(id=1)
type(a.dateA)
\<class str\>

I didn't found any solution over Internet, do you have any idea ?
Thank you

**Comment by coleifer** [comment]
What do the dates in your table look like? Can you show me some examples?

**Comment by daufinsyd** [comment]
it's
15/01/2015 22:15

**Comment by coleifer** [comment]
OK, that's the problem. You'll need to subclass `DateTimeField` and specify the `formats` parameter, e.g.

```python
class CustomDateTimeField(DateTimeField):
    formats = ['%m/%d/%Y %H:%M'] + DateTimeField.formats
```
