### ISSUE TITLE
Constraints not created by db.create_table(Class1), yes by db.create_tables([Class1])

### ISSUE THREAD

**Issue by chrisinmtown** [coleifer/peewee#504]
In peewee 2.4.5 my tests show that methods create_table() and create_tables() differ in creation of uniqueness constraints. If I use db.create_table(Class1) then my request for uniqueness constraints is silently ignored. If I use db.create_tables([Class1]) then the constraints are created as expected.  

I'm using MySQL 5.5, connector is PyMySQL 0.6.3.  The model below is directly from the documentation; mine is very similar. 

    class Transaction(Model):
        from_acct = CharField()
        to_acct = CharField()
        amount = DecimalField()
        date = DateTimeField()

        class Meta:
            indexes = (
                # create a unique on from/to/date
                (('from_acct', 'to_acct', 'date'), True),

                # create a non-unique on from/to
                (('from_acct', 'to_acct'), False),
            )

I expect a clause in the table definition something like this (sorry this is typed not pasted):

    UNIQUE KEY `from_acct_to_acct_date` (`from_acct`,`to_acct`,`date`)

I was put on the trail by issue https://github.com/coleifer/peewee/issues/211.  This is quite a subtle difference!  Please harmonize. Thanks for listening and for a very, very useful package.

**Comment by coleifer** [comment]
The `db.create_table()` method will only create the table, not any of the indexes or constraints. To create a table for a model along with constraints, use ``ModelClass.create_table()`` or if creating multiple tables, ``db.create_tables()``. I understand this is confusing and will update the docs to clarify the difference.

**Comment by chrisinmtown** [comment]
I thank you for updating the documentation. Forgive my grumbling, but my programmer's heart is saddened by enshrining in code & doc different behaviors for functions that at first glance seem to be nearly identical, just one works on a single argument and the other on a list of arguments.

**Comment by coleifer** [comment]
There are historical reasons for this, but I do agree that it can be confusing. The documentation examples all should be showing either `Model.create_table()` or `Database.create_tables()`.
