### ISSUE TITLE
Duplicate field names after stripping '_id' suffix

### ISSUE THREAD

**Issue by teeberg** [coleifer/peewee#510]
For reasons that are beyond me, I'm working on a database that often has fields which have the same name except for the `_id` part at the end, that is one called e.g. `language` and one `language_id`. Generating models for this table using pwiz gives me model definitions like:

    language = CharField()
    language = IntegerField(db_column='language_id')

Other than that, amazing how little tweaking I had to do! Thank you for the awesome ORM!

**Comment by teeberg** [comment]
That was an awesome response time! :-) Thanks so much!

**Comment by coleifer** [comment]
NP! I really appreciate the bug report.
