### ISSUE TITLE
JDBC support

### ISSUE THREAD

**Issue by SamuelMarks** [coleifer/peewee#518]
Has anyone tried using peewee with JDBC, e.g.: using [this wrapper](https://pypi.python.org/pypi/JayDeBeApi/) ([code](http://bazaar.launchpad.net/~baztian/jaydebeapi/trunk/view/head:/src/jaydebeapi/dbapi2.py)) which exposes DB-API v2.0 support?

**Comment by coleifer** [comment]
This type of discussion might be more suited for the discussion group: groups.google.com/group/peewee-orm
