### ISSUE TITLE
[Question] Is there a way to get the display instead of the value for a field with a choices parameter associated with it?

### ISSUE THREAD

**Issue by EPadronU** [coleifer/peewee#521]
Hello, everyone.

In the following code:

    class Model(db.Model):
        field = pw.Charfield(
            choices=[1, 'foo']
        )
        
        def __unidoce__(self):
            return self.<api call I don't know about>

I would like to print **foo** instead of **1**. The ORM implements a way to achieve this?

Thanks in advance.

**Comment by coleifer** [comment]
It's just Python, there's no magic there. One easy way to accomplish this is to write something like this:

```python

class Tweet(Model):
    STATUS_CHOICES = (
        (0, 'Draft'),
        (1, 'Published'),
        (9, 'Deleted'))
    status = IntegerField(choices=STATUS_CHOICES)

    def get_status_label(self):
        return dict(self.STATUS_CHOICES)[self.status]
```

**Comment by EPadronU** [comment]
Thank you very much.

**Comment by pavelik** [comment]
Hello everyone,
and how to display it in select query? (I need it display later in jinja template)
```python
order = Order.select(Order.id, Order.date, Order.status.get_status_label())order_by(Order.date)
```

**Comment by coleifer** [comment]
If you want it as part of the SQL you probably want a `CASE` statement mapping integer statuses to the labels. See the `Case()` helper in the docs: http://docs.peewee-orm.com/en/latest/peewee/api.html#Case

Alternatively, you could avoid "select"-ing a label and just calculate it in Python:

```python
# some view
orders = Order.select(Order.id, Order.date, Order.status).order_by(Order.date)

# some jinja template
{% for order in orders %}
  {{ order.id }} {{ order.get_status_label() }}
{% endfor %}
```

**Comment by pavelik** [comment]
Ok, your solution works. Before it I have tried:

```python
{% for order in orders %}
  {# status column is populated with the status value, so we can use the helper method to get label #}
  {{ order.id }} {{ order.status.get_status_label() }}
{% endfor %}
```
...but this not work. Your answer works as I expected.

Thank you very much.
