### ISSUE TITLE
Keyword URLs supported in database connection?

### ISSUE THREAD

**Issue by SamuelMarks** [coleifer/peewee#528]
Looking through your examples, looks like I need seperated values rather than a single URL.

So going off that:

```
from os import environ
from operator import add

environ.setdefault('HEROKU_POSTGRESQL_AMBER', 'postgres://username:password@hostname:PORT/dbname')

username, password, hostname, PORT, dbname = reduce(
    add, reduce(add,
                map(lambda e: map(lambda i: i.split('/'), e),
                    map(lambda elem: elem.split(':'),
                        (lambda e: e[e.find('//') + 2:].split('@'))(
                            environ['HEROKU_POSTGRESQL_AMBER']
                        )))))
```

I can then do:

```
from playhouse.postgres_ext import PostgresqlExtDatabase

psql_db = PostgresqlExtDatabase(dbname, user=username)
```

Unfortunately `PostgresqlExtDatabase.__init__` isn't documented; and just uses `*args` and `**kwargs` everywhere.

**How do I provide all these details to the initialiser?**

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#db-url

**Comment by coleifer** [comment]
You can use the dburl module or you can check the documentation on psycopg2. Besides the name of the database, all the other args are passed directly to psycopg2.

**Comment by SamuelMarks** [comment]
Thanks, that worked.
