### ISSUE TITLE
[Feature] Ability to explicitly switch db connection per query 

### ISSUE THREAD

**Issue by alexlatchford** [coleifer/peewee#531]
Currently models are defined globally and you have to specific the database in the metaclass, I'd like a way to switch db connection explicitly. I understand that the execution_context decorator exists but still only worked with a single peewee connection pool (i.e. threads).

For my use case I've created a manager class to creates new connection pools per process to get around psycopg2's limitations in that respect. This works great but means I have to hook into private member variables to override the database attribute on Query objects to specify the correct connection (or it'll use the parent/global one that I specified when defining the module).

I'm thinking of a syntax something like this:

```python
from peewee import *
from multiprocessing import Process

global_db_conn = PostgresqlDatabase(...)
class MyModel(Model):
    name = CharField()

    class Meta:
        database = global_db_conn

MyModel.create_table()

def run():
    process_db_conn = PostgresqlDatabase(...)
    my_process_obj = MyModel.db(process_db_conn).get()  # Or select/update/delete etc.

my_proc = Process(target=run)
my_proc.start()
my_proc.join()
```

Not sure if I've explained the problem or covered all the bases or whether there is a nicer solution but this is certainly a problem I'd love to upvote! (If I get a vote that is)

Thanks,
Alex

**Comment by alexlatchford** [comment]
PS. My current solution is something like:

```python
query = MyModel.select()
query.database = process_db_conn
result = query.execute()
```

Works just about, having some teething problems with connections hanging around too though but think it's psycopg2 rather than peewee :)

**Comment by coleifer** [comment]
Thanks for the feature request, seems like a good one. There's a little bit of prior art in the `playhouse.test_utils` module for using a separate database in a context manager for testing.

**Comment by coleifer** [comment]
Added a new ``Using`` context manager to the `playhouse.read_slave` module. Still needs docs, but you can find examples in the tests.

**Comment by alexlatchford** [comment]
Awesome! Cheers Charles, I've put in a ticket into our system to move over to using this I'll let you know once we're using it in LIVE :)

**Comment by coleifer** [comment]
Yikes, good luck!
