### ISSUE TITLE
MySQL full text search

### ISSUE THREAD

**Issue by leebrooks0** [coleifer/peewee#532]
Is there any support for MySQL full text search? I see you can call fn.any_function(), but I am not sure how you would use that when using MATCH AGAINST?

**Comment by coleifer** [comment]
Check out http://docs.peewee-orm.com/en/latest/peewee/querying.html#adding-user-defined-operators

**Comment by elliotchi** [comment]
@coleifer Is there a way to add the FULLTEXT index on the model?

**Comment by coleifer** [comment]
Looks like MySQL syntax is `create fulltext index ...`, which is not supported by peewee's out-of-the-box schema manager. Your best bet is to just run it as a one-off query:

```
db = MySQLDatabase(...)

def create_schema():
    db.create_tables(list_of_models)
    db.execute_sql('CREATE FULLTEXT INDEX ...')
```

**Comment by aaveidt** [comment]
@coleifer the above link is expired. I can't see the way to implement full text search in mysql

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#adding-user-defined-operators
