### ISSUE TITLE
Issue with database.transaction()  for playhouse.flask_utils import FlaskDB 

### ISSUE THREAD

**Issue by havannavar** [coleifer/peewee#539]
I am using FlaskDB

    from flask import Flask
    from playhouse.flask_utils import FlaskDB

      DATABASE = {
    'name': 'testdb',
    'engine': 'playhouse.pool.PooledPostgresqlExtDatabase',
    'user': 'sats',
    'max_connections': 32,
    'stale_timeout': 600,
     }
    app = Flask(__name__)
    app.config.from_object(__name__)
    database = FlaskDB(app)

How to use database.transaction()  as mentioned below
# Explicitly roll back a transaction.
    with database.transaction() as txn:
        do_some_stuff()
        if something_bad_happened():
            # Roll back any changes made within this block.
            txn.rollback()

as FlaskDB has no attribute 'transaction'

**Comment by coleifer** [comment]
You need to access the `peewee` database associated with the Flask `Database` object. So,

```python
with database.database.transaction():
    ...
```
