### ISSUE TITLE
UnsignedIntegerField?

### ISSUE THREAD

**Issue by nilp0inter** [coleifer/peewee#542]
Hi,

I'm trying to create a model with an unsigned integer field but I can't find how to do it with peewee.

Is this possible?

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field

**Comment by sooslaca** [comment]
if you got here through google - like me - here is a quick solution which worked for my use case
``
uid    = SmallIntegerField(null=True, constraints=[SQL("UNSIGNED")])
``

**Comment by coleifer** [comment]
:+1:  thanks for sharing @sooslaca

**Comment by sanjok-bless** [comment]
@coleifer, why do not you add an unsigned=False|True attribute to IntegerField?

**Comment by binderclip** [comment]
got this one worked:

```
class UnsignedIntegerField(IntegerField):
    field_type = 'int unsigned'
```

(peewee 3.3.4)

**Comment by kent-cheung** [comment]
@sooslaca 
it doesn't work as you said.

**Comment by coleifer** [comment]
You can use @binderclip snippet, which works for Peewee 3.x and newer.

**Comment by ionesculiviucristian** [comment]
> got this one worked:
> 
> ```
> class UnsignedIntegerField(IntegerField):
>     field_type = 'int unsigned'
> ```
> 
> (peewee 3.3.4)

Good luck using that with decimals.

**Comment by musnows** [comment]
> got this one worked:
> 
> ```
> class UnsignedIntegerField(IntegerField):
>     field_type = 'int unsigned'
> ```
> 
> (peewee 3.3.4)

```
class UnsignedIntegerField(peewee.IntegerField):
    field_type = 'int unsigned'

class UnsignedDoubleField(peewee.DoubleField):
    field_type = 'double unsigned'
```

thx, works in `peewee==3.16.2`
