### ISSUE TITLE
Meta Class fields not inherited

### ISSUE THREAD

**Issue by stephenfin** [coleifer/peewee#545]
Take two models that demonstrate inheritance:

    class BaseSchema(Schema):
        """Base serializer."""
        id = fields.Integer(dump_only=True)
        created_at = fields.DateTime(dump_only=True)

        class Meta:
            ordered = True

    class PersonSchema(BaseSchema):
        """Person serializer."""
        updated_at = fields.DateTime(dump_only=True)
        name = fields.String()
        email = fields.Email(required=True)

The `PersonSchema` schema inherits all the attributes of the `BaseSchema`, as expected. However, it does not seem to inherit the meta attributes (i.e. `ordered`). To ensure ordered output, it is necessary to include these two lines in every model:

    class Meta:
        ordered = True

I don't know if this is something that could be solved or not (I'm not all that familiar with the implementation of these 'Meta' classes).

**Comment by coleifer** [comment]
This doesn't look like peewee to me.

**Comment by stephenfin** [comment]
Nope - it's Marshmallow. My apologies.
