### ISSUE TITLE
extending database.connect_kwargs in / with ExecutionContext

### ISSUE THREAD

**Issue by richey-v** [coleifer/peewee#546]
I'd like to be able to have same application (in Flask) be able to connect to database (MySQL) with different arguments for some transactions.  Specifically, looking for a way to have certain transactions coming from certain URLs be read-only and some be read/write.

I thought db.execution_context decorator would be a very cool way to annotate the handlers for the smaller set of the read/write URLs (letting default be read-only).

I started digging into extending peewee classes to do this, but wanted to check with you before spending much time.  Maybe a similar feature is planned, or maybe there is a better way?

**Comment by coleifer** [comment]
Unfortunately I don't know how well this will work given the API of `ExecutionContext`. You might look into the new `Using` helper, as I think this is more what you want:

http://docs.peewee-orm.com/en/latest/peewee/api.html#Using
