### ISSUE TITLE
implicit join via select function

### ISSUE THREAD

**Issue by langit** [coleifer/peewee#553]
I use django a lot and have just come to know about peewee, and I already like it. When I read of the N+1 behavior in the quickstart, an idea suddenly hit me: would it be nice if peewee can automatically figure out how to join tables behind the scenes so that users are relieved from such SQL concepts? Here is what I mean in more details:

    for pet in Pet .select(Pet.name,  Pet.owner.name
                     ).where(Pet.animal_type == 'cat'):
        print pet.name, pet.owner.name

From the fields provided in the select(...) function, it should be possible to infer what kind of join is needed to provide those selected fields. Just a very rough idea, I hope you find it interesting and worth refining. Looking forward to hearing from you on what you think about this idea.

**Comment by coleifer** [comment]
This is definitely a nice API and something I will consider for peewee 3.0 (whenever that might be, no timetable yet but I'm starting to think about it). I've added this to the TODOs for peewee 3. Closing for now.
