### ISSUE TITLE
negative operator for descending order

### ISSUE THREAD

**Issue by langit** [coleifer/peewee#556]
I'd like to propose a syntax sugar for ordering. Instead of 

    .order_by(User.name.desc())

one can also do

    .order_by( - User.name)

which simply requires a hook method in class Node:

      def __neg__(self):
             self._ordering = "DESC"

**Comment by coleifer** [comment]
* 08b3c0ee03576e16965b9003b38b4bad4b126fb3
* 3ced2b6d3955243fb815250158c44af94b212781
* 2f114136cb823f5a5b0c936dcc93d313c9e4f368
