### ISSUE TITLE
playhouse.db_url shouldn’t remove the leading slash

### ISSUE THREAD

**Issue by bfontaine** [coleifer/peewee#557]
[`playhouse.db_url`removes the first character of the path](https://github.com/coleifer/peewee/blob/master/playhouse/db_url.py#L45) , which means that when you think you’re connecting to `/foo/bar/mydb.db` it’ll in fact try to connect to `foo/bar/mydb.db` and fail.

This means I’ve to use `sqlite3:////foo/bar/mydb.db` to use an absolute path. Why does it behave like this?

**Comment by coleifer** [comment]
This follows the pattern used by SQLAlchemy:

http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html#sqlite

This translates to `sqlite://<no host, so empty>/<path to database>`.

**Comment by coleifer** [comment]
See also: https://pythonhosted.org/Flask-SQLAlchemy/config.html

**Comment by bfontaine** [comment]
Thanks!
