### ISSUE TITLE
ArrayField: to lower 

### ISSUE THREAD

**Issue by havannavar** [coleifer/peewee#560]
I am trying to convert ArrayField values to lower case, but unsuccessful

here is my query with exception

      Tweets.select().where((fn.Lower(Tweets.preferred_city) == fn.Lower(city)) & (fn.array_lower(Tweets.tagging).contains_any(['foo','bar'])))

          ProgrammingError: function contains_any(unknown) does not exist
        LINE 1: ..."."PREFERRED_CITY") = Lower('NewYork')) AND contains_a...
  
I am using Postgresql 9.4 and in the document i can see this
http://www.postgresql.org/docs/9.4/static/functions-array.html

**Comment by coleifer** [comment]
I don't think `array_lower` does what you are expecting there. It returns the lower bound of the requested array dimension.

**Comment by havannavar** [comment]
So, can you let me know, how can i resolve this issue ?

**Comment by coleifer** [comment]
I am not sure. Can you express this query using plain SQL? If you can give me the correct SQL, then I will help you translate it to utilize peewee.
