### ISSUE TITLE
joining is not allowed on UpdateQuery instances

### ISSUE THREAD

**Issue by arski** [coleifer/peewee#570]
this is an error message from peewee. May I ask why this is though? Let's assume I want to run an update on Books where the Publisher of said book is based in the US. That's imo a very common update query. Or is there just a different way of doing this during an update?

**Comment by coleifer** [comment]
```python
us_pub = Publisher.select().where(Publisher.country == 'US')
Book.update(foo='bar').where(Book.publisher << us_pub)
```

IIRC only MySQL supports joins on update queries, while SQLite and Postgres do not. Subqueries are the way to go.

**Comment by arski** [comment]
aha! thanks for the quick reply.

**Comment by arski** [comment]
actually, what if i wanted to populatw my books with some value
from the related publisher.. No way to do that i guess?

**Comment by GothAck** [comment]
If you're using postgres you can theoretically use `update({Book.foo: Publisher.bar}).from_(Publisher)`

**Comment by coleifer** [comment]
@GothAck is correct, and this is supported by peewee. Sqlite will be adding support for this in the next release as well, which is exciting.

Example peewee usage:

https://github.com/coleifer/peewee/blob/611a08987e8f08af1056ec679ea6cfdccb87c65b/tests/model_sql.py#L689-L743
