### ISSUE TITLE
postgres_ext do not support LTreeField?

### ISSUE THREAD

**Issue by dllhlx** [coleifer/peewee#573]
from the docs <http://docs.peewee-orm.com/en/1.0.0/peewee/playhouse.html#ltree > we can know peewee ext can support postgres ltree but in the source code in github we can not find the define of LTreeField. why?

**Comment by dllhlx** [comment]
i find define of LTreeFiled in peewee old version - 0.9.9 , why delete this logic in lastest version ?

**Comment by coleifer** [comment]
> from the docs we can know peewee ext can support postgres ltree

Where in the docs does it say this?

**Comment by coleifer** [comment]
I have no intentions of adding LTree back, but would accept pull-requests.
