### ISSUE TITLE
peewee successfully updates model with existed unique fields

### ISSUE THREAD

**Issue by semolex** [coleifer/peewee#575]
I have such code:
```python
class User(peewee.Model):
    username = peewee.CharField(unique=True, max_length=50)
    password = peewee.CharField()
    email = peewee.CharField(unique=True, max_length=80)
    status = peewee.IntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'blocked')], default=1)
    class Meta:
        database = database
```
way of creating table:
```python
User.create_table()
```
I have already created record in my DB with username 'Alex'.
And after that, when I'm trying to update some model with username 'Alex', it is updates successfully for the first time! It fails only when I try to do this twice!
Maybe it is issue with something else?

**Comment by coleifer** [comment]
I'm not sure I understand what is happening. Can you share code to replicate the issue?

**Comment by semolex** [comment]
I feel sorry for disturbing you. It is not issue of peewee itself, it was at DB level...
