### ISSUE TITLE
JSON support with MariaDB

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#580]
It would seem that Playhouse has [support](1) for Postgres JSON, where as it doesn't have the same for MySQL. MariaDB, which is backwards compatible, has [supported](1) JSON since 10.0.1 and it would be fantastic to see Playhouse support for this.

Are there any plans to put this on the roadmap?

[1]: https://peewee.readthedocs.org/en/latest/peewee/playhouse.html#pgjson
[2]: https://mariadb.com/kb/en/mariadb/column_json/

**Comment by coleifer** [comment]
I have no plans myself for adding support for any MySQL-specific features since between Postgres and SQLite I never find myself using MySQL. That said, I would certainly be open to a well-tested pull-request (with documentation).

**Comment by foxx** [comment]
Thanks for the quick reply, if I end up using MariaDB JSON heavily then I'll put together a PR.
