### ISSUE TITLE
db_url.connect does not support pooling

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#581]
As seen [here](1), there is no way to make `connect()` use a pooled connection. I've looked over the code and there doesn't appear to be any way to convert an existing DB object into a pooled one, at least short of using some horrible metaclass hacks or monkey patching.

Could someone clarify if this feature is on the roadmap, or whether a PR would be accepted if not?

[1]: http://peewee.readthedocs.org/en/latest/peewee/database.html#connecting-using-a-database-url

**Comment by foxx** [comment]
In the mean time, for anyone who comes across this problem in the future, I was able to get a temporary monkeypatch working;

```
from playhouse import db_url
from playhouse.pool import PooledMySQLDatabase
db_url.schemes['mysql'] = PooledMySQLDatabase
```

The above will replace the MySQL backend with a pooled backend, whenever `connect()` is used. Replace classes accordingly for other databases, see [here](1).

[1]: https://github.com/coleifer/peewee/blob/master/playhouse/db_url.py

**Comment by coleifer** [comment]
You can use `db_url.parse(url)` to parse the data into a dictionary, then pass the dictionary values into a pooled database implementation. Because pooled databases require additional arguments (pool size, etc), they do not seem to me a good candidate for inclusion in the db_url module.

**Comment by foxx** [comment]
That works beautifully, thank you.
