### ISSUE TITLE
Database router and connection manager support

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#583]
As an extension from #582, although Playhouse has an existing class for [ReadSlave](3), it doesn't appear to be a suitable replacement for database routers, as seen in [django](4). 

Admittedly adding support for database routers would most likely require some sort of connections manager, and would need some careful thought on design decision. For example, being able to automatically create/teardown test databases based on a database settings dictionary, similar to the [test db feature](5) in Django.

If such a feature would ever be considered, I will happily spend some time putting together a PR proposal, and would welcome comments/ideas before hand.

Thoughts?

[3]: https://github.com/coleifer/peewee/blob/master/playhouse/read_slave.py
[4]: https://docs.djangoproject.com/en/1.8/topics/db/multi-db/#using-routers
[5]: https://docs.djangoproject.com/en/1.7/topics/testing/advanced/#topics-testing-advanced-multidb

**Comment by foxx** [comment]
Extending the discussion from #582, I was unable to find a clean way to introduce module inspection into Peewee without also bringing in the concept of 'apps', which is way outside of its scope as an ORM.

The cleanest way I've found so far is to use a connection manager by wrapping each connection with a proxy and referencing it later on. The test case can then tell the database proxy to switch out the current connection for the test database connection.

However this breaks because `create_model_tables()` also requires models to be defined explicitly, and due to module inspection not being a clean way forward, the next alternative would be to maintain some sort of global registry of models. This could perhaps be achieved by using the `BaseClass` metaclass to place itself into a list on the peewee module.

So the proposal would be for;

* Database router
* Connection manager
* Models registry

**Comment by coleifer** [comment]
In order to keep peewee simple I have chosen not to implement this type of functionality. The database is simply an attribute on the `Model._meta` object, so tooling could be built to change this at run-time, but at no point do I think peewee will include routers/connection managers like Django for example.

**Comment by foxx** [comment]
Thanks for the quick reply, appreciated.
