### ISSUE TITLE
Query add_column method

### ISSUE THREAD

**Issue by stanep** [coleifer/peewee#593]
Hi , is it possible to add method to query class so we can do something like this

qr = User.select(User.id)

later on
qr.add_column(User.first_name)

**Comment by coleifer** [comment]
No. You can muck around with `SelectQuery._select`, which is a list of the selected columns. Even better is to just use the `SelectQuery.select()` method to modify the list of columns.

**Comment by stanep** [comment]
Ok , fair enough
