### ISSUE TITLE
Having a single multi-column index defined in Meta class breaks table/index creation

### ISSUE THREAD

**Issue by josefdlange** [coleifer/peewee#594]
Given the following, table/index creation fails:

```
from peewee import Model, ForeignKeyField
from somewhere import SomeOtherModel

class SomeModel(Model):
    something = ForeignKeyField(SomeOtherModel)
    name = CharField()

    class Meta:
        indexes = (
            (('something', 'name'), True)
        )
```

This is because Python (as far as I can tell) throws away the outermost parentheses as extraneous, so when you iterate over `indexes` on line `4011`, it actually is iterating on `(('something','name'), True)`, meaning that `fields` and `unique` in this case are `'something'` and `'name'`, respectively. If I change the code to the following, it works just fine:

```
    ...
    class Meta:
        indexes = tuple([
            (('something', 'name'), True)
        ])
```

If you like, I can try and figure out a way around this -- I think the parentheses-only code looks a lot better -- and submit a pull request. Or maybe we do want the outermost structure to be a list and not a tuple at all. Your call, just thought I'd report this.

**Comment by coleifer** [comment]
This is not at all a peewee bug. You just forgot that if you want a tuple with one element you need a trailing comma:

```python
    class Meta:
        indexes = (
            (('something', 'name'), True),  # Added trailing comma.
        )
```

**Comment by josefdlange** [comment]
D'oh! I learn something new every day. Thanks for the tip.
