### ISSUE TITLE
 __init__() got an unexpected keyword argument 'abstract' on peewee 2.04

### ISSUE THREAD

**Issue by jbpineiro** [coleifer/peewee#595]
File "C:\Python27\lib\site-packages\peewee.py", line 1801, in __new__
    cls._meta = ModelOptions(cls, **meta_options)
TypeError: Error when calling the metaclass bases
    __init__() got an unexpected keyword argument 'abstract'

**Comment by coleifer** [comment]
Without a little more info I have no idea what to do with this.

Next time take the two extra seconds to format your issue at least.
