### ISSUE TITLE
Feature Request: N+1 query detection

### ISSUE THREAD

**Issue by josephschorr** [coleifer/peewee#596]
It would be really nice if there was a clean way to detect N+1 queries in tests, perhaps by having peewee (when initialized with a flag) raise an exception when accessing a non-cached ForeignKeyField value.

**Comment by coleifer** [comment]
That's a neat idea, but I'm not sure how to implement that without cluttering up the `ForeignKeyField` / `RelationDescriptor` classes.

One thing you can do currently, which is very easy, is to use the `assert_query_count` helper in `playhouse.test_utils` ([documentation link](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#assert_query_count)):

```python
class TestMyApp(unittest.TestCase):
    @assert_query_count(1)
    def test_get_popular_blogs(self):
        popular_blogs = Blog.get_popular()
        self.assertEqual(
            [blog.title for blog in popular_blogs],
            ["Peewee's Playhouse!", "All About Huey", "Mickey's Adventures"])

    def test_expensive_operation(self):
        with assert_query_count(1):
            perform_expensive_operation()
```

I think these are probably a better way of ensuring correct query behavior than checking for accidental foreign key resolutions anyways.
