### ISSUE TITLE
Tests are not run for MySQL?

### ISSUE THREAD

**Issue by pmeinhardt** [coleifer/peewee#598]
Tests are only run for SQLite and PostgreSQL at the moment. Is there any particular reason the suite is not run against MySQL? After all `peewee` claims to support MySQL in the README and documentation.

See [.travis.yml](https://github.com/coleifer/peewee/blob/65bf15f93f2f96abf8b216e6eea056726711a19f/.travis.yml#L8-L10)

Cheers,
Paul

**Comment by coleifer** [comment]
No they are not run for MySQL because there are some failures that I do not intend to fix. MySQL is supported, and most things work, but it is not tested as part of the continuous integration.
