### ISSUE TITLE
Ordering of set in back reference from ForeignKeyField

### ISSUE THREAD

**Issue by josefdlange** [coleifer/peewee#600]
Is it possible, in a simple way, to declare what order in which the back reference created by a ForeignKeyField returns? I can sort the items once I get them (in most cases since the backref groups shouldn't be huge), but offloading this work to the DB would be nice. Is there something right in front of me I am missing?

Thanks!

**Comment by coleifer** [comment]
Well, let's say you have `User` and `Tweet` from the docs:

```python
class User(Model):
    username = CharField(unique=True)

class Tweet(Model):
    user = ForeignKeyField(User, related_name='tweets')
    content = TextField()
    timestamp = DateTimeField(default=datetime.datetime.now)
```

You can observe that the `user.tweets` object is a `SelectQuery`:

```python
>>> u = User.create(username='charlie')
>>> u.tweets
<class '__main__.Tweet'> SELECT "t1"."id", "t1"."user_id", "t1"."content", "t1"."timestamp" FROM "tweet" AS t1 WHERE ("t1"."user_id" = ?) [1]
```

Since it's just a query you can call `order_by()` on it:

```python
>>> u.tweets.order_by(Tweet.timestamp.desc())
<class '__main__.Tweet'> SELECT "t1"."id", "t1"."user_id", "t1"."content", "t1"."timestamp" FROM "tweet" AS t1 WHERE ("t1"."user_id" = ?) ORDER BY "t1"."timestamp" DESC [1]
```

If you don't want to type this all the time, just create a `property` object on `Tweet`:

```python
class Tweet(Model):
    # ... fields ...
    
    @property
    def tweets_ordered(self):
        return self.tweets.order_by(Tweet.timestamp.desc())
```

Then use `tweets_ordered`.

**Comment by josefdlange** [comment]
The property solution is slick. Thanks!

**Comment by dzpt** [comment]
@coleifer then how do you call `tweets_ordered`? since it would belong to User?
It must be `u.tweets_ordered` , but `tweets_ordered` is a property of Tweet?

**Comment by coleifer** [comment]
I had made a mistake, that should have read class User. I've edited the comment. Hope that helps.

**Comment by West7780** [comment]
syntactic sugar!
