### ISSUE TITLE
Add method/hook for default table names

### ISSUE THREAD

**Issue by mikemill** [coleifer/peewee#601]
In our project we are using the singular form for the model names and the plural form for the tables.  This means each of our models has to have `class Meta: db_table = 'foos'`.  It'd be nice if there was a method or hook for defining the default table name algorithm that way it can be defined once.  Currently it is coded directly into `BaseModel.__new__`.

**Comment by coleifer** [comment]
Nice idea, be happy to add that.

**Comment by mikemill** [comment]
Wow, thanks for such a quick response.  That solution is awesome!
