### ISSUE TITLE
will peewee support table partition?

### ISSUE THREAD

**Issue by pyloque** [coleifer/peewee#602]
in our project, table_name is decided by entity field value, so different entities of the same model class can be saved to different tables with same table_name prefix.
I currently self maked an orm framework with less functions.I wish peewee can support table partition,so I could replace it with powerfull peewee.

```
class Account(Model):
    __partition_key__ = 'username'
    __partition_num__ = 256

    username = StringField()
    password = StringField()

Account.query_for('username_xxx')
Account.query_for_partition(123)
```

**Comment by coleifer** [comment]
You can probably build something *on top* of peewee, but peewee itself does not support table partitioning.

If you want to change the table your query uses at run-time, you can set the `ModelClass._meta.db_table` attribute, e.g.

```python
Account._meta.db_table = 'account_123'
query = Account.select().where(Account.username == 'username_xxx')
Account._meta.db_table = 'account'
```

You could write a context manager, for example:

```python
with Account.query_partition(123):
    query = Account.select().where(...)
```

**Comment by jakedt** [comment]
One potential solution that we're looking at: http://architect.readthedocs.io/features/partition/index.html
