### ISSUE TITLE
Allow the use of connection pooling from within database url

### ISSUE THREAD

**Issue by kylef** [coleifer/peewee#611]
It would be nice if the [database URL](http://peewee.readthedocs.org/en/latest/peewee/playhouse.html#db-url) API would support connection pooling.

For example, an argument to the connect function which allows you to use pooling if available. `connect('uri', use_pooling=True)`

**Comment by coleifer** [comment]
Well, actually if you look at the docs, this is now supported. I don't believe I've pushed those changes to PyPI yet, but they will be included in the next release.

![s1432770417 64](https://cloud.githubusercontent.com/assets/119974/7849927/bca1baf6-04a0-11e5-8a4c-4e017584592c.png)

**Comment by kylef** [comment]
Oh nice @coleifer, making this issue has been on my todo list for months since you asked me to on IRC.
