### ISSUE TITLE
Support set timezone

### ISSUE THREAD

**Issue by changjej** [coleifer/peewee#615]
Hello!

I'm making query like following which filter TIMESTAMP field between two dates.
However, the problem is that our MySQL's default timezone is UTC and I want to query in KST timezone.

```python
Log
  .select(fn.Sum(Log.cnt))
  .where(Log.insert_dt.between(start_date, end_date))
  .scalar()
```

When using SQL, I can set timezone by `set timezone="+09:00"`. I cannot find option to set timezone on Peewee.

**Comment by coleifer** [comment]
Just call ``db.execute_sql('set timezone="+09:00"')``. You can check your mysql driver's docs to see if it accepts a `time_zone` parameter. If not, you can subclass `MySQLDatabase`, override the `_connect` method, and run `set time_zone` on the newly-created connection.
