### ISSUE TITLE
Support PostgreSql table inheritance

### ISSUE THREAD

**Issue by horpto** [coleifer/peewee#616]
PostgreSql has cool feature like [Table inheritance](http://www.postgresql.org/docs/9.0/static/ddl-inherit.html). It'd be good to implement this feature using inheritance field in Meta class of model.

**Comment by coleifer** [comment]
I don't know very much about that particular feature, so I can't really say that I have any plans on implementing it. I think I will defer on this one, but if you'd like to discuss making a pull-request let me know.
