### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by fliiiix** [coleifer/peewee#623]
Are there any plans to pack peewee for Debian?
Or are there any reasons this is not gonna happen?

**Comment by fliiiix** [comment]
I've started something https://github.com/fliiiix/python-peewee but like most times I have not really a clue if I'm doing this the right way.

**Comment by coleifer** [comment]
I do not have plans to make a debian package, nor make that part of the peewee source code. `pip` is seen as the primary way for managing python packages these days, anyways.

**Comment by fliiiix** [comment]
Okey cool thanks for your fast response. 
Just to get this right: you're not doing it and it won't be part of this repository, but there is no problem if someone else does it?

**Comment by coleifer** [comment]
Correct. No problem at all if someone else wanted to maintain a debian package.

**Comment by fliiiix** [comment]
:+1:
