### ISSUE TITLE
Support modification tracking by supply an event api?

### ISSUE THREAD

**Issue by galeo** [coleifer/peewee#629]
Peewee has very limited signal support in `playhouse.signals` currently. Does it have any plan to supply a variety of hooks or an event api that could support modification tracking in the future?

**Comment by coleifer** [comment]
The limitations in Peewee are really the maximum possible. Anything more should be implemented in the database as triggers.

**Comment by galeo** [comment]
I'm trying to integrate Whoosh with Peewee just as the way [Flask-WhooshAlchemy](https://github.com/gyllstromk/Flask-WhooshAlchemy) uses [Flask-SQLAlchemy](https://github.com/mitsuhiko/flask-sqlalchemy/) to implement the so-called real-time indexing by tracking **CUD** actions. Maybe this is not a feasible idea.

**Comment by coleifer** [comment]
Well, if you use the `post_save` and `post_delete` hooks, you should be fine. This will not catch bulk inserts, updates or deletes, however.

**Comment by galeo** [comment]
Without catching bulk operations may lead to confusion. Perhaps as you said above,

> The limitations in Peewee are really the maximum possible.
