### ISSUE TITLE
Proposal for FixedCharField?

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#631]
Although Postgres apparently does not experience any performance difference between `char/varchar` [\[1\]][1], other databases such as MySQL do have a noticeable impact [\[2\]][2]. Also, `char` will use slightly less space than a `varchar`, which seems to be consistent across all databases.

Do you think Peewee would benefit from having `FixedCharField` in the Playhouse? Admittedly this probably isn't something that should go into the core. I'm also not entirely happy with the name `FixedCharField`.

Thoughts?

[1]: http://www.postgresql.org/message-id/C11A06F4.4B7B8%pgsql@007Marketing.com
[2]: http://dba.stackexchange.com/questions/424/performance-implications-of-mysql-varchar-sizes

**Comment by coleifer** [comment]
I think I will leave this alone, but if you wanted to add it to `playhouse` you could create a new `fields` module I suppose? (and maybe move the `AESEncryptedField` and `CompressedField` from `shortcuts` I believe).

**Comment by foxx** [comment]
That's a neat idea, it would be a good place for other common fields too. I have some spare time coming up next week for contributions, I'll get this done then.

**Comment by coleifer** [comment]
I've refactored the code, so there is now a `fields` module in `playhouse.fields`. This module contains the encrypted, compressed and many-to-many fields.

**Comment by foxx** [comment]
Damn you are too fast. LGTM, thank you!
