### ISSUE TITLE
Using bitwise and / or in a query

### ISSUE THREAD

**Issue by josefdlange** [coleifer/peewee#642]
Is it possible to use bitwise operations (&, |, #, ~) in a query and have them translate to the (flavor)SQL keywords to _actually_ do the bitwise operation?

**Comment by coleifer** [comment]
Yes, you can use `.bin_and`, `.bin_or`, `^` (xor).

**Comment by coleifer** [comment]
If they are not mapped to the correct operator for your database please let me know.

**Comment by coleifer** [comment]
It looks like I may need a bitwise `NOT`, though, now that I look at it.

**Comment by josefdlange** [comment]
Awesome, thanks. My usage is like this, am I doing it right? I'm trying to select any `Thing` for which its `field` (an `IntegerField`, representing a bit mask) when ANDed with `other_integer` (also a bit mask), is a match (or better, which is why I'm not doing just integer equality comparison).

So if the binary of `Thing.field` is 11111111 and `other_integer`'s binary is 10101011, that `Thing` would be selected.

So, in essence, am I correct in the use of the `bin_and` method in the where clause?

```
things = (
    Thing
    .select()
    .where(Thing.field.bin_and(other_integer) == other_integer)
)
```

**Comment by coleifer** [comment]
Yeah, I think that should be right.
