### ISSUE TITLE
2.6.2 install error

### ISSUE THREAD

**Issue by pitchforks** [coleifer/peewee#646]
I do setup.py install because I am packaging the source code tarball into a personal package for the Linux distribution that I'm using (it's Slackware64-14.1 with Python 2.7.5) and I'm getting this traceback for peewee-2.6.2:

    Traceback (most recent call last):
      File "setup.py", line 14, in <module>
        ext_modules = cythonize('playhouse/speedups.pyx')
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
        aliases=aliases)
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
        for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
      File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'playhouse/speedups.pyx' doesn't match any files

It did not happen before, for 2.6.1 and earlier versions.

I have Cython-0.22 installed, but I'm pretty sure I installed that as dependency for something else, not for peewee.

I have also skimmed through the README and had a look at http://docs.peewee-orm.com/en/latest/peewee/installation.html, but could not find any useful hints.

What additional steps should I take for peewee-2.6.2 so setup.py build/install succeeds?

Thanks.

**Comment by coleifer** [comment]
I just added that, maybe I needed to add it to `MANIFEST.in`... I pushed a new release, 2.6.3. Will you let me know if that fixes it?

**Comment by pitchforks** [comment]
2.6.3 builds fine, thank you.

The build also succeeded when I temporary uninstalled Cython. Since you did not modify the install instructions in the documentation, I assume that Cython did not become a mandatory build dependency for this new peewee version?

**Comment by coleifer** [comment]
Cython is an optional dependency, but I had forgotten to include the cython module in the package data I believe. I can add info to the docs though, that's a good idea. Thanks for reporitng this!
