### ISSUE TITLE
Introducing returning for postgres

### ISSUE THREAD

**Issue by IxDay** [coleifer/peewee#647]
Hello, I am currently using peewee for managing a postgresql and I have started implementing a returning function on the update and select queries.

I am interested in contributing the results.

Here is an example:

```python
user = User.update(active=False).where(User.registration_expired == True).returning()
```

The returning method will be a SelectQuery and support the selection arguments

```python
sq = (User.update(active=False)
          .where(User.registration_expired == True)
          .returning(User.username))
for user in sq:
    print user.username
```

And also support the `tuples` and `dicts` chaining:

```python
sq = (User.update(active=False)
          .where(User.registration_expired == True)
          .returning(User.username)
          .dicts())
for user in sq:
    print user.get('username')
```

**Comment by coleifer** [comment]
Interesting, how is this implemented at the SQL level?

**Comment by IxDay** [comment]
http://www.postgresql.org/docs/9.1/static/sql-update.html

`If the UPDATE command contains a RETURNING clause, the result will be similar to that of a SELECT statement containing the columns and values defined in the RETURNING list, computed over the row(s) updated by the command` (the last statement is false, every row can be accessed I tested it) .

The sql statement will look like this

```sql
UPDATE users SET active = FALSE WHERE registration_expired = TRUE RETURNING username; 
```

**Comment by coleifer** [comment]
Gotcha, cool! Can you share your code?

**Comment by IxDay** [comment]
I will make a first pull request in order to see if the implementation looks good for you, with a simple test case.

**Comment by coleifer** [comment]
I've gone ahead and merged support for `RETURNING` clauses on `UPDATE`, `INSERT` and `DELETE` queries. These only work with Postgresql, and are protected using a database config attribute, `returning_clause`. I will be adding documentation as well today, then I think it's good to go!
