### ISSUE TITLE
Weird double exception while testing

### ISSUE THREAD

**Issue by brendanWeb** [coleifer/peewee#652]
I am getting both a sqlite3.IntegrityError as well as the peewee.IntegrityError that I am asserting for in my tests. Is this normal? It's causing my tests to error out.
Gist of the issue:
https://gist.github.com/brendanWeb/584d62ba5e7fb9c7338f

**Comment by coleifer** [comment]
The problem is your call to `assertRaises`. It should be written:

```python
self.assertRaises(IntegrityError, Post.create, description="hello world")
```

Or

```python
self.assertRaises(IntegrityError, lambda: Post.create(description="hello world"))
```

**Comment by brendanWeb** [comment]
Thanks!
