### ISSUE TITLE
Model with no primary key

### ISSUE THREAD

**Issue by ballan91** [coleifer/peewee#654]
It looks like while this is supported the documentation might be incorrect, I believe what the documentation actual intends is:

```python
class MyData(BaseModel):
    timestamp = DateTimeField()
    value = IntegerField()

    class Meta:
        primary_key = None
```
While:
```python
    primary_key = False
```
Seems to cause issues when trying to issue a .save() command.

**Comment by foxx** [comment]
Bug confirmed, curiously I just came across this issue myself and was about to report it, weird coincidence? Or perhaps a recent change?

**Comment by coleifer** [comment]
Setting `primary_key = None` will cause peewee to auto-generate an `id` primary key field, so the docs are correct regarding `False`.

Unfortunately some APIs just don't work when you don't have any primary key at all, `save()` being one of them. You need to use the `.insert()` and `.update()` APIs instead.

**Comment by coleifer** [comment]
Added some docs to that effect.

**Comment by foxx** [comment]
Ah yeah, makes sense now, thanks for the quick reply!
