### ISSUE TITLE
Simple question on multiple Model instances from single Join query

### ISSUE THREAD

**Issue by jessepeterson** [coleifer/peewee#660]
First: thanks for Peewee: it's great! Sorry to litter the bug tracker with a simple question, but I'm not able to figure out how to get multiple model instances from a single joined row. For example:

```python
q = Student.select(Student, Teacher).join(StudentTeacher).join(Teacher).where(Student.name == 'Bob')

for row in q:
    print row # is only a Student instance, where is Teacher?
```

When I iterate over `q` I only get a Student instance. How do I get the associated Teacher model instance out of a simple join query like above? When I turn on query logging it's clearly querying for the relevant fields.

I could use `.dict()` to get the raw values and rebuild each model instance separately I suppose but that seems overly laborious.

**Comment by jessepeterson** [comment]
I should add that if I access the `related_name` references of my M:N table I can get to the associated data — but at the cost of multiple queries (hence the join is sort of useless). I *should* be able to get two instances from a single query, no? `aggregate_rows()` and `prefetch()` don't seem to apply to this very simple case. Any help is appreciated!

**Comment by coleifer** [comment]
You need to also select the junction table:

```python
q = Student.select(Student, StudentTeacher, Teacher).join(StudentTeacher).join(Teacher).where(Student.name == 'Bob')
```

Then you can access it via:

```python
row.studentteacher.teacher
```
