### ISSUE TITLE
why does peewee default to it's own file?

### ISSUE THREAD

**Issue by dmead** [coleifer/peewee#666]
https://github.com/coleifer/peewee/blob/master/peewee.py#L3955

maybe i lack contact about sqlite? why is this hard coded to it's own filename?

**Comment by coleifer** [comment]
That line of code is there to allow you to quickly create models that point to a SQLite database named `peewee.db`. So if you just imported `Model` and did not define your own database, it would use the `default_database`.

Most everyone will define their own db, though, so this is not an issue in practice, e.g.

```python
from peewee import *

db = SqliteDatabase('my_database.db')

class BaseModel(Model):
    class Meta:
        database = db

# application models extend `BaseModel`.
```
