### ISSUE TITLE
peewee tries to hard to connect to a data store

### ISSUE THREAD

**Issue by dmead** [coleifer/peewee#667]
I've just had a problem were i didn't have MySQLdb installed, so peewee failed over to sqlite3

this was really annoying because it happened silently and without warning.

im using a statement like this to connect

`db = MySQLDatabase('somedatabase', host='127.0.0.1', port=3306, user='user', passwd='pass')`

**Comment by emamirazavi** [comment]
Where are you using sqlite3 been mentioned in your code example?

**Comment by dmead** [comment]
thats the point. i'm not. peewee is defaulting to write to a file called "peewee.db" every time.

**Comment by coleifer** [comment]
Peewee will not do this silently. Can you share your model definitions? I'm wondering if you neglected to set the db for your models.

**Comment by dmead** [comment]
`
from myproject import database
class BaseModel(Model):
  class Meta:
      db = database`

i'm also using arnold to run table creation stuff, if that matters to you

**Comment by emamirazavi** [comment]
Peewee raises an exception on not installing pymysql and MySQLdb! Which
version are you using?

**Comment by dmead** [comment]
i have both installed. actually.

**Comment by emamirazavi** [comment]
Pay attention, is your code running correctly? Any old edition of code
cached and run? Can you paste your file content and describe a little about
your process of run code?

**Comment by coleifer** [comment]
Yeah, basically this doesn't add up. Peewee won't silently "fall back" to SQLite if you're trying to use MySQL. And if you don't have a mysql driver installed and try to use MySQLDatabase, it will raise an error.

**Comment by dmead** [comment]
my bad.

the ref i had inside the base model was bad. it was actually falling back to sqlite but it was my fault.
