### ISSUE TITLE
Add support for citext columns in postgres 

### ISSUE THREAD

**Issue by esafak** [coleifer/peewee#668]
`pwiz` incorrectly translates `citext` columns to `UnknownField`.

**Comment by coleifer** [comment]
I wouldn't say "incorrectly" -- Peewee does not have any field comparable to a case-insensitive text field. Pwiz is designed to cover the most common data-types but it cannot hope to cover them all. Hence, `UnknownField`. You can go through and replace them with `TextField` if you like.

**Comment by esafak** [comment]
Aren't `text` and `citext` different, though? Isn't the real problem that peewee doesn't have a case-insensitive field?

**Comment by coleifer** [comment]
They are different, and yes, the issue is that peewee does not have a case-insensitive text field. That said, I don't plan on adding one. If you'd like you can add one yourself quite easily, though:

http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field

**Comment by patarapolw** [comment]
Is it as simple as,

    class CITextField(TextField):
        field_type = 'citext'
