### ISSUE TITLE
reflection module is using a not convenient import statement

### ISSUE THREAD

**Issue by aliubchenko** [coleifer/peewee#680]
Reflection.py has this as the import statement:
from peewee import *

When you include peewee in your own package of libraries and use it, all classes from peewee become \<your_package\>.peewee.*
However, for models that were created using Introspection, peewee classes are still peewee.* because of that import statement.

Consequently if you want to do a select query on the generated models, in this function:

    def parse_node(self, node, alias_map=None, conv=None):
        sql, params, unknown = self._parse(node, alias_map, conv)
        if unknown and conv and params:
            params = [conv.db_value(i) for i in params]

        if isinstance(node, Node):

The last check fails. Because it is comparing node (peewee.Entity, created by Introspection) with \<your_package\>.peewee.Node
This fails and leads to queries missing the "as t1" statement right after "from \<table\>" clause.
Leading to the database complaining about missing column names t1.\<column\>.

The fix that worked for me is changing the import statement to use relative import:
from ..peewee import *

This allowed everything to reside in my package and the check worked and proper query was generated.

**Comment by coleifer** [comment]
I don't really think this is a use-case I had intended to cover.
