### ISSUE TITLE
Support for the MySQL BIT data type

### ISSUE THREAD

**Issue by jmenglund** [coleifer/peewee#683]
http://dev.mysql.com/doc/refman/5.7/en/bit-type.html

http://stackoverflow.com/questions/289727/which-mysql-datatype-to-use-for-storing-boolean-values

For my own databases I would probably not use the BIT data type at all (see for example http://www.xaprb.com/blog/2006/04/11/bit-values-in-mysql/) but I need it in order to work with a database not created by me.

**Comment by coleifer** [comment]
At present Peewee uses the `bool` data-type, which is also what Django uses for BooleanField in Django.

If you want `Bit` specifically you can either create a custom field, or specify a field override:

* http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field
* http://docs.peewee-orm.com/en/latest/peewee/api.html#Database

**Comment by jmenglund** [comment]
Thank you very much! My problem was easily solved.

I'm sorry I didn't read the docs more carefully. Perhaps a link to the section "Creating a custom field" directly after the field types table could prevent others from making the same mistake.

**Comment by coleifer** [comment]
Added the links, thanks!

**Comment by jonas-gbl** [comment]
@jmenglund Hello, I am trying to do the same but I have troubles converting the string of hex characters retrieved to booleans. I am a beginner in Python, could you share some snippet
