### ISSUE TITLE
Does peewee support MySQL REPLACE INTO syntax?

### ISSUE THREAD

**Issue by messense** [coleifer/peewee#684]
I only see upsert support for SQLite in documentation.

And another question, does peewee support MySQL ``INSERT IGNORE`` or ``INSERT...ON DUPLICATE KEY UPDATE`` syntax?

**Comment by coleifer** [comment]
Not at present, but I would consider a pull request and would work with you on getting the code into good shape. For now I'd suggest using hand-written SQL queries if you want upserts with MySQL.
