### ISSUE TITLE
Examples of how to add request hooks in wheezy.web

### ISSUE THREAD

**Issue by thirashima** [coleifer/peewee#685]
I'd like to see an example of how to add request hooks for db connection management to the wheezy.web framework. I've tried to figure it out myself, but it is non-obvious to me. Thanks!

**Comment by tuukkamustonen** [comment]
Don't know the framework, but you should probably use [middleware](https://pythonhosted.org/wheezy.http/userguide.html#middleware). Assuming `peewee_middleware` is never the last one:

    def peewee_middleware(request, following):
        db.connect()
        try:
            response = following(request)
        finally:
            if not db.is_closed():
                db.close()
    return response

    app = WSGIApplication(middleware=[
        lambda: peewee_middleware,
        path_routing_middleware_factory
    ])

I would think this question belongs more to wheezy.web project than to peewee, though.

**Comment by thirashima** [comment]
Thanks. I added this here because the peewee documentation specifically asks you to open a ticket if there are any other frameworks you'd like to see examples for. http://docs.peewee-orm.com/en/latest/peewee/database.html#other-frameworks

**Comment by tuukkamustonen** [comment]
Oh, I stand corrected. Did you have luck with the suggestion?

**Comment by coleifer** [comment]
@thirashima -- If you come up with some working code, please comment on this issue and I will add it to the docs. For now I am closing this.

**Comment by thirashima** [comment]
the code that tuukkamustonen provided does seem to be working. thank you everyone for the help.

**Comment by coleifer** [comment]
Cool, I will update the docs, thanks d00dz.

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/database.html#wheezy-web
