### ISSUE TITLE
ascii codec error while running execute_sql

### ISSUE THREAD

**Issue by roozbehid** [coleifer/peewee#690]
I have a simple execute_sql command like this 

        self.db.execute_sql("""
        INSERT IGNORE INTO artists (name,alias_name)
                                   select name,alias_name
        from my_actors""")

The first time I run it (which I mean there are no duplicates...) it runs fine.
But second times it give me 

           File "c:\WinPython\python-2.7.6.amd64\lib\site-packages\peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
           File "c:\WinPython\python-2.7.6.amd64\lib\site-packages\MySQLdb\cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
           File "c:\WinPython\python-2.7.6.amd64\lib\site-packages\MySQLdb\cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
           File "c:\WinPython\python-2.7.6.amd64\lib\warnings.py", line 29, in _show_warning
    file.write(formatwarning(message, category, filename, lineno, line))
           File "c:\WinPython\python-2.7.6.amd64\lib\warnings.py", line 38, in formatwarning
    s =  "%s:%s: %s: %s\n" % (filename, lineno, category.__name__, message)
          UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-20: ordinal not in range(128)

Running this command on MySQL works fine and I think this has to do something with peewee trying to check for warning and .....
I am using peewee 2.6.3 and MySQL charachter sets for all tables are set to utf-8.

**Comment by coleifer** [comment]
Using an interactive debugger, are you able to examine the message of the warning that is failing to be displayed? My feeling is that this is not an issue with Peewee, but I'd like to be sure before closing.

**Comment by coleifer** [comment]
```python
file.write(formatwarning(message, category, filename, lineno, line)
```

That is the line that I think is problematic. Something in the warning message, maybe?

**Comment by roozbehid** [comment]
warning is about having duplicate values I guess, that is why I used INSERT IGNORE. but anyway this throws an exception which should not happen.
The name of column I am using is unicode and somethimes it is ascii I guess...I am myself having problem printing it out....so I used two different lines of code to check if it is unicode or it is ascii!

But all subsequent enquires and everything works as far as I can tell! warning displaying causes problem

**Comment by coleifer** [comment]
> The name of column I am using is unicode and somethimes it is ascii I guess...I am myself having problem printing it out....so I used two different lines of code to check if it is unicode or it is ascii!

OK, then that sounds like the issue. You might've mentioned that in the issue description. This isn't a peewee issue, but an issue with the MySQLdb library.
