### ISSUE TITLE
Output null values for missing dates

### ISSUE THREAD

**Issue by aidanheerdegen** [coleifer/peewee#710]
Hi,

I've tried and I've failed.

I have a table like so 
```python
class ShortUsage(BaseModel):
    projid = ForeignKeyField(Project, to_field="projid")
    folder = CharField(index=True)
    user = ForeignKeyField(User, to_field="username")
    # Support only dates. Don't want sub-day timescales, makes it harder to join
    # data and snapshots are only taken daily
    scandate = DateField(index=True)
    inodes = FloatField()
    size = FloatField()
    class Meta:
        # Combination of projid+folder+user+date must be unique
        indexes = ( (('projid','folder','user','scandate'), True), )
```
For each projid and user I want to output the sum of size, which I can do no problem. Not all users have entries for all dates in a given range. I want to force the output of a value (zero?) for dates where they have no data. Basically, I need to output the sum of size for a superset of all dates within a given range.

I have succeeded in making a query which produces the dates I need for a given period:
```python
SUalias = ShortUsage.alias()
q1 = SUalias.select(fn.Distinct(SUalias.scandate).alias('alldate')).where(SUalias.projid == projid & SUalias.scandate >= startdate & SUalias.scandate <= enddate).alias('q1')
```
but when I try and join that to my existing table
```python
    for date, diskusage in ShortUsage.select(ShortUsage.scandate,fn.SUM(ShortUsage.size))\
        .where((ShortUsage.user == user) & (ShortUsage.projid == projid))\
        .join(q1, JOIN.LEFT_OUTER, on=(q1.c.alldate == ShortUsage.scandate))\
        .group_by(ShortUsage.scandate)\
        .order_by(ShortUsage.scandate).tuples():
        dates.append(date)
        usage.append(diskusage/1000.)
```
It does not report values for all the dates in q1. Is this because it is a LEFT_OUTER join? When I try a full join or RIGHT_OUTER I get this:
```
peewee.OperationalError: RIGHT and FULL OUTER JOINs are not currently supported
````
I am using v2.6.3, and the docs seem to suggest full joins are possible 

> By default peewee will use an INNER join, but you can use LEFT OUTER or FULL joins as well

Any assistance would be greatly appreciated.

**Comment by coleifer** [comment]
If you're using SQLite, then while Peewee supports RIGHT OUTER, SQLite itself does not. Can you simply switch the order of your joins and use a left outer?

**Comment by coleifer** [comment]
You may need to add clauses to your where or join as well that allow for the date to be NULL. But, basically this is a SQL question not a peewee bug.
