### ISSUE TITLE
Problem with playhouse.db_url.connect query params

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#711]
Due to an outstanding [bug](https://bugs.python.org/issue24887) in sqlite3, some connection flags such as `mode=memory/cache=shared` can only be passed in via URI.

However, `playhouse.db_url.connect()` [converts](https://github.com/coleifer/peewee/blob/master/playhouse/db_url.py#L68) these query string parameters into `kwargs` for the database `connect()` call and are stripped from the URI, meaning that they are never actioned on.

As a temporary workaround for Sqlite3, you can bypass `db_url.connect()` and  use `SqliteDatabase` directly with `uri=True`, however it would be nice if it handled this stuff automagically.

**Comment by coleifer** [comment]
Well, technically I think you can specify those using PRAGMAs, can't you? Or as manual params with `connect()`...

But isn't the `uri` aspect fairly new to pysqlite, or am I mistaken?

**Comment by coleifer** [comment]
It looks also like it's a Python3 only thing at the moment, added in 3.4, so I'm going to hold off on supporting that directly.

**Comment by foxx** [comment]
Oh I wasn't aware of PRAGMAs, I'll take another look at this, thanks!

**Comment by foxx** [comment]
After looking at this deeper, some options cannot be enabled via PRAGMAs, such as "shared cache". In this particular example, Python 2.x would have to use `sqlite3.enable_shared_cache(True)` module global, rather than specifying in the URLs. For this feature to have Python 2.x support, the `uri` module functionality would have to be [backported][1], which is extremely difficult given that it's a `cpython` module. 

For anyone seeing this in future, if you're using Python 2.x then you're mostly outta luck. If you're using Python 3.x, then use `uri=True`.

[1]: https://hg.python.org/cpython/rev/f13bb1e40fbc
