### ISSUE TITLE
Backreference relationship signal

### ISSUE THREAD

**Issue by josefdlange** [coleifer/peewee#714]
Hey! I have a suggestion for an addition (and perhaps I could even undertake implementation if you think it's worthwhile and would accept changes!) to the signal support in `playhouse`. It's a little hard to articulate, but I think there might be value in a signal that fires for some model instance, let's call it `Banana`, when any other model establishes a Foreign Key relationship to that instance. I can imagine that in the save handler of a Model, we'd look at the fields for any dirty FKs, and fire a signal at them.

Does that make sense? Do you think that would be useful?

(the other option, of course, is for me to just implement that logic local to _my_ base model class and not make it part of the signal architecture)

**Comment by coleifer** [comment]
I do not think that I would merge such functionality into peewee, but if you end up implementing it on you r own I'd love to see the diff. Maybe you could post it to this comment?

**Comment by josefdlange** [comment]
Haven't implemented yet, but I'm imagining this. This is not using the signals architecture as I'm not too well-read on your implementation of it.

```
# Save method on the base model (from which everyone inherits)
def save(self, *args, **kwargs):
    # Check all our ForeignKeyFields...
    for field in self.dirty_fields():
        if isinstance(field, ForeignKeyField):
            # If we're using signals, I think we would look it up and fire it here instead of making a
            # heavy assumption that the rel_model implements the method fk_established(self)
            try:
                field.rel_model.fk_established()
            except AttributeError:
                pass
```
