### ISSUE TITLE
In meta ,how to set "order by synax"

### ISSUE THREAD

**Issue by rfyiamcool** [coleifer/peewee#730]
I'm use Peewee ORM.

I have a class such as this:
```python
class Sample(PMBaseModel):
    id = peewee.PrimaryKeyField()
    location = peewee.CharField(max_length=255)
    position = peewee.IntegerField()

    class Meta:
        db_table = 'sample'
```
how i can use Meta Class for set default ordering and define Order type?

**Comment by coleifer** [comment]
Well, I think setting a default ordering is *always* a bad idea, but since you asked:

```python
class Meta:
    order_by = ('location', '-position')
```

`order_by` is a tuple. The elements of the tuple are field names. If prefixed by a "-", then the field is ordered descending.

**Comment by coleifer** [comment]
6969201d22676e4e7557949fcccd13d835a662a4 contains doc updates.
