### ISSUE TITLE
Ability to verify inputs based on field type

### ISSUE THREAD

**Issue by kostasdizas** [coleifer/peewee#739]
Hello,

is it possible to verify whether a value is appropriate for a specific field? Is there a comparison/verification function? Is the equivalent primitive type stored somewhere in the field type (after a very quick search I didn't find one) in order to compare it with the type of the input value?
What's the best way to achieve that?

**Comment by coleifer** [comment]
Peewee does not do any validation. The field's value is converted (if necessary) when the field is used in a query. When reading values from a cursor, the value is converted to Python when the model object is created.

I suppose you could add validation of some kind to your fields, but that would exist outside of peewee.
