### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'is_pk' in migrator

### ISSUE THREAD

**Issue by kramer65** [coleifer/peewee#751]
I've successfully used the peewee migrator to add and drop columns, and today I wanted to use the migrator for the first time to drop a not null constrain on a column. In my model I added and set the null constraint to `True`:

    ticket = ForeignKeyField(Ticket, related_name='sent_to_email_addresses', null=True)

So I wrote the following lines to do the migration:

    from playhouse.migrate import MySQLMigrator, migrate
    migrator = MySQLMigrator(db.database)
    migrate(migrator.drop_not_null('emailsending', 'ticket'))

But I'm getting the following error:
```
File "./migrate_db.py", line 55, in from7To8
    migrate(migrator.drop_not_null('emailsending', 'ticket'))
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 579, in migrate
    operation.run()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 152, in inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 390, in drop_not_null
    if column.is_pk:
AttributeError: 'bool' object has no attribute 'is_pk'
```

Does anybody know what I'm doing wrong here?

**Comment by coleifer** [comment]
The problem, not obvious at all, is that the `ticket` column is not found. I bet that if you change it to `ticket_id` you will be set:

```python
from playhouse.migrate import MySQLMigrator, migrate
migrator = MySQLMigrator(db.database)
migrate(migrator.drop_not_null('emailsending', 'ticket_id'))
```

**Comment by coleifer** [comment]
Looking at the tests, there may be some additional issues with the mysql migrations regarding dropping constraints on foreign keys. Looking into it.

**Comment by kramer65** [comment]
@coleifer - Seeing that you closed this issue I presume you concluded that there were no additional issues with the mysql migrations regarding dropping constraints on foreign keys?

**Comment by coleifer** [comment]
Just to be safe I added another testcase adding and dropping not null constraints to a foreign key to verify they worked.

**Comment by kramer65** [comment]
Thanks for adding the tests. I tested it on 3 test setups before deploying the migration to the production server, and everything went perfectly fine.

Thanks for creating peewee!
