### ISSUE TITLE
The build depends on Cython, not noted in `setup.py`

### ISSUE THREAD

**Issue by skatenerd** [coleifer/peewee#759]
If you don't have Cython, this line:
https://github.com/coleifer/peewee/blob/master/setup.py#L12

Sets `cmdclass` to `None`, which causes the (pip) installation to crash, when `dist.py` tries to iterate over `self.cmdclass`:
https://github.com/jaraco/setuptools/blob/master/setuptools/dist.py#L425

Should we just add an `install_requires` argument when we call `setup`?
https://github.com/coleifer/peewee/blob/master/setup.py#L21

**Comment by coleifer** [comment]
Fixed with the 2.7.1 release. Cython is not required, but if you have it peewee will build some c extension.
