### ISSUE TITLE
make code more beautiful

### ISSUE THREAD

**Issue by olivetree123** [coleifer/peewee#764]
The 'Meta class' makes code ugly,would you prepare to make code like this:
 
class Gym(Model):
    __db_table__ = 'gym'
    id   = IntegerField(primary_key=True)

**Comment by coleifer** [comment]
No, that has been that way since version 0.1.0. Are you serious? Do you think I'd actually change it?

**Comment by coleifer** [comment]
Also, cluttering up the namespace is grosser to me.

**Comment by coleifer** [comment]
Also bite me.
