### ISSUE TITLE
Unexpected parentheses required when using multiple WHERE conditions

### ISSUE THREAD

**Issue by martinburch** [coleifer/peewee#769]
I would expect to be able to write:
```
where(
	(
	modelObject.field_name.is_null(True) |
	modelObject.field_name == ""
	)
)
```
but I must add parentheses around `modelObject.field_name == ""` or the query will be generated improperly. The improperly generated query is essentially

```
WHERE `t1`.`field_name` IS NULL = ''
```

which is exactly the opposite of what I want, returning all records that are not null.

For more discussion, please see:
http://stackoverflow.com/questions/33905987/why-is-peewee-not-nesting-this-where-clause-correctly/33906132

**Comment by coleifer** [comment]
Peewee leans on pythons parser to generate expressions. Because of pythons operator precedence you need parentheses around most comparisons. No magic here, just python.

**Comment by martinburch** [comment]
And yet I can do this without needed extra parens:
```
.where(
	(modelObject.field_name << ['a','b','c'] |
	modelObject.field_name % "%word%")
	)
```
Seems inconsistent. I think this needs to be explained in the docs. At least "you should use parentheses around all comparisons, just to be safe." But a list of situations would be ideal.

**Comment by coleifer** [comment]
What do you suggest? Best practice is just put parentheses around binary expressions, then you won't have any issues.

**Comment by coleifer** [comment]
You can created the equivalent expressions by calling the appropriate doubles underscore method on the field object. You can also instantiate expression objects by hand.

**Comment by coleifer** [comment]
The use of parentheses in your python code won't affect the SQL being generated, improves readability for complex, mutli-clause queries (as I typically assume you line-break each expression), and leaves no room for error.

http://docs.peewee-orm.com/en/latest/peewee/querying.html?highlight=precedence#expressions

**Comment by martinburch** [comment]
Sorry, I think you've already got a note in the docs to this effect.
```
Note that the actual comparisons are wrapped in parentheses. Python’s operator precedence necessitates that comparisons be wrapped in parentheses.
```
Thanks for your additional thoughts on this solidly closed issue.
