### ISSUE TITLE
Full migration framework

### ISSUE THREAD

**Issue by mekanix** [coleifer/peewee#772]
In short, if anyone is working on full fledged migration framework, I'd like to contribute. If nobody is working on it, I'd like to do it. Any pointers on how to contribute/implement migrations ala Django (or maybe something better?) are welcome.

**Comment by coleifer** [comment]
@mekanix -- https://github.com/cam-stitt/arnold is one such project I'm aware of. I don't have plans for adding anything more than what is already present in the `playhouse.migrate` module. Perhaps you can bring this up on the mailing list? https://groups.google.com/group/peewee-orm
