### ISSUE TITLE
MyModel.DoesNotExist throws TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by amorphic** [coleifer/peewee#779]
Using Python 3.4.0 and Peewee 2.7.3 I am attempting to handle the case where MyModel.get() returns no results as [described in the docs](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.get). Something like:

```
try:
    user = User.get(User.username == 'charlie')
except User.DoesNotExist:
    print "No user found"
```
However this results in: `TypeError: exceptions must derive from BaseException`.

**Comment by amorphic** [comment]
Apologies... this had absolutely nothing to do with peewee.

**Comment by dpk** [comment]
What was the actual problem? I have a similar error.

**Comment by amorphic** [comment]
I honestly can't remember but I was doing something stupid which was unrelated to peewee.

The module I was working on is [here](https://github.com/re-3D/opengb/blob/master/opengb/database.py) in case it's useful.
