### ISSUE TITLE
RetryOperationalError mixin failing on retry w/ error 2006

### ISSUE THREAD

**Issue by bakemecookies** [coleifer/peewee#783]
Tried using the new RetryOperationalError mixin and although it's reaching the exception block properly (known because it's going to shortcuts.py, line 208, execute_sql), the retry fails and raises the same error.

My hunch is that since we're using PooledMySQLDatabase, could it be that we're closing one stale connection but just getting another stale one on the retry?  Not that it's necessarily a solution, but in the past we've used a combo of sql_error_handler to close stale connections and recursion on execute_sql (i.e., infinite retry only in the case of 2006 errors, as opposed to the single retry in RetryOperationalError) within its exception block to handle this.

**Comment by coleifer** [comment]
Unfortunately, I don't think I will be going back to the "sql error handler" API. I think the implementation in the `RetryOperationalError` mixin is an appropriate way to try to handle re-connect/re-try logic. Maybe you can make some changes to your pool implementation, particularly overriding the `_is_closed()` method to perform some sort of test to check that the conn is really active. Take a look at the pool module's code, particularly the `PooledMySQLDatabase._is_closed()` method...I bet you can find something that'll work for you.
