### ISSUE TITLE
how to use "insert ignore" sql in peewee?

### ISSUE THREAD

**Issue by pc10201** [coleifer/peewee#785]
how to use "insert ignore" sql in peewee?

**Comment by coleifer** [comment]
http://docs.peewee-orm.com/en/latest/peewee/api.html#InsertQuery.on_conflict

Please search the docs before posting tickets like this. Github tickets are more appropriate for **bugs**. If you have a question, post to stackoverflow, the mailing list, or the IRC channel. All of these are described in the documentation: http://docs.peewee-orm.com/en/latest/peewee/contributing.html
