### ISSUE TITLE
Support for triggers in DDL

### ISSUE THREAD

**Issue by macks22** [coleifer/peewee#786]
It would be very useful to be able to define triggers when using `create_table` to create database schemas. [I had this issue and came up with a very simple solution](http://stackoverflow.com/q/34142550/2486302). It fit my use case for a particular type of trigger using sqlite. However, based on my reading of the source, it didn't seem like supporting the full trigger API would be too difficult.

**Comment by coleifer** [comment]
You can use the fields constraints param to specify default values: DateTimeField(constraints=(SQL('default now'),))

I do not plan on supporting triggers at this time.

**Comment by macks22** [comment]
Got it; thanks for the constraints tip.
