### ISSUE TITLE
load csv into database - boolean values always convert to TRUE

### ISSUE THREAD

**Issue by adsahay** [coleifer/peewee#792]
While loading a csv with a boolean field into a db table, the boolean value is always converting to `TRUE`. 

Please find reproducible test case on this [gist](https://gist.github.com/adsahay/38d73837beccd560ad66).

Expected behaviour - `0` should map to `false`, `1` should map to `true`.

I have tried using `t/f`, `TRUE/FALSE` and `0/1` in the csv.

**Comment by coleifer** [comment]
You need to probably specify a custom `RowConverter` and override the `Loader.get_converter` method to appropriately handle your CSV data.

**Comment by coleifer** [comment]
You can pass in a custom converter using the `converter` parameter.

**Comment by adsahay** [comment]
I am trying the following (no luck):

```
    # use a custom RowConverter to handle boolean values, as it is not
    # handled out of the box.
    class CustomRowConverter(RowConverter):
        def field(field_class, **field_kwargs):
            def decorator(fn):
                fn.field = lambda: field_class(**field_kwargs)
                return fn

            return decorator

        @field(BooleanField, default=0)
        def is_boolean(self, value):
            # True if value is a boolean
            # ref: http://www.postgresql.org/docs/9.4/static/datatype-boolean.html
            print('is_boolean %s' % value)
            true_literals = ['TRUE', 't', 'true', 'y', 'yes', 'on', '1']
            false_literals = ['FALSE', 'f', 'false', 'n', 'no', 'off', '0']
            return value in true_literals or value in false_literals

        def get_checks(self):
            """Return a list of functions to use when testing values."""
            return [
                self.is_date, self.is_datetime, self.is_integer, self.is_float,
                self.is_boolean, self.default
            ]

    custom_converter = CustomRowConverter(database=database)
    try:
        load_csv(MyModel,
                 'file.csv',
                 converter=custom_converter)
    except Exception as e:
        app.logger.error('Exception while loading csv %s - %s' %
                         (e.__class__, e))
```

Can you please tell me where the problem is? I can't trigger the `is_boolean` check above.

**Comment by coleifer** [comment]
I put together a test-case and was able to verify that the custom converter could interpret a booleanfield. Maybe you can look at the new test-case and get some ideas on the implementation. It's a little bit of a crummy API, I definitely would like to take a crack at rewriting it in the future, but for now hopefully this helps.

**Comment by coleifer** [comment]
See: 58d0fcbb75faa6200ea63db11a4c43e304f39c73

**Comment by adsahay** [comment]
Thanks for this. I think if we supply a `model` instead of a `database` to the loader custom converter isn't working.
