### ISSUE TITLE
Proposal for create/destroy database

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#803]
There is a common use case of creating/destroying databases, for example when running tests.

Currently there is no support for automating detecting the source database and acting appropriately, for example;

```python
x = SqliteDatabase("file:/tmp/lala.sql", uri=True)
x.create_database() # this would create /tmp/lala.sql
x.destroy_database() # this would unlink /tmp/lala

x = SqliteDatabase(":memory:", uri=True)
x.create_database() # this would create in-memory db space
x.destroy_database() # this would close all connections, thus destroying DB space

x = MySQLDatabase(host='127.0.0.1', database='helloworld')
x.create_database() # this would execute "CREATE DATABASE helloworld;"
x.destroy_database() # this would execute "DROP DATABASE helloworld;"
```

I've got the majority of the above working for Sqlite, however I haven't done Postgres or MySQL yet.

If this was put forward as a well formed PR, would this sort of functionality be accepted into the core, or playhouse?

**Comment by coleifer** [comment]
I've always felt that this type of thing did not belong as a part of peewee. I will pass on this feature.

**Comment by foxx** [comment]
Got it, I'll put this into a separate repo, thanks for the quick reply!

**Comment by gitttt** [comment]
So there is no way to create a database using peewee, right?

**Comment by coleifer** [comment]
@gitttt -- just use the tool from your vendor. For sqlite you don't have to do anything, as it will create if not exists. For MySQL:

* https://dev.mysql.com/doc/refman/5.5/en/mysqladmin.html
* https://dev.mysql.com/doc/refman/5.5/en/create-database.html

For postgresql, use `createdb`: http://www.postgresql.org/docs/9.1/static/app-createdb.html

**Comment by gitttt** [comment]
ok, thanks

**Comment by savraj** [comment]
for future readers, the way I chose to do this (after ending up here) was this: 

```
    db = MySQLdb.connect(host='', user='', passwd='')
    c = db.cursor()
    c.execute("drop database %s" % db_name)
```
