### ISSUE TITLE
Adding table to existing db does not add unique constrant.

### ISSUE THREAD

**Issue by vincentdavis** [coleifer/peewee#807]
Existing SQLite DB defines and created by peewee.
Adding a new table, with a field that has unique=True.
The resulting table does not get the unique constrat added. In my case the line below is needed but not added. I had to remove the entire db to get peewee to add the table correctly.
The table had no ForeignKeyField. 

```sql
CREATE UNIQUE INDEX addresses_IdHash ON addresses (IdHash);
```

**Comment by coleifer** [comment]
How did you create the table, as in what method? You should have either called db.create_tables or model.create_table, but not db.create_table as this will not create indexes.

**Comment by vincentdavis** [comment]
I used db.create_table.
Thanks

**Comment by coleifer** [comment]
Yeah, it's an older API and can unfortunately cause some confusion... db.create_table() just creates the table. However create_tables() will create the tables for a number of models, resolving the foreign key dependencies to ensure a proper order of operations. Model.create_table() will just create the table and indexes for the model.
