### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gjedeer** [coleifer/peewee#808]
I have a problem that I can't figure out. Npm is a peewee model which I'm using like this:

    package = Npm.select().where(Npm.id==package_name)[0]

However peewee throws an exception which is not very meaningful:

![peewee](https://cloud.githubusercontent.com/assets/315648/12140463/7b0206a0-b468-11e5-986c-2c821ab43b59.png)

Any idea what I'm doing wrong or how this can be fixed in peewee code ?

**Comment by coleifer** [comment]
There is no object matching your query. Use .get() instead if you only need 1 object.
