### ISSUE TITLE
add DictField

### ISSUE THREAD

**Issue by alexpantyukhin** [coleifer/peewee#810]
Hello!
Is it possible to implement DictField (basing for example TextField)?
I need to store unstructed data in model and I think such feature would be useful.

**Comment by coleifer** [comment]
You can use the `PickledField`, added just now:

https://github.com/coleifer/peewee/blob/master/playhouse/fields.py#L293-L302

If you're using a new-ish version of Postgres you can use the JSON field or the HStore field.

If you're using a new-ish version of SQLite with the JSON1 extension compiled in or loadable, you can use the JSONField from the SQLite extension module.
