### ISSUE TITLE
Support for model mixins?

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#816]
Currently it's not possible to do the following;

```python
class BaseModelMixin(object):
    id = UUIDField(default=uuid1, primary_key=True, unique=True)

class BaseModel(BaseModelMixin, Model):
    pass

class User(BaseModel):
    pass
```

It's surprising behaviour that I can't construct models from a set of mixins, are there any plans to support this? If not, could you give some insight into why?

**Comment by yohanboniface** [comment]
@foxx, try with:
```
class BaseModelMixin(Model):
```

**Comment by coleifer** [comment]
@yohanboniface has it right.

**Comment by coleifer** [comment]
Additional nit, you don't need `unique=True` for a primary key.

**Comment by foxx** [comment]
Ahh okay, so the mixins have to have subclass `Model`, I'm guessing due to metaclass magic of some sort. Looks to be working now, thanks both :) (also will remove `unique=True`, ty)
