### ISSUE TITLE
cython compilation failing w/ python3.4

### ISSUE THREAD

**Issue by jherre** [coleifer/peewee#820]
Will update with more details as I find time.  Pinning to peewee 2.7 for now

```
  Running setup.py install for peewee
    Complete output from command /vagrant/.tox/py34/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gasvyut8/peewee/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mczyxnc7-record/install-record.txt --single-version-externally-managed --compile --install-headers /vagrant/.tox/py34/include/site/python3.4/peewee:
    running install
    running build
    running build_py
    running build_ext
    cythoning playhouse/speedups.pyx to playhouse/speedups.c
    building 'playhouse._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/vagrant/.tox/py34/include/python3.4m -c playhouse/speedups.c -o build/temp.linux-x86_64-3.4/playhouse/speedups.o
    playhouse/speedups.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef:
            set model_set = set(models)
            set seen = set()
            list accum = []
    
        for model in sorted(model_set, key=_sort_key, reverse=True):
                                                   ^
    ------------------------------------------------------------
    
    playhouse/speedups.pyx:318:48: Cannot convert 'tuple (object)' to Python object
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by jherre** [comment]
Python 3.4.3
Cython version 0.21.1
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)

**Comment by coleifer** [comment]
Try upgrading your Cython?

**Comment by coleifer** [comment]
Using Python 3.5 and Cython 0.23.4 no issues.

**Comment by jherre** [comment]
Using Python 3.4.3 and Cython 0.23.4 also no issues

**Comment by coleifer** [comment]
So that is to confirm that it works correctly after upgrading your Cython?

**Comment by smglab** [comment]
the same error
$ cython -V
Cython version 0.23.4
$ python -V
Python 2.7.6
`------------------------------------------------------------

...

    cdef:

        set model_set = set(models)

        set seen = set()

        list accum = []



    for model in sorted(model_set, key=_sort_key, reverse=True):

                                               ^

------------------------------------------------------------



playhouse/speedups.pyx:318:48: Cannot convert 'tuple (object)' to Python object

building 'playhouse._speedups' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/playhouse

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c playhouse/speedups.c -o build/temp.linux-x86_64-2.7/playhouse/speedups.o

playhouse/speedups.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.

 #error Do not use this file, it is the result of a failed Cython compilation.

  ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`
