### ISSUE TITLE
Using ArrayField w/ BinaryJSONField (PostgreSQL)

### ISSUE THREAD

**Issue by tantona** [coleifer/peewee#824]
I was unable to use these two postgres extensions in conjunction.  I scoured the internet for an answer but all I found was http://stackoverflow.com/questions/18099589/postgres-array-of-json-avoid-casting

My solution (which is a hack) was this 
```
def postgresJsonArrayString(array):
    return "".join(["{", ", ".join(["".join(["\"", json.dumps(m).replace('"', "\\\""), "\""])
                    for m in array]), "}"])
```

I realize it's gross but it does the job for now! I was going to circle back on this but at least this gets me back on track!

love this library - keep up the great work!

**Comment by coleifer** [comment]
Well...since JSON fields themselves can contain arrays, I'm not sure how crucial I feel it is to address this use-case. If peewee is not supporting this, then I'll just defer and mark this wontfix.
