### ISSUE TITLE
[Feature Req] Ability to order by column with NULL preference

### ISSUE THREAD

**Issue by alexlatchford** [coleifer/peewee#826]
Currently you can use the `order_by` metaclass property to assign default sort ordering. I have a requirement to be able to sort a column and also have it respect sort order for nulls, I've been looking through the docs and can't seem to find support for it so I'd like to propose a syntax for potentially adding the feature in lieu of a PR. Something like:

```
class MyModel(Model):
    start = DateTimeField(null=True)
    stop = DateTimeField(null=True)

    class Meta:
        order_by = (('-start', 'nulls'), ('nulls', '-stop'))
```

This extends the current syntax and uses it's tuple position to signify NULLS FIRST/LAST. I'm not 100% happy with it but it'll do the job for sure, let me know your thoughts.

PS. I'm using Postgres which supports this operation, not sure how the other supported databases handle this interaction, for reference: http://www.postgresql.org/docs/current/static/queries-order.html

**Comment by coleifer** [comment]
I do not plan on supporting that as a Meta option, but you can write a wrapper method on your model class that sorts the table correctly. You can pass arbitrary SQL nodes into order_by(), so:

MyModel.select().order_by(SQL('the_col nulls last'))

**Comment by alexlatchford** [comment]
Awesome! Thought it might be possible but wasn't sure how, thanks Charles for the answer :smile:
