### ISSUE TITLE
Support for sophisticated migrations

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#827]
As mentioned in [Peewee Docs][1];

> This engine provides the basis on which a more sophisticated tool could some day be built.

Other framework implementations, such as South and Django Migrations, are quite infuriating to use so I'd be interested to hear your thoughts on how such a tool would be constructed @coleifer.

Would this tool be within the scope of Peewee core or playhouse? If so, are there any plans on the roadmap to start working on such a tool? I can put a certain amount of time towards helping out with this, so if it needs volunteers then count me in.

[1]: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#schema-migrations

**Comment by coleifer** [comment]
I've always maintained the view that anything beyond the APIs currently available would be best suited for a third party package, and I believe maybe one or two such exist. Any type of automatic schema migrator seems like an invitation to disaster and will never be included as part of peewee.

**Comment by foxx** [comment]
Thanks for the quick reply, sounds good, I'll have a think about how this might be implemented as a third party module and will follow up for feedback at a later date.

**Comment by klen** [comment]
@foxx Have a look to https://github.com/klen/peewee_migrate
