### ISSUE TITLE
 too many clients already

### ISSUE THREAD

**Issue by strongant** [coleifer/peewee#829]
OperationalError: FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already

**Comment by foxx** [comment]
This just means your database is rejecting the connection because there are too many clients connected.

**Comment by coleifer** [comment]
I don't see how this is a peewee issue. Probably check your connection management code, maybe you're not properly closing connections.

In the future please provide some shred of useful information in a ticket, otherwise you're just wasting my time and yours.
