### ISSUE TITLE
Support for RethinkDB

### ISSUE THREAD

**Issue by foxx** [coleifer/peewee#832]
I'm looking at the possibility of adding support for [RethinkDB][1] into Peewee. It recently became stable and so far looks absolutely [amazing][2]. After looking at some of the other extensions in playhouse, this seems to be a straight forward task. However I'm struggling to decide what components should be abstracted, for example, there's a lot of functionality relating to [sharding/replication][3], which might make it difficult to use as a generic layer in Peewee. There's a cheat sheet [here][4] showing comparison of SQL to ReQL.

In my use case, I've built several modules with auditing and metrics capabilities, which are re-usable between applications. For some users, they might suffice with just using Postgres but in other situations like mine, these need to scale to billions of rows. If I was able to add support into Peewee for RethinkDB, then I can reduce the amount of database specific work (e.g. having to specifically add support for both Peewee and RethinkDB API).

Anyway I'd be interested to hear your thoughts on whether RethinkDB would be a suitable candidate for playhouse. I'll be working on a prototype in `peewee-extras` over the next month, so any thoughts/feedback/hints would be much appreciated. It will likely be another 6-8 weeks until `peewee-extras` is stable and clean with documentation though (it's still a building site at the moment!)

[1]: https://www.rethinkdb.com/
[2]: http://rob.conery.io/2015/04/17/rethinkdb-2-0-is-amazing/
[3]: https://www.rethinkdb.com/docs/sharding-and-replication/
[4]: https://www.rethinkdb.com/docs/sql-to-reql/javascript/

**Comment by coleifer** [comment]
Sure, a rethinkdb backend would be pretty neat!

**Comment by foxx** [comment]
Okay awesome, I'll let you know once I have something ready for review (an early preview would be appreciated, as you can spot any design flaws much sooner!)

**Comment by coleifer** [comment]
What's going on with this issue? You know, as I'm thinking about it, this would probably benefit from being a separate package. To that effect, I think I will close this out.

**Comment by foxx** [comment]
Apologies for the lack of replies on this, this was shelved in favour of getting some other functionality working first, however I do plan on coming back to this eventually. I'll create a separate package for this, and we can always consider merging it into playhouse at a later date.
