### ISSUE TITLE
Feauture proposal for playhouse: Option to store binary blobs in compressed form

### ISSUE THREAD

**Issue by shirish93** [coleifer/peewee#833]
Hello,

I've been working with peewee lately, and since my data is a lot of repeating text information, it's being compressed. It would seem that such a feature might be useful for everyday peewee users too, considering that most common compression algorithms have much shorter decompression times than compression times (and assuming that most peewee users do database reads more often than db writes).

Would such an addition be aligned with your vision of the project? If so, I would start working on it, and the unit tests. There might be a little guidance required with the internal workings of peewee, but besides that, not too much. Not sure if the proposal would fit with playhouse, or core peewee either.

Here's an example usage of the proposed feature:

During model definition:

`
myLargeContiguousString = BlobField(compressed= True)
`

for access:

`
Model.myLargeContiguousString.select().get()
`

would return a decompressed version.

I am not sure if returning raw compressed strings would be worth it, and it would be upon you to decide on the syntax for such a feature, but such a feature would be made available too, as per your decision.

A good documentation would be needed to tell people about the encodings and as such (my proposal: default to 'utf-8' unless they ask for something else), and that  they would gain the most by compressing only larger strings, etcetera, maybe even a choice between bz2 and zlib (both available in Python core) but that's about the design decisions I can think of. The work of writing up the documentation would obviously be on me, with your guidance.

Thoughts?

**Comment by coleifer** [comment]
You should check the `CompressedField`. It supports zlib and bz2.

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#CompressedField

**Comment by shirish93** [comment]
Oh dear! Totally missed out on that. Thanks!
