### ISSUE TITLE
Signal Support and Identifying Models

### ISSUE THREAD

**Issue by jimjkelly** [coleifer/peewee#835]
Hi - so I have a setup where I've abstracted my models out into a pip installable package so that they can be used in multiple places in my infrastructure.  This works great except when trying to get signals working.  Essentially, things aren't working because of the check here:

https://github.com/coleifer/peewee/blob/master/playhouse/signals.py#L39

Namely - the instance class is being referred to as `foo.Model` where as outside (i.e. when I wire up a signal handler and give it a sender) it's referred to as `models.foo.Model`.  Does that make sense?  If not I can try and put together a small example.

Given this problem - is it possible instead compare models by name?  Or is it not expected that those necessarily be globally unique?  Or is there something else obvious maybe I'm missing here to resolve that problem?

**Comment by coleifer** [comment]
This is not a peewee problem, but a problem with the way you're importing and managing your models.

Python loads your imported modules into memory and you're double-loading them (foo.Model and models.foo.Model). Python sees this as two different modules and in fact they are essentially two different models. What's scarier is you might have two different databases.... I'd strongly consider reorganizing your code as this type of bug can produce weird issues like the one you've posted.

**Comment by jimjkelly** [comment]
Given the way the models get configured I don't have to worry about two different databases, but I'll be a bit more vigilant about importing them the same way.  Thanks!
