### ISSUE TITLE
apsw and non integer PK

### ISSUE THREAD

**Issue by ronyb29** [coleifer/peewee#836]
the apsw driver currently returns the last [rowid](https://www.sqlite.org/c3ref/last_insert_rowid.html) instead of the las inserted PK, this causes problems for any non int pk (like a UUID)

**Comment by coleifer** [comment]
https://github.com/coleifer/peewee/pull/837#issuecomment-175938671

**Comment by coleifer** [comment]
I see the issue now. Normally, last_insert_id() checks first that the model has an auto incrementing pk.

```python
def last_insert_id(self, cursor, model):
        if model._meta.auto_increment:
            return cursor.lastrowid
```

This check is missing in the apsw driver, though. Apologies for the confusion on my part. The fix will just need to add this check to the apsw implementation.
