### ISSUE TITLE
Documentation Idea: Alternative way to using same model with multiple databases

### ISSUE THREAD

**Issue by shirish93** [coleifer/peewee#839]
Hey @coleifer , 

I've asked this question in the mailing list, but I believe I've come up with a more elegant idea to use a model with multiple databases. The user defines a Model, but encapsulates it in a function. The function takes the name of the database to be used, and returns the Model that uses the specified database. If this question comes up again, it might be worth it to point people in this direction.

Sample:
```
global dbName  #Put this dummy value here. It'll be overwritten anyway
def makeModel(dbName):
   global dNname
  class ModelName:
    #classDef goes here.

    class Meta:
      database = dbName

  return ModelName
```
To use it:

```
model_for_db1 = makeModel(dbName1)
model_for_db2 = makeModel(dbName2)

query = model_for_db1.select().where(model_for_db1.field_1 == 'value_1')
```

What is your view with regards to this? Please feel free to remove/close the issue if you feel this does not deserve to be in the 'issues' section. I had a particularly long process trying to find a way to make this work, so I imagine others might gain from it. : )-

Update 2: Added a global variable to fix it. It appears to work now.

Update 1: Doesn't work as expected. Any sort of specific query doesn't seem to work. I'll close the issue after further testing. Sorry for the false alarm.

**Comment by coleifer** [comment]
I don't mean to offend, but this is just basic Python. I don't think it's necessarily worth documenting, but thank you for sharing your thoughts on the issue.
