### ISSUE TITLE
Blog example: werkzeug error

### ISSUE THREAD

**Issue by rubensoleao** [coleifer/peewee#840]
When I run the blog, I randomly get this werkzeug error.

> Exception happened during processing of request from ('127.0.0.1', 38174)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
>     self.handle()
>   File "/home/lubens/Documents/CACIC/Site/blog/local/lib/python2.7/site-packages/werkzeug/serving.py", line 217, in handle
>     rv = BaseHTTPRequestHandler.handle(self)
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/home/lubens/Documents/CACIC/Site/blog/local/lib/python2.7/site-packages/werkzeug/serving.py", line 248, in handle_one_request
>     self.raw_requestline = self.rfile.readline()
> IOError: [Errno 11] Resource temporarily unavailable

Does someone know why that could be?

Thank you!

**Comment by rubensoleao** [comment]
I've noticed that this starts happening when I put youtube videos in my blog entries.

**Comment by coleifer** [comment]
I have no idea what the problem is, but the application itself is fine.

**Comment by ychen820** [comment]
hi , I have the same problem, using python 2.7 and it happens both using uwsgi or the flask built-in server

**Comment by Luqqk** [comment]
For me it happens only when I run app in debug mode. Try to run app without debug. @rubensoleao You're right - youtube videos in entries are related to this issue.
