### ISSUE TITLE
Support for MySQL STRAIGHT_JOIN

### ISSUE THREAD

**Issue by fmazan** [coleifer/peewee#842]
Would it be possible to somehow perform STRAIGHT_JOIN on MySQL tables due to its poor query optimizer except using raw SQL query?

The syntax according to [http://dev.mysql.com/doc/refman/5.7/en/join.html](http://dev.mysql.com/doc/refman/5.7/en/join.html) is:

> join_table:
>     table_reference [INNER | CROSS] JOIN table_factor [join_condition]
>   | table_reference STRAIGHT_JOIN table_factor
>   | table_reference STRAIGHT_JOIN table_factor ON conditional_expr
>   | table_reference {LEFT|RIGHT} [OUTER] JOIN table_reference join_condition
>   | table_reference NATURAL [{LEFT|RIGHT} [OUTER]] JOIN table_factor

**Comment by coleifer** [comment]
Just do this:

```python
from peewee import *
JOIN['STRAIGHT'] = 'STRAIGHT'

my_query = SomeObj.select().join(SomeOther, JOIN.STRAIGHT)
```

**Comment by vyktor90** [comment]
This doesn't work anymore in version 3, due to:


```
class Join(BaseTable):
...
    def __sql__(self, ctx):
        (ctx
         .sql(self.lhs)
         .literal(' %s JOIN ' % self.join_type)
         .sql(self.rhs))
        if self._on is not None:
            ctx.literal(' ON ').sql(self._on)
        return ctx
```

**Comment by coleifer** [comment]
Are you sure about that? Seems to work for me:

```python

In [1]: from peewee import *

In [2]: JOIN['STRAIGHT'] = 'STRAIGHT'

In [3]: class Foo(Model):
   ...:     pass
   ...: 

In [4]: class Bar(Model):
   ...:     foo = ForeignKeyField(Foo)
   ...:     

In [5]: query = Bar.select().join(Foo, JOIN.STRAIGHT)

In [6]: query.sql()
Out[6]: 
('SELECT "t1"."id", "t1"."foo_id" FROM "bar" AS "t1" STRAIGHT JOIN "foo" AS "t2" ON ("t1"."foo_id" = "t2"."id")',
 [])

```

**Comment by fmazan** [comment]
The problem is that the STRAIGHT_JOIN is written with an underscore, it's not space separated. Oh well, those MySQL quirks...

**Comment by coleifer** [comment]
Yeah, the code doesn't seem to support that very well...going to leave as wontfix for now.
