### ISSUE TITLE
Support for `flat` tuples

### ISSUE THREAD

**Issue by alexanderad** [coleifer/peewee#843]
While working with peewee we often query database for a bunch of records on a single field and it is handy in this case to have a flat, chained resultset (functionality similar to [values_list(flat=True)](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#values-list))

So instead of having
```python
>>> User.select(User.id).tuples()
[(1,), (2, ), (3, )]
```
I imagine this could be expressed in API like:
```python
>>> User.select(User.id).tuples(flat=True)
[1, 2, 3, 4, ...]
```

Can we consider having this on board, @coleifer? I'd work on corresponding PR if this fits the design.

/cc @stas

**Comment by messense** [comment]
You can use ``more_itertools`` to flatten that.

```python
In [1]: import more_itertools

In [2]: l = [(1,), (2, ), (3, )]

In [3]: list(more_itertools.flatten(l))
Out[4]: [1, 2, 3]
```

**Comment by alexanderad** [comment]
I can use `itertools` as well (which is part of stdlib contrary to `more_itertools`), but this is not a question _how_ to do that:
```python
In [4]: list(itertools.chain(*[(1,), (2, ), (3,)]))
Out[4]: [1, 2, 3]
```
This is rather a convenient shortcut.

**Comment by coleifer** [comment]
I'm going to pass on this feature, as it is fairly easy to implement on your own. If you really want, instead of a list of row tuples, a list of scalar values - then you can write either `map(query, operator.itemgetter(0))` or something similar.

**Comment by kevart** [comment]
+1, programmers are lazy
