### ISSUE TITLE
ALTER_COLUMN with MariaDB

### ISSUE THREAD

**Issue by ptbrowne** [coleifer/peewee#850]
Hi,

I am using MariaDB (10.1.10 released on 2015-12.24) and peewee 2.8.0 and I am having trouble with a migration.

```python
no_newsletter = BooleanField(default=False)
migrator.add_column(
     'user', 'user_no_newsletter', no_newsletter),
)
```

The SQL issued is:

```
('ALTER TABLE `user` ADD COLUMN `user_no_newsletter` BOOL', [])
('UPDATE `user` SET `user_no_newsletter` = %s', [False])
('ALTER TABLE `user` ALTER COLUMN `user_no_newsletter` SET NOT NULL', [])
```

And I get this error for the last query:

```
peewee.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL' at line 1")
```

I had success by manually changing the request to

```
('ALTER TABLE `user` MODIFY `user_no_newsletter` BOOLEAN NOT NULL', [])
```

Relevant MariaDB docs: https://mariadb.com/kb/en/mariadb/alter-table/

It seems that in MariaDB, ALTER COLUMN cannot be used to enforce NOT NULL on a column.

I am no expert nor in peewee nor in MariaDB so it may be me that is making a mistake somewhere.

Thanks for peewee !

**Comment by coleifer** [comment]
That's odd, are you using the `MySQLMigrator`? The `add_not_null()` method appears to be using the "MODIFY" syntax.

**Comment by ptbrowne** [comment]
My bad... That was it >< Thanks
