### ISSUE TITLE
Postgresql Foreign key Migrations fail to rename columns

### ISSUE THREAD

**Issue by Hendler** [coleifer/peewee#851]
First, thanks for peewee. 

I've tried to include relevant bits for this example. Maybe I'm doing something wrong.

```
import basemodel
from peewee import CharField, DateTimeField, BigIntegerField, BooleanField, IntegerField, ForeignKeyField, Proxy, TextField, PrimaryKeyField
from playhouse.postgres_ext import BinaryJSONField, ArrayField
from playhouse.migrate import PostgresqlMigrator
from playhouse.migrate import migrate as mm
mdb = basemodel.dbfactory()
migrator = PostgresqlMigrator(mdb)

def migration_wrapper(*args):
    with mdb.transaction():
        mm(*args)


    migration_wrapper(
        migrator.add_column('blogpost', 'user', ForeignKeyField(User, related_name='posts', index=True, null=True, to_field=User.id))
)

```

This creates a column called `user`. The model file also has this field, as "user". BUT using create_table would create a column named `user_id`.
So, future inserts fail
```
post = BlogPost()
post.user = User.get(id=user_id)
post.save() # <- column not found

```
probably unrelated to #474 ?

**Comment by coleifer** [comment]
Peewee uses the convention that foreign key columns end with "_id". No bug. Either change your migration to use user_id as the column, or in your field on the model specify db_column='user'

**Comment by Hendler** [comment]
Thanks I got confused by the create_table and column specific operations.
