### ISSUE TITLE
old SQLite3 has no sqlite3_compileoption_used function

### ISSUE THREAD

**Issue by gilchris** [coleifer/peewee#852]
If installed SQLite3 version is less than 2.6.23, [BerkeleyDatabase.check_libsqlite() function in berkeleydb.py](https://github.com/coleifer/peewee/blob/master/playhouse/berkeleydb.py#L102) raise AttributeError.

sqlite3_compileoption_used function in SQlite is added on 2.6.23. [link](https://www.sqlite.org/releaselog/3_6_23.html)

**Comment by coleifer** [comment]
That's one old ass sqlite.
