### ISSUE TITLE
Possibility to see what changes with a save?

### ISSUE THREAD

**Issue by kramer65** [coleifer/peewee#854]
Let's say I've got a `User` model from which I start a new record as follows:
```
u = User()
u.username = 'bob'
u.location = 'home'
u.save()
```
I now use the same user instance and write two values of which one is the same:
```
u.username = 'bob'  # stays the same
u.location = 'work'  # changes
u.save()
```
When saving the updated values, is there a way with Peewee to know which of the values changed (i.e.: `location`), without actually comparing them with the existing values?

Ive got a model with about 50 fields to which I simply save the values of a json object. It would be so much easier if I could get the differences, instead of me needing to compare all those 50 values manually.

**Comment by coleifer** [comment]
Well, peewee knows that you set attributes so those are stored in the `dirty_fields` attribute. But there's no checking to see if it differed from the previous value. Any additional logic will have to live in your app itself.

**Comment by coleifer** [comment]
You can do `model.save(only=model.dirty_fields)`, if you just want to save those that were "set", but it doesn't track actual changes to the underyling value.

**Comment by kramer65** [comment]
Alright thanks. In that case I will need to build something myself.

Thanks!

**Comment by gwillem** [comment]
Why wouldn't peewee check whether values have actually changed? Speed?
