### ISSUE TITLE
Add support for additional connect args as query string in db_url

### ISSUE THREAD

**Issue by RealSalmon** [coleifer/peewee#858]
I'm happy to take a stab at this, but I thought it best to first propose it prior to spending any time . . . 

When using playhouse.db_url for connections, it is not currently possible to include additional connect args directly in the connection string. These must instead be supplied as separate keyword args.

```python
connect('mysql+pool://user:passwd@ip:port/my_db', max_connections=20, stale_timeout=300)
```

It would be nice to get those extra connection arguments directly from the connection string itself

```python
# DATABASE_URL has mysql+pool://user:passwd@ip:port/my_db?max_connections=20&stale_timeout=300
connect(os.environ['DATABASE_URL'])
```

Thoughts?

**Comment by coleifer** [comment]
Yes!

**Comment by RealSalmon** [comment]
Great, I'll start messing around with this evening (real life permitting . . . ).

**Comment by tomako** [comment]
That's cool but how could we set False (eg. register_hstore) via url? Should parse the query string with `keep_blank_values=True`, right?
