### ISSUE TITLE
RHEL python 3.4 Unable to create SQLITE db

### ISSUE THREAD

**Issue by sripathivenky** [coleifer/peewee#864]
Keep running into 

> Traceback (most recent call last):
>   File "db_test.py", line 2, in <module>
>     from playhouse.sqlite_ext import SqliteExtDatabase
>   File "/home/srujan/pyats/pyats/lib/python3.4/site-packages/playhouse/sqlite_ext.py", line 74, in <module>
>     FTS_VER = sqlite3.sqlite_version_info[:3] >= (3, 7, 4) and 'FTS4' or 'FTS3'
> AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'
> 

Upgraded the sqlite3 version to : 3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f 

from peewee import *
from playhouse.sqlite_ext import SqliteExtDatabase
import datetime

db = SqliteExtDatabase('my_database.db')

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    username = CharField(unique=True)

class Tweet(BaseModel):
    user = ForeignKeyField(User, related_name='tweets')
    message = TextField()
    created_date = DateTimeField(default=datetime.datetime.now)
    is_published = BooleanField(default=True)

**Comment by coleifer** [comment]
No idea, but somehow your install isn't finding a python sqlite driver.
