### ISSUE TITLE
Documentation, code example for webapp2

### ISSUE THREAD

**Issue by onel** [coleifer/peewee#865]
I know webapp2 is mainly used with app engine, but I started using it ouside of GAE and with peewee.
You can add the documentation for the db opening, closing on each request

```python
class BaseHandler(webapp2.RequestHandler):

    def dispatch(self):

        db.connect()
        
        try:
            # Dispatch the request.
            webapp2.RequestHandler.dispatch(self)
        finally:
            if not db.is_closed():
                db.close()
```

**Comment by coleifer** [comment]
Going to pass as this is a pretty obscure framework.

**Comment by savraj** [comment]
We use this framework (webapp2) with peewee.  We never call connect() or close(). Is that bad?

**Comment by coleifer** [comment]
@savraj -- Probably... I don't know webapp2, but my guess is that you aren't getting the concurrency you think you might be if you're running in certain types of environments.

If you're using a webapp, my opinion is that you should always open a conn upon receiving a connection and close it afterwards. You *can* use a connection pool if you get a lot of traffic, but that's how I would do things.
