### ISSUE TITLE
http://www.peewee-orm.com/ gives "Not found."

### ISSUE THREAD

**Issue by kramer65** [coleifer/peewee#867]
Although I know the docs can be found at http://docs.peewee-orm.com/ , it looks pretty crappy if the root of a website gives an Error.

Maybe it would be good to redirect http://www.peewee-orm.com/ to http://docs.peewee-orm.com/

Cheers!

**Comment by coleifer** [comment]
Actually it used to do that so I was surprised by your note. I went in and looked at the nginx config and realized I hadn't updated it for when I removed Varnish from my site. The redirects should be working now. Thank you!
