### ISSUE TITLE
Query Error using APSW 

### ISSUE THREAD

**Issue by mox1** [coleifer/peewee#872]
When using the apsw_ext module, I receive the following error when performing queries:
```
>>> x = SomeModel.select().where(SomeModel.col1 == "test").exists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "peewee.py", line 2896, in exists
    return bool(clone.scalar())
  File "peewee.py", line 2653, in scalar
    row = self._execute().fetchone()
AttributeError: 'apsw.Cursor' object has no attribute 'fetchone'
```

I see references in older versions of the code implementing a 'fetchone()' that calls next(), because APSW isn't DB-API compliant. Somewhere this code appears to have been re-factored out. 

This is using the trivial example model from the Docs
```
db = APSWDatabase(':memory:')

class BaseModel(Model):
    class Meta:
        database = db

class SomeModel(BaseModel):
    col1 = CharField()
    col2 = DateTimeField()
```

python 2.7.6 On Ubuntu 14.04
Using peewee 2.8.0 (git rev 4c1db1399c0906ea3ac59448fa4a333e813098fa)
Using python-apsw 3.8.2-r1-1ubuntu1

**Comment by coleifer** [comment]
0e055df5317e9966831b760a5a2aa8990f759207

**Comment by coleifer** [comment]
Thank you for the excellent bug report, this should now be fixed.

**Comment by coleifer** [comment]
You may need to update your apsw version, because in the latest versions it *does* support `fetchone()`. I had to revert my commit that fixed the issue, due to MySQL python driver not implementing the iterator protocol on its cursor... Anyways, just try upgrading apsw and you should be set!
