### ISSUE TITLE
Create type

### ISSUE THREAD

**Issue by IxDay** [coleifer/peewee#875]
As I use custom types, is there a way to perform this in peewee or do I have to add a create_type method in the QueryCompiler class? If so, are you interested in the implementation of this feature ?

Here is an example of the code I use

```sql
CREATE TYPE direction AS (title varchar(50), text text);
```

**Comment by coleifer** [comment]
Unfortunately, you'll need to call `register_fields` to use custom types:

```python
class DirectionField(...):
    db_type = 'direction'

PostgresqlDatabase.register_fields({
    'direction': 'direction',
})
```

Hope to get rid/clean-up that boiler plate in a later version of peewee but for now it is required.
