### ISSUE TITLE
default_index cannot be None in IndexedFieldMixin

### ISSUE THREAD

**Issue by IxDay** [coleifer/peewee#876]
As in the constructor we setup the index like this: 
https://github.com/coleifer/peewee/blob/master/playhouse/postgres_ext.py#L129

```python
self.index_type = index_type or self.default_index_type
```

I cannot specify at Field declaration that I do not want any index, as if I explicitly define `index_type` to be None it will be overridden by the previous line.

I think a better way to handle this can be to wrote the code like this:

```python
class IndexedFieldMixin(object):

    def __init__(self, index_type='GiST', *args, **kwargs):
        kwargs.setdefault('index', True)  # By default, use an index.
        super(IndexedFieldMixin, self).__init__(*args, **kwargs)
        self.index_type = index_type

class ArrayField(IndexedFieldMixin, Field):

    def __init__(self, field_class=IntegerField, dimensions=1, index_type='GIN',
                 *args, **kwargs):
        self.__field = field_class(*args, **kwargs)
        self.dimensions = dimensions
        self.db_field = self.__field.get_db_field()
        super(ArrayField, self).__init__(*args, **kwargs)

...
```

**Comment by coleifer** [comment]
This is fixed by 2fca64c482f536f280303a77fe8e9c040a0c96b3

To indicate that there should be no index, simply specify `index=False` when instantiating your `ArrayField`.

**Comment by coleifer** [comment]
(the same goes for any other field that mixes in `IndexedFieldMixin`.)

**Comment by IxDay** [comment]
Great thanks !

**Comment by coleifer** [comment]
Thanks for reporting the issue, I appreciate it!
