### ISSUE TITLE
Playhouse speedups

### ISSUE THREAD

**Issue by stanep** [coleifer/peewee#877]
Hi, using a new peewee (2.8.0) (pip install -U peewee) I got compiled playhouse._speedups file.
Now I am using SQL Server 2012 and pyodbc with peewee and so far it works but when I install latest version I got error running simple select statements.

File "\playhouse\speedups.pyx", line 179, in playhouse._speedups._QueryResultWrapper.iterate (playhouse\speedups.c:3690)
TypeError: expected tuple, got pyodbc.Row

If I rename _speedupds file I peewee works , so not sure if this is a bug, but maybe you can do
something so speedups will work with pyodbc :)

**Comment by coleifer** [comment]
Just pass `use_speedups=False` when you are instantiating your Database object. That should address the issue. Peewee implements some cursor iteration helpers in Cython and expects the rows to be tuples, hence the issue you're seeing.

Let me know if the above fix addresses the problem.

**Comment by stanep** [comment]
Yes this fix the problem, thx
