### ISSUE TITLE
What is the reason to use keyword argument in positional style?

### ISSUE THREAD

**Issue by kiddick** [coleifer/peewee#891]
https://peewee.readthedocs.org/en/2.0.2/peewee/cookbook.html#using-with-postgresql

```python
psql_db = PostgresqlDatabase('my_database', user='code')
```

Isn't 

```python
psql_db = PostgresqlDatabase(database='my_database', user='code')
```

better?

I understand that that is matter of taste. But it's kind of official docs.

**Comment by coleifer** [comment]
No, it's not better. It's just that you think it's better.
