### ISSUE TITLE
Create makes table, but no columns

### ISSUE THREAD

**Issue by Neotric** [coleifer/peewee#892]
Hello,
Tried my first steps with peewee, looks good, but....
I did a create_table(mytable), the table was created, but none of the defined columns in the class mytable. I want three columns, all CharField(). I only get an column "id" INTEGER NOT NULL PRIMARY KEY. On data insertion rows are created with one column ("id"), but no other data.
Who can help me ? What is going wrong ?

**Comment by coleifer** [comment]
I am positive there is a bug in your code somewhere. I'd suggest posting on stackoverflow and INCLUDE YOUR MODEL DEFINITION and code you're using to create the table. That'll help get the problem fixed the fastest.

This page is for tracking bugs with peewee and creating tables is covered extensively by tests.
