### ISSUE TITLE
How do I update a foreign key directly?

### ISSUE THREAD

**Issue by maaaks** [coleifer/peewee#895]
This doesn't seem to work:

```python
model.relatedmodel_id = 1
```

**Comment by coleifer** [comment]
Fixed, thanks for reporting.

**Comment by coleifer** [comment]
For what it's worth you can always set the actual foreign key field to an integer ID:

```python
model.relatedmodel = 1
```

**Comment by ibushong** [comment]
This is great. It always seemed odd to me to assign an integer to an attribute that really should be an object.

Does this change also allow creating and querying via the same identifiers? e.g.

`Foo(relatedmodel_id=1)`

or

`Foo.select().where(Foo.relatedmodel_id == 1)`

**Comment by coleifer** [comment]
At the moment creation is supported, but for querying you will still need to use the foreign key field itself. And honestly, I don't think I'll change it.

**Comment by ibushong** [comment]
Ok thanks.

Somewhat related: Is there any reason accessing a non-existent field doesn't issue an error/warning. I've spent a decent amount of time tracking down issues that end up being due to using an incorrect field name, e.g.:

```python
# Incorrect
User.select().where(User.city_id == 1)  # This looks valid to me, but will result in the wrong query (with no error/warning)
User.create(city_id=1)  # This one works as of 2.8.1, but previously I'd end up scratching my head over why the city_id field wasn't getting set
```

**Comment by coleifer** [comment]
That should raise an exception, I will reopen.

**Comment by ibushong** [comment]
Cool. Thanks! And just to clarify, the second case can still occur with other values, e.g.
```python
# These "work", but I would expect an exception
user = User.create(non_existent_field=44)
user = User(non_existent_field=235)
```

**Comment by coleifer** [comment]
I actually decided to go ahead and support querying on the `xxx_id` field.
