### ISSUE TITLE
Is it possible to do a coalesce with peewee?

### ISSUE THREAD

**Issue by KrisSiegel** [coleifer/peewee#898]
I have 3 fields that I want to return as one field (2 of the 3 will *always* be NULL so I only want the one with a value) but I haven't been able to find any documentation that shows a way to handle this in PeeWee. Am I missing something?

**Comment by coleifer** [comment]
Yep, it's possible.

e.g.:

```python
SomeModel.select(fn.COALESCE(SomeModel.field_a, SomeModel.field_b).alias('the_value))
```

**Comment by KrisSiegel** [comment]
Thanks, didn't see that in the documentation anywhere.

**Comment by coleifer** [comment]
It's described here:

http://docs.peewee-orm.com/en/latest/peewee/querying.html#sql-functions-subqueries-and-raw-expressions

**Comment by KrisSiegel** [comment]
That doesn't actually mention coalesce only that you can *"use arbitrary SQL functions"* but how do I know which functions are supported through PeeWee? Or do they *only* map directly back to the database I have setup? For instance not every DB has ISNULL.

If the documentation was a little more clear either way it would be helpful. I think it would be nice to list all functions available across all databases versus what's available for individual ones. Or at least the verified working through PeeWee functions.

**Comment by coleifer** [comment]
Literally the third sentence:

> To use arbitrary SQL functions, use the special fn() object to construct queries:

You can call literally any function, whether it exists or not. It's just syntactic sugar, read the code to get an understanding of how it works. You can nest calls to functions, you can do whatever.

> I think it would be nice to list all functions available across all databases versus what's available for individual ones.

That's stupid. Why would I do that? Read your database documentation, no sense in duplicating it.

**Comment by KrisSiegel** [comment]
> Literally the third sentence:

You and I both made reference to that passage and it doesn't address my specific statement so I'm not sure what you gain by reiterating a point we've both talked about. Regardless...

> That's stupid. Why would I do that?

So my comment already addressed the why. But if you think the suggestion is stupid I can't tell if you just ignored my 'whys' or you want other 'whys' without addressing my original ones. Regardless this doesn't sound like a productive conversation so no need to continue it.

**Comment by coleifer** [comment]
The word *arbitrary* means *any* in the sentence I referenced. Meaning there's no need to duplicate other database vendors documentation since Peewee can call literally any function. The `fn` object creates a `Function` instance that the query compiler turns into a function call in SQL. Peewee doesn't have to know any more than that.

**Comment by ak04nv** [comment]
@KrisSiegel 
> I think it would be nice to list all functions available across all databases versus what's available for individual ones.

What about [personal functions](http://www.postgresql.org/docs/9.5/static/sql-createfunction.html)? ;-)

**Comment by skatenerd** [comment]
FWIW I got here by googling "peewee coalesce".  I started developing using Peewee without reading the docs end-to-end, so this issue helped me.

**Comment by seanballais** [comment]
@skatenerd, interestingly, we're just exactly a month apart in using this issue to figure out how to use a `COALESCE` in Peewee.

**Comment by jiamo** [comment]
How about none value but need retuen empty array?  Neither ` fn.COALESCE(SomeModel.array, SQL('{}'))` nor ` fn.COALESCE(SomeModel.array, '{}')` can do it

**Comment by coleifer** [comment]
What happens when you try to do that?

**Comment by jiamo** [comment]
A field have array type. But can be `null`. When it is `null`. I want to return empty array. (One way I know:  I can make a default empty value  for the field, I just want to know how can select by peewee)

**Comment by coleifer** [comment]
I will repeat myself:

What happens when you try to do that @jiamo?

You said neither option worked. In what way?

**Comment by jiamo** [comment]
1. Sorry.  I forgot append `alias` after `fn.COALESCE(SomeModel.array_field, '{}')`  such like `fn.COALESCE(SomeModel.array_field, '{}').alias("array_field")` .  And  I use such `Class(**row) ` to create schema object. The result will be `None`.  So no problem now.  
2. neither option worked. Add default value in database.

**Comment by coleifer** [comment]
>neither option worked.

In what way?

**Comment by jiamo** [comment]
When I have mistake. Both `fn.COALESCE(SomeModel.array, SQL('{}'))` and `fn.COALESCE(SomeModel.array, '{}')`  can't work. ` SQL('{}')` are my neither option.  Now they can both work after append `alias`.
