### ISSUE TITLE
Can I define a default ORDER BY for a relationship?

### ISSUE THREAD

**Issue by maaaks** [coleifer/peewee#900]
I want something like this:

```python
child = ForeignKeyField(Parent, related_name="children", default_order_by="birthday")
```

**Comment by coleifer** [comment]
Your example foreign key definition doesn't make much sense...why would the foreign key be called "child" when it points at a Parent? I'm just going to assume this is a meaningless example...

At any rate, you can always just do:

```python
class Category(Model):
    parent = ForeignKeyField("self", related_name="children_backref")

    @property
    def children(self):
        return self.children_backref.order_by(Category.name)
```
