### ISSUE TITLE
Migration to change CharField max_length

### ISSUE THREAD

**Issue by josefdlange** [coleifer/peewee#901]
The title says the most of it. I'm using `arnold` for migrations on my PostgreSQL database, and I think I'd want to do something like: 

```
def up():
    config.DB.execute_sql("SOME arbitrary SQL to MODIFY column;")

def down():
    config.DB.execute_sql("OPPOSITE of ABOVE SQL code;")
```

Does that sound about right? I don't see any first-class features for changing the size of a Postgres VARCHAR.

**Comment by coleifer** [comment]
Indeed, for that you will need to probably consult the postgres manual for the correct SQL.  Peewee handles most things, but this is one of the ones it doesn't.
