### ISSUE TITLE
Polymorphic relationships

### ISSUE THREAD

**Issue by smilledge** [coleifer/peewee#903]
Does peewee support polymorphic relationships?

Would be awesome to have something similar to what is provided by Laravel and Rails:
https://laravel.com/docs/5.1/eloquent-relationships#polymorphic-relations
http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by arikfr** [comment]
It's named Generic Foreign Keys. Check the Playhouse docs.

**Comment by smilledge** [comment]
Didn't see that, thanks!

**Comment by coleifer** [comment]
Thanks @arikfr ! @smilledge feel free to reply if you have follow-up questions.

**Comment by wonderbeyond** [comment]
I've made a simple generic foreign key implementation: https://gist.github.com/wonderbeyond/0e1f402b7595e0b4f9f653260fed029c#file-index-md
