### ISSUE TITLE
NoneType error when deleting an instance with multiple null foreign keys

### ISSUE THREAD

**Issue by Vesuvium** [coleifer/peewee#906]
peewee raises a NoneType error when deleting an instance with multiple null foreign keys, e.g.:

    Schools(Base):
        id = PrimaryKeyField(primary_key=True)
        name = CharField()

    Parent(Base):
        id = PrimaryKeyField(primary_key=True)
        name = CharField()

    Children(Base):
        id = PrimaryKeyField(primary_key=True)
        parent = ForeignKeyField(Parents, null=True)
        school = ForeignKeyField(Schools, null=True)
        age = IntegerField()

Then

    somechild = Children(age=12)
    somechild.save()
    ...
    somechild.delete_instance()

Will result in this:

     def delete_instance(self, recursive=False, delete_nullable=False):
        if recursive:
            dependencies = self.dependencies(delete_nullable)
            for query, fk in reversed(list(dependencies)):
                model = fk.model_class
                if fk.null and not delete_nullable:
                    model.update(**{fk.name: None}).where(query).execute()
                else:
                    model.delete().where(query).execute()
        >return self.delete().where(self._pk_expr()).execute()
        TypeError: 'NoneType' object is not callable

I was going to post this on Stackoverflow, but then I've seen that getattr(somechild, 'delete') returns None.

I am using peewee 2.8.0 on python 3.4.3

**Comment by coleifer** [comment]
Pushed a testcase... It passed locally on py2.7 with sqlite, so we'll see what's up.

**Comment by Vesuvium** [comment]
I found what's happening. My model has a nullable 'delete' field and that overwrites the delete method.
