### ISSUE TITLE
Please support cockroachdb

### ISSUE THREAD

**Issue by jet10000** [coleifer/peewee#912]
https://www.cockroachlabs.com/

**Comment by coleifer** [comment]
Peewee should work with any Python DB-API 2.0 driver. It looks like work has started on adding one for cockroachdb:

https://github.com/cockroachdb/cockroach-python/pull/12

After that, follow the instructions here to integrate with Peewee:

http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver
