### ISSUE TITLE
Genarated query problem

### ISSUE THREAD

**Issue by monkeykju** [coleifer/peewee#913]
I do deleted query on Relationship table

`
query = Relationship.delete().where(Relationship.video == video)
`

<class 'libs.basemodel.Relationship'> DELETE FROM "relationship" WHERE ("video_id" = (SELECT "t2"."id" FROM "video" AS t1 WHERE ("t1"."name" = ?) ORDER BY "t1"."add_date" DESC)) [u'v5.mp4']

Problem:
OperationalError: no such column: t2.id

My models very simple:

```
class BaseModel(Model):
    class Meta:
        database = database

class User(BaseModel):
    username` = CharField(unique=True)
    password = CharField()
    email = CharField()
    join_date = DateTimeField()

    class Meta:
        order_by = ('username',)

class Relationship(BaseModel):
    video = ForeignKeyField(User, related_name='relationships')
    to_user = ForeignKeyField(User, related_name='related_to')
    class Meta:
        indexes = (
            # Specify a unique multi-column index on from/to-user.
            (('video', 'to_user'), True),
        )

class Video(BaseModel):
    name = CharField(unique=True)
    width = IntegerField()
    height = IntegerField()
    step = IntegerField()
    frame_count = IntegerField()
    add_date = DateTimeField()

    class Meta:
        order_by = ('-add_date',)
```

**Comment by coleifer** [comment]
Please fix the formatting of code.

**Comment by monkeykju** [comment]
Sorry, i've updated code formatting.

**Comment by coleifer** [comment]
To fix this I believe if you explicitly select the Video ID column you'll be set:

```python
video = Video.select(Video.id).where(Video.name == 'v5.mp4')
query = Relationship.delete().where(Relationship.video == video)
print query
```

Outputs:

```sql
DELETE FROM "relationship" 
WHERE ("video_id" = (
  SELECT "t1"."id" 
  FROM "video" AS t1 
  WHERE ("t1"."name" = ?) 
  ORDER BY "t1"."add_date" DESC
))
```

If you've already got the query from somewhere else and want to modify the SELECT clause, you can do:

```python
query = Relationship.delete().where(Relationship.video == video.select(Video.id))
```

------------------------

An unrelated suggestion:

Never ever ever specify a default ordering for your models. It's a code smell and I regret building it into Peewee's API (the idea comes from Django originally, and the Django community seems to feel the same way about it). If you want a default ordering that's easily accessible, just do something like:

```python
class Video(BaseModel):
    # ... fields ...

    @classmethod
    def all(cls):
        return cls.select().order_by(cls.add_date.desc())

-----

videos = Video.all()
```
