### ISSUE TITLE
Sqlite datetime with timezone is not converted into datetime

### ISSUE THREAD

**Issue by goir** [coleifer/peewee#914]
If you store a timezone aware datetime in sqlite the selected value is a unicode and not a datetime object.

```
import datetime

import pytz
from peewee import SqliteDatabase, PrimaryKeyField, DateTimeField, Model

db = SqliteDatabase('test.db')


class ModelA(Model):
    id = PrimaryKeyField()
    date = DateTimeField()

    class Meta(object):
        database = db

ModelA.create_table(True)

ModelA.create(date=datetime.datetime.now(pytz.UTC))
ModelA.create(date=datetime.datetime.now())

for a in ModelA.select():
    print a.date, type(a.date)
```

which returns

```
2016-04-20 07:06:18.021696+00:00 <type 'unicode'>
2016-04-20 09:06:18.420155 <type 'datetime.datetime'>
```

the unicode should be a datetime object with timezone set.

**Comment by coleifer** [comment]
SQLite will store timezone info, but I'm not sure what facilities it provides for sorting when you've got a mixture of timezones (without involving various date functions). You'll probably want to read up on it here: https://www.sqlite.org/lang_datefunc.html -- It might be more convenient to convert to UTC in your application before passing ot the database.

That said, it does seem like peewee should handle the timezone. For now you can subclass the `DateTimeField` and override the formats class attribute.

I'll look into a fix.

**Comment by goir** [comment]
I agree, its not really an issue, more a feature request to have a timezone aware datetime field.

**Comment by coleifer** [comment]
I don't believe I will implement this. If you want to register your own adapter at the driver level, or if you want to implement your own TZ-aware sqlite datetime-field, then I think that'd be the best course. A general purpose solution, though, I'm going to pass on.
