### ISSUE TITLE
Extra Parenthesis

### ISSUE THREAD

**Issue by stanep** [coleifer/peewee#926]
Hi if I have query like this
qr = Cwle.select(Cwle.WaitlistEntryID).filter(
                  (Cwle.WaitlistEntryID == 1) & (Cwle.WaitlistEntryID == 4)
                 )

print qr , will give you 

SELECT CWLE.WaitlistEntryID FROM WCPRDDB1.dbo.CardiacWaitListEntry AS CWLE WHERE ((CWLE.WaitlistEntryID = ?) AND (CWLE.WaitlistEntryID = ?)) [1, 4]

Is it possible to remove outer Parenthesis?

SELECT CWLE.WaitlistEntryID FROM WCPRDDB1.dbo.CardiacWaitListEntry AS CWLE WHERE (CWLE.WaitlistEntryID = ? AND CWLE.WaitlistEntryID = ?) [1, 4]

Reason being that sometimes I want to get query from peewee and run it in db management tool, all
these extra Parenthesis makes your eyes bleeds :)

**Comment by coleifer** [comment]
Sorry, you'll need to write a tool to strip them out or extend the QueryCompiler class.
