### ISSUE TITLE
peewee-versioned 0.1

### ISSUE THREAD

**Issue by kramer65** [coleifer/peewee#927]
Hi @coleifer - after using the code in our own website for a little while I've now released the code for peewee versioned on my github account here: https://github.com/kramer65/peewee-versioned

It would be great if you can have a look at it and possibly test it. I'd appreciate feedback on how to usage works now and how we can make that more intuitive.

And of course feel free to link to it from the peewee docs. Other people might find this useful as well. :-)

**Comment by coleifer** [comment]
Looks nice! I'll leave it to Google to help people find your project but if someone should ask about similar work I'll certainly keep this in mind. I'm kind of curious how foreign keys / referential integrity works when you delete a model but older versions of another table relate to the now-deleted object. There are maybe some edge cases? It also looks like there are gaps in the valid_from / valid_until that probably shouldn't be there... Other than that, though looks good!
