### ISSUE TITLE
How to use "select distinct binary  content from table;" in peewee?

### ISSUE THREAD

**Issue by ladder1984** [coleifer/peewee#928]
How to use "select distinct binary  content from table;" in peewee? I want to use "binary" when "select distinct " .
What's more,I use peewee 2.6.4.

**Comment by coleifer** [comment]
You can do a couple things, but think the simplest would be something like:

```python
from peewee import *

MyModel.select(Clause(SQL('distinct binary'), MyModel.content))

# select distinct binary t1.content from ...
```

You may need to attach an alias to the clause so peewee knows what attribute the value belongs to:

`, MyModel.content).alias('content')`
