### ISSUE TITLE
pwiz fails to generate correct code: missing extension import.

### ISSUE THREAD

**Issue by james-lawrence** [coleifer/peewee#929]
if a table contains a json field, NameError: name 'JSONField' is not defined is raised.
pwiz should just include the import, it shouldn't generate code that doesn't work.

```
createdb
psql <<EOF
CREATE TABLE example (
  field1 json
);
EOF
python -m pwiz -e postgresql -u $USER $USER
```
generated the following code:
```
from peewee import *

database = PostgresqlDatabase('user', **{'user': 'user'})

class UnknownField(object):
    pass

class BaseModel(Model):
    class Meta:
        database = database

class Example(BaseModel):
    field1 = JSONField(null=True)

    class Meta:
        db_table = 'example'
```
generated code blows up on the JSONField()

**Comment by Prillan** [comment]
Not the author but I'll answer anyways.

`JSONField` is contained in `playhouse.postgres_ext` so you need another import, i.e

```
from peewee import *
from playhouse.postgres_ext import JSONField # <----------

database = PostgresqlDatabase('user', **{'user': 'user'})

class UnknownField(object):
    pass

class BaseModel(Model):
    class Meta:
        database = database

class Example(BaseModel):
    field1 = JSONField(null=True)

    class Meta:
        db_table = 'example'
```

See http://peewee.readthedocs.io/en/latest/peewee/playhouse.html#postgresql-extensions

**Comment by james-lawrence** [comment]
I'm well aware of the fix and how to fix it. my point is if pwiz is going to generate this code it should generate it correctly. i.e.) it includes the required import automatically.

**Comment by Prillan** [comment]
Oh, sorry, didn't realize that all of it was generated.
