### ISSUE TITLE
Id field is not created with AUTOINCREMENT

### ISSUE THREAD

**Issue by mamcx** [coleifer/peewee#934]
I have a normal model and the tables have the ID marked as not AUTOINCREMENT.

This is the code:

```python
class BaseModel(Model):
    class Meta:
        database = db

class Cobro(BaseModel):
    nombre = CharField()
```

```sql
CREATE TABLE "cobro"(
	"id"     Integer NOT NULL PRIMARY KEY,
	"nombre" Text NOT NULL )
```

**Comment by coleifer** [comment]
It appears you are using Sqlite. Please read http://sqlite.org/autoinc.html for an explanation why this is not the default behavior. If you want autoincrement with Sqlite, you can use http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#PrimaryKeyAutoIncrementField
