### ISSUE TITLE
Postgres syntax error while using db.execute_sql

### ISSUE THREAD

**Issue by hkarasek** [coleifer/peewee#936]
I have problem with the ' (single quote) in SQL query when passing arguments. I am doing something wrong or it's a bug? 

### Reproducer:

```python
import peewee as pw

EVENTS_TABLE_PREFIX = 'events_'

db = pw.PostgresqlDatabase('events_api', user='test', password='passwd', host='localhost')
sql = 'CREATE TABLE %s (id SERIAL PRIMARY KEY);'

db.execute_sql(sql, ['test42'])
```

### Raises:
```
Traceback (most recent call last):
  File "/home/hkar/.virtualenvs/events_api/lib/python3.5/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.ProgrammingError: syntax error at or near "'test42'"
LINE 1: CREATE TABLE 'test42' (id SERIAL PRIMARY KEY);
                     ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "peewee_bug.py", line 8, in <module>
    db.execute_sql(sql, ['test42'])
  File "/home/hkar/.virtualenvs/events_api/lib/python3.5/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/hkar/.virtualenvs/events_api/lib/python3.5/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/hkar/.virtualenvs/events_api/lib/python3.5/site-packages/peewee.py", line 127, in reraise
    raise value.with_traceback(tb)
  File "/home/hkar/.virtualenvs/events_api/lib/python3.5/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: syntax error at or near "'test42'"
LINE 1: CREATE TABLE 'test42' (id SERIAL PRIMARY KEY);
```

### Environment
Ubuntu 16.04
python 3.5.1
python modules:

ecdsa==0.13
falcon==1.0.0
future==0.15.2
gunicorn==19.5.0
jsonschema==2.5.1
peewee==2.8.1
psycopg2==2.6.1
pycrypto==2.6.1
python-jose==0.6.1
python-mimeparse==1.5.2
simplejson==3.8.2
six==1.10.0

**Comment by coleifer** [comment]
Where are the single-quotes coming from? I'm kinda confused.

**Comment by coleifer** [comment]
There are a few weird things going on in the code you shared:

* Parameterizing the table name: typically you don't want to parameterize things like table names or other things that exist as part of the schema...it's more for external data.
* Postgres uses double-quotes for columns, tables, etc. Single quotes are used for string data.
* Any reason not to define a database model, or are you just using peewee for low-level database access?

To answer your question, though, you should just write:

```python
sql = 'CREATE TABLE "test42" (id SERIAL PRIMARY KEY);'
db.execute_sql(sql)
```

If the table name is coming from an untrusted source (i.e. not hard-coded into your application) then this stackoverflow answer might be helpful:

http://stackoverflow.com/questions/13793399/passing-table-name-as-a-parameter-in-psycopg2
