### ISSUE TITLE
Pass through field default values to SQL schema, or allow explicit creation of default values in model Meta class

### ISSUE THREAD

**Issue by bcattle** [coleifer/peewee#940]
Currently you can specify a model field's default value like 

    new_users = peewee.IntegerField(default=0)

Currently this default is applied at the application level, in the [`add_field`](https://github.com/coleifer/peewee/blob/master/peewee.py#L4304) method of the ModelOptions class. 

It would be nice if this definition were passed through to the underlying SQL schema. So, when the table is created, a SQL statement of the form 

    CREATE TABLE "stats" (
        "new_users" INTEGER NOT NULL DEFAULT 0, 
    )

Is generated. This seems more consistent with how the `null=True` attribute produces SQL with the `NULL` attribute set appropriately. 

Since you can specify any Python callable for the `default=` value, either the calllable would be called once when the module is loaded, or you could use a syntax like the current `Check('price < 10000')` syntax to pass through a SQL string. This would allow you to use a sequence, etc. as a field default value. For example:

    new_users = peewee.IntegerField(default=Default('nextval('user_no_seq')'))

**Comment by bcattle** [comment]
Oh, I see you can already do this. From the [docs](http://docs.peewee-orm.com/en/latest/peewee/models.html#default-field-values): 

> The database can also provide the default value for a field. While peewee does not explicitly provide an API for setting a server-side default value, you can use the constraints parameter to specify the server default:
> 
>     class Message(Model):
>         context = TextField()
>         timestamp = DateTimeField(constraints=[SQL('DEFAULT CURRENT_TIMESTAMP')])

Nice!

**Comment by coleifer** [comment]
Yep! Thanks for checking the docs!
