### ISSUE TITLE
"is_null" and  ">> None" operator  is parsed as "IS None" instead of  "IS NULL"

### ISSUE THREAD

**Issue by iraklikhitarishvili** [coleifer/peewee#941]
`column_name.is_null(True)` and `column_name >> None` expressions in `where` clause are returning `WHERE column_name IS None` in postgresql query.
i think just changing  [`db_value`](https://github.com/coleifer/peewee/blob/master/peewee.py#L928) to
```python
  def db_value(self, value):
        """Convert the python value for storage in the database."""
        return 'NULL' if value is None else self.coerce(value)
```
will help
p.s i was using models translated from django

**Comment by coleifer** [comment]
Since the value is parameterized, it will go in as the string 'NULL'.

**Comment by iraklikhitarishvili** [comment]
thank you very mach. you are right. issue was that i tried to run it with `django_model.objects.raw(sql_query,params)` and django putted `None` from `params` as `None` instead of `NULL`.
