### ISSUE TITLE
first() should set a `LIMIT 1`

### ISSUE THREAD

**Issue by keredson** [coleifer/peewee#959]
when looking at https://github.com/coleifer/peewee/issues/958, i noticed:

```python
class Person(pw.Model):
  name = pw.CharField()
  class Meta:
    database = db

alice = Person.create(name='Alice')
print Person.select().where(Person.name=='Alice').first()
```

generates this sql:

```sql
SELECT "t1"."id", "t1"."name" FROM "person" AS t1 WHERE ("t1"."name" = ?)
```

why would this not set a `LIMIT 1`?  even if the library code stops the underlying sql lib's iteration it's likely already transferred way more data than that.  (psql's default is 1000 rows at a time IIRC)

**Comment by coleifer** [comment]
It is a design decision...and documented. Seriously what is wrong with you.

http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectQuery.first

**Comment by keredson** [comment]
> Seriously what is wrong with you.

i don't see the utility of your personal attacks here.

maybe it was a design decision, maybe it was a post-hoc justification of an unintentional implementation quirk, it's impossible for me to tell.  either way "caching the entire result set when the user asked for the first record because they *might* want more later" is a weak argument for such surprising behavior.  is questioning that choice (regardless of how you got there) not legitimate in your mind?

**Comment by vkhvst** [comment]
@keredson makes a reasonable argument for setting `limit 1` especially because the result set can be very large. Maybe the caching can be moved to a different method where that behavior is expected or more intuitive

**Comment by arikfr** [comment]
To be honest, I find this behavior surprising too. It's true the documentation mentions this, but maybe it's worth putting a clearer message about this. @coleifer would you mind a pull request with this kind of update to the documentation?

**Comment by keredson** [comment]
just to be clear, i'm not advocating changing this behavior in a point release or anything.  but if a major 3.0 rewrite is in the works (which @coleifer has already indicated would be API changing), that seems like a reasonable opportunity.  (*possibly* in v2.9 if there was a clear consensus, or some version of `from peewee.__future__ import first`, or any number of other obvious options, but all that discussion seems secondary to "is this a good idea at all?")

perhaps a better name for the existing behavior would be `peek()`?

**Comment by coleifer** [comment]
Context of my earlier comment... https://github.com/coleifer/peewee/issues/958#issuecomment-223492592

At any rate, I think the documentation should be more clear and would accept a PR or can just type it up real quick either way.

Regarding changing the semantics, I don't feel that is necessary since .get() already has the semantics you're looking for. I believe the reason I left .first() as it is, is so that multiple calls to .first() do not necessarily result in multiple queries, as they would with .get().

**Comment by keredson** [comment]
> I believe the reason I left .first() as it is, is so that multiple calls to .first() do not necessarily result in multiple queries

yeah, i just noticed that myself.  that should also probably be added to the documentation, as most of the rest of the API is non-caching.  (i'd argue that caching the results is something that should be done very sparingly, as the user can easily do it themselves by wrapping w/ `list()`, etc.)

**Comment by coleifer** [comment]
It is done sparingly.

**Comment by arikfr** [comment]
> I don't feel that is necessary since .get() already has the semantics
you're looking for

Not exactly. get() throws an exception if no value is found while first()
returns None.

**Comment by coleifer** [comment]
That's correct -- I should have been more clear -- I just meant that `.get()` applies a LIMIT and will either return a record or raise an exception. It'd of course be easy to add a wrapper to your own implementation:

```python
class MyModel(Model):
    @classmethod
    def get_or_none(cls, *query):
        try:
            return cls.get(*query)
        except cls.DoesNotExist:
            pass
```

**Comment by keredson** [comment]
> It'd of course be easy to add a wrapper to your own implementation:

if i did this, does it work generally, or just on the base model class?  can i do `MyModel.select().where(something).get_or_none()` just by defining this method?

**Comment by coleifer** [comment]
wow, that's something you can probably type into a python console and try out.

**Comment by coleifer** [comment]
And regarding the second part of the question, no unfortunately, you would need to modify the select query class in that case.

**Comment by keredson** [comment]
> wow, that's something you can probably type into a python console and try out.

ironically, i meant it as a compliment.  i assumed it did, otherwise your suggestion would make no sense.  i was expecting a response along the lines of "yep!  pretty cool, eh?"  but you're right, it can't.

```python
class Person(pw.Model):
  name = pw.CharField()
  class Meta:
    database = db
  @classmethod
  def get_or_none(cls, *query):
      try:
          return cls.get(*query)
      except cls.DoesNotExist:
          pass

print Person.get_or_none(Person.name=="derek")
print Person.select().where(Person.name=="derek").get_or_none()
```

```
$ python test2.py
None
Traceback (most recent call last):
  File "test2.py", line 34, in <module>
    print Person.select().where(Person.name=="derek").get_or_none()
AttributeError: 'SelectQuery' object has no attribute 'get_or_none'
```

that's pretty useless in this context.

**Comment by coleifer** [comment]
Well, typically you call `.get()` from the context of a model instance, so adding the classmethod to the model class should cover you.

```python
In [1]: db = SqliteDatabase(':memory:')

In [2]: class Base(Model):
   ...:     class Meta:
   ...:         database = db
   ...:     @classmethod
   ...:     def get_or_none(cls, *query):
   ...:         try:
   ...:             return cls.get(*query)
   ...:         except cls.DoesNotExist:
   ...:             pass
   ...:         

In [3]: class Person(Base):
   ...:     name = CharField()
   ...:     

In [4]: Person.create_table()

In [5]: Person.create(name='charlie')
Out[5]: <__main__.Person at 0x7fa54d378810>

In [6]: Person.get_or_none(Person.name == 'charlie').name
Out[6]: u'charlie'

In [7]: Person.get_or_none(Person.name == 'nobody')

```

**Comment by keredson** [comment]
it's much more common to do `Class.ALL.join(x).join(y).get(unique_condition)`.  honestly i'm *rarely* just getting one row by itself.

**Comment by coleifer** [comment]
Wait, huh?

**Comment by keredson** [comment]
> Wait, huh?

I mean:

I rarely need to do: `Person.get(condition)` or `.first()` or any of those top level terminating methods on the models just by themselves.  (Which is the only circumstance under which your `get_or_none` suggestion is useful.)

Almost always I'm getting an object with some subset of it's related objects through some sort of join API.

This is exceedingly common in my experience for any non-trivial app.  Which is why the usability of the join API is so important in an ORM.  Even minor (or seemingly trivial) improvements have large scale effects when they're in APIs you're using all day every day, multiplied by the number of developers in your organization.  If I seem passionate about what seem to you like minor "that at most just saves a few seconds" style issues this is why.  I'm looking at the aggregate.

**Comment by coleifer** [comment]
I didn't mean tell me your life story dude

**Comment by harry91** [comment]
@coleifer I really don't think @keredson was rude in the first message.
