### ISSUE TITLE
consider exposing transaction isolation levels

### ISSUE THREAD

**Issue by keredson** [coleifer/peewee#979]
for databases that support them.  (we use `Serializable` occasionally.)  i can't find any support for this in the docs.

**Comment by coleifer** [comment]
You can always subclass the database class and provide your own transaction context manager, or set this on the connection by using the get_conn() method.

**Comment by keredson** [comment]
Or there could be an optional keyword argument on the transaction method!  That seems way easier for the user.  What's the point of a database API if not to normalize/simplify accessing the database in ways common to all apps?

**Comment by coleifer** [comment]
I'll just repeat myself:

> You can always subclass the database class and provide your own transaction context manager

**Comment by keredson** [comment]
i can also just use `psycopg2`, or parse the output of `psql -c`, or any number of other options.  but none of those are really good suggestions, and you seem to be missing the point.  what i'm looking for is an open discussion (with you or others) on the merits of the feature.

you've closed this without specify what your objection is.  is it possibly one of:
- database isolation levels aren't a commonly enough used feature of databases?
- it would be technically difficult to implement?
- you don't see how this could be backwards compatible with the existing api?
- you think it's a decent idea, but don't have time to implement it yourself?
- just NIH?

**Comment by coleifer** [comment]
I'll just repeat myself:

> You can always subclass the database class and provide your own transaction context manager

**Comment by coleifer** [comment]
And for good measure, to your next response I also will say:

I'll just repeat myself:

> You can always subclass the database class and provide your own transaction context manager
