### ISSUE TITLE
Index Creation in Postgresql, create_indexes

### ISSUE THREAD

**Issue by mlag** [coleifer/peewee#989]
The first version doesn't work, i.e. creates the table but fails to create an index in postgresql.
```
db = PostgresqlDatabase()
class TestTable(Model):
    class Meta:
        database = db
    id = PrimaryKeyField()
    name = CharField(index=True)
```
whereas the following works: `db.create_indexes(TestTable, ['name'])`

peewee 2.8.1 from pip

**Comment by coleifer** [comment]
I think the "first version" you referred to is missing from the comment. I see your table definition and that calling `db.create_indexes()` creates the indexes, but not the part that may not have been working?

**Comment by mlag** [comment]
Sorry, nevermind.
After having unrelatedly restarted postgres, it works.
What I meant was, that calling `create_tables()` only created the table, but not the index for the `name` field. I had to call `create_indexes()` separately.

**Comment by coleifer** [comment]
Cool, glad to hear it's working correctly! Thanks for the update.
