### ISSUE TITLE
bring select.get() into parity with model.get()

### ISSUE THREAD

**Issue by keredson** [coleifer/peewee#993]
currently this is allowed:

```python
u = User.get(User.id==1)
```

and this is allowed
```python
u = User.select().where(User.id==1).get()
```

but this is not:

```python
u = User.select().get(User.id==1)
```

impl the last option.  (ie make it identical to the middle option just like the first option is)

**Comment by coleifer** [comment]
I would appreciate it if you respected my request that you not post things on my project.

You have your own fork, please use it.

**Comment by keredson** [comment]
i'm sorry, but you don't own github.  i'm allowed to discuss this project with other users/devs (just like anyone else).  you don't have to be involved in that discussion.

**Comment by coleifer** [comment]
> i'm sorry, but you don't own github. i'm allowed to discuss this project with other users/devs (just like anyone else). you don't have to be involved in that discussion.

Do you have so little respect for my feelings and the work that I've done to create this project and community?

**Comment by coleifer** [comment]
Here's the situation: I have been working on this project since 2010. It is a project that I am passionate about and I have worked very hard to build and support the community of people who use and contribute to the project. If you've seen my project, you'll see that I have a number of pretty popular projects.

In the almost 7 years I've been using GitHub, I have not had anyone show so much disregard for my feelings or my work. I think it comes down to the fact that most people understand that "peewee" only exists because someone made it and wants to share it with other people. They recognize, in other words, that Peewee is a labor of love.

You are the only person in all this time who has showed so much disregard for all the years I've worked to build this project into what you see today.

**Comment by keredson** [comment]
> Do you have so little respect for my feelings and the work that I've done to create this project and community?

i have a ton of respect for it!  i've said that many times!  i don't use / develop-on software i don't like!  heck, i'm switching my entire company to it!  it's a great project!  why on earth else would i be spending any time here?

what i don't have respect for is your penchant for personal attacks when you disagree with someone, rather than debating the merits of one change or another.  or your habit of simply deleting entire technical discussions you didn't like the outcome of.  (it takes a long time to write all those little code examples explaining the need and impact of all these little changes.  having someone else wipe out hours of your work because of a baseless personal vendetta is highly annoying.)

but there isn't much i can do about it.  so i'm largely just choosing to ignore it.  still love the code tho.

**Comment by coleifer** [comment]
That's a misrepresentation.

I've said that your comments give off a really entitled vibe. Your issue titles and descriptions have been the same.

I have deleted your comments when:

1. I have closed the issue but you continue to comment.
2. The issue did not pertain to Peewee or the community.

That's it.

--------------------------------------------

This project is something I've worked very hard on. Please by all means continue to use it and work in your fork, but please **respect my wishes and refrain from commenting, creating tickets or posting here**.

**Comment by keredson** [comment]
that is patently false.  you've definitely deleted comments before issues were closed.  and you've not deleted other's comments after issues were closed where you've deleted mine.  (even when my comment was just "i agree w/ person XYZ").  i don't even know how many, as GH doesn't notify me when it happens, nor do i have any record of them (other than me luckily having left the browser open for that one screenshot)

besides, even the premise for your deletion is invalid.  where is there a rule of "you can't comment after an issue is closed"?  where else would one ever say "IMO this is still and issue and should be re-opened, because reason XYZ"?

> refrain from commenting, creating tickets or posting here.

sorry, but no.  if i have something to say that's respectful and on topic, i intend to reserve the right to say it.  freedom of speech and whatnot.

**Comment by arikfr** [comment]
Derek, you seem to misunderstand free speech or your rights on GitHub.

While I might not agree with Charles, I definitely think it is his right to
ask you not to post here.

**Comment by keredson** [comment]
@arikfr i respectfully disagree, for reasons that were just deleted by @coleifer, as i assume this will be in another few seconds.  :)

**Comment by coleifer** [comment]
What am I supposed to think, @keredson . You are a toxic presence on my project, and I don't want you to keep harassing me.

**Comment by coleifer** [comment]
Why can't you respect that, one person to another?

**Comment by keredson** [comment]
> You are a toxic presence on my project

you keep saying that, but you never present anything i've ever said or done as an example.  all i've ever done here is offer suggestions on how the API could be improved and offer PRs that implement those improvements.  (and complain when you delete comments detailing those suggestions or PRs)  i'd argue your selective editing of other people's respectfully stated opinions is the true toxic element here.

**Comment by keredson** [comment]
> Derek, you seem to misunderstand free speech

@arikfr fair enough, that was a little hyperbole.  but at the end of the day, reporting bugs and suggesting enhancements isn't an abuse of the GH community.  it's the entire point of it.
