### ISSUE TITLE
db.create_table does not create indexes

### ISSUE THREAD

**Issue by sin5** [coleifer/peewee#998]
class Client(peewee.Model):
    """
      UNIQUE KEY `rip_rport_stime` (`ip_type`, `remote_ip`, `remote_port`, `start_time`),
      KEY `app_stream_stime` (`app`, `stream`, `start_time`),
      KEY `app_stime` (`app`, `start_time`)
    """
    ip_type = UnsignedSmallIntegerField()
    app = UnsignedIntegerField()
    stream = UnsignedBigIntegerField()
    url = UnsignedIntegerField()
    start_time = UnsignedIntegerField()
    end_time = UnsignedIntegerField()
    remote_ip = UnsignedIntegerField()
    remote_port = UnsignedSmallIntegerField()
    local_ip = UnsignedIntegerField()
    local_port = UnsignedSmallIntegerField()

    class Meta:
        database = db
        indexes = [
            (('ip_type', 'remote_ip', 'remote_port', 'start_time'), True),
            (('app', 'stream', 'start_time'), False),
            (('app', 'start_time'), False),
        ]

Client.create_table(fail_silently=True) # this create the right indexes
db.create_table(Client, safe=True) # but this can't

is it a bug? or i missed the doc?

**Comment by coleifer** [comment]
Hey @sin5 - can you please take the 5 extra seconds and learn how to format your code? Did you even look at your issue after creating it?

**Comment by coleifer** [comment]
Please read the documentation on submitting bugs: http://docs.peewee-orm.com/en/latest/peewee/contributing.html#bugs

Here's a link to GitHub's documentation:

https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

**Comment by coleifer** [comment]
Specifically, though, and this is a bad API -- I will be addressing it in a subsequent release -- calling `database.create_table` will *only* create the table. Calling `Model.create_table()`, on the other hand, will create the table and the indexes.

However,

To create multiple tables, and their indexes, with the dependency graph resolved to ensure the tables are created in the proper order, use the `Database.create_tables()` method.

In fact, I pretty much just recommend that people **always** use `database.create_tables([AModel, AnotherModel])`.

**Comment by coleifer** [comment]
Also read the big fat warning in the docs:

http://docs.peewee-orm.com/en/latest/peewee/api.html#Database.create_table

**Comment by sin5** [comment]
sorry for my code format. and thanks for your answer：）

**Comment by coleifer** [comment]
No probs!
