### ISSUE TITLE
Support cockroachdb?

### ISSUE THREAD

**Issue by jet10000** [coleifer/peewee#999]
https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/

**Comment by coleifer** [comment]
[From one of their devs](https://github.com/cockroachdb/cockroachdb-python/issues/21#issuecomment-229755195),

> Cockroach actually supports the Postgres wire protocol, so the Postgres driver builtin to Peewee should work (we support psycopg2 without issue). That said, we have found that a few drivers use some Postgres-specific SQL extensions (for instance, use of pg_catalog instead of the standard information_schema), so current levels of support for them vary.

This means that peewee, configured with a modified version of the `PostgresqlDatabase`, should be able to work with Cockroach -- at least in some sense.

Going to close this out as I do not plan on implementing support myself.

Those interested can also follow along here:

https://github.com/cockroachdb/cockroachdb-python/issues/21
